### ISSUE TITLE
Problema instalando PyQt4 en Mac OSX

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233-2016-02/Syllabus#1]
Hola! 
Al copiar y pegar ”brew install pyqt --with-python3” en Terminal, me aparece ”-bash: brew: command not found”. Ya instalé Python 3.5.2 y también las librerías ”pip3 install --upgrade simpy”,
”pip3 install --upgrade numpy” y ”pip3 install --upgrade matplotlib”, y no tuve ningún problema con eso.
Saludos!

**Comment by otro-felipe** [comment]
Para poder usar el comando brew debes instalar homebrew. Es recomendable que hayas instalado python con el mismo comando (`brew install python3`) de lo contrario la instalacion de pyqt usando brew no servirá.

Puedes ver [aquí](http://brew.sh/) cómo instalar homebrew.

**Comment by bedefrunner** [comment]
Muchas gracias!

**Comment by FranciscoLarach** [comment]
Si instalé python sin brew, y PyQt con brew ¿Debo desinstalar python y instalarlo con brew de nuevo?, por que al poner en Idle import PyQt4 me aparece que no encuentra el modulo, pero si uso python en terminal, no me lleva a ese error.

**Comment by jgmontoya** [comment]
Hola, 

Si escribes en ambos lo siguiente:

``` python
import sys
print(sys.version)
```

¿Es el output el mismo en ambos casos?

**Comment by tcgarrido** [comment]
Hola, tengo el mismo problema y el output es el mismo en ambos casos:

3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

**Comment by FranciscoLarach** [comment]
A mi me responde con 2 outputs diferentes, ¿ Es por que estoy usando 2 python distintos no? ¿que puedo hacer para que PyQt4 pueda ser leído por el python que acabo de instalar? ... Gracias!

**Comment by fringlesinthestreet** [comment]
Yo lo hice y parecía que se estaba instalando bien pero al final me tiró esto:

'Phonon support is broken.
Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed.'

Igual intenté importarlo y me tira el error de que el módulo no existe.. saben cómo agregar un PATH o qué hay que hacer :P. Gracias

**Comment by fgvenegas** [comment]
@FranciscoLarach estas seguro que tanto en el IDLE como en la terminal estas corriendo python 3.5?

**Comment by felipehv** [comment]
En el issue #5 dieron una solución!
