### ISSUE TITLE
no puedo hacer push 

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#10]
![captura de pantalla de 2016-08-03 18-47-46](https://cloud.githubusercontent.com/assets/20784195/17384539/e3dc27a4-59aa-11e6-9e7c-366b2981d4bb.png)

al ingresar usuario y conr¿traseña me dice que no tengo permisos. ¿Qué puedo hacer?

**Comment by tcgarrido** [comment]
Me pasa lo mismo :c

**Comment by andresbannuraschultz** [comment]
Quizas entendi mal, pero segun yo hay que crear un repositorio propio, no usar el que se creo para el curso (el Syllabus). Luego con ese repositorio propio hacer las cosas que piden en las instrucciones. Creo que el problema aqui es que no tenemos autorizacion para modificar el syllabus, y por lo tanto, no dejan hacer push. Es solo lo que creo, no soy ayudante!

**Comment by narierao** [comment]
un comentario a los ayudantes y que por favor hablen con coordinación. El archivo que nos subieron viene muy mal explicado. Para las siguientes actividades, por favor que sean mejor explicadas. gracias

**Comment by tcgarrido** [comment]
@abannura seco!! ajajja ahora me funcionó, era eso 👍

**Comment by jtagle2** [comment]
Efectivamente, como dice @abannura, no tienen los permisos para hacer push en el Syllabus. Después tendrán sus repos privados en donde subirán sus soluciones.

**Comment by narierao** [comment]
@abannura muchas gracias! ahora puedo hacer push. Te lo agradezco.

**Comment by ivaniadg** [comment]
@narierao 
El material dice que deben clonar _sus repos_ (el ejemplo está hecho con el syllabus). Estos todavía no se han creado pero estarán listos mañana por la mañana. 
Hay algo más que no entiendas?

**Comment by narierao** [comment]
@indonoso, todo claro. Muchas gracias.

**Comment by aaossa** [comment]
Pronto tendrán sus repos :D Por ahora creense uno para practicar :grin: , son gratis (?)
