### ISSUE TITLE
Convención utilizada en types.json

### ISSUE THREAD

**Issue by The-Big-Lebowski** [IIC2233-2016-02/Syllabus#100]
¿En el archivo/diccionario types.json los tipos de ataque son las keys o los values? Para distinguirlos del tipo del defensor.
Gracias

**Comment by fvr1** [comment]
#28

**Comment by jgmontoya** [comment]
Eso que preguntas está en el enunciado. De todas maneras te dejo un ejemplo:

```
"bug": {
      "psychic": 2.0,
      "fighting": 0.5,
      "ghost": 0.5,
      "fire": 0.5,
      "grass": 2.0,
      "dark": 2.0,
      "flying": 0.5,
      "poison": 0.5,
      "steel": 0.5
   }
```

Significa que un ataque de tipo "bug" le hará 0.5 el daño a un programón de tipo "fire".

Saludos!
