### ISSUE TITLE
Tienda de prograbolas

### ISSUE THREAD

**Issue by jbsaeza** [IIC2233-2016-02/Syllabus#102]
Una vez el usuario haya entrado a la tienda, le di la opción de comprar prograbolas o salir de la tienda, una vez que haya elegido la primera, le pregunto cuantas quiere, pero es necesario que en esta parte le ofrezca la opción de volver atrás?(una suerte de arrepentimiento del usuario)

**Comment by jgmontoya** [comment]
Sí.

Cito el enunciado:

> siempre se debe dar la opción de cancelar y volver un
> estado anterior en el menú de navegación

Saludos!
