### ISSUE TITLE
Stock gimnasio

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#104]
Si le gano a un entrenador y me voy del gimnasio, al volver al gimnasio, ¿debo volver a ganarle al entrenador derrotado?
Si por cualquier motivo estoy peleando por segunda vez contra un entrenador, sus programones, ¿son 'los mismos' (mismo iv, ev, etc)? 
Si le gano al líder, me gano la medalla, y me voy del gimnasio, al volver al gimnasio, ¿tiene entrenadores y líder para volver a pelear? Por pelear nada más, pues ya tengo esa medalla.

**Comment by jgmontoya** [comment]
Hola,

> Si le gano a un entrenador y me voy del gimnasio, al volver al gimnasio, ¿debo volver a ganarle al entrenador derrotado?

No

> Si por cualquier motivo estoy peleando por segunda vez contra un entrenador, sus programones, ¿son 'los mismos' (mismo iv, ev, etc)? 

Sí, de hecho son los mismos para los otros usuarios también

> Si le gano al líder, me gano la medalla, y me voy del gimnasio, al volver al gimnasio, ¿tiene entrenadores y líder para volver a pelear?

Queda a su criterio, deben explicitar su decisión en el readme.
Saludos!
