### ISSUE TITLE
Batallas por programon único

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#107]
Las batallas por usuario se deben desplegar al hacer la consulta respectiva.
Las batallas por tipo de programón se deben registrar para hacer las otras dos consultas respectivas.
Cumpliendo todo esto, ¿se espera que cada programón único tenga un registro de sus peleas?

**Comment by jgmontoya** [comment]
Ojo con la primera consulta:

>  Batalla por programón involucrado: Ingresando el nombre del programón, se deberá mostrar un resumen de todas las batallas en la que este se haya visto involucrado y el resultado de estas (ganador o perdedor). Tomar en cuenta si este fue un programón salvaje con el que se peleó, un programón de algún entrenador (en caso de esto, indicar el entrenador), o propio del entrenador. Indicar su contrincante y resultado.

Para esta vas a necesitar guardar la información individual de las batallas.

**Comment by cjgazali** [comment]
No estoy de acuerdo. Ahí dice que se ingresa nombre. Hay muchos 'Charmander', por lo tanto si nos piden un nombre es porque se busca en las batallas por tipo de programón, es decir, tipo 'Charmander', y todos los 'Charmander' cuentan. Corrígeme si me equivoco.

**Comment by jgmontoya** [comment]
El tema relevante es la segunda parte:

>  Tomar en cuenta si este fue un programón salvaje con el que se peleó, un programón de algún entrenador (en caso de esto, indicar el entrenador), o propio del entrenador. Indicar su contrincante y resultado.

La forma de guardar esta información queda a tu criterio, sin embargo la información debe estar.

**Comment by iqacevedo** [comment]
Hola me acabo de dar cuenta que no sé si entendí bien esta parte del enunciado.
¿Con esto se refiere a que debo mostrar, por ejemplo, 10 victorias de charmanders si es que 10 charmanders sálvajes me vencieron? O en el mismo ejemplo debería mostrar solo las batallas perdidas para cada programon que fue derrotado (Y no mostrar las victorias de los charmanders)?
Saludos.
@flobarrios o @jgmontoya ayuda porfis

**Comment by iqacevedo** [comment]
Por favor algún ayudante de buen corazón podría aclararme mi duda :) 
Saludos!

**Comment by jgmontoya** [comment]
Si buscas por charmander, deberá aparecer un resumen de todas las batallas en la que este se haya visto involucrado y el resultado de estas (ganador o perdedor).  Además debes indicar para cada programon en cada batalla si corresponde a un programón salvaje, un programón de algún entrenador (en caso de esto, indicar el entrenador), o propio del jugador.

Saludos!

**Comment by iqacevedo** [comment]
Gracias !
