### ISSUE TITLE
Menú de consultas

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-02/Syllabus#108]
Hola !
En la opción de las consultas, el ítem de Batallas por Programon y Ranking de Programones; es sobre la sesión del jugador que esta jugando actualmente, o todas las sesiones ?

(Ej: En el sistema han jugado 3 jugadores, entonces podría mostrar el ranking de los mejores programones que han peleado en las 3 sesiones)

**Comment by jtagle2** [comment]
Hola
#45
Saludos!

**Comment by Iruretagoyena** [comment]
Mis disculpas
