### ISSUE TITLE
ID entrenadores

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#109]
Como hay entrenadores con el mismo nombre como podremos distinguirlos? Recomiendan crearles id unicos?

**Comment by flobarrios** [comment]
Hola! queda a tu criterio como los diferencias y lo que propones es una opción válida. También se podrían diferenciar por gimnasio, si es líder o entrenador normal, etc. Saludos!

**Comment by andresbannuraschultz** [comment]
En un principio hice eso pero dentro de un mismo gimnasio hay entrenadores (no lider) que se llaman igual. Los estaba diferenciando por nombre hasta que me di cuenta de esto. Si no es creandoles un id, no se me ocurre como diferenciarlos, a menos que cambie el formato de como se entrega la infromacion de los gimnasios (ya sea agregando ahi el id de cada entrenador o asegurandose que los nombres sean todos distintos para usarlos a modo de identificacion).

**Comment by flobarrios** [comment]
Puedes agregarles un id!
