### ISSUE TITLE
Ejercicio Trabajar en equipo

### ISSUE THREAD

**Issue by tcgarrido** [IIC2233-2016-02/Syllabus#11]
Hola, no entiendo donde ver el README.md que dice "Todavía no has pasado la prueba de trabajo en equipo". O eso debe estar en el repo que subirán más tarde? 

Gracias

**Comment by aaossa** [comment]
Holaaa, lo que pasa es que el ayudante que debe crear los repos no está trabajando muy responsablemente, por lo que aún no tienen sus repos privados. Un par de latigazos al responsable y cuando estén listos los repos podremos hacer ese ejercicio :D

**Comment by aaossa** [comment]
Bueno, ya mandamos a trabajar al encargado de los repos (era yo, ups). La prueba de equipo era una actividad que hicimos el semestre pasado para que tuvieran que hacer pull, pero ahora lo hicimos en esta AC, la AC00. Cerraré la issue pero si tienes alguna duda o tienes algun comentario de la "prueba de trabajo en equipo" hazlo por aquí :grin:
