### ISSUE TITLE
Programones en Equipo y en Pc de Bastian

### ISSUE THREAD

**Issue by lefischer** [IIC2233-2016-02/Syllabus#111]
Hola,

El programon que uno escoge en el inicio se incluye en el Pc de Bastian. Si no se incluye, entonces hay que asumir que ese programon nunca puede salir de Equipo. (cuando uno va al centro programon)

**Comment by flobarrios** [comment]
Hola! debes incluirlo ya que el inicial si puede salir del equipo. Saludos!
