### ISSUE TITLE
¿Los programones mueren?

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#114]
Cuando un programon propio llega a hp cero, es decir, es derrotado, ¿se "muere"? ¿Lo perdemos, o también se deben resetear sus stats a como estaban antes de la batalla simplemente? Lo mismo para los entrenadores; programon derrotado, ¿lo pierde para siempre?
En el enunciado dice que al terminar la batalla todos los programones que salieron de la prograbola suben un nivel. ¿Eso también vale para los programones que fueron derrotados o solo los que quedaron vivos?

**Comment by flobarrios** [comment]
Hola!! Las stats de todos los programones se resetean (aun cuando llegaron a hp 0). Saludos

**Comment by jtagle2** [comment]
Respecto a los niveles, se respondió en #61
Saludos!
