### ISSUE TITLE
Datos programones en batalla

### ISSUE THREAD

**Issue by lefischer** [IIC2233-2016-02/Syllabus#115]
Hola,

En una batalla :
que datos del programon del usuario se deben mostar?
que datos de un programon salvaje se deben mostrar?
que datos de un programon de un entrenador se deben mostrar?

**Comment by Hernan4444** [comment]
Ante un programon salvaje o de un entrenador se debe mostrar:
- Hp del programon
- Nivel del programon
- Nombre del programon

Los datos del progamon  del ususario a mostrar son:
- Hp del programon
- Nivel del programon
- Nombre del programon
- Movimientos con sus pp correspondientes

Saludos!

**Comment by cjgazali** [comment]
Favor de hacer enunciados completos para la próxima vez. Es una tortura leer estos issues.
