### ISSUE TITLE
Reset stats batalla salvaje

### ISSUE THREAD

**Issue by asimonv** [IIC2233-2016-02/Syllabus#116]
Qué pasa cuando me escapo de una batalla con un programon salvaje? Igual se reinician los stats?

edit: también se resetean los stats del programon capturado?

**Comment by alainrochette** [comment]
+1 Si arranco de una batalla salvaje todavía se agrega a mi lista de "batallas"?

**Comment by FernandoPieressa** [comment]
Si, se recuperan los stats de los pokemones sin importar el resultado de la batalla.

Saludos!

**Comment by asimonv** [comment]
Gracias!
