### ISSUE TITLE
Cuando un programon evoluciona

### ISSUE THREAD

**Issue by asimonv** [IIC2233-2016-02/Syllabus#117]
Se reinician sus stats?

**Comment by cglevican** [comment]
Hola yo tengo otra duda, si el nuevo programon comienza con evolveLevel del programon que evoluciono.

**Comment by iqacevedo** [comment]
Hola 
Según lo que entendí yo:
1-cuando un programon evoluciona se actualizan sus stats ya que cambian las stats base de este. 
2-el programon cuando evoluciona debería quedar con el evolLevel (que debería ser el mismo que el nivel del programon que evoluciona)

**Comment by flobarrios** [comment]
Hola!! @iqacevedo estas en lo correcto !! Eso debe pasar. Saludos!

**Comment by asimonv** [comment]
Gracias!
