### ISSUE TITLE
Batalla en gimnasios

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2233-2016-02/Syllabus#119]
Hola, cuando mato a un entrenador en un gimnasio los pokemones suben de nivel ? O al final cuando mato a todos los entrenadores y al lider?

**Comment by flobarrios** [comment]
hola! después de cada batalla (de cada entrenador o líder). Saludos!

**Comment by NicolasAguirre** [comment]
Mi duda es que si es asi, seria muy facil ganar debido a que cuando evolucionan el hp se reinicia o me equivoco? Gracias

**Comment by asimonv** [comment]
No debería ser cada vez que se vence a un programon? En el enunciado dice que es después de cada "batalla", también incluyendo a los salvajes, por lo que se entiende como "batalla", la que involucra programones vs programones, no entre entrenadores necesariamente. Estoy mal? jaja

**Comment by nrfreudenberg** [comment]
@NicolasAguirre El hp se reinicia después de cada batalla, independiente de si subes de nivel o no, es decir, no importa si ganas o pierdes la batalla, la próxima vez que debas luchar, el hp de cada programon del equipo debe estar al máximo.

@asimonv No entendí muy bien lo que quisiste decir, de todos modos en el enunciado dice que una batalla termina cuando todos los programones enemigos (o propios) ya no tienen hp o movimientos para seguir luchando.

**Comment by flobarrios** [comment]
@nrfreudenberg exacto!

**Comment by asimonv** [comment]
@nrfreudenberg me refiero que si un entrenador de gimnasio tiene 5 programones, entonces son 5 batallas. 1 programon salvaje es 1 batalla.

**Comment by iqacevedo** [comment]
@asimonv según entiendo, contra un entrenador de gimnasio, la batalla se considera pelear con esos 5 programones (sería una batalla, no 5). Y en las sálvajes es tal como dices, un programon salvaje es una batalla.
Saludos

**Comment by jgmontoya** [comment]
Una batalla se considera contra _todos_ los programones del equipo enemigo, ocurre que el 'equipo' en caso de programón salvaje es solo ese programón.

**Comment by asimonv** [comment]
@jgmontoya puedo dejarlo como expliqué? Para mi tiene más sentido que cada programon gane exp cuando le gana a otro, en vez de que gane experiencia por derrotar a un entrenador, porque es como si el usuario ganara experiencia, no el programon. Lo especificaría en el readme.

**Comment by flobarrios** [comment]
Si!

**Comment by jgmontoya** [comment]
@asimonv No puedes hacerlo así, debe ser por **batalla** y no por programón. Esto es un poco distinto al juego porque se simplificó a propósito el tema de las curvas de experiencia.

Saludos!
