### ISSUE TITLE
Programones en Consultas/Jugador

### ISSUE THREAD

**Issue by iqacevedo** [IIC2233-2016-02/Syllabus#120]
Hola, 
Para la parte de las consultas, cuando se muestran los datos de un jugador, es necesario mostrar los programones del equipo y pc de bastian, o solo los programones del equipo?.

Saludos.

**Comment by iqacevedo** [comment]
Porfavor, que es una de las cosas que me faltan para terminar la tarea.

Saludos.

**Comment by mjjunemann** [comment]
Todos los programones que posea , si quieres agregar si son parte de su equipo o estan en el pc bienvenido sea

> ... dinero, programones con sus niveles con sus
> stats respectivos, .. 

Suerte.

**Comment by iqacevedo** [comment]
Muchas gracias !!!!
