### ISSUE TITLE
Medallas archivo de prueba

### ISSUE THREAD

**Issue by asimonv** [IIC2233-2016-02/Syllabus#121]
Hice un json de medallas con la siguiente estructura:

{
        "city_id": 1,
        "name": "Earth Badge" 
}

pero solo tiene 8 medallas. Cuando usen su archivo de prueba, también tendrá 8 medallas? Las ciudades se llamarán igual que en el juego? O lo dejo con city_id no más?

**Comment by flobarrios** [comment]
Hola! no puedes asumir que la cantidad de ciudades serán 8 o que las ciudades se llamarán igual. Te sugiero generar de forma automática los nombres de las medallas. Por ejemplo, si la ciudad se llama _Vidrian City_, que la medalla se llame _Vidrian City Badge_ o si se llama _X City_, la medalla se llame _X City Badge_.

Saludos!

**Comment by asimonv** [comment]
Gracias!
