### ISSUE TITLE
HP:probabilidad capturar programón 

### ISSUE THREAD

**Issue by bvfernandez** [IIC2233-2016-02/Syllabus#122]
hola! no entiendo la diferencia que hay entre hp_total y el hp_actual que sale en la formula de la probabilidad de capturar a un programón.
Gracias :)

**Comment by jgmontoya** [comment]
Hola,

hp_actual son los puntos de salud considerando el daño recibido en la batalla hasta ese momento mientras que hp_total son los puntos de salud máximo que tiene el programón en ese momento (Stat que depende del nivel, base, iv, etc..)
