### ISSUE TITLE
¿Qué pasa cuando a un jugador se le mueren todos los programones?

### ISSUE THREAD

**Issue by sormazabal** [IIC2233-2016-02/Syllabus#123]
Se acaba la batalla y el hp de mis programones se reestablece? O pierdo el juego y aparezco en el último spot donde grabé?

**Comment by nrfreudenberg** [comment]
![enunciadosobrebatallasperdidas](https://cloud.githubusercontent.com/assets/20805744/17910085/c826a0ee-695d-11e6-95c1-6dac25212373.PNG)

**Comment by sormazabal** [comment]
Gracias. Pero me refería a si el jugador se mantiene en el mismo spot de hierba o gimnasio donde perdió. O sí se quedaba sin Programones debía tirar algo así como "Game over" y salir del juego.

**Comment by flobarrios** [comment]
No, solo pierde la batalla y luego se restablecen sus stats. Queda en el mismo lugar 😄
