### ISSUE TITLE
Stats para un programon recién evolucionado

### ISSUE THREAD

**Issue by sfga** [IIC2233-2016-02/Syllabus#124]
Programón A evolucionó a Programón B en nivel 36: Los stats para B para nivel 36:

1: ¿son calculados en base a los stats de programón A en nivel 35?
2: ¿son los stats base del programón B?
3: ¿otra opción?

Gracias de antemano.

**Comment by vjbreton** [comment]
Según entiendo se calculan nuevamente los stats considerando  los stats base de la evolución. Por ej si tienes charmeleon 35 -> charizard 36 debes calcular los stats de charizard con su base correspondiente, no la base de la preevolución. Es normal que al evolucionar haya un salto en los stats de un pokemon.

**Comment by jgmontoya** [comment]
Es así como dice @vjbreton 

Cabe mencionar que no debes recalcular los iv y ev al evolucionar, sino que deben mantenerse iguales a los que tenía el programón antes de evolucionar.

**Comment by sfga** [comment]
Muchas gracias a ambos por la aclaración.
