### ISSUE TITLE
Aproximación de valor para stats calculados

### ISSUE THREAD

**Issue by sfga** [IIC2233-2016-02/Syllabus#125]
Para el cálculo de stats, ¿se permite la aproximación a entero para el valor final del stat calculado? (como ocurre normalmente en el juego original: solo HP's y Daños (reduccion de HP) como numeros enteros)

Gracias de antemano.

**Comment by jgmontoya** [comment]
Hola, 

Ya están en función piso en el enunciado, por lo que debieran ser enteros.

**Comment by sfga** [comment]
No vi la función piso para la expresión más grande (pensé que era un corchete para seccionar una expresión). Te pido disculpas por mi error y te agradezco por haber contestado.
