### ISSUE TITLE
iv y ev

### ISSUE THREAD

**Issue by smargozzini** [IIC2233-2016-02/Syllabus#126]
tres preguntas que no entiendo de estos datos
1- al entrar en batalla con un programon obtendremos estos valores, estos los usamos para cambiar los stats del programon rival también o este partirá la batalla con los base de ese programon?

2- al evolucionar un programon debemos cambiar sus stats con los mismo iv y ev que usamos al capturar su pre evolución?

3- el programon inicial parte con los stats base o también se generan estos valores aleatorios para cambiarle sus stats en ese momento?

gracias por las aclaraciones

**Comment by vjbreton** [comment]
1. Según entiendo, los stats de un pokemon siempre deben ser calculados mediante la fórmula del enunciado. Si esto es verdad debería calcular también los stats de los salvajes.
2. Creo que si.
3. También tienes que generarles iv y ev y calcular stats con estos.

Esto entiendo yo, no prometo nada.. jeje

**Comment by jgmontoya** [comment]
Hola, 
Es tal como lo dice @vjbreton 
1. Los stats de todos los programones del juego han de calcularse utilizando las fórmulas dadas.
2. Sí, tanto iv como ev se mantienen para un programón a lo largo del juego, incluso si evoluciona.
3. El programón inicial también tiene iv y ev al igual que todos los otros programones del juego.

Saludos!
