### ISSUE TITLE
[Tarea 1] Caminar/ciudad/menú

### ISSUE THREAD

**Issue by fipaniagua** [IIC2233-2016-02/Syllabus#127]
Cuando se llega a una ciudad, ¿tiene que estar implementada la opción "volver al menú" (para poder hacer consultas, salir del juego, etc)? si es así, entonces ¿que sucede si el jugador quiere entrar al gimnasio nuevamente  (debe avanzar y retroceder con la opción caminar)?

**Comment by flobarrios** [comment]
Hola! queda a tu criterio como resuelves eso en específico pero **debes** dar la opción de volver al menú (piensa que en algún momento vas a querer caminar de nuevo para salir de la ciudad). Una posible solución es que dentro del menú, tengas la opción de "volver al último lugar" o bien, se tenga que avanzar y retroceder con la opción caminar como tu señalas. 

Saludos!
