### ISSUE TITLE
Batalla terminada al quedar sin movimientos

### ISSUE THREAD

**Issue by nicovsj** [IIC2233-2016-02/Syllabus#128]
En el enunciado se especifica (a pesar de que es difícil que ocurra, creo) que si uno de los contrincantes se queda sin movimientos (AKA los pp's de cada programon del equipo llega a cero) la batalla se debe terminar. En este caso, quién es el ganador de la batalla? O lo dejo a mi criterio?

**Comment by flobarrios** [comment]
Pierde el que se queda sin movimientos. Tu pregunta es que pasa si los dos se quedan sin movimientos al mismo tiempo? Si es esa, eso no puede ocurrir ya que si o si uno se quedará sin movimientos antes (por el sistema de turnos). Saludos!

**Comment by nicovsj** [comment]
Muchas gracias. Mi pregunta era por si uno se quedaba sin movimientos, quizás un empate podría haber sido plausible. Cierro el issue.
