### ISSUE TITLE
Orden Ciudades

### ISSUE THREAD

**Issue by kcsss** [IIC2233-2016-02/Syllabus#129]
Con respecto a las ciudades, ¿el orden está bien ?. 
Según el enunciado, el primer líder es Giovanni con pokemones en nivel 40. 
Para el juego voy a dejarlo en este orden:
Pewter -> Cerulean -> Vermillion -> Celadon -> Fuchsia -> Saffron -> Cinnabar ->Viridian
Si pueden subir la versión final se los agradecería ... o corregirme.

XoXo.

**Comment by jgmontoya** [comment]
#121 #84 #66 #42 

En resumen: Tu programa debe funcionar con ciudades arbitrarias que se especifiquen en el json que tu programa cargará.

**Comment by kcsss** [comment]
<3
