### ISSUE TITLE
Ejercicio módulos

### ISSUE THREAD

**Issue by DiegoAndai** [IIC2233-2016-02/Syllabus#13]
Hola!, hoy en la ayudantía nos mostraron un ejercicio de módulos para hacer, sin embargo, no puedo encontrarlo en el repositorio. ¿Donde se encuentra?

De antemano gracias.

**Comment by aaossa** [comment]
Holaa, **subiremos todo mañana** :grin: Pero, ¿a qué ejercicio de módulos te refieres? Los ejercicios eran de PEP8 y modelamiento. ¿O estás pidiendo la diapo para poder recrear una estructura similar a la mostrada en ayudantía?

**Comment by DiegoAndai** [comment]
Perfecto :D me refería a un ejercicio de una biblioteca. Ahora que lo pienso creo que fue confusión mía que era de módulos. Tenía modelamiento, pero pensé que como lo habíamos pasado recién también podía tener trabajo con packages creados por nosotros.

Muchas gracias, cierro el issue.

**Comment by aaossa** [comment]
Dejaré la issue abierta para recordarme subir la ayudantía :smile: Cuando lo hagamos cerramos la issue :ok_hand:

**Comment by ivaniadg** [comment]
Hola! [En esta carpeta](https://github.com/IIC2233-2016-02/Syllabus/tree/master/Ayudantias/01-PasarElCurso) está el material de la ayudantía.

Saludos!
