### ISSUE TITLE
Problema con dictToJson

### ISSUE THREAD

**Issue by hanavarrete** [IIC2233-2016-02/Syllabus#130]
Al intentar guardar los datos de mi partida, me lanza un error de que un elemento en mi archivo jugadores (específicamente, una lista con programones)  "is not Json serializable". Ayura?

**Comment by flobarrios** [comment]
Hola! que le estas pasando al dictToJson ? si quieres haz push a tu repo y puedo cachar que esta pasando (pero dime donde esta el error). :D

**Comment by jtagle2** [comment]
Si tu lista es literalmente una lista con programones (una lista con instancias de programones), entonces el método te arrojará ese error, pues una instancia de una clase no es json serializable (Pickle incoming).
Revisa si estás haciendo eso.
Saludos

**Comment by hanavarrete** [comment]
Le acabo de hacer push!. En todo caso, si es una lista con instancias de programones :(. No hay manera de arreglar la clase de manera que si sea serializable?

**Comment by jtagle2** [comment]
@hanavarrete. entonces ese es el error. Y no, json no es capaz de serializar una clase. Lo que puedes hacer, es crear un método que retorne el diccionario que contiene la información del programón, y que sea eso lo que le entregas a dictToJson.
Saludos!

**Comment by hanavarrete** [comment]
buena, hice lo que me dijiste y funciona bien ahora. Gracias!
