### ISSUE TITLE
Tipos de pokemon en archivos prueba

### ISSUE THREAD

**Issue by Nebula2028** [IIC2233-2016-02/Syllabus#131]
Puedo asumir que los tipos seguirán siendo los 17 existentes? (normal, fightning, ghost, water, fire, etc... )

Es para "hardcodear" una parte del parser. Se que los pokemones, rutas, ciudades, movimientos y todo eso puede cambiar con los archivos que corrijan, pero los tipos puedo asumir que seguirán siendo esos?
O tiene que ser capaz de leer y funcionar con tipos inventados fuera de esos 17 ?

**Comment by flobarrios** [comment]
hola! no puedes asumir eso :( La idea es que no "harcodeen" ninguna parte del parser 😢. Saludos!
