### ISSUE TITLE
inicio batalla: eleccion de programones

### ISSUE THREAD

**Issue by bvfernandez** [IIC2233-2016-02/Syllabus#132]
Hola! tengo varias preguntas con respecto a las batallas.
En el enunciado dice que: "al iniciar una batalla, el programon más rapido será el que obtenga el primer ataque". 
1)Lo que entiendo de ahí es que si programon que usaré para la batalla es mas rapido que el programon contrincante, entonces tendré el primer turno (si no, al revés), está bien?

2) Además,no entiendo con qué criterio se elige el programon de mi equipo para iniciar la batalla:
 es el que sea más rapido o yo puedo elegir el programon para iniciarla?

3) "Más rapido" se refiere a el valor de velocidad base o a la actualizada?

Muchas graciaaaas :)

**Comment by flobarrios** [comment]
Hola!

1) Si, está bien.
2) Queda a tu criterio como eliges al programón para iniciar la batalla (puede ser random, según velocidad, etc).
3) Respecto a la velocidad del programón de acuerdo a su nivel (**NO** a la base).

Saludos!

**Comment by bvfernandez** [comment]
@flobarrios muchas graciaaaas!

otra pregunta cortita... el calculo de nuevos stats tambien se tienen q hacer cuando se inicia una batalla (o solo cuando se captura un programon o se aumenta de nivel?)

**Comment by flobarrios** [comment]
solo cuando se captura o aumenta de nivel pero en la batalla deben usar los stats acorde al nivel (los calculados) y no los base. Saludos!
