### ISSUE TITLE
perder en la hierba

### ISSUE THREAD

**Issue by Afalegria** [IIC2233-2016-02/Syllabus#133]
1 - Si pierdo una batalla en la hierba, pierdo los 100 de dinero también? o solo en los gym?
2 - Los pokemones en los gym tambien van subiendo de nivel con cada batalla? o son fijos ?

gracias :D

**Comment by flobarrios** [comment]
Hola!

1) Si, también pierdes 100 yenes.
2) No, no suben de nivel, son "estáticos". Pero, si quieres que sea más real, puedes hacerlo pero recuerda especificarlo en el README!

**Comment by Afalegria** [comment]
gracias ¡
Si capturo un pokemon salvaje en la hierba, cuenta como batalla ganada ? osea si es que gano los 200 yenes y si mis programones suban de nivel

**Comment by flobarrios** [comment]
#54
