### ISSUE TITLE
[Tarea 1] Ese momento que actualizas los json y ya nada funciona 

### ISSUE THREAD

**Issue by Kitaps** [IIC2233-2016-02/Syllabus#134]
Hola, lo que sale arriba
Y trato de hacerle pull al ultimo commit que hice y me dice que está up to date. 
También ya borre los archivos y aun así me dice que está up to date.

Como hago para volver a descargarlos.

La otra duda es, que tanto cambios se le han hecho a los .json?
Me tira errores críticos en los movimientos y en los Pokemon.

Gracias por el tiempo, sorry por el ranting

**Comment by flobarrios** [comment]
Hola! perdón pero no te entendí :(. Tienes problemas al hacer pull al syllabus ?  Que quieres volver a descargar? Los únicos cambios fueron de agregación (agregar programones y movimientos que faltaban), sobre la estructura no cambio nada por lo que no veo por que te esta tirando error. Trata de explicar mejor tu problema para ayudarte!

**Comment by Kitaps** [comment]
Hola, lo que pasa es que me surgieron dos problemas.

Bueno, recién solucione uno.

Lo otro es respecto a git. Lo que pasa es que ya digamos que deje todo mal. Pero había pusheado un commit en git cuando las cosas todavía funcionaban. 
Como hago para descargar las cosas como cuando aun estaba todo bien? 

Porque yo ahora aun que le haga git pull habiendo borrado todo, no me baja nada y me dice que está up to date.

**Comment by aaossa** [comment]
Prueba esto, pero **va a borrar tus cambios** que no estén en el repo remoto (vimos esto en la primera ayudantía)

```
git reset --hard HEAD
git clean -f -d
git pull
```

**Comment by Kitaps** [comment]
gracias
