### ISSUE TITLE
[Tarea 1] Entrenadores derrotados en gimnasio

### ISSUE THREAD

**Issue by gabrielpinkman** [IIC2233-2016-02/Syllabus#135]
Si por ejemplo juego en un gimnasio que tiene dos entrenadores antes de llegar donde el lider, y juego contra el primero y le gano, pero juego contra el segundo y pierdo; si llego a salir del gimnasio, cuando vuelva a entrar debo volver a batallar contra el entrenador que ya derroté?

**Comment by flobarrios** [comment]
#104
