### ISSUE TITLE
Stats

### ISSUE THREAD

**Issue by FranciscoLarach** [IIC2233-2016-02/Syllabus#136]
¿Es normal que al aplicar la formula de Stats y Hp, los outputs de estas funciones sean menores que los valores base?
¿A alguien mas le pasa, o soy yo poniendo mal paréntesis y operadores? (He verificado y escrito muchas veces el tema)

**Comment by FranciscoLarach** [comment]
Otra cosa que creo pude haber entendido mal:
¿Cuando encuentro un programon sus Stats son los baseStats?
Por que lo hacia así entonces eran notablemente mejores.
Gracias, Saludos

**Comment by jgmontoya** [comment]
Los stats de los programones deben ser siempre calculados con las fórmulas dadas.

**Comment by FranciscoLarach** [comment]
¿entonces será menor que los basestats para niveles chicos? ¿eso es  lo normal?..
Gracias!!

**Comment by isidoravs** [comment]
A mi también me bajan los stats y hp al usar la formula del enunciado. La idea es que lo obtenido con la fórmula reemplace a los stats y hp anteriores?

**Comment by vjbreton** [comment]
La fórmula siempre siempre se usa, es normal que un pokemon (sobre todo de bajo nivel) tenga los stats menores que su base. En todos los casos que mencionan deben usar la fórmula.
