### ISSUE TITLE
Ranking de programones

### ISSUE THREAD

**Issue by joseluishaddad** [IIC2233-2016-02/Syllabus#138]
El ranking de los 10 programones con más batallas ganadas solo se aplica a los programones del jugador?

**Comment by iqacevedo** [comment]
Hola según explicaron por ahí, se cuentan todos los programones de todos los usuarios que han ingresado.

**Comment by jtagle2** [comment]
#45
Saludos

**Comment by joseluishaddad** [comment]
Gracias!
