### ISSUE TITLE
Error en Material de clases /02-EDD/03-colas.html

### ISSUE THREAD

**Issue by iqacevedo** [IIC2233-2016-02/Syllabus#139]
Hola, 
En la implementan en python del metodo Cola.first(), dice que se debe usar deque[1], sin embargo esto nos devuelve el segundo elemento, no el primero, por lo que probé debería ser deque[0], como una lista normal.

**Comment by jicortes2** [comment]
Hola! Tienes razón, gracias por avisar :) Lo cambiaremos a la brevedad. Si quedo alguna duda, en el mismo material hay un ejemplo más abajo:

`cola = deque(['naranja', 'manzana', 'platano'])`

`# primer elemento`
`print(cola[1])`

Si bien, el comentario dice que imprime el primer elemento (también lo arreglaremos), el `print(cola[1])` te muestra 'manzana' que es el segundo elemento.
Saludos!
