### ISSUE TITLE
accuracy ataque acertado

### ISSUE THREAD

**Issue by bvfernandez** [IIC2233-2016-02/Syllabus#140]
Hola! tengo tres preguntas relacionadas:
1)Cuando en el enunciado dice "La probabilidad de acertar un ataque  está dado por el accuracy del ataque a utilizar", se refiere a solo cuando es ataque o cuando es defensa también?

2) El daño se hace solo cuando es ataque o si el programón se está defendiendo también?(pregunto por si acaso)

3) Cuando se realiza un movimiento de defensa, también disminuye su pp?

Muchas gracias!!

**Comment by flobarrios** [comment]
Hola! Las reglas son las mismas cuando el programon propio se esta defendiendo y el computador esta atacando. Saludos!
