### ISSUE TITLE
urgente archivo gyms

### ISSUE THREAD

**Issue by Afalegria** [IIC2233-2016-02/Syllabus#141]
Viendo el archivo gyms.json vi que varios trainers se repiten (mismo nombre) y tienen distintos programones...
que hagoo ??

**Comment by jgmontoya** [comment]
Tu programa debe ser capaz de manejar esto.

**Comment by Afalegria** [comment]
pero dejo los programones repetidos dentro de un mismo entrenador ?
o tomo uno solo de los repetidos
o los tomo como entrenadores distintos...

**Comment by jgmontoya** [comment]
Debes considerar que son entrenadores distintos, cada uno con su equipo como está especificado en el archivo.

**Comment by flobarrios** [comment]
#109
