### ISSUE TITLE
Type Fairy 

### ISSUE THREAD

**Issue by aiquinones** [IIC2233-2016-02/Syllabus#142]
> tipo movimiento atacante [dict]: Diccionario con todos los tipos de programones atacados que se ven afectados con el tipo del movimiento del atacante.

En el archivo programones.json hay programones clase Fairy, pero en el archivo types.json no se entrega información sobre esta clase. Esto quiere decir que Fairy tiene valor 1 con todas las otras clases?

**Comment by Hernan4444** [comment]
@Aiquinones tal como dices, la clase Fairy tiene valor 1 con todas las otras clases.
Saludos!
