### ISSUE TITLE
Duda con Kwargs

### ISSUE THREAD

**Issue by Kitaps** [IIC2233-2016-02/Syllabus#146]
Hola, esta es una duda general que tengo con los **kwargs. 

Lo que pasa es que cuando tengo una valor predeterminado como en este caso no se como hacerlo.
![captura1](https://cloud.githubusercontent.com/assets/10112117/18016799/4d2fac0a-6b9c-11e6-8c33-27f405a159ee.PNG)
Porque me tira error, no es grande el problema, pero me gustaría entender como se hace bién.
Este segundo es la forma de como sí me funciona:
![captura2](https://cloud.githubusercontent.com/assets/10112117/18016838/75f33f80-6b9c-11e6-9518-9e4a49501bf5.PNG)

**Comment by FernandoPieressa** [comment]
Que error te tira exactamente?

**Comment by Kitaps** [comment]
Instancio esto, que de la otra forma me funciona bien. (Yo creo que el error esta en el nombra=None):

blue = Jugador([3, 5, 151], [30, 30, 30], "Blue")

y me tira:

TypeError: **init**() takes 1 positional argument but 4 were given

si quieres ecahrle un ojo lo subi a mi Repo, en el modulo entrenadores.py

**Comment by rodolfopalma** [comment]
@Kitaps con `**kwargs` recibes un diccionario de todos los parámetros pasados de la forma `key=value`. En el ejemplo que pusiste, estás pasando parámetros sin llaves que deben ser recibidos usando `*args` en la firma del método `__init__`. En tu caso, cambia el `__init__` de la clase `Jugador` por `def __init__(self, *args, **kwargs):`.

**Comment by FernandoPieressa** [comment]
El problema sucede porque al usar **kwargs solo, es necesario que pongas los atributos con keys, es decir por ejemplo:

Jugador(ids_programones=[3, 5, 151], lvls=[30, 30, 30],nombre= "Blue")

**Comment by Kitaps** [comment]
Ahhhh perfecto, gracias a los 2. 
Quedo super claro.
