### ISSUE TITLE
error git push

### ISSUE THREAD

**Issue by FranciscoLarach** [IIC2233-2016-02/Syllabus#147]
![captura de pantalla 2016-08-26 a las 9 49 12 p m](https://cloud.githubusercontent.com/assets/20795271/18023988/bbdc77f0-6bce-11e6-8ce6-4222bc640ec9.png)
¿Alguien que lo entienda? Ya hice el pull que sugiere, y lo trate de reiniciar(empezando de nuevo).

**Comment by aaossa** [comment]
Primero que todo **copia la carpeta porque lo siguiente borra todos los cambios** que no estén en el repo remoto (Github):

```
git reset --hard HEAD
git clean -f -d
git pull
```

Una vez que lo corras no deberías tener problemas al hacer pull ni push, luego pones los cambios que hayas hechos y deberías poder volver a hacer push sin problemas. Pero recuerda **copia la carpeta antes de hacer esto**

**Comment by FranciscoLarach** [comment]
Gracias
