### ISSUE TITLE
Duda diagrama de clases

### ISSUE THREAD

**Issue by Regenschrim** [IIC2233-2016-02/Syllabus#148]
¿En que formato se entrega el diagrama de clases? Si mal no recuerdo había una especie de programa o pagina donde hacerlo, pero no recuerdo el nombre. Gracias!

**Comment by Hernan4444** [comment]
@Regenschrim, lo importante es que lo entregues en un formato que pueda ser leído (como pdf). Un programa a utilizar puede se usar NClass, este tiene la opción de exportar como pdf.
Saludos!

EDIT: NClass tambien puede exportar en formato jpeg.

**Comment by Regenschrim** [comment]
¿Si o si debe ser en formato digital? Me refiero a si puedo mandar una foto o un scan de un hoja.

**Comment by agmardones** [comment]
Hola, te recomiendo [NClass](http://nclass.sourceforge.net/)

**Comment by Hernan4444** [comment]
@Regenschrim  Mejor que sea un pdf, algun formato de imagen o algo digital que no requiere un programa especial, un Scan puede que no se entienda mucho si es que quieres hacerlo a mano.
Saludos!
