### ISSUE TITLE
Tarea 2 

### ISSUE THREAD

**Issue by mjjunemann** [IIC2233-2016-02/Syllabus#149]
Se encuentra publicada la Tarea 2 y el material de clases para ayudar a la resolución de esta.

**Comment by DiegoAndai** [comment]
Hola! La tarea quedo entonces para el miércoles 14 a las 23:59? Gracias

**Comment by aaossa** [comment]
Así es @DiegoAndai , no sé si lo actualicemos en el enunciado porque es algo menor (considerando que ya se les avisó a todos vía SIDING). Pero esa es la hora de entrega :ok_hand: 

Saludos,
