### ISSUE TITLE
python no se reconoce como un comando interno o externo

### ISSUE THREAD

**Issue by qukaah** [IIC2233-2016-02/Syllabus#15]
Hola, tengo una duda. He tratado de configurar Python en la consola sin tener éxito hasta el momento. Al ingresar a la consola me arroja "python no se reconoce como un comando interno o externo", lo mismo con los comandos de pip. Ya ingresé la ruta dentro de las variables de entorno y he buscado mucha información en google pero no lo he podido resolver. Muchas gracias!!

**Comment by jgmontoya** [comment]
Hola!

¿Qué sistema operativo usas? (Voy a asumir que estás en windows)

¿Qué te arroja si en la consola ejecutas el siguiente comando? 

```
py
```

Podría ayudar el saber qué has intentado, con qué comandos específicamente estás recibiendo el error, etc...
Links que podrían ser de utilidad: 
- https://docs.python.org/3.5/using/windows.html#configuring-python
- http://stackoverflow.com/questions/17953124/python-is-not-recognized-as-an-internal-or-external-command-why
- http://pythoncentral.io/add-python-to-path-python-is-not-recognized-as-an-internal-or-external-command/

**Comment by qukaah** [comment]
Estoy en Windows 10.
Cuando coloco el comando que me enviaste me aparece esto
![image](https://cloud.githubusercontent.com/assets/14930071/17534398/0503c288-5e57-11e6-8635-0148271ca674.png)
Algunos comandos que me arrojaron error fueron:
"python -V"
"pip install --upgrade simpy"
"pip install -i https://pypi.binstar.org/carlkl/simple numpy"
"pip install --upgrade matplotlib"

Los que aparecen en el Wiki.

Saludos!

**Comment by jtagle2** [comment]
Si pruebas con pip3 en vez de pip ¿También te tira error?

**Comment by qukaah** [comment]
Si, me aparece lo mismo. Envío un pantallazo de la variable de entorno que ingresé, nose si espo podria ayudar.

![image](https://cloud.githubusercontent.com/assets/14930071/17534692/6332c204-5e58-11e6-95d5-bae31f158e48.png)

Además les envío la ruta en mi PC.

"C:\Users\fernando\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.5"

**Comment by jgmontoya** [comment]
@qukaah 

Eso significa que funciona, en adelante los comandos que sean del tipo 

```
python <algo>
```

Deberás ejecutarlos como

```
py <algo>
```

Ahora veamos como solucionar lo de pip.
Intenta ejecutar el siguiente comando:

```
py -m pip install -U pip
```

Y cuéntanos qué te sale.

Saludos!

**Comment by qukaah** [comment]
Funcionó!!!. Muchas gracias!!, no lo había podido encontrar en ningún lado, muchísimas gracias!
![image](https://cloud.githubusercontent.com/assets/14930071/17535241/654c5bba-5e5b-11e6-9f0b-7d1a907e6d44.png)

**Comment by Mahund** [comment]
Hola, llegue al mismo punto pero siguen sin funcionar los comandos pedidos.
¿Que debo hacer?
![screenshot_2](https://cloud.githubusercontent.com/assets/20783050/17594955/1e825b8a-5fb9-11e6-8497-3662209e8498.jpg)

**Comment by aaossa** [comment]
Prueba con `py -m pip install simpy --upgrade`

**Comment by Mahund** [comment]
Funcionó, gracias! Para los 2 comandos restantes: 

pip install -i https://pypi.binstar.org/carlkl/simple numpy
pip install --upgrade matplotlib

Serian de la forma:

py -m pip install -i https://pypi.binstar.org/carlkl/simple numpy
py -m pip install --upgrade matplotlib

también?

**Comment by Mahund** [comment]
![screenshot_3](https://cloud.githubusercontent.com/assets/20783050/17595989/6a140bc6-5fbd-11e6-91a2-8b6ed7ff95e3.jpg)

**Comment by Mahund** [comment]
Probé ingresando el comando siguiente y resultó esto:
![screenshot_4](https://cloud.githubusercontent.com/assets/20783050/17596066/b68792c0-5fbd-11e6-9703-a0e3bf015088.jpg)

**Comment by aaossa** [comment]
Significa que ya lo instalaste: _"Requirement already satisfied"_. Para asegurarte de tener la versión mas reciente tienes que agregar el _flag_ `--upgrade` al final

**Comment by Mahund** [comment]
Muchas gracias!
![screenshot_5](https://cloud.githubusercontent.com/assets/20783050/17596297/c0d75886-5fbe-11e6-8855-df49ab01cff1.jpg)

**Comment by jdiaztccp** [comment]
Tengo el siguiente error, su apoyo por favor
![image](https://cloud.githubusercontent.com/assets/29032468/26537437/22182bcc-4405-11e7-9c9e-0cee1e8f9b7a.png)

**Comment by Nukemenonai** [comment]
El thread me ayudo a solucionar el error usando py en vez de python, pero ahora me sale esto: 
![image](https://user-images.githubusercontent.com/29505807/27253870-5236018e-5342-11e7-9b23-0017732d7dcc.png)

**Comment by Nukemenonai** [comment]
como actualización, fui capaz de resolver el error de sintaxis invalida escribiendo cd en la consola de windows

![image](https://user-images.githubusercontent.com/29505807/27253914-40e94b92-5343-11e7-9349-1f0abb622ded.png)
