### ISSUE TITLE
Librerías permitidas/no permitidas en la T02

### ISSUE THREAD

**Issue by agmardones** [IIC2233-2016-02/Syllabus#150]
Para consultar sobre una librería deben responder esta issue con una pregunta de la siguiente forma:

> Puedo usar la librería nombre_libreria para hacer explicacion_de_lo_que_quiero_hacer

Recuerden especificar en su README qué librerías utilizan!

---
## **Librerías Permitidas**
- os
- random
- sys.exit
- string
- copy
## **Librerías Prohibidas**
- re
- collections
## **Built-ins prohibidos**
- eval (:skull:)
- exec (:skull:)
- _list comprehension_
## **ESPECIALMENTE PROHIBIDO**
- listas
- diccionarios
- tuplas
- sets
- En general, estructuras de datos de este tipo provistas por python

En caso de tener problemas con funciones que retornen alguna de las estructuras prohibidas, lean el ejemplo de la sección 9 del enunciado para poder llevarlas a sus propias estructuras.

**Comment by andresbannuraschultz** [comment]
Esta permitida la libreria string?

**Comment by jgmontoya** [comment]
@abannura ¿Para qué la quieres usar?

Acuérdate al preguntar por alguna librería de seguir con el formato pedido:

> Para consultar sobre una librería deben responder esta issue con una pregunta de la siguiente forma: Puedo usar la librería nombre_libreria para hacer explicacion_de_lo_que_quiero_hacer

Saludos!

**Comment by andresbannuraschultz** [comment]
Disculpa, se me fue! La queria para crear un string con todas las letras del abecedario y luego ver a que posicion corresponde la letra que me entrega la funcion on_piece_click. Gracias!

**Comment by andresbannuraschultz** [comment]
Al final puedo usar string? Gracias!

**Comment by jgmontoya** [comment]
Hola, si puedes usar `string` 

Saludos!

**Comment by andresbannuraschultz** [comment]
Gracias!

**Comment by sormazabal** [comment]
Se puede usar la librería "copy" para realizar una copia del tablero?

**Comment by agmardones** [comment]
Hola @sormazabal !, si puedes usar copy :)

**Comment by sormazabal** [comment]
Hola! Se puede usar "re" para el parser?

**Comment by jgmontoya** [comment]
**No** pueden usar `re`

Saludos!

**Comment by domingo-valdes** [comment]
Puedo usar collections para importar MutableSequence y asi definir metodos como **len**, **getitem**, **setitem**, etc.?

**Comment by jgmontoya** [comment]
@domingo-valdes **NO** pueden usar `collections`

No necesitas importar nada para definir esos métodos!

**Comment by ricardor4** [comment]
¿Puedo utilizar range()?, iterar algo haciendo for i in range(algo)?

¿o cuenta como usar listas?

**Comment by Hernan4444** [comment]
@ricardor4 Si puedes utilizar range()
Saludos!!

Edit: Range retorna un iterable, no una lista, así que en estricto rigor no estas usando listas.

**Comment by ghost** [comment]
Hola!
Cuando dicen que puedo usar strig, puedo iterar sobre un string o rescatar un elemento usando [ ]? Saludos!

**Comment by ndleyton** [comment]
Hola, yo ya lo tengo implementado de otra manera, pero 
se pueden usar listas ligadas de listas ligadas?

**Comment by jgmontoya** [comment]
@elliot-anderson Sí puedes hacer eso que preguntas.

@ndleyton Puedes usar las estructuras que estimes conveniente siempre y cuando la implementación sea tuya.

**Comment by ricardor4** [comment]
¿Puedo importar functools para usar reduce?
mi uso es en la definición de ciertos metodos

**Comment by iqacevedo** [comment]
Hola puedo usar la libreria types para reconocer si un objeto es un generador?
Ej: from types import GeneratorType
    generador = (a for a in List(1,2,3))
    isinstance(generador, GeneratorType) 

Saludos!

**Comment by mjjunemann** [comment]
@ricardor4  si, y @iqacevedo si.

**Comment by DiegoAndai** [comment]
No es librería pero tiene que ver con las restricciones así que mejor lo pongo aquí:

Si GrafoList() es mi lista legal y acepta args, puedo hacer:

`GrafoList(*[list comprehension])`

para armar mi lista legal con los args de la lista que se creo por comprehension.

Muchas gracias

**Comment by ndleyton** [comment]
Se pueden usar excepciones?

**Comment by jgmontoya** [comment]
Hola,

**No** pueden usar _list comprehension_.

**Si** pueden usar exceptions.

Saludos!

**Comment by DiegoAndai** [comment]
Hola! Se pueden ocupar decoradores para cambiar el funcionamiento de métodos al acabar el juego? :D

Muchas gracias.

**Comment by DiegoAndai** [comment]
Y generadores se pueden usar? :D

**Comment by Marivera3** [comment]
Se puede usar itertools??

**Comment by aaossa** [comment]
@Marivera3 tienes que especificar qué elemento de ese módulo quieres usar y para qué :grin:

**Comment by Marivera3** [comment]
cycle, para ir alternando entre el color de las fichas

**Comment by ndleyton** [comment]
puedo hacer 
"for i, elem in enumerate (listaLigada):"  ?

**Comment by NachoCasta** [comment]
Hola. Mi clase lista recibe como unico argumento para instanciarla un iterable. En este caso, puedo usar list comprehensions?

Por ej, lo siguiente lo puedo hacer con mi clase lista

``` python
>>> Lista(i for i in range(10))
>>> [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

Cabe mencionar que lo que retorna no es una lista, solamente el **repr** se ve igual
