### ISSUE TITLE
Zapatilla extraviada :(

### ISSUE THREAD

**Issue by Kitaps** [IIC2233-2016-02/Syllabus#151]
Hola todos,

el jueves le presté mi zapatilla a alguien (como alargador), pero como no funcionaba mi pc se me olvido al finalizar la clase.

Es una Fujitel blanca. Puede que hasta tenga Patrick escrito encime. 
Pls halp, no tengo otro adaptador y no quiero comprar otro.

Gracias

**Comment by fvr1** [comment]
La tenemos nosotros! está en el DCC junto con los otros alargadores :)

**Comment by aaossa** [comment]
Esta historia tuvo un final feliz :grin:
