### ISSUE TITLE
[Tarea 2] Falta de columna I

### ISSUE THREAD

**Issue by jmcomber** [IIC2233-2016-02/Syllabus#152]
Después de harto rato me di cuenta de que el tablero de la interfaz no tiene la columna I. ¿Eso es intencionado? Si no, para que se sepa :).

**Comment by jgmontoya** [comment]
Hola, 

Sí, es intencionado.  Las coordenadas para el tablero se saltan la columna I por razones históricas (supuestamente es para evitar la confusión con la J y la L).

Saludos!

PD: Eso no significa que en los archivos sgf se salten la i (no lo hacen).
