### ISSUE TITLE
pyqt 4

### ISSUE THREAD

**Issue by smargozzini** [IIC2233-2016-02/Syllabus#153]
![captura de pantalla 2016-08-27 a las 23 18 07](https://cloud.githubusercontent.com/assets/14154209/18031225/8ff34338-6cac-11e6-9d53-637fa71a826e.png)

hola me aparece eso cuando trato de instalar pyqt4
que significa?
gracias

**Comment by jgmontoya** [comment]
Cuando haces `import PyQt4` eso corresponde a un comando de python.
Intenta ejecutando el comando  `python` _antes_ de hacer el import.
Si falla el comando `python` (o si te muestra que corresponde a python 2.7.x) intenta con `python3` y/o con `py`

Cuéntanos cómo te va.

Saludos!

**Comment by smargozzini** [comment]
me aparece esto cuando trato
![captura de pantalla 2016-08-27 a las 23 50 43](https://cloud.githubusercontent.com/assets/14154209/18035390/beb9fa48-6d2b-11e6-96af-4f8bcd6a783c.png)

**Comment by otro-felipe** [comment]
instalaste python usando homebrew? Si no instalaste python usando homebrew, entonces debes seguir la guía en la issue #16  para instalar PyQt.

**Comment by smargozzini** [comment]
![captura de pantalla 2016-08-28 a las 20 54 37](https://cloud.githubusercontent.com/assets/14154209/18037735/ad5195be-6d61-11e6-9f61-619ac62bf804.png)

al ejecutar el primer comando del paso 5 me aparece este error.
e intentado muchas veces y de distintas formas y todavía no e podido instalarlo...
agradeceria su ayuda

**Comment by asimonv** [comment]
Holaaa! Hice esto:
http://stackoverflow.com/questions/21711594/pyqt4-on-mavericks-with-python-3

pero en vez de agregar :
"PYTHONPATH=/usr/local/lib/python3.3/site-packages:$PYTHONPATH",

agregué:
"PYTHONPATH=/usr/lib/python3.5/site-packages:$PYTHONPATH" a mi bash profile.

Después hice: 
"brew link --overwrite python3" y me funcionó. 

Como dice @jgmontoya, uso python3 en vez de python. El problema puede ser que esté desordenado donde tienes instalado python3, ya que macOS viene por defecto con 2.x.

**Comment by mrafaeli** [comment]
Hola! yo todavia tengo problemas, se me instala correctamente el sip 

![error pyqt](https://cloud.githubusercontent.com/assets/17434914/18072654/28accbf0-6e36-11e6-91ca-b9b333f87fed.png)

me aparece eso, pero luego cuando trato de instalar el pyqt me aparece 

![error pyqt2](https://cloud.githubusercontent.com/assets/17434914/18072661/30614862-6e36-11e6-9e14-bbcb9e4b31d5.png)

He hecho todo lo que dice la guia de la issue #16 pero no logro hacer que se me instale PyQt4.

**Comment by mrafaeli** [comment]
Hola! yo todavia tengo problemas, se me instala correctamente el sip

![image](https://cloud.githubusercontent.com/assets/10425834/18074285/ef399f4a-6e41-11e6-9bc6-ea1eec169848.png)

me aparece eso, pero luego cuando trato de instalar el pyqt me aparece

[error2.pdf](https://github.com/IIC2233-2016-02/Syllabus/files/443788/error2.pdf)
![image](https://cloud.githubusercontent.com/assets/10425834/18074274/dfcbf7b0-6e41-11e6-83b4-b9e007593f39.png)

He hecho todo lo que dice la guia de la issue #16 pero no logro hacer que se me instale PyQt4.

**Comment by aaossa** [comment]
@mrafaeli GitHub te permite colocar imágenes de forma directa aquí. Reemplazaré tus pdf por las imágenes
