### ISSUE TITLE
[Tarea 2] Grupos muertos

### ISSUE THREAD

**Issue by DiegoAndai** [IIC2233-2016-02/Syllabus#154]
Hola, cuando finaliza el juego, los grupos muertos son aquellos que no pueden ser salvados, cierto? O sea aquellos que si el contrincante quisiera, si o si podría capturar.

Muchas gracias 😃

**Comment by jgmontoya** [comment]
Exacto!

**Comment by DiegoAndai** [comment]
Gracias 😁
