### ISSUE TITLE
Dudas generales T02

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#155]
Estaba revisando la tarea y me surgieron varias dudas:
1. Que aconsejan modificar, el demo o el main_window? 
2. Es necesario entrar a modificar archivos que esten en un nivel mas "profundo", por ejemplo el board.py? O no es la idea de la tarea.
3. Para el board ustedes usaron diccionarios para ir guardando las piezas y sus posiciones. Asumo que nosotros no podemos usar esos atributos. Es decir, tenemos que crear nuestro propio tablero con piezas usando una estructura de datos propia, y que esta vaya cambiando "de la mano" con el tablero de ustedes. Es asi?
4. Cualquier consejo sobre por donde partir es bienvenido.
Muchas gracias.

**Comment by jgmontoya** [comment]
Hola,
1. Ninguno. El demo es solo un ejemplo de como usar los diversos métodos de la interfaz pero deben crear sus propios módulos para la lógica del juego. Pueden basarse en el demo pero no pueden modificar archivos de la gui.
2. **No pueden modificar archivos de la gui**
3. Cualquier interacción con la gui debe ser a través de los métodos entregados (los que están en el enunciado y que se muestran en el demo) y no deben preocuparse de cómo están implementadas las cosas dentro de la interfaz misma. Esto quiere decir que deben usar la interfaz solo para mostrar el juego y en ningún caso para guardar o acceder a información de este. 
4. Te recomiendo primero que todo entender el juego y pensar en qué estructuras pueden ser más útiles para modelar cada parte y cómo estas se relacionan entre sí.

Saludos!

**Comment by andresbannuraschultz** [comment]
Dale muchas gracias!

**Comment by bamavrakis** [comment]
Dale pulgar arriba!
