### ISSUE TITLE
EDD permitidas

### ISSUE THREAD

**Issue by asimonv** [IIC2233-2016-02/Syllabus#156]
Algo que no me quedó claro en el enunciado es que si bien no podemos usar las EDD que mencionan, eso no quita que podamos crearlas, cierto?

**Comment by Hernan4444** [comment]
@asimov tal como dices, debes crearlas tu mismo y mencionar en el readme cómo fue su implementación

**Comment by asimonv** [comment]
Gracias!

**Comment by domingo-valdes** [comment]
Puedo importar MutableSequence desde collections para ayudarme a definir metodos como len en nuestras nuevas edd?
