### ISSUE TITLE
metodo add_line

### ISSUE THREAD

**Issue by Sgwa** [IIC2233-2016-02/Syllabus#158]
En el enunciado cuando explican el metodo add_line dice "Los parametros de coordenadas reciben objetos que implementen getitem (como listas, tuplas, sets, etc.)", resulta que en mi clase que emula una lista implemente getitem e igual me tira error, ademas con la lista nativa de python tambien tira un error, este error es en el archivo nodes.py dentro de gui y mirandolo me di cuenta que es por la linea 20 que dice "key = tuple(sorted([cord_1, cord_2]))" y  me fije que cambiandolo por "key = tuple(sorted([tuple(cord_1), tuple(cord_2)]))" ahi si funciona de forma correcta, debido a que cuando trata de agregar la linea, dentro de la tupla quedan las coordenadas en el formato que se hayan metido, mientras que con la linea que yo sugiero los convierte a tupla y queda todo en tupla.

**Comment by otro-felipe** [comment]
Gracias por la notificación! Hemos cambiado la linea de la gui por la que sugeriste. Siéntete libre de revisar la issue #170 por otros cambios o errores que puedas encontrar.
