### ISSUE TITLE
numero sobre ficha

### ISSUE THREAD

**Issue by fsvergara** [IIC2233-2016-02/Syllabus#159]
Hola,
en el metodo add_piece, cual es el significado del numero sobre la ficha? 
este debe corresponder al numero de la jugada segun el arbol de variaciones?

**Comment by isipalma** [comment]
Holi!
Exacto, es el numero de la jugada. Por eso, cuando el arbol se divide la ficha que aparece es el numero siguiente del nodo de donde se empezo la division

**Comment by jgmontoya** [comment]
Hola, 
El método es el siguiente:
- add piece(self, letter, y, text, color)
  - 'letter' e 'y' te dan la posición en el tablero
  - 'text' es lo que quieras poner sobre la piedra, puede ser un número o un texto
  - 'color' es el color de la piedra (blanca o negra)

No es necesario que indiques en el tablero el número de jugada para cada piedra (sí debes indicarlo para cada nodo del árbol). 

El 'text' lo deberán usar para marcar las piedras que serán eliminadas en la parte final (parte 4.3.1 y bonus). También se recomienda **fuertemente** que lo usen para indicar la última piedra jugada en el transcurso del juego. Además, puede ser útil para verificar que están poniendo las piedras en las posiciones correctas al leer los archivos.

Saludos!
