### ISSUE TITLE
Instalación de PyQt en iOS

### ISSUE THREAD

**Issue by otro-felipe** [IIC2233-2016-02/Syllabus#16]
Si tienen problemas instalando PyQt y no quieren intentar desinstalar python e instalarlo de nuevo, pueden seguir [esta guía](http://www.pythonschool.net/pyqt/installing-pyqt-on-mac-os-x/) para instalar PyQt. Se las voy a resumir y a explicar un poco.
### Paso 1: Sistema operativo al día

Verificar que tienen su versión de MAC OS X al día.
### Paso 2: Xcode Command Line Tools.

Deben checkear que tienen las Command Line Tools de Xcode. Para esto pueden hacerlo mediante el siguiente comando en consola:

```
xcode-select -p
```

Si les retorna algo como `/Applications/Xcode.app/Contents/Developer` entonces es porque están bien y pueden seguir.
En caso de no tener las Command Line Tools las pueden bajar con el siguiente comando

```
xcode-select --install
```
### Paso 3: Instalar Qt

Descargar Qt desde [esta página](http://download.qt.io/official_releases/qt/4.8/4.8.6/qt-opensource-mac-4.8.6-1.dmg) e instalarlo.
Si tienen homebrew pueden hacerlo mediante la consola con el comando `brew install qt`.
### Paso 4: Bajar SIP y PyQt

Una vez instalado Qt descarguen el source package de SIP y PyQt para Mac desde estas paginas: [SIP](https://riverbankcomputing.com/software/sip/download) y [PyQt](https://riverbankcomputing.com/software/pyqt/download). 
Una vez descargados muévanlos a una carpeta en común (digamos `Folder`) y descompriman los archivos (hacerles doble click).
### Paso 5: Path a site-packages.

Necesitamos saber donde se encuentra la carpeta site-packages, que es la carpeta que almacena las librerias que descargamos de python.
Para esto debemos escribir lo siguiente en python:

``` python
import site
print(site.getsitepackages()[0])
```

Esto lo pueden hacer en consola:

```
python3
>> import sip
>> sip.getsitepackages()[0]
```
### Paso 5: Instalar SIP.

En la terminal vamos a `Folder/SIP` y escribimos los siguientes comandos:

```
python3 configure.py -d {PATH A SITE-PACKAGES} -arch x86_64
sudo make
sudo make install
```
### Paso 6: Instalar PyQt (Finalmente).

De la forma en que lo hicimos en el paso anterior vamos a `Folder/PyQt` y escribimos los siguientes comandos:

```
python3 configure.py -d {PATH A SITE-PACKAGES}
sudo make
sudo make install
```

_Esta parte se demora e imprime muchas cosas en la consola, si quieren la pueden poner en pantalla completa y pensar que estan hackeando alguna red importante._
### Paso 7: Ver si funciona.

En caso de que no les funcione o hayan tenido algún problema durante la instalación ~~lloren~~ **traten de buscarlo en google en primera instancia**, en caso de ser incapaces de resolverlos por ustedes mismos, pregúntennos (nosotros manejamos mejor el lenguaje de consultas de Google).

**Comment by jgmontoya** [comment]
¿Cuándo estará la guía para android?

**Comment by felipehv** [comment]
+1 jajaja

**Comment by bamavrakis** [comment]
Hola! Necesito esta guía para Symbian :D

**Comment by otro-felipe** [comment]
Próximamente la versión para Windows Phone

**Comment by felipehv** [comment]
Nadie piensa en blackberry :'(

**Comment by aaossa** [comment]
+1 a Windows Phone

**Comment by fringlesinthestreet** [comment]
Hola seguí la guía que hicieron y llegué hasta el paso 5 en donde me tira el error:

Benjamins-MacBook-Pro-2:sip-4.18.1 benjamincarcamo$ python3 configure.py -d {/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages} -arch x86_64
This is SIP 4.18.1 for Python 3.5.2 on darwin.
Usage: python configure.py [opts] [macro=value] [macro+=value]

configure.py: error: no such option: -a

Esto lo corregí visitando la página http://www.noktec.be/python/how-to-install-pyqt4-on-osx, la cual la recomendaban en una issue del semestre 2015-02 (link: https://github.com/IIC2233-2015-2/syllabus/issues/19).

El configure.py se realizó sin problemas al igual que el make pero al probar el comando sudo make install me arrojó el siguiente error:

Benjamins-MacBook-Pro-2:sip-4.18.1 benjamincarcamo$ sudo make install
Password: 
cp -f sip /System/Library/Frameworks/Python.framework/Versions/2.7/bin/sip
cp: /System/Library/Frameworks/Python.framework/Versions/2.7/bin/sip: Operation not permitted
make[1]: **\* [install] Error 1
make: **\* [install] Error 2

Mi sistema operativo es El Capitán y con lo que he leído tiene varios problemas con permisos. Encontré esta página que indica pasos a seguir para poder usar Homebrew como antes. link :http://digitizor.com/fix-homebrew-permissions-osx-el-capitan/. 

Mi pregunta es si es seguro hacer todo eso.. no lo entiendo bien y no quiero matar mi computador.
Eso.. no debi actualizar el sistema operativo parece ://. Gracias!

**Comment by svrivera** [comment]
No hay caso, sigo obteniendo el mismo error:

> Last login: Mon Aug 29 22:14:31 on ttys000
> MacK:~ Sebastianrivh$ cd desktop
> MacK:desktop Sebastianrivh$ cd folder
> MacK:folder Sebastianrivh$ cd /Users/Sebastianrivh/Desktop/Folder/sip-4.18.1 
> MacK:sip-4.18.1 Sebastianrivh$ python3 configure.py -d {PATH A SITE-PACKAGES} -arch x86_64
> This is SIP 4.18.1 for Python 3.5.2 on darwin.
> Usage: python configure.py [opts] [macro=value] [macro+=value]
> 
> configure.py: error: no such option: -a
> MacK:sip-4.18.1 Sebastianrivh$

**Comment by rmsolari** [comment]
Mismo error, lo he intentado todo
@fringlesinthestreet te funcionó lo de la página?
