### ISSUE TITLE
PyQt4 windows

### ISSUE THREAD

**Issue by Tibrahm** [IIC2233-2016-02/Syllabus#160]
![esto](https://cloud.githubusercontent.com/assets/14153815/18097400/0a55f752-6eb4-11e6-93c2-02a7dc6f17f6.png)

se me instala bien el sip pero cuando trato de instalar pyqt4 me sale esto :+1: 

![sin titulo](https://cloud.githubusercontent.com/assets/14153815/18097427/2876f15a-6eb4-11e6-8ed7-e0e71b9a7cca.png)

**Comment by Iruretagoyena** [comment]
1. [Instala anaconda](https://www.continuum.io/downloads) y dale permisos para que se agregue al PATH
2. En la CMD, ingresa "conda install pyqt"

**Comment by Tibrahm** [comment]
ha lo hice, no funciono, tengo que hacer algo despues?

**Comment by aaossa** [comment]
@Tibrahm no te funcionó el método indicado en la Wiki?

**Comment by FernandoPieressa** [comment]
#4 

No tienes el mismo error pero sirve la solución.

**Comment by Nebula2028** [comment]
Disculpen que abra de nuevo el issue, pero yo aun tengo problemas con cargar PyQt4.

Yo efectivamente tenia una instalación previa de python 3.4 del semestre pasado, pero creí que lo había desinstalado bien antes de instalar python 3.5 (al parecer no).

Trate instalando el .whl que sale en la wiki del curso, y ahi efectivamente puedo hacer import PyQt4 sin que python alegue, pero al correr el demo de la tarea me dice que dentro de PyQt4.Gui no puede encontrar QLabel, QText y otras Qcosas.

Probe instalando anaconda pero al poner conda install pyqt o simplemente conda me aparece esto:

![no_conda](https://cloud.githubusercontent.com/assets/13741469/18145741/d07c4028-6fa2-11e6-81e2-c13dc2057502.jpg)

ayura

**Comment by Nebula2028** [comment]
oops, no se exactamente como ni porque pero reinstalando el .whl usando pip y haciendo pull a los nuevos archivos de ejemplo y demo.py me funcionó.

Eso si, aun no me funciona ocupar conda, y ya que instale anaconda igual me gustaría saber como hacerlo funcionar (o sino lo desinstalo nomas... Anaconda se supone que hace un trabajo equivalente a lo que hace pip ? )

**Comment by Iruretagoyena** [comment]
@Tibrahm Trataste cambiando el interprete que esta usando PyCharm ?

**Comment by Tibrahm** [comment]
@Diiru Gracias ahi si pude no habia cambiado el interprente al de conda, vale man !!!
