### ISSUE TITLE
PyQt4 Mac

### ISSUE THREAD

**Issue by mraddatz** [IIC2233-2016-02/Syllabus#161]
He intentado muchos métodos para instalar PyQt4 en OSx (he mirado issues y buscado en google) pero aún no puedo instalarlo. Existe la posibilidad de visitar a alguien en persona que entienda más?

**Comment by aaossa** [comment]
¿Qué significa que no puedas instalarlo? ¿Qué error te aparece? Te pregunto para, que quien sea que pueda ir a ayudarte, sepa a lo que va :ok_hand:

**Comment by mjjunemann** [comment]
Podrias elaborar en el metodo que ocupas para instalar PyQt4, como instalaste python etc ? Que tipo de error de arroja algo ? Si puedes con screenshots de los errores, no somos adivinos 👼.

**Comment by fleon23** [comment]
A mi me pasa que pude instalar homebrew sin problemas... luego instale pyqt4 mediante brew... y ahi arrojo el "error" de que no iba a poder importar desde python. Alguna idea de como solucionar eso? ( Uso MAC)( y no tengo el error que me arrojo y no se que hacer para que me imprima el error de nuevo) GRACIAS

**Comment by aaossa** [comment]
@fleon23 el error te aparece al instalar pyqt4 o al importarlo? Adjuntar una imagen del error porfa :grin:

**Comment by tcgarrido** [comment]
<img width="570" alt="captura de pantalla 2016-08-30 a la s 20 28 48" src="https://cloud.githubusercontent.com/assets/19194486/18110735/396bf32a-6ef0-11e6-89d9-3d3684483442.png">

Me pasa eso, hice lo del issue 2015-2, lo que uds indicaron en la guía y no funca :c

**Comment by mraddatz** [comment]
Ya pude instalarlo y me corre bien solo en IDLE3. Sin embargo en sublime o pycharm me aparece este error.
![captura de pantalla 2016-08-30 a las 8 29 37 p m](https://cloud.githubusercontent.com/assets/20804654/18110850/2e557d98-6ef1-11e6-9f7d-99302c746d3d.png)

Ya instale python3.5 pero al parecer sigue corriendo el 2.7, como hago para desinstalar este último?

**Comment by tcgarrido** [comment]
Me pasa lo mismo! solo me funciona en IDLE. En Sublime pongo Build with Python o Python3 y me sale esto:
<img width="649" alt="captura de pantalla 2016-08-30 a la s 21 31 57" src="https://cloud.githubusercontent.com/assets/19194486/18111843/2c5a6726-6ef9-11e6-8982-e63e66c9989c.png">
<img width="493" alt="captura de pantalla 2016-08-30 a la s 21 32 11" src="https://cloud.githubusercontent.com/assets/19194486/18111844/2c5f68e8-6ef9-11e6-8768-ab7ec466206a.png">

Y en Pycharm:
<img width="797" alt="captura de pantalla 2016-08-30 a la s 21 24 07" src="https://cloud.githubusercontent.com/assets/19194486/18111848/3583ee12-6ef9-11e6-9ec2-f1bde69faa1a.png">

Que puedo hacer?

**Comment by fringlesinthestreet** [comment]
A mi también me apareció lo del Photon Error. Que supuestamente estaba roto algo y que no se podía llegar directamente a lo instalado.. algo así era.

**Comment by fringlesinthestreet** [comment]
EL error es el siguiente:

![captura de pantalla 2016-08-30 a las 10 46 10 p m](https://cloud.githubusercontent.com/assets/20802067/18114196/b672ba96-6f0b-11e6-8965-d3c121f27b46.png)

¿Saben como repararlo?

**Comment by mjjunemann** [comment]
@tcgarrido: escribe en tu consola which python3 y manda un screenshot de lo que te aparece? 
@fringlesinthestreet : phonon es una libreria de pyqt, pero es especialmente para reproducir sonidos, musica , etc , no deberia haber problemas. En general no ocupamos esa modulo de PyQt por problemas compatibilidad entre windows , osx , linux 
@mraddatz: Creo que tienes que cambiar el interprete por defecto que corre cuando le dices que ejecute el script en python, en las preferencias de pycharm metete y busca interpreter y cambialo a python3.5 y en sublime igual.

**Comment by fleon23** [comment]
Mi error es el mismo de fringlesinthestreet . Ejecute los comandos tal y como sale ahi, sin embargo no pasó nada ( ejecute los comandos así con python 2.7 y cambiándolo por 3.5 ) AYUDAA

**Comment by fringlesinthestreet** [comment]
casi\* lo resolví!

Miren, probé con agregar un path temporalmente al mi bash profile, porque leí que si uno intentaba apendearlo permanentemente algunos terminaban perdiendolo todo xd.
Aquí la diferencia con agregar el PATH:

Sin agregar:
![captura de pantalla 2016-08-30 a las 11 54 24 p m](https://cloud.githubusercontent.com/assets/20802067/18115326/f64f2768-6f14-11e6-9fa4-3ae056a035bf.png)

Con Path:
![captura de pantalla 2016-08-30 a las 11 55 13 p m](https://cloud.githubusercontent.com/assets/20802067/18115347/0c0e9124-6f15-11e6-8258-dac5311b7cfb.png)

Esto significa que funcionaba. Así que había que agregar simplemente el PATH en el código. Lo hice de la siguiente manera:
import sys
sys.path.append('/usr/local/lib/python2.7/site-packages')
import PyQt4

Y no tiró error el importar PyQt4.

Eso sí, me salió un error enorme cuando intente cargar el demo:
![captura de pantalla 2016-08-30 a las 11 58 34 p m](https://cloud.githubusercontent.com/assets/20802067/18115397/85c1a402-6f15-11e6-9dee-e148eb4bffdd.png)

Si alguien cacha como hacerlo funcionar :/ porfa manden la respuesta

**Comment by fringlesinthestreet** [comment]
Oigan en vez de:
sys.path.append('/usr/local/lib/python2.7/site-packages')
Pongan:
sys.path.append('/usr/local/Cellar/pyqt/4.11.4/lib/python3.5/site-packages')

Ahora carga el PyQt4.QtGui. Sin embargo, tira un exit code 139...
Voy a investigar xd

**Comment by fringlesinthestreet** [comment]
Me funcionó..

Me tiraba error 'exit code 139' porque abrí pycharm con la versión python 3.44.

Reinicié y abrí un nuevo experimento con la versión 3.5.. y funcionó.!

**Comment by adisrael** [comment]
Instalé PyQt4 en mac con la forma que aparecía en la wiki (brew install pyqt --with-python3)... después de un rato me aparece: 
Warning: pyqt-4.11.4 already installed
pero cuando intento importarlo en python me aparece:
ImportError: No module named 'PyQt4'

**Comment by mjjunemann** [comment]
@adisrael puedes hacer which python3 en tu consola y escribir lo que sale?, tengo la impresion de que es un python distinto al donde instalo pyqt.

**Comment by adisrael** [comment]
@mjjunemann 
Me sale esto:
/Library/Frameworks/Python.framework/Versions/3.5/bin/python3

**Comment by adisrael** [comment]
@mjjunemann 
Ya lo pude arreglar! gracias de todas formas!

**Comment by mjjunemann** [comment]
@adisrael, ya si tienes un python3 instalado de instalador y no es el del homebrew que se recomienda en la guia del curso, te recomiendo desinstalar ese python3 y arreglar el path para que apunte al python3 que instala brew. Hay varias issues que explican como arreglar el path, en esta misma alguien creo que alguien lo arreglo. 

Luego de haberlo arreglado, y hagas which python3 deberia arrojarte algo del estilo /usr/local/bin/python3. 

(Basta solo con ir a tu bash_profile y modificar la variable PATH, que debe ser algo del estilo, export PATH=/Library/Frameworks/Python.framework/Versions/3.5/bin/python3;$PATH, debes remover /Library/Frameworks/Python.framework/Versions/3.5/bin/python3 del PATH, pero es para que no tengas redundancia con programas instalados)
