### ISSUE TITLE
jugadas en sgf

### ISSUE THREAD

**Issue by smargozzini** [IIC2233-2016-02/Syllabus#162]
![captura de pantalla 2016-08-30 a las 16 01 36](https://cloud.githubusercontent.com/assets/14154209/18102976/15969e16-6ecb-11e6-94ff-748fd9e9e0b0.png)

en esta parte del enunciado no entiendo que significan los paréntesis, si el juego es por turnos

**Comment by Hernan4444** [comment]
@smargozzini Con los paréntesis se busca separar diferentes variaciones del juego o lineas de un mismo juego. Como se ve en el enunciado, en una linea de juego el negro puso su pieza en la posición dd pero en otra linea de juego (una variación) el negro puso esa pieza en la posición qd y luego fue respondida por el blanco en la posición dd y luego el negro de nuevo.... La idea es que ustedes puedan diferenciar cada variación dentro del juego gracias a los paréntesis.
Saludos!.

**Comment by isipalma** [comment]
Lo que sucede es que en el programa debes ser capaz de volver en tus pasos y poder hacer otra jugada, lo cual ramifica el arbol en otra rama 
 En el punto 5.2 se explica mejor
