### ISSUE TITLE
Puede haber empate?

### ISSUE THREAD

**Issue by sormazabal** [IIC2233-2016-02/Syllabus#163]
Qué pasa si ambos jugadores terminan con igual puntaje?

**Comment by FernandoPieressa** [comment]
Efectivamente se puede empatar si ambos tienen igual puntaje, Saludos!

**Comment by jgmontoya** [comment]
Puede haber empate solo si el valor del komi es un número entero. Si no lo es, no habrá empate pues el puntaje de Negro siempre será un entero.

Saludos!

**Comment by kcsss** [comment]
Había leído que el segundo jugador, tiene una ventaja de 0.5/6.5 puntos. Por lo que no puede haber empate.

**Comment by Pyralspite** [comment]
Depende de lo que los jugadores/organizadores acuerden. En torneos se suele utilizar una fracción para evitar el empate, pero en juegos casuales algunas personas utilizan enteros porque consideran que esa fracción es injusta. Si dos jugadores son igual de buenos, por que uno debería declararse ganador sobre el otro?

**Comment by jgmontoya** [comment]
Para efectos de la tarea las partidas que se creen con su aplicación deben setearse por defecto con komi de 6.5 como está en el enunciado. 

Pueden leer más acerca del valor del komi [acá](http://senseis.xmp.net/?Komi) y acerca del 'empate' [acá](http://senseis.xmp.net/?Jigo)
