### ISSUE TITLE
Regla de Ko

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#164]
La regla de Ko aplica solo cada dos jugadas o no? Es decir, no puedo volver a un mismo estado que haya ocurrido en la jugada anterior (cosa que tampoco es posible) ni la jugada antes que esa. Gracias!

**Comment by jgmontoya** [comment]
Hola, 

Tal como está en el enunciado, debe prohibirse la repetición de **cualquier** estado anterior. Esto en realidad se conoce como [Positional Superko Rule](http://senseis.xmp.net/?PositionalSuperko).

Si quieres puedes implementar [Situational Superko Rule](http://senseis.xmp.net/?SituationalSuperko) o [Natural Situational Superko Rule](http://senseis.xmp.net/?NaturalSituationalSuperko) y especificarlo en el readme.

Saludos!

**Comment by andresbannuraschultz** [comment]
perfect, muchas gracias!
