### ISSUE TITLE
Parser de SGF

### ISSUE THREAD

**Issue by sormazabal** [IIC2233-2016-02/Syllabus#165]
Tenemos que crear nuestro propio parser para cargar los archivos .sgf? Asumo que sí, pero quería asegurarme.

**Comment by Hernan4444** [comment]
@sormazabal Si, tienen que crear un parser para cargar cualquier archivo.sgf como el explicado en el enunciado.

**Comment by sormazabal** [comment]
@Hernan4444 debe ser desde cero o se puede usar una librería externa que me ayude?

**Comment by Hernan4444** [comment]
@sormazabal Deben hacer su propio parser

**Comment by jgmontoya** [comment]
@sormazabal Aprovecho de recordar que para cualquier librería que quieras usar puedes preguntar en #150 si su uso está permitido o no.

**Comment by lampuerov** [comment]
Tengo una duda respecto al formato de los archivos para crear el parser.
En todos los ejemplos subidos menos en el 'Ejemplo variaciones Simple.sgf' se separa la metadata y el juego por ' ; ', esto es casualidad o debe ir un ' ; ' también después de KM[6.50] o antes de (;B[dd])???
En caso de estar bien el archivo, me recomiendan crear un parser aparte para la lectura de los archivos que comiencen con variaciones?

Saludos!

**Comment by jgmontoya** [comment]
Hola, 

En este archivo esa diferencia ocurre porque hay una variación en la primera jugada. 

No creo que tenga sentido hacer un 'parser aparte' sino que tu parser debiera poder manejar este caso como con cualquier otra variación.

Saludos!

**Comment by lampuerov** [comment]
Gracias por la aclaración, pero estuve buscando en https://online-go.com/demo/ y ahí hay una opción para descargar sgf. Al abrir este archivo me di cuenta que si parte con 2,3... variaciones, de todas maneras separan la metada de la información del juego mediante una línea en blanco.  Está permitido usar estos .sgf como ejemplo?

Saludos

**Comment by DiegoAndai** [comment]
Se comenta en el enunciado que no debe haber problemas si falta alguno de los datos de la partida, si es que no existe ninguno, o sea, todo es por default, el archivo empezaría (;;jugadas....) o (;jugadas....)

(o, en su defecto, (;(;jugadas...) y ((;jugadas....) si es que la primera jugada tiene variaciones)

Mi pregunta es si se mantiene el ';' correspondiente a metadata, exista o no.

Muchas gracias.
