### ISSUE TITLE
PyQt4 error

### ISSUE THREAD

**Issue by fnmendez** [IIC2233-2016-02/Syllabus#166]
Al tratar de ejecutar el demo recibo un error:

[...]
from PyQt4.QtGui import QLabel, QPixmap, QWidget, QPalette
ImportError: DLL load failed: No se puede encontrar el módulo especificado.

Desinstalé Python y lo instalé de nuevo con todos los componentes pedidos y me tiró el mismo error de nuevo. (Al hacer `import PyQt4` no me da error)

Gracias !!

**Comment by aaossa** [comment]
Hola, esto te ocurre al ejecutar por consola? Revisa que, si estás ejecutando esto desde un archivo, el archivo no se llame `PyQt.py` o algo así.

Cual es tu Sistema Operativo? (Windows, Linux, Mac, ...)

**Comment by mjjunemann** [comment]
Esto te podria servir:
http://stackoverflow.com/questions/2738879/cannot-import-pyqt4-qtgui, en el ultimo comentario.
![image](https://cloud.githubusercontent.com/assets/5751374/18131745/52cbc186-6f6a-11e6-81de-4ce1aa70a1c4.png)

**Comment by fnmendez** [comment]
¡Instalé el `msvp140.dll` y funcionó!

Muchas gracias a ambos.

**Comment by gebalassa** [comment]
Probé lo mismo y no me funcionó. Coloqué el archivo `msvcp140.dll` en la carpeta PyQt4 y revisé el PATH, el cual incluía la carpeta correctamente. Sigue lanzando el error que impide encontrar los módulos (aunque permita importar PyQt4).

**Comment by Hernan4444** [comment]
@gebalassa Intenta ejecutar el designer.exe ahi te indicara que dll te faltan. Hubo casos de personas que le faltaron 2 o 3 dll que instalar, puede ser que también sea tu caso.

**Comment by gebalassa** [comment]
¡Saludos!

Abro **Designer** y me permite utilizar QWidgets con normalidad. Puedo guardar el archivo como `.ui` sin problemas. Sin embargo, al seleccionar el tab `"Form" -> "View Code"` me tira: `Unable to launch C://Program Files/Python35/Lib/site-packages/PyQt4/uic`

En ningún momento lanza advertencias respecto a los DLL faltantes. ¿Cuáles DLL les faltaban a los otros casos?

**Comment by gebalassa** [comment]
_**Bumpity Bump**_

**Comment by fhgajardo** [comment]
Hola,
Tengo el mismo problema, instalé el msvp140.dll, pero ahora me aparece "DLL load failed: %1 no es una aplicación Win32 válida." y al usar "designer.exe "  me tira el error 0xc000007b. 
Alguien sabe que puedo hacer con esto?
Gracias de antemano
