### ISSUE TITLE
Dead stones

### ISSUE THREAD

**Issue by asimonv** [IIC2233-2016-02/Syllabus#167]
Holaaa! Tengo una duda con respecto a 4.3.1 del enunciado. Cuando dice que: "Estas piedras se remueven entonces del tablero y se consideran capturadas. Una vez hecho esto, se puede pasar a contar el territorio.", simplemente hay que eliminar lo que el usuario eligió? O hay que crear un algoritmo para decirle al usuario cuáles están muertas?

**Comment by jgmontoya** [comment]
Hola, 

> simplemente hay que eliminar lo que el usuario eligió? 

Para la parte 4.3.1 debes simplemente quitar del tablero las que el usuario marcó como muertas. Te recuerdo eso sí que debes tener las siguientes consideraciones:
- Se debe poder marcar/desmarcar grupos completos haciendo click en cualquier piedra perteneciente a este.
- **No** permitir marcar grupos que estén incondicionalmente vivos (grupos con dos ojos).

> hay que crear un algoritmo para decirle al usuario cuáles están muertas? 

Ese es el bonus!

**Comment by kcsss** [comment]
¿Qué método tenemos para remover las piedras del GUI ?

**Comment by aaossa** [comment]
Lee el enunciado @kcsss 

![image](https://cloud.githubusercontent.com/assets/10425834/18285089/1ff316be-7443-11e6-82a2-bce6ab284dbd.png)

**Comment by kcsss** [comment]
![](https://media0.giphy.com/media/KHH0llHZxgc2A/200_s.gif)
