### ISSUE TITLE
[Tarea 2] Aparición Punto en Árbol

### ISSUE THREAD

**Issue by jmcomber** [IIC2233-2016-02/Syllabus#168]
Tanto en mi programa como en el demo.py no he logrado hacer que aparezca el punto agregado en el árbol. Está puesto (si intento poner un nuevo punto en esa posición me dice que _Node's space already occupied_), pero no se ve. Solo me funciona si, como en el demo, lo pongo en el **init**, más que cuando se pone una ficha. ¿No hay un método para actualizar esa parte de la interfaz, cierto? Agregar las líneas, por otra parte, funciona perfectamente. 

O sea, de acá todo funciona como espero menos el add_point:

```
def on_piece_click(self, letter, y):

        self.add_point(7, 1, 100, "black")
        self.add_line((9, 2), (7, 1), "black")
        self.add_piece(letter, y, '1', "white")
        self.show_message("Added {},{}".format(letter, y))
```

(claramente es un ejemplo burdo para el demo).

¿Entendí algo mal?¿Alguien más habrá tenido ese problema?

Gracias!

**Comment by otro-felipe** [comment]
Tienes razón! Por favor revisa la issue #170 y nos informas si es que el problema fue resuelto.

**Comment by jmcomber** [comment]
Ahora sí, me funciona perfecto!
Gracias
