### ISSUE TITLE
Variaciones

### ISSUE THREAD

**Issue by Snorlax8** [IIC2233-2016-02/Syllabus#169]
Hola!
Disculpen si es muy obvio lo que pregunto, pero no me está quedando claro qué son las variaciones exactamente y para qué sirven. Alguien podría explicarme?

Muchas gracias!

**Comment by isipalma** [comment]
Holi!

Imagina que las variaciones son como dimensiones paralelas. Tu puedes "volver en el tiempo" a cierta jugada (lo cual lo indica el numero encima de la ficha) haciendo click en esa ficha y hacer otra jugada lo cual abre otra "linea de tiempo" y de esa forma llegar a otro estado del tablero. En los programas de go esto sirve para practicar jugadas y poder ir probando distintas estrategias.

Saludos!

**Comment by sormazabal** [comment]
Cuando dices "hacer click en esa ficha" te refieres a la ficha en el árbol o la ficha ya puesta en el tablero?

**Comment by isipalma** [comment]
En el arbol

**Comment by Snorlax8** [comment]
Ok, muchas gracias por tu respuesta!
