### ISSUE TITLE
Definicion de territorio

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#171]
Me entro una duda respecto a que se considera territorio de un jugador. En el enunciado sale que el territorio de un jugador es una zona donde el oponente no puede armar grupos vivos (aparte de que sea una zona "encerrada" por piedras del color correspondiente). Busque en google y segun lo que entendi esta condicion no aplica para el juego real, debemos considerarla? Es decir, en el juego real, por ejemplo,  puedo encerrar una zona vacia de 5x5 donde mi rival podria llegar a formar un grupo vivo con dos ojos (el tipico rectangulo que le faltan dos piedras), pero igual se considera mi territorio. Entiendo que esta situacion no debiese ocurrir, ya que si puedo formar un grupo vivo no habria apretado el pass. Pero que pasa si soy un jugador inexperimentado, o apreto el pass por error. Cuento dicho territorio como propio a pesar de que mi enemigo pueda formar un grupo vivo en el? Sorry lo largo! Gracias!

**Comment by jgmontoya** [comment]
El territorio se cuenta después de que los jugadores pasan y se quitan las piedras consideradas muertas. Cuando en el enunciado se menciona que "no es posible que el oponente haga un grupo vivo" se refiere a que los jugadores al pasar están acordando implícitamente cuáles serán los territorios.

En el ejemplo que indicas, si bien hay espacio para un grupo con dos ojos del jugador contrario es muy fácil para el otro jugador evitar que este lo logre. Si aun así lo quisiese intentar tiene que hacerlo antes de que termine el juego (de que ambos pasen, se quiten las piedras muertas y se cuenten los territorios).

Te dejo un caso extremo (es ridículo pero espero que sirva para aclarar el asunto): Negro juega una vez y luego ambos pasan y termina el juego. En ese caso negro queda con 360 puntos (pues no hay capturas) y blanco queda con 6,5 puntos (suponiendo ese es el valor del komi en la partida). El resultado entonces será B+353.5
![one_stone_territory](https://cloud.githubusercontent.com/assets/11434422/18149079/17f7b6b8-6fac-11e6-8a64-0a9053e18763.jpg)

**Comment by andresbannuraschultz** [comment]
Sirvio perfecto el ejemplo! Te pasastee, muchisimas gracias!!

**Comment by fvandeputte** [comment]
Sigo sin entender que se considera por territorio, cuando no se "encierrra el territorio vacio, que  por ejemplo en este caso: 
![captura de pantalla 2016-09-06 a las 4 23 55 p m](https://cloud.githubusercontent.com/assets/11547737/18287708/919861ec-744e-11e6-8850-8275b3bc49e6.png)

**Comment by jgmontoya** [comment]
En ese caso, si el juego fuera a terminar entonces ambos jugadores tendrían 0 puntos de territorio.

Saludos!

**Comment by fvandeputte** [comment]
Gracias!
