### ISSUE TITLE
Varias preguntas tarea02

### ISSUE THREAD

**Issue by bvfernandez** [IIC2233-2016-02/Syllabus#175]
Hola!! Tengo varias preguntas.... Ojalá me puedan responder :)
1. Para qué sirven los cuadrados en el tablero (add square)
2. Un archivo sfg SIEMPRE parte con (;FF......) o también es opcional (asi cmo SG, DT, ect)
3. Que tipos de eventos existen(aparte de torneos(EV)4.Le influye en algo al jugador?

Como siempre muchas gracias!

**Comment by jgmontoya** [comment]
Hola!
1.  Para indicar el territorio de cada jugador en la parte final.
2.  Los que su programa escribe deben tener: GM, FF, CA, SZ, KM pero al leer un archivo podría faltar alguno de estos y tendrán que asumir los valores por defecto (1, 4, utf-8, 19, 6.5 respectivamente).
3.  Cualquier tipo de evento, lo importante es que el nombre va en EV[], por ejemplo: EV[3rd Kuksu Mountains Team Tournament]
4.  Nope

Saludos!

**Comment by cglevican** [comment]
Se puede asumir que siempre usaremos los valores por defecto?
