### ISSUE TITLE
Duda y problema Tarea 2

### ISSUE THREAD

**Issue by NoemiCC** [IIC2233-2016-02/Syllabus#176]
Hola, 
Tengo una duda sobre el enunciado de la tarea. Nuestro programa debe incluir un oponente virtual o solo debe dejar que dos personas jueguen?

Y otra cosa aparte, cuando trato de correr el demo todo sale bien pero cuando trato de correr mi programa me sale así:
![captura de pantalla 1](https://cloud.githubusercontent.com/assets/20797815/18185943/619ba674-7076-11e6-80b4-9f6fac05d785.png)
No se si es un problema de mi programa o de los basales que nos dieron pero me da cosa meterme donde no cacho y empeorarlo más :$
Ayuda porfa!

**Comment by jgmontoya** [comment]
Hola, 

No es necesario que implementes un oponente virtual (o IA). Debes dejar que dos personas jueguen pero no debes permitir que ninguno de los jugadores rompa las reglas haciendo jugadas que serían ilegales.

Respecto a la interfaz, si te funciona el demo entonces probablemente el error está en tu código. Revísalo comparándolo con el demo para que te sea más fácil encontrar lo que puedes estar haciendo mal.

No debes modificar la interfaz misma, si crees que encontraste un error en esta entonces puedes comentarlo en la issue #170   para que lo veamos.

Saludos!

**Comment by sormazabal** [comment]
@jgmontoya Una vez que juega "blanco", tenemos automáticamente cambiar para que juegue "negro"?

**Comment by jgmontoya** [comment]
@sormazabal Claro, el manejo de los turnos (junto con toda la lógica del juego) lo tienen que programar ustedes.

Saludos!

**Comment by cglevican** [comment]
Hola, 
Una pregunta respecto a esto, en mi código que contiene la lógica del juego, al momento de abrir la pantalla no siguen corriendo las demás líneas hasta que la cierro, ¿qué podría hacer?.

**Comment by Hernan4444** [comment]
@cglevican La idea es que instancias tus objetos dentro de la gui y que ahí se efectúen los comunicaciones necesarias entre la interfaz y la lógica.
