### ISSUE TITLE
Cargador olvidado

### ISSUE THREAD

**Issue by aaossa** [IIC2233-2016-02/Syllabus#177]
Hola, hoy en la sala de la **sección 1** (B23) se quedó un cargador al final de la clase:

![photo74906175718664566](https://cloud.githubusercontent.com/assets/10425834/18188299/7bae4bdc-7087-11e6-9600-9fa9efad7914.jpg)

**Comment by difischer** [comment]
Es mio!!!  :sweat_smile: :sweat_smile: :sweat_smile: :sweat_smile: :sweat_smile: :sweat_smile: :sweat_smile: :sweat_smile: :sweat_smile: :sweat_smile:
Chanson y donde lo puedo recuperar? :sweat_smile: :sweat_smile: :sweat_smile: :sweat_smile: :sweat_smile: :sweat_smile: :sweat_smile: :sweat_smile: :sweat_smile: :sweat_smile:

**Comment by aaossa** [comment]
Tienes que ir mañana a la oficina de la profe Ivania ( :eyes: ), en el DCC (4° piso de San Agustín). Es la primera pecera, pero si no te ubicas preguntale a la Sole :grin: . Puedes ir entre las 11:30 y las 12 o entre las 13 y las 15:30.
