### ISSUE TITLE
Estados Iguales

### ISSUE THREAD

**Issue by srvasquez** [IIC2233-2016-02/Syllabus#179]
Hola, cuando el es estado del tablero es igual pero con distintas variaciones, me paso que al conectar estos nodos del árbol, el largo de la linea blanca no es el suficiente y no llega al otro nodo, de ante mano gracias.

**Comment by otro-felipe** [comment]
¿Que nodos deseas unir?

**Comment by srvasquez** [comment]
Los del arbol, por ejemplo uno que este en la posicion (3,0) y otro en (5,4)

**Comment by andresbannuraschultz** [comment]
Creo que me pasa algo parecido pero con la linea negra. Al unir dos nodos "lejanos" la linea se corta. Da lo mismo? 
![problema_linea_progra](https://cloud.githubusercontent.com/assets/20782578/18234105/fdb09726-72cf-11e6-8d2d-92142b34189d.png)

**Comment by otro-felipe** [comment]
Tienen razon! hay un problema con la gui. Apenas pueda lo arreglaremos y subiremos la issue correspondiente. Por mientras intenten no preocuparse de ese pequeño detalle :)

**Comment by andresbannuraschultz** [comment]
Dalee, muchas gracias!

**Comment by andresbannuraschultz** [comment]
Al unir dos nodos con estados iguales no se cambia el arbol en la interfaz. He hecho varios "prints" para ir debugueando, y justo antes del metodo add_line(), llego con las cordenadas correctas de los nodos que quiero unir. Puede ser que exista esta sea un problema con la gui? gracias! 
P.D: no se si tenga que ver, pero los nodos que quiero unir con una linea blanca ya estan unidos con otros nodos por lineas negras. Quizas hay un problema con agregar mas de una linea a un mismo nodo (?)

**Comment by otro-felipe** [comment]
#200 Espero que con eso el problema quede resuelto. Saludos!
