### ISSUE TITLE
Duda sobre el árbol

### ISSUE THREAD

**Issue by sormazabal** [IIC2233-2016-02/Syllabus#180]
Perdón si la duda es muy tonta, pero aún no me queda claro como funciona el árbol.
1)Una vez que parte el juego, la zona del árbol está vacía?
2)Luego de que blanco juega una pieza, se pone una ficha con el número de la jugada en el árbol y se procede automáticamente al grupo del negro?
3) O se elige el color según las fichas del árbol en las que uno hace click?

**Comment by jgmontoya** [comment]
Hola!
1) Sí, a menos que estés cargando un archivo. En ese caso se debe mostrar el árbol correspondiente.
2) El juego es por turnos, y esto se ve reflejado en el árbol. Por lo que cuando es el turno del jugador negro y este juega una piedra, entonces esa jugada debiera verse en el árbol.

Te recomiendo que pruebes el juego para que te quede más claro.

Saludos!

**Comment by alainrochette** [comment]
Hola, como se agrega un nodo en el árbol con un poco de trasparencia (como en los ejemplos, mostrando las ramas no usadas)?

**Comment by jgmontoya** [comment]
@alainrochette Esa funcionalidad no está disponible en la interfaz.
