### ISSUE TITLE
Notas

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#181]
Como sabemos que notas llevamos hasta el momento? sea actividad / tarea , etc..  mas especifico, dónde las publican. Muchas gracias

**Comment by aaossa** [comment]
Hola, esto será anunciado cuando lleguen las primeras notas, lo que esperamos que sea durante el fin de semana :grin: Les avisaremos vía SIDING. Para ser más específico, de aquí al lunes esperamos tener publicadas las notas de la AC01 y la AC02, junto con el primer control

**Comment by cjgazali** [comment]
Son muchas notas en el curso!! Favor de mantenerlas 'más actualizadas' para poder tener feedback y sacar conclusiones! ¿Existirán instancias de re-corrección para todo? Si no, ¿para qué cosas?

**Comment by aaossa** [comment]
Se pueden recorregir los controles, las actividades, las tareas y el examen.

**Comment by domingo-valdes** [comment]
Como se manda a recorregir una actividad?

**Comment by aaossa** [comment]
Esto ya fue indicado en el anuncio :ok_hand:

**Comment by cglevican** [comment]
En qué link están las notas?

**Comment by aaossa** [comment]
Aparece en el README, pero el link es [este](https://docs.google.com/spreadsheets/d/1ZHHEkQtoPBi4zOv1uSD9Zz9X0-BEiTH0AjxOuoSSx9g) :ok_hand:

**Comment by cglevican** [comment]
Muchas gracias, aprovechando la atención podrían revisar una pregunta que hice el domingo en el issue #176? :D

**Comment by cglevican** [comment]
Cuando estaran las notas de las primeras tareas?
