### ISSUE TITLE
Aclaraciones respecto a 'pasar'

### ISSUE THREAD

**Issue by jgmontoya** [IIC2233-2016-02/Syllabus#182]
Hola,

Un par de aclaraciones al respecto:
- Cuando un jugador pasa, también debe verse reflejado en el árbol.
- En los archivos 'pasar' se ve como una jugada _sin_ coordenadas
  - B[] o W[]

Se les ha subido además un ejemplo adicional de archivo en formato sgf para que lo puedan ver en un archivo real.

Saludos!

**Comment by andresbannuraschultz** [comment]
Respecto a lo que mencionas, **como** debe verse reflejado en el arbol? Lo que estoy haciendo por ahora es crear un nodo extra en el que el numero no cambia (el numero para mi representa la cantidad de fichas que se han puesto) como se ve en la imagen:
![pasar_reflejado_arbol](https://cloud.githubusercontent.com/assets/11434422/18235242/643cb4d2-72e6-11e6-8371-02b94a602b24.png)

Tambien tengo la duda si el numero debe representar otra cosa (como por ejemplo el numero de jugadas) o si esta bien mientras especifique en el README que significado le di. Eso, gracias!!

**Comment by jgmontoya** [comment]
Hola,
Debe verse reflejado en el árbol en el sentido en que tiene que haber un nodo para esa jugada en el color correspondiente.

Respecto a los números de los nodos, por lo general se usan para indicar el número de la jugada por lo que incrementa independiente de si se trata de poner una piedra o pasar. Sin embargo pueden hacerlo de otra manera y especificarlo en el README tal como dices.

Saludos!

PD: Edité tu comentario recortando la foto, para que fuera más compacto.

**Comment by andresbannuraschultz** [comment]
Perfecto, te pasastee, gracias!!
