### ISSUE TITLE
[Tarea 2] duda con una funcion

### ISSUE THREAD

**Issue by roy350** [IIC2233-2016-02/Syllabus#183]
Disculpen pero tengo dudas de la funcion que hace que si el usuario intenta colocar una ficha encima de la otra aparezca este tipo de mensaje "ERROR: Space E,12 already occupied" quiziera saber que funcion o metodo lo provoca ya que necesito hacer unos if si es que pasa esto. Muchas gracias de antemano!

**Comment by jgmontoya** [comment]
No entiendo bien tu duda pero me da la impresión de que quieres usar la interfaz para guardar/obtener información del juego. 

Si esto fuera así insisto en que **_no**_ pueden usar elementos de la interfaz fuera de los especificados en el enunciado. En caso contrario te agradecería que reformularas tu pregunta o des más detalles.

Saludos

**Comment by roy350** [comment]
Bueno mas que nada es para hacer el "cambio de turnos" si me aparece el mensaje "ERROR: Space E,12 already occupied" que significa que el usuario este poniendo la ficha encima de otra no pase el turno al otro jugador sino que le toque nuevamente a el

**Comment by flobarrios** [comment]
Hola! Eso debes manejarlo con tu estructura y no con la interfaz. Debes idear una manera de guardar de forma inteligente las piezas del tablero para que cuando intentes colocar otra, chequees si se puede poner o no en la posición deseada.

Saludos!

**Comment by roy350** [comment]
Muchas gracias por la respuesta!
