### ISSUE TITLE
Uso de __dict__

### ISSUE THREAD

**Issue by iqacevedo** [IIC2233-2016-02/Syllabus#184]
Hola si para comparar la igualdad de dos objetos creados de una misma clase, utilizo __ dict __ de cada uno para compararlos, se considera como usar diccionarios (por consiguiente prohibido)? o puedo utilizarlo sin problemas?

Saludos!

**Comment by jgmontoya** [comment]
Hola,

No es necesario usar _dict_ para hacer eso, puedes implementar los [_rich comparison methods_](https://docs.python.org/3/reference/datamodel.html#object.__lt__) en tu clase para compararlos.

Saludos

**Comment by iqacevedo** [comment]
Muchas gracias!!!
