### ISSUE TITLE
[Problemas con el PyQt4]

### ISSUE THREAD

**Issue by vmcasas** [IIC2233-2016-02/Syllabus#185]
Cuando quiero instalar el PyQt4 tal y cómo indica la wiki me aparece ese problema :cry: 
![image](https://cloud.githubusercontent.com/assets/20783908/18227602/4b5001b8-7200-11e6-9794-5acd1a612dac.png)

**Comment by aaossa** [comment]
Quizás tienes Windows de 64-bits, es es la versión de 32-bits me parece. Prueba revisando cuál es la versión de Windows que tienes y descarga la versión que corresponda desde la página

**Comment by vmcasas** [comment]
Tengo windows 64 y bajé el PyQt4 de 64 Bits :sob:

**Comment by jgmontoya** [comment]
Es la versión de Python que tienes instalada también de 64 bits? :eyes:

**Comment by vmcasas** [comment]
Uuuuuh no me fijé en eso, llegué e instalé la versión por defecto, revisaré! sorry :disappointed:

**Comment by vmcasas** [comment]
Efectivamente eso era :heart: Gracias y sorry :disappointed: Nunca pensé que fuera algo así :sob:

**Comment by vmcasas** [comment]
Tengo otro problema, con respecto al DEMO.
Cuando corro el demo que viene python me arroja el siguiente error:
![image](https://cloud.githubusercontent.com/assets/20783908/18229200/d6953d84-7245-11e6-82fd-7cdc42011ea8.png)
¿Qué puedo hacer? :cry:

**Comment by jgmontoya** [comment]
Prueba con lo que dijeron en #166

**Comment by lareyes2** [comment]
Hola, a mi no me funciono :c tampoco,  instale todo lo que me dijeron y me aparece en consola cuando intento usar QtGui "ImportError: No module named 'sip'" .¿Que hago? Gracias :)

**Comment by vmcasas** [comment]
Cambié todo a 64 bits y me sigue saliendo lo mismo 
![image](https://cloud.githubusercontent.com/assets/20783908/18283945/36e5b368-743e-11e6-805f-de6866b6b6e2.png) :cry:

**Comment by Hernan4444** [comment]
@vmcasas probaste instalando los dll que faltan?
Donde instalaste pyqt, busca y  abre designer.exe y te dirá que dll te faltan,  tienes que descargar esos de forma manual y ponerlos en la misma carpeta en donde esta ese designer.exe

**Comment by vmcasas** [comment]
Intenté buscar eso, pero es chino para mi jajaja :sob:
