### ISSUE TITLE
Duda en "Ejemplo variaciones Simple.sgf"

### ISSUE THREAD

**Issue by fabraghetto** [IIC2233-2016-02/Syllabus#186]
Todos los archivos de ejemplos, a excepción de "Ejemplo variaciones Simple.sgf", empiezan las variaciones sin paréntesis al inicio, por ejemplo:

"(;GM[1]FF[4]CA[UTF-8] 
SZ[19]KM[6.50]
PW[White]PB[Black]
;B[dd]        <--------------------------------
;W[pd]
;B[dp]...."

Lo que tiene mucho sentido, pues el abrir un paréntesis en las variaciones quiere decir la apertura de una ramnificación en el arbol, y no se puede ramnificar si no hay un arbol antes o raíz.

Sin embargo el archivo  "Ejemplo variaciones Simple.sgf" las variaciones empiezan con:

"(;GM[1]FF[4]CA[UTF-8]SZ[19]KM[6.50](;B[dd])             <-------------------------------------------
(;B[qd]
;W[dd]
;B[pq]
;W[dp]
(;B[oc]
;W[po]....."

Con un paréntesis, a pesar de que no haya ninguna raíz previa, y según yo debería ir escrito de la siguiente manera:

"(;GM[1]FF[4]CA[UTF-8]SZ[19]KM[6.50]
;B[dd]            <-------------------------------------------
(;B[qd]
;W[dd]
;B[pq]
;W[dp]
(;B[oc]
;W[po]....."

Lo digo por que me causa problemas a la hora de hacer el parser
Gracias de antemano !

**Comment by jgmontoya** [comment]
Hola, 

Lo que pasa es que en el archivo "Ejemplo variaciones Simple.sgf" hay una variación en la primera jugada. Dejo imágenes de cómo se ve el árbol de este ejemplo:
![ejemplo_1_root_tree](https://cloud.githubusercontent.com/assets/11434422/18229717/1f5d12d4-7251-11e6-9cf5-6bc89da75b08.jpg)
![ejemplo_1_root_board](https://cloud.githubusercontent.com/assets/11434422/18229718/22191da6-7251-11e6-91eb-5217ccb2265f.jpg)
![ejemplo_1_var1_tree](https://cloud.githubusercontent.com/assets/11434422/18229719/27669f18-7251-11e6-9efc-9b6271de1612.jpg)
![ejemplo_1_var1_board](https://cloud.githubusercontent.com/assets/11434422/18229720/2b44f990-7251-11e6-909f-3788d3744c9d.jpg)
![ejemplo_1_var2_tree](https://cloud.githubusercontent.com/assets/11434422/18229724/477bf5a0-7251-11e6-97f0-43e8259ef9d7.jpg)
![ejemplo_1_var2_board](https://cloud.githubusercontent.com/assets/11434422/18229725/47e082b8-7251-11e6-8f99-d2726025d534.jpg)
![ejemplo_1_leaf1_tree](https://cloud.githubusercontent.com/assets/11434422/18229728/5692f5ca-7251-11e6-867a-4d52bdba0af2.jpg)
![ejemplo_1_leaf1_board](https://cloud.githubusercontent.com/assets/11434422/18229730/5848980c-7251-11e6-866f-d19130578f82.jpg)
![ejemplo_1_leaf2_tree](https://cloud.githubusercontent.com/assets/11434422/18229726/4aee7c8a-7251-11e6-9bf5-4dd7061ef562.jpg)
![ejemplo_1_leaf2_board](https://cloud.githubusercontent.com/assets/11434422/18229727/4b2ff5c0-7251-11e6-9f39-7a23a5f63872.jpg)

Si el archivo fuera como sugieres entonces quedaría una de las lineas de juego con dos jugadas consecutivas para negro (B[dd] y B[qd]) y luego una de blanco que estaría sobre una piedra negra(W[dd]
Es útil pensar que siempre hay un nodo raíz que es el correspondiente al tablero vacío al comenzar la partida.

Saludos

**Comment by andresbannuraschultz** [comment]
Hola, entiendo por que hay un parentesis al principio y la diferencia que significa. Sin embargo, no lo encuentro logico, porque si hay una variacion en la primera jugada es lo mismo que empezar un juego completamente nuevo. Es necesario dar la opcion de volver al inicio del arbol? Es decir, antes de que se haya hecho una jugada. En caso que si, como podria marcar esa opcion en el arbol (dado que solo tengo points blancos o negros). Muchas gracias de antemano.

**Comment by jgmontoya** [comment]
Si se debe dar esa opción.

Puedes marcar esa opción con un nodo blanco (puesto que la primera jugada será de negro).

Saludos!

**Comment by andresbannuraschultz** [comment]
Dale, muchas gracias! Aprovecho de agradecer por la rapidez de las respuestas tambien.
