### ISSUE TITLE
Dudas variaciones

### ISSUE THREAD

**Issue by gabrielpinkman** [IIC2233-2016-02/Syllabus#187]
Holi, tengo un chilión de dudas respecto a la utilidad de la parte de la interfaz que no es el tablero y que tiene una especie de "árbol" con fihas blancas y negras, cuál es la utilidad del "arbol"? Cómo se interpreta? Ayura porfavor :v 
Cuando mas puedo preguntar sobre esto?

**Comment by DiegoAndai** [comment]
El árbol es para registrar variaciones de jugadas desde un punto común, lo que pasa es que tu puedes hacer por ejemplo, 20 jugadas, después decidir que quieres volver al estado de la jugada 10 y hacer un juego totalmente distinto a partir de ahí. Entonces tendrías que mostrar una bifurcación del árbol desde la ficha marcada con el 10, en la cuál una rama contiene el progreso original y la nueva rama va guardando un nuevo proceso. 

Juega una partida en https://online-go.com/ , a la derecha hay un menú en que dice analizar partida, ahí puedes ocupar el árbol :D.

**Comment by jgmontoya** [comment]
Es así como dice @DiegoAndai !

**Comment by mraddatz** [comment]
A medida que se juga hay que ir agregando las ramas al árbol y mostrándolas?

**Comment by jgmontoya** [comment]
Sí.
