### ISSUE TITLE
Sistema de coordenadas

### ISSUE THREAD

**Issue by cglevican** [IIC2233-2016-02/Syllabus#188]
En el enunciado muestra que las coordenadas desde los archivos son del tipo 'letra-letra', cuyo origen está en arriba a la izquierda.
En la gui las coordenadas son 'letra-numero' cuyo origen está abajo a la izquierda.
¿Puedo elegir solo un sistema de coordenadas para jugar y guardar los archivos?

**Comment by jgmontoya** [comment]
No, puesto que eso implicaría que o bien que tienes que modificar la gui o bien que tus archivos dejan de ser archivos sgf válidos.

Saludos!

**Comment by cglevican** [comment]
Gracias!

**Comment by Afalegria** [comment]
o sea que tenemos que poder trabajar con letra-letra y letra-numero ?
no entendi bien, la interfaz funciona con letra-numero(metodos reciben eso), pero los archivos de ejemplo vienen con letra letra...
como hacemos ?

**Comment by jgmontoya** [comment]
Para leer/escribir los archivos sgf **deben** usar las coordenadas del formato esto es letra-letra y con origen en la esquina superior izquierda.

Al usar la interfaz **deben** considerar que esta usa un sistema letra-número y con origen en la esquina inferior izquierda.

Su programa debe poder abrir un archivo y leer correctamente la información de este, relacionando las coordenadas de las jugadas con su equivalente en la interfaz para mostrarlas en la posición correcta.

Saludos!
