### ISSUE TITLE
Arbol

### ISSUE THREAD

**Issue by FranciscoLarach** [IIC2233-2016-02/Syllabus#189]
Hola, no se si estoy entendiendo muy bien el árbol (o el registro del lado), pero que pasa si jugando llego hasta un punto a,b y después parto una nueva serie de jugadas hasta que vuelvo a poner una pieza en a,b (después de haber hecho jugadas distintas)....( y así también puede ser varias veces).
Cuando haga click en uno de esos puntos, la función devuelve solo las coordenadas¿ Como diferencio que nodo seleccioné si lo que retorna para ambos es igual?

**Comment by jgmontoya** [comment]
Con esos (a,b) te refieres a posiciones en el tablero o posiciones en el árbol?

**Comment by FranciscoLarach** [comment]
Si posiciones en el tablero, así funciona ¿no?

**Comment by jgmontoya** [comment]
El método `on_point_click` te permite trabajar con las coordenadas _en el arbol_ de donde el jugador hizo click. 

Vuelve a echarle una mirada al demo para que entiendas como funcionan los diferentes métodos de la interfaz.

Saludos!

**Comment by FranciscoLarach** [comment]
Ok, gracias!

**Comment by jbsaeza** [comment]
y en el caso de que (a, b) sean del arbol?

**Comment by jgmontoya** [comment]
@jbsaeza Tienes que evitar sobreponer piezas en el árbol.  Revisa la #195
