### ISSUE TITLE
default syntax sublime text

### ISSUE THREAD

**Issue by figre** [IIC2233-2016-02/Syllabus#19]
Hola, como puedo hacer para que a la hora de abrir sublime text, este me abra una pestaña con la syntax de python automáticamente?

**Comment by FernandoPieressa** [comment]
Hola! Si te metes a sublime, en la esquina inferior de la derecha hay un boton que puedes apretar y te saldra una lista para elegir uno como se ve en esta foto

![image](https://cloud.githubusercontent.com/assets/13782155/17636824/aab8a63c-60ad-11e6-8185-d32825888682.png)

http://stackoverflow.com/questions/7574502/set-default-syntax-to-different-filetype-in-sublime-text-2
(Link con mas informacion)

PD: Usa google!

**Comment by figre** [comment]
Hola, si busque en google y encontré eso mismo. Mi duda es cuando abro sublime directamente no cuando abro un archivo.py. A lo que me refiero es q cada vez que yo abra una pestaña nueva o abrir directamente la aplicación, este por default sepa que voy a escribir en código python.

Gracias

**Comment by nifalconi** [comment]
Estimado:
Se recomienda revisar el link que envio el ayudante anterior, en este aparecen varias soluciones.

**Comment by aaossa** [comment]
Hola, creo que se lo que quieres y parece que puedea hacer algo solo si creas el nuevo archivo con un _keyboard shortcut_. Ve si [esto](http://stackoverflow.com/questions/11814506/sublime-text-2-default-file-type-on-new-file) te sirve. Si no llegaras a encontrar nada que te sirva... son solo dos clicks :eyes:

**Comment by jgmontoya** [comment]
Hola!

La forma que encontré de hacerlo es mediante el plugin [ApplySyntax](http://facelessuser.github.io/ApplySyntax/)  Te recomiendo instalarlo a través de [PackageControl](https://packagecontrol.io/)
Una vez que lo instales, deberás cambiar las user settings de ApplySyntax (Preferences -> Package Settings -> ApplySyntax -> Settings - User):

```
"new_file_syntax": "Python/Python",
```

Luego guardas la nueva configuración y listo! (Si no funciona de inmediato asegúrate de haber escrito todo bien y reinicia sublime text).

Suerte!
