### ISSUE TITLE
funciones con varios return

### ISSUE THREAD

**Issue by ofvera** [IIC2233-2016-02/Syllabus#190]
Cuenta como usar tuplas si a una función le pido un return con múltiples variables, pero no las guardo, sino que las adjunto a distintas variables únicamente?
Es casi como usar tuplas, pero sin que queden relacionadas entre si las variables, es para su uso momentáneo.

**Comment by jgmontoya** [comment]
Hola,
Puedes usar eso pero debes recordar usar tus estructuras en todo momento.
Por ejemplo: 
Supongamos `def f(): return 1,2,3`
Pudes hacer esto:

```
a = MiLista(*f())
b, c, d = f()
```

**_NO**_ hagas lo siguiente (pues estarás usando las estructuras prohibidas :skull: ):

```
a = [*f()]
b = [f()]
c = f()
```

Saludos!
