### ISSUE TITLE
Información en sgf

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#191]
Corríjanme si me equivoco (confirmen si no):
En nuestro caso, siempre GM=1, CA=UTF-8, FF=4, SZ=19.
Todos los otros datos (EV, DT, etc) que pueden aparecer en un sgf los ignoraremos por completo, pues no se nos pide guardar estos datos.
Conclusión: lo único que nos interesa son las jugadas (B y W) y el KM, en caso de que nos interese que no sea siempre 6.5.

**Comment by jgmontoya** [comment]
Hola, 

Estás en lo correcto, con la salvedad de que si abren un archivo que sí contiene los datos 'ignorables', aunque se le agreguen variaciones deben mantenerse estos datos al guardar el archivo (no se puede perder información del archivo tras pasar por su programa). Por supuesto su programa tampoco se debe caer al leer archivos que contengan esta información.

Saludos!
