### ISSUE TITLE
Formato ejemplos SFG

### ISSUE THREAD

**Issue by fvandeputte** [IIC2233-2016-02/Syllabus#192]
Todos los ejemplos, salvo la famosa pelea entre Chen Yaoye y Lee Sedo, tienen jugadas separadas por un espacio. Es un error o nuestro parser debe hacerlo igual considerando ese "error"?

**Comment by jgmontoya** [comment]
Hola, 

No es ningún error. En su parser deben simplemente ignorar el espacio en blanco y saltos de linea.

Saludos!

**Comment by fvandeputte** [comment]
Ok, gracias !
