### ISSUE TITLE
Discrepancia entre número de columnas de SGF y GUI

### ISSUE THREAD

**Issue by sormazabal** [IIC2233-2016-02/Syllabus#193]
Hola!
Estaba cargando los sgf y me di cuenta de que en el eje X de la imagen del sistema de coordenadas de los SGF va de "a" hasta "s". En contraste, el eje X de la GUI va de "a" hasta "T". Hay algun problema o estoy contando mal las columnas?
Saludos!

**Comment by jgmontoya** [comment]
Hola, 

No hay ningún problema. Revisa las issues #173 #152 

Saludos!
