### ISSUE TITLE
Adaptacion de exctructuras para usar generadores

### ISSUE THREAD

**Issue by iqacevedo** [IIC2233-2016-02/Syllabus#194]
Hola, 

En una parte de mi tarea quería usar una expresión del tipo List(a+1 for a in List(1,2,3,4,5)), y me salia que lo que estaba dentro de la lista era un generador. Busque como solucionarlo,  cree una función que dado un generador me retornara una de mis listas con los items que contenía, sin embargo en la función tuve que usar next(generator) y manejo de errores (cuando terminaba el generador).
Puedo utilizar tranquilamente esta función, o alguna de los cosas que utilice se considera prohibida en esta tarea?

Saludos!

**Comment by jgmontoya** [comment]
Hola, 

No me queda claro respecto a qué cosas en particular tienes dudas de si puedes usar o no.

Por lo que entiendo estas implementando métodos tales como `__getitem__` `__next__` `__iter__` y similares. 

Este tipo de cosas son las que esperamos que implementen en sus estructuras para que tengan el comportamiento esperado así que no hay problemas con eso.

Saludos!

**Comment by iqacevedo** [comment]
Mi duda era principalmente si había algún problema con usar el generador, o el manejo de errores, pero al parecer todo se puede.
Muchas gracias por la rápida respuesta! 

Saludos !
