### ISSUE TITLE
Duda arbol

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2233-2016-02/Syllabus#195]
Hola,
 Me surgió la siguiente duda. Imaginen tengo el siguiente árbol (foto), y estoy en la posicion (2,J). Ahora me devuelvo a jugar a la posición (2,B). Si empiezo a jugar desde esta última posición, la siguiente posición debiera ser abajo del (3,D), pero si hago esto me chocaría con las jugadas anteriores. Que tengo que hacer en este caso?? Modificar todas las filas que tenga problema y desplazarlas una posición para que no me choquen? Es necesario hacer esto último o suponemos que esto no va a suceder.

Gracias de antemano

![foto](https://cloud.githubusercontent.com/assets/20804346/18234710/d6ff48f2-72e3-11e6-8d9c-cd1a87095604.jpg)

**Comment by jgmontoya** [comment]
Hola, 

Debes poder manejar este caso de forma tal que se pueda visualizar claramente las distintas ramificaciones que existen. No es necesario sin embargo que ocupen el espacio de forma óptima.

Para seguir con la situación que nos dices, podrías por ejemplo mover toda la rama que parte en (1,F) una posición hacia abajo para hacer espacio a la nueva variación.

Saludos!
