### ISSUE TITLE
variaciones y arbol

### ISSUE THREAD

**Issue by lefischer** [IIC2233-2016-02/Syllabus#196]
Hola

si el usuario hace click en un nodo en el arbol el juego debe tablero debe cambiar a su estado correspondiente del nodo seleccionado? Como el usuario sabe en que rama esta?

**Comment by bamavrakis** [comment]
No entiendo tu pregunta, puedes reescribirla? 
Salu3.

**Comment by lefischer** [comment]
1) como cambia el usuario de una variacion a otra?
2) como se muestra la rama en que se esta jugando actualmente?

**Comment by jgmontoya** [comment]
Hola, 
1.  Al hacer click en algún nodo del árbol, debe mostrarse en el tablero el estado del juego correspondiente a dicho nodo. Es decir que el usuario cambia entre las variaciones haciendo click en los nodos.
2.  Esto queda a su criterio. Una forma de hacerlo podría ser marcando el 'nodo actual' en el árbol con una 'X' o algo por el estilo. Deben especificarlo en el readme.

Saludos!
