### ISSUE TITLE
Tarea2: duda ejemplo con capturas y variaciones

### ISSUE THREAD

**Issue by bvfernandez** [IIC2233-2016-02/Syllabus#197]
Hola!! tengo una duda/problema. Estoy agregando las piezas en el arbol, pero me dice en ciertos casos que la posicion para agregar ya está ocupada.
Viendo el archivo "ejemplo con capturas y variaciones.sfg" me di cuenta que hay jugadas que se repiten.
Por ejemplo, la primera jugada es B[jj](linea 4 del código), y luego en la linea 50 B[jj] se repite.
Está malo el archivo o yo lo estoy interpretando mal?

**Comment by jgmontoya** [comment]
Hola, 

El archivo es correcto. Lo que pasa es que ocurren capturas y por lo tanto algunas posiciones se 'liberan'.

Saludos!

**Comment by bvfernandez** [comment]
Gracias por tu respuesta!Pero me surgió una duda fundamental... 
Antes creía que tenía que agregar la jugada en el arbol segun la posicion de la variacion (o sea, si la jugada era B[aa] tenía que agregar un nodo con el metodo add_point, en la posicion 0,0) pero así no se vería lineal el arbol.
Entonces.. con qué criterio sé en dónde agregar los nodos?(por ejemplo, si tengo la primera jugada, la tengo que agregar a 0,0?, la segunda a (0,1) (si es que esa jugada corresponde a una jugada sin variacion), la tercera a (1,0) (si es que esa jugada corresponde a una nueva variacion de 0,0)... y así sucesivamente?

**Comment by jgmontoya** [comment]
Tienes que aregarlos de forma tal que se puedan distinguir claramente las distintas variaciones como ramificaciones del árbol.

Esto implica que a veces puede ser necesario mover algunos puntos para hacer espacio a una variación. Quizás lo de #195  te puede ayudar.

**Comment by cglevican** [comment]
Hola, 
En los archivos .sfg se guarda la informacion de las capturas?
