### ISSUE TITLE
Problema PyQt4 "no module named sip"

### ISSUE THREAD

**Issue by lareyes2** [IIC2233-2016-02/Syllabus#198]
Hola,

Instalé PyQt4 , la instalación fue exitosa el problema es que cuando intento utilizar QtGui me sale "no module named sip", hice todo lo que dijeron puse la versión de 64 bit igual que mi versión de Python 3.5, lo hice con pip install ademas descarge el archivo sugerivo mvs.... en otro issu y no funciono.:c
Si importa PyQt4 pero no reconoce QtGui :c

Muchas gracias :) de ante mano.

**Comment by Jaluco** [comment]
Yo estoy teniendo problemas parecidos con el pyQt4, y es demasiado necesario para seguir avanzando con la tarea :(

**Comment by lareyes2** [comment]
Hola,  mi compañero lo arreglo :D ,si te sale el mismo error que a mi  y lo estás corriendo con pycharm, si es así abre git y pon "pip install sip" después metete a la configuración de pycharm y ve los cambios y  debería salir sip y le pones apply o instalar. A mi me funciono así, ojala te sirva :) suerte
