### ISSUE TITLE
Marcar piezas agrupadas

### ISSUE THREAD

**Issue by sormazabal** [IIC2233-2016-02/Syllabus#199]
Hola!
De casualidad hay una forma para marcar gráficamente los grupos de piezas que considero "muertas" (como los triángulos sobre las fichas en la imagen de la página 7 del enunciado)? O debo usar remove_piece sobre el grupo y luego agregar las piezas de nuevo con add_piece y cambiar el texto a una "x", por ejemplo?

**Comment by cjgazali** [comment]
Pregunta similar: tenemos alguna forma de marcar los nodos del diagrama? Como para indicar cuál es el nodo actual, como en ejemplos en páginas 11 y 12 del enunciado.

**Comment by otro-felipe** [comment]
Los nodos solo se marcan al hacerles click encima, no existe una forma de marcar los nodos usando la interfaz dada, así que no se preocupen por ese detalle.

**Comment by jgmontoya** [comment]
Debes usar `remove_piece` y `add_piece` así como dices.

Pueden hacer lo mismo para los nodos del árbol.
Saludos!

**Comment by DiegoAndai** [comment]
Con esta pregunta me surgió la duda: ¿Las fichas del tablero deben llevar el número de la jugada encima, al igual que los del árbol? supuse que si porque add_piece acepta texto, pero el juego online no los tiene. ¿O da lo mismo en realidad?

Muchas gracias.

**Comment by jgmontoya** [comment]
@DiegoAndai No es necesario que pongas el número de la jugada en las piedras del tablero. add_piece acepta texto porque lo necesitarán para marcar las piedras muertas en la parte final.  

Además puede servirles para que revisen más fácilmente que su programa funciona en forma correcta (pueden usar eso para indicar el orden de las jugadas, para indicar qué piedras forman un grupo, para ver las libertades de un grupo, etc...). Si dejan algo de esto **deben** especificarlo en el readme.

Saludos!
