### ISSUE TITLE
Problema python 3.5.2

### ISSUE THREAD

**Issue by figre** [IIC2233-2016-02/Syllabus#2]
Me aparece esto al abrir python y luego se cierra. Alguien sabe como arreglarlo?

![captura de pantalla 31](https://cloud.githubusercontent.com/assets/20782785/17313663/8891497c-582b-11e6-93ab-2a5b483d4173.png)

**Comment by otro-felipe** [comment]
Acabo de investigar un poco y el error podría estar relacionado a una variable de entorno que usa python que no fue seteada durante la instalación (`PYTHONPATH`). Es posible que para resolver este problema debas desinstalar lo que instalaste de python e instalarlo otra vez, pero esta vez debes ejecutarlo en modo administrador. Porfavor nos avisas si te funcionó o no :)

**Comment by figre** [comment]
Borrando las variable de entorno pude lograr hacerlo correr sin problemas. Gracias!
