### ISSUE TITLE
Arreglo a método add_line

### ISSUE THREAD

**Issue by otro-felipe** [IIC2233-2016-02/Syllabus#200]
Se arregló la línea de la gui que decía lo siguiente:

`c2 = (30 + cord_2[0]*30, 30 + cord_1[1]*30)`
por
`c2 = (30 + cord_2[0]*30, 30 + cord_2[1]*30)`

Ahora al agregar una línea entre dos estados iguales, ésta debería unir ambos nodos como corresponde.

> A veces la autocompletación nos juega malas pasadas.
> - Albert Einstein

**Comment by andresbannuraschultz** [comment]
Gracias!!
