### ISSUE TITLE
Errores varios de PyQt4

### ISSUE THREAD

**Issue by sebacruzd** [IIC2233-2016-02/Syllabus#201]
Hola, estoy teniendo varios errores al abrir los archivos sgf de ejemplo al ejectuar el demo.

1) Qt: Untested Windows version 10.0 detected!
Este error lo googleé y supuestamente no afecta en nada, solamente es un aviso pero sigue funcionando todo (igual es molesto y preferiría solucionarlo)

2,3) log4cplus:ERROR No appenders could be found for logger (AdSyncNamespace).
log4cplus:ERROR Please initialize the log4cplus system properly.

Ambos errores (2 y 3) parecen estar dados por la instalación de un software en mi PC, Autodesk360. La solución que encontré en stackoverflow dice que lo desinstale, pero no puedo ya que lo estoy usando para otro ramo actualmente. http://stackoverflow.com/questions/19576586/log4cpluserror-in-python-when-calling-for-tkinter-file-dialog
No he podido solucionarlo aún.

Tengo Windows 10 (64 bits)

Ayuda porfa!

**Comment by Hernan4444** [comment]
@sebacruzd tal como dices ese error de da por autodesk 360,  pero ¿ese error esta interfiriendo en tu código? Puesto que yo también tenia autodesk 360 instalado cuando hice el curso y aunque aparecía ese error, nunca me dio problemas y ningún ayudante me dijo nada. 

Por curiosidad,  en que curso estas usando autodesk 360??

**Comment by sebacruzd** [comment]
Creo que no interfiere, ya que el programa no se cierra y sigue abierto, pero no estoy seguro.
Me hace ruido que los errores 2,3 digan que no se encontró tal cosa y no se pudo cargar otra, pero si dices que no afecta te creo 😁
En todo caso igual es super molesto que salga todo el rato, porque no me deja leer el log tan cómodamente.

Estoy haciendo el ramo CAD/CAM. También si llegara a quedar en el concurso de redbull soapbox con mi equipo lo usaríamos, es por esto que no quiero desinstalarlo.
