### ISSUE TITLE
Tarea2: primera jugada

### ISSUE THREAD

**Issue by bvfernandez** [IIC2233-2016-02/Syllabus#202]
En el enunciado dice que el jugador negro parte jugando, pero en todos los archivos sfg, la primera jugada corresponde a blanco, entonces no entiendo muy bien. Si me lo pudieran aclaran sería perfecto :) 

Otra pregunta, si en el archivo una jugada dice B[aa] quiere decir que el jugador blanco puso una ficha en la cordenada [A,0] o [A,19]?
graciassss!!!!!

**Comment by Sgwa** [comment]
B es de black, W de white. En los archivos en todos parte negro.

**Comment by ndleyton** [comment]
respecto a las cordenadas, depende de cómo tengas definidas estas, pero [aa] se refiere a la esquina superior izquierda del tablero
