### ISSUE TITLE
Error PyQt instalado con pip

### ISSUE THREAD

**Issue by Jaluco** [IIC2233-2016-02/Syllabus#203]
Cuando trato de ejecutar el demo que nos dieron me salta el error
**from PyQt4.QtGui import QLabel, QPixmap, QWidget, QPalette
ImportError: DLL load failed: No se puede encontrar el módulo especificado.**

Lo googlee y nada, nose que hacer si alguien tuvo problemas parecidos, ¿qué hicieron para solucionarlos?

**Comment by mrdelanghe** [comment]
Me pasó lo mismo y me funcionó recién! lo puse en un issue nuevo (#204)
