### ISSUE TITLE
Fix para ImportError: DLL load failed: No se puede encontrar el módulo especificado.

### ISSUE THREAD

**Issue by mrdelanghe** [IIC2233-2016-02/Syllabus#204]
Hola! Recién pude arreglar el error y les cuento cómo para quienes les sirva. (Tengo Windows 10 64-bit.(
Primero, fíjense que hayan instalado Python 32- o 64-bit dependiendo de su computador. Hagan lo mismo para PyQt4. 
Si aún no les funciona, prueben correr designer.exe dentro de la carpeta PyQt4. Puede que les tire error y les diga que archivos .dll les falta. Los pueden bajar de interntet.
A mí no me funcionó nada de eso, el designer.exe me corría perfect. Aquí está lo que sí lo arregló:
- Reinstalé Python en modo administrador para todos los usuarios del pc, seleccionando "add to PATH" en el primer paso.
- Abrí el command prompt en modo administrador y actualicé pip usando el comando `python -m pip install mitmproxy` (que saqué de este [link](http://stackoverflow.com/questions/31172719/pip-install-access-denied-on-windows)) porque al tratar de correr `pip install --upgrade pip` arrojaba error de acceso denegado.
- Después, bajé PyQt4 como .whl desde este [link](http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyqt4) fíjandome que fuese la versión para Python 3.5.
- Finalmente, instalé el .whl con `pip install "archivo".whl` desde la carpeta que lo contenía y me funcionó correr el demo!!
  Ojalá les sirva cabr@s!

**Comment by Jaluco** [comment]
Ahora me tira :
**ImportError: DLL load failed: %1 no es una aplicación Win32 válida.** :(

**Comment by gebalassa** [comment]
Wena. Probaré el link pues en la página oficial ni siquiera aparece PyQt4 para Python 3.5 :-/ Que raro que en esta la tengan. Cualquier cosa confirmo. Gracias :D

**Comment by gebalassa** [comment]
Funcionó **perfect** :smile:

¡Grande Martín!

**Comment by JossCs** [comment]
bajé PyQt4 como .whl 
utilize python -m pip install "Archivo".whl
y me funcionò

**Comment by fryzito** [comment]
Obtuve el mismo error utilizando anaconda, cerré la consola y ejecute en modo administrador y funciono.
