### ISSUE TITLE
Grupo de piedras

### ISSUE THREAD

**Issue by bvfernandez** [IIC2233-2016-02/Syllabus#206]
Hola! tengo una duda... en esta imagen se considera como un grupo de piedras blanco(que comparten libertades)? o alguna tiene que ser adyacente(por arriba,izquierda o derecha?
![image](https://cloud.githubusercontent.com/assets/17594085/18313607/ea301c5e-74e5-11e6-829c-58a855823968.png)

**Comment by jgmontoya** [comment]
Hola,

En la imagen se ven cuatro grupos de blanco, cada uno de una sola piedra.

Saludos
