### ISSUE TITLE
Termino de juego

### ISSUE THREAD

**Issue by lfbesa** [IIC2233-2016-02/Syllabus#207]
Tengo dudas con respecto a cuando termina el juego. Cuando se apreta resign, quién gana y por cuanto?¿Que debe pasar en nuestro juego en ese caso?.
Y también cuando se pasa dos veces seguidas se acaba el juego. ¿Ahí se debe contar el puntaje, imprimir el ganador, la diferencia de puntaje y luego cerrarse?

**Comment by jgmontoya** [comment]
Cuando se apreta `resign` gana el jugador que no se rindió y no gana por ningún valor numérico. Del enunciado: 
![tarea_res](https://cloud.githubusercontent.com/assets/11434422/18325239/5dc054d6-750e-11e6-85c4-e94cb191761d.jpg)

Respecto a la segunda pregunta, también está en el enunciado. Resumidamente es así:
- Pasan dos veces seguidas
- Se marcan las piedras muertas
- Se hace click en el botón `count`
  - Se remueven las piedras marcadas
  - Se calcula automáticamente los territorios
  - Se indica el resultado de la partida

En este punto no se debe permitir hacer más jugadas, sin embargo se debe poder volver atrás en la partida (haciendo click en algún otro nodo) y continuar el juego desde ahí. Por lo tanto no debe cerrarse el juego.

Saludos!

**Comment by lfbesa** [comment]
Muchas gracias. Entonces, ¿el botón count solo se usa cuando ya está terminada la partida o se puede usar en cualquier punto del juego?

**Comment by jgmontoya** [comment]
Solo al final. 

Si quieres agregarle alguna funcionalidad extra para usar durante la partida (ver los territorios que hay hasta el momento, marcar libertades de los grupos, marcar grupos de alguna manera, etc..) eres libre de hacerlo siempre que no interfiera con el comportamiento esperado. Si lo haces **debes especificarlo** en el README.

Saludos!

**Comment by isidoravs** [comment]
Hola, cómo podemos permitir que luego de haber marcado el territorio y calculado el resultado, el jugador pueda volver atrás en la partida? Como no existe el método `remove_square`, las marcas de territorio deberían interferir con las jugadas pasadas, o no?

**Comment by andresbannuraschultz** [comment]
El metodo remove_piece borra cuadrados y piezas!

**Comment by isidoravs** [comment]
@abannura perdón lo acabo de ver, gracias!
