### ISSUE TITLE
Uso de variables globales

### ISSUE THREAD

**Issue by joseluishaddad** [IIC2233-2016-02/Syllabus#209]
Usar variables globales es una mala práctica? como para evitarlas digo yo

**Comment by aaossa** [comment]
Sí, el uso de estas es una mala práctica. ¿Por qué? Porque lleva a que funciones, métodos y el resto de tu código pueda tener comportamientos no obvios, inesperados y ocultos provocados por el uso de esta variable. En [esta pregunta de StackOverflow](http://stackoverflow.com/a/19158418/3281097) puedes encontrar estas razones y punteros a más recursos que apoyan esto.

_En Python, las variables globales no se direferencian de las contantes globales. Las constantes globales no tienen ningún problema, las variables sí_
