### ISSUE TITLE
Librerías permitidas/no permitidas en la T01

### ISSUE THREAD

**Issue by agmardones** [IIC2233-2016-02/Syllabus#21]
Para consultar sobre una librería deben responder esta issue con una pregunta de la siguiente forma:

> Puedo usar la librería nombre_libreria para hacer explicacion_de_lo_que_quiero_hacer

Recuerden especificar en su README qué librerías utilizan!

---
## **Librerías Permitidas**
- random
- sys.exit
- math
- copy
- os.path
- operator
- time
- os
## **Librerías Prohibidas**
- json
- ast
- pickle
- UUID
- re
- inspect
## **Built-ins prohibidos**
- __dict__
- eval (:skull:)
- exec (:skull:)

**Comment by Pyralspite** [comment]
Hola!
Puedo usar la librería ast para convertir el string que retorna la lectura de un archivo json en código que python pueda interpretar?

**Comment by jgmontoya** [comment]
Hola @Pyralspite 

No pueden usar **ast**. La idea es que construyan su propio parser.

Saludos!

**Comment by iqacevedo** [comment]
hola!
No creo que haya problema, pero pregunto de todas maneras. 
¿Puedo usarla libreria math para calcular raices cuadradas?.
saludos

**Comment by flobarrios** [comment]
@iqacevedo si se puede!!

**Comment by andresbannuraschultz** [comment]
Puedo usar la libreria copy para copiar una instancia de un objeto? La idea seria poder trabajar con los atributos de la instancia, cambiandolos, pero siempre guardando los valores originales.

**Comment by Hernan4444** [comment]
@abannura Esta permitido usar copy pero no te lo recomendamos, dale una vuelta a lo echo en clases o si no mira el material para darte una buena idea de como hacerlo, existen mejores formas de hacer lo que quieres.
saludos.

**Comment by andresbannuraschultz** [comment]
Dale, gracias!

**Comment by roy350** [comment]
Hola puedo usar la libreria os.path para hacer verificar si un archivo existe? esto lo utilizare para crear o cargar una partida?

**Comment by flobarrios** [comment]
@roy350 si puedes!

**Comment by sormazabal** [comment]
Hola!
Puedo usar la librería UUID para generar un unique_id?

**Comment by jgmontoya** [comment]
@sormazabal 
**No** pueden usar UUID. 
Saludos!

**Comment by sormazabal** [comment]
Gracias :D

**Comment by DiegoAndai** [comment]
¿Puedo usar la librería abc para ocupar métodos abstractos en herencia? 😃

**Comment by bedefrunner** [comment]
puedo usar libreria yaml?

**Comment by fgvenegas** [comment]
@DiegoAndai  si puedes usar abc :D 
@federicobrunner no puedes usar yaml :(

**Comment by bedefrunner** [comment]
puedo usar libreria re?

**Comment by jgmontoya** [comment]
@federicobrunner **No** puedes usar re.

Da la impresión de que estás intentando hacerle el quite al parser, los rumores dicen que si lo haces llegará @fgvenegas a visitarte por la noche....

En general **no** se aceptará el uso de ninguna librería que facilite la construcción del parser.  

Te recuerdo también que a la hora de preguntar por una librería es mejor si explicas para qué quieres usarla.

Saludos!

**Comment by bedefrunner** [comment]
jajaja ya logre hacerlo sin usas librerias! gracias!

**Comment by alexvonbergeno** [comment]
Hola, se puede usar la librería operator, mas específicamente la función itemgetter?
lo estoy utilizando para ordenar las listas de manera mas rápida en la progradex.

**Comment by DiegoAndai** [comment]
Hola, ¿se puede usar la librería inspect?, ocuparía la función signature para obtener los nombres de los parámetros de un método antes de ejecutarlo (para los menus y display de la ejecución), también para iterar sobre atributos de una clase. Gracias.

**Comment by rodolfopalma** [comment]
@Sgvonbergen sí, puedes usar `operator`.
@DiegoAndai no, no puedes usar `inspect`. Trata de crear alguna estructura (diccionario, clase propia, etc.) que te permita asociar métodos con los parámetros que recibe. De todas formas da la impresión de que puedas estar modelando mal el menú, por lo que te recomiendo darle una vuelta a cómo lo vas a implementar.

**Comment by iqacevedo** [comment]
Hola, 
Puedo utilizar la libreria time?, específicamente para usar time.sleep() mientras capturo un programon, para que el tiempo se detenga y haya mas suspenso.

**Comment by Hernan4444** [comment]
@iqacevedo No hay problema ningún problema en usarla.  :+1: 
Saludos!
Edit: Pero en el readme indica donde implementaste el  time.sleep().

**Comment by iqacevedo** [comment]
@Hernan4444 gracias !!!
Saludos

**Comment by domingo-valdes** [comment]
Si usamos la libreria 'os', el que la funcion usada corra o no va a depender del computador de cada corrector o no?

**Comment by aaossa** [comment]
@domingo-valdes  Depende de lo que estés usando del modulo. Trata de usar funciones que estén disponibles para los distintos SOs.

**Comment by jgmontoya** [comment]
@domingo-valdes  Es cierto, sin embargo no debieran usar nada muy rebuscado en esta tarea y en general lo de `os.path` debiera correr bien en distintos sistemas operativos.

**Comment by domingo-valdes** [comment]
@jgmontoya Es solo para usar un os.path.isfile()

**Comment by jgmontoya** [comment]
@domingo-valdes No debieras tener problemas con esa función, úsala tranquilo :smile:

**Comment by sormazabal** [comment]
Se pueden usar defaultdicts en la Tarea?

**Comment by FernandoPieressa** [comment]
@sormazabal Si puedes usar defaultdicts en la tarea. Saludos!

**Comment by DiegoAndai** [comment]
Ya preguntaron por os pero arriba solo aparece listado `os.path`: ¿se puede ocupar `os.makedirs`? es para hacer una carpeta para cada jugador y mantener los archivos de cada uno ordenados. Si la respuesta es si, ¿podría tener problemas entre plataformas con esta función? Gracias.

**Comment by jgmontoya** [comment]
@DiegoAndai Sí puedes usar `os.makedirs`  Y no debiera haber problemas de compatibilidad.

**Comment by domingo-valdes** [comment]
Puedo importar itemgetter de operator?

**Comment by joseluishaddad** [comment]
Hola! puedo usar collections.deque ?
salu2

**Comment by domingo-valdes** [comment]
Y hacer un 'from collections import namedtuple', para aplicar la materia de clases?
