### ISSUE TITLE
Buscando a Bastian D:

### ISSUE THREAD

**Issue by sfga** [IIC2233-2016-02/Syllabus#212]
Hola,

   envié un mail a Bastian @bamavrakis por un asunto sobre la actividad de mañana (AC05), pero no me contesta :( ,¿Con quién (otra persona que pueda ver el tema) me puedo contactar (vía mail)?

Saludos.

**Comment by aaossa** [comment]
Si no pesca pueden ubicarme a mi, y hago reaccionar a Bastián :grin: Le diré que revise ahora

**Comment by sfga** [comment]
Muchas gracias Antonio por responder: te cuento que ya resolví el asunto con Bastián, a quién también le doy las gracias.

**Comment by bamavrakis** [comment]
Para eso estamos :baby:
