### ISSUE TITLE
captura o suicida?

### ISSUE THREAD

**Issue by lefischer** [IIC2233-2016-02/Syllabus#213]
que se evalua primero? si es movimiento es suicida o si hay captura?

**Comment by jgmontoya** [comment]
Hola,

Eso que preguntas está en el enunciado:

![ejemplo_enunciado](https://cloud.githubusercontent.com/assets/11434422/18363086/880dcb7e-75d6-11e6-9aa3-e684d082c8b5.png)

Saludos!

**Comment by lefischer** [comment]
Hola,

queria saber  si la regla Ko y los movimientos suicidas son mutuamente excluyentes

**Comment by jgmontoya** [comment]
No te entendí bien :sweat_smile:  , puedes explicar un poco a qué te refieres con eso?

**Comment by lefischer** [comment]
al jugar en que orden se evaluan ko, captura y suicida. Ademas si un movimiento no cumple con la regla de ko o es suicida entonces le toca al otro jugador?

**Comment by jgmontoya** [comment]
Si como resultado de hacer una jugada estás violando la regla de ko, entonces no debes permitir hacer esa jugada.

Respecto a si pierde el turno: #211

**Comment by bvfernandez** [comment]
al hacer una jugada suicida se debe agregar al arbol aunque sea jugada suicida?

**Comment by jgmontoya** [comment]
No, puesto que al no ser una jugada válida no debes permitir al jugador realizarla.
