### ISSUE TITLE
Administrativa

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#215]
En algun momento tendremos la instancia de "criticar" el ramo? vale decir, comentar nuestras apreciaciones respecto a la metodologia, evaluaciones, etc.

**Comment by ivaniadg** [comment]
Hola,

Existe la encuesta de medio semestre que tiene por objetivo que puedan hacer observaciones al desarrollo del curso para poder realizar cambios antes del término del semestre. También existe la posibilidad de que puedas enviar un email a los profesores y/o al coordinador con tu inquietud. 

Saludos
