### ISSUE TITLE
Visualización Arbol

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-02/Syllabus#216]
Hola !
Como podría arreglar esto:
![arbol](https://cloud.githubusercontent.com/assets/13814193/18391587/cbbf8c5a-7684-11e6-9354-8ec9cf7c5a55.png)

Agrego nodos al arbol, se agregan correctamente pero la caja que los contiene no se agranda y hay que mover la barra para poder seguir viéndolo.
Gracias !

**Comment by isidoravs** [comment]
Si agrandas la ventana del juego, el espacio para el árbol es mayor y se ve mejor!

**Comment by ndleyton** [comment]
Hay alguna forma que la interfaz se vea bien en una pantalla con alto dpi?
todo se ve chico y amontonado :/

**Comment by Iruretagoyena** [comment]
@isidoravs  Jajaja que pavo, gracias !
