### ISSUE TITLE
Fechas de entrega

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#217]
Se corrió la tarea 2 para el miércoles...
¿Se entregará en enunciado de la tarea 3 ahora? Hoy viernes o mañana...
¿Se correrán las entregas en general? Hasta ahora iban todos los viernes por medio al parecer...
Pregunto porque influye demasiado en qué será de mí estos días :grin:
Muchas gracias!

**Comment by mjjunemann** [comment]
Las entregas en general no se corren, es por temas administrativos.
Enunciado de la Tarea 3, se publicará después de la entrega de la Tarea 2.

**Comment by cjgazali** [comment]
Con la segunda pregunta mi preocupación era que la entrega de la tarea 3 no fuera a ser para el viernes a la vuelta del 18, si no que hagan el 'desfase' oportuno (o una tarea que tome menos tiempo...). No pregunté muy bien, disculpa.

**Comment by domingo-valdes** [comment]
A qué hora cierra el plazo de entrega para la Tarea 2? A las 23,59 como siempre?

**Comment by mjjunemann** [comment]
@domingo-valdes: sí, se entrega a las 23:59.
