### ISSUE TITLE
Prisioneros 

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#218]
Cuando pincho un nodo del árbol, el tablero tiene que volver a su estado hasta ese punto, los puntajes de prisioneros también cambian? 🤔

**Comment by jgmontoya** [comment]
Claro, deben considerarse solo los prisioneros que se tenían hasta ese momento en el juego.

Saludos!

**Comment by narierao** [comment]
tomo en cuenta solo a ultima variacion del arbol? vale decir la variacion de más abajo?
porque por ejemplo, tenemos la rama principal del arbol, y se crea una variacion y se juega en esa variacion, ahora, si dentro de esa variacion se crea otra, tomamos en cuenta la variacion anterior dentro de los puntajes?

------------------------------------------------ rama principal
.............. ------------------------------------  primera variacion
. ......................-----------------------------  segunda variacion
. ....................................................-----J      J es la ultima jugada

los puntos son espacios que no me dejo poner la pagina :cry: 

considero desde J devolviendome por cada nodo padre de la variacion?
Espero se enienda mi duda :/

**Comment by jgmontoya** [comment]
No te entendí :disappointed_relieved: 

Cada variación debe considerar las capturadas para esa variación, desde la raíz hasta el nodo que corresponda.

**Comment by narierao** [comment]
gracias! eso era xd
