### ISSUE TITLE
Regla de los ojos Tarea 2

### ISSUE THREAD

**Issue by srvasquez** [IIC2233-2016-02/Syllabus#219]
Hola, ahora que nos dieron más tiempo me di cuenta que existen falsos ojos, es decir, a pesar de que una grupo de piedras tenga mas de un ojo estos realmente no mantienen al grupo vivo 
![consulta](https://cloud.githubusercontent.com/assets/17626486/18411545/cbc4500c-774f-11e6-9b61-db4de61574bc.png)
en el ejemplo si pongo una ficha en el espacio rojo sería una jugada válida, podré agregar esta regla a mi GO, porque no esta especificado en el enunciado, de ante mano gracias.

**Comment by jgmontoya** [comment]
Hola

Efectivamente hay ojos falsos. Sin embargo esto no es ninguna regla especial ni nada que no esté contemplado en el enunciado. 

En el ejemplo que pones, lo que sucede es que en realidad no se trata de un solo grupo negro, si no que hay 5 grupos. De hecho si te fijas bien el otro ojo también es falso.

En definitiva, deben poder distinguir entre grupos con dos ojos ('reales') y grupos que aparentan tener dos ojos pero que alguno (o ambos) son 'falsos'.
Saludos

EDIT: Agrego también que no existe una 'regla de los ojos' si no que es una propiedad que se deriva del hecho de no permitir jugadas suicidas.
