### ISSUE TITLE
[Tarea 1] Sobre jsonToDict y dictToJson

### ISSUE THREAD

**Issue by roy350** [IIC2233-2016-02/Syllabus#22]
Disculpen pero no me quedo claro si nosotros debemos crear un metodo equivalente a jsonToDict y a dictToJson por que al principio dice que podemos usar el segundo pero mas adelante dice que debemos crearlo, o fue un error de enunciado y tenemos que crear un equivalente del primero no mas? Gracias!

**Comment by FernandoPieressa** [comment]
Hola! Efectivamente, la idea es que ustedes creen su propios metodos de parser para leer los json y escribirlos. Ese archivo .py que les entregamos es  solamente para que puedan usarlo para poder seguir con la tarea por si no les sale el parser (porque sino no podrian hacer casi nada del resto de la tarea) o por si quieren dejar el parser para el final. 

Si no hacen el parser y entregan la tarea con los metodos entregados en ese archivo no tendran esa parte del puntaje de la tarea.

Recuerden que la libreria json esta prohibida para la tarea!

Saludos!

**Comment by roy350** [comment]
Ya muchas, lo otro estaba intendando usar el archivo que uds subieron pero no me crean un archivo py de los json por que eso hace jsonToDict o no?

**Comment by FernandoPieressa** [comment]
No, lo que hace ese metodo es leer los archivos json en su programa, transformandolos en diccionarios para que puedas utilizarlos como bases de datos de informacion para tu tarea. No te entrega otros archivos .py.
Es decir, te entrega una variable que es un diccionario con la informacion que habia en ese json.

**Comment by Hernan4444** [comment]
Si tu duda ya fue resuelta, no olvides cerrar la issues

**Comment by flobarrios** [comment]
Hola! habían unos typos en esa parte del enunciado que no dejaba muy claro lo que preguntaste (se subió una nueva versión). **Solo deben crear un método equivalente a jsonToDict**, el método dictToJson lo pueden usar libremente.

Saludos!

**Comment by fgvenegas** [comment]
Tal vez tiene que ver que en tu path intentas abrir una carpeta en vez de un archivo, intenta cambiar eso y ve que pasa

**Comment by Snorlax8** [comment]
Hola! Me quedó una duda con lo que dijo @flobarrios : el método dictToJson lo podemos usar aunque use la librería json para funcionar?

**Comment by jgmontoya** [comment]
@Snorlax8 Sí, ese lo pueden usar.

**Comment by gabrielpinkman** [comment]
Pero lo que dicen no tiene sentido, si no se puede usar la libreria json, entonces cómo se puede usar el método dictToJson, si este usa justamente la librería json?

**Comment by FernandoPieressa** [comment]
@gabrielpinkman La libreria json SOLAMENTE la pueden usar para usar dictToJson.

**Comment by jgmontoya** [comment]
@gabrielpinkman La idea es que construyan su propio parser de json. Para esta tarea **no** es necesario que creen un método para generar un archivo json, por eso se les entrega _dictToJson_ para que lo usen libremente. 

Si quieres además de hacer el parser crear tu propio método para escribir archivos en formato json eres libre de hacerlo, pero no será evaluado y si tus json quedan mal escritos puede generarte problemas. Por esto que te sugiero que avances con el resto de la tarea y que primero termines lo que se pide.

Saludos!
