### ISSUE TITLE
Orden de término de juego

### ISSUE THREAD

**Issue by ndleyton** [IIC2233-2016-02/Syllabus#222]
Hola, me entró la duda sobre cuál sería el orden óptimo al terminar el juego. 
Si se llega al término de juego a través de rendirse o dos pasar, se pasa a la fase de selección de piezas muertas, luego la eliminación de ellas y luego el conteo de territorio?
Qué ocuure al presionar 'count' en medio de una partida?
debe pasar por las otras fases para que cuente?

**Comment by jgmontoya** [comment]
Hola, 

Si algún jugador se rinde no es necesaria la parte de selección de piedras muertas ni la de conteo de territorio.

Luego de que los dos jugadores pasen consecutivamente, tal como se explica en el enunciado el orden de lo que pasa es el siguiente:
- Selección de piedras muertas
  - Debes permitir seleccionar/deseleccionar grupos (que no tengan dos ojos).
  - **No** debes permitir seleccionar aquellos grupos que tengan dos ojos.
- Click en `count` para indicar que se ha terminado de seleccionar grupos de piedras muertas.
- Se eliminan las piedras seleccionadas, sumándose a las capturadas del jugador correspondiente (son consideradas prisioneros)
- Se cuenta el territorio y se despliega el resultado.

Si se presiona `count` en medio de la partida no es necesario que ocurra nada, sin embargo pueden implementar su propia funcionalidad para esto y especificarla en el readme. Por ejemplo pueden ocuparlo para indicar los distintos grupos, indicar las libertades actuales de los grupos, contar el territorio hasta el momento, etc..

Saludos!
