### ISSUE TITLE
AC03

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#224]
como puedo saber cual es el commit que revisaron de la actividad 3?

**Comment by aaossa** [comment]
Hay una issue en tu repo con título "AC03" dentro de la que debería aparecer el commit que se corrige :ok_hand:

**Comment by narierao** [comment]
@aaossa Es que me sale la actualización del programon, que subí al salir de la clase, por ende debían revisar la de mi compañero :/ que puedo hacer?

**Comment by aaossa** [comment]
Solamente tu compañero entregó la actividad. Eso fue lo que se corrigió.
