### ISSUE TITLE
Contador de piedras muertas

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-02/Syllabus#225]
Hola !
Cuando se termina el juego y quedan marcadas las piedras, el enunciado dice que debemos dejar la opción de que el jugador pueda marcar/desmarcar las que quiera. Debemos permitirle hacerlo a **todas** las piedras, aunque no estén muertas ?
Gracias

**Comment by jgmontoya** [comment]
Hola,

¿Te refieres al bonus? (Asumiré que no)

Cuando termina el juego debes dar la opción de marcar los grupos de piedras muertas. Tal como aparece en el enunciado, **no** debes permitir marcar grupos que tengan dos ojos. 

Saludos!

**Comment by Iruretagoyena** [comment]
@jgmontoya  Me refiero al bonus

**Comment by jgmontoya** [comment]
Ups :sweat_smile: 

Si implementas el bonus la idea es que se mantenga lo anterior, pero la única diferencia es que al terminar el juego se muestran automáticamente aquellas piedras que debiesen ser eliminadas. 

Es decir debes permitir marcar/desmarcar aquellos grupos que **no** tengan dos (o más) ojos. 

Esta explícito en el enunciado :eyes: 

![bonus_enunciado](https://cloud.githubusercontent.com/assets/11434422/18414982/974af24a-77ae-11e6-84d9-bfe1feca18fa.png)

Saludos!

**Comment by Iruretagoyena** [comment]
Buenísimo, muchas gracias ! (y perdón, jajaja)

**Comment by Iruretagoyena** [comment]
@jgmontoya Última cosa, no entendí lo de "res" al mostrar los puntajes si es que uno de los jugadores renuncia.  Como es ?

**Comment by jgmontoya** [comment]
Lo de mostrar `+` `res` es porque cuando uno de los jugadores se rinde antes del fin de la partida, no se cuentan los territorios. En este caso no se gana por una cantidad numérica mientras que normalmente se anota `letra` `+` `diferencia de puntaje`.
