### ISSUE TITLE
Definición de grupo vivo

### ISSUE THREAD

**Issue by nicovsj** [IIC2233-2016-02/Syllabus#227]
En el enunciado se especifica que al momento de remover las piedras muertas no se debe pemitir al usuario eliminar grupos con dos o más ojos. Lo que entiendo es que un grupo vivo es aquel que tiene al menos dos ojos. 

Hasta ahí todo bien, pero observando el siguiente final de partida:

![imageedit_2_7619289923](https://cloud.githubusercontent.com/assets/13756829/18420193/22794f80-7843-11e6-8e1e-5d4fb27ba1d7.png)

Si es que entendí bien la definicion de ojos, puedo notar que en estricto rigor el grupo mayor de piedras blancas no tiene dos ojos. Esto implica que si el usuario hiciese click en una de las piedras que forman parte de este grupo no se impedirá que se eliminen del tablero, lo cual parece no ser correcto.

¿Se debe permitir esta eliminación?  ¿O es que no estoy entendiendo correctamente los conceptos de grupo vivo y ojos? Gracias de antemano.

**Comment by jgmontoya** [comment]
Hola,

En el ejemplo se debe permitir seleccionar cualquier grupo de piedras, puesto que si te fijas bien, ningún grupo tiene 2 ojos en estricto rigor.

 Sin embargo para el bonus se debiesen marcar automáticamente las que se ven con  Δ (esas serían las que seleccionarían los usuarios en caso de que la partida terminase).

Saludos!

**Comment by nicovsj** [comment]
Perfecto, Gracias!
