### ISSUE TITLE
Codigo-pauta de T01 y T02

### ISSUE THREAD

**Issue by mcorreaiz** [IIC2233-2016-02/Syllabus#229]
Hola, queria pedir por favor que suban algun codigo solucion hecho por ustedes, de cada tarea, para asi tener feedback e ideas (sobre todo para aprender de aspectos como orden, relacion entre clases, jerarquia, modularizacion, tecnicas) para las proximas tareas. 

Gracias!

**Comment by cglevican** [comment]
Sino que suban la rúbrica con las ponderaciones al publicar las tareas es una opción.

**Comment by flobarrios** [comment]
Hola! Las soluciones de las tareas no se publicarán. Esto por varios motivos, principalmente porque no hay una única solución válida y hay elementos que se repiten a través de los semestres como el parser por lo que al subir una solución de éste, no podríamos evaluarlo en semestres posteriores. Si tienes dudas de alguna posible solución, puedes juntarte con algún ayudante para que te explique una.

Respecto a las ponderaciones, se está evaluando que los próximos enunciados tengan en los títulos de cada sección el porcentaje correspondiente.

Saludos! 😄
