### ISSUE TITLE
[Tarea 1] PP de Programones

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#23]
los programones tienen ataques contados? para saberr si en el centro programon debe restaurarse sus cantidades (comparandolo al juego real) igualmente con la vit de cada uno

**Comment by FernandoPieressa** [comment]
![captura](https://cloud.githubusercontent.com/assets/13782155/17644244/5c6bfd88-614f-11e6-8ae7-50db582621a2.PNG)

Eso creo que responde la duda. Saludos!

**Comment by narierao** [comment]
Gracias! No sé cómo se me pasó eso jajaja

**Comment by Hernan4444** [comment]
Si tu duda ya fue resuelta, no olvides cerrar la issues
