### ISSUE TITLE
Corrección AC03

### ISSUE THREAD

**Issue by sfga** [IIC2233-2016-02/Syllabus#232]
Hola,

según el último aviso del SIDING (10-09-2016 23:44) las notas de la AC03 están publicadas. Sin embargo, no tengo la corrección de la AC03. Les quería pedir que revisaran esta situación por favor.

Saludos.

**Comment by ivaniadg** [comment]
Hola, 
Los casos particulares se revisan por email no por las issues. Envía un email a Bastian con tu caso.
Saludos!
