### ISSUE TITLE
Entrega del diagrama de clases y del README T2

### ISSUE THREAD

**Issue by Gonzalo-Perez** [IIC2233-2016-02/Syllabus#233]
Para la entrega de la tarea 2 también se debe entregar un diagrama de clases?
Si la respuesta es si, este puede entregarse junto con el README (hasta 1 día después)?

De antemano, gracias !

**Comment by FernandoPieressa** [comment]
No, para la tarea 2 no necesitan entregar un diagrama de clases!

Saludos!
