### ISSUE TITLE
List comprehensions en mi clase Lista

### ISSUE THREAD

**Issue by NachoCasta** [IIC2233-2016-02/Syllabus#234]
Hola. 
Mi clase lista recibe como unico argumento para instanciarla un iterable. En este caso, puedo usar list comprehensions?

Por ej, lo siguiente lo puedo hacer con mi clase lista

``` python
>>> Lista(i for i in range(10))
>>> [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

Cabe mencionar que lo que retorna no es una lista, solamente el **repr** se ve igual

**Comment by iqacevedo** [comment]
Hola según por lo que me comentario en #194 si se podría usar.
Saludos !

**Comment by NachoCasta** [comment]
Tienes razon, gracias!
