### ISSUE TITLE
get_asset_path()

### ISSUE THREAD

**Issue by DiegoAndai** [IIC2233-2016-02/Syllabus#235]
Hola, tratando de ordenar mi tarea, hice un módulo que importara todo (la gui y mi código) desde una carpeta y lo corriera. Ocurrió que las piezas del tablero no aparecían, sin embargo, los nodos del árbol, que parecen ser la misma imagen que las piezas, no tenían problema. Revisé los módulos de la gui y me di cuenta que para todas las imágenes del juego, ya sea el tablero, las lineas, o los nodos del árbol, se ocupaba la función get_asset_path(), excepto para las piezas del tablero. Le agregué esta función y mi problema se solucionó. ¿puede ser que se les haya olvidado ponerlo?

Las líneas que tuve que modificar fueron:

```
89- self.setStyleSheet("background-image: url(gui/assets/white_piece.png);")
92- self.setStyleSheet("background-image: url(gui/assets/black_piece.png);")

```

Reemplazándolo con:

```
89- self.setStyleSheet("background-image: url({});".format(get_asset_path("white_piece.png",sep="/")))
92- self.setStyleSheet("background-image: url({});".format(get_asset_path("black_piece.png",sep="/")))

```

de la clase GOPiece del módulo board

**Comment by sebacruzd** [comment]
A mi me está pasando lo mismo, lo extraño es que con el demo que venía si me aparecen, pero al usarlo en otro caso, por ejemplo al hacer add_piece, y ahí le pongo add_point, dejan de aparecer y son "imagenes invisibles" porque en el arbol el nodo se agrega. (la posición y el espacio de la imagen se ocupa por algo invisible)

Con "imagenes invisibles" me refiero a que la parte del arbol despues de poner cierta cantidad de fichas empieza a expandirse, tal como haría si tuviera más imágenes, para que me pueda desplazar y verlas.
