### ISSUE TITLE
Eliminación de piedras

### ISSUE THREAD

**Issue by fnmendez** [IIC2233-2016-02/Syllabus#236]
¡Hola!

Quisiera saber si después de pasar dos veces se debe:

1- Poder eliminar los grupos clickeando cualquiera de sus piedras, restringiendo **solamente** los grupos que tienen *_dos ojos en sí_.

2- Poder volver a un nodo anterior

*No contando los grupos que forman dos ojos ayudándose de "otros" grupos (que no están conectados explícitamente con una piedra pero sí con un espacio que corresponde una jugada inválida para el otro)

**Comment by jgmontoya** [comment]
Hola Franco,
1. Debes restringir solo los grupos que tengan íntegramente dos ojos, es decir que sus piedras se encuentren directamente conectadas.
2. Sí, debes poder volver a un nodo anterior incluso si ya se hizo el conteo de puntos de esa variación.

Saludos!

**Comment by DiegoAndai** [comment]
Sobre el punto 1: No entiendo porqué los ojos tienen que ser formados por un sólo grupo, según yo la regla era que el grupo sea efectivamente "inmortal", de hecho en el enunciado hay ejemplos de grupos separados que forman dos ojos:

<img width="244" alt="captura de pantalla 2016-09-14 a las 6 12 59 p m" src="https://cloud.githubusercontent.com/assets/16889233/18530099/4bf1c4ea-7aa6-11e6-8c48-0cb760d2b0a9.png">

De hecho como tú dijiste en #219 , la regla se deriva de que no se permitan jugadas suicidas.

**Comment by jgmontoya** [comment]
Hola,

Efectivamente hay grupos inmortales cuyas piedras no están directamente conectadas. Son grupos conectados por sus ojos.

Lo de restringir a grupos que tengan dos ojos en sí es para simplificarles un poco esa parte de la tarea. Si quieres puedes hacerlo incluyendo estos grupos (**_especifícalo en el readme**_) pero ten en cuenta que debe funcionar correctamente bajo lo planteado.

Saludos!
