### ISSUE TITLE
Termino Juego

### ISSUE THREAD

**Issue by fringlesinthestreet** [IIC2233-2016-02/Syllabus#237]
Una vez que se termina el juego por:

1) Resign

2) 2 pass seguidos *

*: asume que ya se removieron las piedras y se contaron los territorios.

Se tiene el resultado final del juego. 

Luego, ¿qué se debe hacer? ¿Se puede apretar en otro nodo del árbol y continuar con una variación del juego?, ¿o el juego termina y sólo se puede guardar el resultado en un archivo sgf?

En caso de que la respuesta sea que sí se puede continuar con una variación después de tener un resultado final. Luego, ¿se debe guardar en un nodo del árbol el estado 'Terminado' (con el resultado de esa rama)? ya que si se crea una 'variación' (retroceder un nodo en el árbol y volver a pasar) en donde se remueven otras piedras (si terminó por 2 pass seguidos), quizás cambian los territorios por lo que puede cambiar el resultado final.

**Comment by jgmontoya** [comment]
Hola, 

Sí, debes poder volver a un nodo anterior y continuar desde ahí. (#236 )
Si retrocedes a un nodo anterior pero la jugada es la misma, entonces no estás creando una variación. Recuerda que una variación solo ocurre cuando las jugadas divergen. Por lo tanto si ocurre esto estarías reescribiendo el resultado anterior con el nuevo resultado.

Saludos!

**Comment by fringlesinthestreet** [comment]
Entonces una partida puede tener muchos finales (de distintas ramas, ya corregí eso de las variaciones inmediatamente iguales). 
¿Cómo se guardan las partidas?, ya que en el archivo sgf debe haber una metadata de RE[] con el resultado adentro. ¿Se une a la 'sección' de jugadas? (en la rama correspondiente) o debe estar en el inicio con el resto de la metadata.

**Comment by jgmontoya** [comment]
Para guardar el resultado en el archivo se considera sólamente el de una variación y el metadata `RE[ ]` debe estar junto al resto (al inicio).

Queda a su criterio cuál rama usarán para esto (por ejemplo la variación con más jugadas, la primera en haber sido calculada, etc..)  pero **_deben**_ especificarlo en el readme.

Saludos!
