### ISSUE TITLE
Duda github. Colaboraciones y graficos

### ISSUE THREAD

**Issue by NachoCasta** [IIC2233-2016-02/Syllabus#239]
Hola,

Quería saber por que razón no aparecen mis commits en los gráficos de mi repo personal. Debo hacer algo para que aparezcan?

Gracias

**Comment by aaossa** [comment]
Cuales gráficos?

**Comment by NachoCasta** [comment]
Los que aparecen cuando uno apreta Graphs arriba a la derecha en github en cualquier repositorio, para ver las contribuciones de las distintas personas.

**Comment by aaossa** [comment]
Ah ya lo vi :grin: Es porque al parecer tu usuario de GitHub usa un correo distinto que el mail que pusiste en git al configurarlo localmente. Por lo tanto, reconoce tus commits hechos con ese mail como si fueran de otro usuario, uno que no está en GitHub, y por ello no cuentan como colaboraciones tuyas.

**Comment by aaossa** [comment]
[Related](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#you-havent-added-your-local-git-commit-email-to-your-profile)

**Comment by NachoCasta** [comment]
Gracias lo acabo de cambiar y ahora si me los marca!
