### ISSUE TITLE
[Tarea 1] "Centro programón" y equipo

### ISSUE THREAD

**Issue by cglevican** [IIC2233-2016-02/Syllabus#24]
tengo una duda sobre la oración "es donde se puede acceder al PC de Bastian para cambiar del equipo a algun programon capturado que se encuentre en el PC (equipo tiene un máximo de 6 programones)", ¿a qué equipo se refiere?, ¿eso quiere decir que cada jugador tiene máximo 6 programones y ahí puede intercambiarlos por otros que no haya capturado necesariamente?

**Comment by FernandoPieressa** [comment]
Hola! Se refiere a que cada jugador puede tener muchos programones, pero solo llevar hasta 6 en su equipo para pelear/etc..
Entonces cuando van al PC de Bastian pueden cambiar alguno de los programones que tiene guardado ahi (que son los que efectivamente a capturado alguna vez) con uno del equipo para poder ser usado en peleas/etc..

**Comment by cglevican** [comment]
Super, gracias.
