### ISSUE TITLE
Letra "I" en el tablero

### ISSUE THREAD

**Issue by juliandewulf** [IIC2233-2016-02/Syllabus#240]
Hola, entre la "h" y la "j" falta la la "i",

que se supone que hacemos con la letra "i" del tablero? 
tengo todo en base a la tabla ascii y despues de muchas horas buscando qué me causaba un error, me di cuenta de esto...

Posibilidad de omitirlo? no creo alcanzar a cambiarlo ahora

**Comment by ivaniadg** [comment]
Hola!

Lamentablemente, no existe la posibilidad de omitir ese error. Hay tres issues (#152, #173 , #205 ) que preguntaron lo mismo.

Saludos
