### ISSUE TITLE
Cosas que agregar al readme.

### ISSUE THREAD

**Issue by DiegoAndai** [IIC2233-2016-02/Syllabus#241]
Hola,

podrían agregar una etiqueta README para las issues en que indican algo que especificar en este, por ejemplo #237 y #236 de la Tarea 2. Así no se le pasa a nadie algo que especificar. Es sólo una sugerencia 😄.

Saludos.

**Comment by jgmontoya** [comment]
Buena idea!

**Comment by jgmontoya** [comment]
Lo considerarémos para las futuras tareas, de momento te recuerdo que puedes buscar entre las issues. 

Por ejemplo si buscas por
 `readme label:"Tarea 2"` 
entonces te saldrán las isues con el label `Tarea 2` y donde se mencione `readme`

Saludos!

**Comment by DiegoAndai** [comment]
Claro, así lo hice en las otras dos. Era sólo para organizarlas y tenerlas más a mano.
