### ISSUE TITLE
Agradecimientos Tarea 3

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#243]
Quiero agradecer públicamente a los ayudantes por no subir el enunciado de la tarea 3 la semana pasada. He tenido tres días de perfecta paz mental y eso es muy valioso. A nombre además de todos aquellos que lo agradecen en silencio, felicitaciones por el mejor atino del semestre. :metal:

**Comment by ricardor4** [comment]
Fue genial, pude estudiar incluso para mis otros ramos, estudié en 3 días mas análisis real que en todo lo que llevamos de semestre.

**Comment by sormazabal** [comment]
Me sumo a las palabras de @cjgazali. Muchas gracias por dejarnos descansar! <3 <3

**Comment by dagalloso** [comment]
Me sumo también al agradecimiento. Son grandes! We love you <3

**Comment by Nebula2028** [comment]
Si de verdad que se agradeció muchísimo, el año pasado fue full programar en fiestras patrias.
Muchas muchas gracias

**Comment by roy350** [comment]
Me sumo al agradecimiento disfrute el fin de semana largo que nos dieron muchas gracias!!
