### ISSUE TITLE
Apartado Matemático (15%)

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#244]
No entiendo esta sección. Pareciera que es para ayudarnos a definir algunas funciones (¿no cierto?), pero tiene ponderación de puntaje asignado. ¿A qué se refiere ese 15%? ¿Qué tenemos que 'hacer' en esta sección?

**Comment by Hernan4444** [comment]
La idea es que crean sus propios métodos para calcular las funciones utilizando esas formulas y no funciones externas. Ahí les dimos algunas sugerencias de como calcularlas.

**Comment by cjgazali** [comment]
¿Se asume entonces que **los valores entregados por la función van a ser una aproximación** arbitrariamente cercana al valor real? No podemos hacer sumas infinitas...

**Comment by Hernan4444** [comment]
@cjgazali Estas en lo correcto, esperamos aproximaciones que estén lo mas cercana al valor real pero obviamente pueden diferir un poco.
