### ISSUE TITLE
Notas tareas

### ISSUE THREAD

**Issue by smargozzini** [IIC2233-2016-02/Syllabus#245]
Mas o menos cuanto se demoran en publicar las notas de las tareas después de la entrega?
gracias

**Comment by Bnnunez** [comment]
Para cuándo estarán las notas de la tarea 1?
Saludos

**Comment by flobarrios** [comment]
Hola ! Estarán mañana. Saludos!

**Comment by smargozzini** [comment]
El feedback lo mandan por mail a cada uno?

**Comment by flobarrios** [comment]
@smargozzini se crea una issue en su repo con el feedback (igual que para las actividades).

**Comment by smargozzini** [comment]
gracias!

**Comment by tcgarrido** [comment]
@flobarrios Hola! yo no tengo ese issue con el feedback :c que hago? 

Saludos!

**Comment by flobarrios** [comment]
@tcgarrido ahora esta !! saludos
