### ISSUE TITLE
Librerías permitidas/no permitidas en la T03

### ISSUE THREAD

**Issue by FernandoPieressa** [IIC2233-2016-02/Syllabus#246]
Para consultar sobre una librería deben responder esta issue con una pregunta de la siguiente forma:

> Puedo usar la librería nombre_libreria para hacer explicacion_de_lo_que_quiero_hacer

Recuerden especificar en su README qué librerías utilizan!

---
## **Librerías Permitidas**
- os
- random
- collections
- copy
- functools
- itertools
- mpl_toolkits.mplot3d
## **Librerías Prohibidas**
- Pandas
- Numpy
- pyparser
- Scipy
- Math
- Re
- SymPy
- Tkinder
- fractions
## **Built-ins prohibidos**
- eval (:skull:)
- exec (:skull:)
## **ESPECIALMENTE PROHIBIDO**
- for
- while

(Sin embargo, si se pueden usar loops si es dentro de generadores o listas por compresión. Para mas información leer sección 6 del enunciado de la tarea.)

**Comment by sormazabal** [comment]
Hola! Se puede usar la librería "re" al leer archivos?

**Comment by flobarrios** [comment]
@sormazabal no se puede. Saludos!

**Comment by cjgazali** [comment]
El enunciado (si se lee también el pie de página 12) da a entender en otras palabras que 'a veces podemos ocupar for y while'. Esto hace surgir muchas dudas.
En general, ¿Esperan que forcemos el NO uso de for y while (al punto de empeorar el código) cuando no es estrictamente necesario usarlos? ¿O esperan que prefiramos algo específico? ¿Podrán ser más específicos? Voy a abrir otro issue (#248) pero pongo acá también porque aquí están prohibiendo for y while.

**Comment by flobarrios** [comment]
@cjgazali fue respondido en #248. Saludos!

**Comment by Sgwa** [comment]
Se puede usar libreria functools para usar reduce?

**Comment by flobarrios** [comment]
@Sgwa si se puede!

**Comment by andresbannuraschultz** [comment]
Tampoco puedo usar while en una funcion generadora? Como lo hicimos en la actividad?

**Comment by flobarrios** [comment]
@abannura si se puede ! Siempre y cuando no intentes imitar operaciones funcionales cambiando solamente el return por un yield, ya que se pierde el objetivo de la tarea. Saludos!

**Comment by andresbannuraschultz** [comment]
Mmm, la verdad no te entendi, que son operadores funcionales? Lo que quiero hacer es ocupar el yield como un return, pero tambien que la funcion "parta" desde el yield y no de nuevo. Y lo que se hace mi funcion ponerlo dentro de un while True. No se si se entiende, hay alguna manera de asegurarme que estoy dentro de la ley? jaja

**Comment by flobarrios** [comment]
Si, eso esta permitido! Corrección, era operaciones. Saludos!

**Comment by NachoCasta** [comment]
Para calcular el valor absoluto lo podemos hacer con la funcion abs o debemos definir una funcion que retorne el valor absoluto?

**Comment by gabrielpinkman** [comment]
por qué exec está prohibido? al momento de querer utilizar metaclases se muere la lectura de strings

**Comment by aaossa** [comment]
Tanto `eval()` como `exec()` son peligrosos si no se usan de forma correcta y segura. Existen muy pocos casos (quizás ninguno) en los que su uso es aceptado, por lo que en general se considera una **mala práctica** utilizar ambos _built-in_.

Ahora mismo no encuentro una issue en la que alguna vez respondí bastante completo esto, pero puedes entender la idea con [este comentario de un ayudante el 2015-2](https://github.com/IIC2233-2015-2/syllabus/issues/41#issuecomment-133905606):

> No obstante usar la función `eval()` es una pésima práctica, pues te puedo inyectar código. Por ejemplo, si te paso un archivo que dice
> 
> `__import__('shutil').rmtree('../../')`
> 
> y tu corres `eval()` sobre ese string, borrarás tu repo del computador :cry:
> 
> Así que **NO usen `eval()`!**

**PS:** Si quieres entender mas sobre el asunto puedes encontrar varias entradas de blogs en las que se explica con detalle el por qué no se recomienda usar estos _built-in_

**PS 2:** Tampoco corras ese código. Busca en la documentación lo que hace :ok_hand:

**Comment by rodolfopalma** [comment]
@NachoCasta puedes usar `abs`.

**Comment by Zekayrus** [comment]
¿Se puede usar decimal para que las funciones notables (como cos(k*Pi) con k entero) retornen siempre un valor exacto?

**Comment by asimonv** [comment]
Algún problema con usar namedtuples?

**Comment by sormazabal** [comment]
Se puede usar operator para usar los operadores binarios?

**Comment by asimonv** [comment]
Qué hay de sympy?

**Comment by jgmontoya** [comment]
Hola, les recuerdo que al momento de preguntar por librerías **deben** especificar para qué quieren usarlas.

Saludos.

**Comment by asimonv** [comment]
@jgmontoya sympy para parsear. Namedtuples para ocuparlas como tokens para parsear.

**Comment by jgmontoya** [comment]
Hola, 

**No** pueden usar `SymPy`
**Si** pueden usar `collections`  

Saludos!

**Comment by ceyzaguirre4** [comment]
Queria importar  **copy** para usar deepcopy, lo dejo a su criterio

**Comment by NachoCasta** [comment]
+1 Al usar copy para deepcopy

**Comment by agmardones** [comment]
@ceyzaguirre4 Si, pueden usar `copy`

**Comment by ceyzaguirre4** [comment]
gracias
Y `sys` para aumentar el limite de recursion?

**Comment by domingo-valdes** [comment]
Puedo importar functools para usar reduce?

**Comment by Hernan4444** [comment]
@domingo-valdes si puedes usar functools
Saludos!

**Comment by ceyzaguirre4** [comment]
A mi duda anterior (si se puede o no usar `sys` para aumentar el limite de recursion) añado si se puede usar `Decimal` para evitar los overflow al intentar convertir un int en float

**Comment by joseluishaddad** [comment]
alguna recomendación de librería para plotear? matplotlib?

**Comment by Hernan4444** [comment]
@joseluishaddad efectivamente, hay que usar matplotlib
saludos!!

**Comment by Jaluco** [comment]
Me sumo a los que preguntan si se puede usar la libreria decimal para evitar errores de overflow

**Comment by agmardones** [comment]
**No** pueden usar `decimal`. Acerca del `OverFlowError`, revisen #262.

**Comment by asimonv** [comment]
Se puede usar operator para poder pasar de un char a el operador en sí?

**Comment by asimonv** [comment]
matplotlib pide numpy, se puede usar en ese caso, solo para graficar?

**Comment by cglevican** [comment]
Se puede usar mpl_toolkits.mplot3d para graficar en 3D? Sale en todos los ejemplos de matplotlib

**Comment by stephichau** [comment]
Hola @asimonv ! 

**Sí** se puede ocupar numpy para graficar :)

**Comment by stephichau** [comment]
@cglevican **Sí** puedes usar mpl_toolkits.mplot3d. 

Saludos !

**Comment by gabrielpinkman** [comment]
Se puede usar tkinter?

**Comment by Hernan4444** [comment]
@gabrielpinkman **NO** se puede usar tkinder. Ademas recuerda especificar a la otra el motivo de usar esa libreria.
Saludos!

**Comment by gabrielpinkman** [comment]
Igual no salía especificado en las instrucciones >:c es para que el usuario pueda cargar sus archivos de forma amigable, sin recurrir a saber el lugar exacto donde están sus archivos, o hay que asumir siempre un lugar donde estarán los archivos?

**Comment by Hernan4444** [comment]
@gabrielpinkman Puedes suponer que los archivos estarán en la misma carpeta del programa.
Saludos!

**Comment by DiegoAndai** [comment]
Hola, ¿se puede ocupar itertools para obtener distintos iteradores (obviamente sin ocuparlos después ni con for ni con while) y así poder usar el método next()?

**Comment by agmardones** [comment]
@DiegoAndai, sí puedes usar `itertools` :)

**Comment by Iruretagoyena** [comment]
Hola !
Puedo ocupar Fractions ? Sirve para aritmetica. 
https://docs.python.org/2/library/fractions.html

Gracias de antemano.

**Comment by agmardones** [comment]
@Diiru **No** puedes usar `fractions`

**Comment by NicolasAguirre** [comment]
hola, puedo usar ast para generar arbol?

**Comment by stephichau** [comment]
@NicolasAguirre **No** puedes usar `ast`.

Saludos!

**Comment by nicovsj** [comment]
Hola, se puede usar el modulo inspect para obtener los argumentos que una función desconocida recibe?

**Comment by Iruretagoyena** [comment]
Puedo usar "array" ? Estoy intentando hacer el ploteo, y todos los ejemplos salen con numpy.arange(), por lo que estoy intentando imitar el comportamiento de arange.

**Comment by JaimeGo** [comment]
Se puede usar Pyparser para parsear? Gracias

**Comment by agmardones** [comment]
@nicovsj **Sí** puedes usar `inspect`
@Diiru Puedes usar `numpy.arange()` para graficar, más arriba en esta issue se permitió la librería `numpy` con este fin.
@JaimeGo **No** puedes usar `pyparser`

**Comment by DiegoAndai** [comment]
Ya pregunté por itertools, pero no por estas funciones: compress(), dropwhile() y otras funciones como permutations(), las que ocupo para calcular determinante, inversa y rango de matrices. En general, si aceptan una librería, ¿deberíamos asumir que toda esta se puede ocupar? O tenemos que preguntar para cada aplicación que queremos darle.

**Comment by Hernan4444** [comment]
@DiegoAndai puedes ocupar toda la libreria de `itertools` :)
Saludos!

Pd: en general si una librería esta dentro de la sección "Librerías Permitidas" es que la permitimos totalmente, en caso contrario mejor preguntar por la aplicación que le quieres dar.

**Comment by gabrielpinkman** [comment]
Se puede usar la librería parser? (xD)

**Comment by sebacruzd** [comment]
Hola,
Puedo importar Stack desde pythonds.basic.stack? Es para facilitar un uso de listas. (Stack es una lista)

**Comment by domingo-valdes** [comment]
Puedo usar distutils.util.strtobool ? para pasar de str a booleano

**Comment by stephichau** [comment]
@domingo-valdes **no** puedes utilizar distutils.util.strtobool dado que no necesitas del módulo para implementar lo que quieres hacer :)

**Comment by jbsaeza** [comment]
puedo importar la libreria string exclusivamente para usar ascii_letters???

**Comment by sebacruzd** [comment]
@jbsaeza podrías crear un string = "abc..." no?

**Comment by domingo-valdes** [comment]
Esta permitida la libreria types?
