### ISSUE TITLE
Lecturas 2, Duda

### ISSUE THREAD

**Issue by HenryBlairG** [IIC2233-2016-02/Syllabus#247]
Estaba leyendo el texto de static vs dynamic typing, y me di cuenta de que había mucha como controversia (en los comentarios salty del final xD) entorno de cual era mejor. Y me surgió la duda de cuáles son los problemas que tiene el dynamic typing, que genera esta controversia. Uno de los comentarios decía que se buggeaba más el código. En qué situaciones es recomendable usar static typing en mi código (por que ensayé y se puede hacer en python :smile:) para evitar que se me bugee? A todo esto, disfruté más los comentarios salty de los tipos que la materia misma presentada jajajajajj. Saludos ayudantes :)

**Comment by ivaniadg** [comment]
Hola!

Efectivamente en python se _puede_ usar static typing desde la [versión 3.5 ](https://docs.python.org/3/library/typing.html). Personalmente, en python yo prefiero no hacer definición de tipos, porque como no fue creado para eso se transforma en algo super engorroso (partiendo porque hay que importar una librería para hacerlo). 

Revisa [esta pregunta de quora](https://www.quora.com/What-are-the-differences-between-a-dynamic-programming-language-and-a-static-programming-language-Which-one-is-better-or-in-other-words-has-a-better-prospect) para tener más información sobre la discusión de los dos tipos.
