### ISSUE TITLE
for y while... cuándo?

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#248]
El enunciado (si se lee también el pie de página 12) da a entender en otras palabras que 'a veces podemos ocupar for y while'. Esto hace surgir muchas dudas.
En general, ¿Esperan que forcemos el NO uso de for y while (al punto de empeorar el código) cuando no es estrictamente necesario usarlos? ¿O esperan que prefiramos algo específico? ¿Podrán ser más específicos? 
¿Se puede iterar normalmente sobre un string o sobre una lista?

**Comment by flobarrios** [comment]
Hola! la idea de la tarea es que hagan uso de programación funcional para desarrollar sus métodos. El uso de for y while queda **prohibido** fuera de listas o generadores por comprensión, exceptuando en la la impresión de valores y para esperar inputs de usuarios. De esta forma, no puedes iterar normalmente sobre un string o una lista si no cumple este último punto y debes utilizar programación funcional.

Saludos!
