### ISSUE TITLE
Archivos de Estados T03

### ISSUE THREAD

**Issue by fringlesinthestreet** [IIC2233-2016-02/Syllabus#249]
Hola me fijé que el archivo status3 no tiene el ';' entre las matrices (o inputs).  ¿Este entonces también es una forma en que nos presenten la información?

**Comment by stephichau** [comment]
hola! efectivamente fue un error, puedes asumir que se utilizarán archivos de prueba sin errores :)

**Comment by fringlesinthestreet** [comment]
ok! muchas gracias
