### ISSUE TITLE
[Tarea 1] Archivo jugadoresejemplo.json

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#25]
en el archivo jugadoresejemplo.json esa debe ser la base para la clase jugador?  o puedo crear una base diferente, porque no entiendo el iv que aparece en la parte de programones ni lo que pasa despues de batalla. :( lo del unique_id, victoria, el tipo y demases, si pudieran explicar que es cada uno de forma rapida para tener un nocion. muchas gracias.

**Comment by FernandoPieressa** [comment]
![photo_2016-08-13_13-43-02](https://cloud.githubusercontent.com/assets/13782155/17644703/ff59d68a-615b-11e6-9957-b9cc65f6b3de.jpg)

Es un ejemplo de guia, puedes hacerlo de otra forma mientras especifiques en el README.md como lo haras.

-La idea del unique_id es poder diferenciar 2 pokemones iguales con el mismo id, ya que ambos tendran informacion diferente (ivs, evs, nivel, etc...)
-IV es un numero que se genera al instanciar un programones, que es aleatorio y afecta el combate como se ve en las formulas
-equipo es los programones que tiene actualmente en el para usar en combate
-programones contiene informacion de todos sus programones, tanto en el PC de bastian como en el equipo.
-En batalla se ve toda la informacion de las peleas que tuvo, si la gano o no, en tipo si fue contra un entrenador/lider_gimnacio/etc.., el nombre del contrincante y tambien los programones utilizados.

Espero haber resuelto la duda.

Saludos!

**Comment by narierao** [comment]
entonces tengo que guardar registro de las batallas ocurridas?

**Comment by FernandoPieressa** [comment]
Si es necesario, para hacer la parte de consultas, saludos.
