### ISSUE TITLE
Decimales

### ISSUE THREAD

**Issue by ceyzaguirre4** [IIC2233-2016-02/Syllabus#250]
Trabajando en algunas de las funciones pedidas me encontre con una raiz periodica que deja pegado el programa. Debiera limitar la cantidad de decimales en cosas como calculo de raices/calculo de decimales de pi o le doy la opcion al usuario?
Gracias

**Comment by FernandoPieressa** [comment]
Esperamos aproximaciones que estén lo mas cercana al valor real pero obviamente pueden diferir un poco.
Igualmente siempre puedes especificar en el readme como vas a abordarlo(cuantos decimales, etc..)

Saludos!
