### ISSUE TITLE
Funcion logaritmo

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#251]
La serie de taylor que dan para el logaritmo es para logaritmo natural o no? Y esta bien? Buscando en google encontre:
![image](https://cloud.githubusercontent.com/assets/20782578/18720559/b77ce7c4-8002-11e6-9788-8156dc86c08d.png)
Pero quizas la que subieron es otra forma de lo mismo?

**Comment by agmardones** [comment]
Hola!
Efectivamente la serie del enunciado hace referencia al logaritmo natural (sacada de [acá](https://es.wikipedia.org/wiki/Logaritmo_natural)). Supongo que deberías llegar a lo mismo usando la fórmula que encontraste.
Saludos!
