### ISSUE TITLE
Formato consultas

### ISSUE THREAD

**Issue by asimonv** [IIC2233-2016-02/Syllabus#252]
Hola, podemos nuestro propio formato para una consulta correcta?
Por ejemplo: Sin [ 4 + 2 ] + 4 \* 2 / ( 1 - 5 ) ^ 2 ^ 3'
Que tiene un espacio entre operaciones o paréntesis.

**Comment by Hernan4444** [comment]
@asimonv No deberias depender de los espacios para parsear la información. Lo que puedes hacer es reescribir la consulta en tu propio formato y trabajar a partir de eso.

**Comment by asimonv** [comment]
OK!
