### ISSUE TITLE
Matrices

### ISSUE THREAD

**Issue by dagalloso** [IIC2233-2016-02/Syllabus#253]
No entiendo muy bien la forma en que se definen las matrices, más que nada la diferencia entre " | " y " , ".
Si bien una define filas y otra columnas, cuál sería la diferencia entre las matrices del ejemplo

![sin titulo](https://cloud.githubusercontent.com/assets/20784860/18722101/7248523e-8001-11e6-8a41-09f91ea1e428.png)
La segunda forma no debería quedar como un sólo vector o practicamente da lo mismo si ocupo ambos caracteres?

**Comment by FernandoPieressa** [comment]
Hola! La idea es que tanto usando "|" como "," funcione la matriz correctamente. (En otras palabras, funcionan de la misma manera.)

Saludos!

**Comment by nivek0o0** [comment]
Lo que sale justo arriba de eso, las "filas" definidas como [1,2,3,4,5] y las "columnas" definidas como [1|2|3|4|5] corresponden a un vector fila y un vector columna cierto?

**Comment by agmardones** [comment]
@nivek0o0 No, un vector de 5x1 y otro de 1x5, en tu ejemplo respectivamente.

**Comment by dagalloso** [comment]
Me sigue quedando la duda. No debería ser distinto definir una matriz con vectores columna que con vectores fila? Digo como en el ejemplo, definir una matriz con 3 vectores de 2x1 no debería dar distinto a una con 3 vectores de 1x2? O simplemente las trata por igual?

**Comment by agmardones** [comment]
@dagalloso Es un tema de notación. El carácter "|" fue puesto con el fin de definir matrices de 1xn (al definir [1, 2 , 3] correspondería a una matriz de 3x1), en el resto de los casos, | reemplazaría a la coma, por lo que los ejemplos sí serían equivalentes. Espero te queden un poco más claro!
