### ISSUE TITLE
consultas.txt

### ISSUE THREAD

**Issue by Nebula2028** [IIC2233-2016-02/Syllabus#254]
Hola, quería preguntar por consultas.txt

Según se explica en el enunciado el numero a la derecha de estadoX.txt deberia ser el numero de consultas que se harán luego de cargar dicho estado. Entonces en la primera consulta (status1) no debería
aparecer un 7 en vez de ese 8 ? O hay una operación extra que yo no estoy cachando?

status1.txt, 8
Integrate[g[x], {x,a,d}];
Integrate[f[t[x]], {x}];
Derivate[p[x,y,z], z];
MCM[int, 2,5];
Integrate[Integrate[Integrate[p[x,y,z],{x,a,d}],{y,a,1}],{z,a,d}];
f[5];
Integrate[h[x] \* g[x],{x}];
status2.txt, 4
...

**Comment by stephichau** [comment]
Hola! Efectivamente debería aparecer un 7 :)

**Comment by isidoravs** [comment]
Hola, con respecto a ese archivo, a qué se refiere con que se 

> "se debe cargar al comenzar cada ejecución"

La idea es que cada vez que se cargue un estado se resuelvan las consultas referidas a éste? Todavía no me queda tan clara esa parte del enunciado.
Muchas gracias!

**Comment by stephichau** [comment]
hola @isidoravs ! 

La idea es que todos los archivos con los estados se carguen al iniciar el sistema. Espero que haya resuelto tu duda :)

**Comment by isidoravs** [comment]
@stephichau si me quedó más claro! Pero para el archivo de consultas, se espera entonces, que se carguen todos los estados cuando el usuario ingresa el comando `load consultas.txt`? O debe ser que esos estados del archivo de consulta se carguen al iniciar el sistema?

Muchas gracias.

**Comment by stephichau** [comment]
@isidoravs Se deben cargar los estados al iniciar el sistema. Si el usuario no quiere tener todas las cosas definidas en los archivos, se ocupará el comando correspondiente para borrar las funciones y/o variables :)

**Comment by isidoravs** [comment]
@stephichau Perfecto, gracias!
