### ISSUE TITLE
Indignación evaluación T01

### ISSUE THREAD

**Issue by gabrielpinkman** [IIC2233-2016-02/Syllabus#256]
Es probable que no sea el lugar preciso para hacer el reclamo, pero lo hago igual. Estoy indignado con la entrega de evaluaciones de la T01. Tengo un 1, cuando entregué al menos la mitad de lo solicitado en la tarea. Denuncio esto porque si van a andar poniendo 1s arbitrarios, podrían ser más empáticos con aquellos que se preocupan por sus notas, just saying

Supongo que en cualquier lugar del universo un 1 equivale a no haber entregado nada, a no estar ni ahi con el ramo y haberse sobajeado las bolitas durante 2 semanas, lo que no es mi caso, porque mi tarea está ahi, arriba, con un readme super claro respecto a lo que hice y lo que no hice. De hecho me parece ultra sospechoso que los últimos 4 alumnos que estamos en la lista tenemos un 1, baia baia coincidencia? No lo creo

Exijo una explicación, saludos

**Comment by difischer** [comment]
No te equivocaste al principio del curso al entregar tu nombre de usuario en github? A mi me pasó eso y después no se recolectaban mis entregas, esto último también pudo haber sido un error independiente de lo primero. Otras razones que se me ocurres es no haber cumplido con alguna de las reglas de la evaluación o un error al subir las notas.
Además dudo que "van a andar poniendo 1s arbitrarios", ya que en ese caso deberán recorregirlas igual y sería la misma pega.

**Comment by Bnnunez** [comment]
Igual sería bueno saber que evalúa la pauta y el puntaje. En mi caso tengo un 1,5 y realice la mayoría de lo requerido. Con esa nota en la entrega 1, espero un 0 para la tarea 2.
Ojalá saber antes del 30, para botar el ramo por las buenas.

**Comment by flobarrios** [comment]
Estimado, el medio correcto para hacer este tipo de consultas es por mail. Efectivamente hubo un error en la repartición y las notas faltantes (3 últimos de la lista) estarán entre hoy y mañana. Pido las disculpas respectivas y ten claro que no _"andamos poniendo unos arbitrarios"_. Los feedbacks estarán hoy en sus repos.

Saludos

**Comment by gabrielpinkman** [comment]
@flobarrios Gracias, disculpa las molestias.

**Comment by svrivera** [comment]
Estoy en lo mismo, me deja super desganado la nota de la tarea (1,2) acabo de probar el código y no entiendo como se hizo la evaluación. Sería bueno que el ayudante corrector pudiera hacer llegar  un detalle de los descuentos.

**Comment by flobarrios** [comment]
@svrivera por favor mira tu feedback. Ahi esta todo detallado. En tu caso, el programa se caía por un error de imports y la ayudante te pide que recorrijas y revises con ella el error.

**Comment by svrivera** [comment]
Comentando con algunos compañeros me di cuenta que no me ha llegado el feedback al mail o al github. Como contacto a la ayudante?

**Comment by flobarrios** [comment]
@svrivera tu feedback esta en tu repo hace app 3 horas. Lo puedes ver [aqui](https://github.com/IIC2233-2016-02/svrivera-iic2233-repo/issues/5) (TuRepo --> Issues --> T01)

**Comment by cpieringer** [comment]
Estimado @gabrielpinkman ,

lamento el error en la publicación de tu nota, sin embargo, te recuerdo que este es un foro de discusión de un curso donde se espera que los alumnos se expresen de forma adecuada y respetuosa, como debe ser para alumnos de esta casa de estudios. Del mismo modo como aclaró @flobarrios, los casos particulares o dudas como las originadas por situaciones los puedes aclarar directamente con alguno de los ayudantes jefes. Seguro se pueden solucionar en esa instancia y evitar tu molestia. Como también, puedes manifestar tu descontento mediante correo a cualquier integrante del cuerpo docente.

Saludos cordiales,
Christian

**Comment by gabrielpinkman** [comment]
Hola a todos, me gustaría comentar, para cerrar por mi parte el tema, que reconozco que no me expresé con los términos adecuados, ni en el espacio adecuado. Pido las correspondientes y sinceras disculpas al cuerpo docente y de ayudantes, si mis palabras les causaron un mal rato.

Atte. Gabriel Vargas
