### ISSUE TITLE
Nombres de variables

### ISSUE THREAD

**Issue by sormazabal** [IIC2233-2016-02/Syllabus#257]
Hola!
Los nombres de variables siempre serán un caracter solo (ej: a = 1) o pueden ser una palabra? (ej: var1 = 1)

**Comment by Hernan4444** [comment]
@sormazabal las variables pueden tener cualquier formato (excepto comando o funciones definidas en maplematica como Integrate, Cos, Ln, etc)
Saludos!

**Comment by aiquinones** [comment]
Se puede asumir que no tienen los caracteres "[" y "]"?

**Comment by Hernan4444** [comment]
@Aiquinones puedes asumir que no tendrán esos caracteres.
Saludos!

**Comment by andresbannuraschultz** [comment]
Y pueden tener en su nombre la variable de la que dependen? Me estaba fijando en los ejemplo y en el status4 hay una funcion asi:
dfx[x_] = Derivate[f1[x],x];
donde x esta en el nombre y en la funcion en si. Es valido?

**Comment by Hernan4444** [comment]
@abannura la "x" en el nombre no tiene relación con la x en la función en si, solo se puso para llamar de forma clara a esa función, otros nombres validos pueden ser "derivada_de_x", "df" o "derivadax"

**Comment by andresbannuraschultz** [comment]
Mi duda iba a que para evaluar la funcion yo hacia replace(variable, valor), pero al estar la "variable" en el nombre tmb me remplazaba la x del nombre. Pero como ese input es valido tendre que cambiar esa parte del codigo nomas. Gracias!
