### ISSUE TITLE
Funciones multivariables?

### ISSUE THREAD

**Issue by gabrielpinkman** [IIC2233-2016-02/Syllabus#258]
Se deben considerar las funciones en una o en muchas variables? (Sin, Cos, Exp)

**Comment by agmardones** [comment]
Hola @gabrielpinkman!
Sí, tienes que considerarlas. Tal como aparece en algunos ejemplos del enunciado, habrán funciones multivariables (entre esas, las que mencionas tú), y dentro de las posibles consultas puede estar integrarlas/derivarlas/evaluarlas/etc.

Espero te hayas referido a esto. Saludos!
