### ISSUE TITLE
[Tarea 1] id, unique_id e iv de programones

### ISSUE THREAD

**Issue by ttapia** [IIC2233-2016-02/Syllabus#26]
Hola! Tengo una duda sobre los atributos de los programones. En el enunciado dice lo siguiente:

> **Estructura**
> ...
> Programón: Todo programón tiene un identificador, un nombre ...(etc.)

Pero al revisar el archivo jugadoresEjemplo.json se muestra lo siguiente:
`"programones": [{
            "unique_id":50,
            "id": 1,
            "iv": 10,
            "nivel": 15 }]`
Con lo que pareciera que el programón tiene un "unique_id" y un "id". 
La pregunta es si los programones deben tener un id único o no (ademas del id normal), y también qué es el iv que aparece en esa línea.

**Comment by Hernan4444** [comment]
El iv es un valor que se genera de forma random solo una vez en el programón cuando aparece, después de eso se mantiene para siempre (al igual que los EV).
Considera que podrías tener dos programones iguales, ¿como los diferenciarías?, como sugerencia fue el unique_id, si tienes otra forma puedes usarla mientras la especifiques en el Readme

**Comment by ttapia** [comment]
Oka ya entendí, muchas gracias!
