### ISSUE TITLE
Integrar (primitiva)

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#260]
En cuanto a las integrales, y en caso de no especificar limites de integracion, tenemos que encontrar la primitiva de la funcion? En caso de tener que calcular la primitiva, que tan complicadas seran? Que recomiendan hacer? Hacer sustituciones y "la vaca"? La verdad no tengo idea por donde enfrentar este problema, cualquier guia sera muy bienvenida. Muchas gracias de antemano.

**Comment by stephichau** [comment]
Hola! En cuanto a las integrales, se pueden presentar polinomios de orden n ó funciones trigonométricas de la siguiente forma:

Integrate[x^100,{x}];
Integrate[Tan[x],{x,0,Pi/3}];
Integrate[Integrate[y\* Cos[x] , {y,0,5} ], {x,0,2*Pi } ];

 Finalmente **no** se presentarán consultas de la siguiente forma:

Integrate[x*Sin[x],{x,0,1}];
Integrate[Sin[x] \* Cos[x], {x}];

**Comment by andresbannuraschultz** [comment]
Mmm, dale dale, por lo que entendi entonces no habran integrales dobles no-separables, ni integrales de productos, ni integrales de composicion de funciones. Podria ser por ejemplo un Integrate[(x+1)^2,{x}]? Que en el fondo no deberia entrar ya que es composicion, pero podria entrar porque se puede transformar a un polinomio.
Ademas, dada la "simplicidad" de las integrales, recomiendan hardcodear el codigo? En el sentido de hacer, si es un sen(x) que retorne -cos(x), si es 1/x retornar Ln(x)... y asi para todos los casos (que no son tantos **creo** ). No se si me explique bien. Muchas gracias!

**Comment by stephichau** [comment]
Con respecto a integrar (x+1)^2 y cosas por el estilo, sí se puede dado que es posible expandir el polinomio. Por otra parte, puedes harcodear el código para obtener las derivadas e integrales de las funciones respectivas :)! Pronto subiremos más ejemplos. 

Saludos!

**Comment by andresbannuraschultz** [comment]
Dale, muchas gracias!

**Comment by andresbannuraschultz** [comment]
Podria aparecer una integral impropia? Gracias!

**Comment by Hernan4444** [comment]
@abannura si con integral impropia haces referencia a las que su intervalo presentan infinito, no aparecerán, pero recuerda que si pueden aparecer integrales sin definir intervalos.
Saludos!

**Comment by andresbannuraschultz** [comment]
Muchas gracias!
