### ISSUE TITLE
Problemas con PyQt4

### ISSUE THREAD

**Issue by fergarciafaura** [IIC2233-2016-02/Syllabus#261]
Hola, tengo problemas con la instalación de PyQt4 en python 3.5. Al importarlo desde python3 dice: 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'PyQt4'
```

Me pueden ayudar por favor!

_PS: No sé como se agregan los labels a las issues_

**Comment by aaossa** [comment]
¿Qué intentaste? ¿Qué sistema operativo tienes? ¿Funciona desde consola?

**Comment by fergarciafaura** [comment]
Claro, no di ningún detalle jajaja. Tengo OS X El Capitan.
Hice desde la terminal `brew install pyqt --with-python3`
Después abrí python3, y ahí import PyQt4 y me sale ese error.

**Comment by aaossa** [comment]
Si en consola abres python y tratas de importar pyqt te aparece el error? Revisa #161 :ok_hand: Hay mas issues con problemas de instalación, dales una mirada y si nada funciona o te aparece un error distinto avisanos :grin:
