### ISSUE TITLE
OverFlowError

### ISSUE THREAD

**Issue by ndleyton** [IIC2233-2016-02/Syllabus#262]
Hola, en mi repo, tengo un codigo en el que realizo una sumatoria de 0 hasta n, el asunto es que si n lo hago mayor a 85, me arroja OverFlowError. 
¿Debo ignorar este error y dejar n<86?

**Comment by rodolfopalma** [comment]
El `OverflowError` se produce debido a que el largo del número excede la capacidad de almacenamiento de la estructura de dato que Python usa. Puedes asumir que vamos a usar números razonables (dicho de otra forma, que no serán más grandes que la capacidad de las EDD de Python).

**Comment by ndleyton** [comment]
Gracias!, de todas formas, el error no se produce por el input, si no por la 'precision' con la que quiero realizar las sumatorias, como el sumar 'de 0 a n', al dejar n > 85 me arroja el error

**Comment by domingo-valdes** [comment]
Entonces no deberia preocupareme si, por ejemplo, al ingresar ciertos valores en una trigonometrica inversa me tira un valor de overflow?

**Comment by stephichau** [comment]
Hola @domingo-valdes,  en que casos te sucede ?

**Comment by domingo-valdes** [comment]
@stephichau Por ejemplo con valores de arcseno mayores a 0.83. El error no se produce porque mi código esté malo, se debe a que con  sumatorias infinitas que se demoran en converger las edd de python no aguantan: "OverflowError: int too large to convert to float".

**Comment by jgmontoya** [comment]
Hola, 

Ese problema se produce porque el factorial se hace muy grande y al momento de realizar la división python no es capaz de transformarlo a float. Esto ocurre porque los float de python (que son equivalentes a los double de c) tienen una cantidad de bits fija, a diferencia de los ints, que en python pueden crecer indefinidamente.

Puedes usar ciertas equivalencias para calcular algunas funciones para que esto no ocurra, por ejemplo si usas que:

`arcsin(x) = 2 * arctan(x/√(1-x^2))`

Entonces podrás calcular arcsin de valores mayores a 0.83 sin problemas!

Saludos!

EDIT: Pueden encontrar más equivalencias acá: [Wikipedia](https://en.wikipedia.org/wiki/Inverse_trigonometric_functions#Relationships_among_the_inverse_trigonometric_functions)

**Comment by Jaluco** [comment]
Pregunta al respecto, ¿podemos usar sqrt o debemos crear nuestra propia funcion de raices cuadradas?

**Comment by Jaluco** [comment]
Hola, cuento mi solucion que por razones desconocidas me funciono para evitar el overflow:
- En lugar de que el factorial me devolviese un int, puse que lo convirtiese inmediatamente en un float
  Con eso deje de tener problemas con sin y cos cerca de pi o con numeros decimales

**Comment by Gonzalo-Perez** [comment]
Al final debemos crear nuestra propia funcion "raiz cuadrada"?
