### ISSUE TITLE
Duda AC07 Metaclase

### ISSUE THREAD

**Issue by glbello** [IIC2233-2016-02/Syllabus#263]
Saludos, sé que ya pasó la actividad, pero estabaa intrigado en un problema que estaba teniendo tratando de rehacerla, cuando trataba de agregar a los miembros a la lista que estaba en la clase Organization, en el atributo self.members me pasaba que cuando el jefe agregaba alguien cada vez, en el self.members pasaba algo del estilo:

``` python
[Worker: Jose]
[Worker: Maria, Worker: Maria]
[Worker: Javier, Worker: Javier, Worker: Javier]
```

La funcion de agregar miembros la había definido dentro del método **new** de la metaclase Persona:

``` python
def add_member(cls, member):
            cls.organization.members.append(member)
```

y este luego lo ingresaba como atributo en el mismo método.

Como debería hacer para que no ocurra ese problema 😢

**Comment by iqacevedo** [comment]
Hola,
Me parece que el problema podría ser que el **new** solo es llamado cuando creas las clase Worker y Boss, no cuando estas se instancian, y por eso la función add_member se la debes entregar a un Boss en **call** porque este es el método que es llamado cuando se instancia un Boss (y ahí también recibes la organización a la que el jefe puede agregar miembros). 
No sé si responde a tu duda y tampoco soy ayudante así que podría estar equivocado xd.

Saludos !

**Comment by ivaniadg** [comment]
Hola! 

Puede que ese error se deba a que creaste _variables de clase_ que guardan el nombre, apellido, edad de los trabajadores. Eso es incorrecto, ya que como son **variables de clase** serán para **todas** las instancias iguales. Lo que debías hacer es modificar el `__init__` para crearlas como **atributos del objeto**.

Además tu código tiene un problema :scream: 

En tu solución asumes que la variable organización de `Boss` tiene una instancia de su organización y eso no es correcto. Como dice el enunciiado las clases `Boss` y `Worker` **NO** pueden tener a la instancia de la organización a la que pertenecen. 

##### Cómo arreglas eso?

La organización a la que pertenece `Boss` solo la conoces cuando creas instancias de esa clase. El `__init__` solo recibe el nombre de la organización por lo que el único momento donde tienes acceso a la instancia es en el `__call__` de la metaclase `MetaPerson`.  Lo que debías hacer aquí es crear el método `add_members` de la misma forma que hiciste arriba pero eliminando la variable cls (esto asumiendo que tu `__call__` es de la forma `__call__(cls, organización, *args, **kwargs)` ) y luego hacer `setattr(boss, 'add_members', add_members)`, donde boss es el objeto `Boss` creado.

**Comment by glbello** [comment]
Agradesco las respuestas, intenté una y otra vez lo que me sugirieron, y no tuve éxito :confused:, adjuntaré parte del código de la actividad (resumido solo al problema que tengo), espero que no esté pasando a llevar ninguna regla del curso al postear mi código:

``` python
class MetaPerson(type):
    def __new__(meta, name, bases, attrs):
        attrs['name'] = None
        attrs['organizacion'] = None

        return super().__new__(meta, name, bases, attrs)

    def __call__(cls, organization, *args, **kwargs):
        def add_member(cls, member):
            organization.members.append(member)

        cls.name = name_list[random.randint(0, len(name_list) - 1)]
        cls.organizacion = organization.name

        if cls.__name__ == 'Boss':
            setattr(cls,'add_member', add_member)

        return super().__call__(organization, *args,**kwargs)


class MetaOrganization(type):
    def __new__(meta, name, bases, attrs):
        def see_members(cls):
            print('members: {}'.format(cls.members))

        attrs['see_members'] = see_members

        return super().__new__(meta, name, bases, attrs)

if __name__ == '__main__':
    salo = Organization('Salo')
    jefe_salo = Boss(salo)
    for i in range(3):
        w = Worker(salo)
        jefe_salo.add_member(w)
    salo.see_members()
```

Al correrlo vuelvo a tener resultados similares como:

``` python
members: [Worker: Francisca, Worker: Francisca, Worker: Francisca]
```

¿Qué debería modificar para ya no seguir teniendo el mismo problema?

**Comment by ivaniadg** [comment]
Estás haciendo lo mismo que antes. Recuerda que el primer argumento del `__call__` es la clase, por lo que estás creando las **variables de clase** `name` y `organization`.

**Comment by glbello** [comment]
Perdon la insistencia, pero sigo sin comprender, si creo entender lo que me dices... entonces borro el `cls` de la funcion `add_members` pero me arroja error de la forma:

```
jefe_salo.add_member(w)
TypeError: add_member() takes 1 positional argument but 2 were given
```

**Comment by ivaniadg** [comment]
Antes de entender cómo usar metaclases tienen que entender cuáles son las diferencias entre los atributos del objeto, de la clase y los métodos del objeto y de la clase.

Los **atributos del objeto** son los definidos durante la inicialización del objeto, es decir, cuando se ejecuta el método `__init__`. Estos atributos son distintos para cada una de las instancias de la clase y solo pueden ser accedidos a través del objeto.  En el código solo hay un atributo del objeto `atributo_objeto`.

Los **métodos del objeto** reciben siempre como primer valor al objeto de la clase donde fueron definidos. Por convención se utiliza la palabra `self` pero podría ser cualquiera. Como estos métodos reciben al objeto entonces pueden acceder a los atributos del objeto y a los otros métodos del objeto. También pueden acceder a los atributos y métodos de clase a través de `self`.

Los **atributos de la clase** son definidos cuando se crea o se inicializa la clase, es decir, cuando se ejecuta el método `__new__` o `__init__` de `type` o de la metaclase. Estos atributos tienen el mismo valor para TODAS las instancias de la clase. En el código solo hay un atributo de clase `atributo_clase`. 

Los **métodos de la clase**, son métodos decorados por `@classmethod` y siempre reciben como primer valor a la clase en la que fueron definidos. Por convención se utiliza la palabra `cls` pero podría ser cualquiera. Cómo estos métodos solo reciben a la clase, solo pueden acceder a los otros métodos de clase y a los atributos de clase **no pueden** acceder a los atributos o métodos del objeto.  

Debido a que los métodos y los atributos de clase no acceden a los métodos y atributos del objeto pueden ser llamados directamente por la clase. 

``` python
class Clase:
    atributo_clase = 6

    def __init__(self):
        self.atributo_objeto = 8

    def metodo_objeto(self, arg1, arg2):
        self.atributo_objeto = arg1 * arg2

    @classmethod
    def metodo_clase(cls, arg1, arg2):
        cls.atributo_clase = arg1 * arg2

if __name__ == '__main__':
    objeto1 = Clase()
    print(Clase.atributo_clase) # 6
    Clase.metodo_clase(4, 6)
    print(Clase.atributos_clase) # 24
    objeto2 = Clase()
    print(objeto2.atributo_clase) # 24
    objeto1.metodo_objeto(3, 5)
    print(objeto1.atributo_objeto) # 15
    print(objeto2.atributo_objeto) # 8
```

Ejecuta el código de arriba [en este sitio](http://www.pythontutor.com/visualize.html#mode=edit) y revisa el paso a paso.

**Comment by fipaniagua** [comment]
¿Como se hace entonces para definir un atributo del objeto desde la meta clase (supongo que es desde el **call** y con setattr() pero me queda la duda) ?

**Comment by jicortes2** [comment]
Hola @fipaniagua! Como dijo Ivania antes, puedes modificar el `__init__` esto puedes hacerlo en el `__new__` definiendo la nueva función que quieres que reemplace a tu antiguo `__init__` y asignándolo a la llave`'__init__'` del diccionario que recibes. Te dejó un ejemplo por si no quedó tan claro:

```
class MetaEjemplo(type):
    def __new__(mcs, nombre, bases, diccionario):
        antiguo = diccionario[__init__]  # Aca obtengo el antiguo init
        def new_init(self, *args):  # *args son los argumentos que recibia el antiguo init
            self.ejemplo = 'Esto es un ejemplo'
            antiguo(self, args)  # Aca llamo al antiguo init porque quiero que se seteen las variables predeterminadas
        diccionario['__init__'] = new_init  # Aca se sobreescribe el init
        return super().__new__(mcs, nombre, bases, diccionario)
```

**Comment by fipaniagua** [comment]
ahí me quedo super claro, muchas gracias

**Comment by glbello** [comment]
¡¡Me funcionó!! Ahora si, después de darle mucha vuelta a todos quienes respondieron, pude entender y arreglar mi código, y corrigiendo lo de que las clases **Boss** y **Worker** no tuvieran las instancias de la organización a la que pertenecian, expongo la corrección por si alguien le sirve:

``` python
class MetaPerson(type):
    def __new__(meta, name, bases, attrs):

        def new_init(self, organization, *args):
            self.name = name_list[random.randint(0, len(name_list) - 1)]
            self.organization = organization.name
            attrs['__init__']

        attrs['__init__'] = new_init

        return super().__new__(meta, name, bases, attrs)

    def __call__(cls, organizacion, *args, **kwargs):

        def add_member(cls, member):
            organizacion.members.append(member)

        if cls.__name__ == 'Boss':
            setattr(cls,'add_member', add_member)

        return super().__call__(organizacion, *args,**kwargs)


class MetaOrganization(type):
    def __new__(meta, name, bases, attrs):
        def see_members(cls):
            print('members: {}'.format(cls.members))

        attrs['see_members'] = see_members

        return super().__new__(meta, name, bases, attrs)
```

Mil gracias por su tiempo y paciencia!! 😄

**Comment by ivaniadg** [comment]
Hay un problema :disappointed: 

Con esto

``` python
 def __call__(cls, organizacion, *args, **kwargs):

        def add_member(cls, member):
            organizacion.members.append(member)

        if cls.__name__ == 'Boss':
            setattr(cls, 'add_member', add_member)

        return super().__call__(organizacion, *args,**kwargs)
```

Estás haciendo que todas las instancias de `Boss` agreguen miembros a la organización de la última instancia `Boss` creada. Si revisas bien tu output te darás cuenta de que la organización _Salo_ no tiene ningún integrante, mientras que _Sola_ los tiene todos.

**Comment by glbello** [comment]
Sí, eso me dí cuenta después de volver a revisar, y se me cayó el mundo... asi que, mi pregunta es, se supone que las clases **Boss** y **Worker** no pueden tener entre sus atributos la instancia de **Organization**, entonces ¿cómo puedo mantener el vínculo entre, por ejemplo, _jefe_salo_ con la organización _salo_, y que esta no se pierda cada vez que instancio una clase **Boss** con otras organizaciones?

**Comment by ivaniadg** [comment]
:grin: 

Tienes que darle el método `add_members` al objeto de tipo `Boss` y no a la clase `Boss`. Lo que debes hacer es crear el objeto de clase metaclaseada por `MetaPerson`, agregarle el método `add_members` si corresponde y luego retornar ese mismo objeto.

``` python
 def __call__(cls, organizacion, *args, **kwargs):
     # Esta llamada, que crea al objeto se puede realizar en cualquier parte del método
     # Recuerda que organización NO puede ser un objeto, debe ser un string
     objeto = super().__call__(organizacion.name, *args,**kwargs) 

     def add_member(member):
         organizacion.members.append(member)

     # Nota el cambio en la condición. Solo este cumple con el requisito de la AC
     if 'Boss' in cls.__name__:   
         setattr(objeto, 'add_member', add_member)

     return objeto
```

**Comment by glbello** [comment]
Lo veo, y no lo creo... ahora si funciona, definitivamente... funciona... mil gracias @indonoso ahora caí con eso de poder llegar a los objetos de las clases desde la metaclase, que era lo que me complicaba
💃 💃 💃 💃 💃 💃
