### ISSUE TITLE
Derivadas

### ISSUE THREAD

**Issue by sormazabal** [IIC2233-2016-02/Syllabus#264]
Hola!
Para sacar las derivadas:
1) Tenemos que entregar el valor simbólico: 
Ej: x^2 ----> 2x
o
2) Calcular la pendiente no más:
Ej.  x^2 ----> 2x, pero x= 2, entonces el resultado es 4.

No me queda muy claro en el enunciado si hay que entregar el valor simbólico o numérico.

**Comment by stephichau** [comment]
Hola! 
Si la derivada viene de la siguiente forma:
Derivate[(x^2),x]; 
El output esperado es: 
2 \* x

Por otra parte, si viene como:
f1[x_] = Derivate[2*(x^2),x]; 
f1[2];
El output esperado es:
8

Saludos!
