### ISSUE TITLE
Funcion por partes

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#266]
Las funciones por parte pueden tener mas de una variable? En cuyo caso, el intervalo puede ser mixto? O se dara un intervalo para cada variable de manera separada. Gracias!

**Comment by jgmontoya** [comment]
Hola, las funciones por parte serán de solo una variable.

Saludos!

**Comment by andresbannuraschultz** [comment]
Gracias!

**Comment by andresbannuraschultz** [comment]
Otra duda respecto a las funciones por parte, los intervalos vendran siempre en la forma de comparaciones de desigualdad? Me gustaria saber que tan complicados pueden ser los intervalos. Por ejemplo, puede ser algo como "x>2 x!=3" (es decir, con mas de una condiciones). Tambien si es que puede venir en formato (2,4]. Muchas gracias!

**Comment by stephichau** [comment]
Hola @abannura, los intervalos siempre irán como desigualdades. 

Saludos!

**Comment by andresbannuraschultz** [comment]
Dale muchas gracias!
