### ISSUE TITLE
Se me quedo mi cargador hp en la sala Urgente

### ISSUE THREAD

**Issue by lareyes2** [IIC2233-2016-02/Syllabus#267]
Hola, disculpen las molestias ayer se me quedo mi cargador Hp en la sala b23, Es negro y tiene la punta donde se conecta de color azul. Si alguien lo vio :c o lo tiene por favor avisenme , si alguien se lo llevo sin querer :c también puede ser . Gracias :)

**Comment by flobarrios** [comment]
#259
