### ISSUE TITLE
Asumir el numero de variables

### ISSUE THREAD

**Issue by rrfoster** [IIC2233-2016-02/Syllabus#268]
Hola, se puede asumir que la Piecewise solo sera de una variable, es decir, que tendrá la forma f(x) y no f(x,y) o f(x,y,z).  Sí no, de cuantas variables es el maximo que podemos asumir. Garacias

**Comment by jgmontoya** [comment]
Hola, las funciones por parte serán de solo una variable.

Saludos!

**Comment by asimonv** [comment]
@jgmontoya el MCM/MCD se considera como de 3 o n?

**Comment by jgmontoya** [comment]
Tanto MCM como MCD reciben exactamente tres parámetros.

Saludos!
