### ISSUE TITLE
Sumatorias de funciones con 2 o mas variables.

### ISSUE THREAD

**Issue by FranciscoLarach** [IIC2233-2016-02/Syllabus#269]
Hola!
¿Que pasa si defino f(x,y) = x+y y después quiero hacer la sumatoria de esta función con x de 1 a 3?
¿Se puede ese caso? ¿ se debe retornar algo como 6 + 3y? ¿ o como funciona?
Saludos y gracias de antemano.

PD: ¿la respuesta para este caso aplica a todas las funciones sobre funciones con mas variables?

**Comment by agmardones** [comment]
Hola @FranciscoLarach!
Como tu dices, se debiese retornar una función de la(s) variable(s) que no se considera(n) en la suma. Puedes asumir que en el caso de que guardemos dicha suma se haría definiendo una función que las involucre, es decir, en tu ejemplo. el output se guardaría como g[y_], la que podría ser evaluada después (en una línea aparte) como g[5]. (en caso de no guardarla, en el output simplemente saldría 6 + 3y)

Espero me haya explicado, saludos!

**Comment by FranciscoLarach** [comment]
Si, me ayudó a entender, aun así¿ pueden poner un ejemplo de como llamarían a una sumatoria con una función de mas de una variable? para guiarme un poco mas en eso!
Muchas gracias!

**Comment by andresbannuraschultz** [comment]
En caso de que se guarde como funcion, asumimos que la cantidad de variables de la funcion y las que quedan "libres" en la sumatoria sera la misma o no?

**Comment by agmardones** [comment]
@abannura Sí, estarán bien formateadas las consultas.
@FranciscoLarach 
`g[x_,y_,z_] = x + y*z`
`f[x_,y_] = Sum[g[x,y,z], {z,0,10}] # -> 10*x + 55*y`
En la consulta:
`f[1,1]`
Y el output:
`65`

No necesariamente en la suma hay que pasar una función definida, podría haber pasado el `x + y*z` directamente, pero en dicho caso debería haber definido antes las variables x e y (si no, debería levantarse el error de variable no definida).

EDIT: Al pasar `f[x_,y_] = Sum[x + y*z, {z,0,10}]` no habría ningún problema. Sin embargo, el error de variable no definida aplica si se hiciese `foo = Sum[x + y*z, {z,0,10}]`, ya que no se define una función, ni hay ningún otro tipo de referencia a x e y.

**Comment by andresbannuraschultz** [comment]
Gracias por el ejemplo!

**Comment by FranciscoLarach** [comment]
Muchas gracias ¡el ejemplo ayuda mucho! Suerte

**Comment by andresbannuraschultz** [comment]
Respecto al ultimo ejemplo, que pasa si hago solo Sum[x + y*z, {z,0,10}]. Es decir, no se lo asigno a ninguna funcion, tambien deberia tirar error de variable definida o no? Ya que si no como diferenciaria la variable de un parametro que no existe.

Ademas, que pasa con las integrales (las primitivas) que retornan una funcion cuando las llamo sin asignar el resultado a una funcion (es decir cuando ocupo mi programa como "calculadora"). Muchas gracias de antemano.

**Comment by agmardones** [comment]
Hola @abannura!

Tienes toda la razón, en dichos casos puedes dejarlo a  tu criterio, siempre y cuando especifiques en el README. Es decir, tu decides si muestras un error de variable no definida, o una función en el output.

Saludos!

**Comment by andresbannuraschultz** [comment]
Dale, muchas gracias!!
