### ISSUE TITLE
Commit a revisar AC01

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#27]
estoy un poco confundido, me llego un correo en donde el asunto es AC01 pero el commit a revisar es el de la AC00, yo no subí ningún archivo de AC01 ya que mi compañero lo subió. pido revisar lo anterior. muchas gracias

**Comment by aaossa** [comment]
Hola, lo que pasa es que entre la AC00 y la recolección de la AC01 no hiciste _commits_ en tu repo, por lo que el _script_ de la AC01, al momento de ir a buscar el _commit_ mas reciente, se encontró con el de la AC00. Si tu compañero subió la actividad no te preocupes, si no tienes nada en la AC01 (o esta no existe) no deberías tener problemas :ok_hand:

**Comment by narierao** [comment]
ok, muchas gracias. saludos
