### ISSUE TITLE
T03: Tamaño máximo de matrices

### ISSUE THREAD

**Issue by sfga** [IIC2233-2016-02/Syllabus#270]
Hola,

   ¿cual va a ser el tamaño máximo para el alto y ancho de una matriz?

Gracias.

**Comment by agmardones** [comment]
Hola @sfga!

Las matrices pueden ser de tamaño arbitrario. Esto también aplica para el tamaño de matrices a las que se les pedirá calcular su determinante. Saludos!

**Comment by sfga** [comment]
Gracias @agmardones por contestar.
