### ISSUE TITLE
Matrices2

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#271]
1) ¿Asumen que se permite operatoria entre matrices y otras cosas (ej: Matriz \* 3 pondera a cada elemento de la matriz) y entre matrices (ej: M1 + M2 suma cada uno de sus elementos) o solo se espera que permitamos operar como se muestra?

2) ¿Una variable o una función puede ser una matriz?

3) Favor de responder #253 que lleva pendiente varios días, y es más lo que enreda que lo que resuelve.

Pregunto aquí en mis palabras:
Se supone que [1|2] es una columna, es decir, una matriz de 2x1, y [1, 2] una fila, es decir, una matriz de 1x2. Por lo tanto, en la primera forma debería ser [[a11 | a21 | a 31], etc] en vez de [[a11 | a12 | a12], etc], puesto que para eso es [[a11 , a12 , a 13], etc]. O los ejemplos están malos, o '|' es lo mismo que ',' y por lo tanto la definición de columnas está de sobra.

**Comment by agmardones** [comment]
Hola @cjgazali!

1) Lo esperado es sólo lo que está en el enunciado, no es necesario que implementes la suma/ponderación por escalar/otras operaciones.
2) Una variable **si** podría ser una matriz, una función **no** podría ser una matriz.
3) La respondí hace poco, sorry la demora!

Saludos!
