### ISSUE TITLE
Control de flujo o Functional

### ISSUE THREAD

**Issue by Kitaps** [IIC2233-2016-02/Syllabus#273]
Hola, me surgió una duda, 
es mejor usar if y else ?
o mejor usar map y filter ?

Es decir seguro depende pero cuando se recomienda usar cual?
Supongo que map y filter cuando son muchas iteraciones.

Gracias por su tiempo ;)
Patrick

**Comment by isipalma** [comment]
Justamente eso, si utilizas el map en conjunto del filter puedes lograr aplicar una funcion a ciertos elementos de un iterable que tu definas, lo cual es útil si son muchos los elementos en cuestion. El control de flujo sería como para acciones mas especificas, es lo que yo pienso. Pero si uno te facilita más el trabajo que otro, utiliza el que te acomode, igualmente se recomienda más map y filter por el orden

Saludos ;)

**Comment by Kitaps** [comment]
gracias :)
