### ISSUE TITLE
Uso de while

### ISSUE THREAD

**Issue by joseluishaddad** [IIC2233-2016-02/Syllabus#275]
Hola!, 
quería saber si puedo usar un while si es en un caso como el siguiente (tomada del material de clase) donde usaré una funcion con yield:

``` python
def fibonacci():
    a, b = 0, 1
    while True:
        yield b
        a, b = b, a + b
```

Gracias!
PS: no supe hacer el indentado en el comentario

**EDIT aaossa:** Fixed

**Comment by flobarrios** [comment]
Hola! Si se puede (#255).
