### ISSUE TITLE
¿ Derivar, Integrar, Graficar, Simplificar? ¿Cómo? ¿A qué nivel?

### ISSUE THREAD

**Issue by gebalassa** [IIC2233-2016-02/Syllabus#276]
### **_¡Hola!**_

Acabo de leer la Tarea 3 con mayor tranquilidad y veo que se piden múltiples comandos que implican una complejidad bastante alta, sin ningún tip, ni nada; además, observé que todas las librerías matemáticas están prohibidas. Entonces:

1) _**Derivar e Integrar**_:
a) ¿Cualquier tipo de función elemental y combinación de éstas?

Si lo anterior es afirmativo: 
b) ¿Debemos implementar la "Regla de La Cadena"? (ej: _Derivate[Ln[Sin[Exp[x]] - 1/(x^x)]]_)
c) ¿Debemos implementar el método de "Sustitución", y la "Integración por Partes", ambos de manera automática?
d) En caso de pedir resultados numéricos en vez de simbólicos, ¿Ahí se deben utilizar las series de Taylor, no? Por supuesto, una vez estén todos los términos de la sumatoria integrados/derivados.
e) ¿Qué pasa con casos particulares que requieren otros métodos? (_Ej: x^x, Exp[x^2], Sin[x]/x, etc._)
f) ¿La precisión decimal de los resultados numéricos es arbitraria, entonces?

2) _**Graficar**_:
a) ¿Cómo? ¿Con y sólo con la librería "`matplotlib`"? ¿Qué comandos se pueden usar? ¿Alguna recomendación sobre su uso, que no hemos visto nunca?
b) ¿Los outputs son siempre archivos .txt?  ¿Cómo guardo los gráficos en ese caso? ¿Un JPG aparte usando el parámetro `format="jpg"`? ¿PDF?

3) _**Simplificar**_:
a) ¿Qué significa? ¿Debemos seguir las reglas que utiliza Maple/Mathematica?

Si la anterior es negativa:
b) ¿Cuáles son los requisitos exactos, entonces? No sale _nada_ en el enunciado.

---

Eso por ahora. Gracias de antemano por su respuesta. :grin:

**Comment by agmardones** [comment]
Hola @gebalassa!:

Te recomiendo buscar antes de abrir una issue, ya que varias cosas de las que preguntas están respondidas (así te ahorras la lata de esperar que te respondan):

1) 
a,b,c,e)  #260
d) Sí 
f) Sí, y  te podría interesar #262.
2)  Esto está explicado en el enunciado (último párrafo de la sección 4.2.2)
3) Es tal como suena, recibe una fracción (que podría contener eventualmente partes simbólicas) y entrega su versión equivalente e irreductible.

Espero haber contestado a tus dudas, saludos!

**Comment by gebalassa** [comment]
**¡Hola! Gracias por responder.**

1] El post #260 no dice nada sobre derivar; particularmente, no menciona si es necesaria la "Regla de La Cadena". Se limita sólo a las integrales que se usarán. Te pediría, por lo mismo, que elimines la etiqueta de "Duplica3".

2] La sección 4.2.2 no dice nada sobre el método que recomienda para realizar los gráficos, ni las librerías que se permiten usar. Simplemente hace mención, a pie de página, de un comando (`savefig()`) para guardar gráficos con la librería `matplotlib`. ¿Significa eso que  se puede usar cualquier comando de esa librería? ¿Cualquier formato de imagen? ¿El archivo de la imagen queda en la misma carpeta que el `.txt`del _output_?

3] ¡Gracias! El tema es que, tanto en Mathematica como en Maple, el comando "_Simplify_" hace bastante más que simplemente reducir el resultado a una fracción irreducible, y como quieren que hagamos una especie de clon no sabía hasta que punto pretendían que implementásemos el comando.

Saludos y gracias de antemano,
_Gabriel_.
