### ISSUE TITLE
Operadores Booleanos

### ISSUE THREAD

**Issue by npcariman** [IIC2233-2016-02/Syllabus#277]
Que utilidad tienen los operadores booleanos en la tarea? Leí la tarea y sólo los utilizan en la parte de resolver ecuaciones. Que otra utilidad tienen estos? si hay más por favor den ejemplos.

**Comment by stephichau** [comment]
Hola @npcariman ! 

Además de resolver ecuaciones, se pueden ocupar para definir funciones por partes y para comparar dos números/resultados. Por ejemplo:

e[x_] = Piecewise[x^3, x > 3; x^2 , 0<= x <=3; x^2, x < 0 ];
f[x_] = Sin[x] + 1;
g[x_] = Cos[x] + 2;
h[x_] = Derivate[x^3,x];
i[x_] = Integrate[(x^2)*3, {x}];

4 < 5; (True) 
f[Pi/4] < g[Pi/4]; (True)
h[x] != i[x]; (False) 
e[4]; (64)
e[0]; (0)
e[-2]; (4)

Saludos!
