### ISSUE TITLE
Consultas booleanas

### ISSUE THREAD

**Issue by joseluishaddad** [IIC2233-2016-02/Syllabus#278]
El enunciado en la seccion de consultas booleanas dice:

> Divisible[a,b]: si a es divisible por b

Lo anterior se refiere a si (a/b) es un entero o a si (a/b) existe?

**Comment by aaossa** [comment]
Hola! Siempre se dice que un número es divisible por otro si la división es entera.

![image](https://cloud.githubusercontent.com/assets/10425834/18819912/f2a0ff4c-836e-11e6-9d84-922be0296ddf.png)

###### Resultado de googlear: "definicion de divisible"

Saludos :grin:
