### ISSUE TITLE
Grado máximo de ecuaciones a resolver

### ISSUE THREAD

**Issue by sormazabal** [IIC2233-2016-02/Syllabus#279]
Hola!
Al usar el comando "solve", ¿cuál será el grado máximo de las ecuaciones que debe resolver?
Pregunto porque para resolver cuadráticas y de inferior grado se requieren funciones mucho más simples que para las demás.

**Comment by gebalassa** [comment]
ZA #WARD DO

**Comment by aaossa** [comment]
Hola @gebalassa , esto no es Facebook :grin: Si quieren que les lleguen los mensajes de una issue o Pull Request suscribanse a las notificaciones. Si les interesa todo el repo hagan watch (arriba a la derecha):

![image](https://cloud.githubusercontent.com/assets/10425834/14770701/2608a1c2-0a4e-11e6-8378-c58953883176.png)

Tanto en Facebook como aquí, en Github, existen sistemas para evitar las respuestas que no aportan a la discusión y que son solo para marcar seguimiento. Los invitamos a usar Github correctamente :grin:

**Comment by agmardones** [comment]
Hola @sormazabal!

Mil disculpas por la demora. Solo se pedira grado máximo 2
Saludos!
