### ISSUE TITLE
[Tarea 1] Formato archivos de texto

### ISSUE THREAD

**Issue by Snorlax8** [IIC2233-2016-02/Syllabus#28]
En la sección de "Restricciones y alcances" del enunciado de la tarea, indican:
![pantallazo](https://cloud.githubusercontent.com/assets/14048037/17645319/edd2643e-6167-11e6-80ab-014f10eeb4c3.jpg)

Entiendo que esto significa que el contenido variará, pero ¿se mantendrá el mismo formato de escritura JSON? Es decir, si los corchetes estarán en las mismas posiciones, los espacios serán los mismos, etc. Pregunto por el tema del parser que tenemos que hacer por nuestra cuenta.

**Comment by Hernan4444** [comment]
El formato de los archivos sera siempre json. 
Pero cualquiera de los siguientes podria ser un formato valido:
(ejemplo de movimientos de un programón)

```
"moves": [
    "wing attack",
    "ember",
    "flamethrower",
    "heat wave"
    ]
```

```
"moves": [
    "wing attack", "ember", "flamethrower", "heat wave"
    ]
```

```
"moves": ["wing attack",
    "ember",
    "flamethrower",
    "heat wave"]
```

```
"moves":["wing attack", "ember", "flamethrower", "heat wave"]
```

**Comment by Snorlax8** [comment]
Gracias por tu respuesta :) Son los únicos 4 tipos de formatos o hay más?

**Comment by FernandoPieressa** [comment]
Tambien puede cambiar el orden, por ejemplo

```
{
      "id": 79,
      "type": "water",
      "evolveLevel": 37,
      "hp": 90,
      "special_defense": 40,
      "evolveTo": 80,
      "special_attack": 40,
      "defense": 65,
      "name": "Slowpoke",
      "speed": 15,
      "moves": [
         "tackle",
         "water gun",
         "confusion",
         "headbutt"
      ],
      "attack": 65
   }
```

o 

```
{
      "evolveLevel": 37,
      "hp": 90,
      "moves": [
         "tackle",
         "water gun",
         "confusion",
         "headbutt"
      ],
      "special_defense": 40,
      "evolveTo": 80,
      "special_attack": 40,
      "defense": 65,
      "type": "water",
      "name": "Slowpoke",
      "speed": 15,
      "id": 79,
      "attack": 65
   }
```

Tambien la idea es que usen un parser para todos los archivos, no un parser distinto para cada uno.

Saludos!

**Comment by Snorlax8** [comment]
Ok, gracias! Lo que me complica en realidad es que haya más de una forma de escribir un archivo json. Hay algún lugar en el que pueda ver todos los formatos o serán sólo los 4 listados por Hernán?

**Comment by jtagle2** [comment]
@Snorlax8, no te podría decir que cosas puedes asumir respecto al formato de los archivos txt que serán utilizados para probar tu tarea, para eso espera la respuesta de un tareo. 
Respecto a los "distintos formatos" de json que existen, la verdad hay un solo formato (puedes verlo [acá](http://www.json.org/)), lo que ocurre, es que los "formatos" dados por hernán cumplen con el formato json, pues los espacios en blanco o saltos de línea entre cada valor no modifican un json. Para lo que se pueden usar los espacios, es para que el archivo sea leído de manera más fácil por un humano, pero al parser le da lo mismo. Es más, un json válido podría ser una sola línea que contenga todo
Ejemplo:
`{"key_string": "valor1", "key_lista":[1, "string_en_lista", true, false], "key_booleano": false, "key_int": 2, "key_dict": {"key1": "value1", "key2": "value2"}}`
es lo mismo que decir

```
{  
   "key_string":"valor1",
   "key_lista":[  
      1,
      "string_en_lista",
      true,
      false
   ],
   "key_booleano":false,
   "key_int":2,
   "key_dict":{  
      "key1":"value1",
      "key2":"value2"
   }
}
```

Si ~~tienes~~ quieres realizar un parser propio que sea lo más generalizado posible, te recomiendo familiarizarte bien con json antes de lanzarte a escribir líneas y líneas de código.
Si tienes duda de si un "formato" es válido o no, puedes testear distintos jsons [acá](https://jsonformatter.curiousconcept.com/)

Saludos!

**Comment by frvalenzuela** [comment]
@jtagle2 revisando el URL que explica el formato de JSON, me deja una duda con respecto a las formas de los archivos: "gyms.json", "programones.json", "routes.json", "programonMoves". Según lo que entendí de la página, estos cuatro archivos serían 'arreglos', mientras que el resto de los archivos dentro de la carpeta que tienen el forma json, serían 'objetos', pero no deberían todos los archivos ser 'objetos'? 
Me hace más sentido considerarlos como objetos, pues esta forma tiene una mayor similitud a los diccionarios que ocupa se ocupan en Python. O acaso estoy confundiendo sus formas?

**Comment by jtagle2** [comment]
@frvalenzuela, efectivamente los objetos de json, al leerlos para python obtienes un diccionario, pero esto no es argumento para afirmar que todo debiera ser un objeto (el argumento debería ser por qué escoges diccionarios por sobre listas).
Respecto a la modelación (a nivel teórico), no tienen por qué ser todos objetos, así como tampoco deben ser listas, pues dependerá siempre de como lo modele el programador, y como veo, tu lo hubieses modelado de manera distinta. Lamentablemente, para efectos de la tarea deben ajustarse a los jsons dados, pues para poder probar con distintos archivos json, su programa debe estar preparado para recibir el modelo que tendrán los distintos archivos json utilizados, y ese modelo será siempre el de las bases que se les entregaron (a excepción de la base de jugadores, como se dijo en #32). 
Saludos!

**Comment by frvalenzuela** [comment]
@jtagle2 Entonces el paser que debemos hacer debe convertir cualquier tipo de forma de json a un diccionario en python? o solo debemos convertir arreglos y/o objetos a diccionarios en python? Por ejemplo, podría ser que todo el archivo de texto sea una cadena, o un valor, o solo se mueva entre dos formas.

**Comment by jtagle2** [comment]
@frvalenzuela Efectivamente, el parser debe convertir **cualquier** archivo json a su símil en python, PERO NO NECESARIAMENTE A UN DICCIONARIO. El parser debe convertir los elementos del json  [vistos acá](http://www.json.org/) según la tabla de conversión:

| json | python | caracter que marca límites |
| --- | --- | --- |
| array | lista | [ ] |
| object | diccionario | { } |
| string | string | " |
| number | int o float | Número sin comillas |

Es decir, si hay un `[` en el archivo json, significa que el parser identificará que ahí hay una lista.
Espero se entienda
Saludos

**Comment by frvalenzuela** [comment]
@jtagle2 Entiendo, pero no es un poco contradictorio a lo que dice en la tarea? Perdón por la insistencia, pero estoy bastante confundido.
![image](https://cloud.githubusercontent.com/assets/20147482/17682011/6a7e94ae-631f-11e6-80ae-2cd401b5806b.png)

**Comment by jgmontoya** [comment]
@frvalenzuela Si sigues el enlace que puso @jtagle2 puedes ver que un JSON puede ser un _array_ o un _objeto_ (diccionario en python).

> JSON is built on two structures:
> -  A collection of name/value pairs. In various languages, this is realized as an object, record, struct, dictionary, hash table, keyed list, or associative array.
> - An ordered list of values. In most languages, this is realized as an
>       array, vector, list, or sequence.

Y si te fijas en los archivos subidos, en el nivel de anidación de más afuera te indica qué tipo de estructura ocupar.

Espero que te quede más claro!

**Comment by frvalenzuela** [comment]
@jgmontoya estoy algo confundido, pues como yo veo los archivos subidos son cuatro arreglos y tres objetos.

**Comment by jtagle2** [comment]
@frvalenzuela , si es arreglo devuelve una lista, si es un objeto devuelve un diccionario. El metodo devuelve lo que corresponda según sea el caso (no necesariamente un diccionario).

**Comment by jgmontoya** [comment]
@frvalenzuela 

> @jgmontoya estoy algo confundido, pues como yo veo los archivos subidos son cuatro arreglos y tres objetos.

Toda la razón, fallé ahí. El asunto es como te lo dice @jtagle2 (actualizaré mi comentario para evitar confundir a alguien :sweat:  )

**Comment by DiegoAndai** [comment]
Hola! ¿Cómo hacemos con los paths de archivos para cargar el juego? lo necesitamos saber para abrir el archivo que contiene los json. ¿Se llamarán tal como los subieron pero en .txt? o sea:

el de programones sera: programones.txt
el de movimientos sera: programonMoves.txt
y asi?

¿o dejamos un input para que ustedes ingresen los nombres de los archivos originales y que nuestro juego los guarde después con el nombre y donde le convenga?¿o un input para que cada vez que se inicie el juego deban referenciarse? (no creo que sea esta última jajajajaj)

Muchas gracias.

**Comment by flobarrios** [comment]
Hola! se llamarán igual, no dejes un input para esta parte :)

**Comment by DiegoAndai** [comment]
Gracias :D
