### ISSUE TITLE
Tipo de consultas

### ISSUE THREAD

**Issue by dfvasquez** [IIC2233-2016-02/Syllabus#280]
Hola, tengo la siguiente pregunta: ¿las consultas son solo a partir de un archivo ya creado (con variables y funciones definidas) o se pueden hacer consultas del tipo: "Exp[0]"? (sin haber definido lo que es Exp[]).

Gracias :)

**Comment by agmardones** [comment]
Hola @dfvasquez,

El archivo consultas, debido a su estructura, debe referirse a estados ya creados. Puede darse también, que durante una sesión de tu programa el usuario defina funciones/variables y haga consultas sobre éstas (esto sería análogo a exportar el estado actual y escribir un archivo de consultas referido a éste). Sin embargo, funciones como Exp, entre otras (i.e. las del enunciado), se espera que vengan implementadas y por tanto, se puedan definir variables como:

`foo = Exp[0]`
`bar[x_] = Exp[x]`

Espero haber contestado tu pregunta!. Saludos

**Comment by dfvasquez** [comment]
Ok, gracias!
