### ISSUE TITLE
Spreadsheet de notas no muestra AC04 (columna L)

### ISSUE THREAD

**Issue by gebalassa** [IIC2233-2016-02/Syllabus#281]
**¡Hola!**

El Spreadsheet de notas no me permite ver la columna L, con la AC04. ¿A alguien más le ha pasado? No me permite abrirla tampoco.

Saludos y gracias de antemano,
_Gabriel_.

**Comment by joseluishaddad** [comment]
A mi igual me pasa lo mismo!

**Comment by cjgazali** [comment]
Tampoco tengo los issues correspondientes a las actividades 4 y 5 con la información completa como para recorregir si fuera el caso...

**Comment by vigazali** [comment]
Estoy en las mismas, y en la AC05 me aparece un 1 en la planilla, a pesar de que el commit a revisar corresponde, y no tengo feedback al respecto...!

**Comment by aaossa** [comment]
@vigazali ya estamos al tanto de tu caso, necesitamos que mandes a recorregir para poder hacer todo correctamente :ok_hand:

**Comment by vigazali** [comment]
@aaossa Ok, eso haré. Gracias!
