### ISSUE TITLE
Restricción a funcional

### ISSUE THREAD

**Issue by Zekayrus** [IIC2233-2016-02/Syllabus#282]
De acuerdo a Wikipedia, la programación funcional se caracteriza por evitar efectos colaterales, información mutable y asignación de variables. Sin embargo, en el enunciado solo se prohibe el uso de loops. ¿Eso significa que no va a haber descuento por usar, por ejemplo, `append` o `pop` o recurrir a otras prácticas no-tan-funcionales?

**Comment by rodolfopalma** [comment]
Tienes razón en lo que dices sobre los principios de la programación funcional. Sin embargo, no se penalizará puntaje por el uso de los métodos que mencionas ni por prácticas que no hayan sido explícitamente prohibidas.
