### ISSUE TITLE
Multiplicación de polinomios

### ISSUE THREAD

**Issue by asimonv** [IIC2233-2016-02/Syllabus#283]
Se consideran los casos como (a+bx)(sin(x)*x^+dx) o solo (x + 3)(x^2 + 2), es decir solo con coeficientes numéricos? O cualquier cosa?

**Comment by rodolfopalma** [comment]
El primer caso es una expresión válida. Los coeficientes no serán necesariamente coeficientes numéricos que se encuentren definidos.
