### ISSUE TITLE
Pi

### ISSUE THREAD

**Issue by isidoravs** [IIC2233-2016-02/Syllabus#284]
Hola, podemos establecer el valor de Pi como 3.14159265359? O debemos hacer una mejor aproximación con alguna serie (Taylor, Leibniz)?

Gracias!

**Comment by stephichau** [comment]
Hola @isidoravs ! 

Lo puedes dejar como una constante. 

Saludos!

**Comment by isidoravs** [comment]
@stephichau muchas gracias!
