### ISSUE TITLE
Comando Solve

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#286]
El comando Solve solo es para hacer prints del resultados o tambien puede ser usado para definir variables y funciones? (como el Derivate, Integrate, Sum) Mi pregunta va a que hay casos donde el Solve entregara mas de un valor entonces tener que dar la opcion de guardar el resultado que arroja Solve se complica mucho. Muchas gracias!

**Comment by rodolfopalma** [comment]
Sólo debes imprimir las soluciones que correspondan.

**Comment by andresbannuraschultz** [comment]
Gracias!!

**Comment by andresbannuraschultz** [comment]
Y podrian especificar que cosas si tenemos que poder guardar en variables/funciones y que cosas solo imprimir el resultado? O al reves quizas, que cosas NO hay que guardar. Si no es mucha molestia :)

**Comment by cjgazali** [comment]
las matrices puedes ser asignadas a variables pero no a funciones. eso es tela... en algún issue lo dijeron.

**Comment by andresbannuraschultz** [comment]
Podemos asumir que las expresiones en el Solve siempre seran igual a cero? Gracias!

**Comment by stephichau** [comment]
@abannura no puedes asumir que siempre serán igual a 0.

Saludos!
