### ISSUE TITLE
Uso de parentesis

### ISSUE THREAD

**Issue by bvfernandez** [IIC2233-2016-02/Syllabus#287]
El uso de parentesis en las consultas, o en las funciones siempre me van a indicar en qué orden tengo que hacer las operaciones? o tengo que inferir el orden?
Por ejemplo, en esta consulta, estaría indicando en qué orden tengo que hacer las operaciones:
a+(x^(400/d))
En cambio, en esta no:(como la potencia se hace antes de la division, debo elevar x a 400, despues dividarla por d y luego sumarle a)
a+x^400/d

**Comment by rodolfopalma** [comment]
Ambas son válidas. Para inferir la secuencia de las operaciones debes seguir el [orden de evaluación](https://es.wikipedia.org/wiki/Orden_de_evaluaci%C3%B3n).

**Comment by joseluishaddad** [comment]
No podemos asumir que siempre la priorización se entregará por parte del usuario con uso de paréntesis? jeje

**Comment by bvfernandez** [comment]
graciaaas!@rpalmaotero
