### ISSUE TITLE
Derivadas

### ISSUE THREAD

**Issue by Dalal15** [IIC2233-2016-02/Syllabus#288]
Hola!
Es necesario aplicar regla de la cadena? Gracias.

**Comment by agmardones** [comment]
Hola @Dalal15!

Sí, deben implementar regla de la cadena. Respecto a la dificultad de estas consultas (derivar) les pediremos como máximo una composición. Las posibles funciones ingresadas para estas consultas podrían ser trigonométricas, polinomios, logaritmos, exponenciales pero no productos de estas (es decir, algo del estilo `sin(x)*ln(x)` no podría aparecer, pero si, `sin^2(x)`, `cos(x) + 5ln(x)`, etc)

Saludos!

**Comment by andresbannuraschultz** [comment]
Aprovechod de preguntar, el Sin[x] al cuadrado sera Sin[x]^2 o Sin^2[x]? (La primera porfa jaja)

**Comment by rolfskog** [comment]
No me quedo claro, la reglas del producto y cuociente no son necesarias entonces?

**Comment by agmardones** [comment]
@abannura Tal como aparece en los archivos que subimos (status1.txt) la notación correcta debiese ser `(Sin[x])^2`
@rolfskog Eventualmente no, tu programa debe ser capaz de contestar consultas como las que mencioné en mi otro comentario. Sin embargo, tu podrías decidir implementar las potencias, como por ejemplo `Sin^2(x)` de la forma `Sin(x) * Sin(x)` y utilizar la regla del producto en la última expresión.
