### ISSUE TITLE
Raices

### ISSUE THREAD

**Issue by ceyzaguirre4** [IIC2233-2016-02/Syllabus#289]
Cuantas raices esperan que encontremos para cada polinomio? Yo asumiria que quieren que se muestren n raices (donde n es la mayor potencia de x). Ademas, hay situaciones donde una o mas de las raices son complejas. ¿Estas tambien se muestran?

**Comment by agmardones** [comment]
Hola @ceyzaguirre4, lo acabo de responder en #279. Saludos!
