### ISSUE TITLE
[Tarea 1] Datos jugador

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#29]
En la parte de funcionalidades, al solicitar los datos del jugador, es sobre cualquier jugador o solo sobre el usuario?

**Comment by flobarrios** [comment]
Hola! sobre el usuario que está jugando en ese momento. Saludos!

**Comment by narierao** [comment]
gracias!

**Comment by domingo-valdes** [comment]
Que datos del jugador hay que mostrar, considerando que ademas tenemos el progradex y las consultas?

**Comment by flobarrios** [comment]
Hola! al menos, se debe mostrar lo siguiente:
- Nombre
- Id
- Dinero
- Medallas
- Cantidad de prograbolas disponibles

**Comment by iqacevedo** [comment]
Una duda, en el enunciado dice que también se deben mostrar los programones con sus niveles y stas respectivos, con esto se refiere a los del equipo o del pc de bastian?, o simplemente no es necesario mostrarlos(como entiendo por el comentario de @flobarrios) ?.
Saludos !!!
