### ISSUE TITLE
Parámetro gráficos

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#290]
Pareciera que para las tres funciones de gráficos solo se puede dar el rango de 1 parámetro. Esto me parece extraño para el caso plot 3d.
En plot: el caso de una función de una variable, este parámetro ni siquiera sería necesario consultarlo.
En region plot: ¿se espera una función de dos variables? ¿se espera que se asignen las cotas a una de esas dos variables, según se especifique en el argumento 'parámetro'? No he encontrado funciones de matplotlib que hagan region plot. ¿Existen? ¿Cuál(es)?
En plot 3d: ¿Cómo se ocupan las cotas?

**Comment by ivaniadg** [comment]
Region plot: busca "plot region matplotlib" en google. Aparece en el primer resultado.

**Comment by cjgazali** [comment]
¿Esto?
[http://matplotlib.org/examples/pylab_examples/fill_between_demo.html](http://matplotlib.org/examples/pylab_examples/fill_between_demo.html)
Parece que no sabía bien qué es region plot. Sería fantástico que los enunciados tengan ejemplos.
Sigo sin entender cómo esperan que acotemos plot 3d! Por ahora simplemente estoy graficando en un cuadrado en xy cuyo lado y posición lo define el input de cotas.

**EDIT aaossa:** Corregido el link

**Comment by stephichau** [comment]
@cjgazali revisa la issue #293 !

Saludos!
