### ISSUE TITLE
Derivacion, integracion funciones predefinidas

### ISSUE THREAD

**Issue by ceyzaguirre4** [IIC2233-2016-02/Syllabus#291]
Cual es la notacion _"oficial"_ para llamar a integrar/resolver/derivar, etc una funcion que fue definida anteriormente? No encontre ningun ejemlo en las instrucciones

**Comment by Hernan4444** [comment]
@ceyzaguirre4 revisa la issue #293 .Ahí se responde tu duda de notación
Saludos!!

**Comment by stephichau** [comment]
Hola!

Sería algo así:

f[z_] = 1;
g[z_] = Exp[z];
Integrate[f[z], {z}]; (z)
Derivate[g[z],z]; (Exp[z]) 
Solve[g[z] == 1, z, Reals]; (z = 0)

Saludos!
