### ISSUE TITLE
Aclaración Sintaxis Gráficos

### ISSUE THREAD

**Issue by stephichau** [IIC2233-2016-02/Syllabus#293]
Estimados/as:

La sintaxis para los gráficos **oficial** es la siguiente: 

**`Plot`**: Plot[función1,funcion2, funcion3, funcionN, {variable, cota inferior, cota superior}, color, linewidth];
**`RegionPlot`**: RegionPlot[ funcion1,funcion2, {variable, cota inferior, cota superior}, color, linewidth];
**`Plot3D`**: Plot3D[funcion, {variable1, cota inferior, cota superior}, {variable2, cota inferior, cota superior}, color, linewidth]; 
**Ojo que la función podría ser de 1 variable**

Las opciones **color** y **linewidth** son opcionales, es decir, se puede no especificar en la consulta por lo que deberán dejar un color por defecto. 

Los gráficos deberán mostrarse así:

Plot[x^2, x^3, {x,0, 1.5}];
<img width="619" alt="screen shot 2016-09-27 at 3 14 55 pm" src="https://cloud.githubusercontent.com/assets/16126322/18886636/168d8188-84c7-11e6-89e9-52a2fe4edb98.png">

RegionPlot[x^2, x, {x,0,1.5}];
<img width="629" alt="screen shot 2016-09-27 at 3 14 47 pm" src="https://cloud.githubusercontent.com/assets/16126322/18886628/0adac18e-84c7-11e6-8ba3-8f669250d9f7.png">

Plot3D[Sin[x], {x,-5,5}];
<img width="519" alt="screen shot 2016-09-27 at 3 21 16 pm" src="https://cloud.githubusercontent.com/assets/16126322/18886779/c5c3cbda-84c7-11e6-954d-0a089ebb3805.png">

Lo anterior también se puede definir como:

f[x_] = x^2;
g[x_] = x^3;
i[x_] = x;
h[x_] = Sin[x];

Plot[f[x],i[x], {x,0,1.5}];
RegionPlot[f[x], i[x], {x,0,1.5}];
Plot3D[h[x], {x, -5, 5}];

**Comment by andresbannuraschultz** [comment]
Como se entregaran los colores en caso de tener mas de una funcion graficada? O todos del mismo color nomas?

**Comment by stephichau** [comment]
@abannura si, todos del mismo color :)

**Comment by andresbannuraschultz** [comment]
Gracias!!

**Comment by andresbannuraschultz** [comment]
Hola, me entro otra duda sobre el color. Viene como "blue" o como "b"? o como ambos?

**Comment by stephichau** [comment]
@abannura se pediría como "b".

Saludos!

**Comment by andresbannuraschultz** [comment]
Gracias!

**Comment by npcariman** [comment]
El gráfico por regiones siempre recibe como parámetros dos funciones o existen más variaciones?

**Comment by stephichau** [comment]
@npcariman siempre recibirá dos funciones :)
