### ISSUE TITLE
Imports ciclicos

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#294]
Tengo el siguiente problema de imports: Para integrar necesito evaluar, y para evaluar necesito (a veces) integrar. Queria saber si hay alguna forma de solucionar esto o estoy obligado a tener un solo codigo con ambas funciones. Algo me explicaron sobre que en programacion funcional los llamados recursivos causan problemas de este tipo y no queda otra que tener un solo archivo enorme, pero no estoy seguro de esto tampoco.

Ademas queria aprovechar de preguntar si en la derivacion surge este problema o no. Ya que de la derivacion (como yo lo habia pensado) solo pueden resultar funciones (aun que sea la funcion constante) y no variables. Es asi o tambien puedo guardar el resultado de una derivada como variable? En caso de ser posible, asumimos que el input es correcto no cierto? (es decir, que solo vaya a guardar una variable constante). Muchas gracias!

**Comment by agmardones** [comment]
Hola @abannura, acerca de tu última pregunta, puedes asumir algo como #269 (donde puse el ejemplo de cómo guardaríamos los output con más variables, aquí tambien aplica).

**Comment by andresbannuraschultz** [comment]
Vale gracaias!
