### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by FranciscoLarach** [IIC2233-2016-02/Syllabus#295]
¿Debo asumir que el usuario no puede cambiar ciertas variables y funciones clásicas tales como Pi , Sin, Cos... etc?
Y siendo este el caso, no debo permitir que cambie las funciones que me dan, pero ¿que variables estarían protegidas?

**Comment by agmardones** [comment]
Hola @FranciscoLarach!

Para facilitarte esto, puedes asumir que no se definirán nuevamente funciones/variables notables que ya fueron definidas en el enunciado. Es decir, no podría aparecer algo como:

`Piecewise[x_] = x`
`Pi = 1`

**Comment by FranciscoLarach** [comment]
Excelente, gracias!
