### ISSUE TITLE
Trigonometricas

### ISSUE THREAD

**Issue by jatrijori** [IIC2233-2016-02/Syllabus#296]
Definí las funciones trigonométricas con las sumatorias que salen en el enunciado (con 100 iteraciones) y me surgen dos problemas:
1) No aproxima bien valores simples como sin(45), ¿puede tener que ver con el tema de radianes/grados?
2) No funciona para valores pequeños como pi, por ejemplo (OverFlowError), ¿por qué ocurre? ¿puedo arreglarlo?
De antemano, muchas gracias.

**Comment by DiegoAndai** [comment]
La aproximación de las trigonométricas es con radianes, o sea 45 grados seria Pi/4, que es ~ 0.785 (muy aproximadamente xD). El OverflowError lo explican en #262, se produce porque el tamaño de los floats crece mucho cuando vas sumando términos de la serie, sin embargo para las trigonométricas (al menos yo he probado con seno y coseno) deberías obtener una muy buena aproximación con alrededor de 50 iteraciones, y no va a tirar el error. Creo que puedes llegar hasta 85 iteraciones y aparece el OverFlowError, también lo dice en #262.

**Comment by tcgarrido** [comment]
Hola! me quedó una duda, al momento de probar las funciones trigonométricas, los valores que serán ingresados estarán en grados o radianes? O debemos recibir ambos?

Saludos

**Comment by Hernan4444** [comment]
@tcgarrido Los valores seran entregados en radianes :)
Saludos!

**Comment by Jaluco** [comment]
Hola, te cuento que para el problema de overflow con eso yo cambie el return de mi funcion factorial a floats y se solucionó el problema
