### ISSUE TITLE
Estructura general de la tarea 3

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233-2016-02/Syllabus#297]
Para ver si entiendo bien que hay que hacer.

Existen 3 archivos: 1)variables y funciones, 2)consultas, 3)resultados.

Desde consola solo están las opciones: 1)definir variables y funciones, 2)cargar estados, 3)guardar estados y 4)cargar consultas.

¿Estoy bien?

Otra pregunta:

Suponiendo que estoy bien con lo anterior, deduzco que solo puedo crear consultas directamente escribiendo en el archivo y para crear funciones y variables desde la consola. ¿Está bien eso?
Ademas, algo que no se especifica en el enunciado y quisiera estar seguro de que lo entiendo bien; a medida que voy creando funciones, la idea es que vayan apareciendo imprimidas en para saber como va mi estado? y cuando cargo consultas, ¿Estas tienen que aparecer imprimidas para poder saber que voy a consultar y después consultar o se consulta automáticamente cuando la cargo?
¿Si hago las consultas, solo se actualiza el archivo resultados o además se imprimen los resultados pedidos?

Espero se hayan entendido mis dudas. Gracias.

**Comment by agmardones** [comment]
Hola @jorgeriesco!

Muchas de las cosas que preguntas las puedes definir tú y explicitarlas en tu README, ya que no están necesariamente relacionadas con el correcto funcionamiento del intérprete. 

Existen archivos de estado (con variables y funciones como mencionas) y un archivo de consultas (el que después de leerlo debiese crear un nuevo archivo de resultados). Lo ideal seria que tu programa al inicializar leyese las consultas y creara los resultados, para posteriormente permitir al usuario seguir trabajando, éste último podría referirse a crear variables/funciones nuevas, o bien, seguir haciendo consultas con el estado actual (recuerda que la consola debiese poder recibir cualquier comando válido definido en el enunciado, sean definiciones o consultas). También puedes decidir sobre cómo implementar el menú (cómo/dónde preguntar al usuario si desea guardar el estado/salir del programa/usar el intérprete)

Sobre las impresiones, queda a tu criterio. Si se imprimen los resultados en consola, si se imprime la función recién definida, etc. Implementa lo que tu consideres pertinente para mejorar la interacción con el usuario (pero recuerda que cosas como crear el archivo de output son necesarias).

Espero haberte respondido! Saludos.
