### ISSUE TITLE
Derivadas e Integrales

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2233-2016-02/Syllabus#298]
hola, cuando se integre o derive van a pedir arccos, arcsen, ln, etc?
Cuales son todas las funciones a considerar? 
Gracias!!!

**Comment by agmardones** [comment]
Hola @NicolasAguirre, mira #260. Recuerda buscar tu pregunta antes de hacerla! (principalmente por ahorrarte la lata de esperar respuesta :) )
