### ISSUE TITLE
status3 y Matrices

### ISSUE THREAD

**Issue by sormazabal** [IIC2233-2016-02/Syllabus#299]
Hola!
En el status3.txt se declaran las matrices como:

"M = [[1,2,3],[4,5,6]] 
N = [[7,8],[9,10],[11,12]] "

sin el ";" que va después de declarar una variable o función. Se declaran así las matrices o fue un error y en realidad el archivo status3.txt debería ser:

"M = [[1,2,3],[4,5,6]];
N = [[7,8],[9,10],[11,12]]; 
"

**Comment by tcgarrido** [comment]
@sormazabal Hola! en el archivo status3.txt que tengo yo, si salen los ";" después de cada matriz, quizás no hiciste git pull cuando lo arreglaron. 

Saludos
