### ISSUE TITLE
Problema al instalar librerias

### ISSUE THREAD

**Issue by figre** [IIC2233-2016-02/Syllabus#3]
Hola tengo un problema para instalar las librerias, al ingresar cualquier codigo me tira este error.
![captura de pantalla 32](https://cloud.githubusercontent.com/assets/20782785/17314501/f5034fe0-5832-11e6-9f98-7b261ae207cb.png)
Ayuda para solucionarlos. Gracias

**Comment by felipehv** [comment]
Hola!

Eso es porque debes correrlo directo en consola y no a través de Python!

Saludos!

**Comment by figre** [comment]
Lo corro directo en la consola y tampoco funciona
![captura de pantalla 33](https://cloud.githubusercontent.com/assets/20782785/17314607/a8337888-5833-11e6-92a2-347cf1d2452a.png)

**Comment by felipehv** [comment]
Debes poner python antes de pip, perdón olvidé especificarlo, avisame como
te va!

python pip install --upgrade simpy

_Felipe Haase Vargas_
*Consejero Territorial Ingeniería - Solidaridad *
Estudiante de Ingenieria
Pontificia Universidad Católica de Chile

2016-08-01 22:02 GMT-04:00 figre notifications@github.com:

**Comment by figre** [comment]
Nada mismo problema, python no se reconoce como un comando interno o externo, programa o archivo por lotes ejecutables.

**Comment by felipehv** [comment]
Ah perfecto, es porque no tienes seteada la variable de entorno de python

Puedes seguir [este tutorial](http://www.codingdefined.com/2015/09/how-to-set-up-pythonpath-in-windows-10.html) (con cuidado) y probar. No borres ninguna de las otras variables que ya
existen en el sistema, simplemente agrega una nueva como dice la página.
Si no también puedes ver [este tutorial](https://drive.google.com/a/uc.cl/file/d/0B2Gkr8Xpa8TqcGpXMVVWc3h4ZlE/view) hecho por @mjjunemann 

Luego de eso deberías poder correr python en la consola.
Me cuentas!

_Felipe Haase Vargas_
Estudiante de Ingenieria
Pontificia Universidad Católica de Chile

2016-08-01 22:06 GMT-04:00 figre notifications@github.com:

**Comment by FernandoPieressa** [comment]
Hola! Puede que no tengas pip por defecto, intenta instalarlo.

Aquí va una guia: https://packaging.python.org/installing/#requirements-for-installing-packages

**Comment by figre** [comment]
http://www.codingdefined.com/2015/09/how-to-set-up-pythonpath-in-windows-10.html
Este tutorial sirvio a la perfección, gracias Felipe
