### ISSUE TITLE
Funcion caminar 

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#30]
el usuario al escoger la opcion caminar, esto implica que avanza o retorocede un solo espacio? vale decir, cada vez que el usuario quiera caminar un espacio debe seleccionar esta opcion? (tipo menu iterativo)

**Comment by flobarrios** [comment]
Si, camina o retrocede solo 1 espacio. Saludos!

**Comment by narierao** [comment]
gracias!
