### ISSUE TITLE
Derivadas e integrales

### ISSUE THREAD

**Issue by lefischer** [IIC2233-2016-02/Syllabus#300]
hola:
repecto a las reglas de la derivacion entran:

a) suma y resta (fx +- gx)
b) producto (fx  \* gx)
c) division (fx / gx)
d) cadena (fx(gx))
e) potencia ((fx  ^ gx)

cuando se integra sin cotas como se expresan los resultados? se deja (resultado + c)  con c una constante

**Comment by nifalconi** [comment]
Estimado o estimada:

Se espera que resuelva este tipo de derivaciones, y en particular sus combinaciones. Recomiendo que tenga especial cuidado al implementar la regla de la cadena.  

Al integrar sin cotas, se espera retornen la primitiva, sin la constante.

EDIT: Te podría servir revisar #260 y #288!
