### ISSUE TITLE
Modo calculadora

### ISSUE THREAD

**Issue by domingo-valdes** [IIC2233-2016-02/Syllabus#301]
Me surgió la duda de si nuestro programa también debe ser capaz de recibir inputs como "2+2*Cos[Pi]" y calcularlos sin necesariamente guardarlos en alguna función o variable, como si fuera una calculadora. Asumo que simpre se guardarán en algún lado?

**Comment by agmardones** [comment]
Hola @domingo-valdes!

Tu programa debiese ser capaz de recibir inputs así, quizás no necesariamente vía consola (ya que no está especificado en el enunciado) pero sí podrían haber consultas de ese tipo (sin que se guarden en variables) en el archivo de texto de éstas, por lo que de todas formas tendrías que implementar esto. No debería influir mucho en el desarrollo de tu tarea, sin embargo, es tu decisión que se puedan imprimir los resultados de comandos tipo "calculadora" .

Saludos!
