### ISSUE TITLE
Evaluar

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2233-2016-02/Syllabus#302]
Hola, para evaluar una función puedo usar este código:
http://pyparsing.wikispaces.com/file/view/fourFn.py (por supuesto que sin usar numpy, math, etc). Este codigo viene de http://pyparsing.wikispaces.com/, que creo q es como una libreria.
Otra duda, porque no está permitido usar eval ?? 
Gracias!!!

**Comment by aaossa** [comment]
Sobre `eval`: https://github.com/IIC2233-2016-02/Syllabus/issues/246#issuecomment-248971725

**Comment by Hernan4444** [comment]
@NicolasAguirre puede utilizar el código **PERO** ten cuidado de no utilizar ningún comando o librería que está prohibida o que no se haya preguntado si es posible utilizar. Estaba revisando el código y se realiza la siguiente importación: 

```
"from pyparsing import Literal,CaselessLiteral,Word,Combine,Group,Optional,\
    ZeroOrMore,Forward,nums,alphas"
```

Y dicha librería **no** se ha permitido utilizar.
Saludos!!

**Comment by NicolasAguirre** [comment]
@Hernan4444 Muchas gracias por responder. Tengo otra duda. Si por "x" motivo no me sale el parser, puedo usar una libreria no permitida para evaluar, para asi poder derivar, integrar, graficar (etc)???... Eso si pongo en el readmy q usé esta libreria no permitida para q no me pongan ptos en el parser pero asi puedo sacar ptos en en graficar y evaluar integrales, derivada, etc . Gracias.

**Comment by Hernan4444** [comment]
@NicolasAguirre Si por "x" motivo no lo logras, deberás ingeniártelas para demostrar el funcionamiento de tus funciones, gráficas y operaciones de todo tipo para poder tener puntaje en los demás items pero por ningún motivo puedes ocupar librerías no permitidas. 

De todos modos deberás especificar en el readme y/o en el código que cosas estas haciendo para demostrar que funciona y si es posible donde se pueden cambiar los valores para operar, evaluar o graficar otras cosas..

Saludos!!!
