### ISSUE TITLE
uso de for en generadores

### ISSUE THREAD

**Issue by mrafaeli** [IIC2233-2016-02/Syllabus#303]
Hola, en el material de clases aparece este ejemplo:

`a = (b for b in range(10))`
`for b in a: print(b)`

¿Está permitido este uso de for en la tarea, en la que se itera sobre un generador?
muchas gracias

**Comment by agmardones** [comment]
Hola @mrafaeli,

El segundo for que muestras **no** está permitido. Sin embargo, si lo que deseas es imprimir cosas en pantalla, un código equivalente a lo que preguntas:

`print(*a, sep="\n")`

Saludos!
