### ISSUE TITLE
Paradigma funcional

### ISSUE THREAD

**Issue by fipaniagua** [IIC2233-2016-02/Syllabus#304]
Respecto a la tarea 3 ; si se supone que estamos trabajando el paradigma funcional, ¿es incorrecto modelar la tarea con objetos
(e.g. definir un objeto función que pueda ser derivado, integrado, etc a través de métodos)?

**Comment by mjjunemann** [comment]
Hola, no es incorrecto modelar tu tarea con objetos ya que de alguna forma debes contener la información que quieres trabajar sobre. Luego estos objetos puedes mapearlos , filtrarlos de la forma que quieras, no se contradicen los paradigmas.
