### ISSUE TITLE
Definicion de Variables

### ISSUE THREAD

**Issue by rolfskog** [IIC2233-2016-02/Syllabus#305]
Hola tengo unas dudas acerca de las variables:
1) Se puede definir una variable con variables no existentes, por ejemplo a = b +c sin que exista una de estas? El enunciado solo meciona que debemos mostrar error si se intenta llamar a una variable no definida.
2) Si una variable es definida como a=b+c y luego se modifica la variable b el valor de la variable a tambien debe cambiar?

**Comment by agmardones** [comment]
Hola @rolfskog,

1) No se debe poder definir variables a partir de variables no definidas, ya que de igual manera estarías llamando a la variable que no está definida, por lo que se debiese arrojar error en ese caso.
2) El valor de la variable `a` no debiese cambiar.

Saludos!

**Comment by dfvasquez** [comment]
Una pregunta de notación respecto a la definición de variables... el usuario debe ingresar: ¿"a = 2" o "a = 2;"?
