### ISSUE TITLE
Requisitos para salir de una ciudad

### ISSUE THREAD

**Issue by jbsaeza** [IIC2233-2016-02/Syllabus#31]
En el enunciado en la sección 4.2 Funcionalidades, donde se refiere a Caminar, dice que si el jugador decide salir de una ciudad para avanzar hacia la siguiente dice que esto ocurrirá solo si cumple los requisitos, habla respecto a como debemos notificar al jugador si este no cumple estos "requisitos" pero no se refiere a cuales son estos. El requisito es si gana la medalla del gimnasio de la ciudad respectiva?

**Comment by roy350** [comment]
yo tengo otra duda relacionada con los requisitos asumiendo que fueran que ganamos la medalla de la ciudad respectiva en "viridian city" el lider de gimnasio tiene sus pokes en nivel 45 aproximadamente entonces en esa ciudad no habria restriccion y "saltarnos" momentaneamente ese gimnasio como en el videojuego real para luego volver? muchas gracias!

**Comment by jgmontoya** [comment]
Hola!

El requisito es haber batallado al menos una vez en el gimnasio, independiente del resultado de la batalla. Este requisito será igual para todas las ciudades.

Saludos!

**Comment by jtagle2** [comment]
Vamos a cocinar niños
@roy350 , por favor, al momento de crear issues o preguntar cosas dentro del foro, cuidemos la redacción y el uso de puntuación, así el que lee va a entender más fácil lo que quieres preguntar. Si no, ¿Cómo sabremos si el almuerzo del día serán niños al horno, o si fue un almuerzo cocinado por los niños?
Saludos!

**Comment by asimonv** [comment]
Encuentro que no tiene sentido entrar y perder, si fácilmente podemos saber si el usuario tiene todas las medallas restantes menos la de ese gimnasio para poder entrar, tal como el juego original.

**Comment by flobarrios** [comment]
@asimonv para corregir, cambiaremos las ciudades y programones (y quizás ni siquiera existan en el juego original) por lo que si lo haces como tu dices, te podrías arriesgar a que esa ciudad no esté en el mapa. Además, la medida fue tomada para facilitar la tarea y no agregar más cosas a ésta. Te recuerdo que tienen que programar Programón Rojo y **NO** Pokémon Red. Saludos!

**Comment by asimonv** [comment]
OK, gracias!
