### ISSUE TITLE
Duda 

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2233-2016-02/Syllabus#310]
Hola, en primer lugar me podrían responder lo que pregunté por favor que ando estancado: https://github.com/IIC2233-2016-02/Syllabus/issues/302

Si la respuesta a la pregunta anterior es "no":
Mi duda es respecto a si estoy abordando bien la tarea.  Cuando integro, derivo, gráfico (por ahora) tengo que evaluar un string (ej:  "2+2*(2^5)") , pero hacer esto ultimo me tiene complicado ya que deberia hacer un parser para evaluar string y pasarlo a int. Todo se solucionaria usando eval, u otras funciones similares, pero no se puede.  
Mi duda es si estoy abordando bien o mal el tema.  Si tengo que cambiar mi modo de hacer las cosas o bien envdad tener que hacer un parser (Ojala se entienda, q toy medio estancado).  
Muchas Gracias!!

**Comment by Hernan4444** [comment]
@NicolasAguirre acabo de responder la otra issue.
Sobre tu duda en esta, en verdad esperamos un parser que pase de string a int o a las funciones pertinentes para obtener los datos esperados y por ello no permitimos eval o funciones similares.
Saludos!!

**Comment by andresbannuraschultz** [comment]
Tambien tengo una duda sobre el parser. Cuando tengo solo numeros o funciones evaluadas todo anda bien. Pero no he podido simplificar expresiones con variables no evaludas. Por ejemplo: si hago la sumatoria Sum[3y, {x,0,1}] no soy capaz de decirle al programa que 3y+3y = 6y. Quizas este caso se puede resolver de otra forma (como sacando la expresion si no contiene a la variable fuera de la sumatoria y simplemente multiplicar esa expresion por el resultado de la sumatoria). Pero no todos los casos son asi y hay veces que realmente necesito poder evaluar esas expresiones para no dejarlas como un string eterno "3y+3y+3y....+3y" (que luego al evaluarlo en algun y si puedo calcularle el valor). En el fondo me di cuenta que mi problema es con la funcion simplify para cuando no tengo valores. Algun tip o ayuda para poder enfrentar este problema? Muchas gracias!
