### ISSUE TITLE
Dominio de funciones

### ISSUE THREAD

**Issue by vacodoceo** [IIC2233-2016-02/Syllabus#311]
Quizás sea algo obvio, pero no entiendo a que se refiere el punto 

> "Cuando se dena una función, su programa debe reconocer el Dominio de esta, y revisar si el/los parámetro/s entregados pertenecen al Dominio, en caso contrario: Error13"

 del apartado numero 7.

Acaso debo reconocer que todas las variables entregadas al definir la función estén presentes en la función? O que todas las variables presentes en la función deban ser entregadas a la hora de definirlas?

Saludos

**Comment by stephichau** [comment]
Hola @vacodoceo !

A lo que va ese punto es por ejemplo, si yo defino f[x_] = 1/x; y después llamo f[0]. En este caso, debería lanzar error dado que 0 no pertenece al dominio.

Saludos!

**Comment by vacodoceo** [comment]
Ok, muchas gracias !
