### ISSUE TITLE
?

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-02/Syllabus#313]
Hola !
Pueden dar más ejemplos de inputs sobre el comando "?" para saber sobre cierta función ? Quiero saber como leer la consulta y como entregar los resultados.
Gracias de antemano.

**Comment by stephichau** [comment]
Hola @Diiru ! 
La consulta sería algo del estilo **_comando?_**. 

(Input):
`Derivate?;` 

Un output podría ser algo así: 
**Derivate:
Derivate[f, x]
"Comando que sirve para calcular la derivada parcial de la función f con respecto a x".**

Espero que se haya entendido, 
saludos!

**Comment by jatrijori** [comment]
Ese comando de consulta y otros de los comandos auxiliares salen en el enunciado sin el ";" del final que los demás comandos tienen, ¿esto está bien o también vendrán con el ";" al final? ¿Puedo asumir que absolutamente todos los comandos que entren en la consola terminarán con ";"?

**Comment by stephichau** [comment]
@jatrijori  sí, ya lo cambié :)

**Comment by sormazabal** [comment]
Hay que incluir en el help +, - y / ??

**Comment by Iruretagoyena** [comment]
@stephichau Gracias !! Entonces, solo para corroborar ( y citar esta issue en mi Read.me): 
Solo se pondrán consultas SIN el [funcion,parametros,loquesea]
E.g. MCM y no MCM[a,b,c],
Plot y no Plot[variable/funcion, parametro, cota inferior, cota superior, color, linewidth], 
Integrate y no  Integrate[Tan[x],fx,0,Pi/3g]  ?

Gracias !!

**Comment by stephichau** [comment]
@sormazabal puedes no incluirlos en el help

@Diiru Solo se incluirá el nombre del comando seguido de **?**

Saludos!
