### ISSUE TITLE
Dimension matriz

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#315]
Tengo la duda de que es la dimension de la matriz. Es simplemente el nxm? o tiene que ver con las bases de un espacio? Busque en google y no encontre nada muy claro. Gracias!

**Comment by Hernan4444** [comment]
@abannura estas en lo correcto, la dimensión de la matriz es simplemente nxm
saludos!

**Comment by andresbannuraschultz** [comment]
Gracias!!

**Comment by fvandeputte** [comment]
Y con el rango a que se refiere? Al numero de filas?

**Comment by iqacevedo** [comment]
Hola aquí sale es lo que se ve en álgebra lineal !

https://es.m.wikipedia.org/wiki/Rango_(álgebra_lineal)#Rango_de_una_matriz
