### ISSUE TITLE
MCM

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-02/Syllabus#316]
Hola !
MCM debería verificar si A es el minimo comun multiplo entre B y C. No debería ser A un número ? No entiendo por que en el ejemplo sale MCM[int, 2,5]; o acá se esta verificando que el mínimo sea un integer y deberíamos dar True/False ?
Gracias de antemano

**Comment by FranciscoLarach** [comment]
Ahí int es la variable respuesta de la integral! (En teoría un valor)

**Comment by stephichau** [comment]
@Diiru Tal como dice @FranciscoLarach, en ese caso int es un valor que se definió en uno de los archivos.

Saludos!
