### ISSUE TITLE
Sobre simplicidad de consultas

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#317]
Podemos asumir que no habrá tanta "mezcla" de comandos? Por ejemplo si quiero calcular una integral donde uno de los parametros es el determinante de una matriz? O eso es completamente valido? jaja Gracias!

**Comment by stephichau** [comment]
@abannura Lo que pusiste es completamente válido! Tu programa debe estar preparado para cualquier tipo de consultas :)

**Comment by andresbannuraschultz** [comment]
UFF, jaja dale gracias!
