### ISSUE TITLE
Algunos operadores matemáticos

### ISSUE THREAD

**Issue by srvasquez** [IIC2233-2016-02/Syllabus#318]
Hola, tengo la siguiente duda puede sonar un poco obvia pero se pueden operadores como modulo, 2**3, en general los que vienen incluidos en python ??, de ante mano muchas gracias. Otra duda si ocupo ciertos algoritmos para determinar por ejemplo el mcd, como el de euclides es válido ?? entiendo que si fuese válido lo tendría que explicitar en el README.

**Comment by Hernan4444** [comment]
@srvasquez si tu pregunta se refiere a ocupar operadores de python, la respuesta es **si** pero solo los que vienen directamente de python, sin necesidad de importar nada.
Sobre tu segunda pregunta, puedes ocupar diferentes algoritmos sin necesidad de hacer referencias, mientras funcionen y no quebranten ninguna regla de usar librerías no permitidas. Solo si llegas a copiar códigos de internet, lo correcto es explicitarlo en el Readme

**Comment by jgmontoya** [comment]
Aprovecho de agregar que si bien puedes ocupar el algoritmo que quieras sin hacer referencias, es una buena idea comentar qué algoritmo usaste en tu readme. De esta manera el ayudante que revise tu tarea sabrá que tu implementación es correcta, es decir, que efectivamente calcula lo que debe calcular.

Saludos!
