### ISSUE TITLE
Formato del diccionario que representa a un jugador

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#32]
En el ejemplo se muestra que el "valor" asociado a la key id_jugador es otro diccionario que contiene toda la informacion sobre el jugador. Esta bien? o fue un error de tipeo y lo que tenemos que hacer es en realidad asociar al key id_jugador el valor del id que creamos para ese jugador. Muchas gracias.

**Comment by andresbannuraschultz** [comment]
En el fondo, no seria mas comodo que toda la info sobre un jugador estuviese en un mismo "nivel" y no anidada dentro del atributo id?

**Comment by FernandoPieressa** [comment]
@abannura No olvides que el ejemplo de información de jugador es solo un EJEMPLO. Si quieres puedes escribir la información de los jugadores de otra manera mientras cumpla con todo lo pedido en el enunciado y lo especifiques en el README.md

**Comment by mjjunemann** [comment]
@abannura pueden guardar la información como ustedes quieran y es totalmente valida siempre que puedan resolver la tarea si quieren pueden guardar la información en 1 archivo o 3 como les acomode, el archivo era a modo de ejemplo para que tuvieran una idea de como modelar guardar la información.
Lo del atributo "id_jugador", fue por al que leer esto como diccionario van a poder hacer una búsqueda más rapida del jugador que quieran  de la forma `dic['id_jugador']`, en el caso de que estuvieran en el "mismo nivel" , tendrias una lista de diccionarios , y tendrias que iterar por todos hasta encontrar el que quieres: 

``` python
for jugador in lista_de_jugadores:
   if jugador['id_jugador'] == jugador_que_busco:
         ....
```

Se puede ver que los dos son validos, pero es la forma que guardas la información.

**Comment by andresbannuraschultz** [comment]
Dale, gracias a los dos!

**Comment by Iruretagoyena** [comment]
Una duda chica, "id_jugador" luego será, por ejemplo, un "1", "2", etc ?

**Comment by jgmontoya** [comment]
@Diiru Sería el identificador único.
