### ISSUE TITLE
Duda Gráfico

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2233-2016-02/Syllabus#321]
Hola, el grafico en 3d puede quedar como la siguiente imagen?? o tengo q usar la funcion surface ? Gracias!!!!
![grafico](https://cloud.githubusercontent.com/assets/20804346/19017743/dacffbaa-881b-11e6-8a18-52049472cb72.jpg)

**Comment by stephichau** [comment]
Hola @NicolasAguirre ! 
Lo esperado es que se vea continuo, tal como se ve en la issue [#293](https://github.com/IIC2233-2016-02/Syllabus/issues/293) :)
