### ISSUE TITLE
Definición de matrices

### ISSUE THREAD

**Issue by ndleyton** [IIC2233-2016-02/Syllabus#322]
Hola, tengo una duda. Al definir una matriz, puede ser que la definan con operadores entremedio? como por ejemplo 'Matrix = [[1,2],[3,4]+[[3,4],[2,3]]'?

**Comment by FernandoPieressa** [comment]
No habran operadores entremedio de las matrices, Saludos!

**Comment by Pyralspite** [comment]
Hola, pueden haber funciones evaluadas dentro de las matrices? Por ejemplo: [[f[3],2], [Abs[b],Sin[Pi]] o solo van a haber números y variables? (Perdón si ya han preguntado esto antes, no encontré la issue)

**Comment by stephichau** [comment]
@Pyralspite siempre habrán números y/o variables :)
