### ISSUE TITLE
duda

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233-2016-02/Syllabus#324]
Si hago un parser que lee lo siguiente: "f[x_,y_] = x^2 - sin[x+y]" (es un ejemplo). La idea es que siempre trabaje esto como un string? por ejemplo si consulto la integral de esa funcion, ¿tngo que ir analizando caracter por caracter para, con una funcion, ir resolviendo mientras analizo los caracteres? Si hay una forma más simple agradecería mucho la ayuda.

**Comment by isipalma** [comment]
Hola!

La verdad la forma de resolver un problema no siempre es la misma, por lo tanto tu debes encontrar la forma que mas te acomode y haga sentido para que luego sigas en base a esa idea.

Si quieres, por ejemplo, podrias hacer funciones que te vaya parseando las consultas (siguiendo tu idea de verlo como string) pero necesariamente no tiene porque ser asi, hay varias formas de verlo.

Saludos!
