### ISSUE TITLE
Variables y funciones en Consultas.txt

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-02/Syllabus#325]
Hola !
Se que probablemente la respuesta será no, pero me entro a asegurar;
No habrá definiciones de funciones o variables en los archivos de consultas ?
Gracias !

**Comment by stephichau** [comment]
Hola @Diiru ! 
No, las funciones y variables se definirán solo en los archivos correspondientes :) 

Saludos!
