### ISSUE TITLE
Funciones generadoras sin for/while exterior

### ISSUE THREAD

**Issue by DiegoAndai** [IIC2233-2016-02/Syllabus#326]
Hola! Me surge la duda de cómo se podría aplicar una función generadora que aplique `send` y `next` sin utilizar un `for/while` ni interacción con usuario. He probado con `map` pero creo que no es posible pues si entregamos la función generadora a `map`, los objetos generados quedan fijos y no se puede hacer `send`.

Gracias :)

**Comment by jtagle2** [comment]
@DiegoAndai, para esto, hay que primero entender bien como funciona un generador.
En primer lugar, si nuestro generador es un generador que recibe parámetros desde fuera, olvidémonos de `next` por un rato, y utilicemos solo `send`
Si vemos los generadores que reciben y envían datos, podemos notar que estas 2 acciones se llevan a cabo en la línea donde está la sentencia `yield`. Es decir, cuando se ejecuta el `yield`, se hacen 2 cosas: Recibo un parámetro desde afuera, y retorno un parámetro que está dentro del generador (en ese orden). Ahora, si vemos el código desde el main (ya no analizamos el `yield`, sino vemos el `send`), `send` también hará 2 cosas, envía el valor al generador, y recibe un parámetro desde el generador (en ese orden).
Ahora, para tu problema, solo hay que saber aplicar lo mencionado anteriormente (que a través de `send` yo no solo envío parámetros, sino también los recibo). A modo de ejemplo, tenemos el siguiente decorador:

``` python
def generador():
    next_number = "Esto no lo muestro nunca porque primero recibo el parámetro y luego retorno"
    while True:
        next_number = yield next_number
```

Y queremos obtener una lista con los números del 10 al 15, utilizando el generador pero sin usar `while` o `for`. Si sabemos que el `send` envía y recibe, lo que podemos hacer, es que la lista se forma mediante lo que retorna `generador.send(valor)` Es decir, algo como:

``` python
gen = generador()
gen2 = generador()
gen.send(None)
gen2.send(None)
solucion1 = [gen2.send(k) for k in range(10,16)]
solucion2 = list(map(lambda k: gen.send(k), range(10,16)))
print(solucion1)
print(solucion2)
```

El output de dicho código sería

``` python
[10, 11, 12, 13, 14, 15]
[10, 11, 12, 13, 14, 15]
```

Si quieres entender con más profundidad generadores (por ejemplo, por qué hay que enviar ese None), puedes verlo [acá explicado por usuarios](http://stackoverflow.com/questions/36997078/python-behaviour-of-send-in-generators) o ir  [acá para verlo con más detalle](https://www.python.org/dev/peps/pep-0342/)
Espero te sirva.
Saludos!

**Comment by DiegoAndai** [comment]
Muchas gracias, no había visto la respuesta. Perdón la demora, cierro el issue.
