### ISSUE TITLE
Operaciones Matriciales 

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-02/Syllabus#327]
Hola ! 
Los comandos matriciales (MatrixMultiply, Det, Range, Dim, Trans e Inv) siempre llamaran a matrices ya definidas ? O podría aparecer un Det[[[1,2,3],[4,5,6],[7,8,9]]] o un MatrixMultiply[[[1,2,3],[4,5,6],[7,8,9]], [[1,2,3],[4,5,6],[7,8,9]]] ?
Gracias !!

**Comment by agmardones** [comment]
Hola @Diiru!

No podría aparecer el segundo caso, siempre se aplicarán sobre matrices ya definidas.

Saludos
