### ISSUE TITLE
Dominio funciones

### ISSUE THREAD

**Issue by danyestay** [IIC2233-2016-02/Syllabus#328]
Hola, tengo una duda con el dominio de funciones que aparecen en el apartado matemático como sin(x), cos(x), etc. La función debería recibir radianes o grados sexagesimales? Ej: Sin(1) = 0.0174... ó Sin (1) = 0.8414...
Gracias.

**Comment by flobarrios** [comment]
#296 (solo radianes).

**Comment by danyestay** [comment]
Muchas gracias :)
