### ISSUE TITLE
Funcion externa

### ISSUE THREAD

**Issue by tcgarrido** [IIC2233-2016-02/Syllabus#329]
Hola! quiero citar una función no hecha por mi en el README, como puedo hacerlo?

Saludos

**Comment by flobarrios** [comment]
Hola! 
Primero, no todas las funciones las puedes citar, hay métodos que deben implementar ustedes por su cuenta. En el caso de la función gamma, puedes utilizar [esta](https://rosettacode.org/wiki/Gamma_function#Python). Debes indicar en el README y en el código de donde tomaste el algoritmo (la fuente) y la fecha. Saludos!
