### ISSUE TITLE
[Tarea 1 ] Estadisticas programones

### ISSUE THREAD

**Issue by roy350** [IIC2233-2016-02/Syllabus#33]
Disculpen, pero probando me di cuenta que los hp de los programones suben mucho al hacer el calculo de stats por ejemplo la base de uno es 29 y llega hasta 600 algo, eso esta bien? y lo otro los programones salvajes tienen los stats modificados por que en el enunciado dice si los capturas cambian los stats osea antes de ser capturados tienen lo stats por defecto que tienen los json o ya vienen modificados? eso muchas gracias!

**Comment by mjjunemann** [comment]
La formula del HP esta mal, falto dividir por 100 como en la formula para cualquier otro stat , hace una gran diferencia, pero no debería afectar en nada a tu programa. 

![image](https://cloud.githubusercontent.com/assets/5751374/17652267/65265040-624e-11e6-808d-511bfad8b78f.png)

**Comment by flobarrios** [comment]
Respecto a la segunda parte de tu pregunta, debes pensar en una forma de modelar a los programones tal que te permita calcular su hp y otras stats siempre a partir de las estadisicas base dadas y el nivel en el que éste se encuentra.
Saludos!

**Comment by roy350** [comment]
Gracias por responder @flobarrios pero mi pregunta iba abocada a que si el programon me aparece salvaje instantaneamente debo calcular los stats con la formula que dieron o solo al momento de capturarlo, por que en el enunciado da a entender eso

**Comment by flobarrios** [comment]
Debes calcular los stats con la fórmula en todo momento. Saludos!

**Comment by roy350** [comment]
gracias!

**Comment by roy350** [comment]
Lamento seguir molestando con este tema, pero para el calculo de hp consideramos el dividido en 100 que dijo @mjjunemann , porque osino las batallas se hacen demasiado largas por los tan altos hp que tienen ambos programones, muchas gracias!

**Comment by jgmontoya** [comment]
@roy350 Se ha actualizado el enunciado con eso y se avisó en #35 

Vuelvo a cerrar.
