### ISSUE TITLE
Path archivos consulta y status

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#330]
Creo que ya lo preguntaron, pero no encontre la issue. Podemos asumir que los estados que se cargaran y el archivo de consultas estara en el mismo directorio que el main? Gracias!

**Comment by jtagle2** [comment]
Efectivamente, se dijo en una respuesta en #246 acerca del uso de tkinter.
Saludos!

**Comment by andresbannuraschultz** [comment]
Ahi estaba! jaja Graciaas.
