### ISSUE TITLE
Uso yield

### ISSUE THREAD

**Issue by Tibrahm** [IIC2233-2016-02/Syllabus#331]
hol !!, puedo ocuar dos while para un yield?
algo asi ?

``` python
n = 0
while n < algo:
    m = 0
    while m < algo 2:
       a = operacion
       yield a
       m += 1
    n+=1
```

Gracias !

**Comment by agmardones** [comment]
Hola @Tibrahm!

Sí, es un código válido para esta tarea (siempre y cuando esté dentro de una función generadora).

Saludos!
