### ISSUE TITLE
Definicion de funciones

### ISSUE THREAD

**Issue by roy350** [IIC2233-2016-02/Syllabus#332]
Disculpen, pero me queda una duda en el manejo de errores, en el enunciado dice que las funciones se definen del tipo "f[x_] = 3;" ,  pero en  caso de que se ponga algo como "f(x) = 3" el programa debería tirar una excepción o asumo que esto no pasara? tambien tengo dudas en el ";" si no esta hay excepcion o asumo que no deberia pasar? Muchas gracias!

**Comment by stephichau** [comment]
Hola @roy350!
Puedes asumir que las funciones se definirán sin errores y que cada instrucción terminará con ";" 

Saludos!
