### ISSUE TITLE
[Tarea 3] Duda con los signos

### ISSUE THREAD

**Issue by roy350** [IIC2233-2016-02/Syllabus#333]
Disculpen pero tengo una duda referida a los signos entre cada variable o funcion, puedo asumir que habra un espacio entre cada signo por ejemplo: "x + 3" o puede escribirse como "x+3"?

**Comment by stephichau** [comment]
Hola @roy350!
Se pueden escribir de ambas formas.

Saludos!

**Comment by roy350** [comment]
Gracias! y aprovechando a que la tematica se parece, lo mismo pasa con la definicion de funcion? es decir, se puede escribir tanto "f[x_]=x+1", como "f[x_] = x+1" o debe haber un espacio a la izquierda y derecha del signo igual?

**Comment by stephichau** [comment]
@roy350 se puede escribir como f[x_]=      x+1 o como f[x_]=x      +        1. Lo importante es que se encuentre en el formato correcto :).
