### ISSUE TITLE
Simplificar

### ISSUE THREAD

**Issue by sormazabal** [IIC2233-2016-02/Syllabus#334]
Hola!
Podrían dar más ejemplos de inputs y outputs de %S y FullSimplify? No entiendo bien qué hacen.

**Comment by stephichau** [comment]
Hola @sormazabal !
Ambos comandos sirven para simplificar un resultado. La diferencia de éstos es que %S simplifica el último resultado obtenido y FullSimplify simplifica lo que aparece entre sus argumentos. Si quieres saber más sobre estos comandos, puedes tomar como referencia el FullSimplify implementado en [Mathematica](https://reference.wolfram.com/language/ref/FullSimplify.html) o Simplify de [Maple](https://www.maplesoft.com/support/help/Maple/view.aspx?path=simplify).

Por ejemplo: 

**Input**
F = (3^2)+1;
%S;

FullSimplify[Cos[x] \* Tan[x]]; 

**Output**
10
Sin[x]

Espero que se haya entendido, 
Saludos!

**Comment by sormazabal** [comment]
Otra pregunta:
En el enunciado dice que el %S se usa para simplificar el **último resultado**. Pero en el ejemplo que escribiste F es un resultado o una variable que acabas de definir?
Gracias por la respuesta anterior!

**Comment by stephichau** [comment]
@sormazabal es un resultado guardado en una variable :)
