### ISSUE TITLE
Duda menu

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2233-2016-02/Syllabus#335]
hola, el menu es libre de como hacerlo ?
Por ejemplo mi menu puede ser asi:
lista_func = [ func1, func2, func3...]   una lista con funciones
¿Que quiere hacer?
[1] Integrar
[2] Derivar 
[3] etc
y luego dependiendo la opcion elegida preguntar por las funciones para que haga lo pedido. 
Gracias!

**Comment by agmardones** [comment]
Hola @NicolasAguirre,

Lo que se pide en el enunciado es que tu programa funcione como una **línea de comandos**. Es decir, el menú que buscas implementar no es válido, el usuario debe ser libre de ingresar cualquier tipo de comando sin necesariamente definir una función, quizás un comando que no exista, etc. (tal como funcionan algunos programas curiosamente parecidos)

Saludos!
