### ISSUE TITLE
for legal?

### ISSUE THREAD

**Issue by NoemiCC** [IIC2233-2016-02/Syllabus#336]
En mi programa para la tarea 3 necesito esta función y para hacerla uso el for de la imagen de abajo, puedo usarlo o me quitara puntaje?

`[Imagen censurada]`

Y si tengo que cambiarlo me podrían dar una recomendación para un remplazo, no he encontrado una forma de hacer lo miso con los "for legales". Gracias :)

**Comment by jgmontoya** [comment]
Hola, 

1.- Ese `for` es **_ilegal**_ en esta tarea. :skull: 
2.- Por favor evita subir código de la tarea acá, ya que puede ser considerado copia. Para consultas de este estilo a futuro puedes usar un ejemplo y explicar cuál es el problema en cuestión. Por lo mismo borraré la imagen.
3.- Te recomiendo ocupar un editor como SublimeText o Atom o bien una ide como PyCharm.
4.- Si haces `for r in res` y dentro de ese loop evalúas `r in res` eso siempre se evaluará a True.

Saludos!

**Comment by NoemiCC** [comment]
Gracias, pero no entiendo como ocupar un editor de texto distinto me ayudaría a hacer lo que necesito.
