### ISSUE TITLE
Guardar funciones

### ISSUE THREAD

**Issue by iqacevedo** [IIC2233-2016-02/Syllabus#337]
Hola !
Me gustaría saber cual es la mejor manera de guardar una función (en temas de orden y funcionalidad), si mi objetivo final es guardar muchas funciones en un diccionario.
`funciones={}`
1-.`suma=lambda x, y: x + y`
`funciones["suma"]=suma`
2-.`def suma(x, y):`
`return x + y`
   `funciones["suma"]=suma`
3-.`funciones["suma"]=lambda x, y: x+y`

Cual es mejor? o no hay muchas diferencias entre ellas?, ya que me gustaría poder hacer esto con funciones mas complicadas, pero que igualmente se pueden hacer con un lambda.

Saludos!

**Comment by jgmontoya** [comment]
Hola, 

Como caso general, si le vas a asignar un 'nombre' a una función entonces es mejor usar `def` que `lambda`. En general no hay grandes diferencias en términos de eficiencia, sin embargo funciones definidas con `def` suelen ser más legibles. Además que en una función definida mediante `def` puede contener cualquier cosa mientras que con `lambda` hay ciertas limitaciones.

En resumen, yo me iría por la opción 2.

Saludos!

**Comment by iqacevedo** [comment]
muchas gracias :smile:
