### ISSUE TITLE
uso de for

### ISSUE THREAD

**Issue by smargozzini** [IIC2233-2016-02/Syllabus#338]
hola!
es legal usar un for dentro de una lista por comprensión pero no con el fin de obtener la lista sino que se aplique una función que va a hacer otra cosa y retornar un None

ej:
def función(termino):
      #acá se hace algo con el termino, se agrega a algún diccionario de una clase 

lista = [.....]
agregar = [función( j ) for i in lista for j in i]

esto lo podría hacer con map pero son listas dentro de listas entonces no lo pude usar

**Comment by DiegoAndai** [comment]
Si tienes listas anidadas puedes ocupar maps consecutivos para aplicar funciones a los elementos internos, por ejemplo:

`lista_anidada = [[1,2],[4,3]]`
`lista_cuadrados = list(map(lambda li: list(map(lambda x: x^2, li)), lista_anidada))`

lista_cuadrados quedaría:

`[[1,4],[16,9]]`

Si te pones creativo se pueden adaptar varios comportamientos más complejos con map, reduce, filter, etc... Solo hay que darle un par de vueltas al problema. Podrías incluso implementar una función generadora que te desempaque la lista anidada y tire los valores de a uno, y mapear esa función. Si quieres usar map, las posibilidades son infinitas, al igual que con cualquier tipo de procedimiento.

**Comment by andresbannuraschultz** [comment]
@DiegoAndai Entiendo que hay otras formas de hacerlo, pero de todos modos, meter la funcion en una lista es legal o no?? Y iterarar usando un for dentro de esa lista por compresion..

**Comment by DiegoAndai** [comment]
@abannura Comenté porque @smargozzini dijo que no se podía usar map y no le respondían, era por si estaba pegado con eso y que pudiera ocupar map que sí o si es válido 🙊 No sé si es legal lo propones,  #InvocaUnAyudante.

**Comment by andresbannuraschultz** [comment]
@DiegoAndai  jajaj dale dale, jure que eras ayudante, sorry

**Comment by andresbannuraschultz** [comment]
Algun ayudante? No veo porque no estaria prermitido.. Gracias!

**Comment by jgmontoya** [comment]
Hola,

Ese `for` está permitido.

Saludos!

**Comment by smargozzini** [comment]
gracias!

**Comment by andresbannuraschultz** [comment]
Gracias!
