### ISSUE TITLE
Derivadas e Integrales

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#339]
Se debe poder realizar integrales por partes y fracciones parciales?.
Con respecto a las derivadas, regla de la cadena, multiplicación y división de funciones se deben aplicar todas? o también compuestas, es decir se debe realizar la derivada de una derivada de división que pueda contener una regla de la cadena o cosas por el estilo?. O solo se trabajara con polinomios y trigonométricas?

**Comment by aaossa** [comment]
Hola @narierao . Lo que preguntas ya fue respondido en #288 y #260 . Si tienes dudas en particular sobre alguno de esos temas sigue la discusión en la misma issue (si se encontrara cerrada la reabriremos en cuanto aparezca una nueva duda).

Saludos, :wave:

**Comment by narierao** [comment]
Hola @aaossa  Necesito solo un si para saber si entendí, no habrá derivadas compuestas (a lo más una que sera por cadena) y tampoco integrales más alla de las "clasicas" es decir, se excluye "vaca" y fracciones parciales y también por sustitución.
Muchas gracias.
