### ISSUE TITLE
Diagrama de clases [Tarea 1]

### ISSUE THREAD

**Issue by jmcomber** [IIC2233-2016-02/Syllabus#34]
Para el diagrama de clases que piden, ¿se puede/recomienda hacer a mano y escanearlo? ¿O hay que hacerlo con alguna librería? Estuve mirando y hay varias opciones, pero supongo que de poderse lo pregunto en específico en la Issue correspondiente, para que quede todo en la misma parte.

**Comment by Hernan4444** [comment]
@jmcomber el semestre pasado yo hice el diagrama de clases en word y luego lo pase a un pdf para la entrega pero también hay programas o paginas online que hacen el diagrama de forma automática (pero tendrías que buscarlo en google).
Lo importante al final es que lo entregues en un formato que pueda ser leído (como pdf) y que se entienda el contenido, si es un dibujo escaneado tal vez no se entienda todo y te arriesgues a no tener todo el puntaje.

**Comment by aaossa** [comment]
El semestre pasado preguntaron algo parecido. Como alternativa a lo que dice Hernán, podrías usar NClass, como recomiendan en [esta issue del semestre pasado](https://github.com/IIC2233-2016-1/syllabus/issues/116)

**Comment by fgvenegas** [comment]
La dejare abierta porque es una pregunta mas o menos frecuente :)
