### ISSUE TITLE
ClearV y ClearF

### ISSUE THREAD

**Issue by jatrijori** [IIC2233-2016-02/Syllabus#340]
Hola, me surgió una duda con respecto a lo que ocurre cuando se borra una función definida pero existe otra función o variable que la usaba en su definición. Por ejemplo se tiene:
f[x_] = x^2 +3;
g[x_] = Sin[x]; 
h[x_] = g[f[x]];
Si hago ClearF f[x]; ¿la función h[x] debe seguir existiendo o también se borra?
Misma pregunta si se tiene f[x_] = x^2 +a; a = 3; ClearV a;

Gracias de antemano.

**Comment by stephichau** [comment]
Hola @jatrijori , 
Queda a tu criterio :). No olvides especificarlo en tu README. 

Saludos!
