### ISSUE TITLE
Definir soluciones de ecuaciones

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#341]
Para resolver las ecuaciones o encontrar sus soluciones, pueden ser ecuaciones de cualquier grado? o solamente trabajaremos con grado 2 y 1?

**Comment by fgvenegas** [comment]
Hola
Esto ya fue respondido en otra issue, puedes revisarlas haciendo click en el label "Tarea 3"
Para futuro te recomiendo revisar antes de abrir una issue, tal vez ya existe y está respondida, así te ahorras esperar que te respondan.
