### ISSUE TITLE
Rango y Dimensión

### ISSUE THREAD

**Issue by JaimeGo** [IIC2233-2016-02/Syllabus#342]
Hola! Podrían darnos alguna idea sobre cómo calcular el rango y la dimensión de una matriz? No me refiero a la parte de programación, sino a los teoremas que conviene ocupar desde el punto de vista matemático. Pregunto porque he encontrado información y tengo varias ideas de cómo se puede lograr, pero todas son bastante largas y quería saber si hay alguna forma más razonable de conseguir el resultado. Gracias

**Comment by DiegoAndai** [comment]
Sobre la dimensión: (#315) no se refiere al concepto relacionado a las bases de un espacio, si no simplemente las dimensiones nxm

**Comment by stephichau** [comment]
Hola @JaimeGo !

Para calcular el rango de una matriz puedes pivotear, sacarlo por determinantes, entre otros :).

Saludos!
