### ISSUE TITLE
PEP 8

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2233-2016-02/Syllabus#344]
Hola serán muy pesados con el pep8 (de pasarse los 120 caracteres). Me he pasado en demasiadas ocasiones por usar [[for ...] for ... for ... ].
Alguna forma de como arreglarlo? Gracias

**Comment by aaossa** [comment]
Hola, el máximo de caracteres por línea (en PEP8) es 79, no 120. La idea es que no te pases de esa marca porque si te pasas puede ser que tu código no esté bien anidado o haces demasiadas cosas en una sola línea. Como queremos que el código se entienda es mejor hacer las cosas en múltiples líneas, paso a paso, que todo en una sola linea.

Pero... PEP8 es un conjunto de recomendaciones. Si no encuentras una mejor forma de escribirlo, puedes pasar el límite (79). Ahora, como dijiste que te has pasado muchas veces de 120 y el máximo es 79 te recomiendo buscar una forma de escribirlo que sea más clara.
