### ISSUE TITLE
consultas 

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233-2016-02/Syllabus#347]
No me queda claro como es el tema de las consultas. Necesito que me digan si todas estas variaciones de consultas son validas y necesarias en la tarea, porque siento que no queda muy claro en el enunciado.
Desde consola escribir lo siguiente: (Ejemplos)
Suponiendo que f[x_] y a están definidos.
2^2
a^2
f[x_]^2
f[3_]
derivate[f[3_]]
derivate[f[g[x_]]]

son consultas validas?
puede haber composición de funciones cuando se definen y cuando se consultan?
Sería de gran ayuda tener esto claro. Gracias.

**Comment by stephichau** [comment]
Hola @jorgeriesco !
Sí, todas son válidas :)

Saludos!

pd. Ojo con la sintaxis
