### ISSUE TITLE
materia funcional

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233-2016-02/Syllabus#348]
Existe una forma de imprimir los elementos de una lista saltando un espacio sin usar un for? osea, por compresión o de alguna forma legal para la tarea.

**Comment by jorgeriesco** [comment]
Voy a contestarme a mi mismo: (ejemplo)
d = [2,2,3,4,5]

def f(x):
    print(x)

g = [f(x) for x in d]
#g no sirve para nada

**Comment by jorgeriesco** [comment]
voy a contestarme a mi mismo:
g = [print(x) for x in lista]

-g no sirve para nada
-como generador no se puede, solo como lista

**Comment by Afalegria** [comment]
gracias por la auto respuesta :D

**Comment by jgmontoya** [comment]
Hola!

Si bien hacerlo con una comprensión de listas cumple el objetivo es una mala solución puesto que creas una lista de None que no sirve para nada y que es del tamaño del iterable que quieres imprimir .

Te dejo una solucion más _funcional_:

``` python
def print_iterable(iterable, j=0):
    if j == len(iterable):
        return
    print(iterable[j])
    print_iterable(iterable, j+1)

print_iterable(d)
```

Pero sin dudas la mejor opción es usar la magia de python:

``` python
print(*d, sep='\n')
```

Saludos!
