### ISSUE TITLE
Integrales

### ISSUE THREAD

**Issue by lefischer** [IIC2233-2016-02/Syllabus#349]
Hola

pueden subir una tabla con las integrales inmediatas que se deven calcular, especificamente de las trigonometricas.

**Comment by lefischer** [comment]
segun lo que entende se integran sin, cos, y polinomiales. dentro de las polinomiales debo incluir polinomios con fracciones

**Comment by stephichau** [comment]
Hola @lefischer !
Revisa la issue [#260](https://github.com/IIC2233-2016-02/Syllabus/issues/260) :).

Saludos!
