### ISSUE TITLE
Polinomios y el comando Solve

### ISSUE THREAD

**Issue by gebalassa** [IIC2233-2016-02/Syllabus#351]
**¡Hola!**

Considerando que el comando `Solve` debe resolver las raíces de un polinomio de grado cualquiera, ignoro si se espera que usemos las fórmulas conocidas hasta el grado 5, o si debemos usar algún método de aproximación, o si al final hay un límite, o si Solve no hace lo que menciono, etc. Desconozco una forma relativamente simple de hacer esto para polinomios de grados superiores, por lo que cualquier ayuda se agradece.

_Gracias de antemano,
Gabriel.-_

**Comment by agmardones** [comment]
Hola @gebalassa,

No sé si viste #279, pero restringimos este comando. En caso de que ya lo hayas revisado, [este teorema](https://es.wikipedia.org/wiki/Teorema_de_la_ra%C3%ADz_racional) entrega un algoritmo para encontrar todas las soluciones de este tipo. 

Ojala te haya respondido, Saludos!

**Comment by gebalassa** [comment]
¡Saludos! Gracias por responder. Sí había visto el post, pero no me decía nada. 

Gracias por el teorema; recomiendo editar el post #279 y agregar ese link, pues no creo que muchos lo conozcan; personalmente no lo había escuchado nunca.
