### ISSUE TITLE
Duda sobre simulacion

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#352]
Hola! Estaba leyendo los apuntes sobre simulacion y la ayudantia y sale que recomiendan usar properties para modelar algunos atributos. La verdad no entiendo porque hay una ventaja sobre usar un metodo o un atributo normal. Muchas gracias!

**Comment by jtagle2** [comment]
@abannura, si bien las 3 opciones puedes llegar a la misma solución (que tu simulación funcione), el consejo es por su bien.

# **¿Por qué no un atributo?**

Para verlo en una situación concreta. veamos el caso del taller de autos en el material de clase. Posee una property ocupado, que retorna un valor Booleano que depende de otro atributo de la clase (Tenemos un estado A, que depende del atributo B). Entonces, hay 3 formas de implementarlo,
- **Usamos un método, de forma tal que después hagamos taller.ocupado():** Por ahora no hay problema, en el siguiente ejemplo se muestra porqué no es una buena idea.
- **Usamos un nuevo atributo:** Es una mala idea, pues para qué tener un atributo nuevo en la clase, si sabemos que este depende de otro (redundante). Ahora, si lo hacemos así aún sabiendo que es mala idea, significaría que al modificar el estado B, tengo que cambiar el estado A, y me tengo que preocupar de que siempre que haga un cambio en uno de los atributos, el estado del objeto siga siendo coherente (es decir, que si B cambia entonces A también, o que no puede cambiar A si es que B no ha cambiado). Si eso no te convence, ahora imaginémonos que nuestro estado A, depende no solo de B, sino también de otros atributos C, D, E, F. Eso siginifica que cada vez que actualizo uno de esos valores, tendría que ver que ocurre con A y actualizarlo según eso. Para ahorrarnos eso, hacemos la tercera opción
- **Usar property:** La clase tiene sus características y estados, y según eso tiene la capacidad de ver que sucede con el "atributo" A. Luego, si cambio los atributos B, C, D..., no tengo que preocuparme de A, pues al momento de ser necesario, este será calculado.

# **Ahora, ¿Por qué no un método?**

Veamos otro ejemplo concreto, supongamos que en tu simulación, tienes varios elementos, los cuales todos influyen en el próximo evento a ocurrir (el próximo evento de la simulación, será el mínimo de todos los eventos que ocurrirán en el futuro). Ahora, hay 2 tipos de elementos: un elemento A1, que solo hará una intervención en tu simulación (es decir, solo tendrá 1 próximo evento, y después desaparece). Luego, A1 es lógico que tenga un atributo proximo_evento. Por otro lado, tienes A2 que el próximo evento a ocurrir, dependerá de varios otras variables dentro de la misma clase, es decir, en esta clase tendremos que hacer o una property o un método que le avise a la simulación, cuándo será el próximo evento.
Hasta el momento, no sale ningún problema, pero ahora veamos que pasa en ambos casos, cuando la simulación intenta obtener el próximo evento que ocurrirá.
- **Clase A2 implementó un método:**  Para saber cual es el próximo tiempo de la simulación, debo revisar todos los elementos que están interviniendo en mi simulación. Luego, para A1 reviso A1.proximo evento, y para A2 reviso A2.proximo_evento(). Se ve el problema? Al momento de ver cual es mi proximo evento, como uno lo tiene en un atributo y otro en un método, debería verificar en cada elemento, la instancia para saber si recibo su próximo evento mediante `clase.proximo_evento()` o `clase.proximo_evento`
- **Clase A2 implementó property**: Para saber cual es el tiempo de la simulación, simplemente recorro todos mis elementos y retorno el mínimo de `elemento.proximo_evento`, en otras palabras, aprovechemos el duck typing.

Es verdad que cualquiera de los caminos que se implementen, puede funcionar sin ningún problema. El problema es que sin el uso de las properties, a medida que se va complejizando la simulación, el programarlo se irá haciendo más tedioso y complejo. (Qué es más fácil, recorrer todos los elementos y chequear `elemento.proximo_evento`, o recorrer todos los elementos, chequear `isinstance(elemento, Clase)` y según eso chequear un método o atributo). Espero se entienda la idea, y obviamente esto eran 2 ejemplos puntuales, pero que ayudan a responder por qué es mejor una opción por sobre la otra.
Durante la ayudantía se discutió con más profundidad, siempre es recomendable asistir (y ojalá con el material de clases previamente leído).
Saludos!

**Comment by andresbannuraschultz** [comment]
Primero que todo, disculpa si en la ayudantia ya lo habian discutido, no pude ir esta vez. Segundo, muchisimas gracias por tu explicacion! Muy completa y clara. Nunca se me hubiesen ocurrido a mi estos detalles, pero los entendi perfect y me hicieron mucho sentido. Gracias!
