### ISSUE TITLE
archivo consultas

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233-2016-02/Syllabus#354]
No entiendo bien como funciona el archivo consultas. ¿Por que sale en el enunciado que es necesario importarlo apenas se habrá el programa?
¿Se deben generar los resultados de las consultas de todos los estados o el usuario elige?

**Comment by rolfskog** [comment]
Sumandome a preguntas sobre las consultas, cada vez que se carga un estado nuevo se debe reiniciar el estado de las variables y funciones, o se sigue sumando al estado actual. 
Una vez terminado las consultas el usuario puede seguir usando el interfaz o se debe terminar el programa?

**Comment by agmardones** [comment]
Hola!
@jorgeriesco Cito del enunciado:

> Este archivo se cargará al comenzar cada ejecución del programa y tendrá por nombre consultas.txt

Por lo tanto, siempre que se ejecute tu programa se deberían leer las consultas.txt, y luego permitir al usuario seguir consultando como modo línea de comandos.
@rolfskog Cito del enunciado:

> Un usuario podrı́a cargar un primer estado en cierto punto de la ejecución, y posteriormente cargar un
> segundo estado. En este caso, las variables que tenı́an en común dichos estados se sobreescriben por las del estado más reciente, manteniéndose las variables del primer estado que no están contenidas en el segundo.

Por lo que sí, lo correcto es la segunda opción: se siguen sumando al estado actual.

En todo caso, si a estas alturas ya lo tienen implementado de otra forma, pueden especificar en el README cómo lo hicieron y cómo probar su programa, siempre y cuando cumplan con leer las consultas y permitir el uso como línea de comandos.

Saludos!
