### ISSUE TITLE
Errores archivo consulta

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#355]
Quizas no estoy en lo correcto, pero segun yo hay errores en el archivo de consultas (mas bien en los resultados a estas consultas), como por ejemplo que el producto de matrices si esta definido para ambos lados (no deberia tirar error) o que se llama a funciones no existentes. Ademas muchas consultas ya no cuentan como consultas validas, ya que involucran: integracion de funciones compuestas o resultados imaginarios. Existe la posibilidad de que suban mas ejemplos para probar nuestros programas? Muchas gracias!

**Comment by fvandeputte** [comment]
Me sumo a la pregunta, en la traspuesta de la matriz M tambien existe un error? Considerando que 
M = [[1,2,3],[4,5,6]]; frente a la consulta Trans[M] el resultado dice [[1,4,7],[2,5,8],[3,6,9]]

**Comment by JaimeGo** [comment]
También creo que hay errores y que en general, hay pequeñas confusiones y falta de información en algunos items para poder inferir lo que quieren que haga. Se agradecerían mucho que subieran algunos ejemplos actualizados.

**Comment by cjgazali** [comment]
Una de varias cosas que por los comentarios ya hechos no debería ser válida es el llamado f[t[x]] ya que involucra una composición. Ahora, este llamado sería válido si se escribiera de la forma 'equivalente' `(Cos[x])^2+3`. El gran detalle son los paréntesis, que ya dijeron que deberíamos asumir para potencias de funciones. Si no aclaran todo lo extraño hasta el momento sin contradecir lo que ya han dicho, voy a dar explicaciones en mi readme y hacer supuestos, porque no hay tiempo para esperar tanto a que contesten issues tan importantes como éste. Espero que no exijan más de lo que han explicado, sobre todo en el tema de integrar, derivar y resolver.

**Comment by agmardones** [comment]
Hola,

Acabamos de subir algunos archivos nuevos con consultas válidas, en general referidas a la mayoría de las issues. Ojalá les sirva y aclare más las cosas. 

Saludos a todos!

**Comment by andresbannuraschultz** [comment]
Agradezco que hayan subido nuevos ejemplo, pero creo que estos tambien contienen errores segun lo que hemos ido dejando claro en este foro. Por ejemplo:
- en las consultas del estado 1 se pide integrar Sin[x]*x (habiamos acordado que eso no entraba o no?)
- las soluciones son 1, 2.5 (no 5/3) y 5 
- en el estado 1 para definir a la funcion d solo se entrega la variable x, siendo que al derivar g, la funcion resultante queda con la variable y. Ahora esta como d[x_] = Derivate[g[x,y], x]; , pero debiese ser
  d[y_] = Derivate[g[x,y], x]; o no? O en el fondo el programa tiene que poder darse cuenta que la variable que queda es la que define la funcion? Si es asi entonces no tengo como diferenciar cuando quiero que me la reconozca como variable independiente, de cuando es un parametro no definido.
- la matriz m1xm3 es en verdad m1xm2 y su primer termino es 26 no 29.

Quizas estoy siendo demasiado negativo al recalcar los errores en vez de la buena disposicion que todos los ayudantes han tenido durante el ramo. Yo entiendo que esto lo hacen con la mejor disposicion de todas (de hecho, en teoria no tendrian por que hacerlo y solo lo hacen para beneficio nuestro). Es solo que despues de 2 semanas de trabajo, y al probar el programa el mismo dia de la entrega, y que este no corra bien (uno pensando que esta todo malo) y al final es por los inputs... resulta frustrante.

**Comment by stephichau** [comment]
Hola @abannura ! 

Hubo un problema al corregir los errores, pero ya se arreglaron :).

**Comment by andresbannuraschultz** [comment]
Gracias @stephichau! Quizas mi comentario sono muy pesado, pero no era mi intencion.
