### ISSUE TITLE
Inversa

### ISSUE THREAD

**Issue by lefischer** [IIC2233-2016-02/Syllabus#358]
Hola

cuando calculo la multiplicacion entre una matriz y su matriz inversa no obtengo la identidad por las aproximaciones que python hace al divir. Como puedo soucionarlo?

**Comment by stephichau** [comment]
Hola @lefischer !

Puedes especificar en el README que algunos cálculos difieren un poco del valor esperado dada las aproximaciones que tomaste en tu programa. 

Saludos!
