### ISSUE TITLE
Informacion que debe desplegar progradex

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#36]
Tengo una duda sobre la informacion que mostrar respecto a los programones atrapados. Esta debe ser solo la informacion acerca de la "clase" del programon correspondiente o sobre el programon en particular que atrape. En otras palabras, debo incluir por ejemplo, unique_id, IV, EV, level, etc. (las cuales son caracteristicas unicas), o solo mostrar las caracteristicas genericas (como lo hace un pokedex). Gracias.

**Comment by andresbannuraschultz** [comment]
Por ejemplo, si capturo un segundo programon del mismo tipo, creo una nueva entrada en mi progradex o no?

**Comment by jgmontoya** [comment]
Hola!

La información que debe mostrar la progradex para cada programon es principalmente la que se encuentra en el archivo _programones.json_
Tanto si fue visto como si fue capturado deberá mostrarse la siguiente información:
- Id
- Nombre
- Tipo
- Dónde ha sido visto/capturado (por ejemplo: ruta 1, ruta 3, Pewter City, etc..)

Si fue capturado debe mostrarse además la siguiente información:
- Stats (hp, special_defense, special_attack, defense, speed, attack)
- Nivel al cual evoluciona
- Id del programon al cual evoluciona
  - Si la evolución se encuentra en la progradex (ya sea como visto o como capturado) se debe agregar además el nombre de la evolución
- Movimientos

Es decir, si capturas un segundo programon del mismo tipo **no** deberás crear una nueva entrada en tu progradex, pero posiblemente deberás modificar la entrada existente (si es que fue capturado en un lugar distinto al anterior).

Saludos!

**Comment by andresbannuraschultz** [comment]
Vale gracias!

**Comment by dfvasquez** [comment]
Hola! Me surgió una duda viendo el archivo de ejemplo: "jugadoresEjemplo.json"... 
¿cuál es la diferencia entre "id" y "unique_id"?

Gracias :)

**Comment by sormazabal** [comment]
Otra pregunta sobre el Progradex:
En el progradex se puede buscar por un Programón (ya sea por index o nombre de este)? O sólo debo desplegar la información de todos los Programones en el orden que se estipula en el enunciado?

**Comment by flobarrios** [comment]
@sormazabal no es necesario, solo en el orden que se especifica en el enunciado 😄

**Comment by fhgajardo** [comment]
Una preguta:
La informacion de stat a desplegar debe ser la base o la ya calculada?
Si fuese la calculada, que pasa en el caso que capturo dos programones iguales con diferentes iv o ev?

**Comment by jgmontoya** [comment]
Son los base stats.

**Comment by DiegoAndai** [comment]
Para los movimientos, ¿hay que poner solo el nombre o más información? gracias

**Comment by jgmontoya** [comment]
@DiegoAndai Hay que poner  el nombre y los pp máximo

**Comment by martinvidal** [comment]
@jgmontoya puedo desplegar en el progradex la información estipulada para los vistos o capturados y mostrar si están capturados y la información que aquí se especifica para los capturados entregarla en el pc y menu de equipo (como en el juego original), donde yo encuentro que se vería mejor porque podría poner los stats del programon en especifico. En resumen entregar la informacion que se pide igual pero de una forma en la que yo encuentro que es mas optima y por supuesto informar de esto en el readme? :O
