### ISSUE TITLE
[Tarea 3] Funciones en algoritmo "Shunting-yard algorithm"

### ISSUE THREAD

**Issue by Kitaps** [IIC2233-2016-02/Syllabus#360]
Hola hola, 

lo que pasa es que para la tarea quisiera usar el SYA pero hay una parte que no logro entender. 
Quería saber si alguien me podría ayudar a entenderlo. 

Lo que no entiendo es la explicación de lo que va debajo de:
**If the token is a function argument separator (e.g., a comma):**

fuente:   https://en.wikipedia.org/wiki/Shunting-yard_algorithm
Gracias

**Comment by sfga** [comment]
Hola,

"If the token is a function argument separator (e.g., a comma):
Until the token at the top of the stack is a left parenthesis, pop operators off the stack onto the output queue. If no left parentheses are encountered, either the separator was misplaced or parentheses were mismatched."

Lo que entiendo de esta explicación es:
Mover (sacar) operadores (secuencialmente) del stack y agregarlos al output hasta que el operador del stack a sacar sea '(' (left parenthesis).

Saludos.

**Comment by Kitaps** [comment]
sii, maoma eso había caxado pero no resulta

**Comment by jgmontoya** [comment]
Hola!

> If the token is a function argument separator (e.g., a comma):
> Until the token at the top of the stack is a left parenthesis, pop operators off the stack onto the output queue. If no left parentheses are encountered, either the separator was misplaced or parentheses were mismatched.

Lo que te dice es que si el token es un separador de argumentos en de una función (o sea una ','), hagas pop de los elementos del stack y los pongas en la cola de output hasta encontrar un paréntesis izquierdo ("(").
Luego te dice que si en este proceso no se encontró un paréntesis izquierdo eso significa que el separador estaba mal ubicado o que los paréntesis no estaban correctamente balanceados.

Por ejemplo:
expresión: `max(2, sin(2+3))`
`T: Token`, `S: Stack`, `O: Output queue`
1. `T: max`; `S: [max]`; `O: [ ]`
2. `T: (`; `S: [(, max]`; `O: [ ]`
3. `T: 2`; `S: [(, max]`; `O:[2]`
4. `T: ,`; `S:  [(, max]`; `O:[2]`
5. `T: sin`; `S: [sin, (, max]`; `O:[2]`
6. `T: (`; `S: [(, sin, (, max]`; `O:[2]`
7. `T: 2`; `S: [(, sin, (, max]`; `O:[2, 2]`
8. `T: +`; `S: [+, (, sin, (, max]`; `O:[2, 2]`
9. `T: 3`; `S: [+, (, sin, (, max]`; `O:[2, 2, 3]`
10. `T: )`; `S: [sin, (, max]`; `O:[2, 2, 3, +]`
11. `T: )`; `S: [max]`; `O:[2, 2, 3, +, sin]`
12. `T: ' '`; `S: [ ]`; `O:[2, 2, 3, +, sin, max]`

Saludos!

**Comment by Kitaps** [comment]
gracias :+1:
