### ISSUE TITLE
[Tarea 3] Abrir archivos

### ISSUE THREAD

**Issue by pcsalvo** [IIC2233-2016-02/Syllabus#362]
Hola! Tengo una duda con respecto a abrir/guardar archivos. En el archivo de texto 'consultas.txt' en 'status 3' aparece:
MatrixMultiply[M,N];
MatrixMultiply[N,M];
Pero las matrices M y N no estan definidas en ese archivo, pero si en el archivo de texto 'status3.txt'
Entonces mi duda es si por esto debemos guardar las funciones en un modulo y las variables en otro? O es un error del archivo subido?

**Comment by FernandoPieressa** [comment]
Hola! Como puedes ver con los ejemplos dados, primero tienes que leer el archivo de consulta que saldra en la primera linea (El cual guarda las variables tal como preguntastes de el ultimo estado), junto con la cantidad de lineas posteriores que seran los comandos a ejecturar, ej al leer la linea "status3.txt, 6", significa que tienes que leer el archivo status3.txt (que es efectivamente, un archivo aparte) para conseguir las variables y las siguientes 6 lineas seran los comandos a ejecutar. Recordar que la siguiente lectura de "satuts4.txt, 7" No borra las otras variables, sino que las sobreescribe o las deja igual. 

Saludos!

**Comment by pcsalvo** [comment]
Ya, entonces al pasar de un status a otro, las funciones y las variables 'siguen existiendo' a menos que en el archivo aparezca alguno de los 'Clear'? o lo entendi mal?

**Comment by stephichau** [comment]
@PaulaSalvo sí, entendiste bien :)

**Comment by pcsalvo** [comment]
Muchas gracias :)
