### ISSUE TITLE
plot

### ISSUE THREAD

**Issue by lefischer** [IIC2233-2016-02/Syllabus#364]
Cuando quiero hacer el region plot obtengo

[Imagen Censurada]

Duda:
los 3d plot son para funciones de la forma z[x,y] de dos variables?

EDIT: stephichau

**Comment by stephichau** [comment]
Hola @lefischer !
¿Con que funciones te tira ese error?

Te recomiendo no subir código dado que puede ser considerado copia :). Con respecto a tu duda sobre Plot3D, puede ser para funciones de una o dos variables.  

Saludos!

**Comment by lefischer** [comment]
El error es con cualquier funcion, en google encontre que lo solucionan usando array
