### ISSUE TITLE
[Tarea 3] Funcion Cotangente

### ISSUE THREAD

**Issue by roy350** [IIC2233-2016-02/Syllabus#365]
Disculpa pero en el apartado matematico se pide calcular la cotangente, y me di cuenta que en la parte de las Funciones Trigonometricas definidas esta no aparece entonces quiero preguntar como se escribe esta? es Ctg[x] o CoTan[x] o solo no la ponemos dentro de las funciones pero si en el apartado matematico, muchas gracias!!!

**Comment by stephichau** [comment]
Hola @roy350 !
Revisa la issue [#319](https://github.com/IIC2233-2016-02/Syllabus/issues/319)

Saludos!
