### ISSUE TITLE
Resultados.txt

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-02/Syllabus#366]
Hola !
Tenía una duda acerca del output del programa.
Si el usuario escribe Who; , hasta ahora había hecho que se imprimieran las variables en pantalla y en el output final queda guardado un "Se imprimieron las variables". Hice esto para que el output no tuviese tanto ruido. Lo dejo así, o agrego todas las variables al resultado ?
Salu2 y gracias de antemano

**Comment by agmardones** [comment]
Hola @Diiru,

Sí, puedes hacerlo, pero recuerda especificarlo en el README. Además, si es que se pregunta por Who; en el modo línea de comandos, debiesen mostrarse en pantalla.

Saludos!

**Comment by cglevican** [comment]
¿Qué ocurre si output de una consulta es una función (Ej: 'Derivate[Cos[x], x]')? Al ser programacion funcional, creo que se esperaría que trabajaramos directamente con las funciones, eso es lo que hice entonces no puedo imprimir '-Sin[x]' porque no estoy retornando un string, sino que el objeto funcion -1\* Sin.
