### ISSUE TITLE
Guardar archivo

### ISSUE THREAD

**Issue by npcariman** [IIC2233-2016-02/Syllabus#367]
No se si ya lo han preguntado, pero que guarda el comando save nombrearchivo;
todas las ejecuciones válidas del programa hasta el momento? Sólo las variables? alguna otra cosa?

**Comment by agmardones** [comment]
Hola!

Te dejo un output que te podría servir:
`save?`
`Este comando guarda el estado actual del gran intérprete Maplemathica, es decir: variables y funciones definidas hasta el momento`

Fíjate en los archivos que subimos (statusx.txt) y sigue ese formato, te darás cuenta que en todos sólo hay definiciones de funciones/variables.

Saludos!`
