### ISSUE TITLE
Nunca he jugado Pokemon

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#37]
Me ha llamado la atención leer en los issues frases como:
"La idea es que lo hagamos [de esta manera] o [de esta otra], como en el juego real?"
La tarea está llena de detalles, y estos comentarios me hacen dudar si acaso se están dando otros detalles por sabido. **Me gustaría pedirle a todos que nunca hablen de "el juego" sin especificar a qué se refieren**, y a los ayudantes que consideren si acaso están contando con que jugamos Pokemon alguna vez. Favor de confirmar que puedo trabajar tranquilo conociendo **exclusivamente** lo que ustedes dicen en el enunciado. Gracias!

**Comment by fgvenegas** [comment]
Al parecer los alumnos dedujeron que el juego se parecía a Pokemon aunque esto nunca es mencionado en el enunciado, por lo tanto es claro que no debes haber jugado el juego, además el enunciado tiene todo detallado y necesario para que puedas realizar la tarea sin ningún otro conocimiento previo más que programar, cualquier otra duda que se te presente o que no te quede clara puedes hacerla acá mismo :)

**Comment by fvr1** [comment]
@cgazali, como dice @fgvenegas la tarea no tiene nada que ver con Pokemon, pero aún así te dejo el link de un [emulador de GBA](http://www.pokeyplay.com/descargar_archivo.php?archivo=emuladores_gba/VisualBoyAdvance1.8.1_beta3_.zip) y el del [ROM del Fire Red](http://www.pokeyplay.com/descargar_archivo.php?archivo=roms_gba/Pokemon_FireRed_English.zip) para que no te pierdas la oportunidad de ver cómo es este gran juego (mejor tarde que nunca) y tal vez te inspire a entender mejor la tarea. Primero tienes que ejecutar el emulador y después desde éste tienes que abrir el rom, como si fuera un archivo. 
Espero que te ayude y ante cualquier pregunta sobre enunciado o materia no dudes en abrir una issue!

**Comment by ricardor4** [comment]
@fvr1 usted es diabólica...ya no sé si jugar el juego o hacer la tarea

**Comment by fgvenegas** [comment]
Why not both?
