### ISSUE TITLE
[Tarea 3] Duda funcion valor absoluto

### ISSUE THREAD

**Issue by roy350** [IIC2233-2016-02/Syllabus#370]
Hola, queria saber si la funcion valor absoluto, dentro de ella puede recibir cualquier tipo de operacion es que en el enunciado sale Abs[7 -8] entonces esa es una operacion mas "facil" no se si siempre sera asi o puedo esperar por ejemplo Abs[3^-5 \* -8] por ejemplo

**Comment by agmardones** [comment]
Hola @roy350,

Sí, puedes esperar cualquier conjunto de operaciones que retorne un valor válido para aplicarle Abs[]

Saludos!

**Comment by roy350** [comment]
Muchas gracias! y disculpa que te haga una pregunta que no tenga que ver con el titulo del tema, pero los Divisible, MCM y MCD dentro de sus corchetes deben ir variables definidas con anterioridad, o solo numeros o ambos por ejemplo 
a = 6;
b = 3 ;
Divisible[a,b];
o tambien se puede presentar el caso de directamente poner
Divisible[6,3];

**Comment by stephichau** [comment]
@roy350 pueden ser de ambas formas!
