### ISSUE TITLE
Duda consultas

### ISSUE THREAD

**Issue by jisilvamc** [IIC2233-2016-02/Syllabus#371]
¿Las consultas sólo se hacen al empezar el programa? Es decir,  ¿no se puede cambiar la consulta ni ver sus resultados desde la consola?
Muchas gracias de antemano

**Comment by agmardones** [comment]
Hola @jisilvamc,

Podrías ofrecer la opción de leer consultas.txt al usuario cuando quiera. Por simplicidad se pide que se lea al comienzo de cada ejecución (y genere los resultados). El usuario no debiese ser capaz de editar el archivo desde consola, y en la misma a lo más debiese aparecer un mensaje avisando que la escritura de los resultados fue exitosa.

Saludos!

**Comment by jisilvamc** [comment]
Muchas gracias
