### ISSUE TITLE
y si se corre un día la tarea? :)

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233-2016-02/Syllabus#372]
20 likes y la corren XD

**Comment by bamavrakis** [comment]
eran 20 likes y hay 21. No se corre, lo siento :(

**Comment by tcgarrido** [comment]
Ahora hay 20 :3

**Comment by bamavrakis** [comment]
hay 19

**Comment by jorgeriesco** [comment]
Jajajaaj no se bromea con esooo! :(

**Comment by aaossa** [comment]
Pucha, ya tenía el aviso listo. Lástima que nunca verá la luz

![photo74906175718664614](https://cloud.githubusercontent.com/assets/10425834/19209843/9e3bcc00-8ce9-11e6-9467-42ed2c3050ae.jpg)

**Comment by bamavrakis** [comment]
Si se bromea con eso, pronto subiremos la tarea 4.
Salu4.

**Comment by narierao** [comment]
Que grandes xD ame esta issue 😂❤️
