### ISSUE TITLE
Plot Color

### ISSUE THREAD

**Issue by FranciscoLarach** [IIC2233-2016-02/Syllabus#373]
¿Para los colores ingresaran la letra que corresponde?¿O el color en español, o ingles?
Saludos y gracias

**Comment by stephichau** [comment]
Hola @FranciscoLarach ! 
Revisa la issue [#293](https://github.com/IIC2233-2016-02/Syllabus/issues/293)! :)

**Comment by FranciscoLarach** [comment]
Gracias! No la había encontrado!.. o sea, el comentario jaja
