### ISSUE TITLE
Librerías permitidas/no permitidas en la T04

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233-2016-02/Syllabus#376]
Para consultar sobre una librería deben responder esta issue con una pregunta de la siguiente forma:

> Puedo usar la librería nombre_libreria para hacer explicacion_de_lo_que_quiero_hacer

Recuerden especificar en su README qué librerías utilizan!

---
## **Librerías Permitidas**
- random
- csv
- math
- time
- Numpy
- sys.exit
- copy
- itertools
## **Librerías Prohibidas**
- pandas
## **Built-ins prohibidos**
- eval (:skull:)
- exec (:skull:)

**Comment by fringlesinthestreet** [comment]
Puedo usa math para calcular senos, cosenos, raices, etc?

**Comment by FernandoPieressa** [comment]
@fringlesinthestreet Hola! Si puedes! Saludos

**Comment by roy350** [comment]
Disculpen pero se puede usar la libreria pandas, para leer y almacenar variables desde el archivo mapa.csv?

**Comment by flobarrios** [comment]
@roy350 no puedes usar pandas. No se si te fijaste pero la librería csv **si esta permitida**. Saludos!

**Comment by sormazabal** [comment]
Hola! se puede usar esta[ implementación del A\* Algorithm](http://www.redblobgames.com/pathfinding/a-star/implementation.html) para que los monos se muevan hacia un lugar?

**Comment by Hernan4444** [comment]
@sormazabal Puede usar Breadth-First Search pero no puede copiar esa implementacion,  La puede usar de apoyo, pero de ninguna manera incluir en tu tarea implementation.py
Saludos!!

**Comment by sormazabal** [comment]
@Hernan4444 Gracias!

**Comment by Mhornig** [comment]
Hola, se puede usar la libreria "time" ?

**Comment by Mhornig** [comment]
Hola, se puede usar time?

**Comment by ManuelSIlvaCav** [comment]
@Mhornig Si se puede usar time,
Saludos!

**Comment by Mhornig** [comment]
@ManuelSIlvaCav  Gracias

**Comment by alainrochette** [comment]
Se puede usar Numpy?

**Comment by FernandoPieressa** [comment]
@alainrochette  Si puedes usar Numpy!
Saludos

**Comment by asimonv** [comment]
Se puede usar deepcopy para copiar una variable?

**Comment by DiegoAndai** [comment]
Hola, ¿se puede ocupar la librería itertools en general? o sea ¿hay algo de esta que no se pueda ocupar?

**Comment by FernandoPieressa** [comment]
@asimonv Si puedes usar la libreria copy en general (con deepcopy incluido)

@DiegoAndai Si puedes usar la libreria itertools!

**Comment by DiegoAndai** [comment]
Hola, ¿se puede ocupar collections para usar deque()? es para hacer colas de actividades que realizan las tropas.

**Comment by flobarrios** [comment]
@DiegoAndai si puedes!

**Comment by sormazabal** [comment]
Hola! se puede ocupar Fractions para revisar la proporción que pide GodessFlo?

**Comment by Hernan4444** [comment]
@sormazabal no es necesario usar esta librería.
Saludos!!
