### ISSUE TITLE
Demo T04

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-02/Syllabus#377]
Hola !
Cuando corro el demo.py de la T04, la consola va imprimiendo "libpng warning: iCCP: known incorrect sRGB profile".
Por qué pasa esto ? Lo ignoro no mas ?

**Comment by flobarrios** [comment]
Hola !! Es una advertencia que tira por el perfil de las fotos png. Por ahora no te preocupes ya que no afecta para el desarrollo de la tarea. Se modificara el perfil de los assets dentro del día y avisaremos por aca!

Saludos 😊

**Comment by Hernan4444** [comment]
Hola!! Las imágenes ya fueron corregidas, no debería aparecer ese mensaje.
Saludos!!
