### ISSUE TITLE
Duda administrativa

### ISSUE THREAD

**Issue by srvasquez** [IIC2233-2016-02/Syllabus#378]
Hola, tengo una duda me pasa que en las dos tareas el puntaje que envian por mail es distinto a la nota que aparece en docs de las notas del curso, de hecho en la tarea 2 aparece nota 1, pero si me dan puntaje en los distintos items de la tarea, que nota es la que vale, de ante mano gracias.

**Comment by flobarrios** [comment]
@srvasquez ya actualizamos tu nota de la T01 en la planilla (la correcta era la del feedback). Respecto al feedback de la T02, los puntajes totales no fueron puestos en el overview pero si sumas cada item debiese coincidir con tu nota por lo que no te preocupes, la nota oficial es la de la planilla.

Saludos!

**Comment by srvasquez** [comment]
Muchas gracias, casi me muero al ver e overview jakkajkj.
