### ISSUE TITLE
Dudas de enunciado

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233-2016-02/Syllabus#379]
Hay unos puntos que no me quedaron muy claros y me gustaría ratificar que estoy entendiendo bien.

1) Se dice que la raza humana es racional y solo ataca cuando tiene 3/4 del ejercito enemigo (no me suena tan racional eso jaja pero filo) y cuando ataca deja la mitad en la base, eso quiere decir que estaría atacando con 3/8 del ejercito enemigo?

2)Los heroes se generan mediante una tasa, ¿Eso quiere decir que hay más de un héroe al mismo tiempo? Si no es así, ¿en que aplicaría la tasa?, y si fuera asi, ¿Por que importaría que muera para generar otro desde el tiempo en que murió?

3) A GodPezoa, ¿que hay que atacar para provocarlo? ¿El templo? ¿Su gente? ¿Cualquier edificio?

4) El Berserker, cuando se usa, ¿Es permanente para el resto de la simulación para todos los soldados que se generen y sigan vivos?

5) Se dice que si se destruye un edificio se detiene la creación de ejercito, no entiendo por que. Perfectamente se podría destruir una torreta y eso en que impide que se sigan generando soldados?.

6) No entiendo la explicación del init de la clase Entity. ¿Alguna otra forma de decir lo mismo?

7) En la nota, al final de archivo Mapa, sale que el archivo final presentará 8 edificaciones. ¿Que archivo final? Me perdí ahí.

8) Dice que el arribo del heroe es exponencial, osea, ¿Aparece cada vez más seguido?

9) Que es un tick?

10) Que onda el README 

11) ¿No modifico absolutamente NADA de lo que hay dentro de gui? Para estar seguro XD (A excepción de la variable mencionada obvio)

Y agrego una duda extra: ¿Para que es el modulo **init** que proporcionan en el programa? Dijeron algo de eso una vez, pero no me acuerdo.

Eso por ahora.

**Comment by ManuelSIlvaCav** [comment]
Estimado
Iré punto por punto:

1) Efectivamente seria 3/8, pero piensa en las características de las otras razas, al ser agresivas... los humanos vendrían siendo los defensivos de la simulación.  Puede suceder que después de un ataque enemigo los humanos queden con mas unidades, en este caso les correspondería atacar. También puede suceder que se aplique el criterio de 3/8 , y decidan atacar... pero el otro ejercito ya vendrá en camino a atacarte, por lo que seria como una defensa antes de que entren a su base.

2) Solo existe 1 héroe por raza, la tasa determina cuando aparecerá en la batalla y cuanto se demorara en revivir después de haber muerto.

3)Para Godpezoa considera la activación cuando muera una unidad o cuando entren enemigos a su base. Especificar en el Readme como se abordo.

4) El berserk solo aplica para los que sigan vivos, los nuevos ya no tendrán el beneficio.

5) Solo lo pusimos para simplificar el problema de destruir el cuartel. Pero claramente si destruyen una torreta no influye en la creación de unidades, pero si en el oro que se destinara para la siguiente actividad (reconstrucción de la torreta).

6) Guiate por los ejemplos de demo.py para entender lo que hace entity. En términos simples, cuando heredes de entity (O en su defecto Orc, human o skull) siempre tendrás que entregar un path, tamaño, puntos de vida y la posición (x,y) en forma de tupla además de las características que tu quieras.

7) Solo guíate por el contenido del csv que les subimos (Ojo que puede cambiar)

8) Ver punto (2)

9) El tick es una ejecución de la función que se le entrega, por ejemplo si en el tick dice que una unidad avance 2 en el eje x y la simulación dura 5 ticks, la unidad avanzo finalmente 10 en el eje x

10) Whoops!

11) NADA DE NADA

Extra: El modulo init que esta vació se nos fue jeje

Espero haber resuelto tus dudas !
Saludos

**Comment by tcgarrido** [comment]
Hola!! En el punto 11 dice que se nos entregara un mapa con las coordenadas de donde poner las edificaciones. Esto se refiere a que cuando el team quiera construir tendrá que hacerlo ahí o la simulación debe partir con la edificación en esa posición?

Saludos

**Comment by Hernan4444** [comment]
@tcgarrido Ese mapa indica la posición de las edificaciones con las cuales parte la simulacion, si llegas a construir otra debe ser en otra posicion

Saludos!!

**Comment by cglevican** [comment]
Hola, 
Para crear las clases de guerrero, aldeano, etc. puedo heredar directamente de Entity (sin pasar por Human, Orc, Skull) y dejar el tipo de raza como un atributo?

**Comment by cjgazali** [comment]
El punto 7) siento que no fue respondido. ¿Qué archivo final? ¿Qué significa 'ojo que puede cambiar'? ¿Cuándo cambia? ¿Por qué? No entiendo cómo ocupar el archivo. Solo entiendo la información que contiene, eso sí lo explican.

**Comment by Hernan4444** [comment]
@cjgazali tal como se respondió arriba, nos referimos al archivo .csv y con `ojo que puede cambiar` estamos haciendo referencia que al momento de revisar podemos cambiar la información de adentro, como las posiciones de las bases.
Saludos!!

**Comment by cjgazali** [comment]
Entonces el archivo final es simplemente 'el archivo'...
Entiendo que lo único distinto que podríamos recibir del archivo son esas posiciones, ¿correcto?
Es decir, todo lo demás es fijo, o puede haber cualquier cantidad de edificaciones?

**Comment by Hernan4444** [comment]
@cglevican los archivos .csv tienen la ventaja que en su primera linea indican el orden en como están ordenados los datos: `ARCHIVO,X,Y,TIPO,EJERCITO` y por lo tanto es totalmente aceptable para un csv cambiar el orden a este `'ARCHIVO,X,EJERCITO,Y,TIPO'` y obviamente los datos de abajo estaran ordenados de esa forma. Por lo tanto puede cambiar el **orden** y como tu dices las **posiciones.**
Saludos!!

**Comment by cglevican** [comment]
@Hernan4444 mi pregunta no era sobre los archivos, sino que del uso de las clases que nos entregan. Si es que es obligatorio usar las clases Human, Orc y Skull o puedo crear entidades directamente con entity.

**Comment by ManuelSIlvaCav** [comment]
@cglevican Hola!
Las clases Human, Orc, Skull las entregamos para facilitar el acceso a los paths de las imágenes correspondientes para los distintos tipos de unidades, es por esto que recomendamos su uso :D
Pero eres libre de heredar directamente de entity si te resulta mas fácil c:

Saludos!

**Comment by sebacruzd** [comment]
@ManuelSIlvaCav 
Cuando dices revisar el punto 2) por la respuesta a la duda de a qué se refiere el enunciado con arribo exponencial no entendí cómo era. Hay que usar expovariate con esa tasa?

**Comment by ManuelSIlvaCav** [comment]
Hola!
Efectivamente puedes usar expovariate con la tasa asignada para que te entregue un tiempo exponencial (random) el cual tu deberás considerar para el próximo arribo del héroe (si es que muere) o para que aparezca. 
En el fondo, si haces x = expovariate(tasa), donde x resulta ser 10seg, entonces a tu tiempo de simulación, deberás considerar que en 10 segundos más deberá aparecer el héroe :D 

Espero se entienda,
Saludos

**Comment by sebacruzd** [comment]
@ManuelSIlvaCav perfecto, ahora si entendí, gracias!

**Comment by ofvera** [comment]
en el archivo final, entiendo que igual no es posible que exista más de un templo o mina? la variación, seria de la posición y en cantidad de los otros 2

**Comment by Hernan4444** [comment]
@ofvera los archivos .csv tienen la ventaja que en su primera linea indican el orden en como están ordenados los datos: ARCHIVO,X,Y,TIPO,EJERCITO y por lo tanto es totalmente aceptable para un csv cambiar el orden a este 'ARCHIVO,X,EJERCITO,Y,TIPO' y obviamente los datos de abajo estarán ordenados de esa forma. Por lo tanto puede cambiar el **orden** y como tu dices las **posiciones**. No la cantidad
Saludos!!
