### ISSUE TITLE
Preguntas varias tarea 1

### ISSUE THREAD

**Issue by jatrijori** [IIC2233-2016-02/Syllabus#38]
Hola, tengo una serie de dudas sobre el juego:

1.- Sobre las "Consultas" que puede realizar el usuario:
Batalla por programón involucrado: ¿se debe ingresar solamente el nombre del programón y mostrar la info de todos los que se llaman igual o el usuario debe indicar si es salvaje/propio/de otro?
Ranking de programones: no sé a qué se refiere con  "entiéndase programón como Clases no como la instancia de este". ¿Es que el Ranking es según tipo de programón y no una lista de programones específicos? ¿O son sólo los programones propios? (idek) Además, no sé si sólo va el nombre del programón o también el nivel o lo que sea.

2.- Cuando se intenta capturar un programón salvaje y no se logra, ¿se pierde el turno y le toca atacar al programón salvaje (como en el juego real)?

3.- Leí en otra issue que el IV y EV se generan una vez para cada programón y se guarda para todo el juego, ¿ese IV/EV se mantiane incluso si el programón evoluciona?

**Comment by mjjunemann** [comment]
1.- 
- **Batalla por programon involucrado**: Debes mostrar la info de todos los que se llaman igual
- **Ranking de programones**: Digamos que existen 20 charmanders en el juego , y 10 Pikachus , luego sacas como el % de batallas ganadas del grupo de charmanders como pogramon como nombre.  (no se si esto se entendio)

2.- Queda a tu criterio

3.- Si, los EV e IV se mantienen

**Comment by jatrijori** [comment]
Gracias :smile_cat:
