### ISSUE TITLE
Aspecto Interface

### ISSUE THREAD

**Issue by ndleyton** [IIC2233-2016-02/Syllabus#380]
Hola, le puedo pedir a alguien que suba un screenshot de cómo se le ve la demo o la interface corriendo?
Sucede que al ejecutarlo se ve muy raro y creo que puede deberse a mal scaling.

Adjunto imagen de referencia de como luce.

![ss](https://cloud.githubusercontent.com/assets/20179825/19217977/cd80aafc-8dc1-11e6-8794-da47cf9ed281.png)

**Comment by Hernan4444** [comment]
Hola!!!
Aquí muestro una screenshot, el debugging lo deje como False por si acaso. 

![simulacion](https://cloud.githubusercontent.com/assets/15641721/19220181/87e6fc62-8dfd-11e6-8291-a0591d546045.PNG)

Recuerda que la interfaz es solo una ayuda para visualizar, si se ve un poco raro no te preocupes, no descontará nada. De todos modos puedes ir comentando en esta issue esos detalles para mejorar los assets (o arreglarlos en términos de scalling) o por ultimo para tenerlo en cuenta cuando evaluemos. 

Edit: Por si acaso recuerda que en el enunciado se indicó un tamaño mínimo de la interfaz que es 1024x680.

**Comment by Hernan4444** [comment]
@ndleyton Acabamos de agregar a las clases entregadas (Skull, Orc, Human, Templo and Building) un kwarg `size` que por defecto es `50 x 50` para las unidades y `100 x 150` para las construcciones. Ahora podrás alterar el tamaño de sus unidades en la simulacion sin editar nada de la gui :smiley: 
Saludos!!

**Comment by ndleyton** [comment]
Muchas gracias! ese kwarg ayudará bastante. Y @Hernan4444  respecto a la resolución, la interfaz esta ocupando en mi screenshot 1024 x 680 pixeles :/
