### ISSUE TITLE
Más dudas de enunciado 

### ISSUE THREAD

**Issue by tcgarrido** [IIC2233-2016-02/Syllabus#381]
Hola, después de leer el enunciado me surgieron las siguientes dudas:

1) La vida de las edificaciones y ejército, se regenera con el tiempo mientras no son atacados o simplemente permanece constante, o lo decidimos nosotros?

2) 7.3 Mascota: las mascotas tienen un rango medio (asumo que es rango de disparo) y luego se indica que si una unidad aliada esta siendo atacada dentro de su "rango de batalla" la irán a defender. El rango de disparo es igual al rango de batalla?

3) 7.5 Héroe: El héroe Cristian, mago que provoca daño (asumo que es daño infligido) reducido, puede convertir a unidades enemigas en copias de si mismo, ese "daño reducido" lo definimos nosotros? Dado que fuera de eso, sus copias no tendrían ninguna habilidad. 

4) En el mismo punto anterior, "los Dioses son benevolentes en entregarte uno [héroe] gratis", ese "uno" lo entiendo como que el primer héroe es gratis o tooooodos son gratis.

5) 8.1 Poderes: Invocar a los muertos, se revive a los últimos 7 soldados muertos en combate, "soldados" incluye arquero, guerrero y mascota?.

6) 8 Dioses: De acuerdo al "poder" de GodessFlo, si se ataca a una mascota aliada el ejército irá en su defensa y la mascota podrá seguir atacando al enemigo? 

Eso <3 Sorry si son preguntas muy evidentes.

Saludos!

**Comment by alainrochette** [comment]
7) 'Cada lado empieza con 800 unidades de oro y 5 aldeanos'. Esto significa que los templos no tienen que crear los aldeanos al principio?

**Comment by Hernan4444** [comment]
Hola!!!
1. Por enunciado no se regenera, pero si quiere hacerlo, bienvenido sea :smile: 
2. Con rango medio nos referimos que el rango de disparo de la mascota, ellas pueden atacar desde mas lejos que un soldado pero no tanto como un arquero. Y el rango de batalla es el mismo que el rango de disparo.
3. El daño reducido lo definen ustedes y así es, sus copias son simples soldados mas débiles. Solo que son quitadas del enemigo para ser tuyas.
4. Todos son gratis, solo que tienen un tiempo de reaparición después de morir
5. Exacto, incluye a los 3.
6. Así es, la mascota atacaran pero solo los soldados dejaran de atacar para ir donde esta su mascota y ayudarla a atacar a quien la está matando. Las decisiones de como implementar eso queda a tu criterio.

Por otro lado, cualquier cosa que no este especificada en el enunciado queda a tu criterio, mientras esté especificado en el Readme 

Espero haber respondido todas tus dudas.
Saludos!!!

**Comment by tcgarrido** [comment]
Gracias!!

**Comment by FernandoPieressa** [comment]
7) cada equipo busca tener 6 aldeanos asique buscarian tener 1 mas depues del inicio.

Saludos!

**Comment by tcgarrido** [comment]
Otra duda!! En las minas solo pueden haber 5 aldeanos al mismo tiempo
sacando oro. Eso se refiere a que el sexto debe estar dando vueltas en el
campo haciendo nada o puede esperar afuera a que los otros vayan a dejar al
templo y el ingresa?

**Comment by Hernan4444** [comment]
@tcgarrido eso queda a tu criterio, mientras cumplas el requisito de máximo 5 aldeanos en la mina, todos contentos :smiley: 
Saludos!!

**Comment by tcgarrido** [comment]
Otra duda :c 

8.1 Poderes: No entiendo bien como funciona, dice "Dado el nivel de energía requerido para usarlos, estos [dioses] solo pueden ocupar a lo más un poder" y después en Activación de poderes, dice que una vez que se cumpla el objetivo por algún team y este reciba el poder, se repite el proceso. 

Con esto entiendo que si un team gana ambos objetivos, tendrá dos poderes disponibles pero eso contradice la primera parte ("solo pueden ocupar a lo más un poder"). Tampoco me queda claro cuando deja de repetirse el proceso :c 

Saludos

**Comment by Hernan4444** [comment]
@tcgarrido otra respuesta c:

Al inicio, cuando seleccionas un dios, también seleccionas **un** poder. El equipo tendrá ese poder durante toda la simulacion pero no podrá usarla hasta cumplir un objetivo. Después que se cumple un objetivo, el equipo que lo logró tendrá a su disposición activar el poder. En ese mismo momento aparecerá un nuevo objetivo. Ahora puede pasar 2 cosas:
1. Equipo que ya tenia el poder vuelve a cumplir el objetivo, en ese caso simplemente volverá a tener disponible su poder, si es que lo había ocupado lo podrá volver a ocupar pero sino lo ocupó, mala suerte, no se acumulan los poderes.
2. El otro equipo cumple ese objetivo, en ese caso ambos equipos tienen a su disposición usar su poder. 
   En esta parte es decisión de tuya como implementar la opción de cuando usar el poder.

Este proceso solo se acaba cuando se termina la simulación.

Espero que haya quedado claro :+1: 
Saludos!!!
