### ISSUE TITLE
Borrar Unidades

### ISSUE THREAD

**Issue by sifelbol** [IIC2233-2016-02/Syllabus#382]
hola!
como puedo hacer desaparecer las unidades cuando se les acaba la vida?

**Comment by Hernan4444** [comment]
@Seba-F, Hola!!
- entity.hide() esconderá la entidad de la interfaz
- entity.show() la mostrará en la interfaz
- entity.deleteLater() la eliminara por completo de la simulacion

Saludos!!

**Comment by FranciscoLarach** [comment]
Hola, ¿ Como es eso de que la eliminara por completo de la "simulación" con el deleteLater?
No entiendo bien la diferencia entre hide y eso, ¿Que ventaja tendría el deleteLater?
Gracias, Saludos

**Comment by Hernan4444** [comment]
@FranciscoLarach las imagenes que están en la simulacion también son objetos y como tal deben tener un metodo `del` para eliminarlos de la memoria, `deleteLater()` hace esa función. en cambio `hide()` solo oculta al objeto de la simulacion pero sigue ocupando memoria.
Saludos!!
