### ISSUE TITLE
Duda sobre la clase Human

### ISSUE THREAD

**Issue by sormazabal** [IIC2233-2016-02/Syllabus#383]
Hola!
Estaba revisando la clase Human y no entiendo por qué se hace esto:

``` python
if class_ == "villager":
     if random.randint(0, 1):
          class_ += " 2"
```

**Comment by Hernan4444** [comment]
@sormazabal Como los humanos son una sociedad abierta de mente, no pueden mandar a trabajar como aldeano a solo mujeres o solo hombres así que ese random permite que aparezcan hombres y mujeres de forma al azar como aldeanos.
Saludos!!! :grinning:

**Comment by andresbannuraschultz** [comment]
Tambien tengo una duda relacionada: el parametro parent para las entities para que sirve? Gracias!

**Comment by ManuelSIlvaCav** [comment]
Hola!
El parámetro parent para las entities se usa cuando se trabaja con interfaz gráfica, para referirse a la widget sobre la que se pondrá (Spoilers) Puedes buscar mas información en los apuntes del semestre pasado! (sin embargo no es necesario que sepas para esta tarea, por eso les entregamos la interfaz hecha :D)

Saludos!
Recuerda cerrar la issue si se aclararon todas las dudas!
