### ISSUE TITLE
Duda ataques

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#384]
En el enunciado sale que no se puede atacar a un edificio en construccion, pero se puede atacar al aldeano que lo construye? Que pasaria entonces? Se interrumpe la construccion y se parte de cero, u otro aldeano puede retomar la construccion de donde la dejo el anterior? Muchas gracias.

**Comment by ManuelSIlvaCav** [comment]
Hola!
Para esta y todas las otras funcionalidades que no fueron definidas en el enunciado, **quedan a su criterio** como las implementan, dejando constancia en el Readme de como las abordaron.
Saludos!

**Comment by andresbannuraschultz** [comment]
Dale gracias!
