### ISSUE TITLE
Finalizar Simulación

### ISSUE THREAD

**Issue by fringlesinthestreet** [IIC2233-2016-02/Syllabus#385]
¿Cómo se puede finalizar la simulación? para que así se puedan desplegar las estadísticas y se acabe el programa

(Además de cerrar la interfaz)

**Comment by sebacruzd** [comment]
Se me ocurre que haya un evento "finalizar_simulación" que ocurra en el tiempo de duración máxima que se entrega al programa y cuando eso ocurra, que se haga lo que quieres con las estadísticas.

**Comment by ManuelSIlvaCav** [comment]
@fringlesinthestreet tal como dice @sebacruzd , esa puede ser una buena forma de abarcar tu duda

Recuerda cerrar la issue si tu respuesta fue respondida!
:D

**Comment by domingo-valdes** [comment]
Algo que no me queda claro es dónde o cómo imprimir las estadísticas al terminar la simulación. Alguien puede aclararme eso?
