### ISSUE TITLE
Ubicación edificaciones

### ISSUE THREAD

**Issue by tcgarrido** [IIC2233-2016-02/Syllabus#386]
Hola! por curiosidad,

1) Las edificaciones de ambos teams estarán "mezcladas" en el campo o estarán ubicadas en extremos distintos de este? 
2) La cámara se debe mover siguiendo al ejército, o permanece fija y todo se desarrolla en lo que podemos ver?

Saludos!

**Comment by Hernan4444** [comment]
@tcgarrido en relación a tus curiosidades:
1. Puedes suponer que siempre estarán en posiciones opuestas. Pero ten en cuenta que puede ser Derecha/izquerda, Arriba/abajo o Esquinas opuestas.
2. La cámara estará fija, todo se desarrollara en esa pantalla

Espero haber respondido tus dudas.
Saludos!!

**Comment by tcgarrido** [comment]
Gracias!
