### ISSUE TITLE
Movimientos

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#387]
hay que mostrar a los "monos" moviéndose? es decir que estén en un x,y luego en x+1,y y sucesivamente para que avancen?.
No entiendo como mostrar el desplazamiento (para poder enfrentarse, detectar enemigos, etc)
como definimos el rango de ataque de monos? , es decir en linea recta? medianamente circular? no me quedo nada claro de eso :c

**Comment by ManuelSIlvaCav** [comment]
Hola!
En cuanto al movimiento efectivamente es eso, al ser una simulación sincrona suceden cosas en cada tick (movimientos, ataques, poderes, avance de construccion,, etc) que uds deberán modelar como estimen conveniente!. 

Ahora respecto a como se acercan a atacar a los enemigos y el rango de ataque, todo esto lo definen uds. siempre especificando en el Readme!

Saludos!!

**Comment by narierao** [comment]
o sea puedo decir "los monos llegan y aparecen, no se desplazan" y llegar y cambiar a los monos de posición sin necesidad de hacer una recursión enorme?

**Comment by FernandoPieressa** [comment]
Hola! Si se deben mover,  ejecuta el demo.py entregado para que te hagas una idea de como tiene que ser.

Saludos!
