### ISSUE TITLE
Modificar clases

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#388]
Podemos agregarle metodos o atributos a las clases que ya crearon o estamos a obligados a heredar de ellas? Lo digo para no tener una clase Orc y otra MyOrc, siendo que la clase Orc no la instanciaria nunca (vendria siendo como una clase abstracta)

**Comment by ManuelSIlvaCav** [comment]
Hola!
En teoría debiesen trabajar con la clase Orc solamente, pero no han visto la materia de interfaces, es por esto que les indicamos que hereden de estas y le asignen uds. un comportamiento. Así que... No, no pueden trabajar directamente con ellas ;c

Saludos!

**Comment by andresbannuraschultz** [comment]
Dale gracias!

**Comment by jbsaeza** [comment]
Y puedo directamente no utilizar estas clases de ninguna manera, creando las mías (obviamente teniendo en cuenta las herencias utilizadas)?
