### ISSUE TITLE
[Testing]

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#389]
El decorador @ unittest.skipIf() recibe como una instruccion un booleano y un "comentario" mi pregunta es, ¿este booleano decide si entra o no al test? (¿depende la ejecucion del test que este booleano sea True o False?).
Analogo con @ unittest.skipUnless()

**Comment by jtagle2** [comment]
Si, se hace el test dependiendo del booleano entregado como parámetro.

**EDIT:** Skipif se salta el test cuando le entrego true. Skipunless se salta el test cuando le entrego false

Saludos
