### ISSUE TITLE
Enunciado dudas

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233-2016-02/Syllabus#390]
1) Manu puede tener más de dos mascotas?

2) Cda vez que se comience con el objetivo para el obtener el poder, ¿Se seleccionan al azar las dos cosas? Me refiero al objetivo y al poder. O hay alguna de las dos que son permanentes por toda la simulación? 

3) ¿Se debe informar el poder al que las razas están aspirando o solo se revela una vez logrado el objetivo?

**Comment by jgmontoya** [comment]
Hola,
1. Queda a su criterio, puedes hacer que tenga máximo dos o que cada cierto tiempo invoque más. **Recuerda mencionar tu decisión en el readme**
2. El poder se debe entregar como input al inicio de la simulación. El objetivo es al azar.
3. Como el poder es un dato conocido que se da al principio, no es necesario mostrar cuál es durante la simulación.

Saludos!

**Comment by Iruretagoyena** [comment]
@jgmontoya Hola ! En el enunciado dice "La elecciónon del poder es aleatorio para cada simulacion". Que hacemos ? Lo hacemos así o lo pedimos como input ? Personalmente preferiría que fuese como tu dices y uno pudiese elegir.
Quedo atento, saludos !

**Comment by Hernan4444** [comment]
@Diiru  tal como dice jgmontoya, preferimos que sea como input. Lo que aparece en el enunciado fue un ligero error.

Saludos!!

**Comment by cglevican** [comment]
El enunciado dice tambien "y no se podran repetir entre dioses enemigos". Se elige un poder distinto para cada raza en el input?

**Comment by Hernan4444** [comment]
@cglevican se debe preguntar por un poder para cada equipo. Queda a tu criterio si se aceptan poderes repetidos o no.
Saludos!!
