### ISSUE TITLE
Dudas sobre tiempos

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#391]
Cuando en el enunciado dice que la produccion de cierta unidad tiene un tiempo determinado en segundos, se refiere a segundos de la vida real o de la simulacion? Gracias!

**Comment by jgmontoya** [comment]
Hola, 
Son segundos de la simulación.
Saludos!

**Comment by andresbannuraschultz** [comment]
gracias!

**Comment by andresbannuraschultz** [comment]
Puede ser que los tiempos (iteraciones en verdad) sean muy cortos? Me pasa que los aldeanos estan 1 segundo en la mina o al lado de una construccion y terminan la "pega". Revise el codigo hartas veces para asegurarme que no era una falla de mi programa. Estare bien? Muchas gracias!

Tambien queria aprovechar de preguntar si es normal que las figuras "tiriten" al moverse? Si no es normal, alguna idea de por que podria pasar? Gracias de antemano.

**Comment by ManuelSIlvaCav** [comment]
Hola!

Respecto a lo primero, uds tienen que definir un tiempo de simulación y cuanto avanzara ese tiempo con cada tick, luego definir cuanto duraran las diversas actividades (ojo no necesariamente cada tick es un segundo).

Lo segundo,  puede pasar porque las imágenes que les pasamos originalmente eran mas grandes y las achicamos, nada que temer

Saludos!

**Comment by andresbannuraschultz** [comment]
Mmm creo haberte entendido, en el fondo un tick podria equivaler a 0.25 seg (o 0.5 ahi ir probando) con el fin de que se pueda apreciar en la interfaz que efectivamente se esta construyendo, minando, etc. 

Aprovecho de hacerte otra pregunta! jaja (sorry lo chato). Me esta complicando poder construi edificios en lugares que no topen con ningun otro edificio. Tenia pensado dividir el mapa en 2 mitades (para que cada ejercito construyera en su mitad) y en cada mitad definir posiciones donde se puediera construir (dado que el tamano de los edificios es fijo). El problema de eso es que como los edificios iniciales pueden partir en cualquier lado, pasa que no puedo maximizar la cantidad de edificios,y quedan espacios desaprovechados. De esta forma, habria una cantidad maxima de edificios para cada ejercito. Se que muchas cosas las puedo asumir mientras las explique en el readme, pero me entro la duda si esta era una de ellas. Muchas gracias de antemano, Andres.

O si tienen una idea mejor sera bienvenida! jajaj

**Comment by Hernan4444** [comment]
@abannura primero, siempre y cuando no sea justo arriba, sino que se distinga la construcción y cada uno, no hay problema con que sobrepongan un poco aunque el bonus podría verse afectado por ello.
Saludos!!!

**Comment by ManuelSIlvaCav** [comment]
Si se aclararon las dudas, recuerda cerrar la issue
:D

**Comment by cjgazali** [comment]
En esta discusión han dicho que lo que interesa son los 'segundos de la simulación' y que cuidado que 'no necesariamente cada tick es un segundo' lo cual me parece contradictorio. ¿Qué debemos contar como un segundo?

**Comment by Hernan4444** [comment]
@cjgazali un tick se ejecuta casi en una centésima de segundo, es decir que si consideras un tick como un segundo, en cada segundo (de la vida real) van a haber pasado 100 interacciones en la simulacion lo cual no es lo esperado, es trabajo de ustedes decidir cuanto tiempo equivale un tick o en otras palabras, ¿cuantos ticks son igual a un segundo? y en base a tal conversión realizar tu simulacion
Saludos!!

**Comment by andresbannuraschultz** [comment]
Dale gracias! (lo acabo de ver por eso no lo habia cerrado, no lo voy a cerrar todavia para que cgazali pueda ver su respuesta)

**Comment by cjgazali** [comment]
qué considerado jaja pero puedes cerrar cuando quieras
