### ISSUE TITLE
Duda chica del código. conceptual quizas

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233-2016-02/Syllabus#392]
¿Por que tick debe ser ingresado en run sin ()?, es decir, se debe escribir tick y no tick(), que si no me equivoco sería lo más normal. Lo digo pq cuando puse los () tiró error.

**Comment by jgmontoya** [comment]
Hola, 
Porque si le pasas tick() con los paréntesis, entonces se evaluará el método y se le pasará el valor de retorno de este a run (probablemente será None, aunque depende de cómo hayas definido el método tick).

Sin embargo run espera recibir una función/método para luego poder llamarla/o según se necesite.

Saludos!

**Comment by jorgeriesco** [comment]
¿Necesariamente tiene que ser el método de una clase? ¿Puede ser solo una función?

**Comment by jgmontoya** [comment]
Puede ser una función pero no será para nada práctico ya que tendrás que acceder a variables fuera de esta, por lo que tendrías que usar variables globales :skull:  o algo de ese estilo.

Saludos!
