### ISSUE TITLE
Duda al agregar nuevos edificios

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#393]
Bajan puntos si pongo un edificio encima de otro? No encima encima, pero que queden partes sobrepuestas. Gracias!

**Comment by FernandoPieressa** [comment]
Hola! Mientras esas partes sobrepuestas no dificulten la identificacion del edificio esta bien, sin embargo, la idea es que ojala no se sobreponga nada.

No olvides que el bonus esta dado por  la calidad de la simulacion y que represente fielmente todo lo ocurrido durante esta, por lo tanto el bonus se veria afectado si sobrepones edificios ya que estarias simulando que se contruyen edificios arriba de otros.

Saludos!
