### ISSUE TITLE
PEP8 [Tarea 2]

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#394]
Qué se evalua especificamente en PEP8? no entiendo ese descuento.

**Comment by FernandoPieressa** [comment]
Hola @narierao ! 

PEP8 es un conjunto de recomendaciones para que el codigo sea mas entendible y consistente, para esto la idea es que ustedes se acostumbren a usar las normas PEP8.

Entre estas reglas, esta que las lineas no sobrepasen los 79 caracteres, imports al comienzo del modulo, nombres de variables descriptivos, espacios entre lineas correctas, no mezclar espacios y tabs entre otras. 
Como el descuento es hasta 0.3, dependiendo del grado de errores con respecto PEP8 se pone el descuento.
Para mas informacion puedes buscar mas en https://www.python.org/dev/peps/pep-0008/ 

Esta informacion tambien fue dicha en ayudantia, te invito a ir a las ayudantias y leer los powerpoint para estar claro con este tipo de informacion, o utilizar google para buscar mas sobre PEP8.

Saludos!

**Comment by sebacruzd** [comment]
@FernandoPieressa acabo de darme cuenta de un gran problema con lo del largo que dijiste.
He estado usando Pycharm para que me ayude con los errores de PEP8 y avisa al pasar los 120 caracteres.

Buscando en google me di cuenta que eso es para IntelliJ, aún así diciendo que es PEP8.
He hecho todas mis tareas con Pycharm usando esa configuración, sin saber que estaba mal y ahora cambié la configuración para que me avise en 79 y no 120.

Podría ser considerado este caso para la corrección de la tarea 2/3?

**Comment by FernandoPieressa** [comment]
@sebacruzd 

Tal como dijo Antonio Ossa en la issue #344 
Pueden pasarse siempre cuando lo hagan para que el codigo siga entendiendose.

Siempre puedes mandar a recorregir si crees que te bajaron injustamente por estos puntos.

Saludos!

**Comment by sebacruzd** [comment]
@FernandoPieressa perfecto, gracias!
Pero entonces se puede hacer con un máximo de 120 caracteres en vez de 79 o es solo para excepciones?

**Comment by sebacruzd** [comment]
Con respecto a PEP8, puedo seguir este consejo que dan?
"A style guide is about consistency. Consistency with this style guide is important. Consistency within a project is more important. Consistency within one module or function is the most important.

However, know when to be inconsistent -- sometimes style guide recommendations just aren't applicable. When in doubt, use your best judgment. Look at other examples and decide what looks best. And don't hesitate to ask!

In particular: do not break backwards compatibility just to comply with this PEP!"

A veces siento que los 79 caracteres son muy poco, y me molesta tener que hacer saltos de línea en algunos lugares, con las respuestas que están dando encuentro cierta ambiguedad. Con los 120 caracteres que me recomendaba PyCharm estaba mucho más cómodo.
