### ISSUE TITLE
Tasa de produccion unidades

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#395]
La tasa es unica para cada cuartel o es para el ejercito entero? Es decir, si tengo una tasa 1:2:1 y 2 cuarteles, cada uno tiene que producir 1 guerrero, 2 arqueros, y despues esperar a que se produzca en un unico templo la mascota? Si es asi, y por ejemplo tengo 10 cuarteles, entonces el ultimo cuartel estara sin producir durante mayor cantidad de tiempo esperando a que se produzca su unidad de mascota. Que recomiendan? Gracias!

**Comment by andresbannuraschultz** [comment]
Podriamos asumir que el templo tiene la capacidad de producir varias mascotas a la vez (segun lo que le "exijan" los cuarteles)?

**Comment by sormazabal** [comment]
Puede haber más de un cuartel??
Las ubicaciones de los edificios no son según lo que nos da el archivo .csv? En ese archivo sólo hay una posición para el cuartel de cada raza.

**Comment by ManuelSIlvaCav** [comment]
Hola! 
Pueden asumir que solo habrá **1** cuartel.
Si desean hacer más de 1, para llegar a la tasa pedida, pueden crear los soldados necesarios de manera simultáneamente en los cuarteles y evitar el problema de las colas con las mascotas.

Saludos!
