### ISSUE TITLE
Duda de super().__init__

### ISSUE THREAD

**Issue by dfvasquez** [IIC2233-2016-02/Syllabus#397]
Hola!

Me surgió la duda de dónde poner el super() cuando se está heredando de otra clase. Lo he visto antes y después de definir los atributos y no entiendo cuál es, o si hay, alguna diferencia :(

Adjunto ejemplo de la tarea:

``` python
class Human(Entity):

    def __init__(self, class_, pos=(0, 0), size=(50, 50), hp=100,parent=None):
        if class_ == "villager":
            if random.randint(0, 1):
                class_ += " 2"
        super().__init__(["Human " + class_ + ".png"], size, hp, pos, parent)

```

``` python
class Entity(Widget):


    def __init__(self, base_image, size, hp=100, pos=(0, 0), parent=None):
        super().__init__(parent)
        self._base_label = QLabel(self)
        self._base_image = base_image
        self._size = size
        self._decor_label = None
        self._decor_pixmap = None
        self._hp_max = hp
```

Gracias :)

**Comment by fgvenegas** [comment]
Hola!

La verdad es que no hay diferencia en donde se llame al `super()`, cumplirá su misión tanto al inicio del `__init__` como al final. En el caso del código que pones de ejemplo es mas particular, ya que ahi el `super` recibe ciertos parámetros que van a variar dependiendo si el humano creado es "villager" o no y en base a eso cuando se llame, para Entity recibirá el atributo class_  modificado. Como te digo es un caso especifico donde si es necesario que se evalúen cosas antes de llamarlo, pues si se hiciera antes siempre recibiría class_ sin modificación. Espero se entienda :)
Saludos
