### ISSUE TITLE
Problema al instalar PyQt4 en Windows

### ISSUE THREAD

**Issue by nivek0o0** [IIC2233-2016-02/Syllabus#4]
Hola, 
Al escribir el comando **pip install -i https://pypi.binstar.org/petebachant/simple pyqt4**
me arroja el siguiente error:

![image](https://cloud.githubusercontent.com/assets/20782451/17314963/7967ccce-583e-11e6-960e-e3f59effb763.png)

**Comment by FernandoPieressa** [comment]
Ese problema suele suceder con tener instaladas distintas versiones de python al mismo tiempo (3.4 y 3.5 al mismo tiempo por ejemplo). Elimina uno.

Sino recomiendo hacerlo a traves de un .whl

Busca PyQt4 en http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyqt4 descargalo, y posteriormente desde consola, usa el comando: pip install ruta/de/mi/archivo.whl (también puedes usar el comando cd para irte a la carpeta donde se encuentre el .whl, así te ahorras la lata de poner la ruta completa).

**Comment by nivek0o0** [comment]
Muchas Gracias Fernando! Funcionó perfecto lo de descargar el .whl  de esa página e instalarlo en la consola con la ruta.

Eso si, hay que descargar el que contenga -cp35- si es que la versión de Python instalada es la 3.5.

Por eso mismo creo que el comando que aparece en la Wikia para instalar PyQt4 nunca funcionará, ya que la Wikia pide Python 3.5.x mientras que https://pypi.binstar.org/petebachant/simple solo tiene las wheels de las versiones 2.7 y 3.4

Saludos!

**Comment by aaossa** [comment]
Corregido en la Wiki :grin:, si alguien encuentra una falla en esta avise por aquí :clap:

**Comment by aaossa** [comment]
Seguramente tu computador es de 32 bits, asi que prueba con la versión de 32 bits,

**Comment by aaossa** [comment]
@mister-robot cuando corres `python` en la consola, ¿cuál es el output? En mi caso aparece esto:

```
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
```

Me dió la sensación de que quizás tienes una versión de Python que no corresponde a la arquitectura de tu computador

**Comment by Bnnunez** [comment]
¿Como puedo confirmar que este todo bien instalado, para el jueves? Al parecer creo que esta bien pero al usar  import PyQt4. 
No se reconoce import como comando.

**Comment by isipalma** [comment]
Igualmente para la primera actividad no tendras que utilizar PyQt4
trata de correr un codigo normal para ver si funciona, y prueba otras librerias

**Comment by jgmontoya** [comment]
@Bnnunez 

> Al parecer creo que esta bien pero al usar import PyQt4.
> No se reconoce import como comando.
> - @Bnnunez 

No estarás por casualidad intentando hacer import directamente desde el terminal?
Primero debes ejecutar:

```
python
```

o bien

```
python3
```

Y luego puedes intentar hacer el import.

Si no es este el problema copia el error que te tira.

**Comment by lefischer** [comment]
![image](https://cloud.githubusercontent.com/assets/17749111/17381151/8af746e4-5998-11e6-9a60-a32ce4dc3a87.png)
  lo intente segun lo corregido, pero sigo sin poder
