### ISSUE TITLE
Dudas demasiado básicas jajaa

### ISSUE THREAD

**Issue by bvfernandez** [IIC2233-2016-02/Syllabus#400]
Hola!! Tengo unas dudas que me tinca que son demasiado "básicas" pero prefiero aclarlas :).

1) dice que la guerra es entre 2 dioses y sus ejercitos... Asumo que solo hay dos ejercitos(por lo tanto dos razas)?o debo crear los otros dioses y la raza restante(lo que implicaria que estuvieran ahi y no peliaran)?

**Comment by criscv94** [comment]
Hola! 
Es como dices! Son **solo dos ejércitos**, deben tener raza y dios diferente y no es necesario que crees los dioses ni la raza restante :)
Saludos!

**Comment by ManuelSIlvaCav** [comment]
Recuerda cerrar la issue si tu duda fue respondida 
:D

**Comment by bvfernandez** [comment]
gracias!!! @criscv94
