### ISSUE TITLE
Agregar "monos" al campo de batalla

### ISSUE THREAD

**Issue by sormazabal** [IIC2233-2016-02/Syllabus#401]
Hola!
Tengo una duda sobre como estructurar mi programa: Sería mejor escribir el método que cree a los monos de cada ejército según la tasa g: a :m en la clase Simulación o en mi clase Ejército o Mapa, por ejemplo. (No en la clase Simulación, sino que en otro módulo)?

Lo pregunto porque sería más simple crear todos los métodos para agregar edificios y monos en la simulación misma, pero esto generaría un desorden tremendo y en el enunciado señalaron que modularizáramos lo más posible nuestras funciones.

**Comment by Hernan4444** [comment]
@sormazabal Hola! 
Una correcta modelacion debería ser aquella que se puede ajustar a las necesidades del programador, si para ti es mas simple crear todos los métodos pero eso generaría un desorden, sugiero darle mas vuelta a la idea antes de ponerse a programar. 
En realidad existen mas de una correcta modelacion e indicarte una seria encerrarte a una idea que tal vez no sea la mejor despues
Saludos!!
