### ISSUE TITLE
Mapa.csv - construcciones iniciales

### ISSUE THREAD

**Issue by Nebula2028** [IIC2233-2016-02/Syllabus#402]
Hola, discutiendo con unos colegas nos surgió la siguiente interrogante.

Los edificios que aparecen ahí, deben estar construidos y colocados en nuestro mapa inmediatamente al iniciada la simulación? O solo se debe comenzar con 1 templo y 5 aldeanos y el resto son las posiciones sugeridas (o **obligadas**) en donde tenemos que colocarlas una vez que queramos/podamos construirlas?

Pregunto por que el sem pasado en la tarea se entregaba un archivo mapa.csv similar, y la idea era que el mapa comenzara altiro con todas las cosas que ahí salían construidas.

Eso, de antemano, gracias

**Comment by Hernan4444** [comment]
@Nebula2028 las posiciones entregadas en el csv son  los edificios con los que inician cada equipo.
Saludos!!

**Comment by sormazabal** [comment]
@Hernan4444  Eso significa que cada ejército parte ya con una torreta y un cuartel, además del templo y la mina?

**Comment by Hernan4444** [comment]
@sormazabal Asi es!!!
Saludos!!

**Comment by fergarciafaura** [comment]
@Hernan4444 Y siempre en el mapa estarán todas las construcciones y solo se construirían en caso de ser destruidas ?. O en el mapa pueden no venir todas y tendremos que construir las faltantes ?.

**Comment by Hernan4444** [comment]
@fcgfaura puedes asumir que el archivo csv siempre vendrá completo con todas las construcciones.
Saludos!

**Comment by Snorlax8** [comment]
Hola!!

Tengo otra duda respecto al mapa: en el archivo que entregaron, hay una notoria separación izquierda/derecha, es decir, los edificios de un ejército están dispuestos más hacia el lado izquierdo del mapa y los del otro están más hacia el lado derecho. Fue casualidad o es la idea que los edificios de los ejércitos se dispongan en lados opuestos? Pregunto para ir regulando el lugar en el que aparecen las entidades según se necesite.

Muchas gracias! 🐱

**Comment by Hernan4444** [comment]
@Snorlax8 #386 
Saludos!!

**Comment by Snorlax8** [comment]
Muchas gracias @Hernan4444 !! No encontraba una issue que hablara al respecto 😅
