### ISSUE TITLE
Mascota [Rabia]

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#404]
Rabia son los puntos de daños que hace la mascota al momento de atacar para defender a uno de los suyos? y segundo, si lo anterior fuera correcto, las mascotas tienen algun otro "daño" que puedan hacer?
Ejemplo:
daño normal = 5
daño para defender (Rabia) = 15
gracias!

**Comment by Hernan4444** [comment]
@narierao como ese dato no fue especificado en el enunciado queda a libre disposición tuya c: Puedes considerar la rabia como otro daño que se aplica en "x" casos, como la probabilidad de defender a tu aliado, la probabilidad de hacer mas daño cuando defiendes, etc. Hay un montón de opciones que son totalmente validas mientras la especifiques en el Readme y sea una opcion razonable dentro de la simulacion.
Saludos!!!

**Comment by narierao** [comment]
@Hernan4444  Muchas gracias!!!
