### ISSUE TITLE
Objetivo 

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#405]
Cuando dice "Una vez completado el objetivo, se volverá a elegir uno de forma aleatoria y se repetira el proceso" esto es cuando uno de los dos equipo cumple el objetivo se cambia, o hay que dejar en "cola" el siguiente objetivo para el "perdedor del objetivo"?

**Comment by Hernan4444** [comment]
@narierao no entendí muy bien a que te refieres con: `dejar en "cola" el siguiente objetivo para el "perdedor del objetivo"?` pero lo que esperamos que al momento de que un equipo cumpla un objetivo, aparezca uno nuevo en el label de arriba en el cual ambos equipos puedan optar a cumplirlo.
Espero haber resuelto tu duda.
Saludos!!

**Comment by sormazabal** [comment]
Aprovecho de preguntar aquí también: el objetivo es el mismo para ambos ejércitos??

**Comment by Hernan4444** [comment]
@sormazabal así es, es un objetivo en **comun para ambos** por el cual se compite por quien lo cumple primero.
Saludos!!

**Comment by narierao** [comment]
Eso era. Muchas gracias
