### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#406]
![captura de pantalla de 2016-10-14 00-02-56](https://cloud.githubusercontent.com/assets/20784195/19374401/a12e0ec0-91a1-11e6-93f4-b881213f566e.png)

Que significa el error QPixmap::scaled: Pixmap is a null pixmap ?
cada vez que me aparece las entidades no se logran mostrar :c

**Comment by Hernan4444** [comment]
@narierao eso pasa porque el path no corresponde a una imagen y por lo tanto el QPixmap (que es el encargado de mostrar la imagen) recibe un argumento invalido. 
¿Ese error te aparece cuando instancias una unidad de las dadas por nosotros (en ese caso indicar cual por favor) o es por una entidad que tu intentaste crear??
Saludos!!

**Comment by narierao** [comment]
Si, eso era. Muchas gracias.
