### ISSUE TITLE
Barra de vida 

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#407]
estaba leyendo el codigo de Entity para poder ver como hacer que disminuya a barra de vida y me encontre con esta funcion

@health.setter
    def health(self, hp):
        if hp > self._hp_max:
            hp = self._hp_max
        elif hp < 0:
            hp = 0
        self.__hp_bar.setValue(hp)

el decorador @health.setter no pude encontrarlo y sigo sin saber como hacer que disminuya la barra. Busque en el enunciado y tampoco encontre lo que buscaba, solamente estaba hide_hp_bar() y si pude hacer que desapeciera, pero no logro hacer que vaya "disminuyendo".

**Comment by Hernan4444** [comment]
Hola!!, Te recomiendo revisar el demo.py. En la linea 27 esta resuelta tu duda.
Saludos!!
Pd: si tu duda quedo resuelta, no olvides cerrar la issue :D

**Comment by narierao** [comment]
Gracias!!!

**Comment by jtagle2** [comment]
Respecto a tu duda del decorador. Es un decorador que actúa para fijar el valor de las properties. Para ver acerca de como funciona, puedes revisar el material de clases en OOP, la parte donde habla de properties.
Saludos
