### ISSUE TITLE
Poder plaga

### ISSUE THREAD

**Issue by isidoravs** [IIC2233-2016-02/Syllabus#408]
Hola! Según el enunciado:

> Una vez transcurrido el tiempo de la plaga, las unidades que sobrevivan al
> ataque volverán a su velocidad normal.

Los puntos de vida que también fueron reducidos no deben volver a los originales, como lo hace la velocidad?
Gracias!

**Comment by Hernan4444** [comment]
@isidoravs Como no se especificó en el enunciado, queda a tu criterio las secuelas de la plaga mientras tenga sentido y coherencia dentro de la simulacion.
Saludos!!

**Comment by isidoravs** [comment]
@Hernan4444 gracias!
