### ISSUE TITLE
Problema PyQt4

### ISSUE THREAD

**Issue by fhgajardo** [IIC2233-2016-02/Syllabus#409]
Al revisar las issues sobre este tema encontré algunas que podían servir, pero ninguna lograba ayudarme sobre el error que me arroja: 
ImportError: DLL load failed : %1 no es una aplicación Win32 válida
A alguien le ocurrió el mismo problema y logro solucionarlo
De antemano muchas gracias

**Comment by jtagle2** [comment]
¿Revisaste que Python y PyQt4 sean ambos de 64 bits (o 32 si tu pc es de 32 bits)?

**Comment by fhgajardo** [comment]
Si ese era el problema, el computador tenia Python de 32 y el pc era de 64. 
Muchas Gracias
