### ISSUE TITLE
[Tarea 1] Restricciones

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#41]
Cito sección 10. Restricciones y Alcances:
"Su código debe seguir la guía de estilos PEP8."
"La revisión de la tarea será realizada con distintos archivos .txt"
Y 11. Entrega:
"Tareas que no cumplan con las restricciones señaladas en este enunciado tendrán la calificación mínima (1.0)."
Sobre PEP8, supongo que tendrán alguna manera de castigar poco la nota por un error pequeño de estilo, y que no ocurra que tenemos un 1.0 por no cumplir esa restricción. ¿Cómo revisarán esto?
Y sobre los archivos .txt, no entiendo de qué están hablando, favor de explicar desde cero que significa "La revisión de la tarea será realizada con distintos archivos .txt". Vamos a manipular archivos y van a haber varios, pero no entiendo la frase. Además, la información se almacenará en .json, ¿o no?

**Comment by FernandoPieressa** [comment]
Con respecto a la respuesta archivos .txt, ya fue preguntado y respondido en #28 

Con respecto a lo de PEP8, eso entra en la seccion de descuentos (Hasta 5 decimas). Es mejor acostumbrarse desde ya a escribir en PEP8!

**Comment by isipalma** [comment]
Tambien recuerden modular!!! que tambien descuenta
Ademas tambien les ayuda a ustedes modular para organizar mejor su codigo

Exito!

**Comment by cjgazali** [comment]
@FernandoPieressa ya leí #28 y preguntan por formato .json, pero lo que yo no entiendo es qué significa "La revisión de la tarea será realizada con distintos archivos .txt".
Aparte, por #28, pareciera que se esperan .json y no .txt . No entiendo muy bien la pregunta que se hace ahí. Favor de responderme directamente.

**Comment by Hernan4444** [comment]
@cjgazali Para esta tarea usaremos distintos archivos .json. NO .txt

**Comment by cjgazali** [comment]
Entonces...
"La revisión de la tarea será realizada con distintos archivos .txt" = "Tu entrega debe incluir todos los archivos .json necesarios para que el programa corra" ??
O quizás...
"La revisión de la tarea será realizada con distintos archivos .txt" = "Tu parser original debe ser capaz de recibir cualquier input .json" ??

**Comment by cjgazali** [comment]
Entonces...
"La revisión de la tarea será realizada con distintos archivos .txt" = "Tu parser original debe funcionar con cualquier .json" ??
Acabo de entender, si es que entendí. Me confirman.
¿Esto significaría que van a ver si cualquier .json (o sea que podría ser un .json que no conocemos, que no se incluye en la tarea y que no es necesario usar en la tarea) es procesado correctamente por el parser original?

**Comment by aaossa** [comment]
Si, te confirmo. Los json pueden tener cualquier "forma", pero las llaves y los tipos deberían ser los mismos.
