### ISSUE TITLE
[Tarea 4] Comportamiento de las razas segun objetivo

### ISSUE THREAD

**Issue by roy350** [IIC2233-2016-02/Syllabus#410]
Hola, disculpen pero me queda una duda acerca del comportamiento de las razas. Quiero saber si estas se ven afectadas por el objetivo que se quiera lograr, por ejemplo un humano en un inicio es pacifico, pero si el objetivo es "matar unidades" estos querran matar mas? o simplemente actuaran como siempre ya que ganar el objetivo no es una obligacion. Muchas gracias de antemano!

**Comment by ManuelSIlvaCav** [comment]
Hola!
La combinación de comportamiento de raza + objetivos + dioses, queda a tu criterio, siempre y cuando se mantengan los requisitos del enunciado. Por ejemplo, los humanos si tienen el objetivo de atacar unidades, entonces puedes bajar el requisito de unidades para atacar y dejar solo 1/4 del ejercito en la base. 
La idea es que encuentren una forma de implementar distintas lógicas, para distintas situaciones. Siempre especificando en el README como las abordan!

Saludos!
