### ISSUE TITLE
Agregar entidades

### ISSUE THREAD

**Issue by FranciscoLarach** [IIC2233-2016-02/Syllabus#411]
Hola! Sobre el agregar entidades, por ejemplo al agregar un guerrero, ¿puede este aparecer sobre el cuartel? o como hago para simbolizar que fue creado ahí.
Gracias

**Comment by Hernan4444** [comment]
@FranciscoLarach Si deseas que aparezcan sobre el cuartel nosotros podemos entender lo que buscas representar pero puede ser que la fidelidad de la simulacion se pierda un poco (debido a la superposición de imágenes) otra opcion es fijar una posición del cuartel por donde salgan y nosotros esperaremos ver que siempre aparezcan en ese lugar cada vez que pase el tiempo necesario. 
Saludos!!

**Comment by FranciscoLarach** [comment]
Gracias!
Y sobre los tiempos, por ejemplo los guerreros quedan separados por 5 segundos, que para mi son 5 ticks, por lo que al ir creandose, si se mueven poco, queda un desorden porque todo queda muy junto(hasta ahora mis figuras se mueven una unidad por tick o segundo), ¿Es eso normal, o deberíamos regular que las figuras se muevan por decirlo cada 0.1 segundos entonces tenga que esperar 10 ticks para 1 segundo?
Ya hice un como filtro para que los ticks sean mas lentos, entonces por eso los consideraba como segundos.
Gracias de antemano!

**Comment by Hernan4444** [comment]
@FranciscoLarach lo ideal es que regulen eso, pero si es que lograste aplicar un filtro que los tick sean mas lentos, también esta bien. La idea al final es que podemos apreciar como corresponde la simulacion sin ver cosas desordenas, demasiado juntas o que se mueven tan rápido que no podemos ver lo que sucede.
Saludos!!!!
