### ISSUE TITLE
Mover unidades trigonométricamente

### ISSUE THREAD

**Issue by domingo-valdes** [IIC2233-2016-02/Syllabus#412]
Hola! He estado tratando de hacer que mis unidades se muevan de modo trigonométrico, para que se vea más fluido el movimiento, pero no lo he logrado.Creo que es por temas de decimales, por ejemplo, cuando hay un seno muy pequeño y pongo que avance en una unidad multiplicada por el seno, lo cuenta como 0 y no se mueve. Quería saber qué se puede hacer al respecto.

**Comment by narierao** [comment]
yo hago lo mismo y si se mueve, muy poco, pero se mueve. y al comienzo me paso que el sin lo usaba en radianes y use luna funcion de math para pasarlo a grados. 
prueba si te funciona.
