### ISSUE TITLE
Error Enunciado

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2233-2016-02/Syllabus#413]
Hola, en el enunciado sale una palabra rara en Heroe. Deberia decir "hero". 
![image](https://cloud.githubusercontent.com/assets/20804346/19402761/4ff2cd82-9239-11e6-80c8-ebbd1bf6d993.png)
Gracias!

**Comment by Hernan4444** [comment]
@NicolasAguirre Muchas Gracias por avisar :D
Saludos!!
