### ISSUE TITLE
La simulación parte con los héroes creados?

### ISSUE THREAD

**Issue by sormazabal** [IIC2233-2016-02/Syllabus#414]
Tenía la duda de si el héroe estaba desde el principio o había que crearlo después de un tiempo o logro.

**Comment by ManuelSIlvaCav** [comment]
Hola!
La aparición del héroe viene definido por uno de los input (tasa de aparición del héroe), esto definirá cuando aparecerá el héroe en la simulación, ademas de definir cuando revivirá después de haber muerto!
Considera que este arribo es exponencial!

Saludos!
