### ISSUE TITLE
Término simulación

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#415]
¿Cuáles son las maneras de terminar la ejecución? En el demo pareciera que gui.run() no se detiene hasta que se cierra la ventana, y siguen ocurriendo ticks. ¿Habría que condicionar la función tick para dejar la interfaz corriendo pero no hacer nada al terminar el tiempo de simulación?
Las estadísticas al final, ¿se muestran en consola o en la interfaz? Dependiendo de las maneras de terminar la simulación, ambos casos tienen implicancias.
A grandes rasgos, ¿qué es de la interfaz cuando la simulación se acaba?

**Comment by ManuelSIlvaCav** [comment]
Hola!
Puedes ocupar sys.exit() para salir de la ejecución del gui.run cuando la simulación haya cumplido su tiempo máximo o se haya destruido un templo!
En cuanto a las estadísticas, las puedes printear en consola normal, pero ademas tienes que escribir un .txt con los resultados de la simulación.

Saludos!

**Comment by sormazabal** [comment]
@ManuelSIlvaCav  En el enunciado sale que "Una vez terminada la simulación, se deben mostrar las siguientes estadísticas:". Por esta línea yo entiendo que hay que imprimir en consola no más. Pero acabas de decir que hay que además generar un archivo. Hay que hacer las dos cosas?

**Comment by Hernan4444** [comment]
@sormazabal Asi es, hay que realizar ambas acciones.
Saludos!!!
