### ISSUE TITLE
Creacion de Clases del Gui

### ISSUE THREAD

**Issue by mraddatz** [IIC2233-2016-02/Syllabus#416]
Puedo hacer por ejemplo mi propia clase Temple que herede de building y utilizarla aunque ya venga una en el gui?

**Comment by Hernan4444** [comment]
@mraddatz hola!! 
 Claro que puedes, mientras realice las mismas acciones que la clase Temple que le dimos (ver su vida por ejemplo y el path correcto según el dios) puedes crear toda clase que quieras.
Saludos!!
