### ISSUE TITLE
Duda sobre deleteLater()

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#418]
Cuando dicen que este metodo borra a la entidad completamente del sistema, tengo la duda de que pasa en la siguiente situacion:

A,B,C son entidades (soldados por ejemplo)
A.enemy = C
B.enemy = C

A derrota a C, por lo que hago C.deleteLater()

Que queda guardado en B.enemy? None? No he podido decifrarlo, muchas gracias!

**Comment by domingo-valdes** [comment]
Otra duda con deleteLater(). Si tenemos una clase que hereda, por ejemplo, de Human, y luego borramos una instancia de la clase hija, el deleteLater no es realmente necesario o me equivoco?

**Comment by Hernan4444** [comment]
deleteLater lo que se encarga es eliminar ese objeto luego de que se ejecute el conjunto de instrucciones que se están dando, por ejemplo si ese método es llamado dentro de una función, al momento de terminar la función se eliminara ese objeto. Puede probar poniendo en el init del demo self.building.deleterLater() y en el tick algo como print(self.building.backgroundRole()) la simulacion te va a tirar error porque estas intentando acceder a un atributo de un objeto que fue eliminado antes.

@abannura deleteLater elimina el objeto, pero no las referencias a el, es por ello que dentro de la misma funcion que hiciste deleterLater() todavia podras acceder a la entidad pero luego te arrojará error por intentar acceder a algo que no existe.

@domingo-valdes en interfaz siempre que se quiera borrar una instancia se debe hacer deleteLater aunque se herede, solo así cortas todo tipo de conexión dentro de la interfaz con esa instancia.

Espero que haya resuelto sus dudas.
Saludos!!
