### ISSUE TITLE
Poderes

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#419]
Plaga afecta a los aldeanos?
Glaciar hace que los aldeanos dejen de recolectar oro?

**Comment by ManuelSIlvaCav** [comment]
Hola!
Yes! los poderes como plaga y glaciar **si** afectan a los aldeanos, para berserk y revivir a los muertos puedes no considerarlos, ya que no están en combate, quedan a criterio tuyo estos últimos.
