### ISSUE TITLE
[Tarea 1] Acerca de las evoluciones  y niveles

### ISSUE THREAD

**Issue by entamburini** [IIC2233-2016-02/Syllabus#42]
Hay programones que en el juego original son evoluciones, pero en este caso no lo son (por ejemplo, nidorino no evoluciona a nidoking en este juego). Obvio ese detalle?, o le pongo los datos que le faltan?
Otra consulta, ¿pueden aparecer pre evoluciones con nivel mayor a su evolución?, por ejemplo, ¿un weedle nivel 30?.
Muchas gracias!

**Comment by jtagle2** [comment]
Si quieres agregar programones o evoluciones no hay problema, siempre y cuando **mantengas los estándares entregados**. Es más, puedes inventar tus propios poderes, ciudades, gimnasios, rutas, etc... si también lo haces manteniendo los estándares entregados. 
De todas formas, al probar tu tarea, se usarán otros archivos json, por lo que todas tus invenciones de pokemones no se verán.
**_offtopic**_: Te recomiendo avanzar en las funcionalidades de la tarea antes que completar los 151 pokemones y sus evoluciones, pues hay una fecha tope de entrega

**Comment by entamburini** [comment]
Y acerca de las pre evoluciones?, pueden aparecer programons con un nivel mayor a su evolucion?

**Comment by agmardones** [comment]
Hola @entamburini !

No pueden aparecer pre-evoluciones de programones con un nivel mayor a su evolución.
