### ISSUE TITLE
Estadisticas

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#420]
Cuando dice tasa de creacion de unidades y tasa de muerte
Unidades es mascota, arquero, guerrero y  heroe? :o
y las muerte considera a los aldeanos además de los ya mencionados??

**Comment by ManuelSIlvaCav** [comment]
Hola!
Para todo lo que preguntaste, **SÍ**

Saludos

**Comment by narierao** [comment]
Gracias!
