### ISSUE TITLE
hp de building

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#421]
me gustaría darle un hp específico a los edificios, pero esto es posible solo para los 'monos', a menos que se modifique suavemente la forma en que crearon los edificios en gui (clases Temple y Building en building.py). Como está prohibido que nosotros modifiquemos gui, me gustaría saber si podrían permitir entregar hp distinto de 100 a los edificios, como parámetro opcional.
Gracias!

**Comment by Hernan4444** [comment]
@cjgazali Acabamos de subir una gui nueva donde los edificios y templo tienen un Kwarg llamado `hp` que como su nombre indica, sera para definir el hp máximo.
Saludos!!
