### ISSUE TITLE
edificaciones iniciales

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#422]
En el enunciado, tema 11 dice que archivo .csv especifica posiciones de edificaciones. Éstas son las edificaciones con las que parte cada ejército, según entiendo. Pero en tema 4 dice que todos parten con un 'set de edificaciones disponibles para construir'. ¿Están hablando de lo mismo? ¿Los edificios del .csv deben aparecer como en construcción (¿incluyendo el templo?) o deben estar listos?

**Comment by jgmontoya** [comment]
Hola,

Revisa la issue #402 

Saludos!

**Comment by cjgazali** [comment]
Entonces voy a ignorar la frase 'set de edificaciones disponibles para construir' que es lo que me complica. Se entenderá como 'set de edificaciones construidas'.

**Comment by jgmontoya** [comment]
Eso se refiere a que los edificios que puede hacer cada raza son los mismos.
