### ISSUE TITLE
Superposición

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#423]
Hay algun problemas con que las imagenes se "mezclen" es que necesito que esten cerca para que combatan (se ve algo mas o menos así) 

![captura de pantalla de 2016-10-15 18-55-58](https://cloud.githubusercontent.com/assets/20784195/19413670/200c99d2-930a-11e6-8f89-f6134e62b88d.png)

**Comment by ManuelSIlvaCav** [comment]
Hola!
Las imágenes se pueden "mezclar", ya que no es el fin ultimo de la tarea. **Evitar si**, que se sobrepongan a tal punto que no se puedan distinguir, ya que afectara la percepción de lo que pasa!
Saludos!
