### ISSUE TITLE
Duda sobre assets y debugging

### ISSUE THREAD

**Issue by fabraghetto** [IIC2233-2016-02/Syllabus#424]
Me percaté que algunos assets están rotados en comparación con los otros, por ejemplo el aldeano humano esta mirando hacia un lado por defecto y la aldeana humana esta mirando al lado contrario por defecto, esto igual complica la programación en el sentido de que caminen para donde miran etc. Puedo rotar las imágenes yo mismo en la carpeta gui/assets ?

Por otro lado, no entiendo bien como funciona el método __debugging_, en la demo que viene en la tarea viene el debugging como True, pero intento sacarselo por ejemplo a la unidad Skull que gira, agregando  "self.unit._debugging = False (con un guión bajo antes de la palabra debugging) en el __init__ de Sim pero no funciona (tampoco con las construcciones)

Agradecido de antemano por sus respuestas !!

**Comment by Hernan4444** [comment]
@fabraghetto la única linea que pueden editar es una que esta dentro de entity.py que dice `_debugging = True`, esa la pueden cambiar por False.

Sobre las imágenes, puedes rotarlas como estimes conveniente aunque también dispones de la property `angle` que rota las imágenes dentro de la simulacion.

Saludos!!

**Comment by fabraghetto** [comment]
Aah ahora entiendo! , gracias :)

**Comment by cjgazali** [comment]
@Hernan4444 pero para hacer una función que modifique el ángulo se necesita que ojalá todas estén por defecto mirando para el mismo lado...
Si roto una imagen, la consola me escribe en rojo:
libpng warning: iCCP: known incorrect sRGB profile

Entiendo que dijiste que sí podemos rotarlas. Se puede hacer que esto no aparezca?

**Comment by Hernan4444** [comment]
@cjgazali PyQt es muy sensible con las imágenes que se les da, deben estar en un formato especifico (Dentro del PNG con fondo transparente) es por ello que cuando la estas rotando con el programa que tengas o con una pagina online, este te esta devolviendo una imagen con un formato diferente al esperado por PyQt.

Solo te puedo sugerir que después de rotar la imagen, la pases por esta pagina:
http://imagen.online-convert.com/es/convertir-a-png
Esta devuelve los png en el formato que PyQt no se queja.

Saludos!!

**Comment by cjgazali** [comment]
@Hernan4444 y qué onda que algunas imágenes no se ven completas... el mono tiene que tener un tamaño cuadrado a mi parecer, porque si no, para un ángulo será favorable pero para la dirección perpendicular se vería menos que nunca.
¿Se puede hacer que tome la imagen con 'menos zoom'?

**Comment by Hernan4444** [comment]
@cjgazali Con que imagen te esta pasando eso??
Espero tu respuesta
Saludos!!

**Comment by cjgazali** [comment]
Bueno el dinosaurio sale como sin cola...
Si encuentro más te digo, pero al menos esa.

**Comment by Gonzalo-Perez** [comment]
Para qué quisiéramos cambiar a _debugging = True???
