### ISSUE TITLE
Agregar archivos png

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-02/Syllabus#425]
Hola !
Podemos agregar nuevas fotos, para mostrar en ciertas ocasiones, como valor agregado a la tarea ?
Salu2 y gracias de antemano

**Comment by ManuelSIlvaCav** [comment]
SIIIIIIIIIIIIII
:D
Saludos!

**Comment by criscv94** [comment]
SIIIIIIIIIIIIII
:D
Saludos!
