### ISSUE TITLE
Enunciado, parte Bonus

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-02/Syllabus#426]
Hola !
En el enunciado;
"Hint: Si ocurre algun dano fisico, se ve sangre, si alguien muere, aparece una tumba, etc. Para esto,
cuentan con el metodo: ..."
Luego de eso, no sale nada. Quede con la duda, a que método se referian ?
(probablemente es el init de entity, pero pregunto igual por si acaso)

Gracias de antemano

**Comment by Hernan4444** [comment]
@Diiru Asi es, en vez de método debimos haber puesto: `Para esto cuentan con la clase entity`
Saludos!!!

**Comment by Iruretagoyena** [comment]
@Hernan4444 Gracias !
