### ISSUE TITLE
Duda sobre properties en T04

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-02/Syllabus#427]
Hola !

Tengo un modulo donde manejo ciertas entidades y otro donde manejo la simulacion.
Mi intencion es hacer que dichas entidades tengan cierto comportamiento que haga que desaparezcan de la gui al cumplir cierta condicion.
Para esto, en la clase de la entidad tengo

``` python
    class Entidad(Y,X,Z):
        def __init__(self, ....)
            self.algo =....

        @property
        def condicion(self):
            if alguna_condicion:
                gui.self.deleteLater()
```

Como habran imaginado a esta altura de la pregunta, esto no esta funcionando.
Mi duda es;
El error es la forma como hago la propiedad ? Trate de hacer una property y un setter pero tampoco funciona.

O el error esta en la conexion con la gui ?

Perdon si no me exprese bien y agradezco cualquier ayuda !
Saludos

**edit**: Edité para que se vea mejor el código de ejemplo.

**Comment by Hernan4444** [comment]
@Diiru hola!!
1. Una property es para acceder a atributos que dependen de otro, no para editar. La property.setter se debe encargar de editar lo que quieras (recibiendo el parámetro que quieras poner).
2. ¿No te tira ningun error el tener gui.self? se supone que si estas heredando de entity basta poner self.deleterLater() para eliminarse despues de que se termine de ejecutar la  función.

Con la información que nos otorgas no podemos dar una correcta solución, por el momento te puedo sugerir aplicar el deleteLater() dentro de un método y no dentro de una property, por lo menos así te aseguro que me ha funcionado siempre.

Saludos!!

**Comment by Iruretagoyena** [comment]
@Hernan4444 
No pude hacerlo, pero hice un parche no más y lo deje como metodo en la simulacion. Fome igual, pero el tiempo apremia. No me tiraba error, probablemente porque no estaba entrando a la property.
Gracias igual !!
Saludos

**Comment by jtagle2** [comment]
@diiru, más allá de la tarea y de el error que te arroja (que no se cual es), en el código que pones hay un modelamiento bastaaante ~~malo~~ extraño.
En el código que pones, detengámonos en el `gui.self.deleteLater()`. Asumo que `gui` es una instancia de la interfáz gráfica o no? _(si no es así, de todas formas será instancia de alguna clase (o sería alguna clase(o me voy a la segura y digo algún objeto)))_. Ahora, tú al hacer `gui.algo`, estás diciéndole a la instancia gui, que acceda a su atributo `algo`, en tu caso, estaría accediendo a un atributo que está siendo direccionado al valor de dicho atributo, por una instancia de una clase, en tu caso, una instancia de entidad _(si no se entendió, leer de nuevo, si aún no se entiende, volver a preguntar)_. Ahora, dejando de lado que **esto no se puede hacer**,  (en realidad estarías buscando en un atributo que se llama self) , veamos una pequeña implicancia de este modelamiento.
Supongamos _(para efectos de la tarea no es tanto un supuesto, sino un hecho empírico)_ que tienes una interfaz, y durante tu simulación le vas agregando (o quitando) entidades (obvio, pueden morir en guerra o salir de cuarteles). Luego, cada instancia de la clase entidad, querrá llamar a su property `condicion`. Pero esta property, asume que la instancia está almacenada como un atributo de la instancia de Gui. El problema, es que cuando la Gui se crea, no sabe a priori que entidades van a existir, por lo que si quiere que todas las instancias de entidades estén como un atributo, tendría que ocurrir que cada vez que se crea una instancia de la clase entidad (llamémosla `instanciaejemplo`), en la instancia de Gui se debería crear un nuevo atributo que tenga como nombre `instanciaejemplo` _(como instancia de clase, no como string)_, y ahí recién podría funcionar el método. Y después cuando muere en guerra la `instanciaejemplo`, tendríamos que borrar el atributo que venía dado por `instanciaejemplo` de la gui. Como ya dije, no se puede hacer eso, pues la asignación de atributos no permite tener una instancia de una clase como key.
Una solución parche (que es aún más fea....) sería hacer que `gui.self` exista, y se defina en la misma property, algo como

``` python
@property
def condicion(self):
    gui.self = self
    if alguna_condicion:
        gui.self.deleteLater()
```

En fin, ese ejemplo "solución" podría funcionar, pero es bastante feo, y no corta el problema desde su raíz. Si viera algo así en una solución subida por alguien, me arderían los ojos, me explotaría la cabeza y después el mundo explotaría _(broma... pero se entiende el punto)_
Saludos! y suerte en la tarea

**Comment by Iruretagoyena** [comment]
@jtagle2 Hola ! Gracias por el tiempo que te tomaste en responder. La verdad es que el gui.self.deleteLater() lo hice solo para probar, en principio tenia solo self.deleteLater()  (cosa de manejar un objeto y su atributo). De todas formas, simplemente hice ese chequeo como un método de la simulación y lo puse que se chequeara en cada tick.
Gracias de nuevo !!
