### ISSUE TITLE
Sangre y tumbas

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#428]
En el enunciado dice que exsten unos metodos que permiten mostrar sangre y tumbas y no salen especificados. podrian subir el nombre de los metodos y lo que reciben? gracias

**Comment by Hernan4444** [comment]
@narierao en el enunciado no se dice que existen tales métodos, sino que como Hint les indicamos que esas cosas podrian suceder para darle una mejor calidad a la simulacion (entre otras cosas que se te pueden ocurrir). Lo que si nos fallo (y que se contestó en #426) fue que en vez de escribir método, debimos escribir clase entity.
Saludos!!

**Comment by narierao** [comment]
yaa muchas gracias!

**Comment by ceyzaguirre4** [comment]
como le doy prioridad a una imagen?
mis personajes pasan debajo de las tumbas :(
