### ISSUE TITLE
Duda sobre metodo, modularizacion y malas practicas

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#429]
Para variar tengo un codigo de infinitas lineas y esta vez no quiero perder puntos por no modularizar bien jaja. Entonces, tengo el siguiente problema: 

En un modulo tengo una sola clase con varios metodos, todos bien largos y creo que no los puedo acortar mas. Es una mala practica definir ese metodo como una funcion en un modulo aparte y que reciba como parametro el self? No se si me explico bien. En el fondo estaria definiendo un "metodo" fuera de la clase. No se si este tipo de modularizacion este bien. Gracias de antemano!

**Comment by fvr1** [comment]
Hola!
Mejor déjalo en un módulo. Eso si, si utilizas algunos métodos estáticos en tu clase, esos los podrías agregar a otro módulo. 

Ahora, igual puedes organizar los métodos y atributos dentro de tu clase para que queden más entendibles. Una estructura sugerida es:

``` python
class Clase:
      atributos_de_clase

     def __init__(self):
          # según pep8 tienes que definir en el init
          # todos los atributos que vas a usar 

     @property
     def properties:
          # property setter, getter etc.

     def __built_in_methods__(self):
          # normalmente se agregan los builtin en orden alfabético

     def _private_method(self):
          # los métodos privados también en orden alfabético

     def normal_method(self):
          # y después los normales
```

Lo importante es que agrupes los métodos privados con privados, públicos con públicos y así...
Saludos!

**EDIT:** Otra forma de ordenar funciones dentro de clases es a través del orden de llamada. Por ejemplo:

``` python
class Clase:

     def metodo_a(self):
         # etc
         self.metodo_b()

     def metodo_b(self):
         # etc
         self.metodo_c()

     def metodo_c(self):
         # etc
```

**Comment by andresbannuraschultz** [comment]
Gracias Flo por la explicacion! Me queda una duda eso si, que vendrian siendo los built in methods? Los metodos a los que yo hice overriding que eran built in de python?

**Comment by fvr1** [comment]
si! como el `__repr__, __str__, __lt__, __add__` etc...
