### ISSUE TITLE
Duda "jugadoresEjemplo.json"

### ISSUE THREAD

**Issue by dfvasquez** [IIC2233-2016-02/Syllabus#43]
Hola! Me surgió una duda viendo el archivo de ejemplo: "jugadoresEjemplo.json"... 
¿cuál es la diferencia entre "id" y "unique_id"?

Gracias :)

**Comment by Hernan4444** [comment]
@dfvasquez revisa estas issues: #25 y #26 
Saludos!

**Comment by dfvasquez** [comment]
Gracias!
