### ISSUE TITLE
Multiherencia y super()

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#431]
FAVOR DE EDITAR, no sé cómo hacer que el código quede junto...
(**self-EDIT:** Perdón por largarme, pero esto se me complicó mucho y es materia importante:)
Estuve leyendo el issue #314 para saber si podría hacer algo pero no me queda nada de claro cómo debería hacerlo.
Tengo aldeanos que heredan de sus razas respectivas. Naturalmente, cada una de estas clases aldeano, independiente de la raza, tienen cosas en común. Me gustaría que cada aldeano herede de su raza y de una clase Aldeano molde.
`AldeanoHumano(Human, Aldeano): (...)`
En el issue citado, nos dicen que ocupemos super() con args y kwargs pero no he logrado encontrar ejemplos de cómo ocupar esos args y kwargs.
¿Es viable llamar en dos líneas los init, el de Human y el de Aldeano por separado, especificando parámetros, o necesito usar super(args, kwargs)? Me complica que sea un solo super()... en su ejemplo:

``` python
class A:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

class B:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

class C(A, B):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
```

¿Cómo sería este ejemplo si se trabajara con los parámetros en el init? Porque como no hacen nada, no entiendo las reglas.
La clase Human no ocupa args ni kwargs.
Mi problema se resuelve si pudiera trabajar con cada clase de aldeano sin saber ya su raza, pero esto no es así. Necesito saber su raza y heredar de ella y llamarla. Pero me pregunto si es posible además moldear los aldeanos con una clase propia, lo que resulta en multiherencia.
Eso, gracias.

**EDIT (aaossa):** Para que se vea bien el código tienes que colocar 3 _backticks_ antes y 3 al final del segmento de código. Mira como quedó ahora para que entiendas la idea :ok_hand: 
**self-EDIT:** gracias @aaossa ! Esto se me complicó mucho, así que voy a continuar trabajando sin Multiherencia, pero la discución en general me parece positiva de todos modos.
El tema en particular es que hay métodos que son iguales para todos los aldeanos, pero operan conociendo los atributos que entrega la raza específica, que la clase Aldeano no sabe cuál es. Eso me bloqueó... Un ejemplo serían las coordenadas del ícono; necesito manipularlas en Aldeano, pero son propias del ícono, que es propio de la raza.
LA OTRA OPCIÓN es definir funciones (fuera de toda clase importante) que las clases llamen directamente. Éstas funciones reciben como parámetros todas las 'dudas de raza' que tenga. También me gustaría saber qué opinan de eso.

**Comment by fvr1** [comment]
Si entendí bien, estás tratando de hacer algo como esto:

``` python
class Human:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class Aldeano:

    def __init__(self, b, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.b = b


class AH(Human, Aldeano):

    def __init__(self, b, c,  *args, **kwargs):
        super().__init__(b, *args, **kwargs)
        self.c = c


ah = AH(2,3)

print(ah.b)
print(ah.c)
```

La cosa, es que a pesar que Human no reciba parámetros, igual es necesario que reciba `*args, **kwargs`. ¿Por qué? Python resuelve la multiherencia a través del uso de `super`, así sabe a cuál clase mandarle el parámetro que le corresponde. Si la clase madre no contiene el `super`, La clase hija no va a reconocer los atributos que lleguen de sus clases madres (exceptuando los de la primera clase madre que recibe, en este caso es `Human`). 

Corre el siguiente ejemplo para que entiendas a qué me refiero:

``` python
class Human:

    def __init__(self, *args, **kwargs):
        self.a = 0
        # super().__init__(*args, **kwargs)


class Aldeano:

    def __init__(self, b, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.b = b


class AH(Human, Aldeano):

    def __init__(self, b, c,  *args, **kwargs):
        super().__init__(b, *args, **kwargs)
        self.c = c


ah = AH(2,3)
print(ah.a)
print(ah.b)
print(ah.c)
```

Otra forma de mandar parámetros a las clases madres (desde la clase hija) es haciendo:

``` python
class AH(Human, Aldeano):

    def __init__(self, b, c):
        Humano.__init__(self)
                Aldeano.__init__(self, b)
        self.c = c
```

y quitando todos los `super, *args, **kwargs` de las clases madres. ¡Funciona! 

## PERO

Entramos al problema del diamante ya que estaríamos llamando dos veces al `init` de object (recordemos que todos los objetos de python heredan de object), por lo que no sería una modelación correcta.

**Comment by cjgazali** [comment]
@fvr1 gracias, te pasaste! Justo me temía lo último...
De todos modos, Human no está con `*args, **kwargs`...
Estoy concluyendo que no ocuparé multiherencia de esta manera para esta ocasión...

**Comment by DiegoAndai** [comment]
Me queda una duda, porque yo hice prácticamente lo mismo. Si ocupo el super().**init**() y manejo los parámetros con `*args` y `**kwargs` sin llamar a cada init por separado, ¿no hay problema de diamante cierto? o sea, si hago lo que escribió @fvr1 en el primer pedazo de código, eso esta correcto, ¿cierto?

Muchas gracias.

**Comment by fvr1** [comment]
@DiegoAndai sí! estaría correcto! `super` se encarga de evitar el problema del diamante

**Comment by roy350** [comment]
@fvr1 Muchas gracias!! tenia justo este mismo problema vi tu respuesta de la issues y me funciono!!! :D

**Comment by roy350** [comment]
Una duda relacionada con el mismo tema, mi programa se cae al momento que hago gui.add_entity(self.aldeano1) siendo self.aldeano1 de la clase Personaje, que hereda de Humano y Aldeano, nose a que se debe como que no me deja agregarlo a la interfaz, no si si es por algo que estoy haciendo mal, o nose

**Comment by Gonzalo-Perez** [comment]
Una duda con respecto a la segunda opción que propuso Florencia (fvr1):

``` python
class AH(Human, Aldeano):

    def __init__(self, b, c):
        Humano.__init__(self)
                Aldeano.__init__(self, b)
        self.c = c
```

Considerando que por la estructura de mis clases y herencia no debería tener el problema del diamante (No hay clases con más de una clase hija), esto puede hacerse sin "entrar en malas prácticas"?

De antemano, gracias !
