### ISSUE TITLE
Problemas con elegir random

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#432]
Tengo una funcion que le dice a un mono a donde ir (hacia un objeto, sea guerrero o edificacion). El problema es planeaba hacer una lista de la cual pudieran escoger al azar. pero el problema es que cuando se buscan a veces el programa explota (a los monos les dan taldos). Recomiendan hacerlo de forma configurada?(predeterminada) porque siento que le quita realidad a la simulacion :c
![captura de pantalla de 2016-10-16 19-29-50](https://cloud.githubusercontent.com/assets/20784195/19421418/f56a4f26-93d6-11e6-9761-166429054ad2.png)

Se ven de esa forma y se ponen a tiritar :/
PD: La funcion de ir a X lugar funciona, la probe con los aldeanos para que vayan a buscar la mina y funcionada ok.

**Comment by aaossa** [comment]
Quizás estás cambiando la decisión en cada tick? Puede ser que en un momento una entidad vaya a un lugar y en el siguiente decida ir a otro lado, provocando que tirite.

**Comment by narierao** [comment]
si, acabo de asignarle un "contrictante predefinido" y funciona impecable. 
gracias!
