### ISSUE TITLE
Equipo ganador

### ISSUE THREAD

**Issue by jatrijori** [IIC2233-2016-02/Syllabus#433]
Hola, no me quedó claro qué equipo se define victorioso una vez que termina la simulación: ¿el que tiene menor tasa de muertes, el que se queda con su templo en pie, el que queda con más unidades vivas, etc? Quiero saber porque en la parte de estadísticas piden el resultado final.

Gracias de antemano :)

**Comment by tcgarrido** [comment]
Quien primero derrumbe el templo enemigo, gana.

**Comment by Hernan4444** [comment]
@jatrijori tal como dice tcgarrido, el primero en derribar el templo gana. En caso de que ambos tengan el templo en pie seria un empate. A no ser que especifiques un criterio nuevo para decidir el ganador cuando ambos templos esten en pie, en ese caso no olvides especificarlo en el Readme.
Saludos!!
