### ISSUE TITLE
Dudas T04

### ISSUE THREAD

**Issue by gabrielpinkman** [IIC2233-2016-02/Syllabus#435]
Hola queridxs, disculpen la intromisión, revisé un poco algunas issues para ver si solucionaba un par de dudas de enunciado, pero no encontré nada parecido así que aquí voy...

1) Cuando se habla que cada raza tiene un número de unidades máximas en el campo, cuenta guerreros y arqueros o también cuenta a las mascotas?

2) En el enunciado dice que un aldeano tiene puntos de vida, eso significa que el aldeano puede ir caminando por ahí y lo atacan y se muere sin defenderse?

3) Se pueden tener más de 6 aldeanos en el campo, o 6 es el minimo? o 6 es el máximo?

4) Se puede tener una cantidad fija de aldeanos recolectando oro, o el número debe ir variando?

5) En cuanto a los poderes de dioses, la plaga produce que se le resta vida a los enemigos paulatinamente, o se les baje la vida de golpe?

6) El poder de dioses Glaciar, debe tener un radio o afecta a todas las unidades enemigas?

Saludos

**Comment by Hernan4444** [comment]
Hola!!!
Sobre tus dudas, aquí voy con tus respuestas...
1. Cuanta todo tipo de soldado, es decir guerrero, arquero y mascota. (No cuenta el aldeano)
2. En principio si. Si tu quieres implementar que se puede defender (o huir) para mejorar la simulacion, es totalmente bienvenido, solo recuerda que el aldeano no tiene armas y especificar en el Readme si es que haces un cambio.
3. 6 es la máxima cantidad y a la vez la mínima. Si hay menos de 6, el templo deberá crear los aldeanos restantes hasta llegar a los 6 y de ahí seguir con lo que estaba haciendo. (No necesariamente debe detener la producción de la mascota de ese momento, puedes esperar que termine y de ahí poner a hacer los aldeanos)
4. Los aldeanos tienen un atributo fuerza que les permite acarrear mas oro o lo que se indica como base. Es decir hay una cantidad fija de oro a recolectar pero los aldeanos pueden superarla si es que tienen mas fuerza.
5. Aunque no se especificó preferimos que sea paulatinamente para ir viendo el efecto de la plaga hasta el momento que termina.
6. Es un poder global, afecta a todas las unidades enemigas.

Espero haber resuelto tus dudas  :smiley: 
Saludos!!

**Comment by gabrielpinkman** [comment]
Sen kiu <3

**Comment by narierao** [comment]
heroe cuenta como soldado? para efectos del maximo?

**Comment by Hernan4444** [comment]
@narierao no, el héroe déjalo como unidad extra.
Saludos!!
