### ISSUE TITLE
Cambio pequeño en la gui

### ISSUE THREAD

**Issue by nicovsj** [IIC2233-2016-02/Syllabus#436]
Hola,

En el enunciado está bastante claro que no debemos tocar la gui excepto para cambiar la variable debugging, pero hice esto en la property `@angle.setter` de entity.py que hace que los ángulos de las entidades estén siempre en el rango 0 - 359.(9)

``` python
@angle.setter
    def angle(self, angle):
        angle %= 360
        self.__angle = angle
        self.updatePixmap()
```

Es aceptable agregarle esto a la gui? Pregunto porque en el enunciado fueron bien categóricos con el tema, pero creo que es un cambio razonable. 

Gracias de antemano.

**Comment by jgmontoya** [comment]
Hola,

Si bien es razonable el cambio no aseguramos que vamos a revisar con la misma gui que modifiquen por lo que ese cambio posiblemente no estará en la versión de la gui que usemos. Por lo tanto te recomendaría hacer esa modificación en tu código y no en la gui.

Saludos!

**Comment by nicovsj** [comment]
Muchas gracias!
