### ISSUE TITLE
Invocar a los muertos

### ISSUE THREAD

**Issue by sebacruzd** [IIC2233-2016-02/Syllabus#437]
En el issue #381 está la siguiente pregunta y respuesta.

"8.1 Poderes: Invocar a los muertos, se revive a los últimos 7 soldados muertos en combate, "soldados" incluye arquero, guerrero y mascota? : Exacto, incluye a los 3."

Como no se preguntó por héroes no me queda claro si ellos también cuentan o quedan a nuestro criterio.
En caso de tener que revivir a los héroes, Hernán reviviría con 3 vidas de nuevo?

**Comment by ManuelSIlvaCav** [comment]
Hola!
Revivir a los muertos **no** incluye a los héroes de la raza :D 
Saludos!
