### ISSUE TITLE
Duda heroe hernan

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#438]
En el enunciado sale que Hernan tiene 3 vidas, estas son aparte de la tasa de creacion propia del heroe? O si lo matan 3 veces se acabo el heroe skull para todo el resto de la simulacion?

**Comment by Hernan4444** [comment]
@abannura en el caso de Hernan, despues de morir 3 veces comienza a contar la tasa de creación del heroe para que vuelva a aparecer con 3 vidas otra vez.
Espero que quedara claro este punto.
Saludos!!

**Comment by andresbannuraschultz** [comment]
Perfect! Muchas gracias Hernan jaja
