### ISSUE TITLE
Cómo detener la función run?

### ISSUE THREAD

**Issue by dfvasquez** [IIC2233-2016-02/Syllabus#439]
Holaaaaaaa, necesito ayuda!

Cómo detengo la función run? recibe como parámetro la función tick de mi clase de simulación y no sé como detenerlo :(  Traté de correrlo con un for y explotó jajaja tuve que reiniciar el pc para cerrar python 😆 

Gracias

**Comment by FernandoPieressa** [comment]
Hola!

Puedes usar sys.exit() cuando se cumplen las condiciones de finalizacion de la simulacion, como por ejemplo poner
if [CONDICION]:
  print("finalizado!")
  sys.exit()

No uses for para el trabajo del tick porque quedaras en un loop infinito! Mira el ejemplo del demo.py para ver como ejecutar el tick correctamente usando gui.run

Saludos!

**Comment by dfvasquez** [comment]
GRACIAAAAAAAAAAAAAAAAAAAS 😃
