### ISSUE TITLE
Duda excepciones

### ISSUE THREAD

**Issue by sebacruzd** [IIC2233-2016-02/Syllabus#440]
Hola, avanzando en la tarea me surgió una duda sobre el manejo de exepciones.
He avanzado una cantidad considerable, pero no he hecho nada con try ni except aún.

Recomiendan terminar la tarea (o avanzar lo más posible) asumiendo que todo corre bien y finalmente cambiar lo necesario a try y except, como en la actividad de clases, o hacerlo manejando excepciones desde el principio?

Se me hace más natural hacerlo sin try y except por costumbre, pero no sé qué me tomará más trabajo realmente.

Gracias de antemano.

**Comment by Hernan4444** [comment]
@sebacruzd, si revisas el material del curso, se hace incapie en que try y except se usan principalmente para el manejo de input puesto que dentro del codigo todo se puede trabajar con los condicionales necesarios pero un input es mas dificil de trabajar con `if/else`. Con esta respuesta supongo que ya sabrás en donde esperamos que apliques try y except.
Saludos!!!

Edit: Tambien puedes considerar casos criticos dentro de la simulacion donde supones que puede haber un error como cuando eliminas a un soldado pero otro objeto hizo referencia a él despues, o cuando chocan, etc.

**Comment by sebacruzd** [comment]
@Hernan4444 Gracias! Ahora lo tengo claro.
