### ISSUE TITLE
gui.run()

### ISSUE THREAD

**Issue by Gonzalo-Perez** [IIC2233-2016-02/Syllabus#441]
Alguien podría explicarme que hace el gui.run(sim.tick) que parece en la demo de la tarea 4?
No logro entender donde se encuentra el método "run" de la gui.

De antemano, gracias.

**Comment by sebacruzd** [comment]
Por lo que entiendo, toma el método tick de la instancia sim, y lo ejecuta una vez cada 25 ms, que es el delay default que viene en el método run().
Esto está en la carpeta gui, en el archivo **init**.py

```
def run(main, delay=25):
    __main_widget.show()
    __main_widget.startMain(main, delay)
    # __main_widget.showFullScreen()
    __app.exec()
```

**Comment by Hernan4444** [comment]
@Gonzalo-Perez, tal como dice @sebacruzd el metodo run de la gui, que  esta `gui\__init__.py` recibe como argumento una función o método (sin los parentesis) y se encarga de ejecutarla constantemente con un delay de 25 ms hasta que tu hagas sys.exit y se termine todo.
Saludos!!!
