### ISSUE TITLE
entity.hide()/entity.show()

### ISSUE THREAD

**Issue by cameneses** [IIC2233-2016-02/Syllabus#442]
En la parte de Recursos/Mina de Oro sale que podemos simular el paso de los aldeanos por la mina con entity.hide() y entity.show(). Sin embargo al aplicar, por ejemplo entity.hide() sobre alguna entidad, no logro hacer que esta se oculte en la interfaz gráfica.

Intenté probarlo en la demo que venía con el enunciado de la tarea para ver si es que era un problema en el código de mi tarea. Esto lo hice usando self.unit.hide() sobre la unidad que definen en esta simulación, pero tampoco logré ocultar al Skull en la interfaz gráfica.

¿Hay algún problema con este método?, o bien ¿no lo estoy usando correctamente?

**Comment by Hernan4444** [comment]
@cameneses podrías pushear tu código para poder analizar tu problema.
Avísanos cuando pushees tu código.
Saludos!!!

**Comment by cameneses** [comment]
@Hernan4444 ya lo hice! Esto lo tengo en razas.py, específicamente en la línea 39.
Muchísimas gracias!!

**Comment by jtagle2** [comment]
@cameneses, Viendo tu código, vi que en la función que hace que vaya a recoger oro, haces un time.sleep(1). Es por eso que falla el show y hide (estoy casi seguro, salvo que haya algún otro error, no revisé todos los módulos). Prueba haciendo que el que lleva el tiempo de esconder la imagen, es el tiempo de la simulación (vale decir, los ticks).
ej: Supongamos que el aldeano se demora _k_ segundos en sacar oro, y empieza a sacar oro en el instante _t_. Si hacemos eso, entonces en el instante _t_, dicho villager tendrá que usar `villager.fig.hide()`. Luego, más adelante en tu simulación, llegará el instante _t+k_, que coincide con el tiempo en que el villager va a terminar de sacar oro, y en ese instante haces el `villager.fig.show()`.
Como tip: interfaz gráfica + time.sleep() = problemas

**Comment by cameneses** [comment]
Revisando, justamente es eso, pues sacando el time.sleep el método hide/show funciona bien en la interfaz gráfica.

Muchísimas gracias!!
