### ISSUE TITLE
Bonus

### ISSUE THREAD

**Issue by ceyzaguirre4** [IIC2233-2016-02/Syllabus#444]
Como le doy prioridad a una imagen?
Mis personajes pasan debajo de las lapidas

[edit] y como hago para que no se vea la health bar de las entidades "no vivas" (ie tumbas, ruinas, etc)

**Comment by cjgazali** [comment]
[edit] busca en el enunciado!

**Comment by cjgazali** [comment]
Cómo le das prioridad a las imágenes?? jaja quería saber...
