### ISSUE TITLE
Velocidad de ataque

### ISSUE THREAD

**Issue by sebacruzd** [IIC2233-2016-02/Syllabus#445]
Hola.

En las torretas hay velocidad de ataque, pero en ninguna otra unidad veo que se diga que deben tener velocidad de ataque.

Yo estaba considerando que por cada tick podían atacar una vez, pero al crear la torreta me confundí.
Está bien lo que estoy haciendo?
Tal vez para diferenciar la torreta podría hacer que cada dos ticks (u otra cantidad) ataque, será suficiente esto o debo agregarle una velocidad de ataque a cada entidad que pueda pelear?

Gracias de antemano.

**Comment by ManuelSIlvaCav** [comment]
Hola!
Efectivamente las torres se diferencian por tener velocidad de ataque, por lo que no necesariamente atacara en cada tick(), queda a tu criterio definir cada cuantos ticks atacara la torre, especificando en el README

Saludos!

**Comment by sebacruzd** [comment]
Gracias! :grin:
