### ISSUE TITLE
Error objetivo interfaz

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#446]
Me pasa que en el objetivo solo se muestra la primera palabra. Por ejemplo si quiero poner "recolectar 300 oro" muestra recolectar nomas. A alguien mas le pasa o pasaba? Como lo solucionaron? Gracias de antemano

**Comment by ManuelSIlvaCav** [comment]
Hola!
Esto puede pasar por la resolución de la pantalla por lo que el largo de la label cambia, sigue imprimiendo el texto que quieras aunque se corte, pero ademas, imprime por consola para verificar el objetivo!

Saludos!

**Comment by andresbannuraschultz** [comment]
Dale muchas gracias!
