### ISSUE TITLE
Tamano gui

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#447]
Podemos asumir que la gui sera siempre del tamano estandar? Que uso sus dimensiones para poner los edificios en su lugar. Si no es asi, y el tamano de la gui puede cambiar, como hago para acceder a esta info? Me imagino que esta guardada en gui bajo algun atributo. Gracias!

**Comment by Hernan4444** [comment]
@abannura puedes asumir que el tamaño estandar de la gui sera el mínimo solicitado en el enunciado (1024 x 680)
Saludos!!!

**Comment by andresbannuraschultz** [comment]
Vale gracias!
