### ISSUE TITLE
Construcciones

### ISSUE THREAD

**Issue by smargozzini** [IIC2233-2016-02/Syllabus#448]
Hola!
es posible que una raza decida construir otra edificación, por ejemplo tener dos torretas?
gracias!

**Comment by Hernan4444** [comment]
@smargozzini no esta especificado pero si dentro de tu implementacion consideras correcto construir otra, mientras no se sobreponga a otra edificación, es totalmente bienvenido pero no olvides especificarlo en el Readme.
Saludos!!

**Comment by isidoravs** [comment]
Si dentro de mi implementación no considero que una raza construya más torretas, podemos asumir que la cantidad de éstas que nos den en el mapa siempre será uno? O podría un ejercito tener varias torretas desde un principio?

Gracias!
