### ISSUE TITLE
[Tarea 4] Terminar simulación.

### ISSUE THREAD

**Issue by Kitaps** [IIC2233-2016-02/Syllabus#449]
Hasta ahora lo que he hecho es que cuando llega al tiempo dado por consola ha sido:

Meterle un break

Entregar un while True: pass

Entregar un sleep(muy grande)

Pero en ambos casos lo que eso hace es que se pegue la ventana, no que pare la simulación.

Como habría que hacer para que quede pausado pero sin que se caiga el programa?

![capture](https://cloud.githubusercontent.com/assets/10112117/19498359/cc0abb3e-9566-11e6-9ae2-e239bb3c7129.GIF)

**Comment by Hernan4444** [comment]
@Kitaps si lo que quieres es pausar la simulacion, no se puede de esa forma, la única opción es detener toda acción de los ticks pero estos se seguirán ejecutando. En el caso de que quieras hacer eso para mostrar los datos, te sugerimos usar sys.exit e imprimir los datos en consola.
Saludos!!

**Comment by Kitaps** [comment]
Pero cuando hago sys.exit no sigue ejecutando, me queda igual de mal que con las otras maneras.

Al final lo que hice fue dejar las cosas que quiero que haga antes. 
Poner un sleep corto 
y que de ahí se cierre solo.
Estará bien eso?

![capture](https://cloud.githubusercontent.com/assets/10112117/19500488/23c467dc-9574-11e6-814b-4774ce8906b6.GIF)

**Comment by FernandoPieressa** [comment]
@Kitaps si esta correcto, pero no es necesario el sleep

Ya fue respondido esto con anterioridad en #439

saludos!

**Comment by Kitaps** [comment]
:scream:  Lo siento
