### ISSUE TITLE
Estadísticas de programones

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#45]
Digamos que un usuario únicamente ocupa el juego. Los programones suyos y los demás comenzarán a acumular datos, y se podrá elaborar el ranking por ejemplo. Digamos que Charmander resulta ser el mejor del ranking.
Ahora, si otro usuario comienza a ocupar el juego y pregunta por el ranking inmediatamente, ¿Sigue siendo Charmander el mejor? Es decir, los programones tendrían desarrollo independiente de los usuarios, algo más tipo 'realidad virtual'. ¿O por cada usuario nuevo se espera que comience desde cero una 'historia' del juego?

**Comment by nivek0o0** [comment]
Yo entiendo que el ranking es histórico, independiente del jugador que esté jugando. Si se resetea cada vez que se registra un jugador, no habría ranking hasta que alguna clase de programon acumule más de 10 batallas, y para eso puede pasar mucho tiempo.
Pero sería bueno que algún ayudante lo aclare.

**Comment by FernandoPieressa** [comment]
Hola! Efectivamente como dijo @nivek0o0 tiene que ser universal independiente del jugador.

Saludos!

**Comment by iqacevedo** [comment]
Hola
Una duda el ranking se hace con las especies de programones, o se hace con los programones como individuos separados?
Por ejemplo si tengo 10 charmanders, se consideran los 10 como una entrada charmander, o cada uno como una entrada charmander por separado?
Saludos!

**Comment by Kitaps** [comment]
tengo la misma duda que @iqacevedo

**Comment by cjgazali** [comment]
El ranking es por 'raza' de programon. Cualquier charmander que pelee suma datos a 'los charmander' y eso afecta el ranking. Está en el enunciado y en otra issue.
