### ISSUE TITLE
Pregunta de materia: Threads

### ISSUE THREAD

**Issue by Gonzalo-Perez** [IIC2233-2016-02/Syllabus#451]
Como podría conseguir el mismo comportamiento para un conjunto de Threads a los cuales les "hago" Join solo usando Threads y Locks?

De antemano, gracias.

**Comment by jgmontoya** [comment]
Hola, 

No entiendo bien a qué quieres hacer. ¿Quieres simular un join sin usar join?

EDIT: Si lo que te interesa saber cómo está implementado el join en python, una de las ventajas de usar un lenguaje _Open Source_ es que puedes ir directamente a ver el código, por ejemplo [acá](https://hg.python.org/cpython/file/3.5/Lib/threading.py) está el código de `threading.py` (sí, el que se usa cuando haces `import threading` en tu programa) en particular en la linea 1022 empieza la definición del método join.

Saludos!

**Comment by ndleyton** [comment]
Hola Gonzalo, te refieres a que la actividad 'pare' hasta que se resuelva un thred en específico? 
En cuyo caso tienes que hacer que los procesos sean **Threads** y a lo que quieran acceder tenga un `Lock()`.

Por ejemplo tienes clases que quieren acceder a una matriz y esta la almacenan como self.matriz cada uno. La matriz contendrá un `self.lock = threading.Lock()` y este es el que utilizaremos para controlar la sincronia de los threads, ya que al querer utilizar la matriz, utilizaremos

> `with self.matriz.lock:
>        #tilización de matriz`

De esta manera, cuando un objeto de esta clase quiera acceder a la matriz, esta tendrá que esperar a que los otro objetos terminen _lo suyo_ con la matriz, debido al **lock**

**Comment by Gonzalo-Perez** [comment]
Hola,
Digamos que tenemos N threads creados.
Inmediatamente después de hacerles start(), me gustaría que N-1 Threads funcionaran al mismo tiempo (corrieran en paralelo) y que el Thread número N solo empezara una vez que todos los otros Threads ya han terminado.
Por lo que vi en la documentación lo podría hacer usando la función wait_for para el Thread número N entregandole como variable booleana algo así como "All_other_threads_have_finished" la cual podría calcular verificando con is_Alive para cada Thread de los otros N-1 Threads.
Les parece correcto? habrá alguna forma más eficiente de hacerlo?

Gracias por sus respuestas!

**Comment by fvr1** [comment]
Hola! 
@Gonzalo-Perez según tu primera pregunta asumí que quieres evitar el uso de `join`... pero después en la segunda pregunta lo que quieres hacer se puede realizar fácilmente usando `join`. Entonces creo que no entendí muy bien la pregunta en general...
Sin embargo, se puede resolver tu segunda pregunta (usando `join`) al iniciar todos los N-1 threads y luego hacer join a esos N-1, y después puedes iniciar el thread _n_. Por ejemplo:

``` python

all_threads = [Threads(target=func) for _ in range(N)]
for _ in range(N-1):
    all_threads[ _ ].start()  # inicias todos los threads

for _ in range(N-1):
    all_threads[ _ ].join()   # luego haces join

all_threads[N].start()
```

**OJO:** no puedes incluir el `.join()` en el primer `for` ya que al comenzar el primer thread, el programa principal esperaría hasta que el primer thread terminara, luego comenzaría el segundo thread. 
Prueba este código utilizando esas funciones con un `sleep` que aparecen en el material de clases y vas a entender mejor a qué me refiero jajaja.

**Comment by Gonzalo-Perez** [comment]
Gracias !

**Comment by jtagle2** [comment]
@Gonzalo-Perez, para que privarte de los join si ya los implementó alguien D: Ahora, si quieres hacer lo que dices (el n-ésimo thread espera a todos los anteriores), puedes hacer que tu thread almacene 2 cosas: Un lock propio que se pide apenas empieza el run y se libera una vez que se termina el run, y por otro lado una lista que posea todos los locks de los otros threads que se debe pedir que hayan terminado, y para ejecutar el run debe pedir tambíen los locks de dicha lista.  Es bastante parecido a lo que dices, pero no se almacena un thread dentro de otro para corroborar si está vivo, sino solo almaceno su lock. Soluciones hay varias, pero la que te propuso @fvr1  es la más adecuada.
Saludos!
