### ISSUE TITLE
Pregunta de materia: Herencia

### ISSUE THREAD

**Issue by Gonzalo-Perez** [IIC2233-2016-02/Syllabus#452]
Si tengo una clase E que hereda de las clases C y D, las cuales heredan a la vez de las clases A y B respectivamente, como podría hacer acceder a algo de la clase B y ejecutar el init de la clase B SIN CAMBIAR la clase A (la cual no tiene un super().**init**() ni ningún otro super)?
Estoy pensando que la clase E se define de la siguiente forma (con ese orden de herencia ya que preferiría no intercambiar C con D).

Class E(C,D):

Para C y D sería así:

Class C(A):

Class D(B):

De antemano, gracias !

**Comment by ndleyton** [comment]
Hola Gonzalo, a qué te refieres con 

> Sin cambiar la clase A

No quieres llamar su init o solamente no modificar esta?

De todos modos, esto es posible ocupando **decoradores** en la clase, con estos puedes agregar o quitarle cosas al _diccionario_ de la clase e incluso puedes acceder a sus _bases_ de las cual hereda por medio de `__bases__`

**Comment by Gonzalo-Perez** [comment]
Hola,
Sin cambiar ni tocar absolutamente nada de la clase A (ni siquiera agregando decoradores).
Estoy pensando en un caso en que la clase A se encuentra en un módulo separado que solo puedo importar.

De antemano, gracias !
