### ISSUE TITLE
Dudas sobre Raza Orco

### ISSUE THREAD

**Issue by mrafaeli** [IIC2233-2016-02/Syllabus#453]
Hola, tengo unas dudas con respecto a como actuan los orcos al momento de buscar objetivos para atacar:
-Se busca el objetivo mas cercano o puede ser al azar entre las unidades enemigas?
-Si se busca el enemigo más cercano,  ¿van todas las unidades orcos a atacar la misma unidad o una vez que es targeteada por una unidad las otras eligen la siguiente más cercana?

Por último, si destruyo el templo del enemigo gano inmediatamente y se para la simulacion?

**Comment by ManuelSIlvaCav** [comment]
Hola!
1) Enunciado!!
2) No se especifico si tienen que atacar todas o solo la mas cercana, queda a tu criterio como abordar esto especificando en el README la aproximación!
3) Cuando se destruye el templo se tiene que terminar la simulación, recordar de imprimir las estadísticas!!.

Saludos
