### ISSUE TITLE
Enunciado

### ISSUE THREAD

**Issue by lefischer** [IIC2233-2016-02/Syllabus#454]
1) cuando se activa la fuerza en los aldeanos
2) como se distribuyen los poderes para cada dios, es aleatoriamente cuando se inicia la simulacion?
3) no estiendo que hay que hacer con el testing

**Comment by Hernan4444** [comment]
@lefischer 

1) la fuerza es un atributo del aldeano, se nace con el y dependiendo del valor se distingue si puede llevar más oro o el estándar.
2) #390
3) debes realizar un programa testing donde compruebes/testees que tus métodos y funciones dan el resultado esperado (al menos un 50% de ellos deben ser.testeado).  Con el fin de que aprendan a programar testeando sus metodos.
Por ejemplo si tienes un método para quitar vida,  un testeo seria aplicar ese método con X cantidad y luego haces un iqual entre la vida del objetivo y vida_máxima - X,  si el test funciona significa que tu método cumple lo que esperabas.
Saludos!!!
