### ISSUE TITLE
Duda enunciado excepciones

### ISSUE THREAD

**Issue by jisilvamc** [IIC2233-2016-02/Syllabus#455]
Hola, tengo una duda sobre el enunciado: ¿qué es lo que se va a evaluar exactamente de las excepciones? Me parece que se va a revisar el tema de que sean excepciones que sirvan para un error específico que pueda suceder, pero no me queda claro si se espera que tratemos de usarlas o no. Por ejemplo, si en todo mi código hay una sola excepción y está bien hecha, ¿tendría todo el puntaje? ¿O hay que tratar de usar hartas excepciones?
Gracias

**Comment by Hernan4444** [comment]
Hola
#440 
Saludos!!
