### ISSUE TITLE
Qué pasa si se destruye el templo antes de cumplir el objetivo?

### ISSUE THREAD

**Issue by sormazabal** [IIC2233-2016-02/Syllabus#456]
En muchos casos mis monos destruyen el templo enemigo antes de "crear 10 mascotas", por ejemplo. Pasa algo si "ignoran" el cumplir el objetivo y ganan de igual manera?

**Comment by Hernan4444** [comment]
@sormazabal asi es, ganan de igual manera. Lo que determina todo al final es la destrucción del edificio, los objetivos son solo un requisito para el uso del poder.
Saludos!!
