### ISSUE TITLE
Pregunta de materia: Threads

### ISSUE THREAD

**Issue by Gonzalo-Perez** [IIC2233-2016-02/Syllabus#457]
Quisiera poder correr un Thread más de una vez (ejecutar su método run más de una vez).
Cual sería una forma correcta de hacerlo? (que no tenga "malas prácticas")
Creo que esto sería interesante si quiero realizar una misma acción/proceso/función muchas veces y de forma paralelizada por lo que no sería eficiente tener que volver a crear un Thread cada vez que quiero realizarla.
Estoy equivocado al pensar que es poco eficiente estar creando los Threads todo el tiempo?
Vi esto en internet y quedé con las mismas dudas:
http://stackoverflow.com/questions/29692250/restarting-a-thread-in-python

De antemano, muchas gracias !

**Comment by Gonzalo-Perez** [comment]
Aprovecho de agregar esta duda más precisa:
Que pasa con un Thread una vez que muere? Todos los recursos que utilizó/utiliza (memoría y tiempo de procesamiento) se "limpian" como si nunca hubiera existido?

De antemano, gracias !

**Comment by fgvenegas** [comment]
Lamento no haber visto esta issue! 
Tal vez lo que publique en #488 puede servir un poco como respuesta a tu duda inicial!
