### ISSUE TITLE
Duda testing tarea

### ISSUE THREAD

**Issue by sebacruzd** [IIC2233-2016-02/Syllabus#458]
Hola.

El testing de la tarea es para que el corrector pueda ver que las funciones / métodos funcionan correctamente? 
Qué tan importante es en la ponderación de la corrección?

Gracias de antemano.

**Comment by Hernan4444** [comment]
@sebacruzd no necesariamente, es para que aprendan a programar testeando sus métodos / funciones.
Sobre la ponderación, esa es información privada,  solo te puedo recomendar realizarla, aun hay tiempo.
Saludos!!!

**Comment by sebacruzd** [comment]
Gracias!
