### ISSUE TITLE
heroe cristian

### ISSUE THREAD

**Issue by lefischer** [IIC2233-2016-02/Syllabus#459]
hola

debe seguir una unidad enemiga por un tiempo determinado a una distacia determinada o despues de que se inicia la activacion del poder y el tiempo llega a cero las unidades enemigas que se encuentran a una distancia determinada son compiadas.
durante el rutual, el heroe puede atacar?

**Comment by criscv94** [comment]
Hola!
Cuando yo (cristian) empiezo a realizar mi ritual, debo mantenerme siempre a cierto rango mínimo de la unidad objetivo a convertir. Por lo tanto, si el la unidad objetivo se alejo, debo seguirlo. Respecto al ataque, es decisión de ustedes si yo podré atacar mientras realizo mi ritual o no, recuerda especificarlo en el readme!
Saludos
