### ISSUE TITLE
Duda Heroes

### ISSUE THREAD

**Issue by bvfernandez** [IIC2233-2016-02/Syllabus#460]
Hola! Quería saber a qué se refiere el enunciado en el 7.5 cuando dice "estas unidades son superiores a cualquier soldado"... osea es superior a cualquier guerrero? puede tener un arco por ejemplo? o significa que su rango,velocidad de movimiento, puntos de daño son mayores que cualquier guerrero, arquero, mascota?

**Comment by ManuelSIlvaCav** [comment]
Hola!
Esa descripción se hizo a modo introductorio para los héroes, efectivamente estos tienen mayor hp, puntos de ataque y velocidad, pero el rango no se definió, por lo que queda a tu criterio. Por ejemplo, los héroes humano y orco pueden ser rangos y el de muertos cuerpo a cuerpo, recuerda especificar en el README

Saludos!

**Comment by bvfernandez** [comment]
@ManuelSIlvaCav muchas gracias!!!
Eso si tengo otra pregunta sobre los heroes  :) :su tasa de invocacion es distinta para cada uno(o sea que tendriamos que pedir dos inputs al inicio de la simulación)?

**Comment by ManuelSIlvaCav** [comment]
Hola!
Creo que esta parte no se especifico, pero idealmente deberían ser dos inputs para cada héroe con tasas distintas. Especificar de todas formas como se abordo :D 
Saludos!
