### ISSUE TITLE
Dudas sobre Testing

### ISSUE THREAD

**Issue by sormazabal** [IIC2233-2016-02/Syllabus#461]
Hola! Tengo varias dudas con respecto al testing.

El enunciado dice que más de la mitad de las funciones deben estar testeadas.

1) Si tengo una clase Villager, por ejemplo, y otra HumanVillager(Villager,Human), debo testear el método "walk" de Villager tanto en Villager como en Human villager?
2) Si tengo:

``` python
 def myfunc():
    def myfunc2():
        def myfunc3():
            return True
        return myfunc3
    return myfunc2
```

Basta con testear myfunc() o debo testear cada una de las funciones chicas? Lo digo porque tengo varias funciones para el movimiento de los personajes que se cimientan en funciones más chicas.

3)Para contar las funciones busco por "def" en Pycharm, pero eso me toma los inits también. Hay alguna función de Pycharm para contar el número de funciones?

4) Referente al punto anterior: los inits también hay que testearlos?

**Comment by ManuelSIlvaCav** [comment]
Hola!
Primero que todo, la idea del testing es que uds. prueben las distintas funciones que implementan y chequear que efectivamente retornen lo esperado. En cuanto a tus dudas;
1) Trata de chequear solo las clases y métodos principales, excepto en los casos que hayas sobrescrito un método, en este ultimo deberás chequear con la clase que hereda.
2) Respecto al punto anterior, tratar de testear las funciones mas importantes de tu programa.
3) A priori no sabría decirte si existe esta función... pero quizás Google te ayude!
4)Los init no se testean !

Saludos!
