### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FranciscoLarach** [IIC2233-2016-02/Syllabus#462]
Hola!
Después de simular un rato, en algunas circunstancias especificas llego a este error!
[Usando el deleteLater()]
"RuntimeError: wrapped C/C++ object of type Orc has been deleted"
Busqué un poco y no entendí tanto del error (Tenia mucho que ver con PyQt).
¿Conocen una explicación un poco mas simple para poder ver en que fallo?
Muchas Gracias de antemano.

**Comment by Hernan4444** [comment]
@FranciscoLarach ese error proviene de acceder a un información (atributo o método) de un objeto que no existe. Esto se produce porque eliminaste un objeto de la interfaz pero tienes a un objeto tuyo (que no perteneces a la interfaz) que todavía tiene referencia al objeto eliminado y al intentar acceder a cualquier dato de él, se produce ese error.
Saludos!!!

**Comment by FranciscoLarach** [comment]
Ok! Gracias!!

**Comment by gebalassa** [comment]
Hola! En mi tarea paso la simulación a la funcion `atacar()` de un guerrero, y cuando desde el guerrero borro la estructura atacada (por ahora el _Templo_) con **.deleteLater()** me lanza ese mismo error. Según yo he borrado todas las referencias al templo (ver la parte final del código) pero me sigue tirando problemas:

```
Traceback (most recent call last):
  File "C:\Users\Gabriel\Desktop\T04_ZONADETRABAJO\GuiTesting.py", line 98, in tick
    guerrero.atacar(self)
  File "C:\Users\Gabriel\Desktop\T04_ZONADETRABAJO\MiEjercito.py", line 234, in atacar
    objetivo.deleteLater()
RuntimeError: wrapped C/C++ object of type Temple has been deleted

```

El .deletelater() está casi al final, cualquier duda con el código me preguntan. El parámetro "sim" es la simulación en sí. 

EDIT: Codigo censurado.

**Comment by gebalassa** [comment]
Perdón por el error. Dejo entonces lo que considero relevante:

``` python
objetivo.hide()
 objetivo.deleteLater()
if valor == 1:
    del sim.t2_guerreros[index]
 elif valor == 2:
    del sim.t2_mascotas[index]
elif valor == 3:
    del sim.t2_aldeanos[index]
elif valor == 4:
    del sim.t2_cuarteles[index]
elif valor == 5:
    del sim.t2_torretas[index]
elif valor == 6:
    sim.t2_temple = None
```

**Comment by Hernan4444** [comment]
@gebalassa hola!!
Primero, censuré tu código, por reglas del curso no se puede subir código personal a las issue, simplemente avisas que pusheaste tu código y nosotros lo vemos de forma particular puesto que compartir código puede ser considerado como copia.

Sobre tu error, lo mas probable es que un guerrero tuyo de tu mismo equipo o el mismo guerrero tenga todavía la referencia al templo (puesto que solo borras la referencia del equipo enemigo) y cuando lo intentan volver a eliminar se encuentras con que ya fue eliminado

hint: cuidado con los try y except
Saludos!!!

**Comment by gebalassa** [comment]
Al final el problema yacía en un error del eliminador. 

Gracias de todas maneras y también se agradece el hint, pues me tiraba otro error!
