### ISSUE TITLE
Tamaño mapa

### ISSUE THREAD

**Issue by Jaluco** [IIC2233-2016-02/Syllabus#463]
Buenas,
Para crear un edificio en el mapa me quiero asegurar de que no sea construido fuera o con una porcion fuera del mapa. ¿Qué método tengo que usar para poder conseguir el largo y el ancho del mapa?

**Comment by ceyzaguirre4** [comment]
No soy ayudante, pero lei en otro issue que puedes asumir que el tamaño del mapa es de 1024x680
