### ISSUE TITLE
Duda enunciado Bonus

### ISSUE THREAD

**Issue by Gonzalo-Perez** [IIC2233-2016-02/Syllabus#464]
En el enunciado sale escrito:
"Hint: Si ocurre algún daño físico se ve sangre, si alguien muere, aparece una tumba, etc. Para esto,
cuentan con el método:"
Pareciera que faltó algo despues de los dos puntos. Hay alguna recomendación sobre el bonus que no aparezca ?
Con respecto a la evaluación del Bonus, me imagino que si queda "a criterio del ayudante" tenemos cierta libertad para agregar cosas a la simulación o solo debemos restringirnos a lo que sale de la sangre y las lápidas?
Si quisiera agregar sonido al juego por ejemplo, eso sería contado en la bonificación?
Si quisiera agregarle sonidos que librería/método recomendarían y de ser incluído en la evaluación, cuales serían permitidas?

De antemano, gracias!

**Comment by aaossa** [comment]
> En el enunciado sale escrito:
> "Hint: Si ocurre algún daño físico se ve sangre, si alguien muere, aparece una tumba, etc. Para esto,
> cuentan con el método:"
> Pareciera que faltó algo despues de los dos puntos. Hay alguna recomendación sobre el bonus que no aparezca ?

#426

**Comment by Gonzalo-Perez** [comment]
Gracias ! y con respecto a lo del sonido?

**Comment by Nebula2028** [comment]
+1 a lo de los sonidos.
Alguna forma fácil bonita y rápida de hacer que la interfaz ~~grafica~~ emita sonidos, digase al ocurrir ciertos eventos ?
