### ISSUE TITLE
Sprites girados

### ISSUE THREAD

**Issue by mcorreaiz** [IIC2233-2016-02/Syllabus#465]
Algunos sprites (assets) vienen girados, como por ejemplo el villager 2 y el human distance. No tengo que lidiar con eso dentro del programa, cierto? Simplemente edite (rotacion en 180 grados) el archivo .png desde un editor de imagenes y asi lo arregle. Es una solucion valida, se espera que desde dentro del programa los rotemos?

Gracias

**Comment by flobarrios** [comment]
No hay problema con eso!
