### ISSUE TITLE
Agregar imagenes o texto sin tocar la gui

### ISSUE THREAD

**Issue by Gonzalo-Perez** [IIC2233-2016-02/Syllabus#466]
Veo que con el método add_entity puedo agregar imágenes al juego pero como podría agregar (sin tocar la gui claro) texto ligado a una variable y que se actualice?
Agregue una imagen (una entity) a la cual le agregué un Qlabel pero no logro hacer que se actualice.

De antemano, gracias !

**Comment by Hernan4444** [comment]
@Gonzalo-Perez lamento decir que no se puede agregar texto, no implementamos la gui para tal peticion :c. La opcion que te podemos ofrecer es crear imágenes con los textos y estos los añades como entity. https://es.cooltext.com/ es una pagina que genera logos sin fondo por si consideras esta idea.
Saludos!!!
