### ISSUE TITLE
Creación de aldeanos

### ISSUE THREAD

**Issue by Gonzalo-Perez** [IIC2233-2016-02/Syllabus#467]
En el enunciado sale que cuando un aldeano muere una raza deja de producir tropas (unidades de combate) para producir un aldeano.
En ese caso hay que detener/pausar la producción de tropas de forma inmediata o el templo puede terminar de producir,por ejemplo, la mascota que estaba generando antes de pausar la producción de mascotas y comenzar a producir un aldeano???
En otras palabras, tengo que guardar el tiempo que llevaba produciendose la mascota, producir el aldeano y luego seguir produciendo la mascota desde el tiempo en el que estaba??

De antemano, gracias !!!

**Comment by jgmontoya** [comment]
Hola,

Ambas formas que planteas son válidas por lo que queda a tu criterio.
Recuerda especificar tu decisión en el README.

Saludos!
