### ISSUE TITLE
Override métodos Herencia

### ISSUE THREAD

**Issue by Gonzalo-Perez** [IIC2233-2016-02/Syllabus#468]
Si quiero sobrescribir un método que fue heredado de una clase padre, la siguiente manera que propongo para hacerlo esta correcta? (lo probé y veo que funciona pero me gustaría saber si esta es la forma "ideal" de hacerlo, es decir si no incurro en una mala práctica)

``` python
class A:

    def __init__(self):
        pass
    def f(self):
        print("f de A")

class B(A):

    def __init__(self):
        super().__init__()

    def f(self):
        print("f de B")
```

Al ejecutar el siguiente código:

``` python
>> b=B()
>> b.f()`
"f de B"
```

El output es el print en consola de "f de B"

Aprovecho de preguntarles lo siguiente:
Cómo hacer para publicar códigos y que se vean bien (con los colores del código como en el issue #431) en estos issues (por alguna razón cuando apreto el botón de add code <> no agarra bien las clases).

De antemano, gracias !

**EDIT aaossa:** Agregué el formato de código correcto. Dale una mirada para que veas bien como usarlo :grin:

**Comment by aaossa** [comment]
> Si quiero sobrescribir un método que fue heredado de una clase padre, la siguiente manera que propongo para hacerlo esta correcta? 

Sobre la sobreescritura, no hay problemas con que lo hagas así. Recuerda que los métodos deben recibir los mismos argumentos (e idealmente retornar lo mismo) y que si quieres llamar al método de la clase padre debes usar `super`. Por ejemplo, usando la gui de la Tarea 4:

``` python
# entity.py
# Clase Building (hereda de Entity)
def updatePixmap(self):
        if self.in_construction:
            self._base_image = ["buildings",  self.k + "_construccion.png"]
        else:
            self._base_image = ["buildings",  self.k + ".png"]
        super().updatePixmap()
```

Ambos métodos comparten el nombre y reciben los mismos argumentos. Además, aquí se usa `super` para llamar al método original de `Entity` (en `entity.py`).

> Cómo hacer para publicar códigos y que se vean bien (con los colores del código como en el issue #431) en estos issues (por alguna razón cuando apreto el botón de add code <> no agarra bien las clases).

Lo que hace el botón de code es agregar dos _backticks_ (```), lo que funciona bien cuando quieres escribir código en la misma línea que el texto (por ejemplo: "Tienes que hacer `print("Hola")`"). Para escribir código en multiples líneas tienes que escribir **3 _backticks_ al comienzo y 3 al final del código**. Además, si inmediatamente después de los 3 _backticks_ iniciales escribes el lenguaje que usarás, GitHub le agrega el _syntax highlighting_ (los colores) apropiado para que sea más legible:

``` python
class A:

    def __init__(self, *args, **kwargs):
        pass
```

El código usado arriba (lo puedes ver en el mail que te llega con esta respuesta):

``````
```python
class A:

    def __init__(self, *args, **kwargs):
        pass
```
``````
