### ISSUE TITLE
Extracción de oro en la(s) mina(s)

### ISSUE THREAD

**Issue by Gonzalo-Perez** [IIC2233-2016-02/Syllabus#469]
Debemos asumir que los aldeanos van a extraer oro solo de la mina que le corresponde a su ejército/equipo según aparece en el archivo mapa.csv?
Es decir no pueden ir a sacar oro de la mina del oponente?

De antemano, gracias !

**Comment by jgmontoya** [comment]
Hola,

Este aspecto queda a su criterio. Recuerda mencionar explícitamente tu decisión en el README.

Saludos!
