### ISSUE TITLE
Decoracion con Entity

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-02/Syllabus#470]
Hola, hice unas imagenes para decorar el juego, he estoy usando entity para mostrarlo, pero por alguna razón (creo que debe ser algo del path), no me lee la imagen.
Podrian revisar mi codigo y ver que esta mal ?
Esta en una funcion que se llama revisar_efectos en el main
Muchas gracias de antemano !

**Comment by Hernan4444** [comment]
@Diiru estaba revisando tu código y en el método `revisar_efecto` llamas al método `add_decoration`. Estoy suponiendo que ese método no es creado por ti sino uno que estaba en la gui que no fue explicado en el enunciado. No les mencionamos ese método porque no funciona como nosotros esperamos, es por ello que ustedes deben crear una nueva entidad y a ella agregarle la imagen que quiera.

Cuando crees tu nueva entidad, si todavía no se muestra la imagen, avisanos y vemos lo que sucede con el path.
Saludos!!

"Warning: un except sin especificar es mala practica y también puede jugarte en contra a la hora de debuggear"

**Comment by Iruretagoyena** [comment]
@Hernan4444 Oka, muchas gracias !! Seguiré tratando

Warning: Jeje si, como no conocía el método no sabía que iba a pasar, pero lo que he hecho hasta ahora es hacer : 
1. try
2. except(s) que probablemente saldrá(n)
3.except general para evitar que se me caiga

**Comment by Hernan4444** [comment]
Warning: el problema de eso está en tu punto 3, un except general para evitar que se caiga es una mala practica, cuando uno programa debe saber bajo que errores se enfrenta y con ese except general omitirás algun posible error que no te diste cuenta.
Saludos!!

**Comment by Iruretagoyena** [comment]
@Hernan4444  Mish, igual tienes razón, pero (y para saber, no estoy discutiendo) para efectos de una entrega, no sería mejor "parchar" el programa ? Total, ya cubrí las que me estaban saliendo y si las dejara sin el general me expongo a esa pequeña posibilidad de que pase algo que a mi no me paso y le pase al ayudante, afectando mi nota. O no ?

**Comment by Hernan4444** [comment]
@Diiru entiendo totalmente tu punto pero a este nivel del curso, nosotros esperamos que un alumno programe sabiendo en donde estan sus falencias, en caso de "parchar" el codigo, no sabras bajo que error llegaste a eso y ademas ¿como podremos darte feedback de que tu programa no funciona en tal parte?
Saludos!!!
