### ISSUE TITLE
QProgressbar

### ISSUE THREAD

**Issue by lfbesa** [IIC2233-2016-02/Syllabus#473]
Alguien me podría explicar por que me sale este error?
RuntimeError: wrapped C/C++ object of type QProgressBar has been deleted
En ningún punto uso deleteLater ni borro ningún atributo, lo único que uso es hide(). ¿Las barras de progreso se borran automáticamente en algún punto?

**Comment by lfbesa** [comment]
Ojalá si algún ayudante pudiera ver mi tarea para ver por qué es

**Comment by Hernan4444** [comment]
@lfbesa revisa linea 115 modulo demo.py, ahi utilizas deleteLater() y lo mas probable es que haces referencia a la barra de vida de ese soldado (haciendo soldado.health -= algo) y ahí ocurre el error.
Saludos!!
Warning: cuidado con PEP8

**Comment by lfbesa** [comment]
Muchas gracias.
