### ISSUE TITLE
Testing: Como probar funciones que requieren input?

### ISSUE THREAD

**Issue by Nebula2028** [IIC2233-2016-02/Syllabus#474]
Bueno eso, estaba cachando que si uno trata de testiar una función que dentro de ella requiere recibir inputs del usuario, esto no se puede ni con setUp ni en los test_x ya que se ejecuta la funcion y se queda esperando por siempre por los input del usuario (tampoco deja escribir en la consola de testing para que pueda seguir corriendo)

Como lo hago?
ej: 

``` python
def funcion_ejemplo(self):
       num = input("Ingrese un numero")
   return num
```

como podria hacer por ejemplo un assert.isInstance(funcion_ejemplo(), int) ???

**Comment by aaossa** [comment]
Hola, el enfoque que debes darle a las funciones que piden input es pensar que la función trabaja "dado un input", por lo tanto, es mejor capturar el input fuera de la función y pasarselo como parámetro.

Esta issue de hace un par de semestres entrega una buena respuesta y un buen ejemplo: https://github.com/IIC2233-2015-2/syllabus/issues/225
