### ISSUE TITLE
Sprites tanques

### ISSUE THREAD

**Issue by JaimeGo** [IIC2233-2016-02/Syllabus#478]
Hola! Estaba revisando la tarea y, si entiendo bien lo que hay que hacer, se requieren cuatro tipos de tanques distintos y varios tipos de balas. Tenía algunas preguntas respecto a eso.

1) Para los tanques enemigos, ¿la idea es ocupar el mismo sprite en distinto color, dependiendo del tipo de tanque? Supongo que así es, pero quería preguntar por si acaso.
2) ¿Hay que ocupar distintos sprites para cada tipo de bala? ¿O basta con colores distintos?
3) Los tanques enemigos, ¿pueden mover el cañón? O sea, ¿necesitan que el sprite del cañón esté por separado? Si es así estoy seguro que va a ser muy difícil encontrar un sprite adecuado. Para tantos variedades de tanques sólo encontré cañones fijos.
4) ¿Pueden sugerir páginas donde se pueda encontrar los sprites que piden? He encontrado algunas, por supuesto, pero la variedad de tanques que ofrecen es bastante limitada. 

Mi idea es ocupar un sprite similar al del enunciado, con distintos colores, para los tanques enemigos, y uno diferente para el tanque principal, que permita mover el cañón. Otros sprites que ocuparía serían: moneda, escudo, bala ralentizante, bala explosiva, bala penetrante, bombas (¿qué hacen las últimas? No se explica). ¿Está bien así? 

Gracias!

**Comment by FernandoPieressa** [comment]
Hola! Respecto a tus dudas:

1) Queda a tu criterio los sprites mientras se note la diferecia, si quieres cambias el color, o si quieres lo cambias completamente

2) A criterio tuyo mientras se note la diferencia

3) Los enemigos pueden tener cañon estatico O por separado, queda a criterio. Sin embargo el tanque principal tiene que poder mover el cuerpo y el cañon por separado.

4) La verdad es que es muy libre y no es que tengamos una pagina especial para sacar sprites de tanques. Mi mejor recomendacion seria buscar Tank Sprites! Siempre le puedes hacer una pequeña modificacion a las imagenes con paint o photoshop para que queden como deseas.

Lo que hacen las bombas se encuentra en el punto 3.2.4.

Tienes que tener en cuenta que "Sprites" Se refiere a un conjunto de imagenes que simulan movimiento, por lo tanto los power ups no son sprites. Si te referias a en total con imagenes, no te olvides que faltan todas las que sean escenario! (Paredes, portal, tienda, etc..)

Saludos!

**Comment by jgmontoya** [comment]
Por favor recuerda dejar explícito en el readme cuales fueron tus decisiones al respecto.

**Comment by HenryBlairG** [comment]
En el enunciado dice que hay que observar al menos 3 estados de movimiento, sin embargo me surge la duda de si esos estados deben ser estrictamente mostrados en las ruedas o podemos buscar una manera alternativa de hacerlo, por ejemplo que el tanque vaya dejando marcas de sus orugas o algo por el estilo. ¿Es estrictamente necesario el tema de las ruedas para mostrar su movimiento? 🤔

**Comment by Iruretagoyena** [comment]
@HenryBlairG Adhiero a esta pregunta. Es necesario mostrar el movimiento con ese cambio de ruedas ? O podemos hacerlo de otra forma ? (e.g. rastro)

**Comment by flobarrios** [comment]
@HenryBlairG @Diiru deben mostrar el cambio de ruedas si o si. Si además quieren incluir el rastro bacán!
