### ISSUE TITLE
[Tarea 5] Dudas varias

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#479]
1) No entiendo lo que caracteriza al tanque círculo. Favor de explicar desde cero.
2) Las balas propias pueden romper paredes destructibles? depende del tipo de bala? a nuestro criterio?
3) en los controles eje mouse no se espera que dos teclas sean movimiento en diagonal?
4) el bonus es bonus solamente (no tiene puntaje asignado)? dice “tu juego debe dar la opción de cambiar a dos tipos de controles”...

**Comment by FernandoPieressa** [comment]
Hola! 

1) El tanque circulo funciona asi: digamos que tienes un punto (0,0). El tanque circulo giraria alrededor de este punto con un radio constante definido por ti. Ademas de esto, a traves del tiempo el centro del circulo debe ir cambiando (en este caso el punto (0,0) podria cambiar a (1,1) u otro). Recuerda que debe respetar las paredes y no las puede atravesar!

2) Solo las bombas rompen las murallas destructibles

3)En eje mouse el movimiento no necesita teclas diagonales porque moviento la posicion del mouse empezaria a cambiar el angulo para caminar

4) Se escribio asi en el enunciado, lo de dar la opcion de cambiar es solo si haces el bonus. Recordar que el bonus vale 10% de la nota que tengas, osea si te sacas un 7, el bonus seria de 7 decimas.

Saludos!

**Comment by cjgazali** [comment]
1)
Me encantaría una descripción gráfica :sweat_smile: .
Si hay una pared dentro de su trayectoria circular, ¿qué hace? ¿se detiene, o cambia su trayectoria?
Considerando que no es necesario que su cañón apunte independientemente de su movimiento (#478), entonces estaría apuntando siempre en la dirección tangencial a la circunferencia que describe, en uno de los dos sentidos, y dispararía sólo si me cruzo por al frente suyo. ¿Correcto?

5) Tengo una imagen de tanque que está fantástica pero no se le ven las ruedas. ¿Será problema que no se vean los 3 estados distintos de movimiento que nos piden? Pienso usarla solo para el tanque principal, y quizás una con el mismo 'problema' para el tanque grande. Para los demás, tengo unos igualitos a los del enunciado con varias posiciones de ruedas.

**Comment by FernandoPieressa** [comment]
1)![dfgdgfgd](https://cloud.githubusercontent.com/assets/13782155/19630092/b203acea-9959-11e6-8df7-d981a03d2d56.png)

(Perdon la imagen fea pero en estos momentos no tengo ningun programa bueno para imagenes)
Pero como veras, primero el tanque ira por el circulo negro cuando su centro es el punto P1, y despues cuando el centro cambie al P2, la trayectoria que seguira el tanque sera la roja, sin embargo no se puede teletransportar al otro recorrido, es decir que tienes que buscar como hacerlo fluido el cambio de camino de un circulo a otro, y eso queda ya a criterio tuyo. Respecto a que hace si toca una pared, la idea es que no se quede pegado, podrias por ejemplo hacer que cambie el sentido del recorrido. Con lo del disparo de la bala, efectivamente es lo que estas diciendo, apuntara a la direccion tangencial a la circunferencia que describe y disparara si cruzas al frente.

5) Tiene que tener minimo 3 estados, aunque tampoco es tan dificil ponerle marcas a las ruedas de tu dibujo o algun detalle con el que logres ver los distintos estados al moverse ( tipo los del ejemplo entregado en enunciado)

**Comment by jgmontoya** [comment]
Hola,
Para complementar un poco la respuesta de @FernandoPieressa respecto al movimiento del tanque círculo, quizás sirva hacer una analogía con el movimiento de la luna. 

La luna describe órbitas en torno a la Tierra, mientras que a su vez la Tierra se desplaza.
En este caso la luna sería el tanque-círculo y la Tierra sería el punto X que va cambiando de posición.

Saludos!

**Comment by cjgazali** [comment]
@FernandoPieressa muchas gracias!

5) ...el problema es que no se le ven las ruedas. Es un tanque más seguro 😄 . Tendría que buscar otro tanque que se le vean las ruedas para hacer tres estados distintos, o tendría que hacerle al mío unas marcas extrañas que no tengan ningún sentido físico pero que se vea como si estuviera haciendo una marca sobre las ruedas... que no se ven...

**Comment by domingo-valdes** [comment]
Me queda una duda con respecto al bonus. No hace sentido que con los controles según el eje del mouse uno pueda moverse a los lados. Es difícil explicarlo por escrito, pero puedo decir que el movimiento del tanque queda completamente determinado por el uso de las flechas de arriba y abajo. Los movimientos hacia los lados los genera el uso del mouse (al ser usado con las teclas antes mencionadas).
