### ISSUE TITLE
sprite tanque

### ISSUE THREAD

**Issue by smargozzini** [IIC2233-2016-02/Syllabus#480]
![captura de pantalla 2016-10-23 a las 20 23 36](https://cloud.githubusercontent.com/assets/14154209/19630316/a572d83e-995e-11e6-8cfc-6daa100ce91f.png)

No entiendo lo que quiere decir esta parte del enunciado, seria tener dos imágenes una de la base con los tres estados de movimiento y otra del cañón la cual las agregamos por separado a la interfaz gráfica?
Lo pregunto ya que ya tengo la base y el cañón por separado pero será mejor hacer varias fotos diferentes con el cañón apuntando a diferentes posiciones o simplemente se puede agregar el cañón por separado apuntando a donde uno quiera?

**Comment by jgmontoya** [comment]
Hola, 

Se refiere a lo que dices de tener dos imágenes.
De esta manera bastará con rotar la imagen correspondiente al cañón para mostrar que se apunta en distintas direcciones (en particular en la dirección en la que se encuentre el mouse en ese momento).

Saludos!

**Comment by smargozzini** [comment]
ok muchas gracias!

**Comment by narierao** [comment]
esto cuenta unicamente para el bonus no?, ya que basicamente segun lo que entiendo, solo podemos movernos en cuatro direcciones o no?

**Comment by FernandoPieressa** [comment]
No, lo necesitas sin el bonus, puedes hacerte una idea del porque viendo este juego como ejemplo http://www.notdoppler.com/toytankarena.php

El control de esa pagina es el control deseado sin bonus.

Saludos!
