### ISSUE TITLE
Threads en tarea 5

### ISSUE THREAD

**Issue by Riarrieta** [IIC2233-2016-02/Syllabus#481]
Hola! ¿Tienen alguna sugerencia sobre en que parte de la tarea utilizar threads? Se me ocurre que para calcular el estado del programa en cada tick se utilizen varios threads para repartir el trabajo (por ejemplo que cada tanque sea un thread), pero no se si habrá una gran diferencia en cuanto a velocidad de calculo. Si lo hiciera así, ¿tendría que hacer wait/join al final de cada tick para evitar que los threads se descordinen, o existe una mejor forma de hacerlo?

Saludos

**Comment by FernandoPieressa** [comment]
Hola!!
Hay una gran cantidad de threads en la tarea, tiempos, enemigos, powerups, balas, bombas, etc...

Como sugerencia podrías estudiar QThreads o QTimers para ver como manejar los threads en conjunto con la interfaz de una buena manera.

Saludos!

**Comment by fgvenegas** [comment]
Hola!
Recomendación personal: QTimers
Saludos
