### ISSUE TITLE
Cómo hago que el juego no se pegue?

### ISSUE THREAD

**Issue by sormazabal** [IIC2233-2016-02/Syllabus#482]
Hola!
Tengo un thread para el tanque del jugador y un thread para las balas. Eso sí, cuando echo a andar el juego, disparo y luego avanzo con el tanque, se me queda pegado el juego. En el caso de que no se queda pegado totalmente, se pega un momento y luego se despega cuando el tanque y la bala ya avanzaron. Siento que debo estar manejando mal los threads de alguna forma que vuelve a mi programa menos eficiente y por eso se pega. 
Hay alguna forma óptima de manejar este problema?

**Comment by sormazabal** [comment]
A lo anterior le sumo una nueva duda:
-Se puede lanzar más de una bala a la vez?

**Comment by jtagle2** [comment]
Respecto a lo de threads, como no puedo ver tu código (no haz hecho ningún push), no sabría decirte que estás haciendo mal o si hay algo ineficiente. Lo que si te puedo decir, es que como dijo @fgvenegas en #481 , te recomiendo usar QTimers en vez de threads, puede ser que con estos te corra más rápido el juego. 
Saludos!

**Comment by FernandoPieressa** [comment]
@sormazabal Respecto a la segunda pregunta, puedes lanzar multiples balas a la vez, obviamente respetando el limite de balas que uno tiene.

Saludos!

**Comment by sormazabal** [comment]
Gracias! Lo arreglé ahora, el problema era que no había puesto time.sleep.
Muchas gracias por su ayuda!
