### ISSUE TITLE
Rotacion De Imagenes

### ISSUE THREAD

**Issue by mraddatz** [IIC2233-2016-02/Syllabus#484]
Que conviene, girar el pixmap que contiene a la imagen o el label que contiene el pixmap? En el caso de girar el pixmap, tendria el problema que como mi pixmap se ajusta al tamaño del label este se veria deformado. Muchas gracias!

**Comment by FernandoPieressa** [comment]
Tecnicamente te estas respondiendo de cual combiene usar jajaj

Exactamente como dijiste, si mueves el pixmap y tienes el tamaño ajustado al label este se va a deformar, por lo tanto combiene rotar el label.
Si estas buscando como hacerlo rotando el pixmap tendras que usar el pixmap no ajustado al label.

Saludos

**Comment by mraddatz** [comment]
Sisi, en verdad tenia más o menos claro que convenia rotar el label, el tema es como. He buscado bastante en internet y hay tantas otras opciones (alternativas al label que no hemos visto en clases como Graphic View) que no se que conviene usar. Asumo que con los contenidos vistos en clase deberiamos poder. De esta forma, como puedo rotar un label o donde puedo encontrar dicha informacion?

**Comment by Hernan4444** [comment]
@mraddatz están libres de usar cualquier contenido dentro de PyQt (Qgraphic View puede ser pero es tu responsabilidad aprender a manejarlos como corresponde) **PERO** cuidando la compatibilidad de s.o.

Por otro lado, en general **tienen** que investigar mucho más sobre interfaz gráfica, la AC es muy básica comparada con lo que hacen en la tarea.

Hint: Revisa la gui de la tarea 4, ahí se rotaban imágenes y puedes jugar un poco con el código para lograr lo que quieres (y si se puede).

**Comment by andresbannuraschultz** [comment]
Me sumo a la duda! Entiendo que el objetivo del curso sea que nosotros seamos capaces de encontrar soluciones por nuestra cuenta, pero la verdad he buscado harto y encuentro respuestas que creo se escapan de lo que esperan que hagamos. Por ejemplo, para rotar un label he visto que ocupan  un "painter" pero no entiendo bien que es ni como funciona. Conviene hacerlo asi? Por otro lado, tambien habia pensado en ocupar varios labels para distintos grados e ir haciendo show y hide a medida que muevo el mouse, el problema de eso es que no seria continuo. Cualquier ayuda o guia se agradece mucho.

**Comment by DiegoAndai** [comment]
Tenía el mismo problema de la rotación que se deformaba, como dice @Hernan4444 , revisen bien la gui de la T04. Para cachar como funciona copien todo lo que hacen **paso por paso!!**  (porque hay algunas cosas que parecen no tener relación con la rotación pero que mantienen la imagen sin deformarse) y borren cosas hasta que deje de funcionar xD, eso hice yo.

**Comment by andresbannuraschultz** [comment]
Buena buena, estaba revisando la tarea anterior como dijiste, y me sirvio para entender algunas cosas, muchas gracias! Aun asi, segun lo que cache, lo que se esta rotando es la imagen y no el label, como decia @mraddatz, y que es lo que yo tambien pensaba hacer. No conviene entonces girar el label si no que girar la imagen? (eso no es lo que se da a entender con el comentario de @FernandoPieressa) Que recomiendan hacer ustedes (ayudantes)?

Ademas aprovecho de preguntarte @DiegoAndai si a ti no se te deforma la foto cuando la giras. Puede ser que me haya faltado copiar algo de la tarea 4, pero lo que a mi me pasa es que la foto gira, bacan, pero el label tiene un tamanho fijo. Ademas tengo que la imagen se ajuste al tamanho del label. Lo pense asi pq me es mas facil controlar los tamanhos de los label en el QtDesigner que cambiar los tamanhos de las imagenes. Quizas eso no conviene. 

Muchas a gracias a todos de antemano, Andres

**Comment by Hernan4444** [comment]
@abannura, no te podemos recomendar ninguno puesto ambos caminos son totalmente factibles y correctos, puedes rotar el label (buscando los comandos que hagan eso) o rotar el pixmap asegurándote de ajustar el tamaño del label (buscando los comandos que hagan eso). El problema de @mraddatz es que el tenia un pixmap ajustado al label así que obviamente no le convenía rotar el pixmap
Saludos!

**Comment by andresbannuraschultz** [comment]
Yo tengo el mismo problema, uso setSacaledContents(True), y trabajo con los tamanhos de los labels. Por esto queria rotar el label, pero no encontre/entendi que comandos usar. Tu @Hernan4444 conoces alguno que me pueda servir? Painter? Y entiendo que no nos quieran decir "haganlo con esto" pq en el fondo pueden estar restringiendonos opciones que quizas a nosotros nos parezcan mas intuitivas, faciles, etc, no obstante, me gustaria un poco mas de guia, de ser posible. Aca nosotros estamos (creo) para aprender de gente que sabe como ustedes. En el fondo, si tu tuvieras que hacerlo, como lo harias? Muchas gracias por las rapidas respuestas

**Comment by DiegoAndai** [comment]
@abannura Yo no estoy ocupando QtDesigner, pero logre que no se me deformara, al principio giraba pésimo y se perdía la calidad, pero en la gui cargaban y seteaban el tamaño cada vez al pixmap y eso funcionó.

**Comment by andresbannuraschultz** [comment]
Gracias @DiegoAndai por responder! Oye y tu estas con el modo imagen se ajusta a label, o label se ajusta a imagen?

**Comment by vureyes** [comment]
No se si les sirva, pero lo que a mi me funciono (lo encontré en google) fue setear el tamaño del pixmap y después ajustar el label para que sea un cuadrado del porte de la diagonal del pixmap. Así cuando giras la imagen no tienes el problema de que desaparezcan los bordes.

**Comment by andresbannuraschultz** [comment]
Gracias @vureyes, si habia visto ese ejemplo en google, lo que no me convencio es que en ese caso manda la imagen, y yo queria que mandase el label. Pero veo que esa opcion no conviene.
