### ISSUE TITLE
Duda General

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2233-2016-02/Syllabus#485]
Hola, quería preguntar si es que hay alguna instancia para recorregir presencialmente alguna tarea. No quedé conforme con la corrección de la tarea 1. 
Gracias!!!

**Comment by flobarrios** [comment]
@NicolasAguirre si! Al final del semestre hay una última instancia para recorregir que es presencial y se ven cosas específicas de alguna tarea. Ojo que no se considerarán tareas que no se hayan mandado a recorregir en su momento.

Saludos!!
