### ISSUE TITLE
Dudas enunciado

### ISSUE THREAD

**Issue by tcgarrido** [IIC2233-2016-02/Syllabus#486]
Hola, tengo dos dudas:
- Una pared debe estar constituida por cuantos bloques mínimo? 2+, 3+
- La idea es que cada vez que juego la etapa distintas veces, las paredes mantienen su posición? o se ubican aleatoriamente?

Gracias! 
Saludos

**Comment by FernandoPieressa** [comment]
Hola!

1) En el ejemplo estuvo hecho con imagenes de bloques, pero no necesariamente tienen que ser bloques, puede ser una muralla de una forma como quieras. El tamaño es a criterio tuyo.

2)Se pueden mantener o puedes hacer que sean aleatorias, mientras cumplan con los requisitos de la etapa. No fue especificado en el enunciado asique queda a tu criterio. Eso si ten en cuenta que si trabajas con murallas en posiciones aleatorias podrias generar un mapa donde un tanque quede atrapado (tendrias que tener cuidado), asique te recomendaria definir los mapas de cada etapa y que se mantengan.

Saludos!

**Comment by tcgarrido** [comment]
Muchas gracias!! 😁
