### ISSUE TITLE
Tip Tarea 5

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2016-02/Syllabus#488]
Hola! Basado en la experiencia tanto de ayudante como de alumno decidí crear esta issue con uno que otro consejo que podría serles util en su tarea 05 (aparte que la documentación de Qt es tan extensa que una manito no esta demás).

Como sabrán (porque supongo que ya comenzaron a hacer su tarea), tienen que manejar distintos eventos de manera asíncrona (obviamente un tanque debe poder disparar sin que todo el juego se detenga mientras la bala se mueve). Para poder implementar esto se puede hacer uso de 2 herramientas de Qt (Tal vez existen más, no lo se, google (a.k.a su mejor amigo) lo puede saber):
### **QThreads** y **Qtimers**
# QThreads:

Los Qthreads siguen el mismo comportamiento que los Threads que fueron enseñados en el ramo, por lo que no debería presentarles mayor complicación aplicarlos en su tarea. Pero que pasa si queremos utilizarlos para una acción que sabemos que se va a repetir constantemente ? Podríamos implementar algo así en el Qthread

``` python
def run(self, ):
   while True:
       # Lo que quiero que el QThread haga en cada iteración
       time.sleep(0.1) # Muy importante para que su interfaz no se quede pegada, el valor es ajustable
```
- ¿Con esto que tenemos ?: Un QThread que repite una acción una y otra vez.
- ¿Problemas?: Si. 
- ¿Cuáles? Como detenemos este Qthread.
  En general detener (matar) un thread [es una mala practica](http://stackoverflow.com/questions/323972/is-there-any-way-to-kill-a-thread-in-python), la idea es que un Thread se inicie, cumpla su objetivo y muera al terminarlo, no que lo tengamos que detener por nuestra cuenta (mas detalles en el link, es interesante y útil)
  Entonces siguiendo esta misma lógica estamos abusando del run del Qthread con un vacío legal.
- ¿Puedo detenerlo con `break` ? Si, hay casos donde alumnos usan Qthreads en toda su tarea y no tienen problemas, como experiencia propia, empezar a matar Qthreads a diestra y siniestra con este método no escalo bien.
# Qtimers:

Otro forma de realizar lo que hacíamos con Qthreads es con Qtimers.
- ¿Cuál es la ventaja que tienen estos sobre Qthreads?:

Qtimers esta pensado para que se repita una y otra vez lo que contiene su run sin necesidad de utilizar un while, recibe como parámetro al inicializarlo el tiempo cada cuanto se debe ejecutar y ademas posee un método `stop` para poder detenerlo "legalmente". Si, se ve mas limpio en general que usar Qthreads, pero no asegura que su programa vaya a ser perfecto ni vaya a sufrir problemas de lag o caídas de interfaz, eso ya va en la programación de cada uno.
# Recomendación final:

Son libres de usar ambos en sus tareas, los 2 son útiles y pueden tener una tarea 100% funcional ya sea con uno, el otro o ambos. Por ejemplo para objetos que existan en muchas cantidades y sea difícil controlar cuando interrumpirlos puede ser mas útil utilizar un Qtimer con ellos, pero para objetos que permanecen constantes en el escenario o que son mas fáciles de controlar un Qthread es una buena opción. 
Experimenten ! Vean con cual les anda mejor, con cual es mas eficiente su tarea y averigüen mas por su cuenta, siempre es útil leer un poco antes de lanzarse a usarlo algo, y no olviden siempre comentar en el README este tipo de decisiones y porque escogieron lo que escogieron.

Éxito en lo que queda del semestre y en esta bella tarea <3  :D (@tareos I love you so much)

**Comment by cglevican** [comment]
Si yo quiero poner en un thread una funcion que actualice las posiciones de los objetos de mi ventana, puedo crearlo dentro de mi clase ventana o tengo que crearlo afuera y conectarlo de alguna manera?

**Comment by fgvenegas** [comment]
Hola!
Debes tener bien claro primero el concepto de Frontend y Backend y como se relacionan entre ellos. En pocas palabras la idea del Backend es que realice la lógica del programa y el Frontend muestre en la interfaz los cambios que van ocurriendo. Por esto tendría mas sentido que el thread esté en el Backend realizando los cambios y mediante una señal avisar a la gui para que muestre el cambio de la posición. Te recomiendo que veas [este ejemplo](https://github.com/IIC2233-2016-02/Syllabus/tree/master/Ayudantias/09-PyQt4/pyqt%20example) que se enseño en la ayudantia para ver como se mueven imágenes. Es muy útil y si tienes dudas de como funciona puedes hacerlas por acá.
Saludos

**Comment by DiegoAndai** [comment]
Hola! los QTimers al lanzar el timeout() ejecutan la función objetivo (slot) entera, ¿cierto? o sea que la función objetivo del Qtimer no es de por sí asíncrona. Si es así, ¿podría ocupar un Qtimer cuya función objetivo sea comenzar un Qthread? ¿o sería una mala práctica? la idea de esto es que el Qtimer lanza el Qthread y aprovecho la capacidad del primero de repetirse y la capacidad del segundo de ser asíncrono, y puedo parar fácilmente haciendo stop del QTimer sin tener que asesinar threads inocentes.

Muchas gracias.

**Comment by fgvenegas** [comment]
Hola!

¿ Podrías redactar un poco mejor tu pregunta por favor ? Tengo una intuición de lo que querías preguntar pero prefiero asegurarme

Saludos

**Comment by DiegoAndai** [comment]
Cada cierto tiempo el QTimer ejecuta cierta función, me preguntaba si esa función puede ser `algun_thread.start()` o si esto causaría algún error o comportamiento inesperado 🤔

**Comment by fgvenegas** [comment]
Si puedes hacerlo, no hay problema, pero ten cuidado con el tiempo del Qtimer, para que no vaya a generar demasiados threads en poco tiempo (Crash)

Saludos!

**Comment by gebalassa** [comment]
La función del Qtimer no es asíncrona...?

**Comment by gebalassa** [comment]
No entendí qué ventaja tendría usar QThrrads en vez de qtimers en lo que sea.

**Comment by DiegoAndai** [comment]
@gebalassa si tienes un proceso que termine (no cíclico) es mejor el Qthread porque no tienes que detenerlo, si ocupas QTimer la única forma de pararlo es con .stop() (a menos que sea un QTimer con singleshot). Además el proceso que corre el QThread es, obviamente, un thread, el proceso que corre el QTimer es una función normal, así que tienen comportamientos distintos.

Al final, según yo, y corríjanme si no, son cosas distintas que pueden servir para lo mismo: el QTimer ejecuta una función (entera) cada cierto tiempo y el QThread ejecuta un thread, o sea que la función "comparte" tiempo de CPU alternándose con otros threads (y con el thread principal),así que se va ejecutando por partes.

**Comment by gebalassa** [comment]
Pero el QThread permite usar locks y otros metodos de sincronizacion mientras que Qtimer no lo permite?

**Comment by DiegoAndai** [comment]
No se qué métodos tendrá uno u otro, ahí habría que ver la documentación. Yo los entiendo como cosas distintas (como expliqué arriba y como explican en el primer post de este issue). En esta tarea lo que he seguido yo como regla principal es **cíclico: QTimer, lineal: QThread**. Pero como dice arriba, lo mejor es probar, experimentar, sufrir y de esa experiencia aprender qué es mejor para qué tarea. <br>
Personalmente pasé un par de días peleando con ambos pero hemos llegado a conocernos y ser amigos jjaajjaj.

**Comment by gebalassa** [comment]
Súper. Gracias! A veces es mejor preguntar directamente y ahorrarse la pérdida de tiempo 😝 

Saludos 🍡

**Comment by fabiohsm2008** [comment]
Una consulta, estoy realizando una especie de bomberman y me he quedado estancado en la parte del tiempo de explosion de la bomba.

Uso un QTimer general para 2 jugadores a la vez, y el caso es que si coloco 2 bombas a la vez, solo "explota" la 2da.

Quisiera saber si hay alguna manera de usar QTimer en cada clase Jugador que he creado, para que llame al tiempo de la bomba y exploten cada una por separado, sin usar ambas la misma funcion QTimerEvent.

Gracias de antemano.

**Comment by DiegoAndai** [comment]
QTimer lo puedes ocupar solo en objetos de pyQt (asumo ese es tu problema), pero puedes crear timers ocupando threading. La librería threading tiene una clase Timer. Esta no se repite como el QTimer sino que se ejecuta una vez dado cierto tiempo, documentación [aquí](https://docs.python.org/3/library/threading.html). Sirve para tu caso porque necesitas sólo una llamada a la función (explotar). Puedes asignar un timer a cada jugador con esta clase.

Si necesitas un timer con loop, como QTimer, puedes crear una clase o función que dentro suyo tenga un Timer del módulo threading, con un método recursivo que reactive el timer cada vez que se ejecuta, algo como

```python
import threading

class Timer:
    def __init__(self, time, target = None):
        self.time = time
        self.target = target
        self.stop_flag = False

    def set_target(self, target):
        self.target = target

    def start(self):
        self.recursive_call()

    def stop(self):
       self.stop_flag = True

    def recursive_call(self):
       if self.stop_flag:
           self.stop_flag = False
       else:
           self.target()
           threading.Timer(self.time, self.recursive_call).start()
```

Nota que no guardas el Timer, sino que al tiro le haces start(). Podrías incluso tratar de heredar del Timer de threading, no lo he intentado. Ojalá haya sido de ayuda, Suerte!
