### ISSUE TITLE
Problemas con property

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#491]
Hola, cuando llamo a la property se genera un Attribute Error, pero cuando ocupo esa property como metodo anda todo bien. Alguna idea de porque podria pasar esto? Muchas gracias

**Comment by jtagle2** [comment]
En que archivo/línea te tira el error?
Con lo que dices hasta el momento, no podría decirte por qué te tira el error. Pero un error común, es que a veces en el init, hay gente que llama a otras funciones, y en dicha función se necesita un atributo de la clase, pero que se define más adelante en el constructor. Otro error que me ha tocado ver, es que un atributo depende de otro (ej A depende de B), y se trata de definir A antes de B.
Pero no se que sea (quizás no es ninguna de las 2). Haz push y avisa que archivo y que línea tira el error

**Comment by andresbannuraschultz** [comment]
No me vay a creer, pero se arreglo solo. Ni idea por que, muchas gracias de todas formas!
