### ISSUE TITLE
Movimiento tanques

### ISSUE THREAD

**Issue by FranciscoLarach** [IIC2233-2016-02/Syllabus#492]
Hola!
Tengo unas dudas respecto al movimiento de los tanques:
¿Si los taques solo se mueven en teoría avanzando o retrocediendo, cuando apretamos <- o -> deben rotar? ,¿desplazarse hacia los lados? o ¿se refiere a una tercera opción donde al apretar hacia el lado rota instantáneamente?
En caso de ser rotar, en el eje mouse ¿no contarían esas teclas?
En el caso de ser desplazarse hacia el lado ¿Como rotaría el tanque en el eje fijo (pues el mouse mueve el cañon)?
Gracias de antemano

**Comment by FernandoPieressa** [comment]
Hola, en ambos controles los botones <- y -> hacen que se mueva para la derecha y izquierda.

En eje mouse(bonus), como el eje de cordenadas depende del mouse, parecera que esta girando en circulo alrededor del mouse como va cambiando el eje de cordenadas, entonces el eje x que seria por el cual se mueve con los botones izquierda y derecha, siempre va a terminar siendo una tangente a un circulo

En eje fijo te mueves comun y corriente hacia los lados, te puedes hacer una idea de como es el movimiento exactamente con eje fijo en el siguiente link de juego: http://www.notdoppler.com/toytankarena.php

Saludos!

**Comment by FranciscoLarach** [comment]
GRACIAS!
