### ISSUE TITLE
pixmap con fragmento de imagen / uso de sprite sheets

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#493]
En un sprite sheet aparecen muchas cosas. Sé que puedo recortar algo que me sirve y guardarlo en una imagen aparte. Pero, ¿es posible decirle que quiero cierto fragmento de la imagen? Digamos, ciertos pixeles. Así se podría 'iterar sobre una imagen' sacando fragmentos ordenados,  en vez de guardar muchas imágenes.

Esta issue tiene dos títulos porque son dos enfoques que me interesan por igual, pero se mezclaron un poco. Me interesa saber si hay una forma de ocupar los sprites sheets que no estoy entendiendo y además, si tiene sentido querer que pixmap tome un pedazo seleccionado  de una imagen en vez de la imagen completa.

No he encontrado resultados en Google...

**Comment by aaossa** [comment]
Hola, encontré [esta respuesta](http://stackoverflow.com/a/14024064/3281097):

``` python
# -*- coding: utf-8 -*-
import sys
import time

from PyQt4 import QtGui, QtCore


class SpriteAnimation(object):
    def __init__(self, image_path, sprite_width, sprite_height, label):
        pixmap = QtGui.QPixmap(image_path)

        width, height = pixmap.width(), pixmap.height()
        self.pixmaps = []
        for x in range(0, width, sprite_width):
            for y in range(0, height, sprite_height):
                self.pixmaps.append(pixmap.copy(x, y, 
                                                sprite_width, sprite_height))
        self._current_frame = 0
        self.label = label

    def play(self, interval=100):
        self._timer = QtCore.QTimer(interval=interval,
                                    timeout=self._animation_step)
        self._timer.start()
    def _animation_step(self):
        self.label.setPixmap(self.pixmaps[self._current_frame])
        self.label.update()
        self._current_frame += 1
        if self._current_frame >= len(self.pixmaps):
            self._current_frame = 0


class Window(QtGui.QWidget):
    def __init__(self, parent=None):
        QtGui.QWidget.__init__(self, parent)
        self.resize(100, 100)
        layout = QtGui.QVBoxLayout(self)
        label = QtGui.QLabel()
        layout.addWidget(label)
        # http://content.makeyourflashgame.com/pbe/tutorials/star-green.png
        self.animation = SpriteAnimation('start.png', 48, 64, label)
        self.animation.play()


if __name__ == '__main__':
    app = QtGui.QApplication(sys.argv)
    window = Window()
    window.show()
    sys.exit(app.exec_())
```

Con ese código puedes usar _sprites_ y no se ve que sea lento. Eso sí, tienes que ver bien cómo recorres las imágenes, que puede no ser tan trivial.

###### Cambié la imágen por [esta](http://opengameart.org/sites/default/files/styles/watermarked/public/forum-attachments/sprites.png) ya que no encontré la indicada en la respuesta. El código mostrado aquí lo modifiqué para que funcionara con la nueva imagen. Busqué "use sprite sheet in pyqt4" y me salió esta respuesta :grin:
