### ISSUE TITLE
Se abre una ventana extra al agregar un widget

### ISSUE THREAD

**Issue by sormazabal** [IIC2233-2016-02/Syllabus#494]
![errorpng](https://cloud.githubusercontent.com/assets/7980453/19710038/00d68444-9b0a-11e6-931b-b7612851be71.png)

Hola! Quería saber por qué sucede esto y cómo podría arreglarlo. Cuando quiero agregar los bloques para crear la pared en las etapas se me abren unas ventanitas pequeñas con cada uno de los bloques individuales, en lugar de añadirse la piedra al main window.

**Comment by DiegoAndai** [comment]
Añadiste la ventana principal como parent de los bloques?

**Comment by sormazabal** [comment]
No, usé una clase "Board" como parent. Luego cargo esa clase Board en la Main Window. Lo raro es que los tanques y las balas también las cargo en Board y no pasa lo mismo. Debo cargar los widgets de los bloques en Main Window entonces? Pregunto porque probé haciendo eso y aún pasaba lo mismo.

**Comment by sormazabal** [comment]
@DiegoAndai  cerraron el issue, pero me sigue pasando esto mismo. :S

**Comment by DiegoAndai** [comment]
No se que pueda ser, trata de pedir acá que un ayudante revise tu código. Hiciste exactamente lo mismo para los widgets de los bloques que los otros? yo creo que hay algo diferente (además de la imagen), si no sería un comportamiento muy raro.

**Comment by fvr1** [comment]
@sormazabal te sigue pasando lo mismo? 
Puedo revisar tu código!

**Comment by aaossa** [comment]
@sormazabal prueba con esto en `show_walls`:

``` python
for wall in self.board.paredes:
    self.add_entity(wall) # En lugar de wall.show()
```

con eso "seteas" el _parent_ y haces `show`. Con ese cambio (y descomentando `self.show_walls`) me aparece el muro (de `ParedDes`) en la esquina superior izquierda

**Comment by sormazabal** [comment]
Graaaaciaaas <3 ahí salió la piedrita
