### ISSUE TITLE
Duda Quitar Fondo

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2233-2016-02/Syllabus#495]
Como puedo hacer para que en una imagen no se vea el fondo(por ejemplo para el cañon solo quiero que se muestre el cañon, no el fondo blanco). No logro encontrar la solución en Internet.
Muchas Gracias!!!

**Comment by FernandoPieressa** [comment]
Hola! Esa duda es mas respecto a edicion de imagenes que de programacion, tienes que buscar alguna aplicacion que ponga fondo transparente tipo photoshop/ editores online.

Saludos!

**Comment by Snorlax8** [comment]
http://www.online-image-editor.com/

Esa es una página en la que puedes quitarle el fondo a una imagen de forma rápida y sencilla 😁 Si no te acomoda, en internet puedes pillar muchas más opciones.

**Comment by iqacevedo** [comment]
También usar el programa GIMP de edición de imágenes :)

**Comment by NicolasAguirre** [comment]
Gracias a todos!! me sirvió !!
