### ISSUE TITLE
Problema al hacer start() de un QThread

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#496]
Tengo 3 threads que no parto (todavia no necesito que simulen nada), uno dentro de otro (esto esta bien? se puede?). Aparte, tengo mi main window que segun yo es otro thread. La estructura es asi: tanque (un thread) tiene a canhnon (otro thread) que a su vez crea balas (otro thread). Cuando quiero hacer start de una bala python deja de responder. No he podido solucionar este problema  y lo mas probable es que mi modelacion no sea la correcta, ayuda porfavor!

Subi al repo lo que llevo por si alguien tiene tiemp para hecharle una mirada! Gracias!!

**Comment by andresbannuraschultz** [comment]
Para dar un poco de contexto, tengo un QObject y un QThread para cada "entidad" (tanque, canon, bala) . Lo pense asi para manejar frontend y backend por separado (el qobject es frontend y el qthread backend). Cada front end (es decir Qobject) se crea en el init de un QThread (asi cada thread tiene un elemento grafico asociado). Lo que estaba haciendo antes, es que desde el Qthread cannon estaba instanciando un Qthread bala y haciendo start de este ahi mismo (me tiraba error y python se caia). Lo que hice ahora es que desde el Qthread canon instancio un Qthread bala (igual que antes), pero hago start desde el Qobject bala. Es decir, el camino es: instancio Qthread bala, en el init de este instancio un Qobject bala y en el init de este hago start del Qthread bala. Esto funciona, peeeeero....

Respecto a esto tengo dos dudas:

1) Como puede funcionar si estoy haciendo start() de un thread que nisiquiera ha terminado de instanciarse.

2) Por que ya no tengo el problema anterior? (que python se caia)

Muchas gracias!

**Comment by jtagle2** [comment]
@abannura. Respecto a la segunda pregunta, no se por qué ya no tienes el problema, no alcancé a ver tu código antes del cambio.
Respecto a la primera pregunta, hacer el `start()` dentro del init de tu objeto que hereda de Thread no tiene ningún inconveniente (salvo que no llames al `init` de la clase padre Thread). ¿Por qué? Porque cuando estás dentro del init, tu instancia ya existe (self). Lo que pasa es que está incompleta y tu la vas llenando con los atributos que le quieres ir definiendo.
Para que se entienda lo anterior, prueba algo de este estilo:

``` python
class MediaPersona:

    def __init__(self):
        try:
            self.nombre = "Pedro"
            self.rut = 1/0
            self.apellido = "Perez"
        except:
            pass

e = MediaPersona()
print(e.nombre)
print(e.apellido)
```

Si te fijas, la persona se alcanzó a crear hasta donde pudo llegar el init, pero el hecho de que este no haya terminado completamente su ejecución, no quiere decir que deja de existir. Solo es una persona con nombre pero sin apellido.
Si vemos esto en los threads, si tu llamas al start dentro del init de tu thread, no hay ningún problema, pues al momento de empezar a correr el thread, la clase ya obtuvo todos los datos necesarios en el init. De hecho, el thread se puede inicializar sin necesidad de haber terminado de ejecutar el init, pero eso ya es más propenso a errores. Como se ve en este ejemplo, el thread nunca arrojará un problema por empezar a ejecutarse sin haber terminado el init (el error puede derivar de otros problemas asociados a esto).

``` python
from threading import Thread
from time import sleep

class MyThread(Thread):

    def __init__(self):
        super().__init__()
        self.start()
        sleep(1)
        self.mensaje = "Ahora si está bien definido el atributo :D"
        print("Se terminó de ejecutar el init")

    def run(self):
        #sleep(1)
        valor = getattr(self, "mensaje", "AUN NO ESTÁ DEFINIDO EL ATRIBUTO! Va a tirar error esta cosa :S")
        print("Empezando a correr el thread, y el mensaje será: {}".format(valor))
        print(self.mensaje)


e = MyThread()
```

Saludos, espero te sirva de algo.

**Comment by andresbannuraschultz** [comment]
Buenisimo! Te cache perfect, muchas gracias por darte la lata de contestar! en verdad estaba chato de no entender que estaba pasando. Eso si, yo estoy haciendo start() del QThread desde el init de un QObject, no del mismo QThread. Pero ya veo que tambien es valido, en el fondo los metodos se definen antes de empezar con el init, lo importante es haber definido los atributos que usara el metodo antes de llamarlo. Epico.

Con respecto a lo primero, probablemente el codigo que tu viste es igual al que cuando tenia problemas, la unica diferencia es que el start() en vez de hacerlo donde te digo, lo hacia desde otro QThread (del QThread Cannon). No se si eso tenga algo que ver. 

Muchas gracias por todo! Realmente te pasaste!
