### ISSUE TITLE
Flechas no gatillan Key Press Event

### ISSUE THREAD

**Issue by Snorlax8** [IIC2233-2016-02/Syllabus#497]
Hola!

En mi programa, por alguna extraña razón no se reconocen las flechas como teclas. Al presionar cualquier otra, se detecta que está ocurriendo un Key Press Event y sucede lo que debería, pero mi programa se niega a pescar las flechas. ¿Alguien sabe por qué puede ser esto?

Espero su respuesta, muchas gracias 😁 .

**Comment by aaossa** [comment]
Asegurate de que al usar las flechas el focus se mantenga en el widget y no cambia. Date una vuelta por las issues del semestrr pasado y busca KeyPressEvent, hay hartas issues con problemas similares que se resolvieron y un ejemplo de código que puse. Cuando tenga tiempo (y si responde tu duda) colocaré la respuesta acá.

Resumen: Busca en las issues del semestre pasado

**Comment by Snorlax8** [comment]
Muchas gracias @aaossa ! Efectivamente era un problema de foco. 

Algo que no me queda muy claro, eso si, es la diferencia entre setFocus y setFocusPolicy.

**Comment by aaossa** [comment]
Yap, traté de aterrizar un poco la documentación de PyQt:
- **[`QWidget.setFocus(self)`](http://ftp.ics.uci.edu/pub/centos0/ics-custom-build/BUILD/PyQt-x11-gpl-4.7.2/doc/html/qwidget.html#setFocus):** Te sirve para decir "haz _focus_ en este widget"
- **[`QWidget.setFocusPolicy(self, Qt.FocusPolicy)`](http://ftp.ics.uci.edu/pub/centos0/ics-custom-build/BUILD/PyQt-x11-gpl-4.7.2/doc/html/qt.html#FocusPolicy-enum):** Te sirve para decir "acepta _focus_ de esta forma"

**Comment by Snorlax8** [comment]
Muchas gracias!
