### ISSUE TITLE
AC12 sem pasado

### ISSUE THREAD

**Issue by asimonv** [IIC2233-2016-02/Syllabus#499]
Alguien pudo crear el .wav?

**Comment by asimonv** [comment]
Tengo problemas con la lectura del header del archivo, porque leo los headers de otro archivo (que también nos dieron en la última ayudantia de este semestre, el previously.wav) y lo lee bien, pero el header de TOP SECRET.iic2233 que se supone que son los primeros 44 bytes, no me lo lee bien.

**Comment by asimonv** [comment]
Parece que es porque es un .mp3 jaja

**Comment by fgvenegas** [comment]
Hola!
Podrías explicar un poco mas tu problema ? Mas bien a que te refieres con  que no te lo lee bien 
Saludos

**Comment by asimonv** [comment]
Creo que es porque no era un .wav, sino que un .mp3, entonces estaba utilizando la estructura de .wav para leer. Me di cuenta porque al leer el header, tiene como tag ID3, y no RIFF.
Estaba pensando en .wav porque en el enunciado decían que podía ser ese tipo.

**Comment by asimonv** [comment]
Ya pude solucionarlo, gracias!
