### ISSUE TITLE
Python 3.5 y versión PyQt

### ISSUE THREAD

**Issue by ricardor4** [IIC2233-2016-02/Syllabus#5]
He instalado Python 3.5 en OS X, y no pude instalar PyQt 4, al hacer pip3.5 install PyQt4 no encuentra el paquete, pero si pude instalar PyQt 5, con pip3.5 install  PyQt5, y funciona al hacer import PyQt5.

¿Importa en el curso si la versión a ocupar es la 4 o la 5?

**Comment by aaossa** [comment]
Hola :grin: Actualmente en el curso usamos PyQt4, por lo que usar PyQt5 no garantiza que a los ayudantes les funcione tu código o que a ti te funcionen los códigos del curso. Intenta instalar PyQt4 y si sigues con problemas no dudes en abrir una issue :D

**Comment by jgmontoya** [comment]
Lamentablemente PyQt5 **NO** es compatible con PyQt4 por lo que sí importa instalar correctamente PyQt4.

Si te interesa leer acerca de las diferencias entre PyQt4 y PyQt5 puedes hacerlo [acá](http://pyqt.sourceforge.net/Docs/PyQt5/pyqt4_differences.html)

EDIT: Si al seguir el wiki te encuentras con [este](https://github.com/IIC2233-2016-02/Syllabus/issues/1) problema. Tal como respondió @MainScientist necesitarás instalar homebrew para usar el comando brew. (Puedes ver como instalarlo [aquí](http://brew.sh/) )

**Comment by ricardor4** [comment]
al hacer "brew install pyqt --with-python3" me señala "Warning: pyqt-4.11.4 already installed"
pero al entrar a python y hacer "import PyQt4" obtengo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'PyQt4

**Comment by domingo-valdes** [comment]
Yo también tengo problemas con PyQt4, pero en Windows. Me arroja esto
![error1](https://cloud.githubusercontent.com/assets/17691819/17344598/bd1e9686-58d0-11e6-8988-c16335e9356d.png)

**Comment by FernandoPieressa** [comment]
@domingo-valdes 

#4

Por favor revisa las otras issues antes de preguntar

**Comment by domingo-valdes** [comment]
@FernandoPieressa Disculpa, lo acabo de ver. Muchas gracias, me sirvió instalarlo desde http://www.lfd.uci.edu/%7Egohlke/pythonlibs/#pyqt4

**Comment by cmgainza** [comment]
Tengo el mismo problema de @ricardor4
al importar PyQt4 obtengo 
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import PyQt4
ImportError: No module named 'PyQt4'

Si trato de importarlo desde el terminal obtengo
-bash: import: command not found

**Comment by jgmontoya** [comment]
@cmgainza 
Para hacerlo desde el terminal primero debes usar alguno de estos comandos:

```
python
```

o bien

```
python3
```

**Comment by cmgainza** [comment]
@jgmontoya si utilizo el comando python obtengo
python: can't open file 'import': [Errno 2] No such file or directory

al ejecutarlo en python obtengo que no existe el modulo llamado PyQt4

gracias!

**Comment by jgmontoya** [comment]
@cmgainza 
No me expliqué bien, en el terminal debes usar alguno de esos comandos **antes** del import.
Por ejemplo: 

```
python
(Saldrá algo como: "Python 3.5.1 ... 
    Type "help", "copyright", "credits" or "license" for more information.")
>>>
```

Y ahí haces el import

```
>>> import PyQt4
```

**Comment by cmgainza** [comment]
@jgmontoya sigo obteniendo lo mismo.. 

MacBook-Pro-de-Constanza-3:~ ConstanzaGainza$ python
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyQt4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named PyQt4

mil gracias por tu ayuda! :simple_smile:

**Comment by cmgainza** [comment]
@jgmontoya sigo obteniendo lo mismo..

MacBook-Pro-de-Constanza-3:~ ConstanzaGainza$ python
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

> > > import PyQt4
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: No module named PyQt4

mil gracias por tu ayuda!

**Comment by ricardor4** [comment]
Coni, al usar Python en terminal, te tira al 2.7 que viene instalado, tienes que usar Python3 para que te tiré al 3.xx

**Comment by cmgainza** [comment]
@ricardor4 gracias! pero tampoco funciona..

MacBook-Pro-de-Constanza-3:~ ConstanzaGainza$ python3
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

> > > import PyQt4
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: No module named 'PyQt4'

**Comment by aaossa** [comment]
@cmgainza Y pudiste instalarlo con `brew install pyqt --with-python3` sin problemas? O el output al instalarlo te decía algo?

**Comment by cmgainza** [comment]
@aaossa en ese caso obtengo
MacBook-Pro-de-Constanza-3:~ ConstanzaGainza$ brew install pyqt --with-python3
Warning: pyqt-4.11.4 already installed

creo que el problema tiene relación con lo que dice Ricardo. En el terminal al ver que versión de python estoy usando me retorna la 2.7.1 cuando inicio con "python". 
Si inicio con "python3" utiliza la 3.5.2

Salí de python (exit()) y después instale con "brew" python3 y me retorna esto:

MacBook-Pro-de-Constanza-3:~ ConstanzaGainza$ brew install python3
Warning: python3-3.5.2_1 already installed, it's just not linked

¿como puedo solucionarlo?

**Comment by felipehv** [comment]
Intenta con
Brew link python3
Si no funciona usa
Brew link --overwrite python3

**Comment by cmgainza** [comment]
@felipehv ya logramos solucionar el problema con python.. tuve que desinstalarlo, instalarlo mediante brew (con el overwrite) y luego vincularlo con brew link (créditos a @jgmontoya)

El problema ahora es con pyqt, constantemente retorna ImportError: No module named 'PyQt4'.
Luego desvincule pyqt con "brew unlink pyqt —with-python3"

en eso vamos.. ahora estamos viendo si eliminar el pyqt con "brew prune" y diagnosticando que links están desvinculados con "brew doctor" para reinstalarlo después

**Comment by felipehv** [comment]
Ups quizás no me llegó esa parte al correo jaja.
Sobre el problema, tiene que ver con que al parecer al usar python3, se
utiliza una instalación distinta a la de brew. Lo vi hoy en un mac. No
logré llegar a una solución pero para que veas el problema también por ahí.
:)

**Comment by ricardor4** [comment]
Logré solucionarlo, desinstalé con brew la versión que había instalado, descargué PyQt4 de (https://riverbankcomputing.com/software/pyqt/download), y lo instalé siguiendo el readme, es decir yendo al terminal a la carpeta donde descomprími el tar.gz, luego haciendo python3 configure-ng.py, luego make, y make install.
Ahora al hacer python3 import PyQt4 no hay ningún error

**Comment by mraddatz** [comment]
@cmgainza que comandos usaste para desinstalar e instalar python mediante brew?

**Comment by cmgainza** [comment]
@mraddatz lo desinstale manualmente (como desinstalas cualquier programa). 
para instalarlo con brew use "brew install python3". Existe también el comando brew uninstall por si lo quieres intentar

**Comment by otro-felipe** [comment]
si siguen con problemas pueden revisar la issue #16
