### ISSUE TITLE
Movimiento faltante en programonMoves.json

### ISSUE THREAD

**Issue by Zekayrus** [IIC2233-2016-02/Syllabus#50]
Weedle, Tentacool , Nidoqueen y otros 5 programones tienen el movimiento "poison sting", pero no hay información de éste en programonMoves.json.

**Comment by flobarrios** [comment]
Hola ! se subirá un nuevo programonMoves.json dentro de hoy y mañana corrigiendo ese error!

**Comment by mjjunemann** [comment]
Ya esta arreglado el archivo con los ataques que faltaban 👍
