### ISSUE TITLE
Obligacion enunciado

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2233-2016-02/Syllabus#500]
Hola , es obligación poder moverse con las flechas? Es como incomodo estar con el mouse, flechas y las letras de la izquierda (q o e) al mismo tiempo. No se puede hacer que en vez de moverse con las flechas sean las teclas w,s,a,d ??? 
Muchas Gracias

**Comment by flobarrios** [comment]
Hola! Si, puedes cambiar las teclas pero debes especificar en el README a que equivale cada una! Saludos 😄
