### ISSUE TITLE
Tarea 2

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#501]
Hola, tenia un 39 en la tarea 2 y mande a recorregir y me subieron a un 42 y me aparece un 32 en la tarea, a quien puedo pedirle que revise mi caso?

**Comment by flobarrios** [comment]
Hola! hubo un error y no se te consideró el punto base. Será actualizado ahora. Para futuras dudas administrativas de tareas, debes enviar un mail directamente a mi o a @mjjunemann. Saludos!!
