### ISSUE TITLE
Problemas mostrando imágenes

### ISSUE THREAD

**Issue by FranciscoLarach** [IIC2233-2016-02/Syllabus#502]
Hola! 
Estoy teniendo muchos problemas para mostrar imágenes dentro de mis widgets, he buscado y leído harto pero aun no me funciona. Entiendo que debo hacer un label y ahí hacer el setPixmap para mostrarla.
Hice un push por si alguien esta dispuesto a ayudar (no llevo mucho), tratar con el modulo "Niveles".
Gracias de antemano.
pd: según yo es algo muy simple

**Comment by FernandoPieressa** [comment]
Hola @FranciscoLarach !

Vi tu codigo y el problema tenia que ver con la imagen!!!!

El formato de tu imagen es .jpg, el poner .png hace que no funcione correctamente.

Prueba poniendo 
QPixmap("fondo.jpg")

y cambiandole a .jpg en vez de .png la imagen

Saludos!

**Comment by FranciscoLarach** [comment]
GRACIAS!!
disculpa lo basico!
