### ISSUE TITLE
libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-02/Syllabus#503]
Hola !
Me sale exactamente el mismo error que salia en la gui de la T04, antes de que lo arreglaran. 
Según lo que busque, lo más probable es que haya modificado algún nombre de archivo, lo este buscando y no lo encuentre. Tengo varias imágenes (como 25) y fui revisando una por una y estaban todas sus referencias bien.
Alguna otra razón que podría estar causando que se imprima eso ?
Como lo arreglaron en la T04 ?

Saludos ! Y gracias de antemano

**Comment by Hernan4444** [comment]
@Diiru ese error se genera porque la imagen png que estas usando esta en algún formato (dentro de los png) que pyqt no le gusta. Lo que se hizo fue pasar todas las imágenes por un convertidor (http://imagen.online-convert.com/es/convertir-a-png).
Espero que eso te sirva para solucionar tu problema

Saludos!!

**Comment by Iruretagoyena** [comment]
@Hernan4444 Mhh que raro, tengo todos en png, les pegare una re-repasada por si acaso.
Gracias !

**Comment by Hernan4444** [comment]
@Diiru te creo que estan en png, pero dentro de png hay diferentes formas de crear uno y ahi está el problema, pyqt es sensible a los diferentes formatos. Por ejemplo puede que te falle con png en formato rgba pero no en rgb.

Saludos!

**Comment by aaossa** [comment]
Solo para aclarar. Esto no es un error como dijeron, es un _warning_. El programa no se va a caer si les aparece esto, por lo que no es un error. **Un _warning_ es como una alerta**. No va a parar tu programa, pero te avisa si es posible que tu programa tenga algún problema. Por ejemplo, los _warnings_ se usan cuando una función en un modulo va a ser eliminada o su funcionalidad va a cambiar. 

Entonces, a ti lo que te sale **es un _warning_**. Tu programa no "se cae", solo te avisa que algo raro pasa. Ponlo en el README que hagas. Mientras no afecte la funcionalidad de tu tarea no deberías tener mayores complicaciones. 

---

Respuesta tomada de https://github.com/IIC2233-2016-1/syllabus/issues/581
