### ISSUE TITLE
Dudas de T05

### ISSUE THREAD

**Issue by gabrielpinkman** [IIC2233-2016-02/Syllabus#504]
Holi, después de leer la tarea tengo las siguientes dudas
1.  El tanque puede tener por ejemplo, 10 vidas, y con cada disparo le quito una, o debe tener por ejemplo 5 vidas con barras de 100 hp y cada disparo no le quita una vida, sino que le hace daño solamente ? No entiendo el tema de las barras de vida y las vidas y quitarles vidas, en el pdf se realizan menciones a "vidas" y "vida" en la misma frase lo que me causa confusión.
2.  La bala penetrante puede atravesar tanques?
3.  Puede ser, Izquierda = "A", Derecha = "D", Arriba = "W", Abajo = "S", Disparo = click izquierdo, poner bomba = click derecho, disparar portales = espacio ?
4.  No entiendo la diferencia entre eje fijo y eje mouse

**Comment by jgmontoya** [comment]
Hola!
1. Se trata de una barra de hp donde los disparos le hacen daño. A cada hp ('punto de salud') se les llamó vida.
2. Queda a su criterio. Recuerda especificarlo en el readme.
3. Sí, pero recuerda especificar en el readme!
4. Con eje-mouse, la flecha hacia arriba moverá al tanque en la dirección del mouse mientras que con eje-fijo se moverá hacia arriba en la pantalla. Esto significa que, estando en eje-mouse, si el mouse estaba abajo del tanque, el tanque se moverá hacia abajo apretando la flecha hacia arriba.

En otras palabras, con eje-mouse ocurre lo siguiente:
- La flecha hacia arriba disminuye la distancia entre el tanque y el mouse
- La flecha hacia abajo incrementa la distancia entre el tanque y el mouse
- La flecha hacia la derecha mueve el tanque en sentido anti-horario, manteniendo la distancia entre el tanque y el mouse
- La flecha hacia la izquierda mueve el tanque en sentido horario, manteniendo la distancia entre el tanque y el mouse.

Mientras que con eje-fijo:
- La flecha hacia arriba mueve al tanque hacia arriba
- La flecha hacia abajo mueve al tanque hacia abajo
- La flecha hacia la derecha mueve al tanque hacia la derecha
- La flecha hacia la izquierda mueve al tanque hacia la izquierda

Saludos!

**Comment by gabrielpinkman** [comment]
gracias <3
