### ISSUE TITLE
Cosas misteriosas

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#506]
Hay al menos dos cosas misteriosas que me están ocurriendo:

1) Hay sectores dentro de la ventana (en general cuadrante superior izquierdo) en los que el tanque se mueve más lento y más tonto (ej. no se mueve exactamente en diagonal cuando corresponde). Sin embargo, la funcionalidad del movimiento no debería depender de la posición y la implementación de QTimer's no debería relantizar la ejecución. Por lo visto, pareciera que los timers se ejecutan cada menos tiempo del que deberían cuando esto ocurre.

2) No logro seguir el mouse SIN necesidad de hacer click. Tengo `setMouseTracking(True)` en mi Widget y ocupo el evento `mouseMoveEvent(self, event)`, que cuando hay MouseTracking, debería ocurrir siempre que el mouse se mueve SIN necesidad de hacer click, según he leído.

Estas dos cosas me resultan muy misteriosas, así que quería preguntar a pesar de lo muy específicas que son. Para los ayudantes, tengo un push con estas condiciones dadas que pueden revisar. Hay que ejecutar `stage1.py`.

Muchas gracias.

**Comment by aaossa** [comment]
Para 2) prueba haciendo focus en el widget antes de empezar el MouseTracking. Esto explicaría por qué debes hacer click antes de que te haga caso, porque con el click estás haciendo focus en ese widget

**Comment by jbsaeza** [comment]
Tengo el mismo problema con el mouseTracking, intente hacerle focus a mi único widget de distintas formas pero sigo requiriendo mantener el click para que se ejecute el mouseMoveEvent. help D:

**Comment by andresbannuraschultz** [comment]
Prueba poniendo StrongFocus en tu MainWindow y ademas en su CentralWidget (ademas obvio, del widget en el que estay trabajando), a mi me pasaba que tenia Strong Focus en el main window y en el widget que estoy trabajando pero me faltaba ponerle al central widget. Ojala te funcione tambien! Saludos

**Comment by cjgazali** [comment]
lo mismo que @jbsaeza ; no estoy hablando del primer click que hago sobre la ventana, estoy diciendo que NUNCA me sigue el mouse A MENOS que esté apretando algún botón...

**Comment by cjgazali** [comment]
2) RESUELTO: `self.installEventFilter(self)` en init, luego se define método `def eventFilter(self, object, event)`, y se revisa si el evento es de tipo HoverMove en mi caso.

**Comment by cjgazali** [comment]
1) es demasiado misterioso... no tiene sentido que los timers no se la puedan, tan poco sentido como que unos threads no se la puedan... o no? debería ocupar threads?  :angry:

**Comment by jbsaeza** [comment]
muchas gracias @cjgazali  :D

**Comment by vureyes** [comment]
Como solucion alternativa para seguir la posicion del mouse: guardar un QCursor como atributo en la clase que va a revisar la posicion del mouse, despues solo le piden la posicion. (Es la posicion respecto a la pantalla)

**Comment by asimonv** [comment]
Holaa no sé si lo habrás solucionado o no lo del mouse, pero agregué
`self.tank_view.setMouseTracking(True)`
en MainWindow y funciona perfect, sin la necesidad de installEventFilter. `tank_view` es una clase que hereda de QGraphicsView.

**Comment by roy350** [comment]
@cjgazali con respecto al problema de 2 que se debe poner dentro de def eventFilter(self, object, event)? es que tengo el mismo problema :(

**Comment by aaossa** [comment]
@roy350 si quieres hacer algo parecido a lo que dijo @cjgazali tienes que identificar el tipo de evento (usando `event.type()`)
