### ISSUE TITLE
Widget y layout

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#507]
En mi main window tengo un cierto layout. Queria hacer en QtDesigner un widget para cada nivel y despues ir agregando/quitando estos widgets al layout mencionado. Pense que al cambiar el sizepolicy de los widgets iba a andar todo bien para que se ajustaran y expandieran al tamano del layout en el main window, pero no funciona. Alguna idea de porque esto no funciona? o de algo que podria estar haciendo mal? muchas gracias

**Comment by aaossa** [comment]
Qué significa que no funcione? Puedes ser un poco más específico? No se ven, no funcionan? Gracias.

**Comment by andresbannuraschultz** [comment]
Sorry sorry, me refiero a que no se expande en todo el layout. Si mi layout es de 100x100 (los layout no tienen dimensiones pero para que te hagas una idea nomas) y mi widget es de 50x50 yo quiero que al agregar el widget al layout quede de 100x100, pero sigue quedando de 50x50. Segun lo que habia leido el set sizepolicy arreglaba eso o no?
