### ISSUE TITLE
Problemas con QtDesigner

### ISSUE THREAD

**Issue by gabrielpinkman** [IIC2233-2016-02/Syllabus#508]
Hola, necesito ayuda, no me abre el Designer :c

**Comment by aaossa** [comment]
Disculpa @gabrielpinkman , puedes decirnos qué intentaste? No te abre designer o no lo encuentras?

**Comment by gabrielpinkman** [comment]
Lo busco y lo ejecuto, pero no abre nada

**Comment by gabrielpinkman** [comment]
Ok, pasó esto...
Al no abrir designer pretendí arreglar mi error reinstalando PyQt4, al desinstalar PyQt4 para volver a instalarlo, comenzó a generarme un error de que no encontraba la librería para instalarla, así que bajé desde el link http://www.lfd.uci.edu/~gohlke/pythonlibs/ el archivo que sale especificado en la wiki del Syllabus... ahora, al intentar instalarlo tengo un problema llamado "name threading is not defined" lo que me indica que python ni siquiera está reconociendo a threading, ya no sé qué hacer, esto me retrasará un montón la tarea, por favor ayuda

**Comment by aaossa** [comment]
@gabrielpinkman 2 preguntas: ¿Cómo se llama el archivo que te tira el error? y ¿cómo estas importando los _threads_?

**Comment by gabrielpinkman** [comment]
Ya, voy a explicar de nuevo... de hecho le pedí ayuda a Osvaldo Torres, que me ayudó a desinstalar las versiones de PyQt4 y python que tenía

En mi computador tenía la versión 3.5.1 de python, instalado con anaconda3... Luego me di cuenta que no me abría QtDesigner, así que decidí desinstalar PyQt4 y ahí comenzó mi problema: cuando quise volver a instalarlo me tiraba un error de que PyQt no existía, luego diciendo que pip estaba desactualizado o algo así... finalmente bajé el famoso archivo get-pip.py , y cuando lo hacía correr me tiraba el error que Threading no está definido, y ya no sé qué más hacer

**Comment by aaossa** [comment]
Ya trataré de responderte a pesar de que no respondiste mis preguntas. Revisa la versión de Python que estás usando, que tu archivo no se llame `threading.py` y que los paths a las versiones de Python que tienes en consola y que usas en tu editor sean la misma. Yo no uso Anaconda así que prefiero no opinar al respecto, pero algo así podría ser.

Te recuerdo también que hay una guía en la wiki para instalar estas cosas (que deberían haber instalado hace tiempo) en la que podrías apoyarte para tratar de arreglar esto. Suerte.
