### ISSUE TITLE
Tanques enemigos

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#509]
Cuando dicen en el enunciado que los tanques enemigos disparan "respetando las murallas", se refiere a que solo disparan si hay un camino libre entre el y el tanque del jugador, o que simplemente sus balas respetan las murallas como cualquier otra bala? Sorry la duda tonta jaja

**Comment by FernandoPieressa** [comment]
Hola!

Cuando dice respetando las murallas se refiere a que el tanque siempre intentara llegar a ti para destruirte pero que si hay una muralla entre el jugador y el enemigo no la puede atravesar, entonces tendría que ver como darle la vuelta para llegar a dispararte, no se refiere al disparo en si.

Saludos!

**Comment by andresbannuraschultz** [comment]
Ahh dale dale, muchas gracias!
