### ISSUE TITLE
Archivo no encontrado en material de clases

### ISSUE THREAD

**Issue by The-Big-Lebowski** [IIC2233-2016-02/Syllabus#51]
Hola. En la página 05-Herencia-Multiherencia la imagen en "Multiherencia y el Problema del diamante" no aparece y muestra el error: "archivo no encontrado"

**Comment by aaossa** [comment]
Acabo de subir las imágenes, haz pull y prueba de nuevo. Si persiste el problema avisa por aquí :ok_hand:

**Comment by The-Big-Lebowski** [comment]
Perfecto! Gracias

**Comment by bedefrunner** [comment]
Hola! Me pasa lo mismo, acabo de hacer pull y el problema persiste.
