### ISSUE TITLE
[Tarea 5] notas: 'constantes'

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#510]
¿A qué se refieren con 'las constantes que hayamos escogido'? ¿Qué tipo de información, exactamente, esperan poder ver y modificar dentro de nuestro archivo de constantes? ¿Es obligatorio que exista este archivo?

**Comment by FernandoPieressa** [comment]
Si efectivamente tiene que existir, y es todo lo que quedo a su criterio, por ejemplo: tiempo, vidas, velocidad, poder, radio explosiones, puntajes, precios de tienda, etc..

Todos esos numeros que en verdad fueron definidos por ustedes como variables a su criterio tienen que ser posible de leer mediante algun archivo para que podamos editarlas.

Saludos!
