### ISSUE TITLE
Dudas sobre multithreading

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#511]
Tuve el siguiente error:

QObject::setParent: Cannot set parent, new parent is in a different thread
QPixmap: It is not safe to use pixmaps outside the GUI thread

Me puse a investigar y a leer sobre multithreading y encontre varias cosas. Creo ya entender porque puede estar pasando, pero mi duda es mas general. No entiendo como pensar en los threads. Como se que thread esta dentro de otro? Cuando lo inicio en el metodo de run? No entiendo la estructura de los threads en mi programa y por lo tanto me cuesta mucho debuggearlo. Algunas dudas ya mas concretas:

1) Por ejemplo, si creo un nuevo objeto QThread, pero no hago start de el, ese thread donde esta? Dentro del thread que lo creo o dentro del thread que le hizo start? 

2) Si no hago start de un thread, cuenta como thread? o es un objeto normal nomas.

3) Como se dentro de que thread estoy? En el fondo para poder construir un arbol y hacerme la idea.

Cualquier ayuda o explicacion general sobre como funcionan estas cosas es muy bienvenida.

**Comment by andresbannuraschultz** [comment]
Tenia el problema antes mencionado al disparar una bala desde un canhon enemigo. Lo que estaba haciendo era en el run llamar al metodo shoot() de ese mismo tanque. Segun lo que entendi en internet, el problema se producia porque habia una senhal que no se estaba emitiendo desde el thread en que se creaba. Bueno, probando y probando, en vez de llamar directamente al metodo shoot() cree una senhal que lo "llamase". No entiendo porque ahora funciona perfect jaja. Porfa ayuda para entender todo esto!

**Comment by Hernan4444** [comment]
@abannura Sobre el error, esto pasa cuando in thread intenta modificar a un objeto de la interfaz de forma directa. Por ejemplo
`self.graph_object.setPos(x,y)`

Lo esperado que todas esas modificaciones las haga el frontend por medio de señales.

Sobre las preguntas 1 y 2:
1. el Thread está en el que lo creó, pero se podría pasar a otro Thread para que lo inicie, aunque se mantendrá en su Thread creador
2. Sigue siendo un objeto Thread pero que no está en ejecución.

Saludos!!!

**Comment by andresbannuraschultz** [comment]
Yo tambien pensaba que ese era el motivo del error, pero segun yo en ninguna parte estaba modificando cosas de la interfaz desde un thread. Ademas, la solucion fue algo nada relacionado (segun yo) con modificar la gui. En vez de llamar a una funcion directamente, la pase a llamar con una senhal. Gracias por responder!
