### ISSUE TITLE
Dudas sobre Tarea 5

### ISSUE THREAD

**Issue by fabraghetto** [IIC2233-2016-02/Syllabus#512]
Tengo algunas dudas sobre la tarea:

1) El tanque circulo ataca? o solo anda en circulo sin atacar?
2) El tanque grande destruye las paredes destructibles al colisionar con ellas
o al lanzar un misil o las dos?

Duda extra:
3) Cómo puedo hacer para que al hacer click en mi ventana del juego, algún método o lo que sea me retorne la coordenada o pixel que clickié, lo que se vió en material de clases es el método mousePressEvent, pero no retorna lo que necesito, por otro lado en internet buscando encontré grabMouse pero no se como utilizarlo y llevo atrapado en esta duda varias horas,

Agradecido de antemano por su ayuda!

**Comment by FernandoPieressa** [comment]
Hola! Respecto a tus dudas:

1) TODOS los tanques atacan si estas en su visión

2) Las destruye al colisionar, respecto a la bala queda a criterio si deseas que tambien sus balas grandes destruyan murallas.

3)Creo que lo que buscas es el comando QMouseEvent.pos(), lo puedes utilizar tipo
def mousePressEvent(self, QMouseEvent):
        print(QMouseEvent.pos())

y recibiras las cordenadas.

Saludos!

**Comment by fabraghetto** [comment]
Muchas gracias !

**Comment by fabraghetto** [comment]
Aprovecho de preguntar otra duda que no tiene que ver con lo anterior. En el modo survival hay tienda??, no queda claro en el enunciado (creo)

**Comment by FernandoPieressa** [comment]
A criterio suyo.

Saludos!
