### ISSUE TITLE
Prioridades

### ISSUE THREAD

**Issue by gebalassa** [IIC2233-2016-02/Syllabus#513]
¡Hola!

Considerando que terminar esta tarea en una semana supera mis posibilidades físicas humanas sin caer en la auto-flagelación, deseaba saber **qué** partes recomendaban "**priorizar**" antes que otras con tal de, por lo menos y bajo las estrictas reglas de corrección, sacar un azul. En particular, si la **Tienda** tenía mucha importancia, o las **animaciones**, o los **Tipos de Bala**.

¡Muchas gracias de antemano!

Gabriel.-

**Comment by isipalma** [comment]
Hola!

La verdad es que no podriamos decirte lo que mas vale ni a que punto sería un azul, pero si podemos decirte que es altamente recomendable que partas por lo básico  y necesario como para poder jugar (movimiento, disparo, tienda, etc), y luego avances cuanto puedas en las demas implementaciones que tu creas que valen y que te tome menos tiempo, eso igual puedes evaluarlo tu.

Saludos ;)

**Comment by isipalma** [comment]
Sin embargo, debes tomar en consideración que lo que se considera "básico" es solamente una parte de la tarea, por lo que si no la haces completa o avanzas más de lo que puse aca es probable que no logres obtener una buena nota
