### ISSUE TITLE
Duda "hitbox" de un QGraphicsProxyWidget o QGraphicsItem en general

### ISSUE THREAD

**Issue by fopasten** [IIC2233-2016-02/Syllabus#514]
Hola!, 
tengo una duda, necesito cambiar el "hitbox" de mi tanque ya que hice un proxy de un widget que cree para que sea mas fácil el manejo de las imágenes, traté cambiando el boundingRect y el sceneBoundingRect directamente pero no me ha dado resultados. Alguna ayuda?.
Quería consultar si la forma en que estoy creando ventanas esta medianamente correcta de igual forma.

PD: si revisan mi codigo está en el archivo Board.py la creación del tanque y en Tank.py esta el QWidget en base al cual lo creo.

Saludos!

**Comment by Hernan4444** [comment]
@fopasten estuve leyendo tu código y lo que más me hace ruido es que tu sobrescribes los métodos por  QtCore.QRect, un objeto. Eso en general debería tirar error en algún momento porque ese método ya no se le puede hacer call, ahora es un atributo.

Si lo que quieres es que esos métodos ahora retornen el dato que quieras, aprovecha la capacidad de python de sobrecargar los métodos, o en vez de definir el método como un atributo (como la estas haciendo tu), defíelo como una función.

Saludos!!

**Comment by fopasten** [comment]
@Hernan4444 Finalmente lo que hice fue crear un QGraphicsRectItem que es externo a el proxy del widget, que se mueve en conjunto con el tanque y que funcionaría como mi "hitbox" del tanque, ya que traté de muchas formas de editar el boundingRect de tal manera de que no recorte lo que se muestra en pantalla pero no fue posible ;(

---

Tengo otra duda, mi nota de la T01 no aparece en el documento de hace varios dias, es por la recorreción? Soy el único que no tiene nota ;(

**EDIT (aaossa):** Esto ya fué resuelto. Para la próxima envía un mail a los jefes de tareas con copia a Bastián en lugar de preguntarlo de una forma muy escondida en el comentario de una issue donde es posible que nadie lo vea :scream:

**Comment by fipaniagua** [comment]
hola @fopasten  finalmente hisiste QGraphicsRectItem? si es asi como lo haces para rotarlo
porque yo ocupo  setTransformOriginPoint(x,y) y   setRotation(angulo) pero cuando hago el rotation
tambien  cambia la posicion, ¿de casualidad no tuviste el mismo problema?

**Comment by fopasten** [comment]
@fipaniagua Si, usé QGraphicsRectItem para el hitbox con ese método, y no tuve problemas para moverlo y rotarlo.
