### ISSUE TITLE
Recorrección actividad 4

### ISSUE THREAD

**Issue by sebacruzd** [IIC2233-2016-02/Syllabus#515]
Hola,

Mandé a recorregir la AC04, pero nunca me llegó un mail diciendo qué commit se revisaría ni nada que indicara que se va a recorregir.
En la primera corrección dice que no hubo entrega.
En el issue de la corrección dejé un comentario con el commit correspondiente a la actividad.

Gracias de antemano.

**Comment by aaossa** [comment]
Hola @sebacruzd mandame un mail con tu caso para ver qué se puede hacer (han pasado 2 meses desde la AC :eyes: ).
