### ISSUE TITLE
Rotación de imágenes y detectar múltiples teclas.

### ISSUE THREAD

**Issue by rrfoster** [IIC2233-2016-02/Syllabus#516]
Tengo un par de dudas, primero es posible cambiar el eje de rotación de un pixmap. Y segundo como se puede detectar múltiples teclas que sean presionadas simultáneamente para lograr las 8 direcciones del enunciado.

gracias de antemano.

**Comment by FernandoPieressa** [comment]
Busca en google siguiendo las instrucciones de la ayudantia.

Saludos!

**Comment by npcariman** [comment]
me sumo a la duda, también he googleado bastante pero no he encontrado nada que sirve realmente

**Comment by dagalloso** [comment]
+2 también he buscado como procesar multiples teclas y he encontrado una forma que permite detectarlas, pero cuando se mantienen presionadas las detecta como sólo una vez :(

**Comment by fvr1** [comment]
[Hint](http://stackoverflow.com/questions/7176951/how-to-get-multiple-key-presses-in-single-event)

**Comment by Iruretagoyena** [comment]
@fvr1  Gracias !! Me sirvió muchísimo.
Algún hint para la rotación 👀?

**Comment by fvr1** [comment]
![1685291](https://cloud.githubusercontent.com/assets/13739465/19898397/9878f9a0-a03a-11e6-9087-4ca8e572dcd4.jpg)

**Comment by fvr1** [comment]
@Diiru eso es más googleable! 👀 jajaja
