### ISSUE TITLE
Mi tarea se crashea

### ISSUE THREAD

**Issue by fabraghetto** [IIC2233-2016-02/Syllabus#517]
Mi programa se crashea si es que apreto muchas teclas de movimiento ("wasd") en poco tiempo, o si pongo los controles v2 (en el menu de pause). Llevo intentando solucionar este problema varias horas y necesito ayuda. Por lo que pude averiguar probando es que se crashea por culpa de los Qthreads del archivo "Clases_entidades", pues si le pongo un sleep al run más grande no se crashea con tanta facilidad (actualmente tengo un sleep de 0.1).

Agradecería si alguien revisará mi código que acabo de pushar o si me dice a priori que hacer, pues ya no se que hacer y me quede pegado en este problema practicamente todo el día.

**Comment by fvr1** [comment]
La revisé y en los threads que tienes, en el `run` usas un `while True:`  pero nunca haces `break` o algo para terminar el thread (recuerda que un thread deja de funcionar cuando termina de leer el código en el método `run`). Puede ser por esto que se cae tu programa, ya que dsp de tirar muchas balas éstas se están moviendo infinitamente por ahí. ¡Cambia eso y avísame cómo te va!

**Comment by fabraghetto** [comment]
Gracias por responder, lo implementaré en las balas, sin embargo no se me crashea por culpa de las balas, pues se me crashea de antes de haber escrito la existencia de las balas. Puedes probar esto si es que no disparas nunca y te mueves en diferentes direcciones en poco tiempo, o poniendo los controles 2

**Comment by fgvenegas** [comment]
Hola !
Te recomiendo trabajar las balas como QTimer, echale una leída a #488 si no lo has hecho aun
Saludos!

**Comment by fabraghetto** [comment]
Oka ! , pero insisto que mi problema no es con las balas :( (no se me crashea por eso)

**Comment by fvr1** [comment]
Ok, lo revisaré de nuevo. Igual hay otra cosa, para coordinar el tanque con el mouse vas cambiando la imagen con cada posición nueva del mouse, te recomiendo que vayas rotando la imagen, es menos carga para el computador.

**Comment by fabraghetto** [comment]
Ok, si hice eso porque al rotar no tenía bien el eje de rotación, pero aún así no creo que esa sea la razón de porque se caiga, pues si me quedo quieto y roto la torreta a la velocidad de la luz, no se cae. Pero a ti se te cae cuando lo pruebas ya presionas muchas teclas "wasd" en poco tiempo ??, quizás es mi computador

**Comment by fvr1** [comment]
Es que a veces sí y otras no, entonces todavía estoy averiguando que pasa....

**Comment by andresbannuraschultz** [comment]
Estoy igual, a veces cuando chocan balas entre si se cae y no he podido cachar por que, ayuda porfa!

**Comment by otro-felipe** [comment]
El error que me da tu programa es el 0xC0000374. Lo googlié y dice que es un problema con el heap (probablemente estás usando demasiada memoria).  A mi tu programa no me crushea al menos hasta que disparo una bala. Fíjate en la función Actualizar_iamgen, está haciendo demasiado trabajo y crea QPixmaps nuevos cada vez que es ejecutada, te recomendaría intentar optimizar esa parte de tu código (quizás cargar los pixmaps en variables y esas variables en vez de llamar al constructor de QPixmap cada vez que se ejecuta el código).

**Comment by fabraghetto** [comment]
Perfecto !!, eso era, era el hecho de crear los pixmaps a cada rato, los guarde todos los que necesitaba en una lista y reutilizandolos ya no se me cae, gracias por darte el tiempo de ayudarme
