### ISSUE TITLE
Threads

### ISSUE THREAD

**Issue by npcariman** [IIC2233-2016-02/Syllabus#518]
Una duda, que  si no uso Threads directamente y uso un tick periodico, va a tener penalización en la nota?
en el fondo en vez de hacer una tarea Asincrona haría una Sincrona

**Comment by fgvenegas** [comment]
Si tu tarea es Sincrona como puede hacer que por ejemplo dispares y tu tanque pueda seguirse moviendo sin tener que esperar que la bala finalice su trayecto y a la vez todos los tanques enemigos se muevan también ?

**Comment by npcariman** [comment]
Según el materia de clases, una simulación sincrona todo se divide en pequeños periodos de tiempo, de esa manera podría ahorrarme usar Threads, ya que voy llamando en mi tick todo lo que se debe mortrar en la gui, pero no se si me bajaran puntaje por hacerlo así

**Comment by FernandoPieressa** [comment]
Hola! La idea es que vayan aprendiendo los contenidos del curso con las tareas, por lo tanto en esta tarea cuyo objetivo es aprender interfaces graficas y threading, es necesario que utilices threads y tu nota SI se vera penalizada si lo haces sincrono. Ademas que te va a quedar peor y generara mas problemas si lo haces con ticks. Saludos!

**Comment by smargozzini** [comment]
y se puede usar solo Qtimers? o es obligacion el uso de Qthreads?
saludos

**Comment by jgmontoya** [comment]
Hola,
Sí, pueden hacerlo solo en base a QTimers si así lo estiman conveniente!
Saludos!
