### ISSUE TITLE
Duda administrativa sobre cantidad de tareas

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#519]
Hola! Quizas lo han mencionado, pero no lo tengo claro, cuantas tareas son al final? 7? Y lo otro, se borra alguna? En el programa del curso sale que no, pero otros semestres han hecho una recuperativa y se borra la peor, asi que queria saber como va a ser este semestre. Gracias!

**Comment by flobarrios** [comment]
Hola!! Tenemos planificadas 6 tareas pero cualquier cambio que hagamos será avisado.
Saludos!

**Comment by andresbannuraschultz** [comment]
Dale, gracias!
