### ISSUE TITLE
[Tarea 1] Medallas

### ISSUE THREAD

**Issue by sormazabal** [IIC2233-2016-02/Syllabus#52]
Hola!
Tenía una duda sobre cómo debemos almacenar las medallas. Se deben guardar con el nombre del Gimnasio donde se ganó la medalla o podemos sólo registrar que "el jugador tiene 8 medallas", por ejemplo.
Para clarificar, debemos mostrar que el jugador tiene las medallas:
1) "Ash tiene las medallas Cerulean, Viridian, Cinnabar.
o
2) Ash tiene 3 medallas.

Otra pregunta: Se puede ganar más de una vez la misma medalla?

**Comment by jgmontoya** [comment]
Hola!
- Debes especificar las medallas que tiene, no solo indicar el total de ellas.
- No se puede ganar la misma medalla dos veces pero si se puede pelear varias veces en el gimnasio.

Saludos!
