### ISSUE TITLE
problemas con el qthread de las balas

### ISSUE THREAD

**Issue by jbsaeza** [IIC2233-2016-02/Syllabus#520]
Tenia un problema parecido al que presentaba un compañero en la issue #496 , el problema que se soluciono solo, tras mucho tiempo de googleo llegue a algo que CASI funciona pero extrañamente no me ejecuta bien el run() de mi bala,  si pudieran revisar mi código para cachar bien cual es el error seria espectacular, para correrlo hay que ejecutar menu_inicial y se esta instanciando la clase bala en el método disparar de la clase tanque. Al poner un print("algo") en el run este aparece en la pantalla como se espera pero el resto no. La solución que estaba intentando darle a este problema viene de http://stackoverflow.com/questions/20324804/how-to-use-qthread-correctly-in-pyqt-with-movetothread

**Comment by FranciscoLarach** [comment]
Hola! Me sumo al problema! a mi me arroja un "QThread: Destroyed while thread is still running" y busque en internet y creo que estaba en una issue de semestres pasados pero no logre entender.
(Puede ademas que disparen medio mal, pero creo que de verdad necesito poder entender esto para avanzar en la tarea y no encuentro algo que entienda bien en internet o aplique a mi problema).
Otra cosa es que mi programa por alguna razón solo sigue al mouse mientras esta apretado y lo realice según lo leído en issues acá e internet, así que dispara con el space momentáneamente. 
Se tendría que correr el modulo Niveles.py!
Gracias!!!

**Comment by jbsaeza** [comment]
Ya lo arregle, cada vez que hacia click se creaba una una nueva bala con su respectivo QThread, asi que hay que almacenar ambos en alguna parte, es algo un poco obvio pero no habia dado cuenta de ese detalle xD.
@FranciscoLarach A mi igual me pasaba lo del mouse, lo solucione al hacer que mi clase heredara de MainWindow, y asi funciono magicamente, hay una issue con una solucion alternativa en las issues cerradas.
