### ISSUE TITLE
Posible problema de herencia

### ISSUE THREAD

**Issue by Gonzalo-Perez** [IIC2233-2016-02/Syllabus#521]
Tengo problemas haciendo que una clase herede de Qwidget y de QThread.
Me imagino que se genera el problema del diamante con QObjects al no usar super() pero no estoy tan seguro de que eso sea lo que está pasando.
Es eso posible o simplemente lo que estoy tratando de hacer está mal?

De antemano, gracias.

**Comment by fvr1** [comment]
Cuál es el error que te tira? y por qué no usas `super`?
