### ISSUE TITLE
Donde se captan los eventos Tarea 5

### ISSUE THREAD

**Issue by Gonzalo-Perez** [IIC2233-2016-02/Syllabus#522]
Mi duda es algo básica pero todavía no entiendo bien lo siguiente:
Cuando quiero "captar" eventos como los KeyPressEvent todo eso debe hacerse en la MainWindow de la gui y luego enviar señales a los threads que hacen cosas o hay una forma de hacer que los threads estén captando los eventos por separado?

De antemano, gracias.

**Comment by fvr1** [comment]
Lo que se hace es la primera opción que dijiste, la MainWindow capta los eventos como cuando se apreta una tecla o se mueve el mouse y a partir de eso le puede mandar a los otros threads. Para la interacción entre threads debes usar señales, en la ayudantía vimos un ejemplo con señales, te recomiendo basarte en ese!
Y otra cosa, a qué te refieres con captar eventos por separado?

**Comment by bvfernandez** [comment]
holaa @fvr1 quería aprovechar de preguntar si es lo mismo que se capten los eventos en un central widget de la ventana o tiene que ser si o si en la MainWindow? graciaaas

**Comment by Gonzalo-Perez** [comment]
Me refería a captar eventos de forma paralela.
Por ejemplo (no sé si los QWidget lo harán paralelizado aunque no creo) cuando reviso los KeyPressEvent, los hago todos en la ventana principal (Qwidget) dentro de un mismo bloque, es decir así:

``` python
    def keyPressEvent(self, e):

        if e.key() == QtCore.Qt.Key_X1:
            cosass...
        if e.key() == QtCore.Qt.Key_X2:
            cosass...
        if e.key() == QtCore.Qt.Key_X3:
            .
            .
            .
            etc
     def mouseMoveEvent(self, event):
         cosass...
            .
            .
            .
            etc
```

Y me gustaría saber si se pueden hacer Threads por ejemplo que revisen estos eventos y otros eventos de forma paralela (que no tengan que ser verificados dentro de la clase de la ventana principal).
