### ISSUE TITLE
Ayura

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-02/Syllabus#523]
Hola ! 
Algún ayudante podría ver mi T05 ?
Si mueven el tanque principal (ignoren que nada funciona), en la primera muralla, el tanque obedece los limites excepto en la parte de más arriba. Por que es ? Use el widht y height de la muralla misma. Puede ser que la imagen se este saliendo del label ?

Gracias por el tiempo ! Saludos

Edit: También, las balas salen cuando quieren; a veces se lanzan y a veces no. Por qué será ?

**Comment by aaossa** [comment]
Tu pregunta es demasiado amplia, nos estás preguntando por qué pasan cosas en tu propia tarea. Trata de reducir tus dudas a preguntas puntuales y abre una issue al respecto.
