### ISSUE TITLE
Problema QTimer

### ISSUE THREAD

**Issue by srvasquez** [IIC2233-2016-02/Syllabus#525]
Hola llevo mucho tiempo intentando que se ejecute el start de mis balas, pero no me funciona, mi codigo esta arriba el archivo de las ballas es Bullets.py no se si me puedan ayudar :((

**Comment by fvandeputte** [comment]
A mi me pasaba lo mismo, quizas intenta con guardar el timer (si es de una clase) en un atributo (lo lei en internet) , pues si no se "pierde" el timer.

**Comment by aaossa** [comment]
> A mi me pasaba lo mismo, quizas intenta con guardar el timer (si es de una clase) en un atributo (lo lei en internet) , pues si no se "pierde" el timer.

Mas sobre [garbage collector](https://es.wikipedia.org/wiki/Recolector_de_basura)

**Comment by srvasquez** [comment]
Muchas Gracias, no se porque se "pierde" si las balas están en una atributo de lista, pero si son un atributo funciona, lo importante es que funciono 💃
