### ISSUE TITLE
Qt Designer 

### ISSUE THREAD

**Issue by Tibrahm** [IIC2233-2016-02/Syllabus#526]
No encuentro el Qt Designer, descargue PyQt con anaconda pero no lo puedo pillar en ningun lado

**Comment by aaossa** [comment]
Para encontrar donde debería estar QtDesigner en tu SO, sigue las instrucciones de la ayudantía sobre el tema 

**EDIT:** Recien vi que dijiste "con anaconda", nosotros no recomendamos instalarlo de esa forma por lo tanto no podemos ayudarte :cry:

**Comment by vacodoceo** [comment]
Yo tambien lo instale por anaconda y lo encontre aplicando control F en C: buscando designer.exe.

**Comment by fvr1** [comment]
Yo uso anaconda, en mi caso está en `Anaconda3/Library/bin`.
Por lo general los `.exe` se encuentran en alguna carpeta `bin` (para la próxima que te toque buscar algo como eso) 😄 
Saludos
