### ISSUE TITLE
Duda general github tareas

### ISSUE THREAD

**Issue by Gonzalo-Perez** [IIC2233-2016-02/Syllabus#527]
Cuando entregamos una tarea, ustedes (el cuerpo docente) guardan en alguna parte nuestro último commit válido (por cuanto tiempo)??
Hago esta pregunta porque tengo entendido que al final del año hay una instancia de recorreción donde se pueden ver detalles de tareas pasadas y me pregunto, qué pasa si es que alguien hace un commit y sobreescribe algo de una tarea pasada?

De antemano, gracias.

**Comment by aaossa** [comment]
Los commits de **todas las evaluaciones** quedan indicados en la issue de cada evaluación ("commit a revisar"). Teniendo el commit podemos volver al estado del repo en ese momento (tanto vía web como localmente) :grin:
