### ISSUE TITLE
Nota Control 5

### ISSUE THREAD

**Issue by domingo-valdes** [IIC2233-2016-02/Syllabus#528]
Hola! Cómo debería proceder si es que me falta la nota del control 5? Yo di el control, pero me aparece la casilla en blanco en la tabla de notas.
De antemano, gracias

**Comment by fgvenegas** [comment]
Hola! hay un control sin nombre, el jueves un ayudante se contactara contigo en clases, por lo que es necesario que andes con un control antiguo para compararlos y asegurarnos que es el tuyo

Saludos!

**Comment by domingo-valdes** [comment]
Muchas gracias! Disculpen las molestias  😕  , voy a intentar que no pase nuevamente.
No se si tenga controles antiguos, pero les voy a mostrar un cuaderno
