### ISSUE TITLE
Piedad :( 💔

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#529]
Podrían dar unos dos días más para poder terminar bien la tarea? :( Google se ha portado mal y me ha tenido días buscando cosas T.T 
Gracias 
PD: necesitaba desahogarme

**Comment by domingo-valdes** [comment]
El pueblo clama por piedad! A mi me robaron el computador 😢

**Comment by vigazali** [comment]
¡¡Sii por favor!! muy de acuerdo con @narierao, esta tarea, al menos a mí, me ha resultado muy difícil por todo lo que hemos tenido que averiguar por nuestra cuenta! :'(
Le he dedicado muchas horas y muuy poco avance...
Piedad... Gracias!!

**Comment by flobarrios** [comment]
Hola! tienen hasta el sábado 5 a las 23:59. Sin embargo, quiero recalcar que parte importante del curso es aprender a averiguar cosas por cuenta propia. Saludos!!

**Comment by narierao** [comment]
:o los amo <3

**Comment by Nebula2028** [comment]
muchas gracias! puede significar vivir o morir :+1:

**Comment by vigazali** [comment]
Graciaaaass!! Y si, era de vida o muerte...!! 😟

**Comment by kcsss** [comment]
![](http://generadordememesonline.com/media/created/ktmvtq.png)

**Comment by ceyzaguirre4** [comment]
Es correcto asumir entonces que se alarga el plazo de entrega del readme tambien?
Gracias

**Comment by flobarrios** [comment]
Si!
