### ISSUE TITLE
Preguntas presenciales

### ISSUE THREAD

**Issue by Gonzalo-Perez** [IIC2233-2016-02/Syllabus#530]
Quisiera saber si hay algún lugar y horario en donde haya algun(a) ayudante dispuesto a responder dudas de forma presencial? Claro que lo mejor es preguntar con los issues para qué todo el mundo pueda acceder a la información pero es para saber en el caso de que tenga una duda corta pero difícil de explicar en una issue.

De antemano, gracias.

**Comment by flobarrios** [comment]
Hola! [aquí](https://docs.google.com/a/uc.cl/spreadsheets/d/1LsXK3z-LX9bQlqfpm1T9qccvqKxbgpSXRUK15ulNMUc/edit?usp=sharing) están los horarios disponibles. Saludos!!
