### ISSUE TITLE
AC13?

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#531]
Puede ser que no hay materia nueva esta semana?
Necesito saber qué vamos a hacer mañana cuanto antes. ¿Misma materia? ¿No hay actividad?
Gracias!

**Comment by andresbannuraschultz** [comment]
jaja tuve la misma duda, en el programa salia que entra serializacion! Ultima parte del ultimo html que subieron!

**Comment by cjgazali** [comment]
Mala mía... me retiro lentamente y en silencio...
