### ISSUE TITLE
utilidad de serializar

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#533]
Hola, no se si estoy entendiendo bien. Se supone que la gracia de serializar es poder almacenar los datos sin la necesidad de generar archivos no?. En el caso de que lo anterior fuera cierto, tecnicamente si yo quisiera salirme del programa, para utilizar estos datos posteriormente si o si debo crear un archivo o no? .-. como que es solamente para no escribirlo mientras se ejecuta el programa cierto?

¿Qué utilidad tendria lo anterior?  en el caso de que todo estuviera correcto.
Gracias <3

**Comment by ivaniadg** [comment]
Hola,

> Se supone que la gracia de serializar es poder almacenar los datos sin la necesidad de generar archivos no?

No. La idea es crear cosas que se pueden almacenar. De hecho la definición de wikipedia dice

> In computer science, in the context of data storage, serialization is the process of translating data structures or object state into a format that can be stored (for example, in a file or memory buffer, or transmitted across a network connection link) and reconstructed later in the same or another computer environment.

Saludos

**Comment by narierao** [comment]
oh gracias, es la mejor :D

**Comment by btkramm** [comment]
Creo que la situación que más te puede hacer sentido es cuando necesitas enviar la información correspondiente al estado de un objeto en tu aplicación por la Web. Así, el cliente podrá interpretar la información serializada y hacer algo al respecto con ella.

Saludos.

**Comment by narierao** [comment]
y eso lo vamos a ver pronto o no? :o

**Comment by aaossa** [comment]
Si

**Comment by narierao** [comment]
Gracias!
