### ISSUE TITLE
Problema con QTimers

### ISSUE THREAD

**Issue by cameneses** [IIC2233-2016-02/Syllabus#534]
Hola! Tengo un problema con QTimers en mi tarea y quería saber si hay algún ayudante que pueda echarle una ojeada a mi código.

Específicamente, al correr window.py y realizar un click sobre la ventana, debería pasar que la bala se mueva hacia la posición del click, sin embargo mi tarea se crashea o bien, no se realiza correctamente el desplazamiento. 
Las balas están definidas en bullets.py y lo que tengo es un QTimer para regular su movimiento.
Esto es específicamente en la línea 152 de window.py.

De antemano, muchísimas gracias!!

**Comment by Hernan4444** [comment]
@cameneses estaba revisando tu código y aquí el problema es que le estas pidiendo al Qtimer que se comporte como un Qthread, te recomiendo volver a echar una ojeada a #488 y si todavía tienes dudas, nos preguntas.

Saludos!!

**Comment by cameneses** [comment]
Muchísimas gracias!! Ya logré entender bien por qué es que mi tarea se caía con las balas!!
