### ISSUE TITLE
ayuda con el "hitbox"

### ISSUE THREAD

**Issue by jbsaeza** [IIC2233-2016-02/Syllabus#535]
Eh buscado muchisimo de como hacer para que una bala que este volando en el juego pueda saber cuando choca contra algo o no, lo unico que eh logrado descubrir es que esto se pueda hacer con QGraphicsScene y QGraphicsWidget, pero mas que esto no eh logrado encontrar.
Cualquier ayuda o guia es de utilidad. Gracias

**Comment by aaossa** [comment]
Hola, recuerda que el aspecto gráfico de tu aplicación debe ir separado de la lógica de la misma (por eso nacen el _frontend_ y el _backend_). Las balas representadas con un `QWidget` (como los que nombraste) son válidas porque indican como se presentan estos elementos, pero lo que hacen y cómo se comportan las balas es parte del aspecto lógico, no del gráfico. 

En resumen, busca cómo tratar "por debajo" (en la lógica de tu programa) los choques, no pienses en los elementos de PyQt, porque esta no es su funcionalidad. Esto debería llevarte a una mejor separación de las funcionalidades de tu aplicación. Espero te sirva :)

**Comment by iqacevedo** [comment]
Hola 
no sé si sea tan buena idea pero puedes usar window.childAt(x,y) para saber lo que hay en la ventana en las coordenadas x,y por lo menos con eso pude hacer los choques yop.
Saludos !

**Comment by jbsaeza** [comment]
muchas gracias @iqacevedo  y @aaossa , logre hacerlo :D

**Comment by DiegoAndai** [comment]
@aaossa Hola, una duda respecto a la diferenciación frontend/backend: ¿Un objeto de backend puede (debe) manejar QLabels? pregunto porque lo hice así, ya que en la ayudantía lo hicieron con un QThread que tenía labels, pero leyendo esto me entró la duda, ya que QLabel está destinado, según yo, a mostrar texto/imagenes, y sería más de frontend.

Muchas gracias.
