### ISSUE TITLE
feedback AC10

### ISSUE THREAD

**Issue by smargozzini** [IIC2233-2016-02/Syllabus#537]
hola!
me llego un feedback con un 1 en la actividad 10 pero yo tengo otra nota.
se podría arreglar esto?
saludos!
gracias de antemano

**Comment by bvfernandez** [comment]
a mi tambien!

**Comment by smargozzini** [comment]
Ahi me lego
gracias!

**Comment by aaossa** [comment]
Ya debería estar arreglado, cualquier problema avisen por aquí :ok_hand:

**Comment by sormazabal** [comment]
A mí me llegó un mail con un puntaje y el desglose  del feedback, pero en la nota sale un 1.0. :S

**Comment by aaossa** [comment]
@sormazabal si la suma de los puntos te da la misma nota que la nota que te aparece en el excel, no hay problema :ok_hand:
