### ISSUE TITLE
Problema Explosiones

### ISSUE THREAD

**Issue by srvasquez** [IIC2233-2016-02/Syllabus#538]
Hola hice mis explosiones con Qtimer pero no se ejecuta el start de la explosión, no se me ocurre el por qué ya que es prácticamente lo mismo que las balas y estas me funcionan perfectamente, mi código esta arriba.

**Comment by Hernan4444** [comment]
@srvasquez estaba revisando tu código y no es lo mismo que las balas, estas combinando la forma de trabajar de los Thread con la del Qtimer. Con ese información sé que seras capaz de encontrar el error. 
Saludos!!
