### ISSUE TITLE
Disparos en Qtimer

### ISSUE THREAD

**Issue by dagalloso** [IIC2233-2016-02/Syllabus#539]
Afectará en algo (la nota por ejemplo jaja) si los disparos se ejecutan con cierto "lag" de repente. Los estoy haciendo con Qtimers y cuando se disparan va todo bien, en un instante como que se ralentiza y  después sigue normalmente. Además si hay varias balas, estas cada vez van mas lento :/
No se si también hay alguna alternativa para que esto no pase...

**Comment by cjgazali** [comment]
Quiero volver a llamar la atención a #506, en el punto 1) , llámese 'el punto que todos ignoraron', que me parece no menor; el juego se me pone lento excepto si el tanque jugador anda por la esquina inferior derecha del mapa, aproximadamente. Es algo misterioso, de ahí el nombre del issue. Como dicen acá, pareciera ser un problema de QTimers, lo cual es triste. Una de las cosas que me hace creer que NO es un problema de implementación es que en el sector donde no se me relantiza funciona perfecto.

**Comment by DiegoAndai** [comment]
Trata de minimizar las operaciones que realizas lo más que puedas, cada QTimer ejecuta una función, por eso más balas = más lag. Trata de dejar sólo lo imprescindible.
