### ISSUE TITLE
[Tarea 1] Batalla termina con programon atrapado

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#54]
Como se clasifica una batalla que termina con el programon salvaje atrapado? Ganada o perdida? Para efectos de luego clasificarla. Ademas, se sube de nivel a los programones propios que participaron en la batalla?

**Comment by flobarrios** [comment]
Hola! queda a tu criterio pero debes especificarlo en el README. Puedes considerarla ganada y que no suban de nivel, ganada y que suban de nivel, ni gana ni perdida, etc. Saludos!

**Comment by andresbannuraschultz** [comment]
Gracias!
