### ISSUE TITLE
QTimers - Programa lento en una zona del mapa

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#540]
Quiero volver a llamar la atención a #506, en el punto 1) , llámese 'el punto que todos ignoraron', que me parece no menor; el juego se me pone lento excepto si el tanque jugador anda por la esquina inferior derecha del mapa, aproximadamente. Es algo misterioso, de ahí el nombre del issue. Pareciera ser un problema de QTimers, lo cual es triste. Una de las cosas que me hace creer que NO es un problema de mi implementación es que en el sector donde no se me relantiza funciona perfecto. Me encantaría explicarme esto... va más allá de la nota, el juego sería choro si hiciera caso. Como no hace caso, es fome y me molesta. Los ayudantes entusiastas pueden revisar mi programa. Basta con que ejecuten `stage1.py` en la carpeta `stages`. No tengo ninguna razón para creer que threads sería mejor, pues son cosas que deberían funcionar siempre y también me han dicho que los threads se ponen lentos.

**Comment by domingo-valdes** [comment]
Con threads no mejora la cosa, tengo el mismo problema.

**Comment by DiegoAndai** [comment]
Hola, está raro eso jajajaja, el problema se mantiene sin importar que hay cerca del tanque? o no hay nada cerca? se me ocurre que si tienes algún algoritmo para detectar colisiones, se pondría más lento con cosas cerca... pero es sólo una idea. No creo que sea un problema de pyqt, yo hice casi todo con QTimers y ni un problema relacionado a la posición.

**Comment by cjgazali** [comment]
El tanque puede estar solo en el mapa o puede estar lleno de cosas. Siempre se pone lento cuando entra en la misma zona de la ventana, y mientras esté en la esquina inferior derecha aproximadamente funciona perfecto.

**Comment by vigazali** [comment]
Estoy con el mismo problema!!!

**Comment by Diiru** [comment]
Sale su cambio de fecha de entrega hasta la programaton del miércoles ?

**Comment by aaossa** [comment]
Hola @cjgazali , corriendo tu código me funciona perfecto, quizás no tienes la versión mas actualizada de tu código en tu repo. Podrías subirlo o activar todo para reproducir tu problema? Gracias

**Comment by aaossa** [comment]
@vigazali me ocurre lo mismo que arriba. Probé tu código (`algo.py` y `level.py`) y puedo moverme sin problemas, no se pone lento. Te pido que actualices tu código o subas la configuración con la que se presenta el problema para darle una mirada :ok_hand: . Gracias

**Comment by aaossa** [comment]
@domingo-valdes esto es lo mismo que se solucionó en #542 cierto?

@Diiru no

**Comment by cjgazali** [comment]
@aaossa gracias por el comentario... lo que pasa es que cambié algunos parámetros en mi archivo de constantes para que sea más 'liviano'... el problema en el fondo sigue, pero si te parece perfecto me quedo con las nuevas constantes y me olvido. No me deja de dar curiosidad por qué ocurren estas cosas así que ya que lo dices te comento que la única diferencia relevante son los parámetros "timing" y "speed". Como voy a estar subiendo versiones con las configuraciones nuevas, te cuento que en "timing": 10 y "speed": 1 se nota el problema. Probablemente los encuentres en 50 y 5 respectivamente, pero ahora estará arriba una nueva  versión con 10 y 1, al menos un rato.

**Comment by aaossa** [comment]
La versión que tengo está con `timing: 10` y `speed: 1` y anda mucho mejor que la de 50 y 5. Comenta esto en tu README y si algun tareo tiene algun problema con esto se pronunciará aca :ok_hand:

**Comment by Hernan4444** [comment]
@cjgazali acabo de probar tu código (recien) y te recomiendo dejarlo en 10,1 cuando lo subas pero que especifiques en el README que a ti te funciona mejor con otro timing y speed para probar por si acaso.

Saludos!!

**Comment by domingo-valdes** [comment]
@aaossa si, efectivamente era el problema de los connect, muchas gracias!

**Comment by vigazali** [comment]
@aaossa Perdón, no había hecho commit de lo último. Ahora lo hice. Otra cosa es que no sé qué hacer para que no se ponga tan lento cuando disparo balas. Mientras más balas más lento. Es un problema de dónde o cómo estoy llamando los QTimer??
Sería bacan si lo puedes ver (o cualquier ayudante). Muchas gracias!!

**Comment by cjgazali** [comment]
@aaossa y @Hernan4444 muchísimas gracias!! Tendré muy en cuenta lo que me dicen, procuraré entregar con 10,1 y voy a resumir un poco esta historia en el README. Voy a explicar todos los parámetros importantes.
