### ISSUE TITLE
Problema al abrir la tienda

### ISSUE THREAD

**Issue by smargozzini** [IIC2233-2016-02/Syllabus#541]
tengo una ventana que se abre cuando entro a la tienda, esta tiene muchos botones que sirve para comprar las cosas. A cada botón le pongo self.boton.clicked.conect(self.funcion) y llega un punto en que trato de abrir la ventana y python no la abre y deja de correr el programa sin poner ningún error...
alguien sabe como solucionar esto?
si saco la función self.boton.clicked.conect(self.funcion) de algunos botones esta ventana se abre perfectamente sin tener errores

**Comment by smargozzini** [comment]
También se abre una ventana que dice "python se a cerrado inesperadamente"

**Comment by aaossa** [comment]
1) Cual es tu pregunta? Alguna tesis? Qué intentaste?
2) No pude correr tu código porque no están todos los archivos:  `FileNotFoundError: [Errno 2] No such file or directory: 'tienda.ui'`. 

PD: No "_hardcodees_" paths a las imágenes, sino al ayudante corrector no le va a funcionar tu tarea. A mi no me funciona asi que no puedo hacer nada :cry:

**Comment by smargozzini** [comment]
1) no logro abrir la ventana tienda, no se porque. tengo para cada botón su función al hacerle click pero la ventana no se me abre. pero si borro la función que conecta a cada botón con lo que tiene que hacer de 5 botones si se me abre. quizás es algún problema de mi computador pero quería preguntar de todas maneras
2) lo acabo de subir de nuevo. lo de las imágenes lo arreglo despues

**Comment by aaossa** [comment]
Ya encontré tu error. Prueba poniendo prints entre tus funciones para encontrar el error (una especie de _debugging_), dale una mirada a la clase de tu Tienda para encontrar qué falla.

**HINT:** Les hemos dicho que eviten usar `ñ` y tildes en sus códigos por temas de encoding.

**Comment by smargozzini** [comment]
cambie la ñ por una n y se arreglo todo pero no entiendo porque pasaba el error.
gracias por la ayuda!
