### ISSUE TITLE
Lentitud del programa

### ISSUE THREAD

**Issue by domingo-valdes** [IIC2233-2016-02/Syllabus#542]
El código en mi programa funciona como se nos pide, pero por alguna razón se va volviendo lento a lo largo del tiempo, llegando a hacerse insoportable en cierto punto. Quería saber, en primer lugar si es que habrán descuentos por tener un código no optimizado que funcione, pero lento. En segundo lugar quería saber si nos pueden dar tips para optimizar la velocidad, ya que a pesar de que no es el objetivo de la tarea, puede entorpecer su corrección (Google es demasiado general). 
PD: Cualquier mirada a mi código por el tema de velocidad es bien recibida  :)

**Comment by domingo-valdes** [comment]
He intentado aumentando el time.sleep por un tiempo mayor, pero aun así, después de un rato los threads que indican qué hacer a cada tanque se comen mi cpu y el juego se queda pegado.

**Comment by jtagle2** [comment]
@domingo-valdes, ejecuté tu código, y al parecer es extremadamente lento porque algunas cosas de tu código estan implementadas de manera MUUY poco eficiente, no es por el time.sleep de tus threads.
Ejecuté tu juego, y comencé una etapa. Al momento de empezar, el juego me usaba 23 mb de memoria (aprox). Luego lo dejé sin hacer absolutamente nada (sin disparar, moverme, etc...) y después de un minuto de ejecución, ya me estaba usando 86 mb de memoria ¿Por qué? Si no hice nada :cry: .
**Hint**: Revisa el run de tu clase ActuarEnemigo.
**Hint sobre el Hint**: Revisa como estas manejando las señales.
Espero te sirva, Saludos.
pd: Si arreglas eso, te funciona perfecto, y puedes disparar todas las balas que quieras y no se cae.

**Comment by domingo-valdes** [comment]
Gracias! Por si a alguien más le sirve, el error es que los connect estaban puestos dentro del ciclo, por lo que se estaban generando una cantidad inmensa de de ellos.
