### ISSUE TITLE
Duda existencial excepciones

### ISSUE THREAD

**Issue by DiegoAndai** [IIC2233-2016-02/Syllabus#545]
Hola! tengo una duda, ¿las excepciones debieran ocuparse como parte del desarrollo lógico del programa? Obviamente si no hay otra opción por estar trabajando sobre código externo o algo por el estilo, hay que ocupar excepciones, pero si hay un error que puede pasar, producido por mi programa, ¿es aceptable ocupar error handling para manejarlo?

Por ejemplo si estoy sacando valores de una lista, es aceptable la forma:

```python
lista = [1, 2, 3]
i = 0
while True:
    try:
        next_item = lista[i]
        i += 1
        return next_item
    except KeyError:
        return None
```

o sería incorrecto/mala practica, ya que hay otras formas de hacer esto sin manejo de errores. Ese es un ejemplo un poco burdo pero creo que se entiende la idea general: es válido un manejo así si el error puedo evitarlo yo, cambiando mi programa, por más fácil/díficil que sea cambiarlo.

Saludos!

**Comment by sebacruzd** [comment]
Como dices, tu ejemplo es un poco burdo ya que simplemente puedes hacer:

```
if lista:
    return lista.pop()
```

Pero si hay un código en el que no tienes manera de evitar los errores/casos excepcionales, no creo que esté mal el try/except.

Por lo que entiendo, si manejas correctamente cada excepción y sabes que en los casos que se llega a una excepción el programa sigue bien y no le falta ningún dato (dado por el except), no habría problema.
El problema y mal uso del manejo de excepciones es cuando usas por ejemplo un:

```
except:
    hacer_algo_general
```

Ya que estarías omitiendo excepciones diferentes que tienen distintas repercusiones en el programa, a menos que solo haya una excepción.

Esto es mi entendimiento del manejo de excepciones, si estoy equivocado corrijanme por favor.

**Comment by DiegoAndai** [comment]
Por eso, mi pregunta es si es evitable el try/except, ¿es una mala práctica usarlo?

**Comment by ivaniadg** [comment]
@DiegoAndai Sí.

Try/Except se debe usar cuando existe la posibilidad de que ocurran errores y cuando ocurren no es posible continuar con el funcionamiento normal del programa. En general se usan cuando se necesita del input del usuario o se trabaja en red.

**Comment by DiegoAndai** [comment]
Gracias 😃
