### ISSUE TITLE
Velocidad disparos NPC's ( + múltiples )

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-02/Syllabus#547]
Hola !
1. Que tan rápido sugieren que disparen los tanques ? 
( Asumí que debía haber un timer, si no, disparan miles y el juego es muy difícil)

2. En el modo normal; también se deben guardar los highscores ? Esto debe pedirse abriendo otra ventana que reciba el nombre o puede ser en la misma ventana ?

3. Implemente la rotación del cañon (en el usuario) pero se mueve muy raro y desaparece a ratos, algún ayudante podría ver el código ? Toda la info del cañon esta en el archivo "Clases".

4. Importa si los cañones de los NPC's pasan por arriba de las murallas ? El tanque no lo hace, pero a veces en los tanques giratorios una parte del cañon pasa por arriba.

5. A veces mis powerups caen arriba de las murallas (ambos de posiciones aleatorias). Igual se pueden agarrar, por el rango que le dí, pero igual se ve feo. Esto podría descontar ?

Gracias de antemano !

**Comment by Diiru** [comment]
GG.
