### ISSUE TITLE
Tanque quieto

### ISSUE THREAD

**Issue by dfvasquez** [IIC2233-2016-02/Syllabus#549]
Hola,

Tengo una duda con la definición del tanque quieto, con "te atacará si estás en su línea de visión". ¿Los tanques enemigos no giran su cañón para atacar al tanque principal? Si no es así, el tanque quieto atacaría solo si está en frente de él? 
Por ejemplo, si el cañón está apuntando hacia la derecha y mi tanque pasa por la coordenada (x+algo,y) del tanque quieto, solo en ese caso le dispararía?

Espero haber sido clara con mi ejemplo jajaja
Gracias :)

**Comment by vjbreton** [comment]
Lo que yo entiendo es que el tanque quieto si debería mover su cañón, pero no va a disparar si hay una muralla o un tanque enemigo entre los dos, osea que con "línea de visión" se refiere a que hay un camino limpio para disparar

**Comment by FernandoPieressa** [comment]
Hola!  El tanque quieto no debe poder transladarse de su posicion pero queda a tu criterio si puede rotar en si misma, y a donde apunta es su linea de vision.

Cabe destacar que como solo exigimos el uso de cañon y cuerpo del tanque por separado en el tanque  principal, puedes hacer que rote todo su cuerpo si quieres hacer que pueda girar en si mismo.

Saludos!.

**Comment by dfvasquez** [comment]
Pensé que eso del cañón y tanque por separado era para todos los tanques 😮  Entonces queda a mi criterio donde apunta, gracias!! 😄
