### ISSUE TITLE
[Tarea 1] batalla y captura

### ISSUE THREAD

**Issue by FranciscoLarach** [IIC2233-2016-02/Syllabus#55]
Si al debilitar a un programón en la hierba, se deja su hp en 0 ¿se puede asumir que esta capturado? ¿o debo preguntar al usuario si desea capturarlo?

**Comment by FernandoPieressa** [comment]
![dfdfs](https://cloud.githubusercontent.com/assets/13782155/17715466/9547c230-63da-11e6-916f-d59dd326b705.PNG)

Por lo tanto se tiene que dar la opcion. No se asume capturado.
Saludos!

**Comment by FranciscoLarach** [comment]
Mire lo mismo, pero después leí esto y me confundí porque al dejar sus hp en 0 se acaba la batalla!
![batalla](https://cloud.githubusercontent.com/assets/20795271/17715680/48b3b250-63d3-11e6-876f-53f35f7d0402.png)
¿Pregunto igual? 
Gracias de antemano!!

**Comment by FernandoPieressa** [comment]
Me exprese mal, perdón. Me refería a que se tiene que dar la opción durante el combate Y NO AL FINALIZAR. Cuando su hp llega a 0 termina la batalla nomas.
