### ISSUE TITLE
Qthreads

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#550]
hice una clase que heredara Qthread y cuando le hago clase.start() me dice que no tiene este metodo.
¿Cómo inicio este Thread?

**Comment by aaossa** [comment]
No encontré en tu repo una clase que heredara de `QThread`. La clase que herede de `QThread` debería implementar el método `run()` y así puedes llamarlo con `start()`. Busca ejemplos en los que hereden de `QThread`para ver esto :ok_hand:

**Comment by narierao** [comment]
@aaossa ahi actualice el repo, defini el metodo como **run**() y como run() y en ninguno de los casos me lo acepto :c 

en el archivo tanque quieto herede QThread y lo ejecute en Definitivo linea 14-17
Muchas gracias

**Comment by aaossa** [comment]
@narierao estás heredando dos veces de `QObject` y eso no se puede hacer ([SO source](http://stackoverflow.com/a/17622472/3281097), [PyQt source](http://pyqt.sourceforge.net/Docs/PyQt4/gotchas.html#multiple-inheritance))

**Comment by jbsaeza** [comment]
Yo tenia un problema parecido y decidí no heredar de QThread y en vez de eso en el init de la clase cree un thread, que en conjunto con señales, hice que su target fuera un método que luego de hacer ciertas cosas emitiera la señal y que esta fuera recibida por una función del parent. Esperao que te sirva :D @narierao 
EDIT: acuerdate de decorar el metodo que va a estar emitiendo la señal con pyqtSlot()
