### ISSUE TITLE
mouse tracking

### ISSUE THREAD

**Issue by smargozzini** [IIC2233-2016-02/Syllabus#551]
Hola!
tengo un problema con seguir el mouse, cuando pasa mi mouse por la ventana se mueve bien el cañon pero al pasar por un lablel (fondo del juego) no me sigue el mouse...
alguien me podría ayudar con esto por favor e buscado mucho en internet y no puedo arreglarlo
o revisar mi código por si puse algo mal
gracias!

**Comment by seba-bug** [comment]
Hola! Al menos a mi se me arregló haciendo .setMouseTracking(True) para cada label que iba agregando... prueba a ver si funciona

**Comment by smargozzini** [comment]
ahi me funciono! gracias @sguerra2
