### ISSUE TITLE
Frontend vs Backend

### ISSUE THREAD

**Issue by Gonzalo-Perez** [IIC2233-2016-02/Syllabus#552]
La acción de cambiar (después de que ya haya sido "seteado" inicialmente) un QPixmap se debe hacer en el Frontend o está bien hacerlo en el Backend (si hago el "show()"  y la "actualización de la imagen" en el Frontend) ??

De antemano, gracias !

**Comment by aaossa** [comment]
Lo ideal sería que tu _backend_ le envíe el cambio al _frontend_ para que este lo haga, no se si se entiende mas o menos la idea
