### ISSUE TITLE
AC13

### ISSUE THREAD

**Issue by IgnacioTobar** [IIC2233-2016-02/Syllabus#553]
En la issue de la AC13 que me acaba de llegar, el commit a revisar es uno antiguo de la T05, en vez del que subí para la actividad. ¿Podrían volver a revisar eso, para que me evalúen el commit correcto? 
Debería ser el commit 9a9c8050c5234759349081e7b606adcc67bb058e (no se como lo hacen ustedes para que  linkee al commit correspondiente?)

**Comment by aaossa** [comment]
El commit que aparece indicado es el se corregirá. Si no aparece el commit con tu actividad es porque ese commit no estaba en tu repositorio al momento de hacer la recolección (poco después de las 16:55).

**Comment by IgnacioTobar** [comment]
El commit fue hecho antes de las 16:55, pero al final de la clase no pude subirlo porque me fallaba el internet. Lo hable con un ayudante en la sala y me dijo que cuando le hiciera push en mi casa igual aparecería con la hora cuando se hizo el commit (y en efecto aparece así), y que mientras no hiciera ningún cambio y subiera el commit tal cual, no habría problema. ¿ Entonces al final, que va a pasar?

**Comment by ivaniadg** [comment]
@IgnacioTobar  
Los casos particulares se resuelven por mail. @bamavrakis se contactará contigo.
