### ISSUE TITLE
Python 3.5 - Tarea 6

### ISSUE THREAD

**Issue by gabrielpinkman** [IIC2233-2016-02/Syllabus#557]
Hola, tengo una duda, en las especificaciones de la tarea se indica que se debe usar Python 3.5, sin embargo yo tengo muchos problemas al intentar instalar esa versión de Python, por lo que manejo la 3.4.3, hay algún problema si no me cambio a la 3.5? (De verdad estuve casi una semana intentando hacer funcionar la versión 3.5)

**Comment by aaossa** [comment]
Asegurate de que tu tarea se pueda correr en Python 3.5 y todo estará bien

**PD:** Solo agregar que las instrucciones para instalar sin mayores problemas la versión de Python del curso está en la Wiki. Espero lo hayas visto

**Comment by jgmontoya** [comment]
[Acá](https://docs.python.org/3/whatsnew/3.5.html) puedes leer acerca de las diferencias entre las versiones de Python 3.4 y 3.5

Saludos!
