### ISSUE TITLE
9.1 Mensajería Interna 

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#558]
Cuando se habla de las especificaciones del chat, esto ocurre solamente afuera de la sala no? Es decir, esta el chat para adivinar la palabra y luego no puede existir otro chat dentro de la sala para hablar cierto? (Básicamente solamente pueden hablar como grupo fuera de la sala - sin estar jugando -)

**Comment by FernandoPieressa** [comment]
Hola! El chat de juego es diferente al chat afuera del juego.

El chat de juego se explica en el punto 5.3, y no necesita que implementes los requerimientos del otro (como los emojis, etc..)

Los del punto 9.1 son los requerimientos del que esta afuera del juego.

Ten en cuenta que el chat del juego del 5.3 igual puedes leer los mensajes de los otros compañeros (a menos que sea la palabra correcta) asique si se puede hablar por el mientras juegas.

Saludos!
