### ISSUE TITLE
Problema pasando de Python 3.4.x a 3.5.2

### ISSUE THREAD

**Issue by Nebula2028** [IIC2233-2016-02/Syllabus#56]
- **WINDOWS 7 64 bits:**
- **Python 3.5.2:**
- Foto del error:

![captura_error_python](https://cloud.githubusercontent.com/assets/13741469/17715391/3edae742-63da-11e6-9725-46159213d093.png)
- Descripción del problema: Tratando de upgradear mi version de python de la 3.4.x a la 3.5.2 me pasó que instale el 3.5.2 con el instalador de windows que aparece en la guia de la wiki y luego me seguia saliendo que era la version 3.4 cuando iba a Inicio -> CMD-> python -V, entonces fui a los programas del panel de control y desinstale python 3.4 y luego todo se derrumbo.
  Trate desinstalando todo e instalando solo el ejecutable de 3.5 y tampoco me funciona
  El semestre pasado instale pip y python 3.4 y no tuve problemas, ahora no me funciona ninguno de los dos.

Ayuda porfavor!

**Comment by aaossa** [comment]
Y usando solo ’py -V’?

**Comment by jgmontoya** [comment]
Hola!

Qué te aparece si en la consola haces el siguiente comando:

```
echo $PYTHONPATH
```

**Comment by Nebula2028** [comment]
![captura_error_py](https://cloud.githubusercontent.com/assets/13741469/17716076/94ccb538-63dd-11e6-9d9a-ce658f74acb4.jpg)

**Comment by Nebula2028** [comment]
he buscado en google el ImportError: no module named "encodings" pero no encuentro soluciones en los threads the stackoverflow o git que hay por ahi :confused:

**Comment by jtagle2** [comment]
Hola!
Panel de control > Sistema y seguridad > Sistema > Configuración avanzada del sistema > variables de entorno.
Tienes alguna variable de entorno que se llame PYTHONHOME, o dentro de la variable de entorno PATH, tienes algo que apunte a python?

**Comment by Nebula2028** [comment]
![variables_entorno](https://cloud.githubusercontent.com/assets/13741469/17716389/debf20e4-63de-11e6-8c04-7fb99ee236a2.jpg)

**Comment by Nebula2028** [comment]
Tengo que editar PYTHONHOME y poner el path de donde se instaló Python35 ?

**Comment by jtagle2** [comment]
Si, prueba eso y avisas como vas.

**Comment by Nebula2028** [comment]
Lo hice y se solucionó, gracias maestro, sos un grande!
