### ISSUE TITLE
Blocking I/O

### ISSUE THREAD

**Issue by asimonv** [IIC2233-2016-02/Syllabus#560]
Hola! Algo que me está pasando es que cuando creo un `QTimer` o `QThread` corriendo para que se encarguen de escuchar si es que el servidor ha mandado algo, se me cae la GUI :-/
Qué debería usar para tener I/O asíncrono? (O al menos eso estuve leyendo)

**Comment by Hernan4444** [comment]
@asimonv revisando un poco el codigo que subiste, estaba usando Qtimer, intentalo con Qthread o Thread y nos comentas, por lo menos el semestre pasado para esta tarea use Qthread y no presento problemas

Saludos!!

**Comment by asimonv** [comment]
Además de eso, hice while 1 en el run() para que el cliente siempre estuviera escuchando el server y funciona! :) 

Gracias @Hernan4444 :)
