### ISSUE TITLE
Readme T05

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-02/Syllabus#562]
Hola !
Había escrito mi Readme en mi Pycharm, ya que lo tengo conectado con Github. La cosa es que se me olvidó hacerle push ayer. Puedo subirlo ahora ? O ya pasó ?

Gracias

**Comment by jgmontoya** [comment]
Hola,
Súbelo y si tienes suerte no tendrás descuento.
Ahora depende solamente de si al ayudante que le tocó revisar tu tarea ya lo hizo o no.
Saludos!
