### ISSUE TITLE
Argumento en eventos de PyQt

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#564]
```python
def paintEvent(self, e):
    qp = QtGui.QPainter()
    qp.begin(self)
    self.drawPoints(qp)
    qp.end()
```

este codigo esta en internet y no creo que haya problema en ponerlo... 
Duda, como es posible que utilicen la variable qt e ignoren completemente la variable e? :o imprimi esta variable y me sale <PyQt4.QtGui.QPaintEvent object at 0x7f081e3caee8> 
estoy muy perdido? o es otra de las magias de python3? xd

**Comment by aaossa** [comment]
Todo _event handler_ recibe un objeto que es un evento (suena raro pero es lo que dijiste). No veo lo raro, cuál es tu duda?
