### ISSUE TITLE
Funcionamiento 

### ISSUE THREAD

**Issue by Tibrahm** [IIC2233-2016-02/Syllabus#566]
por lo que entendi el cliente es un programa donde uno solo iteractua con la interfaz pero todo el proceso de datos se hace en el servidor o no? 
como ejemplo, cuando  vas a registrar a un jugador nuevo pones los datos a través del programa del cliente y estos se envían al servidor, que puede estar en otro computador, se hace todo el proceso de verificación y la todo, la información queda guardada en ese computador y se envía una respuesta de vuelta al programa del cliente?

**Comment by jgmontoya** [comment]
Hola,

Estás en lo correcto, en general la estructura cliente/servidor funciona así como lo describes, con la salvedad de que también se puede hacer procesamiento en el lado del cliente cuando sea pertinente.

Esto, en el caso de verificaciones de datos, tiene dos ventajas:
- Le reduce potencialmente carga al servidor al evitar recibir mensajes 'inútiles'
- Hace potencialmente más rápida la interacción para el usuario, ya que no debe enviar un mensaje al servidor y esperar por su respuesta.

Por ejemplo, si un usuario intenta registrarse sin ingresar una contraseña o nombre de usuario, entonces el cliente podría detectar esto y no enviar la 'solicitud de registro' al servidor y en vez desplegar un mensaje diciendole al usuario que le faltan datos o que sus datos son inválidos. Esto le evito parte del procesamiento al servidor y a su vez hace que esa verificación sea prácticamente instantánea para el usuario.

Es importante notar que esto no es un reemplazo a las verificaciones que se hacen del lado del servidor. Siguiendo con el ejemplo, el servidor igual debiera chequear que la combinación usuario/contraseña es válida antes de ingresarlo a la base de datos  y enviar la respuesta acorde al cliente.

Saludos!
