### ISSUE TITLE
Duda general sobre sockets, address y puerto

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#567]
Cuando quiero crear un socket servidor, y hago bind a un cierto IP y un cierto puerto, ese puerto corresponde a la maquina cuyo IP es el que estoy pasando como parametro cierto? Que impide que yo pueda crear un socket servidor con el IP de una pagina web cualquiera y escuche todas las request que se le hacen a dicha pagina? Muchas gracias (creo no estar entendiendo bien como funcionan los IPs, puertos y sockets)

**Comment by aaossa** [comment]
Hola, en teoría nada lo evita. Como se puede ver en [esta parte de la documentación](https://docs.python.org/3/library/socket.html#socket-families) "_host is a string representing either a hostname in Internet domain notation like `daring.cwi.nl` or an IPv4 address like `100.50.200.5`_". Como vimos en la ayudantía de ayer, solamente un socket a la vez puede estar en un puerto, por lo que si ya hay un programa escuchando las conexiones de esa página no te podrás conectar.

**PS:** Revisa la ayudantía

**Comment by andresbannuraschultz** [comment]
Dale muchas gracias!
