### ISSUE TITLE
Posible error 

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#569]
Hola! estoy probando un especie de Paint (que estoy diseñando y me funciona bien) pero cuando lo cierro, en mi consola aparece esto (escrito muchas veces), debo prestarle atencion?

```
(python3:4354): Gtk-CRITICAL **: IA__gtk_widget_realize: assertion 'GTK_WIDGET_ANCHORED (widget) || GTK_IS_INVISIBLE (widget)' failed
Violación de segmento (`core' generado)
```

**Comment by aaossa** [comment]
Solo te aparece eso? Alguna idea de en qué linea o módulo se podría estar generando?

**Comment by narierao** [comment]
Ni idea, simplemente aparece, y de verdad que el programa funciona super bien, hago rectangulos, circulos y lineas de colores. No logro entender la raiz del problema.
![captura de pantalla de 2016-11-08 23-55-11](https://cloud.githubusercontent.com/assets/20784195/20125811/d4ae556c-a60e-11e6-92ca-106e88b752e0.png)

Te adjunto una foto.

**Comment by aaossa** [comment]
Lo que encontré que al parecer soluciona el problema es usar `QApplication.setStyle` para definir otro estilo. Prueba eso, no cambiará las funcionalidades, solamente la apariencia de tu interfaz :ok_hand: 

**PD:** Podrías pushear tu código para darle una mirada también

**Comment by narierao** [comment]
@aaossa Muchas Gracias! ya no me lanza mas errores. Ahora, tengo otro problema, defini una grilla y no aparece en mi interfaz, y la agrego a todos lados y no se me muestra. como puedo saber que hacer? (actualizare mi repo)

**Comment by narierao** [comment]
Archivo Prueba.py, linea 142 a la 161.

**Comment by narierao** [comment]
@aaossa ya lo solucione! estaba seteando mal los valores. Gracias Igual!
