### ISSUE TITLE
[Tarea 1] Duda EV

### ISSUE THREAD

**Issue by The-Big-Lebowski** [IIC2233-2016-02/Syllabus#57]
Hola. No entiendo porque el EV no aparece dentro de la información de jugadores.json como el IV. En el json aparece un "id" aparte del "unique_id" ¿es "id" en el json lo que en el enunciado se llama EV?

**Comment by FernandoPieressa** [comment]
No son lo mismo, unique_id es por cada instancia del programon (Diferenciar 2 Bulbasaur). mientras que id es por tipo de pokemon (Ejemplo, Bulbasaur id 1,Venasaur id 3, etc..).

El jugadores.json es simplemente un ejemplo tal como sale en el nombre y la intencion era dar una idea de como estructurar la informacion de los jugadores. Tu puedes agregar EV sin problemas y hacer cualquier cambio a como guardas la informacion de jugadores mientras especifiques en el Readme.

Saludos!

**Comment by The-Big-Lebowski** [comment]
Ok, te entiendí.  Entonces, Los id's que aparecen en progradex (en jugadores.json) son de los unique_id ?

**Comment by R0W5tortion** [comment]
Como tengo entendido, la progradex reúne la información de todos los programones vistos/capturados, y solo entrega informaciones generales, las unique_id no tienen nada que ver ahí. Las id de la progradex son los identificadores de cada especie de programon (ej: bulbasaur es 1, mew es 151, y así para todo lo de en medio). La unique_id sirve para diferenciar dos programones iguales (ej: dos rhydon comparten la misma id, pero DEBEN tener unique_id distintos). Dicho esto, me gustaría saber si dos programones distintos (distinta id) podrían tener unique_id iguales para un mismo jugador?

Y volviendo al tema original, el enunciado aclara muy poco sobre las EV, solo sé que son requeridas para calcular stats y que varía entre 0 y un número grande. ¿Funciona igual que los IV (vale decir que se genera automáticamente cuando un programón es encontrado)?

Finalmente, respecto a los EV (y también los IV), cada programon tiene un solo valor para todos sus stats, o 6 valores distintos, uno por stat? (Y solo para aclarar, los stats deben ser enteros, ¿cierto?)

**Comment by Tomizaky** [comment]
Esta es mi duda también

Los IV son como la genética del programón y nosotros somos libres de agregar EV de la forma que queramos?

**Comment by jgmontoya** [comment]
Hola,

> me gustaría saber si dos programones distintos (distinta id) podrían tener unique_id iguales para un mismo jugador?

La idea es que sea un identificador único, no sé por qué querrías hacer eso...

>  cada programon tiene un solo valor para todos sus stats, o 6 valores distintos, uno por stat?

Cada programón solo tiene un IV y un EV.

>   (Y solo para aclarar, los stats deben ser enteros, ¿cierto?)

Están en función piso así que sí.

> Los IV son como la genética del programón y nosotros somos libres de agregar EV de la forma que queramos?

Tanto IV como EV deben ser generados de forma aleatoria (dentro de sus rangos respectivos). También es el caso que ambos no cambian para un mismo programón.
