### ISSUE TITLE
RGB

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#572]
El usurio debe ingresar R, G, B o hay que mostrar una rosa cromatica y que el seleccione un punto? :o

**Comment by rodolfopalma** [comment]
Basta que ingrese los valores de RGB, además de los 4 colores más usados. Si todavía no se cuenta con la información para determinar los 4 más usados puedes mostrar colores arbitrarios (negro, rojo, verde, azul, etc.).

**Comment by domingo-valdes** [comment]
Hay que controlar que el usuario ingrese un color válido o se asume que sabe lo que hace?

**Comment by narierao** [comment]
Controlar los colores igual es sencillo, los R,G,B siempre están entre 0 y 255 :3
