### ISSUE TITLE
Problema con los puertos

### ISSUE THREAD

**Issue by lfbesa** [IIC2233-2016-02/Syllabus#573]
Cada vez que trato de conectarme a un puerto me sale el siguiente error y no se como arreglarlo: 
```python
Traceback (most recent call last):
  File "C:\Users\felipe\Dropbox\Universidad\6° semestre\Programación Avanzada\Git\syllabus\Ayudantias\11 - Networking\Ejemplo - Chat\chat.py", line 84, in <module>
    client = Cliente(nombre)
  File "C:\Users\felipe\Dropbox\Universidad\6° semestre\Programación Avanzada\Git\syllabus\Ayudantias\11 - Networking\Ejemplo - Chat\chat.py", line 19, in __init__
    self.s_cliente.connect((self.host, self.port)) # El cliente revisa que el servidor esté disponible
ConnectionRefusedError: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
```

He probado con todos los ejemplos de la materia y de la ayudantía y ninguno me funciona. Alguna idea de como darle permiso a los puertos o como solucionar esto?

**Comment by jgmontoya** [comment]
Hola, 

Estás iniciando el servidor antes que el cliente?

Saludos!

**Comment by lfbesa** [comment]
No sabría como comprobar eso, es el ejercicio del chat de la ayudantía, que al poner C o S, en ninguno me funciona. Tampoco con los ejercicios del material de clase. Por ejemplo con: 

``` python
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
host = socket.gethostname()                           
port = 10001

s.bind((host,port))

s.listen(5)

cont = 0
while True:
    socket_cliente, address = s.accept()      
    print("Obtuvimos una conexión desde %s" % str(address))
    socket_cliente.send("{}. Hola nuevo amigo!\n".format(cont).encode("ascii"))
    socket_cliente.close()
    cont += 1
```

 Ahí después de hacer el accept se queda en un ciclo infinito también

**Comment by jgmontoya** [comment]
:thinking: 
En el ejemplo de la ayudantía, ¿En qué momento se cae? Inmediatamente al poner S?

**Comment by aaossa** [comment]
Con qué puertos intentaste? Además, como dijo Javier tienes que iniciar el servidor (S) antes que el cliente (C). Después de hacer `accept` no se queda en un loop infinito, se queda detenido en el `accept` (dicho en ayudantía)

**Comment by lfbesa** [comment]
Justo al inicializar la clase, después de poner el nombre del usuario. Si pongo S se queda en un ciclo infinito (no pasa el bind) y si pongo C entra en el except ya que no puede conectar (si imprimo el error me salía el anterior)

**Comment by aaossa** [comment]
Tienes que ejecutar el Servidor y en otra consola ejecutar el Client. Ambos programas tienen que estar corriendo
