### ISSUE TITLE
Control 6

### ISSUE THREAD

**Issue by HenryBlairG** [IIC2233-2016-02/Syllabus#575]
Hola!!

No me apareció en el googlesheets mi nota del control 6. ¿Me preocupo? ¿tengo que hacer algo? Según yo lo hice y muy bien y me preocupa que no me haya aparecido

**Comment by aaossa** [comment]
Hola @HenryBlairG, estamos revisando tu caso. Te contactaremos para darte una respuesta definitiva.

**Comment by lefischer** [comment]
hola,

a mi tampoco me aparece la nota del control 6

**Comment by aaossa** [comment]
@lefischer tu nota está arreglada

@HenryBlairG Bastián se comunicará contigo para solucionar esto por mail (como siempre :ok_hand: )
