### ISSUE TITLE
Ayuda!!!!

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#579]
Estaba probando el envio de una clase por el servidor y me sale __EOFError: Ran out of input__  y me arroja problemas en una linea donde tenfo pickle.loads(algo) podrian revisar mi repo y decirme por que se cae? segun yo deberia estar funcionando pero no :c 
Los archivos a ejecutar son:
- Sala.py (servidor)
- Dibujante.py (cliente que envia datos)
- bla.py (cliente que recibe los datos)

porfa :c <3

**Comment by narierao** [comment]
Este error me aparece en la terminal del servidor! un detalle

**Comment by aaossa** [comment]
`EOFError: Ran out of input`... No le estás dando todo el _input_ que se necesita para hacer `pickle.loads`. Considerando que trabajamos con _sockets_, ¿qué podría ser? En la ayudantía conversamos sobre cómo recibir datos que fuesen más grandes que nuestro _buffer_ (esto ya es una pista :thinking: )

**Comment by narierao** [comment]
Hice un while que me leyera el largo de lo que debo recibir y luego le digo que me sume el objeto que estoy enviando, pero aun asi no me funciona (hicimos esto en la actividad de hoy y funcionaba, pero ahora no me funciona).

**Comment by narierao** [comment]
ya lo solucione, era error en un thread. Gracias
