### ISSUE TITLE
[Tarea 1] Error ataques programones

### ISSUE THREAD

**Issue by roy350** [IIC2233-2016-02/Syllabus#58]
Disculpen pero probando mi codigo para realizar batallas programones, me aparecio un sandlash salvaje y eliguio poison sting por que es un movimiento que posee, pero este ataque no esta en "programonMoves.json" para que lo arreglen por que mi programa se cayo por eso :c

**Comment by jgmontoya** [comment]
Ya está reportado en #50
Por favor evitemos repetir issues para mantener el orden.
