### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#580]
Es normal que cuando coloco muchas entidades (agrego muchos puntos) se dejen de enviar los puntos via thread? como que no se me grafican en las otras ventanas, pero cuando lo hago lento si funciona :o

**Comment by FernandoPieressa** [comment]
Hola! Esto puede suceder porque el envio y recibo de información entre cliente y servidor, es un proceso que sucede mas lento de lo que se ejecuta el resto del código en el cliente. Una forma que se me ocurre para solucionarlo es poner un time sleep muy muy pequeño para dejar que el servidor pueda trabajar con la información enviada antes de que el cliente siga ejecutando su código.

Saludos!

**Comment by narierao** [comment]
Si quisiera un poco de ayuda (personalizada) como puedo ubicar a algún ayudante? Como que quiero implementar algo en la Tarea pero no estoy seguro si puede estar bien (tengo un diagrama en croquis). Como lo puedo hacer? :c

**Comment by narierao** [comment]
Gracias! eso lo soluciono! recomiendo sleep de 0.05 con 0.1 era muy lento y con 0.01 igual habia lag xd
