### ISSUE TITLE
Conexión

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#581]
Para conectarme desde computadores desde una misma red solo es necesario setear host y port? o necesito alguna variable extra? porque tecnicamente yo estoy haciendo en mi programa:

```python
self.host = socket.gethostname()
self.port = 15001
self.socket_cliente = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
```

al hacer `self.host = socket.gethostname()` le asocio el nombre de mi "computador" Nicolas pero si lo hago decomputadores distintos no me resultaria la conexion, tendria que guardar el Adress junto al socket y luego corroborar el Adress de quien envia y a cuales Adress debo enviarselo? me confundio demasiado eso x.x 

**EDIT aaossa:** Formato de código

**Comment by ivaniadg** [comment]
`self.host` debe tener la dirección IP del computador al que te quieres conectar. `gethostname()` no necesariamente te entregará una dirección IP. Mira [este link](https://docs.python.org/3.5/library/socket.html#socket.gethostbyname) para entender mejor cómo usarlo.

Para conectar dos computadores que están en la misma red debes hacer que el servidor haga bind a una tupla `(HOST, PORT)` y comience a aceptar conexiones. El cliente debe hacer `connect((HOST, PORT))`, donde `(HOST, PORT)` tienen el mismo valor que el servidor, para que se puedan conectar.
