### ISSUE TITLE
Servidores 

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#582]
Hola! Quiero crear una clase (distinta a servidor) pero que tenga un servidor (definido en el módulo del servidor, con host y port predeterminado), cuando quiero conectar el que dibuja con el que trata de adivinar, envían la información a la clase que quiero crear? O al servidor que está dentro de la clase? :o gracias <3

**Comment by aaossa** [comment]
No se entiende mucho tu pregunta, pero cuando conectas un cliente a un servidor la comunicación es bidireccional, no es necesario que ambos sean _servers_

**Comment by narierao** [comment]
No era eso, disculpa.
Para la tarea necesitamos conectar más de un computador? O basta con correrlo en local?

**Comment by jgmontoya** [comment]
Tu programa debiera funcionar desde varios computadores en una red local.  Sin embargo puedes hacerla y probar todo en local dejando cláramente indicado los parámetros que se especifican en el enunciado.

Esto significa que si el servidor guarda información en un archivo, el cliente **no puede** acceder directamente al archivo.

Saludos!

**Comment by lampuerov** [comment]
Hola, necesariamente la comunicación entre servidor-cliente debe ser probada en más de un pc?, o basta con que corra en mi pc respetando la edición de archivos que corresponde al servidor y cliente?. Lo que pasa es que al probarlo solo en mi pc no tengo problemas, pero al correr el archivo del cliente en otro pc no puedo establecer la conexión de forma apropiada. Cuáles son las posibles causas y soluciones a este problema? (Tengo arriba mi código). Gracias de antemano
