### ISSUE TITLE
Duda sobre la GUI de la AC14

### ISSUE THREAD

**Issue by sormazabal** [IIC2233-2016-02/Syllabus#584]
Hola! Revisando el código de la gui de la AC14 me surgió la siguiente duda:

En el código de la GUI importan los archivos .ui y luego los cargan de una forma distinta a como está en el material de clase:

```python
def get_absolute_path(relative_path):
    return os.path.join(os.path.dirname(__file__), relative_path)

splash_dialog_ui    = uic.loadUiType(get_absolute_path("./ui/splash_dialog.ui"))
signin_dialog_ui    = uic.loadUiType(get_absolute_path("./ui/signin_dialog.ui"))
signup_dialog_ui    = uic.loadUiType(get_absolute_path("./ui/signup_dialog.ui"))
main_window_ui      = uic.loadUiType(get_absolute_path("./ui/main_window.ui"))
compose_widget_ui   = uic.loadUiType(get_absolute_path("./ui/compose_widget.ui"))
read_mail_widget_ui = uic.loadUiType(get_absolute_path("./ui/read_mail_widget.ui"))


class GUI:
    def __init__(self):
        self.splash_dialog    = SplashDialog()
        self.signin_dialog    = SignInDialog()
        self.signup_dialog    = SignUpDialog()
        self.main_window      = MainWindow()
        self.compose_widget   = ComposeWidget()
        self.read_mail_widget = ReadMailWidget()

        self.__bind_signals()
        self.splash_dialog.show()
        self.splash_dialog.raise_()
```

Mi pregunta es: ¿Cómo puede Python cargar la clase SplashDialog() que no se ha definido antes? (ej: self.splash_dialog    = SplashDialog())
Agradecería mucho una explicación, porque se ve muy mágico y misterioso.

**Comment by aaossa** [comment]
Hola, primero que todo, revisa en la wiki cómo colocar código en Markdown. Lo arreglé y ahora se entiende mucho más :grin: (también puedes ver cómo quedó el texto de tu pregunta viendo la opción "editar")

Python puede cargar la clase `SplashDialog()` porque la carga antes de instanciarla. Si te fijas bien, la clase se crea mas abajo, por lo que al momento de ejecutar el "_init_" de la clase `GUI`, Python ya sabe de su existencia

**Comment by Tibrahm** [comment]
hola, también estaba revisando la gui de la actividad 14 y por lo que puedo deducir el self.__toggle_windows() es una función que cambia una ventana por otra,  pero no logro encontrar donde fue definida o de donde pudo haber sido heredada
