### ISSUE TITLE
Conexión entre computadores

### ISSUE THREAD

**Issue by cameneses** [IIC2233-2016-02/Syllabus#585]
Tengo una duda respecto a la conexión entre servidor-cliente.

Al hacerlo de forma local, el host tanto para el servidor y el cliente serán el mismo, y lo hago obteniendo `gethostname()`. Mi duda recae en si al realizar la conexión entre dos computadores distintos en una misma red, basta con pasarle al cliente, la dirección IP del servidor (esto usando `socket.gethostbyname(socket.gethostname())` para obtener la dirección IP y no el nombre de la máquina) al que me voy a conectar; o bien, es necesario realizar algo adicional a esto.

**Comment by narierao** [comment]
Hola, no soy ayudante pero le pregunte lo mismo a uno, la gracia de estabecesr como host tu ip del computador es que creas una "wifi" donde otros computadores puedes conectare a ti siempre y cuando ellos tengan seteado como host el ip de tu computadora y el puerto correspondiente a la conexion.

**Comment by fgvenegas** [comment]
Hola!
Tal como menciona @narierao, la idea es que si utilizas 2 computadores, la IP con la que trabajaras sera la del computador que actuará de servidor (en windows la obtienes ingresando `ipconfig` en la consola y en Mac esta en las preferencias de sistemas) entonces tu echas a correr el servidor con esa IP y en el fondo estas "abriendo" tu pc para que otras personas (los clientes) se puedan conectar a tu computador en un puerto x, por lo tanto el Cliente al hacer la conexcion tambien debeŕa poner esa IP (la del computador que es Servidor). Desconozco si se puede hacer automatico, porque cuando lo hacia, siempre lo hice manual
Saludos

**Comment by jgmontoya** [comment]
Un par de cosas para complementar un poco la respuesta de @fgvenegas  
Puedes usar `ifconfig` para obtener la IP en linux.

No puedes obtener la dirección del servidor de forma automática porque podría ser cualquier cosa. Incluso cuando uno ve una página en internet tiene que decirle al cliente (el browser) a qué dirección ip quiere conectarse. Ejemplo típico cuando uno quiere buscar información en internet pone en la barra de direcciones `173.194.219.139` y ocupa el buscador típico :roll_eyes: . 

Cuando uno escribe `google.com` lo que ocurre es que el browser inicialmente consulta a un servidor dns (cuya IP está puesta 'a mano' en tu conexión [acá puedes ver cómo obtener la dirección IP del servidor dns en tu computador](http://www.cyberciti.biz/faq/how-to-find-out-what-my-dns-servers-address-is/)) el servidor dns le responde a tu browser con la dirección IP que corresponde a la página `google.com` para que luego tu browser pueda interactuar directamente con el servidor que corresponde.

Saludos!

**Comment by cameneses** [comment]
Muchas gracias a todos por las aclaraciones!
