### ISSUE TITLE
QGraphics y pickle

### ISSUE THREAD

**Issue by cglevican** [IIC2233-2016-02/Syllabus#587]
Estoy utilizando pickle para la serializacion, pero tengo problemas con los items de QGraphics. Encontré esta página donde dice que clases de objetos se pueden serializar de pyqt4 (http://stackoverflow.com/questions/22889876/python-pickle-and-qt-pyqt) pero yo quiero necesito los objetos Item de QGraphics, como por ejemplo, QGraphicsLineItem porque incluyen el lápiz con el que fue escrito. Tengo que crear una cls para serializar personalizadamente?

**Comment by jbsaeza** [comment]
Yo tenia el mismo problema y la solución fue no enviar objetos de QGraphics y en ves de esto enviar los parámetros y en los demás clientes crearlos de nuevo con los parámetros.

**Comment by cglevican** [comment]
Gracias, tendré que hacerlo así.

**Comment by narierao** [comment]
usa personaliza la serializacion! a mi me resulto excelente eso!

**Comment by aaossa** [comment]
También podrías hacer lo que dice uno de los comentarios en la respuestas que tu misma indicaste: controlar como se hace el _pickling_. Puedes ver un ejemplo y la explicación [en la documentación de Python](https://docs.python.org/3.5/library/pickle.html#object.__getstate__). Pero tratando de aterrizar un poco el proceso lo explicaré aquí porque seguramente alguna vez lo usarán (más aun porque esta técnica también sirve para json).

``` python
import pickle


class MiObjeto:

    def __init__(self, val=2):
        # Un init comun y corriente
        self.val = val

    def __getstate__(self):
        # Cuando no podemos serializar un objeto es porque 
        # un objeto de su diccionario (por ejemplo un atributo)
        # no es serializable, por lo que simplemente lo dejas 
        # afuera del diccionario y ya
        print("Haciendo pickle.dump")
        self.val *= 2
        return self.__dict__

    def __setstate__(self, d):
        # Cuando intentas recuperar el objeto serializado
        # solamente tienes que darle un valor a la key faltante
        print("Haciendo pickle.load con valores {}".format(d))
        self.__dict__ = d
        self.val *= 3

mo = MiObjeto()
mo_string = pickle.dumps(mo)
mo_new = pickle.loads(mo_string)
```

Recomiendo hacer esto porque de esta forma sabes lo que estás mandando, como funciona y puedes enviar lo que necesitas. De verdad lo van a usar, se van a acordar de esta issue algun dia (?)

**Comment by cglevican** [comment]
Pero en ese caso, como sabemos los atributos que no se pudieron serializar?

**Comment by narierao** [comment]
Dentro de la clase mensajero hice variables auxiliares (colores, para armar Qcolor) y cosas así, para cuando deserialises armes el atributo correctamente con QGraphics

**Comment by aaossa** [comment]
@cglevican puedes ir probando o solo pasar los atributos necesarios para inicializar la clase
