### ISSUE TITLE
"QObject: Cannot create children for a parent that is in a different thread"

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#588]
```
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QTextDocument(0x2810900), parent's thread is QThread(0x244f540), current thread is QThread(0x7efc88001650)
Violación de segmento (`core' generado)
```

tengo este error y no aparece nada en internet 
Estoy utilizando QTextBrowser() para enviar mensajes y el Thread listen me arroja errores :c help :c

**Comment by aaossa** [comment]
Segun el mensaje de error... estas agregandole un _child_ a tu `QTextBrowser` desde un thread que no es el mismo que creó que `QTextBrowser`. Prueba enviarle una señal al _thread_ principal para que este le agregue el _child_ a a tu `QTextBrowser`

**Comment by narierao** [comment]
No pude hacerlo. He tratado de hacerlo pero no resulta :/ que puedo hacer? llevo horas sacado ese error -.- onda le hice set a una variable de la ventana y le mande una funcion para que lo cambie y no -.- por alguna razon no me deja mandarselo :/

**Comment by narierao** [comment]
voy a crear una clase con el mensaje y vere si me resulta.

**Comment by narierao** [comment]
funciono, se caia en el protocolo. Gracias
