### ISSUE TITLE
Frontend y Backend

### ISSUE THREAD

**Issue by Gonzalo-Perez** [IIC2233-2016-02/Syllabus#589]
Todavía tengo problemas para separar bien el backend del frontend.
Si , por ejemplo, quisiera hacer que se abrieran diferentes ventanas en función de algo como una función "check" con varios ifs, esa función "check" debería estar definida en el backend y ser llamada por el frontend al momento de abrir (o no) las ventanas? Sería correcto poner la función "check" directamente en el frontend?

De antemano, gracias.

**Comment by narierao** [comment]
hola, no soy ayudante pero pensaba hacer algo similar, tu en el backend puedes manejar las ventanas que se abren en el frontend de dos formas: 
- 1) Puedes instanciarlas en ese momento y hacer ventana.show()
- 2) Instancialas en el init y posteriormente hacerles ventana.close() y ventana.show() cuando quieras mostrar o cerrar las ventanas.  

Un consejo para saber cuando te refieres al backend, tienes que pensar si estas hablando de la logica del juego (ejemplo, en que orden mostrar las pantallas o abrirlas) y luego para el fronted dices, ok, esto es lo que tengo que mostrar. Espero te ayude!

**Comment by ivaniadg** [comment]
@Gonzalo-Perez 
Revisa esta [issue](https://github.com/IIC2233-2016-1/syllabus/issues/502) del semestre pasado. Piensa que el _backend_ siempre va a realizar toda la lógica del programa y el _frontend_ solo debe mostrar los resultados de lo que hace el backend.
