### ISSUE TITLE
terminar conexiones socket 

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#590]
Cuando hago que mi ventana termine su conexion con el servidor se cierra muy bien, pero en la consola del servidor me arapece esto:

xception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "Sala.py", line 91, in listen_client_thread
    received = pickle.loads(response)
EOFError: Ran out of input

No se supone que ese Thread debe morir ? cuando cierro la conexion? no entiendo lo que hace python por detras :/

**Comment by Gonzalo-Perez** [comment]
Justo iba a crear una issue por lo mismo.
Me aparece el mismo error (EOFError: Ran out of input) como si el servidor hubiera enviado un arreglo de bytes vacío y que eso al pickle.loads no le haya gustado.
Tenía entendido que el .recv(1024) estaba "escuchando" y por lo tanto si no se le envía nada no debería tirar error. Ahora, si se le envía algo vacío no sé pero no es el caso en mi código (lo subí por si alguien le quiere echar un ojo).

De antemano, gracias.

**Comment by Iruretagoyena** [comment]
En la ayudantía hay un ejemplo de función para manejar esto ! A mi me sirvió.

**Comment by cjgazali** [comment]
También he tenido ese problema...
¿@Diiru en qué parte de la ayudantía específicamente está el manejo de esto? No lo he encontrado...

**Comment by mraddatz** [comment]
Si alguien logró solucionarlo puede decir como porfa?

**Comment by narierao** [comment]
En vez de hacer while True debes condicionarlo a una variable para terminar el thread, posterior a terminarlo tienes que cerrar la conexión en el servidor (con cliente) y en el cliente (con el servidor) te recomiendo usar sleep() para darle tiempo de cerrarse
