### ISSUE TITLE
¿Qué pasó con la recorrección de AC05?

### ISSUE THREAD

**Issue by vigazali** [IIC2233-2016-02/Syllabus#592]
Hola ayudantes! Hace ya harto tiempo que mandé a recorregir la AC05, porque me aparecía un 1,0 y no tenía ninguna clase de feedback en la issue correspondiente, a pesar de que sí hice la actividad. En su momento me dijeron que era porque, por alguna razón, no habían recolectado bien el archivo, aunque el commit a revisar que dice la issue está bien, y por lo tanto, que mande a recorregir.

Eso hice, mandé a recorrección indicando claramente el commit y el archivo que debía ser revisado, pero todavía me aparece un 1,0 y tampoco tengo feedback en la issue. ¿Qué habrá pasado con la recorrección?

Gracias!!

**Comment by aaossa** [comment]
Estimado, ya corregimos tu nota. Te recuerdo que los casos particulares se resuelven por mail

**Comment by vigazali** [comment]
Ah, perdón por no hacerlo por mail, se me fue.
Muchas gracias!
