### ISSUE TITLE
Duda sobre la ayudantía

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-02/Syllabus#594]
Hola !
Estaba revisando el código de server/client de la ayudantía (la de envío de objetos ) y me di cuenta que para enviar las cosas, las metían a una lista y luego las enviaban. 

Para que hacen esto ? Por que no mejor mandar el texto solamente ? Por si se requiriese manejar más de una señal ? Como podría pasar eso ? ( a nivel Tareas, me imagino que si nos complicamos es más que posible)

Gracias de antemano

**Comment by aaossa** [comment]
Porque la gracia del ejemplo era "enviar objetos"
