### ISSUE TITLE
Manejo de tiempos

### ISSUE THREAD

**Issue by Tibrahm** [IIC2233-2016-02/Syllabus#595]
Hola !!
Tengo mi archivo cliente donde tengo definido el botón de ingreso, este envía el usuario y la clave ingresados al servidor, el servidor procesa la informacion  y envía de vuelta al cliente si estos se encuentran correctos o no ( Todo dentro de la funcion del  botón ). Si están correctos debería desplegar la ventana principal y sino quedarse en la misma ventana, el tema es que mientras se procesa la informacion en el servidor el cliente sigue corriendo entonces lo que manda el servidor llega "tarde" al cliente y cuando los datos, a pesar de estar bien ingresados, no se despliega la  ventana principal (Es como si siempre estuvieran mal ingresados). No se si entiende mi problema, si algún ayudante puede ver mi código es la linea 108 del archivo cliente

**Comment by aaossa** [comment]
Hola @Tibrahm , tu pregunta es demasiado amplia, de hecho creo que no hay una como tal. ¿Qué intentaste hacer?¿Qué crees que pueda funcionar? Para guiarte un poco en tu descripción en partícular, ¿qué ocurre cuando te intentas "loguear" a alguna _app_ desde tu teléfono o navegador?

**Comment by Tibrahm** [comment]
perdón la cerré sin querer, básicamente lo que quiero hacer es que el retorno de mi función botón ingreso, espere la respuesta del servidor, es decir, que mientras se espera lo que el servidor responda no se siga corriendo la función de botón de ingreso

**Comment by aaossa** [comment]
@Tibrahm , lo que describes lo hace una función que revisamos en la ayudantía y que usaron en la actividad. Te invito a darle una vuelta al material para que sepas cuál es.

**Comment by Iruretagoyena** [comment]
@Tibrahm A mi me paso exactamente lo mismo. Lo que esta pasando es que el resultado del proceso que mandamos ocurre después del retorno de la función que le dice a la Gui si pasa o no.
Todavía no lo resuelvo al 100%, pero creo que con un Lock() podemos solucionarlo, cosa de parar todos los otros procesos mientras se procese el de la gui (parar el listener continuo).
