### ISSUE TITLE
Qué pasa si un usuario no tiene amigos?

### ISSUE THREAD

**Issue by sormazabal** [IIC2233-2016-02/Syllabus#596]
Hola!
Me entró la duda de qué hacer si un usuario nuevo (sin amigos :( ) quieres jugar. Dado que no puede seleccionar amigos para abrir una sala, debiera conectarse a jugar a una sala random donde ya haya gente conectada?

**Comment by cjgazali** [comment]
Adjunto mi issue con algunas cosas específicas que fue cerrado por ser de este mismo tema:
"""
No entiendo si existe un juego con gente que no son amigos. Las salas son para amigos, los chats son entre amigos; ¿la única opción es agregar a alguien como amigo y después jugar? De no ser así, ¿cómo se empieza un juego si alguien no es mi amigo?

En la parte de Amigos, dice "se pueden buscar personas por el nombre de usuario" y "La idea de los amigos, es que se puedan invitar a una sala (explicado mas adelante) y jugar con ellos nuevamente". Al buscar nombres, entiendo que se deben mostrar todos los usuarios que existen, sean o no sean amigos, y poder agregar a los que no sean, ¿cierto? ¿O sólo se muestran los que no son amigos? ¿De dónde salen estos nombres? ¿Usuarios conectados actualmente, todos los usuarios de la historia, ...?
"""
Gracias.

**Comment by FernandoPieressa** [comment]
Hola! Se podria decir que existen 2 formas de iniciar un juego ~~pinturillo~~ programillo:
- La primera forma es dentro de un chat grupal, donde se inicia el juego con los del grupo y solamente para los del grupo. En estas es donde actua el historial de partidas, etc..
- La segunda forma es al crear o unirse a una sala cualquiera que no pertenece a un grupo de chat. Estas salas son publicas y cualquiera puede ingresar, la diferencia en tener amigos es que si estas en una de estas salas, puedes invitar a tus amigos para que se unan directamente a la sala, sin embargo cualquiera se puede unir en una lista de "partidas abiertas".

@cjgazali con respecto a tu dudas: Como no sale en el enunciado queda a tu criterio si quieres que aparezcan los que ya son amigos en la busqueda pero no se puedan volver a agregar porque ya son amigos, o si simplemente no aparece. Y los que pueden aparecer en este busqueda son todos los usuarios registrados en el sistema.

Saludos!

**Comment by cjgazali** [comment]
Gracias! Creo que esto merece etiqueta IMPORTANTE porque el segundo punto de @FernandoPieressa pareciera estar dado por hecho pero ni se sugiere en el enunciado...

**Comment by cjgazali** [comment]
Otra cosa!
Se debe poder abrir una sala entre amigos SIN necesidad de abrir primero un chat entre amigos?

**Comment by FernandoPieressa** [comment]
Una vez que entras al chat grupal se da la opcion de abrir una sala para jugar.

Saludos!

**Comment by fipaniagua** [comment]
si se entra a una sala a jugar pinturrillo es necesario mantener el chat abierto??

**Comment by FernandoPieressa** [comment]
Hola! En la sala de juego tiene que estar el chat del juego abierto para poder jugar y adivinar palabras.
Saludos!
