### ISSUE TITLE
Tarea 6: ¿existe modo 'normal sin amigos'?

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#597]
No entiendo si existe un juego con gente que no son amigos. Las salas son para amigos, los chats son entre amigos; ¿la única opción es agregar a alguien como amigo y después jugar? De no ser así, ¿cómo se empieza un juego si alguien no es mi amigo?

En la parte de Amigos, dice "se pueden buscar personas por el nombre de usuario" y "La idea de los amigos, es que se puedan invitar a una sala (explicado mas adelante) y jugar con ellos nuevamente". Al buscar nombres, entiendo que se deben mostrar todos los usuarios que existen, sean o no sean amigos, y poder agregar a los que no sean, ¿cierto? ¿O sólo se muestran los que no son amigos? ¿De dónde salen estos nombres? ¿Usuarios conectados actualmente, todos los usuarios de la historia, ...?

Gracias.

**Comment by aaossa** [comment]
Movida a #596
