### ISSUE TITLE
Ejecución (o 'existencia') de un servidor

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#598]
No entiendo qué 'representa' correr un código servidor y luego que se termine su ejecución. En particular, no me queda claro si un servidor normal 'real' equivale acaso a **una gran ejecución** de un módulo servidor. Es decir, en nuestra tarea, por ejemplo, ¿deberíamos implementar el servidor pensando en que tendrá **una gran ejecución** y funcionará por toda la eternidad? Pensando sobre todo en la siguiente implicancia: todo lo que el servidor recibe, que es mucha información, debe ser exportado cada vez y ordenado para ser importado en cada ejecución, o simplemente debe contener y manipular todo sin mayores enredos ya que, en teoría, "siempre estará corriendo".

**Comment by jgmontoya** [comment]
Hola, 

El servidor es un programa que se ejecuta en un computador y que _hace algo_ cuando se conectan a el. 

¿Nunca te ha pasado que al intentar acceder a una página, aplicación web o juego online, aparece un mensaje que los servidores están en mantención y por lo tanto no puedes acceder? Lo que ocurre es que en ese momento se dejó de correr el código del servidor en los computadores que manejan ese servicio. Para los servidores en general se utilizan computadores que pueden pasar una gran cantidad de tiempo sin ser apagados (justamente para evitar el _downtime_), sin embargo nada puede funcionar eternamente sin interrupciones.

Además de esto, la información que maneja un servidor eventualmente será mayor a lo que cabe en la memoria del computador. Por ejemplo twitter genera aproximadamente 8TB de información diarios.

Por esto es que se necesita usar el almacenamiento secundario (a.k.a. archivos en el disco) para poder tener tanto persistencia de los datos (no queremos que todos los datos se pierdan si se apaga el servidor) y para no dejar sin memoria al computador.

Saludos!

**Comment by cjgazali** [comment]
Perfecto.
