### ISSUE TITLE
Encriptación/ desencriptación

### ISSUE THREAD

**Issue by sebacruzd** [IIC2233-2016-02/Syllabus#599]
Hola,
Me surgió una duda que no está clara en el enunciado.
Al encriptar la clave es necesario que pase por el servidor?

En mi caso lo hice directo desde el cliente, ya que al intentar iniciar sesión se revisan los archivos de la manera especificada en el enunciado, pero directamente desde el cliente. No se envia la clave que intentó usar al servidor para luego revisar si es la correcta, sino que en el cliente se hace directamente todo ese proceso. (Y supongo que se hara todo desde el mismo pc, por lo que el servidor y clientes están en el mismo pc.

Según enunciado entiendo que estoy bien ya que las contraseñas están siendo encriptadas antes de guardarse.

Está bien lo que hago o es necesario pasarla al servidor para que la revise?

Gracias de antemano!

**Comment by jgmontoya** [comment]
Hola, 

Es necesario que el hash se guarde desde el servidor. Puedes hashear la contraseña en el cliente y enviar el hash o bien enviar la contraseña y hashearla desde el servidor. Si no, ¿Cómo revisarás cuando un usuario hace log-in? Recuerda que el cliente **no** tiene acceso directo a la base de datos, si no que solo puede interactuar a través del servidor.

Saludos!

**Comment by sebacruzd** [comment]
Gracias!
Justamente esa era mi duda, si es que el cliente podía acceder a esa base de datos.
