### ISSUE TITLE
Problema instalando Sublime-text3 en Mac OSX

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233-2016-02/Syllabus#6]
Al escribir ”brew cask install sublime-text3” me tira
“Error: No available Cask for sublime-text3“
“Error: nothing to install“
Ya instalé brew y todo el resto de las cosas, solo con sublime tuve este problema.
Saludos!

**Comment by jgmontoya** [comment]
Hola!

Prueba con 

```
brew cask install sublime-text
```

Y comenta qué versión de sublime text instala

**Comment by bedefrunner** [comment]
Hola!

Me instaló la versión Build 3114, creo que es la más reciente.

**Comment by jgmontoya** [comment]
Efectivamente, y corresponde a la última versión de sublime text 3.

Tal como se indica [aquí](https://github.com/caskroom/homebrew-cask/issues/1252) la razón es que la versión 3 de sublime text es el nuevo default al ser la versión linkeada en la página de descarga de https://www.sublimetext.com/ 

Saludos

EDIT: Actualicé la información de la wiki para que tuviese el comando actualizado.

**Comment by bedefrunner** [comment]
Muchas gracias!
