### ISSUE TITLE
[Tarea 1] Duda sobre stats y entrenadores

### ISSUE THREAD

**Issue by Riarrieta** [IIC2233-2016-02/Syllabus#60]
Hola! Tengo dos dudas:
1) en la formula para calcular stats y hp, el término sqrt(EV) está encerrado por unos corchetes ¿esos corchetes son parte entera o son para aproximar hacia arriba? No se parecen a los tipicos corchetes de parte entera.
2) los stats iv y ev de los programones de los entrenadores de los gyms son fijos una vez creados? O cambian cada ves que el jugador vuelve a pelear con el entrenador?.
Saludos

**Comment by flobarrios** [comment]
Hola!

1) Es una aproximación por debajo (floor function) y aproxima al entero más grande, menor o igual al número. Por ejemplo:

| x | floor |
| --- | --- |
| 2 | 2 |
| 2.4 | 2 |
| 2.9 | 2 |
| -2.7 | -3 |
| -2 | -2 |

2) Sí, los stats quedan fijos!

**Comment by Riarrieta** [comment]
Vale!
