### ISSUE TITLE
Ventanas y threads 

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#600]
Tengo un ventana que tiene el thread `listen()`, el problema es que cuando la cierro me aparece este error:

```python
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "Nuevo_Usuario.py", line 61, in listen_thread
    response_bytes_length = self.socket_servidor.recv(4)
OSError: [Errno 9] Descriptor de archivo erróneo
```

cuando antes de cerrar a ventana hago `socket_servidor.close()`

igual entiendo que es super normal que este thread muera, pero dejo pasar este error?

**Comment by aaossa** [comment]
Al parecer ocurre cuando intentas utilizar un método de un `socket` cuando este ya está cerrado ([SO](http://stackoverflow.com/a/15958099/3281097)), ten cuidado con el orden en que haces esas acciones para evitar esto
