### ISSUE TITLE
Archivos PNG

### ISSUE THREAD

**Issue by kpribbeck** [IIC2233-2016-02/Syllabus#602]
Para pasar una imagen a formato PNG, al momento de crear el IDAT, ¿cómo puedo obtener la información de la matriz de pixeles? Hasta ahora he trabajado en base a QPixmap y QImage.
Otra duda. La secuencia de bytes que se señala en el enunciado (137 80 78 71 13 10 26 10), ¿va antes de cada chunk o sólo al comienzo?

Muchas gracias

**Comment by FernandoPieressa** [comment]
Hola!

La secuencia de bytes tal como sale en la imagen del enunciado, es solo al comienzo.

La matriz de pixeles del IDAT la tienes que crear tu, no la obtienes. Por lo tanto tendrías que crear una matriz de las dimensiones deseadas para la imagen PNG, y en cada posicion de la matriz seguir los pasos explicados en la seccion 6.2: creando el IDAT. Tienes que poder ser capaz de guardar con la informacion que tienes los colores que usaste en formato RGB en cada punto del dibujo para poder colocarlas en la matriz creada por ti en las posiciones correctas.

Si tu duda es como obtener el RGB de un QPixmap o QImage, se puede encontrar en google facilmente.

Saludos!

**Comment by cglevican** [comment]
Se puede pasar desde el QGraphicsView a la matriz RGB de alguna forma? O en vez de ir guardando los items de QGraphics que el usuario va incluyendo, hay que llenar una grilla de 3 dimensiones, que represente la pantalla en donde los usuarios dibujan? (Creo que lo segundo es menos eficiente) .

**Comment by iqacevedo** [comment]
@cglevican según lo que he investigado puedes pasar el QGraphicsView a un QImage, y desde ahí obtener la matriz RGB, ya que puedes recorrer pixel por pixel la imagen desde ahi.

**Comment by cglevican** [comment]
Gracias @iqacevedo, tengo otra duda. Entre las filas del archivo IDAT o entre IHDR, IDAT y IEND hay que agregar un '\n'? He intentado varias horas y no me resulta con el formato correcto.

**Comment by iqacevedo** [comment]
Me sumo a la duda, también seguí las instrucciones, busque por internet y mis imágenes quedan distintas a las reales :( .

**Comment by Hernan4444** [comment]
@iqacevedo me di la libertad de revisar tu codigo a la rapida y podria decir 3 cosas:

(1) La mas importante!!!: Estas analizando los pixeles por columnas y creando asi tu png. Tiene que ser por fila siempre.
(2) Prueba usar una profundidad de 8 y no de 16 (a veces a mi eso me sirve caleta)
(3) Adjunto una imagen png que debería funcionar para testear su código como en tu caso. Dentro del mundo de las png hay una variedad de imágenes que usan otros filtros, compresiones, formato de color (rgba), etc. Y puede ser que justo estas probando tu código con un png que no es lo esperado por nosotros. Con esta imagen y con la que crean en el programillo no deberán tener problemas siguiendo las instrucciones dadas por el enunciado.

![08c7fa81-9934-437a-bb11-12d87740868e](https://cloud.githubusercontent.com/assets/15641721/20412497/de120c2c-ad05-11e6-86b6-dbd75339ff7c.jpg)

Saludos!!

Edit: Ante una duda de que no les resulta, ruego subir su código antes de preguntar, así puedo ver que están programando antes de dar una respuesta.

**Comment by iqacevedo** [comment]
@Hernan4444 muchas muchas gracias. Eso explica porque se rotaba la imagen cuando la guardaba. Si no me resulta con lo de los 8 te aviso.

Saludos !

**Comment by iqacevedo** [comment]
Listo! Resultó todo perfecto muchas gracias por la ayuda !
