### ISSUE TITLE
Problema al cerrar el Server

### ISSUE THREAD

**Issue by seba-bug** [IIC2233-2016-02/Syllabus#603]
Hola!
Tengo problemas al momento de cerrar el servidor por consola con una tecla de salida. Me lanza un `ConnectionAbortedError: [Errno 53] Software caused connection abort` y por lo que logré entender, el tema está en que el thread que espera nuevos clientes está pegado en el método `accept()` y muere al cerrarlo. ¿Hay alguna forma de que deje de escuchar (sacarlo del accept a la mala) o se puede modelar mejor incluyendo algún control? 
El error es fácil de obtener, basta correr el server.py y poner "q" en la consola.

Muchas gracias!

**Comment by ivaniadg** [comment]
Hola,

No entiendo el problema, en especial esta parte

> el tema está en que el thread que espera nuevos clientes está pegado en el método accept() y muere al cerrarlo

puedes explicar mejor el flujo que produce el error?
