### ISSUE TITLE
Tope de horario exámen

### ISSUE THREAD

**Issue by mrafaeli** [IIC2233-2016-02/Syllabus#605]
Hola! Tengo un problema con el horario del exámen, ya que me calza con el horario de otro examen en mi facultad (estudio ing.comercial). Quería saber que se puede hacer o con quien hay que hablar para tratar de solucionarlo, muchísimas gracias de antemano.

**Comment by ivaniadg** [comment]
Hola,

En una fecha antes del examen les vamos a pedir a todos los que tengan tope que envíen un email diciendo con qué ramo tienen tope y a qué hr salen del examen. A esas personas les vamos a tomar el examen en otro horario, el mismo día. 

Saludos.

**Comment by Tibrahm** [comment]
yo también, el mismo día tengo 3 exámenes  !!

**Comment by ivaniadg** [comment]
@Tibrahm 
Como dije arriba

> En una fecha antes del examen les vamos a pedir a todos los que tengan tope que envíen un email diciendo con qué ramo tienen tope y a qué hr salen del examen. A esas personas les vamos a tomar el examen en otro horario, el mismo día.

Es imposible que tengas 3 exámenes el mismo día, tendrías que tener tope de horario.

**Comment by Tibrahm** [comment]
Es enserio, no es broma y no no tengo tope de horario

**Comment by aaossa** [comment]
Para casos similares les recuerdo que está el formulario respectivo en SIDING :grin:
