### ISSUE TITLE
Paint

### ISSUE THREAD

**Issue by domingo-valdes** [IIC2233-2016-02/Syllabus#607]
Hola! Me surgió la duda de si podemos implementar el programa más parecido a paint de lo que se dice en la guía. Es decir, que no tengamos figuras prehechas, sino que sea el usuario quien las dibuje del tamaño que quiera arrastrando el mouse (al igual que el viejo MS paint). Me parece más razonable e intuitivo dada la naturaleza del juego.

**Comment by FernandoPieressa** [comment]
Hola! No hay ningun problema si las haces viendo el tamaño al arrastrar el mouse como paint, mientras se formen las figuras pedidas.

Saludos!
