### ISSUE TITLE
Informacion Guardada Por Servidor

### ISSUE THREAD

**Issue by mraddatz** [IIC2233-2016-02/Syllabus#608]
Cuando el servidor guarda información se puede hacer mediante variables? O debe hacerse utilizando archivos los cuales los va sobrescribiendo y leyendo?

**Comment by FernandoPieressa** [comment]
La idea es que toda la informacion sea guardada en el servidor y poder utilizarlas en futuras ejecuciones del programa en el servidor.

Piensa que si guardas todo en variables solamente al hacer una mantencion del servidor perderas toda la informacion de todas las cuentas.

Saludos!

**Comment by jgmontoya** [comment]
#598
