### ISSUE TITLE
[Tarea 1] Subir nivel programones

### ISSUE THREAD

**Issue by roy350** [IIC2233-2016-02/Syllabus#61]
Disculpen me quedo la duda en el enunciado que dice que todos los programones suben de nivel si es que salieron de la prograbola, mi pregunta es que si en la batalla fue derrotado pero gane con otro programon el programon vencido igual sube de nivel o este no lo hace?

**Comment by flobarrios** [comment]
Hola! suben de nivel todos los que hayan participado y que al final de la batalla, tengan un hp > 0. Saludos!

**Comment by jbsaeza** [comment]
Es necesario que los programones que participaron en el combate y al ser lograda la victoria, tengan hp > 0?, ya que según yo recuerde en el juego original no es así, ademas que es un poco injusto para el programon que peleo xD

**Comment by roy350** [comment]
@jbsaeza en el juego original si es asi, pero como el enunciado no especificaba pregunte pero @flobarrios ya lo resolvio

**Comment by roy350** [comment]
Disculpa por re abrir la issue pero en el juego original al debilitar al pokemon contrario ganan experiencia en este caso sube de nivel altiro pero mi pregunta es si es un entrenador q tenga mas de un programon, mis programones suben de nivel cada vez que debilito a un programon de mi adversario o una vez que gano la totalidad de la batalla? muchas gracias!

**Comment by flobarrios** [comment]
Cuando se gana la totalidad de la batalla. No antes!! 😄

**Comment by roy350** [comment]
muchas gracias te pasaste! 😀
