### ISSUE TITLE
Por que QGraphics? (vs QPainter)

### ISSUE THREAD

**Issue by Nebula2028** [IIC2233-2016-02/Syllabus#610]
Eso, básicamente me surgió la duda por que a pesar de que en el enunciado aparece y cito "Se sugiere fuertemente el uso del módulo QGraphics de PyQt4 para el renderizado de los dibujos en los clientes." yo todo lo que llevo de la tarea (por esas cosas de la vida) esta hecho con QPainter.

Cuando busque en google "QGraphics PyQt4" me di cuenta que el módulo QGraphics en si no existe, existen QGraphicsScene, QGraphicsItem, QGraphicsView, QGraphicsRectItem, y un largo etc... lo cual a principio me confundió y me pareció más simple con QPainter y QImage. 

**Mi pregunta es: Hay alguna razón en particular (digase serialización, abrir/guardar imagenes, algo de networking, etc) por la que convendría usar QGraphicsCosas ?** 

pregunto por que hasta el momento estoy bien con lo otro, pero no se si me toparé con algún problema especifico por el cual mejor cambiarme lo antes posible a QGraphics

gracias!!

**Comment by Hernan4444** [comment]
Se sugirió QGraphics puesto que con esos elementos ya estaba 100% probado de que se lograrian los objetivos de la parte grafica de la tarea sin ningun problema

en tu caso que usaste Qpaint, no podemos asegurar que no presentes algun inconveniente que seria mas dificil de resolver por parte de los ayudante, pero si es que te funciona perfectamente, lo mejor seria seguir, no existe un solo camino para lograr lo que pedimos c:

Saludos!!
