### ISSUE TITLE
QWidget dentro de un QWidget (MainWindow)

### ISSUE THREAD

**Issue by joseluishaddad** [IIC2233-2016-02/Syllabus#611]
Se puede meter un QWidget (que no hice con QtDesigner) dentro de otro QWidget (MainWindow que hice con QtDesigner) ?? 

Saludos

**Comment by DiegoAndai** [comment]
Recuerda que puedes ocupar todas las entidades del QWidget lo hayas creado o no con QtDesigner, es decir, si creas una clase basándote en tu archivo.ui puedes ocuparla tal como si hubieses puesto las entidades (Qlabels, QGraphics, PushButtons, QLayouts....) con código. Esto lo haces tal como lo harías si lo hubieras escrito con código, con self.nombre_entidad.metodo...()

Así, si creaste una MainWindow con QtDesigner, puedes ocupar self.setCentralWidget(QWidget) tal como lo harías si hubieses escrito el main window en código. La gracia de QtDesigner es hacerte más fácil colocar las entidades, pero no cambia la sintáxis de pyQt ni crea cosas distintas a las que haces con código.
