### ISSUE TITLE
Duda enunciado sobre el dibujo

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#612]
Hola! Quizas sale en el enunciado, pero mi comprension lectora ya desaparecio luego de tanto programar, pero me quedo la duda de si hay que poder hacer lineas libres, onda que la linea siga al mouse. Me parece que no pero no estoy seguro, gracias!

**Comment by FernandoPieressa** [comment]
Hola! Si se tiene que poder hacer lineas libres dentro del dibujo, los otros tipos de dibujo son funcionalidades extras para dibujar.

Saludos!

**Comment by andresbannuraschultz** [comment]
Dale gracias!
