### ISSUE TITLE
Dibujo Curvas

### ISSUE THREAD

**Issue by npcariman** [IIC2233-2016-02/Syllabus#613]
Hola, no entiendo cómo debería quedar la curvatura, y la nota al pie de página me dejo más confundido. Pueden acarar con algún ejemplo si es posible. Gracias.

**Comment by ManuelSIlvaCav** [comment]
Hola,

Imagínate la linea curva de paint, que cuando seleccionas los dos puntos puedes darle una curvatura a la linea que tu quieras. En este caso, es mas fácil, ya que se indica que la curvatura viene definida por ustedes, por lo tanto cuando hagas la linea entre los dos puntos, esta ya tiene que venir "doblada" con una curvatura que quede a tu criterio.

Espero se entienda,
Saludos
