### ISSUE TITLE
Dudas invitaciones y chat

### ISSUE THREAD

**Issue by Pyralspite** [IIC2233-2016-02/Syllabus#614]
Hola,  tengo varias dudas y creo que no están especificadas en el enunciado:
1. Al iniciar un chat, se abre una ventana aparte o se cambia la ventana principal?
2. Si me agregan a un chat, me redirigen inmediatamente/se abre la ventana sola o debo aceptar la invitación?
3. Si se abre una ventana aparte, puedo tener más de un chat activo al mismo tiempo?
4. Si se inicia una partida con un chat grupal, el resto del grupo es redirigido o deben confirmar la invitación? 
5. Se puede hablar con alguien que está en una partida? (Asumiendo que se abre una ventana extra para el chat)
Perdón si son cosas obvias :(

**Comment by FernandoPieressa** [comment]
Hola!

1) Mientras se cumplan los requisitos pedidos la forma en que funciona queda a tu criterio. Mientras mas ordenado mejor.

2) Se debe aceptar la invitacion, tal como sale en punto 7.2.

3) Si puedes, queda a tu criterio.

4) Tambien a tu criterio.

5) Uno si le puede mandar mensajes a esa persona, pero puedes hacer que los lea en otro momento cuando abra su chat de conversacion, o pop up, eso queda a tu criterio.

**Comment by Pyralspite** [comment]
Muchas gracias! Entonces espero haber tomado las decisiones correctas :D
