### ISSUE TITLE
Duración examen 

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-02/Syllabus#616]
Hola !
Mis disculpas si ya respondieron esto en otro lado, pero; cuanto dura el examen ? Tengo otro examen ese mismo día, pero dependiendo de la duración, puede que no me topen.

Gracias de antemano !

**Comment by ivaniadg** [comment]
No se sabe pero será entre 2 y 3 hrs. Responde el formulario que enviamos :grin:

**Comment by Iruretagoyena** [comment]
@indonoso Ok !! No sabía si responderlo porque si dura 2 no me topa, pero ok lo responderé. Gracias !
