### ISSUE TITLE
Historial

### ISSUE THREAD

**Issue by fringlesinthestreet** [IIC2233-2016-02/Syllabus#618]
¿El historial debe guardarse para futuras conexiones del usuario?

EDIT: el historial de gente que jugó con él.

**Comment by kcsss** [comment]
Siguiendo con el thread, como puedo borrar mi historial , no quiero que mis amigos vean mis páginas de estudio.

**Comment by FernandoPieressa** [comment]
Hola! La idea es que el historial quede guardado.

Saludos!
