### ISSUE TITLE
Guardar Imagen

### ISSUE THREAD

**Issue by joseluishaddad** [IIC2233-2016-02/Syllabus#619]
La opcion guardar imagen, guarda el dibujo en el pc del cliente como una imagen más o en el servidor de tal forma que solo se pueda acceder mediante el cliente??
No logro entender bien del enunciado.
Saludos y gracias de antemano.

**Comment by FernandoPieressa** [comment]
Hola! La idea es que puedas guardar la imagen en tu computador, por lo tanto es solo necesario trabajar el guardado de imagen desde el cliente y no en el servidor. Si la idea fuera poder acceder a esa imagen desde el programa en cualquier computador habria que trabajarlo en el servidor pero no es necesario para esta tarea.

Saludos!

**Comment by joseluishaddad** [comment]
@FernandoPieressa Gracias Fernando!
