### ISSUE TITLE
Nuevo Calculo de promedio de Catedra

### ISSUE THREAD

**Issue by jbsaeza** [IIC2233-2016-02/Syllabus#62]
Debido a que se a eliminado el MidTerm, existe ahora una ponderación con notas respecto a controles, cuando se realizaran estos?, serán sorpresa?, cuantos van a ser?

**Comment by aaossa** [comment]
Hola, los controles ya estaban considerados para la nota (15% ahora). Fechas? Cualquiera. Cantidad? Sorpresa también :hear_no_evil:

**Comment by jbsaeza** [comment]
Y estos se realizaran en horario de cátedra o ayudantia?

**Comment by fgvenegas** [comment]
Catedra siempre
