### ISSUE TITLE
Hablar con personas offline

### ISSUE THREAD

**Issue by asimonv** [IIC2233-2016-02/Syllabus#620]
Se le pueden enviar mensajes a personas que no están online y que cuando se conecten les lleguen? O no es requisito implementar esto.

**Comment by FernandoPieressa** [comment]
Hola! Eso queda tu criterio si necesitas estar conectado para que te lleguen mensajes, o los puedes ver despues, eso si especificalo en el readme! Saludos!

**Comment by asimonv** [comment]
Gracias!
