### ISSUE TITLE
Recorrección Tarea 3

### ISSUE THREAD

**Issue by domingo-valdes** [IIC2233-2016-02/Syllabus#621]
Hola! Cuándo va a estar lista la recorrección de la tarea 3? Ya ha pasado mucho tiempo desde que la mandé y varios de mis compañeros ya tienen la recorrección lista. 😕

**Comment by aaossa** [comment]
Perdón, recién vi esto. @bamavrakis supervisará a quien esté a cargo de tu recorrección y se te contactará cuando se tenga respuesta. Cuando este resuelto se cierra esta issue :ok_hand:
