### ISSUE TITLE
Actividad 14

### ISSUE THREAD

**Issue by smargozzini** [IIC2233-2016-02/Syllabus#622]
Me llego un mail que me dice que yo estuve ausente en la actividad 14, lo respondí pero me gustaría asegurarme por acá ya que yo si fui. Diego Andai el podría confirmar que yo si fui.
Atentamente Sebastian Margozzini.

**Comment by aaossa** [comment]
El correo es la notificación de que una issue se abrió en tu repo. Estos repos nadie los revisa, lo hemos dicho. También hemos dicho que situaciones así se ven por correo, así que te invito a enviarme un mail (con copia a Bastián) para que veamos tu caso y si se puede hacer algo. Te recuerdo que la revisión de la asistencia pasada en la clase es responsabilidad de los alumnos. Espero tu correo :ok_hand:
