### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#624]
![captura de pantalla de 2016-11-16 21-06-11](https://cloud.githubusercontent.com/assets/20784195/20371167/96a30194-ac41-11e6-968b-59aad869e6bf.png)
Que significa este error? estoy iniciando de manera correcta las ventanas :c pero las abre y me tira ese error y se cierrar -.-

**Comment by Hernan4444** [comment]
@narierao sobre tus errores podria decir:

(1) En el primer error se indica que estas haciendo modificaciones de un pixmap, widget (objeto de interfaz) desde otra clase que no es la Gui, por ejemplo desde un thread. usando señales deberia solucionarse ese error
(2) Segun google-sama, el segundo error puede ser porque se esta creando algún Qwidget fuera de la gui principal (tal vez hay un thread que esta creando widget)

Saludos!!
