### ISSUE TITLE
Viernes de Tarea <3

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#625]
Podríamos coordinar una hora para que los ayudantes puedan ayudarnos con nuestras tareas? (con errores como el que mande antes :s) prometo estar todo el dia :c

**Comment by joseluishaddad** [comment]
hola, vengo a bancarte, chao.

**Comment by Nebula2028** [comment]
Porfavor! Me sumo a esto, creo que algún horario en donde nos puedan auxiliar estaría salvador!

**Comment by fgvenegas** [comment]
No es una sala de ayudantia oficial, pero mañana habremos algunos ayudantes en la Alvaro Campos (sala de pizarras) en el Dcc durante el dia :D
