### ISSUE TITLE
QListView como display de chat

### ISSUE THREAD

**Issue by joseluishaddad** [IIC2233-2016-02/Syllabus#626]
Hola, estaba pensando usar QListView para ir mostrando los mensajes que se envían en los chats, pero me entraron dos dudas:
1. Se pueden "appendear" filas a la lista con cada mensaje nuevo o estos objetos (QListView) solo funcionan cargándole todos los datos de una?
2. Creen que es una buena forma de mostrar la conversación?? 😅

Gracias de antemano

**Comment by iqacevedo** [comment]
Hola si se pueden agregar elementos después con addItem creo, yo lo hice con eso y me resultó bien :)
