### ISSUE TITLE
Problema GUI

### ISSUE THREAD

**Issue by lefischer** [IIC2233-2016-02/Syllabus#628]
hola,

no se porque no se me muestran los dibujos en la gui. (en QGraphicsScene)
esta en mi repositorio todo

**Comment by Hernan4444** [comment]
Tu pregunta es demasiado amplia, nos estás preguntando por qué pasan cosas en tu propia tarea. Trata de reducir tus dudas a preguntas puntuales y abre una issue al respecto.
Saludos!

**Comment by lefischer** [comment]
hola, 
no se porque dentro de QGraphicsView la posicion del mouse es siempre 0,0

**Comment by aaossa** [comment]
Teoría: Quizás el focus no está en el widget

**Comment by lefischer** [comment]
hay alguna posibilidad de poder juntarme mañanana con un ayudante para vue cual es el problema

**Comment by Hernan4444** [comment]
#625. Tal como dice ahi, mañana estarán algunos ayudantes en el DCC (sala Álvaro Campos). Sugiero ir con las dudas mas puntuales posibles, así optimizamos el tiempo para resolver dudas
Saludos!!
