### ISSUE TITLE
pikle.load

### ISSUE THREAD

**Issue by Tibrahm** [IIC2233-2016-02/Syllabus#629]
```python
import pickle

relacion = ["A", "B"]
otra_relacion = ["C", "D"]

with open("relaciones", "ab+") as archivo:
    pickle.dump(relacion, archivo)
    pickle.dump(otra_relacion, archivo)

with open("relaciones", "rb") as archivo:
    print(pickle.load(archivo))
```

Como ven solo me retorna la primera lisa que le di pero necesito ambas, nose como hacer para que me devuelva todo !

**Comment by aaossa** [comment]
Prueba buscando exactamente lo que preguntaste

**EDIT:** Además, en lugar de colocar una foto coloca código por favor, es más fácil para poder probarlo
