### ISSUE TITLE
Tarea 5

### ISSUE THREAD

**Issue by Pyralspite** [IIC2233-2016-02/Syllabus#630]
Hola, ya que dudo que puedan subir las notas de la tarea 5 antes del lunes, podrían al menos subir la pauta? Para estimar la nota que tuvimos y evaluar si es necesario hacer la tarea 7 :)

**Comment by flobarrios** [comment]
Hola ! efectivamente, no vamos a tener las notas para el lunes :( Les dejo la pauta:

 # [Tarea 5]

## Overview

---

### Puntaje

| Item | Puntaje |
| :-- | :-- |
| Interfaz gráfica | 0 |
| Jugador | 0 |
| Supervivencia | 0 |
| Etapas | 0 |
| Enemigos | 0 |
| Power-ups | 0 |
| Tienda | 0 |
| Colisiones | 0 |
| Bonus | 0 |
| Descuentos | 0 |

| Nota |
| :-- |
| **1.0** |

### Comentarios Generales

## Desglose Puntaje

---

#### Interfaz gráfica **(1.2 pts)**
- **(0.2 pts)** Item 1: Pantalla de inicio del juego con modalidad etapas y supervivencia, selector de etapas y modo normal.
- **(0.3 pts)** Item 2: Pausa y salida del juego.
- **(0.2 pts)** Item 3: El juego corre con fluidez y sin caerse.
- **(0.1 pts)** Item 4: Se muestra el disparo y su trayectoria por la pantalla.
- **(0.15 pts)** Item 5: Se muestra la vida de cada tanque, tiempo y puntaje correspondiente.
- **(0.15 pts)** Item 6: Funciona correctamente el cargador de balas (mostrando las siguientes dos balas)
- **(0.1 pts)** Item 7: Se diferencias los distintos tipos de bala/portal al disparar.

| Item | Puntaje | Comentarios |
| :-- | :-- | :-- |
| 1 | 0 | - |
| 2 | 0 | - |
| 3 | 0 | - |
| 4 | 0 | - |
| 5 | 0 | - |
| 6 | 0 | - |
| 7 | 0 | - |

#### Jugador **(1.2 pts)**
- **(0.2 pts)** Item 1: Control eje fijo.
- **(0.1 pts)** Item 2: Continuidad en el movimiento del tanque.
- **(0.2 pts)** Item 3: Pierde vida cuando es impactado por bala o bomba.
- **(0.1 pts)** Item 4: Jugador respeta el funcionamiento de las balas normales.
- **(0.2 pts)** Item 5: Se pueden colocar dos portales respetando las reglas descritas y se pueden atravesar.
- **(0.2 pts)** Item 6: Se pueden colocar las bombas y tienen un radio de explosion mayor a la colision balas.
- **(0.2 pts)** Item 7: El puntaje se calcula correctamente.

| Item | Puntaje | Comentarios |
| :-- | :-- | :-- |
| 1 | 0 | - |
| 2 | 0 | - |
| 3 | 0 | - |
| 4 | 0 | - |
| 5 | 0 | - |
| 6 | 0 | - |
| 7 | 0 | - |

#### Supervivencia **(0.6 pts)**
- **(0.15 pts)** Item 1: Se encuentra la muralla indestructible y destructible y la destructible vuelve a aparecer cada cierto tiempo.
- **(0.15 pts)** Item 2: Aparecen tanques de manera incremental.
- **(0.2 pts)** Item 3: Funcionan los Highscores.
- **(0.1 pts)** Item 4: El juego termina al quedar sin vidas.

| Item | Puntaje | Comentarios |
| :-- | :-- | :-- |
| 1 | 0 | - |
| 2 | 0 | - |
| 3 | 0 | - |
| 4 | 0 | - |

#### Etapas **(0.6 pts)**
- **(0.2 pts)** Item 1: Etapas funcionales.
- **(0.3 pts)** Item 2: Las murallas destructibles se destruyen correctamente.
- **(0.1 pts)** Item 3: Vuelve a pantalla inicio si se acaba el tiempo o sin vidas

| Item | Puntaje | Comentarios |
| :-- | :-- | :-- |
| 1 | 0 | - |
| 2 | 0 | - |
| 3 | 0 | - |

#### Enemigos **(0.65 pts)**
- **(0.15 pts)** Item 1: Correcta implementacion tanque_quieto.
- **(0.15 pts)** Item 2: Correcta implementacion tanque_circulo.
- **(0.15 pts)** Item 3: Correcta implementacion tanque_guiador.
- **(0.2 pts)** Item 4: Correcta implementacion tanque_grande.

| Item | Puntaje | Comentarios |
| :-- | :-- | :-- |
| 1 | 0 | - |
| 2 | 0 | - |
| 3 | 0 | - |
| 4 | 0 | - |

#### Power-ups **(0.6 pts)**
- **(0.05 pts)** Item 1: Aparición de power-ups durante el juego 
- **(0.1 pts)** Item 2: Balas especiales: al comprarlas o recogerlas se agregan al cargador
  del tanque como una pila
- **(0.1 pts)** Item 3: Bala explosiva
- **(0.1 pts)** Item 4: Bala perforante
- **(0.1 pts)** Item 5: Bala ralentizante
- **(0.05 pts)** Item 6: Moneda.
- **(0.1 pts)** Item 7: Escudo.

| Item | Puntaje | Comentarios |
| :-- | :-- | :-- |
| 1 | 0 | - |
| 2 | 0 | - |
| 3 | 0 | - |
| 4 | 0 | - |
| 5 | 0 | - |
| 6 | 0 | - |
| 7 | 0 | - |

#### Tienda **(0.5 pts)**
- **(0.2 pts)** Item 1: Correcto acceso a la tienda (se pausa el juego y existe cooldown).
- **(0.1 pts)** Item 2: Es posible subir los stats gastando puntaje y estos se mantienen hasta el fin del juego.
- **(0.1 pts)** Item 3: Los efectos de los stats y su coste se aplican y aumentan acorde a su nivel actual.
- **(0.1 pts)** Item 4: Es posible gastar puntaje en la tienda para comprar balas especiales y/o bombas (se descuenta correctamente del puntaje del jugador).

| Item | Puntaje | Comentarios |
| :-- | :-- | :-- |
| 1 | 0 | - |
| 2 | 0 | - |
| 3 | 0 | - |
| 4 | 0 | - |

#### Colisiones **(0.65 pts)**
- **(0.05 pts)** Item 1: Tanque y bordes/paredes.
- **(0.05 pts)** Item 2: Tanques enemigos y bordes/paredes.
- **(0.05 pts)** Item 3: Tanque principal y tanques enemigos.
- **(0.25 pts)** Item 4: Balas y bordes/paredes.
- **(0.25 pts)** Item 5: Entre balas.

| Item | Puntaje | Comentarios |
| :-- | :-- | :-- |
| 1 | 0 | - |
| 2 | 0 | - |
| 3 | 0 | - |
| 4 | 0 | - |
| 5 | 0 | - |

#### Bonus **(10%)**
- **(0% - 10%)** Item 1: Control Eje Mouse

| Item | Puntaje | Comentarios |
| :-- | :-- | :-- |
| 1 | 0 | - |

#### Descuentos
- **(0.3 pts)** Item 1: Se descuentan 3 décimas máximo por PEP8.
- **(1 pts)** Item 2: Se descuenta 1 punto máximo por entregar tarea en un solo módulo.
- **(0.3 pts)** Item 3: Se descuentan 3 décimas máximo por problemas en el programa (caídas del programa que dificulten correción).
- **(0.5 pts)** Item 4: Se descuentan 5 décimas por mal formato de entrega.

| Item | Descuentos | Comentarios |
| :-- | :-- | :-- |
| 1 | 0 | - |
| 2 | 0 | - |
| 3 | 0 | - |
| 4 | 0 | - |

**Comment by Pyralspite** [comment]
Gracias!

**Comment by DiegoAndai** [comment]
Hola! viendo esta pauta (y habiendo notado cosas parecidas en otras tareas) me parece que la asignación de puntaje se enfoca mucho en el producto visible (en este caso el juego) y poco en la aplicación de la materia del curso, y creo que debiera ser más equitativo (recordaré ponerlo en la encuesta docente para que lo tengan en cuenta). 

Aquí por ejemplo no veo ningún punto sobre la separación de frontend y backend, sobre la que se recalcó harto y que quitaba bastante tiempo por que había que estar tratando todo mediante señales. Tampoco hay puntaje en la aplicación misma de threads y el uso correcto de QTimers y QThreads, obviamente su uso se refleja en ciertas partes del juego (como que no se caiga), pero me parece que debiese darse un foco mayor a este ítem. No veo tampoco evaluado ningún concepto propio de pyQt, como el correcto uso de MainWindows, Widgets, Labels, Pixmaps. Lo que quiero decir es que el foco está demasiado cargado al producto, y creo que debería darse igual importancia a la implementación en sí, ya que en esta se refleja directamente la materia del semestre.

De la misma forma, en ninguna tarea se evaluó si se evitaba la modelación circular explicada en [esta](https://github.com/IIC2233-2016-1/syllabus/issues/481) lectura y que me parece es un concepto muy importante y que también quitaba tiempo. En fin, quizás este no es el lugar de exponer esto pero leí la pauta y me pareció un poco notorio, algo que ya venía ocurriendo en las otras tareas con sus respectivos conceptos. En la tarea del intérprete matemático el puntaje de funcional era bajo también, y en la de Go el juego tenía más nota que las estructuras de datos.

Quizás se podrían sacar tantos detalles de las tareas y agregar más carga en la materia, que es lo que estamos aprendiendo, al fin y al cabo. No digo que tenga más puntaje, pero al menos la misma cantidad, pues entiendo que el objetivo de las tareas también es que aprendamos a escribir código que funcione bien (buen producto).

Saludos 😃

**Comment by Hernan4444** [comment]
@DiegoAndai, en relación al feedback que nos estas dando, queremos aprovechar la instancia de aclarar algunos puntos c:

(1) Tales contenidos que tu indicas son tratados de manera transversal. Por ejemplo no hacer modelación circular es verdad que no posee puntaje pero es un fuerte determinante para cuando estamos revisando errores de código, mientras menos modelado esta mas tiempo nos demoramos en responder puesto que nos dificulta separar errores de modelación con el error que le aparece al alumno.

(2) Un punto similar es para el frontend y backend, nosotros recalcamos mucho esto pero no era el fin que lo hicieran solo porque "tenia puntaje" sino que lo implementaran así como una buena practica, en general la tarea de interfaz es densa por lo mismo para quien no realiza una correcta separación de frontend y backend al final de queda atascado con tantas cosas mezcladas, situación que se ve reflejada claramente en la nota. 

(3) Sobre el enfoque que tiene la tarea, esto se debe a que formas de programar hay muchas  y son igualmente validas (por ejemplo esta tarea se podría haber hecho con Qgraphics y por lo tanto no usaría el mismo material que alguien que usó labels y pixmaps), el propósito de enfocarse en el producto es que ustedes, los alumnos, logren dar un paso mas que solo programar en base al material y que programen un código funcional pero ordenado puesto que estas tareas no se hacen de una y por lo tanto a tu yo del futuro le gustaría tener un código ordenado para seguir mejorando 

(4) Tal vez esto es muy alejado a la realidad por el momento, pero al fin de cuentas muchos programadores estaremos creando programas a clientes y a ellos no les importará mucho como lo hiciste, sino si funciona como quiere o no. Al único que le importará si esta ordenado y correctamente modelado será a tu equipo de trabajo y a ti. Por otro lado, una realidad es que en algunos cursos del DCC que vienen después de avanzada, tus tareas serán corregidas con test y la nota es 7.0 si funciona, 1.0 si es que no. Ahí no importará cuantas lineas de código hiciste. 

(5) Por ultimo queremos recalcar que durante la corrección de las tareas los ayudantes leemos su código si nos fijamos en la modelación los cuales se refleja en los comentarios que intentamos hacerles en el feedback o a través de los descuentos que hacemos cuando no lo hace como se debe.

De todos modos no olvides dejarlo en la encuesta docente para tener esta valiosa opinión en cuenta cuando se planifique el próximo semestre. 

Saludos y exito que lo que queda del curso!! :smile:

**Comment by cjgazali** [comment]
¿Será posible tener también (y cuanto antes) el desglose de puntaje de la tarea 6?
Fue muy bonito cuando en el enunciado de la tarea 3 pusieron el peso de cada ítem en el puntaje y en realidad se extraña mucho en estos días para tomar sabias decisiones entre tanta pega...
