### ISSUE TITLE
chats y ventanas

### ISSUE THREAD

**Issue by FranciscoLarach** [IIC2233-2016-02/Syllabus#631]
hola!
¿pueden explicar en un breve resumen como deberían ser las ventanas del juego en las distintas instancias?
Me refiero de que al iniciar sesión se me muestra una ventana que tiene un chat que es ... ¿con todos los que no están en una sala?¿mis amigos? ¿y ahí tengo la opción de ver mis amigos? y.. ¿tengo la opción de sumarme a una sala al azar y de crear una? ¿ademas puedo ver estadísticas?
Y en las salas de juego ¿solo esta el chat con los de la sala?
Gracias y disculpas lo confundido

**Comment by FernandoPieressa** [comment]
Hola! No te puedo responder exactamente de como tiene que ser cada ventana, puesto que es a criterio tuyo el diseño exacto de la pagina mientras que se cumpla todo lo pedido.

Respecto a las dudas puntuales:

1) No existe el chat publico con todos los usuarios conectados, se podria decir que hay 3 chats distintos. El del juego en si, con todos los que estan jugando y es en donde se adivinan las palabras. Despues esta el chat individual entre amigos, lo puedes considerar 1 a 1 tipo whatsapp. Finalmente esta el grupal, donde hablas con todos los del grupo

2) Exactamente como dijiste, debes poder crear una sala o unirte a alguna (mientras no sea de grupo)

3) Se podria decir que al entrar al chat grupal, puedas ver todas las opciones y informacion pedida del grupo al lado del chat

En verdad todo lo que sea como hacer y que debe tener cada ventana esta totalmente a tu criterio, lo mejor es dejarlo lo mas claro y ordenado posible a tu juicio y si crees que nos podemos complicar encontrando alguna funcionalidad especifica decirlo en el readme :)

Saludos!
