### ISSUE TITLE
Render QScene a QImage

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#632]
Hola! Estoy teniendo problemas para obtener una QImage (o Qpixmap) desde la QScene. Segun lo que encontre en internet una forma de hacerlo seria usar el metodo render de la QScene, crear un QImage, crear un QPainter, y que el QPainter haga la imagen. Luego, para chequiar, guardo la QImage en un archivo PNG, pero este es todo negro. Es decir, no se guardo la imagen correctamente. Alguien sabe porque podria estar pasando esto? Muchas gracias

**Comment by iqacevedo** [comment]
@abannura yo tenía un problema similar, por lo menos a mí se me arreglo entregando un parámetro de formato en el QImage cuando lo creaba, del tipo QImage.Format_"algo" (no recuerdo bien cuál era ese algo jajajajaj)
Saludos !

**Comment by andresbannuraschultz** [comment]
Estoy usando QImage.Format_RGB32! Imposible que te acuerdes cual usaste? :D jajaja

**Comment by sormazabal** [comment]
@abannura  yo tenía el mismo problema, y después me di cuenta que me salía todo negro porque no había puesto el fondo de mi imagen como blanco

**Comment by andresbannuraschultz** [comment]
Gracias @sormazabal  eso era!
