### ISSUE TITLE
Duda Guardar Imagen - método save() de QImage

### ISSUE THREAD

**Issue by lampuerov** [IIC2233-2016-02/Syllabus#633]
Hola, quería ver si puedo usar el método save de un PyQt4.QtGui.QImage object para guardar las imágenes, a este método se le entrega como parámetros el nombre del archivo y el formato("png"). La utilización de este método ahorra la manipulación de los bytes, si bien entiendo la manipulación en chunks es para enviar la imagen desde el cliente al servidor, pero qué pasaría si aprovechando el intercambio de información del mouse entre el dibujante-servidor-otrosjugadores en el servidor se crea un Dibujo en paralelo igual al que poseen el jugador que dibuja y al finalizar el tiempo se guarda desde el servidor el dibujo utilizando el método save()?, es esto válido o se espera que creemos de todas formas el .png?
Gracias de antemano.

**Comment by Hernan4444** [comment]
@Tyrell-Wellick en #555  declaramos que usar esta  built-in no esta prohibida pero no se te asignará puntaje en esa parte puesto que lo evaluado en esa sección no se logra usando ese método pero si cuando lo manipulas como bytes.

Saludos!!

**Comment by lampuerov** [comment]
Gracias por la aclaración! 👍
