### ISSUE TITLE
Fecha de entrega Tarea 6

### ISSUE THREAD

**Issue by fabraghetto** [IIC2233-2016-02/Syllabus#634]
Hola, me surgió algo más o menos terrible. Según el enunciado que tengo de la Tarea 6, la fecha de entrega es para el 28 de Noviembre
![pantallazo enunciado tarea seis progra avanzada](https://cloud.githubusercontent.com/assets/20796589/20414409/04d1ebce-ad11-11e6-9e9d-f977c5084cd7.png)
Y obviamente me programé con el estudio de todos los exámenes, ultimas ies y trabajos finales pensando que se tenía la tarea para esa fecha (No tengo nada hecho en este momento). Me acabo de enterar por suerte que la fecha que sale del enunciado del Syllabus es el 20 de Noviembre. Nunca pensé que podrían cambiar la fecha y que si la cambiaban adelantándola se asegurarían de que todos se enterarán.
Mi duda entonces es mas o menos obvia... esa es la fecha definitiva??, casi que la entrego para el 28 si no fuera porque otra persona me hablo sobre la tarea. Adjunto mi enunciado de la Tarea por si acaso.
[Enunciado T06.pdf](https://github.com/IIC2233-2016-02/Syllabus/files/598826/Enunciado.T06.pdf)

**Comment by lampuerov** [comment]
Yo también lei que la entrega era para el 28, aunque por suerte tengo algo avanzado de la tarea. Se podrá hacer algo respecto a la fecha de entrega o la del 20 es definitiva?. Saludos

**Comment by aaossa** [comment]
Hola, este no es el lugar para resolver situaciones particulares, el lugar correcto es el mail, a los jefes del área y con copia a Bastián (lo hemos repetido harto).
