### ISSUE TITLE
Problema con PNG

### ISSUE THREAD

**Issue by cglevican** [IIC2233-2016-02/Syllabus#635]
Tengo un problema al realizar el cambio hacia los bytes con el IHDR, y IDAT.
Por ejemplo, cuando transformo a bytes la siguiente lista: [298, 282, 16, 2, 0, 0, 0], la respuesta es:
b'\r\x00\x00\x00IHDR*\x01\x00\x00\x1a\x01\x00\x00\x10\x02\x00\x00\x00\xcb\x9e\xb9\x03'
Hay carácteres extras como r y * que pueden estar influyendo en que mi código no funcione.
PD: además la scene se me corre cada vez que agrego algo.

**Comment by Hernan4444** [comment]
@cglevican sobre la r, esa aparece porque la codificacion (byteorder) que estas usando permite esa. Revisando tu código me percate que usas sys.byteorder, para el manejo de bytes en PNG, el byteorder dejalo como "big". Sobre el \* no te tienes que preocupar, solo es una forma que el computador hace para guardar un numero en forma de hexa. Eso no generará problemas en tu código.

En relación a tu otro problema de que se te corre la escena, como sugerencia intenta usar el método de QgraphicsView llamado setSceneRect. Este método recibe un QRectF y lo que hace es otorgarle un valor fijo a la pantalla. pero ¿Que valores le doy al QRectF?, te sugiero investigar acerca del viewport().

Edit: de ahi nos cuentas si sigues con problemas o lo lograste solucionar c:

Saludos!!

**Comment by DiegoAndai** [comment]
En este mismo tema, quería preguntar si me pueden ayudar con mi código. Acabo de subirlo, si me pueden revisar por favor, en el archivo windowlib.py existe el método save_png(self) [líneas 586-637] en el que hago el parse para guardar el PNG y lo guardo, por alguna razón guarda la imagen muy extraño (según yo tiene que ver con que se corre una línea o algo así):

![1](https://cloud.githubusercontent.com/assets/16889233/20460723/c607ee7c-aecb-11e6-9377-ab2b9b30b428.png)

(no lo subí dos veces, sale doble no se porque) ahí debería haberse guardado un cuadrado negro y adentro de este un círculo rojo con un fondo blanco. He revisado y revisado y no logro encontrar el error. Si quieren probar pueden ejecutar Server.py junto a main.py, registrarse, dibujar y apretar el botón Save drawing (está a la izquierda), se guardara la imagen como "programillo.png"

Muchas gracias de antemano

**Comment by Hernan4444** [comment]
@DiegoAndai primero prueba cambiando el bit de profundidad de 16 a 8. Segundo, verifica que estas agregando un bit de 0 en cada fila. Después de eso nos muestras como resultó la imagen.

Saludos

**Comment by DiegoAndai** [comment]
Cambiarle la profundidad lo arreglo 👌 muchas gracias 😄
