### ISSUE TITLE
Dudas de PyQt4

### ISSUE THREAD

**Issue by gabrielpinkman** [IIC2233-2016-02/Syllabus#636]
Hola, me gustaría conocer las diferencias entre QLineEdit y QTextEdit si pudieran ser tan amables :c

**Comment by Hernan4444** [comment]
@gabrielpinkman tal como su nombre indica, el primer elemento es para escribir una linea de texto, esto implica que si comienzas a escribir mas caracteres de lo alcanzado en la ventana, esta se debería expandir de forma vertical enfatizando en mostrar la ultima palabra escrita.
En cambio un QtextEdit está hecho para soportar textos, ante el mismo caso de antes, si escribas mas caracteres de los alcanzado. este ultimo se expandirá de forma horizontal privilegiando ver la mayor cantidad de texto posible.

A modo de ejemplo, los chat de facebook se podrian ver como QtextEdit mientras que el buscador de google seria un QLineEdit.

Saludos!!!
