### ISSUE TITLE
Se rompio mi GUI :(

### ISSUE THREAD

**Issue by jbsaeza** [IIC2233-2016-02/Syllabus#637]
Tenia mi gui funcionando perfectamente pero luego de agregar los métodos para guardar los usuarios en un json, dejo de funcionar en parte, (ya subí mi código si pudieran revisarlo para entender mejor mi problema) cuando me registro y luego presiono el botón, que luego de comprobar que todo esta en orden, debería iniciar el menú principal de mi gui, aparece la ventana pero esta se pegue y arroja "No responde" y no me queda otra que cerrarla. Es raro por que logra guardar la información del usuario y la gui se inicializa bien (probe con varios prints y estos funcionan), y si intento acceder a ella mediante login esta funciona bien. Luego de googlear encontré que algún proceso que todavía esta corriendo podria estar interfiriendo con la gui, pero no creo que sea esto debido a que todo proceso paralelo esta siendo manejado por threads. Ayura D:

**Comment by Hernan4444** [comment]
@jbsaeza revisé tu codigo y el error proviene por la modelación que estas ocupando, estas haciendo que un objeto ejecuta al método de un objeto que es atributo atributo de otro objeto `self.objeto.otro_objeto.metodo()`  (Hint: cliente.py linea 51). 
¿Como solucionar esto? Señales!!!
Acabo de implementar con tu código el uso de señales para el registro y ya no se atascó.

Saludos!!

**Comment by jbsaeza** [comment]
@Hernan4444  Muchas gracias, funciono perfecto 👍
