### ISSUE TITLE
Ultimo paso para pasar a formato PNG

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#638]
Cuando ya tengo un bytearray con la sequencia inicial mas los 3 chunks (ihdr, idat e iend), lo escribo a un archivo .png que creo en modo "wb" nomas? Muchas gracias

**Comment by Hernan4444** [comment]
@abannura asi es :D 

Saludos!!

**Comment by andresbannuraschultz** [comment]
Gracias!!
