### ISSUE TITLE
Propiedad intelectual y utilización de codigos encontrados en internet

### ISSUE THREAD

**Issue by Gonzalo-Perez** [IIC2233-2016-02/Syllabus#639]
Quisiera saber hasta que punto está aceptada la utilización de códigos publicados en internet.

Por ejemplo si, buscando como hacer lo que piden en una tarea, encuentro un código que hace algo de lo que ustedes piden, hasta que punto puede usarse?

Además quisiera saber como se cita un código. Es decir, si uso un código libre publicado "al mundo" por alguien, como debe citarse esa referencia en mi trabajo?

De antemano, gracias !

Saludos,

Gonzalo Pérez.

**Comment by FernandoPieressa** [comment]
Hola!

La idea es no usar copy/paste sino entender los codigos de internet y usarlos como guia en su trabajo.
Si te empiezas a guiar demasiado y es una parte considerable de codigo, lo que tienes que hacer es poner en el readme que paginas utilizaste y para que parte.

Saludos!

**Comment by Gonzalo-Perez** [comment]
Ok, gracias !

Y cuando se trabaja con librerías proporcionadas por otra gente (publicaciones de código libre o de trabajo en equipo) no hay como una forma estandard de poner al inicio del código alguna referencia?
Me imagino algo asi como:

``` python
__author__ = 'Joaquín Silva'
__collaborators__ = 'Rodrigo Casas' &'Francisca Rodriguez'
```

De antemano, gracias.

**Comment by aaossa** [comment]
Hola @Gonzalo-Perez 

El código público siempre debe ir acompañado de una licencia (puedes ver un poco mas [aca](https://help.github.com/articles/open-source-licensing/)). Lo que se hace normalmente, y que se puede ver bastante en GitHub, es crear un archivo con la licencia en el código fuente. A modo de ejemplo, puedes mirar la licencia en el repo de [kennethreitz/requests](https://github.com/kennethreitz/requests/blob/master/LICENSE). También en algunos casos la licencia se coloca en todos los archivos del repo (a mi no me gusta como se ve, [ejemplo en código de Tensorflow](https://github.com/tensorflow/models/blob/master/im2txt/im2txt/configuration.py)). 

En ambos casos, tu utilizarás este código como un requerimiento, no deberías poner el código fuente junto con el tuyo para evitar esta ambigüedad, aunque puedes hacerle modificaciones si la licencia lo permite y bajo las condiciones de la misma. No es necesario que hagas lo que pusiste en tu último comentario, porque tu no estás colocando el código de esas personas junto con el tuyo, no te estás adjudicando la propiedad. 

Otro caso común es tomar código de StackOverflow. El código de las respuestas de esa página está bajo la licencia Creative Commons ([source](http://stackoverflow.com/a/26395396/3281097)), por lo que un ejemplo de cita de SO sería, basado en [CreativeCommons](https://wiki.creativecommons.org/wiki/Best_practices_for_attribution#This_is_an_ideal_attribution) y [Meta-StackExchange](http://meta.stackexchange.com/questions/272956/a-new-code-license-the-mit-this-time-with-attribution-required):

``` python
# Project: Code from StackOverflow page <link a la pagina>
# Code Author: <link al usuario>
# Licensed under CC-Wiki <link a la licencia>
```

Pero lo que normalmente se hace, y es suficiente al parecer ([source](https://github.com/moment/moment/blob/497f918515ae6ab900f008f19523b1e4ae5e2450/src/lib/parse/regex.js#L45)):

``` js
// Code from http://stackoverflow.com/questions/3561493/is-there-a-regexp-escape-function-in-javascript
function unescapeFormat(s) {
    return regexEscape(s.replace('\\', '').replace(/\\(\[)|\\(\])|\[([^\]\[]*)\]|\\(.)/g, function (matched, p1, p2, p3, p4) {
        return p1 || p2 || p3 || p4;
    }));
}
```

Pero...

### no queremos que citen grandes porciones de código porque para aprender realmente como funciona algo, tienes que hacerlo tu mismo.

**Extras** 
- [Interesante respuesta en Quora](https://www.quora.com/How-do-I-properly-credit-an-original-codes-developer-for-her-open-source-contribution/answer/Gil-Yehuda?srid=uEw8q) sobre el tema :ok_hand: 
- [Una razón para no copiar de SO](http://www.theverge.com/tldr/2016/5/4/11593084/dont-get-busted-copying-code-from-stack-overflow)
