### ISSUE TITLE
Archivos json al corregir

### ISSUE THREAD

**Issue by Tomizaky** [IIC2233-2016-02/Syllabus#64]
Hola! Por ahí leí que al revisar la tarea usarán otros archivos json. Son estos iguales a los originales que están en el repo?
Pregunto esto para saber si puedo confiar por ejemplo en el orden de la lista en programones.json

**Comment by jgmontoya** [comment]
Hola, 
No cuentes con que sean iguales. Es más, podrían haber pokemones completamente nuevos en los archivos que ocupemos para revisar y tu programa debería funcionar bien con estos. Lo que sí se mantiene es la estructura de la información.
Saludos!

**Comment by Tomizaky** [comment]
Gracias!

**Comment by Hernan4444** [comment]
Por si acaso revisa la issue #28
