### ISSUE TITLE
Desglose puntaje T06

### ISSUE THREAD

**Issue by vigazali** [IIC2233-2016-02/Syllabus#641]
Ayudanteees!!!

Estoy en una situación que, tanto en esta tarea como el la T07 necesito mucha nota para pasar... Y estando ya totalmente contra el reloj, de verdad es urgente saber qué es lo que ponderará más para la T06 y así intentar alcanzar la nota necesaria. Me imagino que no soy el único en esta situación, entonces, ¿podrían subir el desglose de puntaje de los ítemes de la T06?

¡Muchas gracias!

**Comment by vigazali** [comment]
PD: algunos ya han pedido esto en otras issues, pero parece que no los han visto, así que aproveché de hacer una issue especialmente

**Comment by FernandoPieressa** [comment]
Hola! Puesto que la tarea no acaba aun no podemos darles el desglose entero del puntaje, sin embargo les daremos los porcentajes de cuanto vale cada parte para que puedan tener una idea.
- Cliente-Servidor : 13.3%
- Manejo de usuario: 17.5%
- El Juego: 25.83%
- Guardar imagen: 10%
- Salas de juego: 11.6%
- Chats: 21.6%

Espero que les sirva para tomar la decision correcta.

Saludos!

**Comment by vigazali** [comment]
Gracias @FernandoPieressa !! De todas maneras que ayuda!

**Comment by sormazabal** [comment]
@FernandoPieressa  a qué se refieren con manejo de usuario?

**Comment by jgmontoya** [comment]
@sormazabal Todo lo que está en el enunciado respecto al manejo de sesiones, es decir que se pueda registrar (usando el sistema de autenticación adecuado), hacer log-in, que la información de los usuarios sea persistente, etc..

**Comment by sormazabal** [comment]
@jgmontoya otra pregunta, la parte del paint está incluida en guardar la imagen o en el juego?

**Comment by FernandoPieressa** [comment]
@sormazabal En el juego, guardar imagen es solo guardarla, no crearla
