### ISSUE TITLE
control de salida

### ISSUE THREAD

**Issue by FranciscoLarach** [IIC2233-2016-02/Syllabus#642]
Hola
Existe alguna manera y como se puede controlar el evento de salida de un cliente? por ejemplo si apretar la "x" roja para cerrar la ventana? (para imponer algunas condiciones a la salida).
Gracias

**Comment by FernandoPieressa** [comment]
http://stackoverflow.com/questions/9249500/pyside-pyqt-detect-if-user-trying-to-close-window
