### ISSUE TITLE
Problemas con abrir ventanas 

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#643]
Tengo una clase que se llama espera (es una ventana que sale cuando ya ingresos a que sala quiero jugar, etc) el problema es que tengo que mandar una señal al cliente que me diga (te toca dibujar, o adivina la palabra) y dependiendo de eso me abra ventanas, (la clase espera tiene a mi cliente) el problema es que Python no deja abrir ventanas desde thread y ya llevo como 5 días intentando sacar esto. 

Como referencia intente hacer una clase Qthread que esperara a que un valor de cliente cambiara y abriera mi ventana (no funcionó -.-) 

Intenté usar emit.SIGNAL pero no entendí tan bien cómo funcionaba a sí que también lo descarte 

Intente abrir las ventanas tapando la procedencia del thread (3 funciones como para engañar a Python) 

Intenté dejar una especie de thread (que en verdad era solo un while True) y mi programa se me pegaba y moría. 

De verdad que tengo una buena interfaz y me da pena no poder usarla T.T 

Ayuda!!!! 😭💔

**Comment by narierao** [comment]
Acabo de subir una actualización de mi repo por si quieres cachar que es lo que intento hacer, sería en el archivo cliente (línea 182 y 186) y en el archivo Espera (línea 19). Ambas están en la carpeta Cliente por si le quieren echar un vistazo :( ❤️

**Comment by Hernan4444** [comment]
@narierao lo que intentas hacer tiene una solución y justamente es la que descartaste porque no entendías tan bien como funcionaba.
Te sugiero que revises el material del curso de interfaz, las señales no solo se envían mediante el emit.SIGNAL, en el material se presenta otra alternativa

Saludos!!

**Comment by narierao** [comment]
Ok. Avisaré en el caso qu eme funcione o que no xD saludos.

**Comment by narierao** [comment]
@Hernan4444  Si algun dia te llego a conocer, recuerdame que te debo un chocolate! despues de cinco dias al fin saque el error! Gracias <3
