### ISSUE TITLE
Error que no es Error

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#644]
En la consola me dice que un metodo de una clase no existe, pero aun asi, se ejecuta lo que hace el metodo xD tengo que corregir esto? si igual funciona :0

**Comment by Hernan4444** [comment]
@narierao puedes subir que el error es y cual es el procedimiento para que se genere tal error.
Saludos!!

**Comment by narierao** [comment]
![captura de pantalla de 2016-11-19 17-54-40](https://cloud.githubusercontent.com/assets/20784195/20458342/49f31c98-ae81-11e6-986e-daee43138603.png)

Este es el error que se genera, ocurre cuando le digo a mi cliente agrega este item a tu pantalla (tengo definido el metodo y todo, incluso lo agrega. Estoy convencido que es por el orden de iniciacion de la clase :0)

**Comment by narierao** [comment]
ya lo solucione, me estaba equivocando en algo muy idota xD gracias igual.
