### ISSUE TITLE
Servidor-Cliente 

### ISSUE THREAD

**Issue by lampuerov** [IIC2233-2016-02/Syllabus#645]
Hola, necesariamente la comunicación entre servidor-cliente debe ser probada en más de un pc?, o basta con que corra en mi pc respetando la edición de archivos que corresponde al servidor y cliente?. Lo que pasa es que al probarlo solo en mi pc no tengo problemas, pero al correr el archivo del cliente en otro pc no puedo establecer la conexión de forma apropiada. Cuáles son las posibles causas y soluciones a este problema? (Tengo arriba mi código). Gracias de antemano

**Comment by fgvenegas** [comment]
#581 #585
