### ISSUE TITLE
save image

### ISSUE THREAD

**Issue by lefischer** [IIC2233-2016-02/Syllabus#646]
Hola

las imagenes las guardo haciendo QGraphicsScene.render()
esta permitido hacerlo?

**Comment by Hernan4444** [comment]
@lefischer el render solo esta permitido como vía para obtener la matriz, si tu haces render pero luego ocupas save o cualquier método que te permita guardar el png sin pasar por el manejo de bytes del enunciado no sera considerado para el puntaje. No te penalizamos pero tampoco te otorgamos puntos.

Saludos!!

**Comment by lefischer** [comment]
hola

no me funciona guardar a png, no se si comprendi algo mal del enunciado.
me aparece que el formato del archivo no es compatible

**Comment by aaossa** [comment]
@lefischer no te funciona... que cosa? Usar `save`? Tu función para generar el archivo? Especifica un poco mas para poder ayudarte.

**Comment by lefischer** [comment]
lo que no me funciona es la funcion save de central widget, el largo del idat esta calculado correctamente pero al abrir la imagen me aparece que el formato del archivo no es compatible
