### ISSUE TITLE
Problema con señales 

### ISSUE THREAD

**Issue by gabrielpinkman** [IIC2233-2016-02/Syllabus#647]
Hola, cuando corro mi programa tengo la siguiente advertencia:

QObject::startTimer: timers cannot be started from another thread

La verdad estaba buscando en internet sobre cual es el problema con la advertencia, pero no me queda claro, me pueden ayudar? el error sale cuando corro el archivo "interfaz_juego.py" está en mi repo

**Comment by Hernan4444** [comment]
@gabrielpinkman ese error sale porque un thread esta intentando cambiar (o crear) un objeto de la clase Object (cualquier objeto de PyQt), esto se soluciona aplicando señales para que la misma interfaz edite los objetos de pyqt o los creé. El thread solo le avisa lo que tiene que hacer.

Saludos!!!
