### ISSUE TITLE
Templates Rectangulos/Cuadrados

### ISSUE THREAD

**Issue by ndleyton** [IIC2233-2016-02/Syllabus#648]
Hola, me preguntaba si es necesario hacer un template para rectangulos y otro para cuadrados, ya que haciendo en la forma en como tengo el hacer un rectangulo se puede dejar como un cuadrado.

Adicionalmente, considero que es bastante más 'libre' que el template de circulos sea de elipses, puedo dejarlo así?

**Comment by FernandoPieressa** [comment]
Hola!

Mientras de tu forma se pueda generar tanto rectangulos como cuadrados esta bien. Lo mismo con la idea de los elipses.

Saludos!

**Comment by ndleyton** [comment]
Muchas gracias
