### ISSUE TITLE
Problemas al usar un Thread para modificar la GUI

### ISSUE THREAD

**Issue by joseluishaddad** [IIC2233-2016-02/Syllabus#649]
Hola, estoy teniendo problemas para modificar mi GUI desde un thread hecho con threading.Thread que corresponde a un método de la misma clase de la GUI. 
Me lanza el error:
`QObject::setParent: Cannot set parent, new parent is in a different thread`

Qué puedo hacer D:
Saludos!

**Comment by narierao** [comment]
no puedes modificar la GUI desde un thread, debes hacerlo desde el main emitiendo una señal del thread. Revisa el material de curso. ahi sale la explicacion de como hacer (esta en GUI casi al final)

**Comment by aaossa** [comment]
#588 #511
