### ISSUE TITLE
Modo Guardado

### ISSUE THREAD

**Issue by fringlesinthestreet** [IIC2233-2016-02/Syllabus#65]
¿Es necesario que la información que se guarde, para ser usada en otra corrida del código, esté escrita como .json? ¿Podríamos usar pickle?

**Comment by flobarrios** [comment]
Hola! no necesariamente tiene que ser json pero no pueden usar pickle, ya que corresponde a parte de la materia que verán mas adelante. Saludos!

**Comment by jgmontoya** [comment]
Por favor preguntas de módulos hacerlas en #21 (aprovecho de agregar pickle).
