### ISSUE TITLE
Error QTimer

### ISSUE THREAD

**Issue by ndleyton** [IIC2233-2016-02/Syllabus#651]
Hola, quería tener un QTimer que fuese controlando la logica de cada sala de juego, pero no puedo iniciarlo como thread, ya que me arroja el error `QObject::startTimer: QTimer can only be used with threads started with QThread`. Usé muchos QTimers en la tarea 5 y los estoy inicializando de manera similar, pero no se por qué  el error. ¿Hay alguna forma de evitarlo?

**Comment by jgmontoya** [comment]
Hola,

Estás iniciando los QTimers con threads de `threading` o no?
Si es así prueba usando QThreads en vez de esos.

Saludos!

**Comment by ndleyton** [comment]
Hola, arreglé el problema, sucedía que como en **server.py** no hay GUI, no estaba iniciando una app

**Comment by ndleyton** [comment]
Mentira, cuando quiero interactuar con el QTimer vuelve a lanzar el error.
Lo inicializo con 
`timer.timeout.connect(timer.run)`

**Comment by Hernan4444** [comment]
@ndleyton  te sugiero que sigas el consejo de montoya y uses qthread

Saludos!!

**Comment by ndleyton** [comment]
Trataré, gracias!
