### ISSUE TITLE
Duda sobre loggeo

### ISSUE THREAD

**Issue by roy350** [IIC2233-2016-02/Syllabus#655]
Disculpen pero me queda una duda respecto al loggeo que sea realizar para probar la tarea, no me queda claro si tendemos que proporcionar una cuenta de youtube o las client_id y el client_secret, o los dejamos como un input y uds ingresan con la suya, muchas gracias!

**Comment by srvasquez** [comment]
Según lo que entendí, debemos proporcionarles todo lo necesario para hacer funcionar nuestra interfaz con los requerimientos pedidos, el client_secret.json lo puedes conseguir al momento de crear una credencial en la console developers de google.

**Comment by FernandoPieressa** [comment]
Hola!

La idea es que lo reciba como parametro en alguna parte para que nosotros podamos editarlo con otros datos de cuenta.

En esos parámetros que hagan ustedes ponen sus datos con la cuenta que vayan a crear para probar la tarea.

Saludos!

**Comment by srvasquez** [comment]
Eso significa que esa interacción tiene que ser parte de la interfaz de nuestro programa ? Me refiero a que si un usuario hace login con la interfaz igual necesitaríamos el client_secret, me tiene algo confundido.

**Comment by FernandoPieressa** [comment]
Como sale en la parte 4.2.1, tiene que ser mediante la interfaz. Ahi haces que te pida los parámetros necesarios para iniciar sesión con la api y poder hacer todos los requests correctos.

Eso si en alguna parte deja los parametros que usaste por cualquier problema que tengamos para iniciar sesion.

Saludos!

**Comment by srvasquez** [comment]
Lo que me esta complicando, es el login, para los request hay buena info. He buscado como hacer login en una API y encontre que google tiene algo llamado ClientLogin pero en todos los foros decian que era algo obsoleto y con muchos errores. Especificamente la duda es como crear una credencial asociada a un mail, ya que para eso hay que crear un proyecto que cumpla con unas especificaciones y eso es lo que no encuentro como hacer a traves de la interfaz.

**Comment by lfbesa** [comment]
Tengo la misma duda que srvasquez

**Comment by juliandewulf** [comment]
Lo mismo aca, alfinal como lo dejaron?
