### ISSUE TITLE
Duda sobre código de ejemplo

### ISSUE THREAD

**Issue by sebacruzd** [IIC2233-2016-02/Syllabus#656]
Hola,

Estoy ejecutando un código de ejemplo que encontré en uno de los links que nos dieron, específicamente el de **[esta página](https://developers.google.com/youtube/v3/code_samples/python#create_a_playlist)**.

Estaba probando el de **crear una lista de reproducción** y al ejecutar el código por primera vez (o cuando no existe el archivo "playlist.py-oauth2.json") me pide acceso a mi cuenta en mi explorador de internet, como sale en la foto:
![image](https://cloud.githubusercontent.com/assets/14894992/20507361/05efb4e8-b039-11e6-8216-3e216a33975b.png)

Está bien que pase esto o en mi programa no debería abrirse nada en el explorador y simplemente modificar la cuenta sin preguntarme nada? En este caso, crear una playlist sin pedir el permiso que sale en la imagen.

Es este el paso que debería hacer yo usando las credenciales de youtube que uno debe proporcionar a la interfaz gráfica, que se menciona en el enunciado?
Será que con alguna especie de POST haga log-in a la cuenta y evite que me pida el permiso fuera del programa que estoy haciendo?

Perdón si son muy obvias/mal hechas las preguntas, pero he estado varias horas y no encuentro respuestas en google que apunten exactamente a estas dudas.

Gracias de antemano!

**Comment by sebacruzd** [comment]
Update.
**[Acá](https://developers.google.com/youtube/v3/guides/authentication)**  encontré información sobre lo último que decía.

Dice que al intentar usar por primera vez una funcionalidad de la aplicación

> La aplicación dirige al usuario al servidor de autorización de Google.

Que es lo que me está ocurriendo.
Esto me genera confusión, ya que por otro issue #655, entiendo que debe ser todo por interfaz 😕

**Comment by jgmontoya** [comment]
Hola, 

Es normal que pase eso, sin embargo para la tarea esto debe mostrarse desde su programa en vez de abrirse con un browser aparte.

Saludos!

**Comment by sebacruzd** [comment]
Gracias!

**Comment by jgmontoya** [comment]
> Es normal que pase eso, sin embargo para la tarea esto debe mostrarse desde su programa en vez de abrirse con un browser aparte.

Esto queda de bonus finalmente por si no se enteraron.

Saludos!
