### ISSUE TITLE
Sobre credenciales

### ISSUE THREAD

**Issue by gabrielpinkman** [IIC2233-2016-02/Syllabus#657]
Hola, vengo por una duda grande.

En la tarea se nos pide trabajar con YouTube Data API , la cual, según entiendo, funciona si conseguimos ciertas credenciales de autorización, sin embargo se nos pide elegir entre OAuth 2.0 o API Keys. En la página explican las diferencias, pero no me queda claro cuál realmente hay que pedir para la tarea

**Comment by sebacruzd** [comment]
Si quieres realizar cambios debes usar OAuth2, por ejemplo para crear una playlist.
En cambio, si quieres buscar una canción por ejemplo (buscar por palabra clave) solo necesitas una API key.

Hay ejemplos sobre eso en los links que están en el enunciado, específicamente [este](https://developers.google.com/youtube/v3/code_samples/python)
Saludos!
