### ISSUE TITLE
Entrega de credenciales

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#658]
Si entendí bien, deberíamos:

1) Crear una cuenta de Google para esta tarea
2) Obtener credenciales y descargar un 'client_secrets.json' como le llaman en [Code Examples](https://developers.google.com/youtube/v3/code_samples/python)
3) Permitir conexión para generar un 'archivo.py-oauth2.json' con el cual ya no es necesario permitir conexión en el browser (ver #656).
4) Adjuntar en la entrega todos estos archivos para que puedan ejecutar el programa.
5) Adjuntar nuestro usuario y contraseña creados en 1 para que puedan comprobar resultados.

Hasta el punto 3 he hecho todo y me funciona. En #656, si no mal entiendo, dicen que es necesario hacer esta confirmación vía interfaz, pero entiendo que esta confirmación no es necesaria si existe el archivo especificado, ¿cierto?
¿Son 4 y 5 suficientes para que el programa se pueda correr en cualquier computador y observar los resultados?
Entiendo que lo que pretenden es iniciar sesión con nuestra cuenta en un browser de manera normal al momento de comprobar los resultados que tengan que ver con la cuenta, como una modificación en una lista de reproducción.

EDIT 1: si 'archivo.py-oauth2.json' no existe y no tengo ninguna sesión de Google abierta en mi browser, me hace abrir una y confirmar, y el programa queda conectado a la cuenta que abrí. Estoy entendiendo entonces que la idea es que con un usuario y contraseña de Google ingresado por la interfaz se haga este proceso por interno. Pero iniciar sesión en Google no tiene que ver con la API de YouTube, ¿o si? No entiendo cómo proceder porque la confirmación y la creación de un 'archivo.py-oauth2.json' ocurre automáticamente.

EDIT 2: Acabo de encontrar de dónde sale el nombre de tipo 'archivo.py-oauth2.json' en mi programa. Independiente del nombre, hay un archivo que se necesita que no es igual al descargado al hacer una ID de cliente de OAuth 2.0, y que se crea automáticamente cuando confirmo en el browser (3). No entiendo cómo crear esto ingresando por la interfaz.

Perdonen los edits pero pasan las horas y los problemas no se resuelven pero voy descubriendo cosas...

Gracias.

**Comment by sebacruzd** [comment]
Tu punto 3 según lo que tengo entendido, está mal. Ese permiso se debe aceptar en nuestra interfaz gráfica, no debe estar hecho con anterioridad. @jgmontoya es así lo que digo?

**Comment by cjgazali** [comment]
@sebacruzd leer EDIT 1, perdona el desorden

**Comment by sebacruzd** [comment]
@cjgazali no soy ayudante jajaja, por eso pedí a @jgmontoya que confirmara, ya que él es quien me respondió en el issue #656. 

Lo que dices en el edit 1 según yo está bien. Yo tampoco sé cómo hacerlo desde la interfaz aún, pero tengo la tincada de que es con [esto](http://doc.qt.io/qt-4.8/qwebview.html). Estoy avanzando en otra parte ahora, eso lo leí a la rápida.
