### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by kcsss** [IIC2233-2016-02/Syllabus#66]
¿Cuándo revisen la tarea cuanto modificarán los archivos?. Por ejemplo utilizarán información incompleta para ver si nuestro programa se cae (eliminando programones de los archivos .json o cosas por el estilo) o debemos asumir que a la hora de la corrección todos los archivos estarán completos. 
Además, puedo asumir que el mapa no cambiará ?

Saludos.

**Comment by flobarrios** [comment]
Hola! respecto a lo primero ya lo han preguntado varias veces: #28, #64. Respecto al mapa, no puedes asumir que no cambiará (la imagen del enunciado hacer referencia al archivo json subido de las rutas, pero este puede cambiar). Debes cargar todos los datos a partir de los archivos .json.

**Comment by abannura** [comment]
Respecto a la ultimo, el mapa puede cambiar en cuanto a las ciudades y el orden en que aparece, pero una ruta siempre tendra tres "espacios" o no??

**Comment by nivek0o0** [comment]
Hola
El mapa puede cambiar, pero siempre habrán 3 cuadros de hierba entre las ciudades, ¿cierto?
Ya que el enunciado dice que se debe seleccionar la opción caminar 4 veces.

**Comment by andresbannuraschultz** [comment]
En que sentido puede cambiar el mapa? Siempre existira Pallet Town y sera el lugar inicial o no?

**Comment by flobarrios** [comment]
Sí, Pallet town siempre será la ciudad inicial. Puede cambiar el nombre de las ciudades, cantidad de ciudades, nivel de los programones que se encuentran en la ruta de una ciudad y otra, etc. Lo que no cambia es la cantidad de cuadros de hierba que hay entre ciudad y ciudad (3) y que Pallet Town siempre es la primera. Saludos!

**Comment by lefischer** [comment]
hola, se supone que las ciudades tienen in id propio segun el enunciado, pero en ningun archivo json se hace rferencia este id, se supone que lo creamos nosotros?

**Comment by flobarrios** [comment]
@lefischer si te fijas en gyms.json, esta el atributo city y el atributo id, ese id corresponde al de la ciudad. Saludos!

**Comment by rolfskog** [comment]
Hola, podemos asumir que el numero del route siempre estará en el orden de como se debe avanzar? Por ejemplo siempre sera que debemos partir en el 1 y después viene el 2, 3 etc.

**Comment by flobarrios** [comment]
Hola! @rolfskog si, pueden asumir eso 😄

**Comment by kcsss** [comment]
Con respecto a las ciudades, ¿el orden está bien ?. Según el enunciado, el primer líder es Giovanni con pokemones en nivel 40. 
Para el juego voy a dejarlo en este orden:
Pewter -> Cerulean -> Vermillion -> Celadon -> Fuchsia -> Saffron -> Cinnabar ->Viridian
Si pueden subir la versión final se los agradecería.

XoXo.

**Comment by jgmontoya** [comment]
@kcsss Leíste la respuesta de @flobarrios cierto?

El orden se especifica en el archivo json correspondiente y tu programa deberá cargarlo de ahí.
