### ISSUE TITLE
Qué tan precisa debe ser la búsqueda?

### ISSUE THREAD

**Issue by asimonv** [IIC2233-2016-02/Syllabus#660]
Por ejemplo pueden haber distintos videos para una canción, etc. Pueden haber errores en la lista de reproducción?

**Comment by cjgazali** [comment]
Yo me preguntaba cómo escoger un video apropiado para una búsqueda sin ver los videos, que es lo que uno hace normalmente, porque seguro hay muchos resultados. Incluso si una canción no está en YouTube, igual habrán resultados de búsqueda que pueden ser cualquier cosa.

**Comment by flobarrios** [comment]
Hola! la idea es que traten de reducir el error pero obviamente puede ocurrir que un video se llame igual a la canción y su contenido sea distinto (eso ya escapa de su manejo y no es lo que estamos evaluando). Al hacer el request, les recomiendo utilizar el primer video que hizo "match" con la canción.

Saludos!
