### ISSUE TITLE
Permanencia de las listas de reproducción

### ISSUE THREAD

**Issue by cameneses** [IIC2233-2016-02/Syllabus#661]
Tengo una duda respecto a la permanencia de las listas de reproducción en ejecuciones distintas del programa. Si durante una primera ejecución se creó una lista en el canal, al momento de ejecutar nuevamente el programa ¿esta lista deberá aparecer como que ya está creada? o bien ¿será necesario que el usuario vuelva a hacer el proceso de seleccionar esta lista para crearla en el canal?

**Comment by flobarrios** [comment]
Hola! deberían mantenerse entre sesiones. Saludos!

**Comment by jatrijori** [comment]
¿Hay alguna manera de entrar a las listas de reproducción de una cuenta para ver si ya crearon la lista o puedo guardar en un json los usernames de las personas que entren a mi aplicación con las listas que ya crearon?
