### ISSUE TITLE
Duda basica

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#662]
Desde cualquier usuario de youtube puedo conectarme al programa que estoy haciendo o no? En el fondo el client_id y el client_secret son del que hace la "aplicacion" pero en esta cualquier usuario normal se puede meter. O estoy cachando nada?

**Comment by flobarrios** [comment]
Hola! no, la idea es que solo el que tiene acceso a modificar la aplicación se pueda logear. Saludos!

**Comment by andresbannuraschultz** [comment]
Mmm entonces tengo mas dudas jaja. Yo creia que en la interfaz que tenemos que crear yo le iba a pedir al usuario ingresar un username + password de youtube. Esto no funcionaria entonces si la API que estoy usando "esta a nombre" de otro usuario? Para que entonces tenemos que pedir usuario + contrasenha si solo se puede conectar el usuario que pidio la authenticaiton de la API. O estoy entendiendo mal como funciona la cosa. Gracias!!

**Comment by sebacruzd** [comment]
Lo que yo entendí (a prueba y error) es que con una API y cliente+secreto OAuth2 puedes acceder o modificar los datos de cualquier cuenta google, youtube en este caso.

Me di cuenta porque tenía logeada mi cuenta UC y le agregó una playlist a esa cuenta en youtube, siendo que mi OAuth2 era de la cuenta que cree para la tarea, pero el permiso (lo que genera los tokens) fue concedido desde la cuenta UC.

**Comment by andresbannuraschultz** [comment]
Claro perfect! Esa era mi duda, entonces en el la interfaz tenemos que pedir los datos de la cuenta a cambiar me imagino.

**Comment by srvasquez** [comment]
A mi me pasa que con la cuenta uc me tira un error de autorización pero con mi cuenta personal si funciona aunque tampoco sea la cuenta que registro la API.

**Comment by andresbannuraschultz** [comment]
Me esta tirando este error:
googleapiclient.errors.HttpError: <HttpError 401 when requesting https://www.googleapis.com/youtube/v3/playlists?part=snippet%2Cstatus&alt=json returned "Unauthorized">
Y no lo he podido solucionar. Se supone que es porque no tengo habilitada la api pero estoy casi seguro que si la tengo habilitada. Porfa ayuda, llevo demasiado rato pegado

**Comment by ttapia** [comment]
@abannura a mí me tiro ese error y era porque no había creado un canal de youtube (tenía la cuenta de google creada pero no habia entrado a youtube), ojalá te sirva

**Comment by andresbannuraschultz** [comment]
@ttapia Buenisimo, eso era! No estay cachando como te lo agradezco llevaba pegado demasiado rato.
