### ISSUE TITLE
Lista de canciones para lista de reproducción

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#663]
¿La única forma que nuestra interfaz ofrece para crear una lista de reproducción de YouTube es seleccionando de `listas de reproduccion.json` o se puede crear una lista vacía y agregar canciones de a una (mientras se encuentren en YouTube)?

Para el bonus de Spotify, ¿la idea es implementar un buscador de listas? Para que el usuario pueda elegir...

**Comment by flobarrios** [comment]
Hola! nosotros solo estamos evaluando lo primero. Si quieres agregar más funcionalidades allá tu ! Respecto al bonus, queda a tu criterio como lo haces (buscador de listas o un set de listas por default de donde el usuario pueda escoger). La única restricción es que estas listas las debes obtener con la API. 
Saludos!!

**Comment by cjgazali** [comment]
Perfecto gracias!
