### ISSUE TITLE
Duda sobre estadísticas

### ISSUE THREAD

**Issue by sebacruzd** [IIC2233-2016-02/Syllabus#664]
Estoy haciendo las estadísticas y me surgió una duda.

Al agregar canciones a una lista de reproducción estoy encontrando el id de cada video con requests para luego agregar ese id a una lista de reproducción ya creada.

Después para ver las estadísticas de una lista de reproducción debo usar el id de esos mismos videos, o sea, los mismos ids que ya encontré anteriormente.

Podría guardar en un archivo aparte por ejemplo un diccionario con "ListaReproduccion_x":[id1, id2, ..., id_n]
para cada lista de reproducción, para no tener que volver a hacer esos requests y volver a encontrar los id de los videos? Los requests a cada video son demorosos y con esto podría hacer el proceso a la mitad del tiempo.

Gracias.

**Comment by FernandoPieressa** [comment]
Hola! No hay problemas en que uses ese metodo mientras persista entre sesiones.

Saludos!

**Comment by sebacruzd** [comment]
Gracias!
