### ISSUE TITLE
Aclaraciones Autentifación!!!

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233-2016-02/Syllabus#665]
Antes las dudas sobre el modo de autentificar queremos aclarar que con sus keys de Oauth2, cualquier usuario que ejecute su código  se le abrirá una ventana para aceptar el uso de la Api con la cuenta de google que este logueado y al momento de aceptar, su código podrá alterar la cuenta de youtube según lo que programaron.

Por otro lado se decidió como cuerpo de ayudantes que para priorizar otras cosas de la tarea, el manejo de la ventana que pide aceptar el uso de la API desde su interfaz queda como bonus de 0.3 puntos. 

Saludos!!

**Comment by andresbannuraschultz** [comment]
Gracias por las aclaraciones pero todavia me quedan dudas sobre como debe funcionar nuestra interfaz. Primero debo dar la opcion de hacer login? Pedirle un usuario y contrasena, de alguna manera intentar, a traves de la API, hacer el login que el usuario haria normalmente en un navegador. Despues si el login resulta existoso debo preguntarle al usuario si quiere aceptar el uso de la API. Asi es ? Alguna pista de como hacer login a traves de la API, no he podido encontrar nada util. Muchas gracias

**Comment by cjgazali** [comment]
Entonces, ¿el comportamiento del código en #666 es correcto (sin bonus)?
¿Se espera que el usuario inicie su sesión de YouTube en el browser?

**Comment by andresbannuraschultz** [comment]
Entonces el login no se hace en la interfaz propia si no que en el navegador? Al igual que la parte de aceptar el uso de la API?

**Comment by jgmontoya** [comment]
Hola!

El comportamiento esperado (sin bonus) es el siguiente:
  - Un usuario ejecuta su aplicación
  - Se abre la ventana en el browser desde donde el usuario puede, ingresando con su cuenta, dar permisos a la aplicación
  - El usuario puede ocupar el programa (las playlists se harán en su cuenta, los comentarios a su nombre, etc..)

Ojo que si se cierra el programa y luego se vuelve a abrir debe existir la opción de entrar con un usuario distinto. Lo ideal sería que manejaran el caso de un usuario que ya utilizó su programa no necesite volver a otorgar permisos pero no es taan importante.

En la práctica entonces hay dos archivos, uno que contiene la información de acceso a la api (que deben generar creando una aplicación desde su cuenta google) y otro que corresponderá a las credenciales del usuario (que se debiera generar cuando desde el browser se otorgan los permisos).

Para el bonus se espera que manejen todo desde su aplicación sin la necesidad de que se abra un browser externo para realizar todo esto. No podemos darles pistas de como hacerlo (por algo es bonus) pero es posible que deban desviarse un poco de los ejemplos para lograrlo.

Saludos!

**Comment by srvasquez** [comment]
Me surge una duda, si el login se hace a traves del browser, como diferenciar sesiones de usuario de la API, para así guardar las playlist creadas en la sesion.

**Comment by gebalassa** [comment]
> "En la práctica entonces hay dos archivos, uno que contiene la información de acceso a la api (que deben generar creando una aplicación desde su cuenta google) y otro que corresponderá a las credenciales del usuario (que se debiera generar cuando desde el browser se otorgan los permisos)."

1) ¿A qué te refieres con crear una aplicación desde la cuenta Google? 
2) ¿Por qué se debe crear un archivo para las credenciales del usuario? ¿Esto no elimina la privacidad de la contraseña? ¿La API usa esta contraseña cuando accede a hacer los cambios, o usa una especie de "permiso especial" cuando se le entregan los permisos?
3) ¿Por archivos separados te refieres a dos módulos, o a un archivo en Python y las credenciales en un .txt?

**Comment by Jaluco** [comment]
Una duda sobre esto, tengo un pequeño trozo de código que le da like a un video (nada de la tarea pero lo estoy usando para realizar pruebas). Mi problema es que si ingreso en el browser a otra cuenta distinta no sucede lo que dicen, no se piden permisos ni se da like al video en cuestion.

**Comment by jgmontoya** [comment]
@srvasquez Puedes usar la API para obtener el nombre del canal de youtube.

@Jaluco ¿Eso te ocurre aun cuando se modifica el json de las credenciales? Fíjate que no estés usando siempre el mismo archivo

**Comment by srvasquez** [comment]
@jgmontoya gracias, entonces para cambiar de usuario habría que hacerlo con el nombre del canal de youtube (sin bonus)??

**Comment by jgmontoya** [comment]
Para cambiar el usuario basta con cambiar (borrar o renombrar) el archivo que tiene la autenticación de este, así al intentar autenticarse volverá a abrir el browser. 

Si está el archivo entonces lo ocupará para loguearse sin abrir el browser.

**Comment by aaossa** [comment]
@cjgazali #653

**Comment by cjgazali** [comment]
Perdooon lo tengo clarísimo pero vi mal

**Comment by aaossa** [comment]
Iba a que ya permitían ocuparlo

![image](https://cloud.githubusercontent.com/assets/10425834/20610518/bb75322e-b279-11e6-9a4f-ada201450866.png)

**Comment by cjgazali** [comment]
Dale apaño eliminar silenciosamente todos estos comentarios... gracias @aaossa
