### ISSUE TITLE
Entrega de credenciales

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#666]
Esto viene de #658 pero me quedó un desorden así que la cerré.
Si entendí bien, deberíamos:

1) Crear una cuenta de Google para esta tarea
2) Obtener credenciales y descargar un 'client_secrets.json' (como le llaman en [Code Examples](https://developers.google.com/youtube/v3/code_samples/python)) al momento de hacer una ID de cliente de OAuth 2.0.
3) Iniciar sesión ingresando usuario y contraseña de Google en la interfaz, y permitir que el programa administre la cuenta (#656), sin que jamás se abra un browser solicitando lo anterior.
4) Adjuntar en la entrega 'client_secrets.json' para que puedan ejecutar el programa.
5) Adjuntar nuestro usuario y contraseña creados en 1 para que puedan comprobar resultados.
¿Correcto?

Lo que menos entiendo es el punto 3.  Iniciar sesión en Google no tiene que ver con la API de YouTube, ¿o si? ¿Cuál es la forma? He encontrado muchas cosas en internet, entre ellas soluciones con gdata.youtube (prohibida).

El siguiente código abre el browser para permitir y genera un archivo en el llamado a `run_flow(flow, storage)` si es que no existe previamente.
```
flow = flow_from_clientsecrets(CLIENT_SECRETS_FILE, scope=YOUTUBE_SCOPE,
                                   message=MISSING_CLIENT_SECRETS_MESSAGE)

storage = Storage("%s-oauth2.json" % sys.argv[0])
credentials = storage.get()
    
if credentials is None or credentials.invalid:
    credentials = run_flow(flow, storage)
    
youtube = build(YOUTUBE_API_SERVICE_NAME, YOUTUBE_API_VERSION,
                          http=credentials.authorize(httplib2.Http()))
```
Una vez creado el archivo con información (tokens y otros) que no sé cómo obtener de otra manera, este mismo código carga esa información sin ejecutar `run_flow`. ¿Debería verse así la solución? ¿Cómo obtener tokens y otros de otra manera? Estoy en blanco en este sentido.

Gracias.

**Comment by sebacruzd** [comment]
Yo tampoco entiendo cómo hacer el punto 3, por favor algún ayudante explicar un poco más detallado que las otras respuestas (de los issues referenciados) si es posible 😞. He buscado por mucho tiempo y no encuentro cómo hacerlo.
