### ISSUE TITLE
[Tarea7] Duda archivo json

### ISSUE THREAD

**Issue by roy350** [IIC2233-2016-02/Syllabus#667]
Hola, disculpen pero yo puedo ya agregar videos cualquiera a una lista de reproduccion que creo pero mi problema es que de los datos que nos dieron no se cual es el id de cada cancion por ejemplo en el archivo la cancion "Love my life" tiene un id de "5iJzuuTd5Fl2uosN4WG5I4" y quiero saber que significa este id por que al tratar de correrlo por youtube poniendo el link https://www.youtube.com/watch?v=5iJzuuTd5Fl2uosN4WG5I4 y no existe, muchas gracias por la ayuda!

**Comment by stephichau** [comment]
Hola @roy350! 

Ese id es el identificador de la canción en spotify. 

Saludos!
