### ISSUE TITLE
Duda playlists

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2233-2016-02/Syllabus#668]
Tengo una duda respecto a cuando tenemos que hacer las playlists. En la interfaz tiene que haber una "caja" en donde el usuario pueda escribir el nombre de la playlist a agregar??? Por ejemplo que escriba "top 50 usa". Al hacer esto tengo que ver si existe la playlist en el json y si existe agregarla.

O bien tengo que hacer varios botones donde el usuario eliga que playlist quiere añadir?
Gracias!!

**Comment by flobarrios** [comment]
Hola! Lo segundo. Saludos!
