### ISSUE TITLE
Otra duda playlists

### ISSUE THREAD

**Issue by sebacruzd** [IIC2233-2016-02/Syllabus#669]
Hola,

Al darle las opciones de playlists al usuario (sé que tienen que ser las del archivo), tengo que hacer mi código para un caso genérico donde la cantidad de listas es variable, o puedo asumir que siempre habrán 10 listas, como en el archivo que nos dieron?

Esto es porque planeo usar unos botones para mostrar cada lista y luego elegirla.
En caso de que sea variable la cantidad de listas haría un QListWidget, pero no sé cómo hacer que cada item del widget sea una especie de QPushButton o actúe como tal 🤔.

Gracias.

**Comment by FernandoPieressa** [comment]
Hola!

No puedes asumir que siempre habrán 10 listas, te recomiendo que cambies un poco la idea de los botones por la misma razón que dijiste, hay varias formas de resolver tu problema en cuanto interfaz ;)

Saludos!

**Comment by sebacruzd** [comment]
Gracias!
Alguna recomendación o tip para esas varias formas?
La única que se me ocurre es QListWidget, pero en la tarea pasada no logré que cada item funcionara como un botón distinto 😞 

En verdad otra forma mas fea es mostrar todas las listas y hacer que escriba la que quiere, es válido esto?

**Comment by cameneses** [comment]
QListWidget tiene el médodo `currentItem()` que devuelve el item que está seleccionado! Quizás eso te pueda servir

**Comment by sebacruzd** [comment]
@cameneses gracias!
