### ISSUE TITLE
Problemas con Github pull

### ISSUE THREAD

**Issue by asimonv** [IIC2233-2016-02/Syllabus#67]
<img width="732" alt="screen shot 2016-08-16 at 4 59 37 pm" src="https://cloud.githubusercontent.com/assets/7036160/17737276/c2cca83c-6462-11e6-837a-c6a841ba62a0.png">

Qué puedo hacer? :-/

**Comment by aaossa** [comment]
Intentaste alguna de las soluciones que aparecen googleando el error?

**Comment by asimonv** [comment]
Sí, pero no entiendo cómo resolverlo y no quiero echar a perder algo del Syllabus.

**Comment by ivaniadg** [comment]
Hola,

Como eres alumno no tienes permisos para modificar el syllabus que está en GitHub.com, así que cualquier cosa que hagas en la carpeta que tienes en tu computador **solo se verá en tu computador**. El mensaje te está diciendo que modificaste archivos,  no has hecho _commit_ y por lo tanto no puedes hacer _pull_. 

#### ¿Cómo resolverlo?

No tienes permisos para hacer _commit_, así que lo razonable es copiar los archivos que hayas modificado en alguna carpeta y después hacer `git reset --hard HEAD`. Luego de esto podrás hacer _pull_ sin problemas.

**Comment by asimonv** [comment]
Muchas gracias!
