### ISSUE TITLE
[tarea 7] Duda sobre citar

### ISSUE THREAD

**Issue by roy350** [IIC2233-2016-02/Syllabus#670]
Hola dentro de todas las investigaciones y ejemplos que he visto queria saber que tan importante es el tema de citar por que siento que muchos tendremos codigos similares debido a las funcionalidades de las API pues muchos codigos de los links base que nos enviaron eran utiles mas otros encontrados dentro de la API como stackoverflow asi que queria saber eso, muchas gracias!!

**Comment by aaossa** [comment]
Podrías basarte en #639 colocando como comentario la página de la cual tomaste el ejemplo. Cuando los ejemplos son simples no se citan, pero si vas a tomar algo más grande agradeceríamos que colocaras la página :grin:
