### ISSUE TITLE
Cuenta Suspendida

### ISSUE THREAD

**Issue by alainrochette** [IIC2233-2016-02/Syllabus#671]
Esto me pasó a al crear todos los playlists de la lista_de_reproducciones en youtube. Es normal que pase esto? Debería seguir haciendo cuentas y que me sigan suspendiendo, o hay algo que debería hacer distinto?

<img width="817" alt="screen shot 2016-11-23 at 10 43 27 am" src="https://cloud.githubusercontent.com/assets/10841635/20563987/ab77beb6-b169-11e6-9df7-3f06582c8c2f.png">

**Comment by aaossa** [comment]
Cuantas creaste?? :scream:

**Comment by ndleyton** [comment]
En teoría con hacer 100 inserciones ya se agotan la cuotas de la API,o no?

**Comment by gabrielpinkman** [comment]
A mi me pasó lo mismo, cuando intento crear todas las listas de reproducciones me dice que agoté la cuota de la API, qué puedo hacer? puedo poner los nombres de las listas en mi interfaz y cargarlas solo cuando se presionen?

**Comment by ndleyton** [comment]
Eso dice el enunciado que uno debe hacer

**Comment by flobarrios** [comment]
@gabrielpinkman no debes crear todas las playlists al inicializar la interfaz. Debes irlas creando a medida que el usuario escoja crearlas.

**Comment by gabrielpinkman** [comment]
Ok, me queda más claro el enunciado. Por otro lado, es necesario mostrar las canciones que tiene la lista antes de crearlas?

**Comment by Nebula2028** [comment]
Una pregunta (quizás un poco tonta)... Sirve de algo si ponemos algunos time.sleep de unos 2 o 3 segundos entre cada operacion tipo GET o POST para asi evitar sobre cargar el servidor?? (en otras palabras, el limite es solo un total de solicitudes máximas totales? o por dia? o por hora? No hay problema con hacer muchas solicitudes por segundo? Algo como que el server se vaya a pasar el rollo que es un ataque DDoS o algo asi cuando en verdad es solo un programador noob? xD)

**Comment by jgmontoya** [comment]
@Nebula2028 Tu pregunta no es tonta!

Puedes ver [en la documentación](https://developers.google.com/youtube/v3/getting-started#quota) cómo funciona el límite en esta api en particular.
