### ISSUE TITLE
Duda sobre comentar

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#672]
En en el enunciado no queda claro si es que los comentarios deben ser sobre videos de playlists ya creadas o si tambien debo dar la opcion de que a partir de una playlist "original", yo busque una de sus canciones, y comente el video correspondiente. Sin haber agregado esa playlist. Gracias

**Comment by flobarrios** [comment]
Hola! Lo primero. Saludos 😊

**Comment by andresbannuraschultz** [comment]
Flo porfa ayudanos con la duda sobre el login! Creo que somos varios atascados ahi. Se supone que cualquier usuario con una youtube/google puede usar nuestro programa. En otras palabras, cualquier usuario google puede usar la API a traves de mi credencial. El problema es que realmente no he podido encontrar en google como hacer login de una cuenta distinta a la del client que tiene la credencial para la API. Lo unico parecido que he notado es que cuando no hay ninguna cuenta loggeada, y pido autentificacion, antes de redirigirme a la pagina para aceptar el uso de la API me hace ingresar con algun usuario google. Como puedo hacer esto desde la interfaz? Para empezar, se puede? Los ejemplos quehe visto ocupan la libreria gdata. Como tiene que ser todo este tema del login? Porfavor ayuda!! 
Muchas gracias por contestar la otra duda. Saludos.

**Comment by flobarrios** [comment]
@abannura lo estoy viendo ahora y a penas tenga una respuesta definitiva se las doy. Mientras traten de avanzar con las funcionalidades!
