### ISSUE TITLE
Comentarios desactivados

### ISSUE THREAD

**Issue by rolfskog** [IIC2233-2016-02/Syllabus#673]
Hola, 
Haciendo la parte de las estadisticas me di cuenta que en algunos videos estan desactivados los comentarios, generando errores ya que no me da el commentCount cuando lo pido. Que hacemos en este caso, ignoramos el video con un exception o le asignamos 0. Paralelamente cuando se intenta comentar uno de estos videos retorna un error de que no hay autorizacion para comentar.

**Comment by flobarrios** [comment]
Hola! ese video no entraría en el ranking ya que no es posible comentarlo. Ambos casos manéjalos con una excepción!

**Comment by roy350** [comment]
pero si yo les asigne 0 a los videos para que entraran al ranking? es que ya termine esa parte :(

**Comment by jgmontoya** [comment]
@roy350 Puedes dejarlo con 0 para efectos del ranking.

**Comment by roy350** [comment]
@jgmontoya muchas gracias javier! me ayuda demasiado eso!!! :)
