### ISSUE TITLE
Problema en la busqueda

### ISSUE THREAD

**Issue by srvasquez** [IIC2233-2016-02/Syllabus#674]
Hola, tengo un pequeño problema con las búsquedas, en la playlist Old School Reggeaton del archivo, hay una canción que no me arroja ningún resultado `zion - sere yo158`, mi pregunta es, se espera también reducir el error de las playlist de la base de datos ? 
PD: el error es el que el nombre de la canción contiene ese 158 si lo busco sin esa parte me da buen resultado, pensé en quitar de los nombres números pero tendría un impacto negativo en la playlist por ejemplo con Calle 13 que si arroja buen resultado.

**Comment by flobarrios** [comment]
Hola! se espera que al menos tengas una segunda búsqueda en caso de no dar con la canción. Una recomendación podría ser que **si no se encuentra un video**, filtres los números (así no estarías perdiendo las canciones de calle 13). Saludos!
