### ISSUE TITLE
Videos protegidos

### ISSUE THREAD

**Issue by cameneses** [IIC2233-2016-02/Syllabus#675]
Me pasa que muchos videos (si no es todos) están protegidos por VEVO, WMG o alguna otra plataforma de videos musicales y en consecuencia no puedo reproducirlos en la interfaz, obteniendo algo como esto

![alt text](https://i.gyazo.com/0ac511f40260e91549ef56d82f9d3d2f.png "Videos Protegidos")

Respecto a esto tengo la duda de si influirá esto en la parte del bonus de mostrar los videos en la interfaz y en caso de que sí ¿cómo es que podríamos obtener un video que no presentara estos problemas?, pues, todos los filtros para el orden de una búsqueda terminarán llevando a videos con estas restricciones, ya que generalmente son los más vistos, con más likes, los más relevantes para la búsqueda, etc.

**Comment by FernandoPieressa** [comment]
Hola!

Esos tipos de video estan hechos especialmente para que no puedan ser reproducidos mediante APIs y por lo tanto la gente que quiera verlos tenga que estar obligatoriamente en youtube.

Por lo tanto, ese tipo de videos dejalos con ese mensaje de restriccion, porque de todas maneras en tu sistema tambien se mostrara el peor video, asique igual podremos ver si funciona correctamente tu programa.

Saludos!

**Comment by cameneses** [comment]
Muchas gracias por la aclaración!! Sin embargo, no me queda claro eso de _en tu sistema tambien se mostrara el peor video_, tenía entendido que teníamos que agregar a la lista un video (por cada canción) y reproducir ese en la interfaz, por lo que no me queda claro a qué te refieres con lo del _peor video_.

**Comment by FernandoPieressa** [comment]
Es que hablas de que solo buscas el mejor video y que este la mayoría de las veces tendrá problemas por ser de alguna plataforma musical, pero como también tienen que encontrar el peor video de su lista, ese probablemente funcione sin problemas. Sin embargo lo que dices es correcto, al elegir una canción de la lista se muestra el video en la interfaz, asique no te preocupes.

Saludos!

**Comment by cameneses** [comment]
Muchísimas gracias por la aclaración!!
