### ISSUE TITLE
duda ejemplos youtube api

### ISSUE THREAD

**Issue by smargozzini** [IIC2233-2016-02/Syllabus#676]
hola!
en la pagina de la api de youtube se dan muchos ejemplos con los códigos ya hechos y muchos de ellos nos sirven para la tarea, mi pregunta es si podemos usar estos ejemplos tal cual aparecen ahí o debemos entenderlos y escribirlos con nuestro propio codigo?
gracias de antemano

**Comment by aaossa** [comment]
Nunca se debe usar código que no sepas lo que hace. Te recomiendo leerlo bien, entenderlo y luego escribir lo que necesites utilizar

**Comment by aiquinones** [comment]
Y si lo leí mil veces hasta entenderlo, y le hice modificaciones muy pequeñas para que funcione con mi código, esta bien también?
