### ISSUE TITLE
Duda sobre comentarios

### ISSUE THREAD

**Issue by cameneses** [IIC2233-2016-02/Syllabus#677]
Para comentar un video estoy guiándome con esta parte de la documentación [https://developers.google.com/youtube/v3/docs/commentThreads/](url), sin embargo hay algo que no logro entender bien y es que si con `snippet.channelId` se refieren al id del canal que realizará el comentario o bien a otro parámetro.

Estoy intentando la implementación de esto en mi tarea y no logro hacerlo porque recibo un error dando a conocer que no tengo los permisos suficientes. Sin embargo no logro entender qué es lo que estoy haciendo mal. Si hay alguien que pueda echarle una ojeada a mi código lo agradecería muchísimo :(, esto se encuentra en la línea 41 de videos.py

**Comment by aaossa** [comment]
Por lo que entendí de la documentación se refiere al canal al que pertenece el video. También puedes probar con comentarios distintos para revisar si en un mismo video te da el mismo id (lo digo porque hacer eso es nas rápido que preguntar :grin: )

**Comment by fhgajardo** [comment]
Tengo el mismo problema al comentar los vídeos, me dice que no tengo los permisos suficientes (Al revisar las credenciales me dice que tengo las credenciales necesarias)

Saludos y gracias de antemano

**Comment by sebacruzd** [comment]
Yo logré comentar sin usar el channelId, uso solo el id del video.

Hay que modificar bastante ese código para que funcione, al menos de la manera que lo hice yo.
Intenta modificar la parte de los args que se crean y los que le das.

También los métodos que revisan comentarios y eso no los necesitas, algunos de esos tiraban error y al sacarlos te ahorras harto debugging.

**Comment by jgmontoya** [comment]
Todo lo que están preguntando acá tiene su respuesta en la documentación.

Cito a un gran profe:

> * primero, que no preguntes "[tengo este error…] ¿Qué hago?", pues suena a que te enfrentas a un problema y dependes de que alguien te de instrucciones para resolverlo; esa no es una actitud deseable.
> * segundo, que siempre que tengas un error en una aplicación, luego obviamente de buscar en Google y tratar de resolverlo por ustedes mismos, cuando preguntes en algún foro siempre incluyas cuál es el error que estás viendo. Muchas veces no basta con una descripción de lo que hiciste y con la línea en donde se te muestra que tienes un error (de hecho, cuando los errores se gatillan en el template, muchas veces no tienen que ver con el template en sí). 
> 
>Raúl Montes

**Comment by fhgajardo** [comment]
Estimado @jgmontoya no entiendo la finalidad de tu comentario

**Comment by jgmontoya** [comment]
Tiene la finalidad de que primero intenten por su cuenta buscar la solución a los problemas que les surgen y también que lean la documentación en vez de simplemente copiar el código de ejemplo sin entenderlo.

Además de esto tiene la finalidad de que aprendan a preguntar mejor, decir "tengo un error en la linea X alguien me lo puede revisar" **no** es la forma adecuada de preguntar.

**Comment by fhgajardo** [comment]
Te informo que si he buscado y leído reiteradas veces la documentación y que no utilice el ejemplo para realizar esta parte de la actividad, pero lamentablemente tenia el mismo error de mi compañero. Solo buscaba en mi comentario que no cerrara la issue, ya que podían entregar información relevante para mi trabajo

**Comment by fhgajardo** [comment]
Creo que la forma de decirlo tampoco fue la mas correcta

**Comment by sormazabal** [comment]
Tengo una duda similar:
Cuando trato de insertar un commentario desde Python me tira el error de autentificación:

> Traceback (most recent call last):
  File "C:/Users/socre/T7Web/Main1.py", line 203, in <module>
    insert_comment(added_vid, "I love it")
  File "C:/Users/socre/T7Web/Main1.py", line 190, in insert_comment
    "videoId": "v7YVEUhEW2w"
  File "C:\Anaconda3\lib\site-packages\oauth2client-4.0.0-py3.5.egg\oauth2client\_helpers.py", line 133, in positional_wrapper
  File "C:\Anaconda3\lib\site-packages\google_api_python_client-1.5.5-py3.5.egg\googleapiclient\http.py", line 838, in execute
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/youtube/v3/commentThreads?alt=json&part=snippet returned "Insufficient Permission">


Pero cuando lo hago desde la [API ](https://developers.google.com/apis-explorer/?hl=es#p/youtube/v3/youtube.commentThreads.insert?part=snippet&_h=6&resource=%257B%250A++%2522snippet%2522%253A+%250A++%257B%250A++++%2522topLevelComment%2522%253A+%250A++++%257B%250A++++++%2522snippet%2522%253A+%250A++++++%257B%250A++++++++%2522textOriginal%2522%253A+%2522I+love+it+%253C3%2522%252C%250A++++++++%2522videoId%2522%253A+%2522v7YVEUhEW2w%2522%250A++++++%257D%250A++++%257D%250A++%257D%250A%257D&) me funciona perfecto. 
![error1](https://cloud.githubusercontent.com/assets/7980453/20640476/fb020640-b3c5-11e6-9562-aa753482aba4.png)
![error2](https://cloud.githubusercontent.com/assets/7980453/20640477/fb030dce-b3c5-11e6-9b97-03d859bd9f1c.png)


He estado pegada varias horas con esto, por lo que me sería muy útil algún tipo de orientación :S

**Comment by aaossa** [comment]
@sormazabal dale una mirada a #695 , podría ser eso

**Comment by jgmontoya** [comment]
Revisa qué nivel de permisos necesitas para comentar videos y qué nivel de permisos estás solicitando con tu programa.

**Comment by sormazabal** [comment]
@aaossa Revisé eso y no era, ya que me deja crear playlists sin problema en el mismo archivo .py con el mismo client_secrets.json
@jgmontoya perdón por lo noob, pero cómo reviso el nivel de permisos que pide mi programa?

**Comment by jgmontoya** [comment]
@sormazabal  [Esto](https://developers.google.com/youtube/v3/guides/authentication) puede servirte
