### ISSUE TITLE
Problema Videos sin Comentarios

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2233-2016-02/Syllabus#678]
Hola, que hago cuando un video tiene los comentarios desactivados. Esto es para sacar estadisticas. Porque cuando corro el código me dice que no existe la key["commentCount"] y me tira error. 
Ej: https://www.youtube.com/watch?v=b4Bj7Zb-YD4
Para las estadisticas omito esta cancion o bien esta es la canciòn con menos comentarios??? 
Gracias!!

**Comment by aaossa** [comment]
Ese error lo puedes evitar fácilmente y capturar ese caso antes de que te produzca una excepción. Cómo manejar esto para el usuario queda a criterio de los tareos.  

**Hint:** `dict.get(key)`
