### ISSUE TITLE
Duda con argparse

### ISSUE THREAD

**Issue by Nebula2028** [IIC2233-2016-02/Syllabus#679]
argparser.add_argument("--q", help="Search term", default=palabra)
        argparser.add_argument("--max-results", help="Max results", default=max_results)
        args = argparser.parse_args()
        try:
            return self.mi_funcion_que_busca(args)

Esa es una porción pequeña del código que estoy utilizando . Hay algo que me ha tenido muchas horas pegado y no logro entender que sucede. Mi función para buscar funciona perfecto, le doy como parametros el string que quiero buscar y el num max de resultados y funciona perfecto.... PEEEERO, solo funciona una vez :S... la segunda vez que trato de usar mi funcion en la misma ejecución me tira un error en la primera linea que puse (argparser.add_argument("--q", help="Search term", default=palabra) .
El error es:
argparse.ArgumentError: argument --q: conflicting option string: --q

el parametro default=palabra es la palabra que estoy buscando.

Esta pusheado mi código, es el modulo "buscar_keyword.py" por si alguien puede revisarlo please!!!

**Comment by Nebula2028** [comment]
Ya lo solucioné, (tipico que uno pasa horas en algo y cuando lo postea en el foro lo soluciona altiro) pero lo solucioné dejando de usar argparser por completo.

Igual me gustaría saber por que sucede ese comportamiento (incluso trate de que mi funcion fuera el metodo de un objeto "Funciones", y al hacer una segunda busqueda elimino ese objeto e instancio uno nuevo, con la esperanza de que cualquier tipo de "memoria" que pueda haber tenido la funcion se pierda, pero aun asi tira el error y no funciona a la segunda)

**Comment by jgmontoya** [comment]
La razón de por qué pasa eso está en el mensaje de error:

> argparse.ArgumentError: argument --q: conflicting option string: --q

Lo que pasa es que con el primer llamado estás seteando la opción q con cierto valor por defecto (en tu caso una palabra para buscar) y luego estás volviendo a setear esa opción q, el comportamiento default es que se genera una excepción porque estás agregando dos acciones con el mismo 'option string' ("--q")

Saludos!

**Comment by Nebula2028** [comment]
Gracias por la respuesta! Me quedó claro.... aunque aun no se como se haría entonces (si quisiera/tuviera que ocupar argparse)

**Comment by jgmontoya** [comment]
Lo que pasa es que argparse está hecho para entregar argumentos mediante la linea de comandos, en ese caso es raro querer modificar en tiempo de ejecución la opción default.

Dicho esto, se puede hacer, [puedes leer cómo acá](https://docs.python.org/3/library/argparse.html#conflict-handler)

Saludos!

**Comment by Nebula2028** [comment]
Gracias de nuevo!

**Comment by Tibrahm** [comment]
Hola he tenido el mimo problema desde ayer en la tarde y revisado infinitamente google y la pagina que esta en esta issue para entender el problema y como solucionarlo pero aun no puedo, @Nebula2028  como lograste hacerlo ?

**Comment by Nebula2028** [comment]
No lo solucioné, simplemente no ocupe arg parser en absoluto.

Pasale a la funcion los argumentos q esta requiera sin todo esa "preparacion"  de argparser :) no se si te pueda ayudar mas

Saludos

**Comment by lampuerov** [comment]
Por si a alguien no le funciona, el parámetro 'q' que recibe la función youtube.search().list es el str que se quiere buscar en youtube (ej: q="cocorosie fairy paradise")
