### ISSUE TITLE
Videos de lista de reproducción

### ISSUE THREAD

**Issue by Snorlax8** [IIC2233-2016-02/Syllabus#680]
En la issue #667, dicen que el id que le corresponde a una canción en el archivo json entregado es su identificador en Spotify, no YouTube. Entonces, las canciones no se refieren a un video específico en YouTube, o me equivoco? Para una misma canción, siempre habrá más de un video que la reproduzca. Está bien elegir cualquiera o hay algo que estoy pasando por alto?

Espero su respuesta, muchas gracias! 
😄

**Comment by flobarrios** [comment]
Hola! Exactamente, dado el nombre de una canción tienes que buscar el video equivalente. Dado que pueden existir múltiples opciones, puedes elegir la que gustes. Saludos!

**Comment by Snorlax8** [comment]
Muchas gracias 🍰 !

**Comment by Tibrahm** [comment]
Entonces al momento que un usuario agrega una playlist a su canal tenemos que ir buscando los id correspondientes a todas las canciones que se encuentran en esa playlist del archivo json, escogiendo por ejemplo el id de la primer vídeo que encontró,  y luego agregar ese id a la playlist que se creara en el canal ?

**Comment by flobarrios** [comment]
@Tibrahm no te entendi muy bien pero la cosa es así: 

1) Usuario elige la playlist que desea crear
2) Se toma la info de la playlist del archivo json y por cada canción, en base a el/los **artistas** y **nombre** de esta (por ejemplo, ya que también podrías filtrar por album), buscas en youtube el video que haga "match" con estos parámetros.
3) Luego, ese video que hico match con el nombre de la canción lo agregas a la lista de reproducción de youtube.

_Nota: El id que aparece en el archivo json no tiene nada que ver con los id de los videos (es el id que les asigna spotify)._

Saludos!

**Comment by Tibrahm** [comment]
ya perfecto eso mismo era, gracias !!
