### ISSUE TITLE
Problema para reproducir video en qwebview

### ISSUE THREAD

**Issue by hanavarrete** [IIC2233-2016-02/Syllabus#681]
Hola! Tengo un problema, al intentar reproducir un vídeo de youtube en un qwebview logro poner el link del vídeo solamente, pero no me deja darle play ya que sale "La reproducción no es compatible con este dispositivo". Ya intenté activando los pluggins pero aún no logro nada. heeeelp

**Comment by NicolasAguirre** [comment]
Tengo el mismo problema!! Le active el ... + setAttribute(QWebSettings.PluginsEnabled,True) para poder ver flash pero me tira el mismo error. Porfa ayuda!!

**Comment by stephichau** [comment]
Hola @hanavarrete ! 
Que video estas intentando reproducir?  Hay muchos videos que tienen restricciones para su visualización en otros dispositivos fuera de YouTube dado los derechos de autor.

Saludos :)

**Comment by hanavarrete** [comment]
Me pasa con todos los videos que intentó reproducir. A menos que justo haya probado solo vídeos restringidos

**Comment by hanavarrete** [comment]
aló? :(

**Comment by sebacruzd** [comment]
A mi también me pasa, lo logré hacer con un video X pero no con los de la lista.

Puedo dejar un botón que abra directamente ese video para que vean que sí pude implementarlo, y en caso de que no se puedan reproducir los otros al intentar abrirlos, imprimir un mensaje que lo indique?

**Comment by flobarrios** [comment]
@sebacruzd si !! puedes hacer eso.

**Comment by hanavarrete** [comment]
@sebacruzd  me podrías mandar la url del video que si te funciona? para ver si es problema mío o efectivamente de los videos de la lista

**Comment by sebacruzd** [comment]
@hanavarrete con [este](https://www.youtube.com/watch?v=wuggc60TVzU) me funciona. (no es broma), en todo caso busca uno con pocas visitas y de un canal no famoso y te servirá.

Creo que todos los videos de todas las listas están prohibidos.
Como son canciones "populares", los artistas generalmente están en compañías disqueras como Vevo, Sony y otras. 
Todos esos canales tienen sus videos con derechos y están bien restringidos. (incluso hay países donde no se pueden ver)

Probé con muchos videos y me aburrí, no pude abrir ninguno de las listas.
Dejaré un botón para mostrar que sí puedo abrir videos, espero que sea suficiente.

**Comment by andresbannuraschultz** [comment]
@hanavarrete tengo el mismo problema, y tmpoco me funcionan los ejemplos que han subido, lo pudiste solucionar?

**Comment by ndleyton** [comment]
Hola, a mi no me funciona con el rickroll :/. Resulta que es un problema de codecs, ya que al parecer QWebKit en PyQt4 no viene con los codecs para video en HTML5.
Puden probar esto abriendo https://www.youtube.com/html5 en QWebKit, donde a mi me dice que no tengo ninguno de los codec.
Es por esto que todos los videos me dirán "La reproducción no es compatible con este dispositivo", sin embargo investigué y PyQt5 sí viene con estos codecs, pero supongo que no podemos usarlo, o si?

**Comment by Snorlax8** [comment]
Me sumo a las inquietudes, ni Rick Astley pudo salvarme 😞

**Comment by jgmontoya** [comment]
Se puede con PyQt4.

Saludos!

**Comment by asimonv** [comment]
@jgmontoya a onde jaja

**Comment by Nebula2028** [comment]
Algun tip de como hacerlo? No tiene nada que ver con QWebView? Para dejar de intentar hacerlo asi xD

**Comment by Nebula2028** [comment]
3:49, aun no logro reproducir ni a rick astley ni la cancion triste del alumno de programacion avanzada...

Es con QWebView y setHtml ? (asi me sigue saliendo que la reproduccion no es compatible con este dispositivo) 

O hay que usar la forma "oficial" que es eso del API de IFrame Embeds? (https://developers.google.com/youtube/iframe_api_reference?hl=es)

Una pista por favor !

**Comment by cameneses** [comment]
@Nebula2028 yo lo hice guiándome por [esto](http://stackoverflow.com/questions/15983148/the-sound-dont-stop-when-qwebview-window-closed-loaded-with-youtube-video) y me funcionó perfectamente. Espero que te sirva

**Comment by lefischer** [comment]
@cameneses yo me me guie en lo mismo que tu pero de todos modos me aparece  "La reproducción no es compatible con este dispositivo"

**Comment by Snorlax8** [comment]
Me pasa igual que a @lefischer  😕

**Comment by jatrijori** [comment]
Me uno al lloriqueo pq lo he intentado de varias maneras y sigue sin funcionar :'(

**Comment by jatrijori** [comment]
update: se me arregló por fin :o, cambié la línea que tenía como webview.settings().PluginsEnabled = True por webview.settings().setAttribute(QWebSettings.PluginsEnabled, True) y la webview la guardé dentro del constructor de la window

**Comment by Snorlax8** [comment]
@jatrijori a qué te refieres con que la guardaste dentro del constructor de la window? tengo esa misma línea y no me funciona 😕

**Comment by jatrijori** [comment]
@Snorlax8 en vez de hacer la webview en Qt Designer la cree primero en python, le puse lo de los settings de plugins, después guardé esa webview como atributo de la ventana y se la puse a una layout que tenía la ventana

**Comment by ndleyton** [comment]
Siempre lo he tenido como dices y no funciona jajajaj

**Comment by lefischer** [comment]
@ndleyton estoy en la misma

**Comment by asimonv** [comment]
@ndleyton aún en la misma jaja

**Comment by andresbannuraschultz** [comment]
Comparto mi solucion al problema. Quiero aclarar que mi razonamiento puede estar incorrecto (corrijan ayudantes en dicho caso):

Segun lo que estube leyendo python ocupa firefox y no chrome como default para abrir las paginas web. El tipico problema para explicar porque el video no se reproducia era que el plugin de Flash Player no estaba intalado en el browser. Entonces lo que yo hacia era instalarlo, pero en Chrome. Por ende, no cambiaba nada en lo que respecta a Python.

La solucion fue descargarme Firefox, descargarme/instalar Adobe Flash Player (ojo ahi hay que ser estricto en cuanto a cerrar las ventanas de firefox antes de instalarlo) y con eso se soluciono el problema.

Ojala les sirva y sea ese su problema. Saludos!

**Comment by Iruretagoyena** [comment]
Yo había leído lo mismo que @abannura. En resumen, no es algo que se pueda hacer con código, si no que nos tenemos que preocupar de hacer correctamente el embedding y el resto es que el ayudante ocupe un browser con permisos ( Chrome hace más pruebas de seguridad y bloquea más cosas). O no ?

**Comment by ndleyton** [comment]
Encuentro raro que funcione de esa manera, ya que YouTube reproduce con HTML5 ahora y no con Flash, pero quizás es algo en el `SetPluginsEnabled` que quizás lo *pasa* a Flash

**Comment by Pyralspite** [comment]
Doy fe de que la solución de @abannura  funciona. Gracias!

**Comment by andresbannuraschultz** [comment]
Opino igual que tu @Diiru. En verdad hacer esto no cambia nada en la correccion que hara el ayudante. No es codigo como dices. Lo unico es que al hacer esos cambios puedes comprobar que efectivamente tu codigo funciona. De todas formas, el codigo que estamos usando para agregar los videos no es complejo asi que no deberia haber problemas con eso.
