### ISSUE TITLE
Bonus Spotify

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-02/Syllabus#682]
Hola !
Con respecto al punto 4.4.2, sobre dar la opción de "elegir listas de reproducción desde Spotify", que debemos mostrar ?

A. Apretar un botón que diga "Obtener lista de Spotify" y agregar alguna lista de reproducción a las opciones que teniamos, sacada de spotify.

B. Abrir una ventana con varias opciones de listas, elegir una y agregarla a nuestras opciones.

Gracias de antemano !

**Comment by FernandoPieressa** [comment]
Hola! Queda a tu criterio que lista de Spotify, puede ser ya de alguna de las opciones anteriores, o elegir una nueva con algún método empleado por ustedes, al final del día intentamos evaluar que sean capaces de conseguir la información de listas de Spotify y las pongan en su programa.

Saludos!
