### ISSUE TITLE
Velocidad video

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-02/Syllabus#683]
Hola !
Cuando selecciono la canción y se muestra el video, este se demora (unos 4-5 segundos) entre abrirse Youtube, cargarse y luego auto-ajustarse a mi ventana (al principio muestra la barra de búsqueda y luego se mueve solo apuntando el video).

Importa que pase esto/debería preocuparme ? Se puede hacer que sea más rápido ?

Por si las moscas, el código donde pruebo el video esta en la linea 197 de main.py

Gracias !!

**Comment by jgmontoya** [comment]
Hola,

Para que cuente el bonus debe cargarse solo el video por lo que no es válido cargar toda la página y mostrar luego solo el cuadro correspondiente al video.

Me llamó la atención la cantidad de imports que tiene tu programa, sobretodo porque no ocupas la mayoría de esas librerías! 

Hay varias razones de por qué eso no es una buena idea, como por ejemplo el hecho de que le estás añadiendo dependencias a tu programa que no son necesarias (para correr tu programa se debe contar con todas esas librerías) o el hecho de que cada vez que se ejecute tu programa se estará ejecutando un montón de código adicional lo que hará que se demore más y que ocupe más memoria de lo necesario.

Saludos!

**Comment by Iruretagoyena** [comment]
@jgmontoya Ok ! Me quedo claro, gracias !

Sii los imports los tengo ahí porque copie y pegue todas las librerías permitidas, para ir revisándolas de vez en cuando a ver si me daban alguna pista. Se me fue borrarlas esta vez, gracias igual.
