### ISSUE TITLE
Error en los ejemplos :(

### ISSUE THREAD

**Issue by laurateuber** [IIC2233-2016-02/Syllabus#684]
No me funcionan los ejemplos de https://developers.google.com/youtube/v3/code_samples/python, el de agregar un video destacado me tira:
PROBANDO.py: error: the following arguments are required: --channel-id, --video-id ,
y el primero del boletín me tira lo mismo pero con --message.
Todo lo que hice fue cambiarle el nombre del archivo client-secret por el mio :(

**Comment by aaossa** [comment]
Hola, revisa bien lo que te dice el error y podrás resolverlo. **La idea de una tarea no es llegar y copiar código (esto es para todos), es ver un ejemplo, entender qué está pasando, tomar lo que necesiten y armar su propia implementación**. 

En este caso te recomiendo darle una leída al código para que entiendas lo que hace cada parte y así podrás resolver tu problema. Si tienes alguna duda con un comando o método específico búscalo, y si no quedas conforme o algo no queda claro puedes preguntar acá solo si buscaste primero :ok_hand:

**Comment by sebacruzd** [comment]
Si te fijas, tiene como 2 métodos extra que no te sirven de nada, esos borralos.

En [esta página](https://developers.google.com/youtube/v3/docs/commentThreads#resource) salen las cosas necesarias para insertar un comentario, ojalá te sirva.

**Comment by laurateuber** [comment]
Hola, si había mirado el código, buscado en google y agregado/borrado cosas al código. Pero llevaba harto rato en eso y decidí preguntar. Puse que "solo había cambiado el archivo" porque me dijeron que funcionaba tal como estaba en la página.
