### ISSUE TITLE
Obtener videos de Playlist

### ISSUE THREAD

**Issue by fnmendez** [IIC2233-2016-02/Syllabus#686]
Hola,

Hay algunas playlist del json que tienen más de 50 videos y Youtube permite recibir como máximo 50 videos por playlist.

`maxResults 	unsigned integer
El parámetro maxResults especifica el número máximo de elementos que se deben mostrar en el conjunto de resultados. Los valores aceptables son 0 a 50, ambos inclusive. El valor predeterminado es 5.`

**Comment by aaossa** [comment]
Cual es la pregunta? `maxResults` es la cantidad de videos a mostrar en los resultados, pero puedes tener *playlists* con más videos

**Comment by fnmendez** [comment]
Es un aviso para que no se espere que se desplieguen todos los videos de una playlist que tenga más de 50.

**Comment by entamburini** [comment]
es porque las playlist se envian como páginas que tienen máximo 50 items, si te fijas, hay una key en el json que te envían que dice nextPage o algo así... tienes que pedir esa página y tendrás otros 50 resultados y así con las siguientes peticiones :)
