### ISSUE TITLE
argpaser 

### ISSUE THREAD

**Issue by Tibrahm** [IIC2233-2016-02/Syllabus#688]
Hola tengo la misma duda que @Nebula2028 con el argparse en #679 y he estado bastante horas googleando para salucionar el problema pero aun no puedo, otra cosa que note es que la documentacion es de argparse pero el codigo ocupa argpaseR, no se si eso tenga algo que ver

**Comment by Tibrahm** [comment]
ya lo solucione jaja, Gracias igual !

**Comment by seba-bug** [comment]
hola @Tibrahm, cómo lo resolviste??? Cambiaste a argparse?

gracias!

**Comment by jgmontoya** [comment]
Hola,

Para qué ocupan argparse (o argparser)?

Saludos!

**Comment by seba-bug** [comment]
Ya no lo uso jaja Lo acabo de desechar. Lo usaba porque estaba en los ejemplos, pero me di cuenta que no era necesario. Al .search().list(...) le pasé sus keyword arguments y no hubo ningún problema.
😄
