### ISSUE TITLE
Duda comentarios

### ISSUE THREAD

**Issue by srvasquez** [IIC2233-2016-02/Syllabus#689]
'Debera poder seleccionarse una cancion de la lista de reproduccion original, y para esta mostrar el
correspondiente video en YouTube (Ttulo del video, link y espacio/boton para comentar).' Esto significa que el usuario también podra comentar listas que estan en el archivo json sin haberlas agregado a su canal ??

**Comment by flobarrios** [comment]
No, deben haber sido creadas antes para poder comentarlas.

**Comment by srvasquez** [comment]
Gracias 💃
