### ISSUE TITLE
Rutas 

### ISSUE THREAD

**Issue by domingo-valdes** [IIC2233-2016-02/Syllabus#69]
¿Podemos asumir que siempre el archivo de rutas que se ingresará será como una recta? Es decir, que para llegar de la primera a la última ciudad hay que cruzarlas todas, que no hay caminos alternativos o ciudades de las que salga más que un camino de ida y otro de vuelta.

**Comment by flobarrios** [comment]
Hola! Eso sí lo pueden asumir, junto con que entre cada ciudad **siempre** habrán 3 cuadros de hierba. Saludos!

**Comment by domingo-valdes** [comment]
gracias!
