### ISSUE TITLE
Obtención de videos de una playlist

### ISSUE THREAD

**Issue by cameneses** [IIC2233-2016-02/Syllabus#690]
Tengo una duda más que nada de modelamiento en cuando a la obtención de videos de una lista de reproducción. Lo que estoy haciendo es que cuando el usuario solicita escuchar una canción cualquiera de una lista, busco esa canción con el mismo algoritmo que uso para buscar un video en la creación de la lista (o sea que me devuelve el mismo video que está en la lista de reproducción del canal). Esto lo hago porque siento que es mucho más eficiente que pedirle al servidor tooda la lista y buscar entre esta la canción solicitada.

Mi duda va en si lo que se espera es que ese item lo hagamos pidiéndole al servidor toda la playlist y filtrar el id del video desde ahí o bien puedo dejarlo como lo tengo y explicar en el README que es por temas de no sobrecargar el uso de la API y por hacer el programa más eficiente en cuanto a esto.

**Comment by Tibrahm** [comment]
Tengo la misma duda, cuando queramos comentar un video u obtener las estadísticas de este siento que es mucho mejor ir directo al video usando el algoritmo que los busca directamente  antes de tener  que obtener nuestra playlist filtrar el id y recien ahi hacer lo solicitado

**Comment by Tibrahm** [comment]
y cuando dice que debemos mostrar el link del video se refiere al link del video original o al link del video es nuestro canal en nuestra playlist?

**Comment by flobarrios** [comment]
Hola! En una issue se habló de esto, y un alumno sugirió guardar un json (o varios) con las listas y los id de los videos de youtube (no de spotify). Creo que eso los puede ayudar para evitar volver a hacer el match entre la canción de spotify y youtube. Respecto a lo segundo, da lo mismo pero recuerda especificarlo en el readme 😊

**Comment by cameneses** [comment]
Muchas gracias!!
