### ISSUE TITLE
[Tarea 7] Duda sobre playlists

### ISSUE THREAD

**Issue by roy350** [IIC2233-2016-02/Syllabus#692]
Disculpen, pero me queda la duda de que en el caso de mi programa lo que hago al iniciar éste, pide autorizacion con una cuenta de youtube y luego puede crear una de las 10 listas del json, una vez creada, puede crear otra si lo desea o irse a las diversas opciones ranking, comentarios o cerrar sesion, el tema es que yo evito que cree la misma playlist, para que tenga sentido en si el programa al cargar los datos de el ranking ya que tendran las mismas canciones, pero en el caso que cierre la sesion por ejemplo si antes creo la playlist "TOP 50 hits" obviamente esta seguira existiendo en la cuenta de youtube pero al momento de correr nuevamente el programa éste si dejara crear esa lista osea que mi programa basicamente evita que crees la misma lista de reproduccion siempre y cuando no cierres la sesion(en mi programa), mi duda es el programa debera reconocer las listas de reproduccion creadas con anterioridad o simplemente basta como lo tengo actualmente? muchas gracias por la ayuda!!

**Comment by FernandoPieressa** [comment]
Hola! Queda a tu criterio si se pueden crear nuevamente las mismas playlist que uno tenia o no, por lo tanto queda a tu criterio que hacer respecto a si se deben reconocer las listas de reproduccion dentro de tu programa luego de otro inicio de sesion(Mientras el cambio si se mantenga en youtube).

Si es que deseas hacerlo de esa manera siempre puedes guardar en archivos la informacion que quieres guardar para otro uso del programa.

Saludos!
