### ISSUE TITLE
Video público

### ISSUE THREAD

**Issue by jicortes2** [IIC2233-2016-02/Syllabus#694]
En vista que muchos han tenido problemas con el embedding de algunos videos, les dejo uno para que prueben sus tareas :D tiene todas las opciones públicas y permite ser insertado en sus tareas asi que no deberían tener problemas.
[Un pobre alumno de progra avanzada](https://www.youtube.com/watch?v=xFvZKHKRdVk)
En la guitarra: su tareo preferido @criscv94 
Acompañándolo cantando su docencio preferido: Yo :)
Éxito!!

**Comment by andresbannuraschultz** [comment]
Jajajajaja buenisimo el video

**Comment by Nebula2028** [comment]
Si no me funciona ese video en mi aplicación es que definitivamente lo estoy haciendo mal? :(

**Comment by Tibrahm** [comment]
a mi me sale el mismo problema que con el resto de los videos ! 

![image](https://cloud.githubusercontent.com/assets/14153815/20650983/a87696c0-b4ba-11e6-9762-939addc44bf6.png)

**Comment by Tibrahm** [comment]
estoy haciendo algo mal o es un problema como el de el resto de los videos ???????? llevo ya hartas horas tratando de solucionar el problema de diferentes formas pero me sigue saliendo lo mismo !!

**Comment by lefischer** [comment]
estamos todos en la misma

**Comment by ivaniadg** [comment]
Vieron la issue #681?
