### ISSUE TITLE
Insufficient Permission

### ISSUE THREAD

**Issue by Tibrahm** [IIC2233-2016-02/Syllabus#695]
Tengo una problema que me tiene muy frustado, tengo mi archivo comentar.py donde tengo mi funcion 
insert_comment, si llamo a esta funcion desde este archivo hace el comentario correctamente. Por otro lado tengo mi archivo GUI.py que importa comentar.py, y al momento de llamar a la misma funcion pero desde el archivo GUI me salta este error "googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/youtube/v3/commentThreads?alt=json&part=snippet returned "Insufficient Permission">" 

No entiendo porque me tira que no tengo permiso si corro la funcion desde otro archivo pero si lo corro del mismo funciona perfecto

**Comment by ivaniadg** [comment]
No tienes un problema con el path del archivo que tiene las credenciales?  

Si el path es relativo es probable que ese sea el problema.

**Comment by Tibrahm** [comment]
Eso mismo era !!!!!! Gracias !

**Comment by sormazabal** [comment]
@indonoso me ocurre lo mismo, pero estoy usando el absolute path :S

**Comment by vacodoceo** [comment]
@sormazabal lo resolvi utilizando otra forma de guardar las credenciales, especificamente la que aparece [aca](https://developers.google.com/youtube/v3/docs/commentThreads/insert). Tendras que utilizar el "youtube" que crean con esa funcion, y tambien tendras que guardar esas credenciales en otro archivo para que esto funcione. Debe haber otra manera mas linda y simple de arreglarlo, pero despues de estar con ese error todo el dia ya no tengo animos de investigar mas al respecto jaja

**Comment by sormazabal** [comment]
@vacodoceo  <3 <3 <3 GRACIAAAAAAAAAAAAAAAAAAAAAAAAASSSSSSSSSSSSS!!!!!!!!!!!!!!!!!!!!!!!!!!
Había estado tan pegada con eso <3 te debo la vida
