### ISSUE TITLE
Es válido el código ?

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-02/Syllabus#696]
Hola !
Estaba feliz con mi solución de como mostrar videos en la GUI, pero después re-leí el enunciado y me dio miedo la parte que dice
> Para cada una de las siguientes funcionalidades, queda estrictamente prohibido desplegar el codigo html en un browser para cumplir con lo pedido.

Si bien, dudo mucho que mi solución caiga en esta categoría, un descuento de puntaje no sería grato, por lo que prefiero preguntar; **algún ayudante puede revisar la forma que implemente, y decirme si es legal ?** Línea 176 hasta Línea 182 de main.py

De antemano, muchísimas gracias !

**Comment by jgmontoya** [comment]
Es legal :-)
