### ISSUE TITLE
Resultados de búsqueda vacíos

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-02/Syllabus#697]
Hola !

Qué debería pasar si es que llegará a retornar vacío luego de hacer la búsqueda de un vídeo ?
En vez de resultados, avisar de alguna forma que no se encontró tal video ?
Pasa muy, muy poco, pero por si acaso.

Gracias de antemano

**Comment by jgmontoya** [comment]
Hola, 

Cómo manejar este caso queda a su criterio, siempre y cuando sea algo razonable estará bien. Eso sí el programa no debe caerse.

Saludos!
