### ISSUE TITLE
Videos 

### ISSUE THREAD

**Issue by Tibrahm** [IIC2233-2016-02/Syllabus#698]
Tengo un duda respecto a como tenemos que desplegar el vídeo para poder verlo, creo que esto ya lo respondieron en otra issue. Por ahora lo que estoy haciendo para desplegar el video es ocupar una ventana qwebview pero esta muestra toda la pagina de youtube, esto se puede hacer así o solo tiene que mostrar el vídeo ?

**Comment by flobarrios** [comment]
Hola! No se puede hacer asi. No puedes desplegar la pagina completa. Saludos!

**Comment by Tibrahm** [comment]
ok Gracias !!!!!
