### ISSUE TITLE
Problema al buscar ciertas canciones

### ISSUE THREAD

**Issue by seba-bug** [IIC2233-2016-02/Syllabus#699]
Hola! Siento que esto ya lo respondieron....

Con algunas listas me pasa que no aparecen resultados para ciertas canciones... revisé un poco y de hecho no pude encontrar algunas de forma manual (por ej, "Now It's Over Now I'm Awake" de LUCHS en la lista Deep Focus). 

¿Se espera que avisemos de estos problemas y sigamos no más o simplemente no lo avisamos?

Gracias!

**Comment by Hernan4444** [comment]
@sguerra2, efectivamente ya se respondió, revisa #697 
Saludos!!
