### ISSUE TITLE
Problema en Descarga librerias para Windows

### ISSUE THREAD

**Issue by Bnnunez** [IIC2233-2016-02/Syllabus#7]
Hola cuando coloco el comando: pip install -i https://pypi.binstar.org/carlkl/simple numpy  
Me aparece el siguiente error.

Could not find a version that satisfies the requirement numpy (from versions: )
No matching distribution found for numpy
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by FernandoPieressa** [comment]
Al parecer, leyendo los contenidos de ese link, no tiene numpy para la versión python 3.5. Es bastante parecido al caso que algunos ya tuvieron con PyQt4. #4

Para futuro general, muchas veces pueden encontrar paquetes .whl en la pagina http://www.lfd.uci.edu/~gohlke/pythonlibs/ con las ultimas versiones de python y se instala igual haciendo pip install ruta/de/mi/archivo.whl.

**Comment by Bnnunez** [comment]
se me arreglo (creo) utilizando el tercer comando de la libreria antes que el segundo.

**Comment by Marivera3** [comment]
Hola! también tengo un problema con las librerías. Al escribir: pip install --upgrade simpy
Me aparece el siguiente error:
File "<stdin>", line 1
pip install --upgrade simpy

SyntaxError: invalid syntax

¿Cómo lo puedo solucionar?

**Comment by otro-felipe** [comment]
Al parecer estas usando pip desde la consola de python. Debes usar pip desde la consola de tu sistema operativo.

**Comment by sebacruzd** [comment]
@Bnnunez eso también lo hice yo y también le funcionó a un amigo, esa es la solución cuando se puede instalar el resto excepto numpy
