### ISSUE TITLE
PC de Bastián 

### ISSUE THREAD

**Issue by gabrielpinkman** [IIC2233-2016-02/Syllabus#70]
Hola, tengo una pregunta, cuando se visualiza el PC de Bastián dice " Contiene todos los programones capturados a través de una prograbola y contiene toda la información de estos por cada jugador". No entiendo si hay que mostrar todos los programones atrapados por todos los jugadores que ocupan el juego o solo los atrapados por aquel que ingrese su nombre y contraseña.

**Comment by jgmontoya** [comment]
Hola,

> No entiendo si hay que mostrar todos los programones atrapados por todos los jugadores que ocupan el juego o solo los atrapados por aquel que ingrese su nombre y contraseña.

Se deberán mostrar solo los atrapados por aquel que ingrese su nombre y contraseña.

Saludos!

**Comment by FranciscoLarach** [comment]
Y entonces cual es la diferencia con el progradex? en el progradex solo se muestra como la identidad de los conocidos? como vistos y capturados?
Saludos

**Comment by flobarrios** [comment]
Hola! la diferencia es que la idea de acceder al pc de Bastián es para cambiar a algún programón del equipo, mientras que la progradex es netamente informativa. Además, la progradex muestra a los vistos y capturados (incluyendo las evoluciones) mientras que el pc solo muestra a los programones "disponibles" para ser parte del equipo del jugador.

**Comment by juliandewulf** [comment]
Hola, en el PC de Bastián tienen que estar absolutamente todos los programones capturados o solo los capturados que NO están en el equipo? 
pregunto ya que no tengo bien claro si hacer la separación o no

**Comment by jgmontoya** [comment]
@muiturriaga Solo los que **_NO**_ están en el equipo.
