### ISSUE TITLE
fabricación json "listas_de_reproducción"

### ISSUE THREAD

**Issue by ndleyton** [IIC2233-2016-02/Syllabus#700]
Hola, tratando de hacer el bonus de spotify, me encontré con que al solicitar las playlist de un usuario, retorna un json muy distinto a `listas_de_reproduccion.json` y solo quería saber si al hacer este, fue algo que se consiguió directamente o que se *fabricó* de cierta manera, como obteniendo datos de las listas y de estas, de los tracks?

**Comment by jgmontoya** [comment]
![image](https://cloud.githubusercontent.com/assets/11434422/20643918/4cc8d42a-b404-11e6-9dfa-b14ea1f4fef1.png)

**Comment by jgmontoya** [comment]
Se *fabricó* de cierta manera, puedes hacerlo como te parezca más adecuado.

Saludos!
