### ISSUE TITLE
if desocupado y buena onda: probar mi programa

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#701]
Hice algunos issues muy lateros preguntando qué necesitábamos entregar exactamente para que todo corra bien. Este issue es mucho más entretenido porque creo que ya terminé y me encantaría que algún simpático ayudante eche a andar mi código y vea si funciona todo bien.

Favor de leer sub título 'Usuario' en el README. En el README debería estar todo lo que necesitan, si es que necesitan algo.

Gracias!

**Comment by jgmontoya** [comment]
NameError: name 'desocupado' is not defined

**Comment by flobarrios** [comment]
Hola, 

Si quieres que algún ayudante revise tu tarea, se asumirá que es la entrega final y cualquier otro cambio que hagas no será considerado en tu evaluación (como comentario, no te lo recomiendo). Si cumples con lo que dice el enunciado entonces quédate tranquilo.

**Comment by cjgazali** [comment]
Okay @flobarrios pero me corrijo si no fui enfático: me preocupa que el 'ambiente' sea el adecuado. No necesito que revisen toda la tarea. De hecho con que me digan que se ven todos los archivos necesarios es suficiente. Esto no tiene que ver con el enunciado.

Si resulta explicativo, he aquí las dos issues que no fueron pescadas hace días (no es necesario que las pesquen ahora): #658 y #666 .

En variadas otras ocasiones los ayudantes resuelven dudas mirando la tarea y no cuenta como entrega. Creo estar en ese nivel de petición.
