### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#702]
Estaba realizando la creacion de una playlist y youtube me entrega un token (que debe ser ingresado en el programa) este debo dejar que el usuario lo coloque? o tengo que hacerlo de forma automatica? 
PD : al usuario le pide el logging el la ventana de internet, Eso esta bien? porque despues de ingresar el token tengo que apretar nuevamente log-in  y me aparece el usuario (ya no pide contraseña). 

Saludos.

**Comment by ivaniadg** [comment]
Ver #665
