### ISSUE TITLE
Bonus: Spotify

### ISSUE THREAD

**Issue by jbsaeza** [IIC2233-2016-02/Syllabus#705]
Respecto al bonus quisiera saber que tan lejos tengo que llegar para obtener el puntaje máximo, hasta ahora tengo que la persona puede buscar listas en spotify mediante un titulo que ellos ingresan y se despliegan los resultados en una QListWidget y ellos ven cual agregan, pero mi duda es que si debo darle la opción de ver que canciones tiene cada lista para que evalúen si la agregan o no, o si debo entregarle otro tipo de información de la lista como la cantidad de vídeos que tiene o algo así.

**Comment by FernandoPieressa** [comment]
Hola! La idea del bonus es que se pueda buscar canciones y armar una lista con ellas mediante spotify, no necesariamente haciendo el mismo json que les entregamos, por lo tanto lo que tienes hecho esta bien.

Saludos!

**Comment by jbsaeza** [comment]
Entonces no basta con buscar listas ya creadas dentro de spotify, el usuario debe crear una personalizada eligiendo las canciones que estarán dentro de ella?

**Comment by jatrijori** [comment]
Hola, yo entendí que se debían buscar playlists ya hechas y eso es lo que hice, bastará con eso?

**Comment by asimonv** [comment]
Yo hice que el usuario pudiera traspasar sus listas a youtube. Al menos eso entendí del enunciado.

**Comment by Iruretagoyena** [comment]
@FernandoPieressa 
Hola Fernando ! Por #682 yo entendí que teníamos cierta libertad, por lo que mi bonus de Spotify consiste en un boton, abajo de las listas ya disponibles, en donde al apretarlo se agrega una lista sugerida por Spotify a la lista de canciones ya existentes, usando su API. Eso bastará ? Ruego avisarme si tengo que modificarlo ! Gracias

**Comment by FernandoPieressa** [comment]
Al parecer mi mensaje no quedo muy claro, el tema es que ustedes tienen mucha libertad de como y de que forma implementar el uso de la API de spotify en su programa.

Mientras usen la API para conseguir canciones de spotify y con ellas armar una lista en youtube esta bien su trabajo, de ahi como y que esta a su criterio :) (Pero pongan en su readme)

Saludos!
