### ISSUE TITLE
Video a mostrar en estadisticas

### ISSUE THREAD

**Issue by lefischer** [IIC2233-2016-02/Syllabus#706]
hola

en las estadisticas se debe mostrar el peor o mejor viedo segun el criterio escogido, o ambos.

**Comment by FernandoPieressa** [comment]
Hola!

Se debe poder mostrar ambos casos en las estadisticas, el mejor y el peor video segun criterio escogido.

Saludos!

**Comment by fipaniagua** [comment]
hola al principio no habia leido bien el enunciado, y lo que mi programa hace es desplegar todos los videos
dela lista ordenados segun el parametro
¿esta bien si lo dejo asi o lo tengo que cambiar?
(en el fondo de la forma que lo hice obtienes mas informacion)

**Comment by FernandoPieressa** [comment]
@fipaniagua Esta bien si lo dejas asi  mientras se pueda ver claramente el orden según el parámetro.

Saludos!
