### ISSUE TITLE
Cuenta bloqueada en YouTube

### ISSUE THREAD

**Issue by rrfoster** [IIC2233-2016-02/Syllabus#707]
estaba probando mi programa y me banearon la cuenta de prueba que estoy usando sin mayor explicación que estaba violando los términos y condiciones de uso, la cuenta ha sido borrada permanentemente. a que se debe esto, alguna recomendacion para evitar que ocurra de nuevo?

**Comment by Afalegria** [comment]
A mi me pasó y tuve que crear otra, no es tan terrible, saca de nuevo el json y haz lo mismo que la anterior, solo reemplazas el json y la apikey... creo que es porque pasé el limite de datos o no se que onda jaja alguna condicion se pasó a llevar con tanta prueba de la tarea

**Comment by aaossa** [comment]
Por favor traten de no abusar de la API, por eso los están bloqueando. Es un asunto de buenas costumbres, si yo te dejo tomar un vaso de agua en mi casa tu no vienes a llenar tu piscina :confused: .  Muchas veces las APIs tienen un límite de *requests* en cierta cantidad de tiempo (por ejemplo GitHub entrega 5000 por hora para usuarios autenticados) para evitar que los usos abusivos sobrecarguen sus servidores.

**¿Cómo les sugiero trabajar?** Lean bien la documentación, creen sus parámetros, hacen la *request* para probarla (código) y si no les funciona leen de nuevo la documentación, su código y los parámetros. Cuando la *request* funcione agregan el código en su programa principal. NO prueban con 20 ejemplos y NO corren el programa a cada rato. De esta forma podrán desarrollar su aplicación correctamente. Una vez que hayan agregado un par de consultas prueban todo su programa. 

**Pro tip**: Usen [**Jupyter Notebook**](http://jupyter.org/). Se los recomendamos a comienzo de semestre y un buen uso es crear una *request* y después poder obtener datos de la respuesta sin tener que estar consultando cada vez el recurso vía API

**Pro tip 2**: Usen [**requests.Session**](http://docs.python-requests.org/en/master/user/advanced/), les facilitará utilizar las *request* que ya hayan hecho y además debería ser más eficiente, pues es una conexión al servidor que se reutiliza.

Tirón de orejas para todos los que les pasó esto :skull:  

### #shame

**Comment by fgvenegas** [comment]
https://www.google.cl/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=0ahUKEwizx9Oi_snQAhVLHpAKHZE9CNUQjRwIBw&url=https%3A%2F%2Ftwitter.com%2Fonfiresemmler%2Fstatus%2F660843562045714432&psig=AFQjCNHtmfU6xxHoQnG0h631esfwML0_6g&ust=1480372178724796

**Comment by fgvenegas** [comment]
![shame](https://cloud.githubusercontent.com/assets/13748708/20652442/014e1274-b4d8-11e6-9ffa-665386547621.jpg)
