### ISSUE TITLE
Problema con importar modulo

### ISSUE THREAD

**Issue by lefischer** [IIC2233-2016-02/Syllabus#708]
hola

me aparece ImportError: No module named 'httplib2'  desde la consola de idle
httplib2.ServerNotFoundError: Unable to find the server at www.googleapis.com desde la consola de spider
pero si hago pip list si me aparece en la lista y ayer si me funcionaba

**Comment by fgvenegas** [comment]
Si desde la consola haces `python3` y dentro haces `import httplib2` que sucede?

**Comment by lefischer** [comment]
me aparece
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import httplib2
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import httplib2
ImportError: No module named 'httplib2'
>>> 

probe reiniciado el computador

**Comment by fgvenegas** [comment]
Entonces tienes que instalarlo, asumo que por cosas de la vida puedes tener python 2 y 3 en tu computador, pip es de python 2, prueba haciendo `pip3 install httplib2`

**Comment by lefischer** [comment]
ya lo hice
C:\Users\lefis>pip3 install httplib2
Requirement already satisfied: httplib2 in c:\users\lefis\anaconda3\lib\site-packages

**Comment by fgvenegas** [comment]
Cuando dije que usaras la consola, usaste la de spyder o la terminal de comandos ? (Cmd)

**Comment by lefischer** [comment]
ahora por alguna razon somo me funciona dentro de spider. ayer me funcionada desde cualquier consola
