### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lefischer** [IIC2233-2016-02/Syllabus#709]
hola

por alguna razon solo en la cancion de ''Silhouette" en ''feel good indie rock'' no se me agrega name al dict. lo maneje con una ecxepcion. es decir si no hay name que ponga el titulo en youtube.

es muy grave el error?

aparte... en general todo se demora mucho en cargar, y no se como arreglarlo

**Comment by asimonv** [comment]
Gracias! No había cachado.
