### ISSUE TITLE
Orden de los gyms

### ISSUE THREAD

**Issue by asimonv** [IIC2233-2016-02/Syllabus#71]
El gimnasio de Viridian City está al último en su gyms.json, pero su id es 1, por lo que el jugador no puede seguir si es que no lo ha vencido y es difícil porque los pokemones del gimnasio tienen niveles muy altos para ese punto en el juego. En el original te lo saltai hasta que tienes todas las medallas restantes, podemos hacer lo mismo?

**Comment by flobarrios** [comment]
Hola! por favor revisa issues antes de abrir una nueva. Duplicada: #31
