### ISSUE TITLE
Libspotify App-Key

### ISSUE THREAD

**Issue by seba-bug** [IIC2233-2016-02/Syllabus#710]
¿Alguien tiene una app key que me regale/preste/arriende? Recién me puse a trabajar en el bonus y la pagina para obtener la key no está funcionando 😭 
https://developer.spotify.com/technologies/libspotify/application-keys/

Si es ilegal no me queda más que llorar...

**Comment by fgvenegas** [comment]
Hola
Para las keys no necesitas eso !

Tienes que crear una aplicacion (es una de las opciones del lado My Applications) ahi creas una aplicacion y te entregas las keys que necesitas para trabajar :)

**Comment by seba-bug** [comment]
jiji Gracias!

Ahora estoy usando spotipy y hasta el momento no he necesitado ninguna autorización 😉
