### ISSUE TITLE
Problema con el repositorio del git Ayuda porfavor

### ISSUE THREAD

**Issue by fabraghetto** [IIC2233-2016-02/Syllabus#712]
Al hacer el código "git add --all" me sale el siguiente error:
"error: inflate: data stream error (unknown compression method)
fatal: failed to read object 216cc67d13dfcce964cc944350e84a25efdd0356: Invalid argument"

Creo que tengo que eliminar el objeto que indica pero no se a que archivo corresponde ese código, esto me impide pushar, agradecería mucho la ayuda.

**Comment by ivaniadg** [comment]
Buscando en google "error: inflate: data stream error (unknown compression method) fatal: failed to read object *: Invalid argument" encontré dos soluciones. Tiene que ver con un archivo que quedó corrupto. Alguna de esas dos te sirvió?

**Comment by fabraghetto** [comment]
Mm si intenté pero o no las entendí bien o no me funcionaron

**Comment by fabraghetto** [comment]
¿Que hago si no puedo subir mi tarea por causa de este error? , puedo mandarla por mail o algo por el estilo?

**Comment by ivaniadg** [comment]
que instrucciones seguiste?? La opción más fácil es hacer pull del repositorio en otro lugar de tu computador, copiar tu T07 ahí y luego hacer push. No se reciben tareas por otros medios.

**Comment by fabraghetto** [comment]
Hice lo que me dijiste (lo más fácil), gracias por la ayuda, pueden cerrar la issue si quieren.
