### ISSUE TITLE
redirect_uri spotipy

### ISSUE THREAD

**Issue by Afalegria** [IIC2233-2016-02/Syllabus#714]
Hola, llevo mucho rato pegado con el redirect url de spotipy, cuando instancio mi "Spotify", me tira lo siguiente en consola:

"User authentication requires interaction with your web browser. Once you enter your credentials and            give authorization, you will be redirected to a url.  Paste that url you were directed to to  complete the authorization."

Se supone que tengo que hacer un request que me va a redirigir a un url ? He probado miles y no pasa nada asi... y donde tengo mis datos puse un url para que sean iguales al de cuando instancio y tmpco me pesca... aiura :(

**Comment by asimonv** [comment]
yo usé ```SPOTIPY_REDIRECT_URI = 'http://localhost:8080/callback'``` no más jaja

**Comment by seba-bug** [comment]
@asimonv te debo un queque.... lo logré gracias a tu comentario!! 🎉
