### ISSUE TITLE
Se requiere scope con "force.ssl" para comentarios

### ISSUE THREAD

**Issue by gebalassa** [IIC2233-2016-02/Syllabus#715]
## **¡Buenas!**

¿Cómo obtengo el certificado con _scope_ `https://www.googleapis.com/auth/youtube.force-ssl`? La página de consola me permite descargar el JSON pero sólo me otorga el _scope_ `https://www.googleapis.com/auth/youtube` sin el "force-ssl", necesario para crear comentarios (y probablemente para otras operaciones). Esto conduce a un error tipo "**Insufficient Permission**".

La otra opción sería modificar todo mi código de autorización para solicitar el certificado directamente, especificando el _scope_, pero deseaba saber si existía alguna forma más sencilla.

**Comment by jgmontoya** [comment]
Hola,
Debes especificar el scope que tu aplicación requiere en su totalidad cuando hagas la autenticación para que te den el nivel de permisos necesario.

Saludos

**Comment by gebalassa** [comment]
Wenas:

El certificado que se obtiene en `console.developers.google.com` no permite seleccionar "scope", simplemente te da la opción de elegir entre una serie de dispositivos (Android, Web, etc) del cual yo elijo "web". Posteriormente te permite descargar el JSON.

Luego ejecuto mi código, se crea el auth2.json y puedo realizar las operaciones de playlists. La capacidad de comentar es la única que me bloquea. ¿Debo, entonces, buscar la forma de pedir el certificado directamente mediante parámetros? Como lo estaba haciendo solo requería insertar el certificado como un string dentro del programa y que se creara como JSON si el archivo no está ya en la carpeta.

**Comment by gebalassa** [comment]
Por alguna razón ahora que volví a descargar el archivo funcionó. Desconozco el por qué. Ahora sale "...force-ssl" en el certificado.

Gracias de todas maneras por el tiempo (y la hora)!

Saludos (y)
