### ISSUE TITLE
Sobre examen

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#717]
Si entendí bien, el examen será para todos el viernes a las 15:30, ¿correcto? Podrían actualizar el calendario para evitar problemas...

¿Podrán subir las diapositivas de las ayudantías extra para el examen? Con que esta mañana suban la del viernes pasado ya es de mucha ayuda, pero suban la de hoy pronto también 😄 .

EDIT PD: ¿evalúan las lecturas en el examen?

Gracias!

**Comment by aaossa** [comment]
Ya actualicé la fecha :ok_hand:

**Comment by ivaniadg** [comment]
@cjgazali 

Subí la ayudantía recién :grimacing:, tiene unos ejemplos que no vimos en clases para explicar las preguntas que no alcancé a responder.

> EDIT PD: ¿evalúan las lecturas en el examen?

Sí
