### ISSUE TITLE
Opción cancelar

### ISSUE THREAD

**Issue by srvasquez** [IIC2233-2016-02/Syllabus#72]
Hola, la opción cancelar se refiere a que por ejemplo un jugador selecciona caminar en el menú y preguntar de nuevo si esta seguro de la opción, y si no esta seguro volver al menú donde estaba la opción caminar?

**Comment by flobarrios** [comment]
Hola! se refiere a que des la opción de volver al estado anterior. Por ejemplo, si tienes:

```
1. Programones en la progradex
2. Caminar
3. Datos del jugador
4. Consultas
5. Salir del sistema
```

Y vas a consultas (4):

```
1. Batalla por programón involucrado
2. Ranking de programones
3. Jugador
4. Volver atrás
```

Si vas a volver atrás (4) deberías volver a desplegar:

```
1. Programones en la progradex
2. Caminar
3. Datos del jugador
4. Consultas
5. Salir del sistema
```

Espero que haya quedado más claro!

**Comment by bedefrunner** [comment]
Hola! Entiendo que hay que dar la opcion de volver atras, pero realmente tiene que ser SIEMPRE? Por ejemplo, si un jugador es nuevo, debe elegir un programon. Despues de elegirlo, puede arrepentirse, volver atras y elegir otro? O si compra prograbolas, puede volver atras y que se eliminen las que compro?

**Comment by flobarrios** [comment]
@federicobrunner no! en esos casos que mencionas no es necesario. Es necesario para salir de la tienda de prograbolas, salir de un gimnasio, volver a las opciones (como caminar, consultas, etc). Saludos!
