### ISSUE TITLE
Duda __init__ metaclases

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#720]
Opino que el __init__ de una metaclase no debería retornar nada, a pesar de que en las ayudantías siempre han puesto que retorne el `super().__init__(name, bases, attrs)`.

PyCharm me marcaba un error si intentaba retornar, pues no encuentra nada para retornar en el `super().__init__(name, bases, attrs)` porque un __init__ no retorna nada. Solo necesitamos llamarlo para que se corra ese código, pero ningún __init__ le está retornando nada a nadie, a diferencia de __new__ que debe retornar el objeto creado y __call__ que debe retornar una inicialización de la clase creada por __new__. He encontrado ejemplos de lo que opino en internet.

¿Estoy entendiendo bien? Gracias.

**Comment by ivaniadg** [comment]
Hola,

Estás en lo correcto. Por convención mucha gente pone un `return` al `__init__` pero en verdad solo retornan `None`.
