### ISSUE TITLE
Dos dudas

### ISSUE THREAD

**Issue by JaimeGo** [IIC2233-2016-02/Syllabus#722]
Hola! Tengo las siguientes dos dudas, ojalá me puedan ayudar:

1) ¿Cuando sería la instancia final para corregir tareas? Voy a prepararme un poco estudiando cada corrección. Quizá quieran dar la fecha más adelante, o puede que ya lo hayan mencionado y no lo haya leído, pero pregunto por si acaso.

2) Según lo que recuerdo hubo un noveno control (a mi me tocó explicar socket.bind, si eso ayuda) y como no aparece entre las notas quería saber si va a reemplazar el peor, va a ser un control normal, o cómo lo van a hacer. Si estoy confundido, disculpen las molestias.

Muchas gracias!

**Comment by ivaniadg** [comment]
Hola!

> ¿Cuando sería la instancia final para corregir tareas? Voy a prepararme un poco estudiando cada corrección. Quizá quieran dar la fecha más adelante, o puede que ya lo hayan mencionado y no lo haya leído, pero pregunto por si acaso.
 
El martes 6 de diciembre entre las 9 y las 13hrs se va a recorregir 
- Tareas 5, 6 y 7
- Examen
- Control 9
- Actividades 14 y 15.

> Según lo que recuerdo hubo un noveno control (a mi me tocó explicar socket.bind, si eso ayuda) y como no aparece entre las notas quería saber si va a reemplazar el peor, va a ser un control normal, o cómo lo van a hacer. Si estoy confundido, disculpen las molestias.

Recuerdas bien. La pauta del control 9 estará mañana. Como sale en las reglas del curso, *no se borran controles*, el control 9 es un control normal.
