### ISSUE TITLE
pregunta examen 2016-1

### ISSUE THREAD

**Issue by Tibrahm** [IIC2233-2016-02/Syllabus#724]
no entiendo el primer print en esta pregunta !!

```
class MetaExamen(type):
    v1 = []
    def __call__(cls, *args, **kw):
        while(len(cls.v1) < args[0]):
            cls.v1.append(super().__call__(*args, **kw))
        return cls.v1
    
class Pregunta(metaclass=MetaExamen):
    cont = 0
    def __init__(self, n):
        self.id_ = Pregunta.cont
        Pregunta.cont += 1

    def __repr__(self):
        return str(self.id_)

a = Pregunta(7)
print(a)
print([type(a[i]) for i in range(len(a))])
```

porque se le va sumando uno ?
EDIT: formato código

**Comment by isidoravs** [comment]
Hola, según lo que entendí, lo que pasa es que en el `__call__` de la metaclase no se retorna la instancia de la clase, sino que una lista de instancias de la clase Pregunta (cuando se hace `cls.v1.append(super().call(*args, **kw))`). 

Entonces `a` es una lista con instancias de la clase Pregunta y al imprimirla cada uno de los objetos muestra su id (por la sobrecarga de `__repr__`) que toma el valor del atributo de clase `cont` comenzando en 0 y aumenta en uno cada vez que se crea una instancia de la clase.

**Comment by asimonv** [comment]
Porque el ```super().__call__(*args, **kw)``` retorna una instancia de la clase que "hereda" de la metaclase, entonces en ``` cls.v1.append(super().__call__(*args, **kw))``` le estás agregando instancias de Pregunta (por lo que llama a su init, no de la metaclase, sino que de Pregunta, además  es ahí donde se hace ```Pregunta.cont += 1``` y su id aumenta), a v1 que lo hereda de la metaclase. 

Luego, como el ```__call__``` de la metaclase retorna ```cls.v1``` (lo que significa que trata a la instancia de Pregunta como una lista -> ```return cls.v1```), entonces como al imprimir cada elemento de la lista, se llama al ```__repr__```del elemento y este retorna el id y así el resultado es el que conoces jaja.
