### ISSUE TITLE
Duda decoradores

### ISSUE THREAD

**Issue by jbsaeza** [IIC2233-2016-02/Syllabus#725]
En Syllabus/Ayudantias/14-Examen-1/Decoradores.ipynb, tengo dos dudas:

1) En la linea donde se hace func3 = deco1(sumar), se estaría aplicando 2 decoradores sobre una misma función, y por lo que eh probado gana la que fue implementada con sugar sintaxis, no tengo muy claro por que gana esta ya que según los prints, la ultima función func3 es la que se aplica ultimo.

2) Cuando los kwargs pasan por el decorador, eston no hacen efecto en el resultado de la función, por ejemplo, func2 tiene como argumentos de su constructor a = 2, b = 3, c = 10, por lo que se espera un resultado de -11, sin embargo se imprime -1, mediante prints averigüe que a restar le llega por valor de c un str equivalente a "c", no el valor 10, siendo que al imprimir este kwarg en el constructor aparece como corresponde. Por que ocurre esto?.

**Comment by iqacevedo** [comment]
Según lo que yo entendí:

1-. Pasa por como se construyó el decorador, fíjate que no importa lo que reciba la función una vez decorada siempre se evaluará en lo que el constructor recibió como parámetros. Si le aplicas el decorador nuevamente, intentarás que la función reciba otros parámetros, pero como ya la habías decorado retorna los del primer decorador.

2-.Pasa porque está mal escrito xd. Fíjate que la línea dice func(*args, *kwargs) y solo sale un * acompañando a kwargs (por lo que solo lo reconoce como la lista de las llaves del kwargs), si lo dejas como func(*args, **kwargs) te dará -11 (ya que ahi reconoce como corresponde a *kwargs)

**Comment by jbsaeza** [comment]
@iqacevedo  grande ignacio!!!
