### ISSUE TITLE
Recorrecion

### ISSUE THREAD

**Issue by jbsaeza** [IIC2233-2016-02/Syllabus#727]
Debido a que soy de región, voy a viajar este fin de semana devuelta a mi hogar y es sumamente difícil postergar este viaje, por lo que no podre estar para la recorrecion presencial, quería saber si un amigo que también esta dando el ramo puede ir por mi.

**Comment by bamavrakis** [comment]
Estimado,
Si puede ir tu amigo. Envíame un mail diciéndome quién irá en tu lugar.
Saludos!
