### ISSUE TITLE
Re-correcion Tarea 5

### ISSUE THREAD

**Issue by NoemiCC** [IIC2233-2016-02/Syllabus#729]
Hola,
Hoy vi mi feedback de la tarea 5, este dice que mi nota es un 1 (lo cual no creo que este correcto) y no hay ningún comentario, ni general ni especifico. Recuerdo haber mandado la tarea en la fecha y hora correcta así que esto no puede deberse a que no la haya entregado. Se que la fecha oficial de la re-corrección es el Martes 6 pero este Lunes 5 me operan de la rodilla y estaré hospitalizada como mínimo hasta el Martes en la noche, por lo que no hay forma de que pueda asistir. Para mi es muy importante esta re-corrección, ya que de esta depende si puedo pasar el curso o no. Si alguien puede ayudarme se lo agradecería mucho.

**Comment by bamavrakis** [comment]
Hola! No hay nadie que pueda ir a recorregir por ti?

**Comment by NoemiCC** [comment]
No, como ya le explique a los ayudantes en jefe, no tengo a nadie que pueda asistir en mi lugar y apelar por mi. Ni mis amigos ni familiares saben de programación.

Enviado desde mi iPhone

**Comment by DiegoAndai** [comment]
@NoemiCC yo creo que voy a ir el martes, si quieres me mandas un mail o hablamos y me explicas lo más que puedas y voy por ti. Avísame 😄
