### ISSUE TITLE
Información inicial de jugadores

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-02/Syllabus#73]
Hola !
Ya leí que la información con la que probarán el código será distinta, pero note que en el ejemplo dado, el usuario Florencia no tiene el item de prograbolas ni el del lugar en donde se encuentra. Asumo que será entregado ? (y si es que no, lo manejo con un try/except y le pongo que partió desde Pallet? ) 

Esto es para evitar que se caiga el código si es que llego a buscar algún "prograbolas" o "lugar" y no esta.

**Comment by srvasquez** [comment]
Según lo que lei en otras issues #57 en el readme tu especifícas como quieres guardar la informacion de los jugadores, el archivo jugadores que nos dieron es solo una pequeña guia.

**Comment by Iruretagoyena** [comment]
Cierto, pero si quieren poblar el sistema con un documento de texto dado, necesito saber que información vendrá o no vendrá, para saber que keys buscar.

**Comment by flobarrios** [comment]
Hola ! Dado que dimos total libertad a como ustedes decidan guardar la infirmación de un jugador, si poblamos el sistema, tenemos que usuar sus propios archivos de texto o hechos por nosotros pero siguiendo estrictamente el estilo de ustedes. Por lo tanto, no es necesario lo que mencionas. Guarda la información de la manera que encuentres más conveniente y sientete tranquilo en que no poblaremos el sistema con archivos que tengan un formato distinto al hecho por ti. Saludos!
