### ISSUE TITLE
Tarea 7

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#731]
No se encuentra mi nota de la tarea 7 y si la subi en la fecha correspondiente y si conteste el cuestionario en el siding :c que hago?

**Comment by narierao** [comment]
PD me paso algo similar con la tarea 6. tuve que hablar con un ayudante para que me la corrigieran.

**Comment by flobarrios** [comment]
Hola! por alguna razón tu tarea no fue recolectada :( La corregiremos ahora!!

**Comment by narierao** [comment]
![image](https://cloud.githubusercontent.com/assets/20784195/20886295/2c477216-bad4-11e6-93af-4d9123c7a42a.png)

**Comment by narierao** [comment]
disculpa que los moleste T.T </3 y gracias  <3
