### ISSUE TITLE
Corrección T07

### ISSUE THREAD

**Issue by Patoulloa** [IIC2233-2016-02/Syllabus#732]
Hola,

Mi T07 aparece con nota 1.0, pese a que hice entrega de la tarea y contesté el cuestionario dentro de los plazos indicados.  Agradecería que pudieran revisar mi caso antes de la recorrección de mañana.

Saludos!

**Comment by agmardones** [comment]
Hola!

Efectivamente tu tarea fue bien recolectada, lo que pasó fue que durante la correción no pudimos  correrla (aún así probando en distintos computadores) y siguiendo tu README. La instancia para recorregir, en caso de que lo necesites, es mañana.

Saludos.
