### ISSUE TITLE
Otro caso Tarea 7

### ISSUE THREAD

**Issue by cjgazali** [IIC2233-2016-02/Syllabus#733]
Perdón, no quiero ser molesto ni parecer chanta, sé que las re correcciones son mañana, pero estoy seguro de que si mi caso se hace desaparecer antes será mejor para los ayudantes y para quienes estén mañana luchando por aprobar el curso, que no es mi caso pero les deseo lo mejor.

Tengo 0.2/1.6 en la parte de estadísticas por un error que al ayudante le aparece con 'likeCount'. Esto no me aparece, y me funciona todo perfecto en todas las listas que consulto, considerando además que el botón para actualizar estadísticas funciona.

Que yo sepa no existen videos con cuenta de likes deshabilitada, por lo que no me explico el error que mencionan en el feedback, considerando que me hago cargo de los videos que no fueron encontrados.

No me imagino cómo esto puede fallar SIEMPRE. Estoy convencido de que incluso si alguna lista arroja error (lo cual no me explico), la gran mayoría al menos debería funcionar perfectamente. Si es posible correr el programa y revisar lo que comento sería fantástico, pues el descuento es gigantesco y mi programa me corre demasiado bien y estaba orgulloso :pensive:.

Si no es posible realizar mi solicitud tendré que ir mañana y lo entiendo pero no quiero hacerles perder tiempo valioso.

Muchísimas gracias.

**Comment by FernandoPieressa** [comment]
Hola!

La instancia para hacer recorrecciones es el dia de mañana 6 de diciembre como ya se dijo varias veces.
Las issues no es el lugar para hacer solicitudes de recorrecciones.

Saludos!
