### ISSUE TITLE
Recorrecion AC

### ISSUE THREAD

**Issue by IgnacioTobar** [IIC2233-2016-02/Syllabus#734]
Hola
Mande a recorregir la AC13 hace un tiempo pero aun no me ha llegado ningún feedback y/o cambio en la nota.  Si alguien pudiera ver que sucede con eso se lo agradecería. Si no, ¿podría al menos pedir mañana que la revisen junto con todo lo demás?

**Comment by jicortes2** [comment]
Hola!
Las notas de la recorrección de esa AC estarán antes de la recorrección masiva de mañana.
Saludos!
