### ISSUE TITLE
Ayudantes 2017-1

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#737]
Hola! cuando uno postula a ser ayudante, eso queda decidido antes de la toma de ramos? necesito saber esto para ver que opciones tengo y poder tomar un TPD para que no se me pase la micro T.T 

eso, los banco mil <3

**Comment by bamavrakis** [comment]
Hola :D 
La mayoría de los ayudantes serán seleccionados para antes de la toma de ramos, aunque puede que corra la "lista de espera" durante las vacaciones.
Saludos!
PD: yo también nos banco mil (uno).
