### ISSUE TITLE
ERROR EN PIP INSTALL

### ISSUE THREAD

**Issue by jdiaztccp** [IIC2233-2016-02/Syllabus#739]
Estimados su apoyo por favor para indicarme cual es el error al instalar un mod ulo por pip install
![image](https://cloud.githubusercontent.com/assets/29032468/26537461/6013b75c-4405-11e7-94e3-a4d3ee6d6bf7.png)

**Comment by aaossa** [comment]
Hola, al parecer estás instalando una *wheel* para Windows de 64 bits en una versión de 32 bits. Intenta instalar la *wheel* de 32 bits.

PS: Este repo es de un curso que actualmente se encuentra cerrado. Para preguntas de este tipo se recomienda buscar por tu cuenta y/o utilizar StackOverflow. Además, este repositorio no contiene código fuente que se relacione con lo que estás usando, así que no corresponde abrir la issue en este repositorio.

Éxito solucionando tu problema :)
