### ISSUE TITLE
Level de los Programones 

### ISSUE THREAD

**Issue by joseluishaddad** [IIC2233-2016-02/Syllabus#75]
Se asume que los programones parten en nivel 0?

**Comment by nrfreudenberg** [comment]
Al elegir un programon inicial, segun el enunciado, debe estar en nivel 5. El resto de los programones tendra un nivel dependiendo de la ruta en la que los encuentres.

**Comment by bvfernandez** [comment]
@nrfreudenberg o sea que si en la ruta1 se tiene un nivel dado por [1,7], debo hacer que en esa ruta aparezca cualquier programón y hacer que este tenga un nivel random entre 1 y 7?

**Comment by Pyralspite** [comment]
@bvfernandez Siempre y cuando no haya conflicto con los niveles de las evoluciones. Por ejemplo, si la ruta es [1,7] puede aparecer un charmander, pero no un charmeleon, ya que este va a tener como nivel mínimo 16 (el nivel en que evoluciona charmander). Del mismo modo, en una ruta [15,20] puede aparecer un charmeleon, pero no un charmander.
