### ISSUE TITLE
Actualizacion de Enunciado

### ISSUE THREAD

**Issue by marcelobordoni** [IIC2233-2016-02/Syllabus#76]
Hola, Quisiera saber si es posible subir un nuevo enunciado con las correcciones y/o aclaraciones (sobre la tarea) que se han hecho en esta pagina, debido a que ya van casi 80 issues y sus respectivos comentarios, después de haber leído todas ellas es fácil que se nos olvide algún detalle importante.

Gracias...

**Comment by flobarrios** [comment]
Hola! no se actualizará el enunciado ya que para ustedes sería muy difícil notar donde se hicieron los cambios. En cambio, marcaremos las issues que aclaren partes del enunciado con el label IMPORTANTE. Para poder buscar estas issues, en el buscador debes poner:

```
label:IMPORTANTE label:"Tarea 1"
```

Te dejo una imagen:

![screen shot 2016-08-18 at 8 43 36 am](https://cloud.githubusercontent.com/assets/11543803/17772437/4138cd74-651f-11e6-942a-460f721c18f8.png)

Saludos!
