### ISSUE TITLE
Pelea contra entrenador

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#77]
Como elige programon un entrenador? Puedo solo hacerlo en orden, i.e. el entrenador no cambia de programon ? o tengo que crear un random tambien para ver si elige cambiarlo en vez de atacar?

**Comment by andresbannuraschultz** [comment]
y otra duda, entre entrenadores si se reestablecen los stats o no? se consideran peleas independientes no cierto?

**Comment by flobarrios** [comment]
hola! como se elige un programón queda a tu criterio y debes especificarlo en el README. Por lo segundo sí, se restablecen los stats de los programones (junto con los pp de los movimientos de cada uno) luego de cada batalla. Saludos!

**Comment by ofvera** [comment]
los pp de los movimientos en el juego real se restablecen cuando los llevan al centro pokemon eso si, puedo especificar eso si lo hago asi?
