### ISSUE TITLE
jugadoresEjemplo.json

### ISSUE THREAD

**Issue by smargozzini** [IIC2233-2016-02/Syllabus#79]
no entiendo para que sirve este ejemplo (jugadoresEjemplo.json), nosotros debemos guardar así un jugador después de ser creado? de ser así de donde sacamos cual fue la ultima ubicación de ese jugador en el mapa?
o podemos guardarlos de otra forma y así podemos incluir su ultima ubicación en ese archivo
gracias

**Comment by FernandoPieressa** [comment]
Hola! Puedes guardarlos como gustes mientras especifiques en el readme! La idea era dar un ejemplo de la estructura de como debes hacerlo.

Saludos!

**Comment by fabraghetto** [comment]
@FernandoPieressa una pregunta... al correr el programa debemos cargar algún archivo como "jugadoresejemplo.json" o partimos desde cero con todos los jugadores?

**Comment by bvfernandez** [comment]
@FernandoPieressa una pregunta... al correr el programa debemos cargar algún archivo como "jugadoresejemplo.json" o partimos desde cero con todos los jugadores?

**Comment by FernandoPieressa** [comment]
@bvfernandez

La idea es crear un archivo como ese para poder cargar la informacion y tambien para poder guardar los cambios y avances de un jugador para la proxima vez que lo use, Saludos!
