### ISSUE TITLE
Ejercicio clonar repositorio y subir archivo

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233-2016-02/Syllabus#8]
Hola!

Ya cloné mi repositorio, pero no estoy seguro de haberlo clonado en la carpeta PrograAvanzada que tengo. Lo digo porque en el ejercicio siguiente, al intentar agregar el archivo hola.txt al stage usando el comando “git add hola.txt” me dice
“fatal: Not a git repository (or any of the parent directories): .git”

Tanto el archivo hola.txt como el Terminal los puse en la carpeta PrograAvanzada...no se si eso tendrá algo que ver.

**Comment by aaossa** [comment]
Estas seguro de que estás dentro de la carpeta que clonaste? El error dice que no es así. Si no me equivoco deberías haber hecho algo mas o menos así

```
git clone <something something> "CualquierNombre"
cd CualquierNombre
# Creas un archivo en la carpeta
git add <mi archivo>
...
```

**Comment by sebacruzd** [comment]
En la consola debes estar en la direccion de la carpeta, para eso usa 'cd "nombre siguiente carpeta"' para aumentar un nivel la dirección y 'cd..' para bajar un nivel. Al estar en la carpeta que quieres que sea el repositorio local tienes que poner 'git init' antes de hacer algun add o commit, ojalá te funcione!

**Comment by bedefrunner** [comment]
Hice lo que dijo @aaossa y ahora estoy bastante seguro de que hice la clonacion de manera correcta, pero me ocurre que luego de crear el archivo hola.txt en la carpeta, pongo
"git add hola" (tambien probé con git add hola.txt y el resultado es el mismo)
y me dice
“fatal: pathspec 'hola.txt' did not match any files” 
También intenté poniendo "git init" antes de hacer el add, pero el resultado es el mismo.

**Comment by jgmontoya** [comment]
@federicobrunner 

Cuando haces 

```
git add hola.txt
```

Tienes que estar en el directorio donde está el archivo 'hola.txt'.
Por ejemplo:
Supongamos tengo la siguiente estructura de directorios:
/
/repo
/repo/prueba
 Si el archivo "hola.txt" está dentro de la carpeta prueba (que a su vez está dentro de la carpeta repo) entonces tendré que moverme hasta esa ubicación (/repo/prueba) y una vez que esté ahí podré utilizar el comando git add "hola.txt".

Para navegar por los directorios usando la consola puedes usar los siguientes comandos:

```
ls (listar lo que hay en el directorio actual)
cd <directorio_hijo> (moverse a directorio_hijo)
cd .. (moverse al directorio padre)
```

En el ejemplo, si al abrir la consola me encuentro en / entonces una opción será como sigue:

```
/> cd repo
/repo> cd prueba
/repo/prueba> git add "hola.txt"
```

También puedes moverte más de un directorio:

```
/> cd repo/prueba
/repo/prueba> git add "hola.txt"
```

Saludos!

EDIT:

También puedes pasarle el path completo al git add:

```
/> git add prueba/hola.txt
```

**Comment by cglevican** [comment]
Respecto al repositorio donde se subiran las tareas tiene que tener algun nombre en especial?

**Comment by cglevican** [comment]
Y otra pregunta, ¿qué es el staging area?

**Comment by Marivera3** [comment]
Staging Area:
A place where we can group files together before we "commit" them to Git.

**Comment by aaossa** [comment]
@cglevican Hoy en la noche creare sus repos en la organizacion. No se preocupen por eso :D

**Comment by aaossa** [comment]
@cglevican Efectivamente _staging area_ es lo que indica @Marivera3 . Si mañana alguien sigue con dudas sobre git, o comandos, o lo que sea preguntele a cualquier ayudante que pillen en la sala :grin:

**Comment by bedefrunner** [comment]
@jgmontoya hice lo que me dijiste y todo va bien, pero cuando pongo git add "hola.txt" me dice 
"fatal: pathspec 'hola.txt' did not match any files", siendo que hola.txt sí está en el directorio en el que estoy trabajando

**Comment by tcgarrido** [comment]
Hola @federicobrunner, tuve el mismo problema. Mi carpeta está el en escritorio. Puse el archivo en la carpeta y luego en el terminal cd Desktop -> cd micarpeta -> git add hola.txt. Jeje no sé si lo hice bien pero al poner git status me aparece el mensaje "cambios para hacer commit", hasta ahí funciona al menos.

**Comment by iqacevedo** [comment]
¿Aun no están creados todos los repositorios verdad?, no encuentro el mio

**Comment by bedefrunner** [comment]
Gracias! Me funcionó jaja

**Comment by aaossa** [comment]
Aún no @iqacevedo , el ayudante responsable recibirá las penas del infierno por el retraso
