### ISSUE TITLE
Acciones del sistema batalla

### ISSUE THREAD

**Issue by DiegoAndai** [IIC2233-2016-02/Syllabus#80]
Hola! hace mucho tiempo que no juego pokemon y no me acuerdo: Si el programon enemigo es más rápido y por lo tanto empieza atacando ese turno, ¿el entrenador elige que hacer (atacar, cambiar de programon, huir) antes o después que el oponente haya atacado? 

 En el enunciado dice:

<img width="699" alt="captura de pantalla 2016-08-18 a las 12 46 45 a m" src="https://cloud.githubusercontent.com/assets/16889233/17761369/db529522-64dc-11e6-877f-a93a71f37f52.png">

Pero no me queda claro si se elige inmediatamente antes de la acción o no.

Muchas gracias.

**Comment by flobarrios** [comment]
Hola! no entiendo muy bien tu pregunta, por entrenador te refieres al jugador (que inició sesión) o al entrenador de algún gimnasio?. Si es lo primero, el jugador elige que hacer después de ser atacado por el programón oponente (en caso de que este sea más rápido y por tanto comience la batalla).

**Comment by DiegoAndai** [comment]
Exacto, eso era 😁 Muchas gracias.
