### ISSUE TITLE
Defensa programones

### ISSUE THREAD

**Issue by lefischer** [IIC2233-2016-02/Syllabus#81]
Hola,

Entiendo que en la lista de movimiento de ataque se encuentran los especiales y lo normales, lo que no entiendo es cuando se usa defenza especial y cuando la normal.

**Comment by flobarrios** [comment]
Hola! si el ataque es especial, el otro programón se defiende con defensa especial.

**Comment by ghost** [comment]
y si el programón que defiende no tiene defensa especial?

**Comment by Nebula2028** [comment]
mmm según yo eso no debería pasar. defensa_especial es de los stats que deberían tener TODOS los programones. quiza puede haber algun error por ahi, pero segun mi parser todos tienen def_esp

**Comment by mjjunemann** [comment]
@elliot-anderson  como dice @Nebula2028 , eso no debería pasar porque ustedes a partir del IV, EV deben generar todos los stats del programón , y estos nunca van a ser 0 , en caso de es un error del archivo , pero creo que no se nos paso.
