### ISSUE TITLE
definir ataque critico

### ISSUE THREAD

**Issue by narierao** [IIC2233-2016-02/Syllabus#82]
Cuando aparece la posibilidad de relizar un ataque critico se da por una formula que contiene BaseSpeed, esto correponde a la velocidad del pokemon que ejecuta el ataque?

**Comment by flobarrios** [comment]
Si!! 😄

**Comment by cjgazali** [comment]
Entiendo que se refiere a la velocidad base, la que nos dan en el archivo programones.json. Me parece extraño... ¿es así?

**Comment by flobarrios** [comment]
Es así. Saludos!
