### ISSUE TITLE
Dudas sobre json

### ISSUE THREAD

**Issue by andresbannuraschultz** [IIC2233-2016-02/Syllabus#83]
Creo un diccionario con una key de type int. Al hacer dictToJson y luego jsonToDict, en el diccionario que retorna esta ultima, la key es un string. Se asume entonces que las keys de un diccionario creado a partir de un object en formato json siempre tendran keys de tipo str? Gracias.

**Comment by flobarrios** [comment]
Hola! si, las keys de un archivo json siempre serán strings.

**Comment by andresbannuraschultz** [comment]
gracias!
