### ISSUE TITLE
[Tarea 1] revision con otros json

### ISSUE THREAD

**Issue by roy350** [IIC2233-2016-02/Syllabus#84]
Disculpen pero en una issues lei que las ciudades no estaria necesariamente en el orden que estan en el json q nos dieron, mi pregunta es si tendran los mismos nombres?

**Comment by flobarrios** [comment]
Hola! no necesariamente, la idea es que cargues toda la información a partir de los archivos entregados. Saludos!

**Comment by roy350** [comment]
Gracias! y otra pregunta entonces los archivos routes.json y gyms.json que usaran para revisarnos tendrian una conexion igual que los arvhciso que nos dieron? , en el sentido que  se tiene en el routes.json ,"starting_point": "Pallet Town", "destination": "Viridian City", y en el gyms.json "city": "Viridian City", "id": 1, osea que indique que la ciudad del id:1 sera la primera ciudad con gimnasio, la del id:2 la segunda y asi?

**Comment by flobarrios** [comment]
Si eso si !

**Comment by roy350** [comment]
Muchas gracias :D

**Comment by roy350** [comment]
disculpa respecto al mismo tema en los archivos que usaran para revisarnos en el gyms.json en la seccion de "trainers", este siempre sera una lista con "name" y "programones" en ese orden?

**Comment by roy350** [comment]
Hola soy yo de nuevo :(, disculpa pero me surgió la duda si es que en numero de Trainers siempre ira de 1 a 4 dependiendo del gimnasio o en los archivos que nos darán habrá mas de 4 entrenadores?

**Comment by jgmontoya** [comment]
Hola,

#69 #66 #42 

(La cantidad tanto de ciudades como de entrenadores es arbitraria)

**Comment by roy350** [comment]
Disculpen pero en el archivo "programones.json" que uds van a utilizar podemos asumir que los id de los programones que evolucionan están en forma ordenada?
por ejemplo: en nuestro archivo charmander tiene id 4, charmeleon id 5 y charizard id 6, no pasara que charmander tiene id 4 squirtle id 5 charmeleon id 6? no se si se entiende mi pregunta

**Comment by jgmontoya** [comment]
No puedes asumir eso. La información necesaria ya está en "evolveTo" y no debiera importar realmente si el id de la evolución es mayor o menor.
