### ISSUE TITLE
Actualizacion de stats + pp

### ISSUE THREAD

**Issue by ceyzaguirre4** [IIC2233-2016-02/Syllabus#85]
Como dice el titulo no me queda claro cuando debieran reestablecerse los stats/pp de los programones. Abajo hago una lista de lo que me hace sentido, para que confirmen y/o hagan cambios.
1.- Luego de cada pelea contra un programon salvaje se reestablecen stats y pp (independiente de si se atrapo, gano, perdio, huyo)
2.- luego de vencer a un entenador: me queda la duda de si se reestablecen despues de vencer a cada programon del entrenador, despues de vencer a todos los programones de un entrenador, o despues de vencer a todos los enternadores + lider de un gimnasio. O quizas hay circunstancias bajo las cuales no se reestablecen para cada caso, ie., si se vence a solo un programon de el entrenador y luego se huye.

**Comment by FernandoPieressa** [comment]
Hola! Es despues de cada batalla, es decir, despues de vencer a todos los programones de un entrenador/lider o terminar una batalla con un programon salvaje
