### ISSUE TITLE
Progradex

### ISSUE THREAD

**Issue by tafuenza** [IIC2233-2016-02/Syllabus#86]
La informacion que debe aparecer en la progradex segun el enunciado deben ser todos los stats de los programones, sus movimientos etc.... Debe aparecer la informacion base? no la informacion calculada segun el nivel?
Otra cosa en que formato debe aparecer esta informacion? en el mismo que nos lo entregan en los archivos .json

Gracias

**Comment by jgmontoya** [comment]
Revisar #36
