### ISSUE TITLE
letra ñ

### ISSUE THREAD

**Issue by mraddatz** [IIC2233-2016-02/Syllabus#87]
Se pueden utilizar variables con la letra "ñ"?

**Comment by aaossa** [comment]
De preferencia **no**. Casi como convención, **todo lo que es código se escribe en inglés**, por lo que no deberías usar la letra "ñ". Además, podrían haber problemas de encoding al correrlo o si lo corre alguien más.

En resumen, anda despidiéndote de la letra "ñ" :cry:
