### ISSUE TITLE
consultas jugador

### ISSUE THREAD

**Issue by rolfskog** [IIC2233-2016-02/Syllabus#88]
Hola, cuando el jugador elige la opcion consultas: batalla por programon involucrado, una batalla victorioso seria cuando mi programon derrota a otro o la victoria se refiere a cuando se derrota a todos los progamones del enemigo y esta se asigna a todos los que participaron.

**Comment by flobarrios** [comment]
Hola! es lo segundo, una batalla se da por finalizada cuando se derrota a todos los programones del enemigo. Saludos!
