### ISSUE TITLE
[Tarea 1] Tipo, Crítico en modificador

### ISSUE THREAD

**Issue by lampuerov** [IIC2233-2016-02/Syllabus#89]
Hola, en el sistema de batallas se especifica que el valor de tipo en el modificador toma valores 0, 0.5, 1 o 2 dependiendo del tipo de ataque y el tipo del programon defensor, mi pregunta es: ¿cuándo asigno cada valor?.  La otra duda de enunciado es a quién pertenece BaseSpeed en el cálculo de Crítico, ¿al programon atacante o al defensor?. Saludos!

**Comment by jgmontoya** [comment]
Hola, 
- Tal como se dice en el enunciado la  información del tipo está en el archivo types.json
- Respecto a los críticos, corresponde al BaseSpeed del programón atacante

Saludos

**Comment by lampuerov** [comment]
Gracias!
