### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by NoemiCC** [IIC2233-2016-02/Syllabus#9]
- **Sistema Operativo:** Mac osx
- **Programa a instalar:** Git
- Foto del error:
  ![2016-08-03 17 57 52](https://cloud.githubusercontent.com/assets/20797815/17383558/8cead900-59a4-11e6-825d-2004d549056e.jpg)
- Descripción del problema: al intentar ejecutar los comandos pedidos (git config --global user.name "Nombre Apellido") recibo un mensaje de error que dice "Segmentation fault: 11" o "illegal instruction: 4"

**Comment by aaossa** [comment]
Puedes ver que version de git tienes instalada?

```
git --version
```

**Comment by NoemiCC** [comment]
No me deja usar el comando, me manda el mismo error, pero según la descarga es 2.9.2

**Comment by aaossa** [comment]
Y que version de OSx tienes? Quizas no es una reciente, por lo que tendrias que intentar instalando una version anterior de git o haciendo upgrade de tu OS

**Comment by NoemiCC** [comment]
Tengo la version 10.7.5

**Comment by NoemiCC** [comment]
Ok, ya encontré una versión que funciona, gracias.

**Comment by aaossa** [comment]
Ejalé :D
