### ISSUE TITLE
[Tarea 1] IV Pokemones

### ISSUE THREAD

**Issue by Genaron** [IIC2233-2016-02/Syllabus#90]
Quería saber si el pokemon inicial que un jugador elige (Bulbasaur, Charmander o Squirtle) tiene un IV en específico o si se elige un valor aleatorio al igual que los pokemones salvajes. Lo mismo para los pokemones de los entrenadores de los gimnasios, porque no tiene mucho sentido que el pokemon de un entrenador pueda ser más fuerte o débil según cuándo decido enfrentarme con él.

**Comment by jgmontoya** [comment]
Hola!
- El IV del pokemon inicial funciona igual que al atrapar un pokemon nuevo, es decir es un valor aleatorio dentro de los rangos especificados.
- En el caso de los entrenadores, como estos son los mismos para los diferentes usuarios, entonces se debe mantener el iv calculado para estos. Es decir se calcula una vez y luego reutilizas los valores. 
  - Queda a tu criterio si quieres calcular los iv de los entrenadores al iniciar el juego, al encontrar un entrenador por primera vez, al  entrar al gimnasio, etc.. pero debes especificarlo en el readme.

Saludos!

**Comment by Pyralspite** [comment]
Hola, respecto al tema de los entrenadores, no entendí si los valores deben mantenerse para cada jugador en forma independiente o si una vez que se establecen en una sesión debe compartirse también en las otras.

**Comment by jgmontoya** [comment]
Debe compartirse, es decir dos usuarios distintos enfrentarán a los mismos pokemones de entrenadores.

**Comment by Genaron** [comment]
¿Y lo mismo aplica para el EV de cada uno?

**Comment by jgmontoya** [comment]
Sí, el EV funciona de igual manera que el IV.
