### ISSUE TITLE
[Tarea 1] termino de batalla

### ISSUE THREAD

**Issue by roy350** [IIC2233-2016-02/Syllabus#91]
Dsiculpen pero en el enunciado dice que si se termina una batalla el jugador gana 200 yenes eso vale tambien para los programones salvajes o solo si es un batalla con entrenador?

**Comment by jgmontoya** [comment]
Hola,

Eso vale para todas las batallas, independiente de si se trata de pokemones salvajes o de batallas con entrenadores.

Saludos!

**Comment by roy350** [comment]
muchas gracias! y en el enunciado dice que al terminar de la batalla todos los programones al salir de la prograbola suben un nivel eso tambien vale para los programones que fueron derrotados o solo los que quedaron vivos?

**Comment by cjgazali** [comment]
Una duda relacionada: cuando un programon propio llega a hp cero, es decir, es derrotado, ¿se "muere"? ¿Lo perdemos, o también se deben resetear sus stats a como estaban antes de la batalla simplemente?

PD: quizás @roy350  quiso decir: "En el enunciado dice que al terminar la batalla todos los programones que salieron de la prograbola suben un nivel. ¿Eso también vale para los programones que fueron derrotados o solo los que quedaron vivos?"

**Comment by alainrochette** [comment]
Si arranco de una batalla salvaje, todavía se le agrega a la lista "batallas"?

**Comment by flobarrios** [comment]
@roy350 vale para todos los programones que participaron en la batalla (vivos y derrotados).
@cjgazali se resetean sus stats, los programones nunca mueren 💪.
@alainrochette no, solo se consideran batallas completadas (perdidas o ganadas).

**Comment by roy350** [comment]
@flobarrios disculpa pero si yo ya lo hice considerando que solo suben de nivel los vivos, puedo ponerlo en el readme es que me costo caleta hacerlo :(

**Comment by flobarrios** [comment]
@roy350 si, pero especifícalo en el README!
