### ISSUE TITLE
Erorres al jugar el juego

### ISSUE THREAD

**Issue by tafuenza** [IIC2233-2016-02/Syllabus#92]
Una duda, puedo asumir que la persona que esta jugando es inteligente y no va a cometer errores del tipo:
[1] Si quieres comer
[2] Si quiere jugar
[3] Si quiere hablar
y la persona mande una "j", tengo que en cada menu, hacer la excepcion si la persona que esta jugando no retorna el caracter que le estoy pidiendo??
En resumen, puedo asumir que la persona que juega no se va a equivocar?

**Comment by fgvenegas** [comment]
Así como te equivocaste en escribir el título de la issue(con cariño <3), no puedes asumir que la persona que juega no se va a equivocar

**Comment by Genaron** [comment]
Hay un ejemplo de cómo evitar que eso pase en el material de clase (me parece que el primer o segundo tema). Busca la parte donde se define la clase Menu y ve cómo se ejecuta (es fácil de entender y se ocupa mucho en esta tarea).
