### ISSUE TITLE
Programones con misma speed ?

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2233-2016-02/Syllabus#93]
Qué hacemos cuando dos programones tienen la misma Speed ? Quién parte ?
Gracias!

**Comment by jgmontoya** [comment]
Hola,

Ese caso queda a su criterio, deben explicitar su decisión en el readme.
Solo a modo de referencia, en los juegos de pokemon en estos casos se decide al azar quien parte.

Saludos!

**Comment by Iruretagoyena** [comment]
Gracias !
