### ISSUE TITLE
Problema con algunos id

### ISSUE THREAD

**Issue by lukasquense** [IIC2233-2016-02/Syllabus#94]
Puede ser que algunos programones tengas id's distintos a los que se dan en el archivo  gyms.json? Al leer el id que tienen los programones de los entrenadores, no los encuentra en el archivo programones y hay problema para cargarlo...

**Comment by jgmontoya** [comment]
Hola, 

Como se mencionó hace unos días en #39 se actualizó el archivo con los programones que faltaban. Asegúrate de estar usando la versión más actualizada de este haciendo _pull_ nuevamente.

Saludos!
