### ISSUE TITLE
Requisitos para avanzar a la siguiente ciudad

### ISSUE THREAD

**Issue by vacodoceo** [IIC2233-2016-02/Syllabus#95]
Cuales son los requisitos para avanzar a la siguiente ciudad? Solo haber ganado la medalla del gimnasio actual?

**Comment by jgmontoya** [comment]
Por favor revisar las issues antes de preguntar. Ya se ha dado respuesta a esto en #31

**Comment by vacodoceo** [comment]
no me fije que habia una seccion de issues cerrados :c perdon !
