### ISSUE TITLE
Pokedex, capturado y visto?

### ISSUE THREAD

**Issue by jbsaeza** [IIC2233-2016-02/Syllabus#96]
Cuando un programon es visto (queda guardado en la pokedex como visto), pero otro programon con el mismo id (especie) es capturado, en la pokedex pasa a ser capturado pero debemos mostrarlo como un programon capturado y visto, o solo capturado?

**Comment by jgmontoya** [comment]
Un pokemon capturado necesariamente tiene que haber sido visto, no tienes que listarlo dos veces (es decir queda solo como capturado).
