### ISSUE TITLE
[Tarea 1] Setup

### ISSUE THREAD

**Issue by Kitaps** [IIC2233-2016-02/Syllabus#97]
Hola una duda, el setup se supone que lo corren al momento de corregir o pueden estar los diccionarios y otros files que se necesiten para correr bien el programa ya hechos?

En caso de que el setup no pueda estar hecho, puede ser que en el Readme.md se den instrucciones del orden de como habría que correr los distintos programas para que funcione bien?

**Comment by jgmontoya** [comment]
Hola,

No entendí lo que querías decir, ¿Podrías re-formular tu pregunta y dar más detalles de lo que quieres saber?

**Comment by Kitaps** [comment]
sry,
Aver, que por ejemplo tengo el diccionario de ataques pokemon, que lo hago con la funcion JasontoDic.
Entonces mi duda es, si esa funcion la puedo correr yo y guardar el archivo de texto para que uds al corregir solo corran el programa de juego o no.

En caso de que no mi segunda duda es que si es que tiene que ejecutarse la creacion del archivo/diccionario cada vez que se corre el codigo principal o si puedo meter instrucciones en el Readme.md que digan por ejemplo: 
1.-Corre el archivo JasontoDic
2.-....
3.-De ahora en adelante el archivo de juego que se ejecuta desde main debería funcionar.
algo así

**Comment by fvr1** [comment]
y no podrías importa esos módulos al main y ahí correr las funciones que necesitas?

**Comment by jgmontoya** [comment]
Hola!

Tal como te dice @fvr1 puedes correr las funciones que necesitas en el main y luego correr el juego en la misma ejecución.
Explica el funcionamiento en el readme y no debieras tener problemas!

**Comment by Kitaps** [comment]
Pero si lo hago así cada vez que corra el juego va a crear los diccionarios de nuevo (los archivos.txt)
No importa?

**Comment by aaossa** [comment]
Puedes revisar si dicho archivo existe antes de crearlo. Si existe no lo creas de nuevo

**Comment by Kitaps** [comment]
smart jajajaja
