### ISSUE TITLE
Problema de modularización

### ISSUE THREAD

**Issue by gabrielpinkman** [IIC2233-2016-02/Syllabus#99]
Hola, estoy desesperado, mi implementación arroja un error constante y que no entiendo bien; en StackOverflow ni siquiera sale el problema.

Tengo un archivo llamado "Clases_miscelaneo.py" que tiene la clase Jugador, con los atributos correspondientes. Desde otro archivo (al cual ya llamé "main.py") importo el primer archivo poniendo: import Clases_miscelaneo as cm

El problema es que al crear una instancia de la clase Jugador en el archivo "main" escribo
a = cm.Jugador(atributos) y me arroja el error: 
AttributeError: module 'Clases_miscelaneo' has no attribute 'Jugador'

¿Estoy haciendo algo mal? Este error me está quitando mucho tiempo de la tarea y no logro solucionarlo, también intenté hacer la prueba con clases que no tenian que ver con la tarea y obtengo el mismo error (con otros nombres claramente).

AYURAMECHIAVE

**Comment by fvr1** [comment]
Sube tu tarea a tu repo para poder ver que podría ser!
